### ISSUE TITLE
How to disable/ignore update warning when calling Lando from scripts?

### ISSUE THREAD

**Issue by dsnopek** [lando/lando#1000]
So, we have a bunch of scripts that call `lando` and parse it's output, for example:

- `lando info`
- `lando drush pm-list --format=json`

However, when there's a new Lando update available, the update message gets put before the JSON and breaks parsing.

Is there a way to disable the warning entirely when running from a script? Or, if the message was output on stderr, then it could still be shown, but the stdout will be clean, parseable JSON.

Just encoutered this again because there was just a release a little bit ago :-)

**Comment by dsnopek** [comment]
I'm not aware of a CI that fails just because there's something output on stderr, most usually look at the exit code, but if there was such a CI you could just run redirect stderr somewhere, for example:

```
lando info 2>/dev/null
```

**Comment by dustinleblanc** [comment]
You're probably right, my fear was likely unneeded 😆 

I like the idea of dumping it to stderr as a way of seperating the output but pretty much always making sure it shows up (the main reason there really isn't a way to turn it off).

**Comment by pirog** [comment]
This has been changed in forthcoming RC2. The update warning will now be sent to `stderr`

**Comment by dsnopek** [comment]
Awesome, thanks!

**Comment by heitoralthmann** [comment]
Hi guys.

First of all, thank you for the awesome work in here. Lando is a tool that I use on a daily basis and just makes my life so much easier!

Second, I wonder if there's a way to hide the lando update warning by these days?

It's boring to have such a big warning message popping up every time I need to run a lando command.

Just wanna be free to decide when to do the update without getting big verbose outputs all the time.

Thank you.

**Comment by pirog** [comment]
@heitoralthmann the best way to disable the update warning is to update. this helps our team out quite a bit. that said, i assume you are asking about _another_ way to disable the warnings. You can set the release channel to "none" to stop getting update warnings. Read the docs:
https://docs.lando.dev/config/releases.html#release-channels

Note that we dont support people on older versions so its a good idea to stay current

**Comment by heitoralthmann** [comment]
Hi @pirog! Thank you for taking the time to answer my question.

Sure, I understand that being up to date is always the best way to go.

It's just that I've had bad experiences in the past while trying to update lando, in a way that the only way I could get my environment back to work was to completely remove lando + Docker and then installing it from scratch again.

That means removing all my projects and starting them over, which ends up taking quite some time to accomplish.

As when an update comes out I'm working on multiple projects, I always prefer to leave those for when I'm in low activity periods, so if anything goes wrong, fixing the problem does not interfere with my work.

I am just detailed my personal scenario so you get to know a little more about your different users' use cases/reasons.

Thank you.

**Comment by pirog** [comment]
@heitoralthmann your use case is why we have a `none` setting to the `--channel` option. Lando has not been stable until very recently so that updating experience is expected. I'd encourage you to read through the 3.0.0 post to get a better idea on what is to come
https://blog.lando.dev/2020/06/22/lando-3-0-0/

**Comment by pfrenssen** [comment]
For the lazy who do not want to read the blog post above, the command to disable the update checks is

```
$ lando --channel none
```
