### ISSUE TITLE
lando-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by MSBuV** [lando/lando#1001]
Bug Report
==========

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

 v3.0.0-beta46 on Windows 10 Professional with Docker Version 17.12.0-ce-win47 

**Tell us about your `.lando.yml`**

```yml
name: test
recipe: drupal8
config:
  webroot: .
  drush: global:8.1.15
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

```bash
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Starting test_database_1 ...
Starting test_appserver_1 ... error

ERROR: for test_appserver_1  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/lando-entrypoint.sh\": stat /lando-entrypoint.sh: no such file or directory": unknown

ERROR: for appserver  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/lando-entrypoint.sh\": stat /lando-entrypoint.sh: no such file or directory": unknown
Encountered errors while bringing up the project.
test_database_1 is up-to-date
Starting test_appserver_1 ... error

ERROR: for test_appserver_1  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/lando-entrypoint.sh\": stat /lando-entrypoint.sh: no such file or directory": unknown

ERROR: for appserver  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/lando-entrypoint.sh\": stat /lando-entrypoint.sh: no such file or directory": unknown 
Encountered errors while bringing up the project.

```

**Tell us generally about your bug**

I run lando start on a cloned Drupal 8.5.3 site and get the errors above.

```bash
1. Git clone Drupal 8.5.3
2. Paste lando.yml from above, same for lando init with Drupal 8 recipe
3. Run lando start
```

**Tell us more**

I had to switch from 18.03.1-ce-win65 of Docker to 17.12.0-ce-win47 of Docker, because "export COMPOSE_CONVERT_WINDOWS_PATHS=1" did not solve my "not a valid Windows path" error, like it did for everyone else here: 
https://github.com/docker/for-win/issues/1829
With 17.12.0-ce-win47 I now get the error above, both with a pasted lando.yml or using lando init.

**Comment by dustinleblanc** [comment]
Hi @MSBuV! That error almost sounds like Volume mapping isn't working, which is something that can happen on Windows quite frequently it seems. You are presented with a little permissions thing when Docker for Win starts up that asks to mount some folders and I've seen the notice kind of get hidden on multiple user's machines, I'd recommend seeing if you can get vanilla docker/compose to work just to be sure, turn docker off/on, reinstall if needed, make sure you have enough disk space mounted for docker, etc.

**Comment by MSBuV** [comment]
Should Docker ask for the user password again after I've uninstalled 18.03.1 and installed 17.12.0?
The permission window appeared when I installed the older version, but when I clicked on "Share" I didn't have to enter my password like I did originally.

**Comment by dustinleblanc** [comment]
@MSBuV good question! That sounds related to what I've seen. I imagine this would normally ask for permissions, but its possible it doesn't need to if it already did once?

**Comment by MSBuV** [comment]
So far I tried:
- factory settings reset: I had to confirm the permission window and enter my password again, but the same error appeared
- uninstalled Lando and Docker, installed Docker 17.12.0 first then Lando beta 46 alone. Permission window without password confirmation appeared, same error.
- installed Lando with Docker 18.03.1-ce-win65 selected, but that returns the "not a valid windows path"-error:
```bash
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
test_database_1 is up-to-date
Creating test_appserver_1 ... error

ERROR: for test_appserver_1  Cannot create container for service appserver: b'Mount denied:\nThe source path "/c/Users/User/Desktop/Sites/test/C:\\\\Users\\\\User\\\\.lando\\\\services\\\\config\\\\drupal8\\\\php.ini"\nis not a valid Windows path'

ERROR: for appserver  Cannot create container for service appserver: b'Mount denied:\nThe source path "/c/Users/User/Desktop/Sites/test/C:\\\\Users\\\\User\\\\.lando\\\\services\\\\config\\\\drupal8\\\\php.ini"\nis not a valid Windows path'
Encountered errors while bringing up the project.
test_database_1 is up-to-date
Creating test_appserver_1 ... error
```
That is after running "export COMPOSE_CONVERT_WINDOWS_PATHS=1" with Git Bash in the "test"-folder.
Not sure what to try next.

**Comment by MSBuV** [comment]
@dustinleblanc I think that's a bug with beta 46. If I run beta 45 with 17.12.0-ce-win47 of Docker (Docker installed first, then Lando and Git together), I can start up projects, but once I upgrade to beta 46 running the .exe installer, I get the error from my original post.

**Comment by dustinleblanc** [comment]
Good to know @MSBuV, we'll have to look for a regression

**Comment by pirog** [comment]
*pretty sure* this is the same as #1004 so going to close and redirect there. we are def working to get a hotfix out for this asap though!

**Comment by redhawk527** [comment]
Hey all, I'm helping a colleague get up and running on a Windows 10 Pro machine. Is this issue resolved?

**Comment by pirog** [comment]
As far as we know!
