### ISSUE TITLE
ERROR: for index Cannot create container for service index: b'Mount denied:\nThe source path ... \nis not a valid Windows path'

### ISSUE THREAD

**Issue by RichardDavies** [lando/lando#1004]
Bug Report
==========

**Tell us about your setup**

Lando v3.0.0-beta.46 on Windows 10 Professional 

**Tell us about your `.lando.yml`**

```yml
name: portlandor3
recipe: pantheon
config:
  framework: drupal8
  site: portlandor3
  id: 5c6715db-abac-4633-ada8-1c9efe354629
framework: drupal8
xdebug: true
services:
  appserver:
    xdebug: true
    config:
      conf: xdebug.ini
drush: composer
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

```bash
lando start -- -vvvv
verbose: Running spawn C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe with args ["--project-name","portlandor3","--file","C:\\Users\\csrichardd\\.lando\\compose\\portlandor3\\portlandor3-2.yml","--file","C:\\Users\\csrichardd\\.lando\\proxy\\portlandor3-proxy-3.yml","up","-d","--remove-orphans"]
debug: In mode collect with detached false
debug: With env ALLUSERSPROFILE=C:\ProgramData, APPDATA=C:\Users\csrichardd\AppData\Roaming, ChocolateyInstall=C:\ProgramData\chocolatey, ChocolateyLastPathUpdate=Wed Jan 31 15:13:00 2018, CommonProgramFiles=C:\Program Files\Common Files, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, CommonProgramW6432=C:\Program Files\Common Files, COMPOSE_CONVERT_WINDOWS_PATHS=1, COMPUTERNAME=WS19793, ComSpec=C:\WINDOWS\system32\cmd.exe, DEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection, FP_NO_HOST_CHECK=NO, HOMEDRIVE=C:, HOMEPATH=\Users\csrichardd, LANDO=ON, LANDO_APP_NAME=portlandor3, LANDO_APP_ROOT=C:\Users\csrichardd\Sites\portlandor3, LANDO_APP_ROOT_BIND=C:\Users\csrichardd\Sites\portlandor3, LANDO_CONFIG_DIR=$LANDO_ENGINE_CONF, LANDO_DOMAIN=lndo.site, LANDO_ENGINE_CONF=C:\Users\csrichardd\.lando, LANDO_ENGINE_GID=1000, LANDO_ENGINE_HOME=C:\Users\csrichardd, LANDO_ENGINE_ID=1000, LANDO_ENGINE_IP=127.0.0.1, LANDO_ENGINE_REMOTE_IP=host.docker.internal, LANDO_ENGINE_SCRIPTS_DIR=C:\Users\csrichardd\.lando\engine\scripts, LANDO_HOST_GID=1000, LANDO_HOST_IP=host.docker.internal, LANDO_HOST_OS=win32, LANDO_HOST_UID=1000, LANDO_INSTALL_PATH=C:\Program Files\Lando, LANDO_WEBROOT_GID=33, LANDO_WEBROOT_GROUP=www-data, LANDO_WEBROOT_UID=33, LANDO_WEBROOT_USER=www-data, LOCALAPPDATA=C:\Users\csrichardd\AppData\Local, LOGONSERVER=\\ROSEAD1, NUMBER_OF_PROCESSORS=4, OneDrive=C:\Users\csrichardd\OneDrive, OS=Windows_NT, Path=C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\PuTTY\;C:\Program Files (x86)\DevDesktop\tools;C:\ProgramData\chocolatey\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Microsoft VS Code\bin;C:\Users\csrichardd\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Lando\bin, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, PKG_EXECPATH=C:\Program Files\Lando\bin\lando.exe, PROCESSOR_ARCHITECTURE=AMD64, PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel, PROCESSOR_LEVEL=6, PROCESSOR_REVISION=5e03, ProgramData=C:\ProgramData, ProgramFiles=C:\Program Files, ProgramFiles(x86)=C:\Program Files (x86), ProgramW6432=C:\Program Files, PROMPT=$P$G, PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\, PUBLIC=C:\Users\Public, SAPLOGON_INI_FILE=C:\Windows\, SystemDrive=C:, SystemRoot=C:\WINDOWS, TEMP=C:\Users\CSRICH~1\AppData\Local\Temp, TMP=C:\Users\CSRICH~1\AppData\Local\Temp, USERDNSDOMAIN=ROSE.PORTLAND.LOCAL, USERDOMAIN=ROSE, USERDOMAIN_ROAMINGPROFILE=ROSE, USERNAME=csrichardd, USERPROFILE=C:\Users\csrichardd, VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\, VSEDEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection, windir=C:\WINDOWS, windows_tracing_flags=3, windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
portlandor3_cache_1 is up-to-date
portlandor3_database_1 is up-to-date
Creating portlandor3_index_1 ... error

ERROR: for portlandor3_index_1  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\services\\\\helpers\\\\sql-export.sh"\nis not a valid Windows path'

ERROR: for index  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\services\\\\helpers\\\\sql-export.sh"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
verbose: Spawn exited with code: 1
silly: Spawn finished with
debug: About to run 0=C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe, 1=--project-name, 2=portlandor3, 3=--file, 4=C:\Users\csrichardd\.lando\compose\portlandor3\portlandor3-2.yml, 5=--file, 6=C:\Users\csrichardd\.lando\proxy\portlandor3-proxy-3.yml, 7=up, 8=-d, 9=--remove-orphans
^C
```

**Tell us generally about your bug**

After updating from beta 45 to beta 46, whenever I attempt to lando start or rebuild I get a handful of errors like 

> Creating portlandor3_index_1 ... error
> 
> ERROR: for portlandor3_index_1  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\services\\\\helpers\\\\sql-export.sh"\nis not a valid Windows path'
> 
> ERROR: for index  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\services\\\\helpers\\\\sql-export.sh"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.

> ERROR: for portlandor3_index_1  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/cs
> richardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\engine\\\\scripts\\\\user-perms.sh"\nis not a valid Wi
> ndows path'
> 
> ERROR: for index  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites
> /portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\engine\\\\scripts\\\\user-perms.sh"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> portlandor3_cache_1 is up-to-date
> portlandor3_database_1 is up-to-date
> Creating portlandor3_index_1 ... error
> 
> ERROR: for portlandor3_index_1  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/cs
> richardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\engine\\\\scripts\\\\add-cert.sh"\nis not a valid Wind
> ows path'
> 
> ERROR: for index  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites
> /portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\engine\\\\scripts\\\\add-cert.sh"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> portlandor3_cache_1 is up-to-date
> portlandor3_database_1 is up-to-date
> Creating portlandor3_index_1 ... error
> 
> ERROR: for portlandor3_index_1  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/cs
> richardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\services\\\\helpers\\\\sql-export.sh"\nis not a valid
> Windows path'
> 
> ERROR: for index  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites
> /portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\services\\\\helpers\\\\sql-export.sh"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> portlandor3_cache_1 is up-to-date
> portlandor3_database_1 is up-to-date
> Creating portlandor3_index_1 ... error
> 
> ERROR: for portlandor3_index_1  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/cs
> richardd/Sites/portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\engine\\\\scripts\\\\add-cert.sh"\nis not a valid Wind
> ows path'
> 
> ERROR: for index  Cannot create container for service index: b'Mount denied:\nThe source path "/c/Users/csrichardd/Sites
> /portlandor3/C:\\\\Users\\\\csrichardd\\\\.lando\\\\engine\\\\scripts\\\\add-cert.sh"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> error: Error

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
git clone -c core.symlinks=true git@github.com:eGovPDX/portlandor.git
git config core.autocrlf false
lando start
```

**Tell us more**

Does this bug prevent you from using lando? Yes (at least beta 46)

I've tried (unsuccessfully) to fix this by uninstalling Lando and Docker, removing my ~/.lando directory, and reinstalling.

**Comment by jonathanjfshaw** [comment]
I'm hitting same problem. I also found that Docker did not start properly when installed as part of the Lando installation (it sat forever 'starting' leaving the Lando installer waiting), so I had to restart the PC and then docker started properly. I also had to manually go to Docker settings and share the c:\ drive.

**Comment by dustinleblanc** [comment]
Hi @RichardDavies! Beta 46 included a Windows specific regression, we recommend rolling back to 45 and waiting for us to release 47 before upgrading again, sorry about that!

**Comment by Markus-Schmitt** [comment]
I have the same problem with the newest Lando version.
I am trying to setup the project for platform.sh from here: https://github.com/thinktandem/template-drupal8.

> 
> # Bug Report
> 
> **Tell us about your setup**
> 
> Lando v3.0.0-rc.13 and Docker Version 18.03.1-ce-win65 (17513) on Windows 10 Professional
> 
> **Tell us about your `.lando.yml`**
> 
> ```yaml
># Change this name to something that makes sense for your project
>name: translationupdates
># Excludes rarely edited folder / files to win performance.
>excludes:
>  - drush
>  - scripts
>  - vendor
>  - web/core
>  - web/modules/contrib
>  - web/profiles/contrib
>  - web/sites/default/files
>  - web/themes/contrib
># Use the recipe appropriate for your application.
>recipe: drupal8
># Configure the D8 recipe to match up closer to a vanilla platform.sh stack
>config:
>  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
>  via: nginx
>  # Set the webroot to match your .platform.app.yaml.
>  webroot: web
>  # Set this to match the version in your .platform.app.yaml.
>  php: 7.2
>  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
>  # Specify the version to match what's in services.yaml.
>  database: mariadb
># The following additional build step will install the Platform CLI
># in the application container and auto-run `composer install`
>services:
>  appserver:
>    run:
>      - "mkdir -p /var/www/.platformsh/bin"
>      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.40.2/platform.phar"
>      - "chmod ug+x /var/www/.platformsh/bin/platform"
>      - "cd /app && composer install"
>    overrides:
>      environment:
>        BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'
>        PLATFORMSH_CLI_TOKEN: "$PLATFORMSH_CLI_TOKEN"
>        PLATFORMSH_PROJECT_ID: "t5lb5eonwa4uq"
># The following entry creates a `lando platform` command that will run
># any Platform CLI command from inside the container if desired.
>tooling:
>  platform:
>    service: appserver
>    description: Run Platform CLI commands
>    cmd: /var/www/.platformsh/bin/platform
>  phplint:
>    service: appserver
>    cmd: /app/vendor/bin/phplint
>  phpcs:
>    service: appserver
>    cmd: /app/vendor/bin/phpcs
>  phpunit:
>    service: appserver
>    cmd: /app/vendor/bin/phpunit
>  phpstan:
>    service: appserver
>    cmd: /app/vendor/bin/phpstan
>  behat:
>    service: appserver
>    cmd: /app/vendor/bin/behat
> ```
> 
> **Tell us about the command you were running**
> 
> ```shell
> lando start
> ```
> 
> **Tell us about the error you got**
```
Let's get this party started! Starting app..
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "translationupdates_default" with the default driver
Creating volume "translationupdates_exclude_drush" with default driver
Creating volume "translationupdates_exclude_scripts" with default driver
Creating volume "translationupdates_exclude_vendor" with default driver
Creating volume "translationupdates_exclude_web_core" with default driver
Creating volume "translationupdates_exclude_web_modules_contrib" with default driver
Creating volume "translationupdates_exclude_web_profiles_contrib" with default driver
Creating volume "translationupdates_exclude_web_sites_default_files" with default driver
Creating volume "translationupdates_exclude_web_themes_contrib" with default driver
Creating volume "translationupdates_data_mounter" with default driver
Creating volume "translationupdates_home_mounter" with default driver
Creating translationupdates_mounter_1 ... error

ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'

ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
Creating translationupdates_mounter_1 ... error

ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_profiles_contrib:\\\\tmp\\\\web\\\\profiles\\\\contrib"\nis not a valid Windows path'

ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_profiles_contrib:\\\\tmp\\\\web\\\\profiles\\\\contrib"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
Creating translationupdates_mounter_1 ... error

ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_sites_default_files:\\\\tmp\\\\web\\\\sites\\\\default\\\\files"\nis not a valid Windows path'

ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_sites_default_files:\\\\tmp\\\\web\\\\sites\\\\default\\\\files"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
Creating translationupdates_mounter_1 ... error

ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'

ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
Creating translationupdates_mounter_1 ... error

ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'

ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
Creating translationupdates_mounter_1 ... error

ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_themes_contrib:\\\\tmp\\\\web\\\\themes\\\\contrib"\nis not a valid Windows path'

ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_themes_contrib:\\\\tmp\\\\web\\\\themes\\\\contrib"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
Removing network translationupdates_default
Removing volume translationupdates_exclude_drush
Removing volume translationupdates_exclude_scripts
Removing volume translationupdates_exclude_vendor
Removing volume translationupdates_exclude_web_core
Removing volume translationupdates_exclude_web_modules_contrib
Removing volume translationupdates_exclude_web_profiles_contrib
Removing volume translationupdates_exclude_web_sites_default_files
Removing volume translationupdates_exclude_web_themes_contrib
Removing volume translationupdates_data_mounter
Removing volume translationupdates_home_mounter
error: Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.start.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Promise.each.Promise.retry (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
```

> **Tell us generally about your bug**
> 
> After switching from beta 47 to rc13, whenever I attempt to lando start  I get the error above. It happens with a completely new site and installing Lando and Docker from scratch. I am not sure, if I am supposed to use the base.lando.yml file or create my own lando.yml file, but the problem happens with both.
> Please detail the steps we can take to replicate this bug. Be as detailed as possible.
> 
> ```shell
> git clone https://github.com/thinktandem/template-drupal8 translationupdates
> lando start
> ```
> 
> **Tell us more**
> 
> Does this bug prevent you from using lando? Yes (at least rc13)
> 
> I've tried (unsuccessfully) to fix this by uninstalling Lando and Docker, rebooting, sharing Drive C: and reinstalling.

**Comment by pirog** [comment]
@Markus-Schmitt this is already captured over at #1510 and only happens if you are using "excludes" which is currently an experimental and unsupported feature
