### ISSUE TITLE
Feature Request: Add a command to show the vitals for an app

### ISSUE THREAD

**Issue by algorgeous** [lando/lando#1008]
Feature Request
===============

As a lazy developer I sometimes lose track of the URLs to get to the mailhog or PHPmyadmin for my app, or the port that the appserver is running on, so it would be super convenient to be able to run a command, such as `lando vitals` that displays the same vitals information as you get after running `lando start`. That way I can quickly launch the URLs to get to my particular services.

The output of the command would be very similar to this:

```
Here are your vitals again (you lazy developer):

 NAME        d7
 LOCATION    /lando/examples/drupal7-2
 SERVICES    appserver, nginx, database
 NGINX URLS  https://localhost:32799
             http://localhost:32800
             http://d7.lndo.site:8000
             https://d7.lndo.site:444
```

Being able to run `lando vitals` would be more convenient than running `lando info` and gives the service URLs in a more readable and clickable manner.

**Comment by pirog** [comment]
just run `lando start` again!

**Comment by searnest-e3** [comment]
I support the idea of "lando vitals".  I think "lando start" takes too long and scans the services which is not ideal.

```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Scanning to determine which services are ready... Please stand by...
```
