### ISSUE TITLE
Add renaming .env.example and running "lando php artisan key:generate" to Laravel docs

### ISSUE THREAD

**Issue by MSBuV** [lando/lando#1009]
I am currently trying to create a project with Laravel and running
```bash
- git clone https://github.com/laravel/laravel.git .
- lando init, laravel
- lando start
- lando composer install
- lando restart
```
on Windows 10 with beta 45 and Docker Version 17.12.0-ce-win47  leads to "Whoops looks like something went wrong" trying to access the public folder.
I needed to rename .env.example to .env and run "lando php artisan key:generate" in the root directory.
Maybe that can be added to the documentation.

**Comment by dustinleblanc** [comment]
@MSBuV that's not exactly the standard way of generating a fresh Laravel app. We actually provide the Laravel installer with the Laravel recipe. Using the Installer would run you through a composer create-project style command which causes Laravel to handle the .env file and generation of the app key automatically. I'd suggest going that route
