### ISSUE TITLE
How to Access Services On localhost

### ISSUE THREAD

**Issue by awcab** [lando/lando#1010]
I have a REST service running on my localhost (Windows 10).  I'm getting connection refused when trying to do a GET from the lando app to the service.  Is there a way to make this work?  I can access internet resources just fine so I feel like I'm missing something simple. #

**Comment by pirog** [comment]
@awcab since your containers are all running inside of a light hyper-v instance you'll need to know the hostname or IP of the host machine. Generally we set `$LANDO_HOST_IP` to your computer do i'd use that 

```bash
lando ssh -c "env" | grep LANDO_HOST_IP
```

**Comment by awcab** [comment]
Thanks so much.  This is exactly what I needed.

**Comment by alxvallejo** [comment]
This just gives me `LANDO_HOST_IP=host.docker.internal`

**Comment by pirog** [comment]
host.docker.internal will map to your host machine

**Comment by leydisContre7777** [comment]
@awcab  could you please clarify if you run `lando ssh -c "env" | grep LANDO_HOST_IP ` from the project folder and it worked?. Just tried and still getting cURL error 7: Failed to connect to localhost port 5001

I have a rest api  running on  localhost port 5001 and I need to be able to call this from my wordpress lando site.
Could you post your .lando.yml ? 
Thank you very much. 
`

**Comment by melvix** [comment]
I needed to give my local dev instance of lando access to another app running locally on my machine using a Guzzle http request.

I ran  `lando ssh -c "env" | grep LANDO_HOST_IP` which gave me the IP of my host machine.

I used the IP and port as a proxy in the http request options like this: `['proxy' => 'http://192.168.0.123:3333']` where 3333 is the port used by the second app.

**Comment by leydisContre7777** [comment]
@melvix  Thank you so much. I will give a try.
