### ISSUE TITLE
Lando will not install on Ubuntu 18.04

### ISSUE THREAD

**Issue by nicxvan** [lando/lando#1013]
Bug Report
==========

**Tell us about your setup**
I have docker  17.12.10-ce installed on a fresh Ubuntu 18.04.
I downloaded: v3.0.0-beta.47.deb
Double clicking on it opens an install prompt. Clicking install prompts for the user's password.

After entering the password an install bar opens and immediately closes and install is the only option.

I see no errors, running lando in a new terminal says the command is not found.

**Comment by nicxvan** [comment]
I also tried installing the last three versions. None worked.

**Comment by dustinleblanc** [comment]
@nicxvan try `dpkg -i -D 1 /path/to/deb` and see what it spits out as the failure cause. Where did you get docker and compose from?

**Comment by nicxvan** [comment]
Thank you @dustinleblanc that error is somewhat helpful.

The error says I don't have docker-ce installed. 

`D000001: ensure_diversions: new, (re)loading
D000001: ensure_statoverrides: new, (re)loading
Selecting previously unselected package lando.
(Reading database ... 182088 files and directories currently installed.)
Preparing to unpack lando-v3.0.0-beta.46.deb ...
D000001: process_archive oldversionstatus=not installed
D000001: ensure_diversions: same, skipping
Unpacking lando (3.0.0-beta.46) ...
D000001: process_archive updating info directory
D000001: generating infodb hashfile
D000001: process queue pkg lando:amd64 queue.len 0 progress 1, try 1
dpkg: dependency problems prevent configuration of lando:
 lando depends on docker-ce; however:
  Package docker-ce is not installed.

dpkg: error processing package lando (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-11ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
D000001: ensure_diversions: same, skipping
Processing triggers for mime-support (3.60ubuntu1) ...
D000001: ensure_diversions: same, skipping
Errors were encountered while processing:
 lando
`

But I have docker.

`docker --version`

`Docker version 17.12.1-ce, build 7390fc6`

I had to install docker as `sudo apt install docker.io` since there is no stable docker version for 18.04 yet.

**Comment by mrconnerton** [comment]
lando specifically requires docker-ce. You have to manually install the nightly version from https://download.docker.com/linux/ubuntu/dists/bionic/pool/nightly/amd64/. Make sure you uninstall docker before you install this. Just grab the newest one at the bottom of the list.

**Comment by nicxvan** [comment]
Thanks, that seems to have worked. I assumed (incorrectly) that since it had ce in the version it was community edition. I mean the naming convention is the same.

`Docker version 17.12.1-ce, build 7390fc6`
`Docker version 18.06.0-ce-dev, build 1023e99`

Any way after removing docker and installing the nightly build lando seems to be working.

**Comment by jonpugh** [comment]
See https://docs.lando.dev/basics/installation.html#linux

You can ignore the docker-ce dependency like so:


```
sudo dpkg -i --ignore-depends=docker-ce lando-stable.deb
```

**Comment by laxmariappan** [comment]
thanks, I installed docker first and then ignored the dependency as you pointed out. Running lando 3.0.23 on Ubuntu 20.04

**Comment by benhadad** [comment]
Or you can follow this to get docker installed

```
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
```

check to see if you are using the correct repo.

```
apt-cache policy docker-ce
sudo apt install docker-ce
```

**Comment by supermavster** [comment]
Thanks @jonpugh 

For Ubuntu or WSL windows:

```sh
# Download last stable version  
wget https://files.devwithlando.io/lando-stable.deb
# Show information (Optional)
dpkg --info lando-stable.deb
# Install with Ignore docker
sudo dpkg -i --ignore-depends=docker-ce lando-stable.deb
# Show version
lando -v
```

**Comment by Tigatok** [comment]
@supermavster I am running WSL. Often times docker-ce prevents me from running some other installers as well. Is there a more permanent solution to ensure that docker-ce is not checked?

**Comment by janisint** [comment]
@Tigatok would be interested too. Did you happen to find anything?

**Comment by ByNetherdude** [comment]
I found a fix to this in the lando documentation.
See:

> After installing lando this way, you may need to edit the /var/lib/dpkg/status file and remove docker-ce from the lando package dependency list in order for future apt related commands to work. Great care should be taken while editting this file!!!.
_from https://docs.lando.dev/getting-started/installation.html#docker-ce_

So I just removed `docker-ce` from the file as shown below. It works like a charm now! 
It should be said that you should only do this when you have Docker installed on Windows and are not using the docker-ce package. Hope this helps.

<br>

![image](https://user-images.githubusercontent.com/64026660/197389903-6d12ba7b-01b9-4cd1-b480-1c46cff93765.png)

**Comment by caplod** [comment]
why not list docker-ce OR docker.io as a dependency?
