### ISSUE TITLE
WordPress asking for FTP credentials

### ISSUE THREAD

**Issue by lumpysimon** [lando/lando#1015]
I am running several WordPress sites in Lando, all using identical `.lando.yml` files, and all working fine, but one site is asking for FTP credentials when I try to update or install plugins or themes.

I have checked the owner, group and permissions of the webroot and all subfolders, and they are the same for every site. Permissions are `drwxr-xr-x@`, owner is my username, group is `staff`.

I've also tried `lando rebuild`, `lando poweroff`, etc, but it's still asking on this one site.

Do you have any suggestions what could be causing this?

<img width="1050" alt="screen shot 2018-06-06 at 12 00 56" src="https://user-images.githubusercontent.com/625372/41034476-a0b0eed6-6981-11e8-9c0e-52e93ede9ea4.png">

**Comment by OriginalEXE** [comment]
Hi @lumpysimon 

Try adding this to your wp-config.php:
`define('FS_METHOD', 'direct');`

Place it somewhere above the `if ( !defined('ABSPATH') )` line. Let me know if that helps.

**Comment by lumpysimon** [comment]
Thanks for the tip @OriginalEXE, I'd forgotten about the `FS_METHOD` constant. I actually wiped and reinstalled that site and it's working fine now, but if it happens again I'll try that first.
