### ISSUE TITLE
lando composer install broken

### ISSUE THREAD

**Issue by ezenko** [lando/lando#1016]
lando  v3.0.0-beta.47 on Debian 9

lando.yml file:

```
name: {name}
recipe: pantheon
config:
  framework: drupal8
  site: {name}
  id: {id}
```

Steps done:
0. project created with terminus build:project:create d8 {name} --team="{team}" --org="{org}"
1. lando init github  --recipe pantheon
2. lando pull
3. lando composer install

The result:
**Script DrupalComposer\DrupalScaffold\Plugin::scaffold handling the drupal-scaffold event terminated with an exception                                                                              
  [ErrorException]                                                            
  count(): Parameter must be an array or an object that implements Countable** 

Stack trace:
`Exception trace:
 () at /var/www/.composer/vendor/hirak/prestissimo/src/CurlMulti.php:156
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 count() at /var/www/.composer/vendor/hirak/prestissimo/src/CurlMulti.php:156
 Hirak\Prestissimo\CurlMulti->remain() at /app/vendor/drupal-composer/drupal-scaffold/src/PrestissimoFileFetcher.php:72
 DrupalComposer\DrupalScaffold\PrestissimoFileFetcher->fetchWithPrestissimo() at /app/vendor/drupal-composer/drupal-scaffold/src/PrestissimoFileFetcher.php:35
 DrupalComposer\DrupalScaffold\PrestissimoFileFetcher->fetch() at /app/vendor/drupal-composer/drupal-scaffold/src/Handler.php:145
 DrupalComposer\DrupalScaffold\Handler->downloadScaffold() at /app/vendor/drupal-composer/drupal-scaffold/src/Plugin.php:98
 DrupalComposer\DrupalScaffold\Plugin::scaffold() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:292
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:215
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:81
 Composer\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:195
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:323
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:59
 require() at /usr/local/bin/composer:24`

**Comment by tenken** [comment]
I see this error when I try to build a `.gitlab-ci` workflow using the `composer` image from the Lando example gitlab-ci file in Github. The same `composer.json` file builds locally fine when calling `Lando restart` using this docker image `devwithlando/pantheon-appserver:7.0` using Lando `v3.0.0-beta.45`.

Any feedback / advice?

**Comment by dustinleblanc** [comment]
This looks like a Composer/Drupal-Project/Prestissimo bug rather than one with lando. It looks like it might have an issue with one of the project dependencies?

**Comment by tenken** [comment]
fyi, I resolved this issue. I had a problem in my composer.json file to my knowledge and the problem has gone away.
