### ISSUE TITLE
Feature Request: allow typing to help select options on init

### ISSUE THREAD

**Issue by generalredneck** [lando/lando#1017]
Feature Request
===============
As a lando user, I would like to be able to start typing "pan" and the list of recipies narrow down to items so that I can find the option faster.
As a lando user, I would like to be able to start typing the site name and the list of recipies narrows down to items containing that string.

So kinda like select boxes or commandline autocomplete do... the chosen or Select2 of commandline world.... Since I work for an agency (and our primary hosting is pantheon) the number of sites ranges pretty close to 100.

Totally get if this doesn't hit the top of the list as I can manually create the .lando.yml with the exact stuff I want and probably the majority of the users of lando don't have as many sites as I do... and lastly, I get that `lando init` isn't used super often... but it would be a great UX upgrade!

**Comment by dustinleblanc** [comment]
Autocomplete would be legit, iceboxing it, but definitely a good addition

**Comment by pirog** [comment]
looks like there is even a plugin for inquirer that does this
https://github.com/mokkabonna/inquirer-autocomplete-prompt
