### ISSUE TITLE
Add ability to destroy all applications

### ISSUE THREAD

**Issue by RobLoach** [lando/lando#1022]
Feature Requests and Bug Reports
--------------------------------

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

- [x]  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
- [x]  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
- [x] Fill out either the `BUG REPORT` or `FEATURE REQUEST` below.

Feature Request
===============

> Please explain your request and its importance in the form of a user story.

As a lando user cleaning up their machine, I want the option to destroy all the applications, so that I don't have to go through each one manually.

> Please provide some detail on how lando can help solve this problem

Add an `--all` option to `lando destroy`. #1020

```
lando destroy --all -y
```

**Comment by pirog** [comment]
you are a man of danger @RobLoach

**Comment by pirog** [comment]
So even though burning things to the ground is generally appealing to me im not sure anyone should wield this much power. 

Tha said we are considering some sort of "lando dev" plugin with "power tools" and this might fit in there pretty well

**Comment by RobLoach** [comment]
:+1:
