### ISSUE TITLE
Unit tests for plugins/lando-engine/lib/compose.js.

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#1023]
Test coverage for `compose.js`.

**Comment by pirog** [comment]
@serundeputy this should be merged into https://github.com/lando/lando/tree/1036-engineLevelUp

**Comment by paul94010** [comment]
lando pull --database=test
Usage: lando <command> [args] [options] [-- global options]

Commands:
  composer                 Run composer commands
  config                   Display the lando configuration
  db-export [file]         Export database from a service
  db-import [file]         Import <file> into database
                           service
  destroy [appname]        Destroy app in current directory
                           or [appname]
  drupal                   Run drupal console commands
  drush                    Run drush commands
  info [appname]           Prints info about app in current
                           directory or [appname]
  init [method]            Initialize a lando app, optional
                           methods: github, pantheon
  list                     List all lando apps
  logs [appname]           Get logs for app in current
                           directory or [appname]
  mysql                    Drop into a MySQL shell on a
                           database service
  php                      Run php commands
  poweroff                 Spin down all lando related
                           containers
  rebuild [appname]        Rebuilds app in current directory
                           or [appname]
  restart [appname]        Restarts app in current directory
                           or [appname]
  share [appname]          Get a publicly available url
  ssh [appname] [service]  SSH into [service] in current app
                           directory or [appname]
  start [appname]          Start app in current directory or
                           [appname]
  stop [appname]           Stops app in current directory or
                           [appname]
  version                  Display the lando version

Global Options:
  --help, -h  Show help
  --verbose, -v, -vv, -vvv, -vvvv  Change verbosity of
  output

Unknown arguments: database, pull
