### ISSUE TITLE
Take lando-engine plugin to THE NEXT LEVEL

### ISSUE THREAD

**Issue by pirog** [lando/lando#1036]
### Tazkz

- [x] Refactor code into es6 (@pirog)
- [x]  Appease code climate as much as possible (@pirog)
- [x]  Write out spec stubs (@pirog)
- [ ]  Write the tests (@dustinleblanc @serundeputy @pirog)
- [x]  Add engine api to docs
- [ ]  Update relevant jsdocs to match new spec (@dustinleblanc @serundeputy @pirog)

I *think* we want to try to get at least a B average in CC and 75% test coverage.

**Comment by pirog** [comment]
alright alright alright @dustinleblanc @serundeputy i've got about 100 engine plugin specs written up in this branch so feel free to dive in and start living the dream of testing! lets def try to hit up the office hours tomorrow so we can plan the attack. in the meantime im going to move onto another plugin

**Comment by dustinleblanc** [comment]
ONIT

**Comment by pirog** [comment]
@dustinleblanc also added relevant speczzz to the events plugin so those are available for da teztz as well. also coveralls is failing... wtf

**Comment by dustinleblanc** [comment]
Files, claim em as you got em!

- [ ] compose
- [ ] daemon
- [ ] docker (@dustinleblanc)
- [ ] env
- [ ] router
- [ ] utils
