### ISSUE TITLE
.env file only found if lando is started from the project root.

### ISSUE THREAD

**Issue by yobottehg** [lando/lando#1045]
If you have a .env file it is only found and injected if you start lando from the exact folder where the .env file is located.

If you start lando from a subfolder (for example /web) the following message is given:
`warn: Trouble parsing .env file with Error: ENOENT: no such file or directory, open '.env'`

This is an edge case scenario but took me 30 minutes to find out why it was failing. (I did not recognize i was in /web)

Perhaps we can fix this so it does not happen to other persons.

**Comment by dustinleblanc** [comment]
I've seen this occurance too but never really thought much about it. Putting it in the backlog

**Comment by neclimdul** [comment]
Add me to the list of people annoyed by this and who keeps meaning to find that troublesome join that's not working correctly...

**Comment by tylerssn** [comment]
@neclimdul, @yobottehg, and @jnous - hopefully PR #1246 resolves the issue for you.

**Comment by pirog** [comment]
Should be fixed as part of https://github.com/lando/lando/pull/974#issuecomment-453836939
