### ISSUE TITLE
Lando Drupal 8 Cant upload files

### ISSUE THREAD

**Issue by aproxit** [lando/lando#1057]
Hi all,

Im using Lando beta 47 and Docker Version 18.03.1-ce-win65 (17513) on Windows 10.

When using the Drupal 8 recipe and then using composer to setup a Drupal Lightning installation all seems fine until I try to upload some files which error out saying cant upload files.

I have seen various posts about Docker and permission issues but cant find anything relative to this. I am very new to Lando and containers in general so any help on diagnosing this issue would be great.

Cheers

**Comment by pirog** [comment]
@aproxit im guessing this is what you want https://docs.devwithlando.io/issues/win-file-upload.html

**Comment by aproxit** [comment]
Thanks Mike,

Looking at the link it suggests that Lando beta 38 or above should use nginx with perms already fixed and there wont be anything to do. Am I reading this wrong and there are in fact some other steps to this as Im using Lando beta 47.

**Comment by aproxit** [comment]
ok I ran lando stop > modified the lando.yml to use nginx rather than apache however when I try to browse the site I get a file not found. This is presumably due to nginx not having the correct config setup to server the site. Is there a rapid command to fix this and get the existing site backup and working?

**Comment by Markus-Schmitt** [comment]
The patch from this issue worked for me with the drupal 8 recipe a couple weeks ago:
https://www.drupal.org/project/drupal/issues/944582

How to apply the patch:  
https://www.hook42.com/blog/using-lando-drupal-8-core-issue-patch-testing
