### ISSUE TITLE
Pantheon Recipe doesn't support utf8mb4

### ISSUE THREAD

**Issue by dgading** [lando/lando#1058]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-beta.47 on MacOS Sierra*

**Tell us about your `.lando.yml`**

```yml
name: d7-pantheon
recipe: pantheon
config:
  framework: drupal
  site: <site-name> Took these out for client reasons
  id: <site-id> 
  conf:
    database: config/mysql
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

```
[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=truemax_allowed_packet=16M
```
I added the following according to https://pantheon.io/docs/platform-considerations/#emoji-support to my settings.php along with my default `pantheon` database credentials.
```
$databases['default']['default']['charset'] = 'utf8mb4';
$databases['default']['default']['collation'] = 'utf8mb4_general_ci';
```

**Tell us about the command you were running**

```bash
lando start
lando db-import pantheon_live_database.sql.gz
```
Running the steps above returned the following error.
```bash
Destroying all current tables in pantheon... 
NOTE: See the --no-wipe flag to avoid this step!
Gunzipped file detected!
Importing /app/pantheon_live_database.sql.gz...
ERROR 1071 (42000) at line 77: Specified key was too long; max key length is 767 bytes
```
My follow up steps were:
```bash
lando destroy -y && lando rebuild -y
```

During the browser's install steps, when verify requirements appears, I get the following error:

```
Database 4 byte UTF-8 support | Not supported
4 byte UTF-8 for mysql is activated, but not supported on your system. Please turn this off in settings.php, or ensure that all database-related requirements are met. See the [documentation on adding 4 byte UTF-8 support](https://www.drupal.org/node/2754539) for more information.
```

**Tell us generally about your bug**

*I tried to build a local of my Pantheon live site using the Pantheon recipe, but couldn't import the database. I checked for other issues about this subject and could only find #959 which was using the Drupal 8 recipe.*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. Clone Pantheon D7 site that includes a Database with Collation of utf8mb4_general_ci
2. lando init
3. choose Pantheon recipe
4. Choose the site that was cloned from Pantheon.
5. lando start
6. lando db-import / lando pull pantheon_db.sql.gz
```

I also tried using the steps with this module as well:
https://www.drupal.org/project/utf8mb4_convert
It returned the following error:
```bash
lando drush utf8mb4-convert-databases --verbose
Executing: mysql --defaults-extra-file=/tmp/drush_QSEMjU --database=pantheon --host=database --port=3306 --silent  < /tmp/drush_1BZJxM
Executing: mysql --defaults-extra-file=/tmp/drush_qHfXX9 --database=pantheon --host=database --port=3306 --silent  < /tmp/drush_QtHP81
This will convert the following databases to utf8mb4: default
Back up your databases before continuing! Continue? (y/n): y
Target MySQL database: pantheon@database (default:default)
The default:default MySQL database does not support UTF8MB4! Ensure that the conditions listed in settings.php related to innodb_large_prefix, the server version, and the MySQL driver version are met. See https://www.drupal.org/node/2754539 for more information.
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
I'm not sure if there is a way to update Config in the Pantheon recipe like the Drupal 7 recipe. If there is, then this might just be a documentation issue. I looked over the pantheon.js in the recipe folder and didn't see where I could add additional config

Does this bug prevent you from using lando?
It only prevents me from using the Pantheon recipe. I can make all these updates using Drupal 7 build which is what I initially used. I'm currently converting the site to Pantheon and wanted to setup Lando to match.

**Comment by teknikqa** [comment]
Add these lines to your custom MySQL config file:

```
# Use UTF8MB4 as the character set
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

I agree that this could be better documented.

**Comment by dgading** [comment]
I was able to get it imported. I updated my lando build as well, moving the config directly to the database service. I don't know if it was my lack of mysql knowledge or something in my lando file but this worked more reliably with a few other updates I had made for the specific database. 

```
# .lando.yml
...
services:
  database:
    config:
      confd: lando_config/mysql
```
```
# lando_config/mysql/my.cnf
[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=truemax_allowed_packet=16M

# Use UTF8MB4 as the character set
collation-server = utf8mb4_unicode_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

Thank you for helping look into this!
