### ISSUE TITLE
recipe: wordpress | wpcli installs late, post-start happens before it, and events seem to be eaten after it

### ISSUE THREAD

**Issue by javorszky** [lando/lando#1064]
Bug Report
==========

## Tell us about your setup

OS: macOS 10.13.5 (17F77)
Lando: v3.0.0-beta.47
Docker: existing Docker installation, Version 18.03.1-ce-mac65 (24312), 93354b38bd, freshest version as of now

## Tell us about your `.lando.yml`

```yml
name: wpclitest
recipe: wordpress
config:
  webroot: .
events:
  post-start:
    - appserver: which wp
```

## Tell us about the command you were running

Paste in a series of commands that caused the bug.

```bash
$ lando init
# edited the .lando.yml file to include the event
$ lando start
```

## Tell us about the error you got

```bash
lando start -- -vvv
...
debug: Engine is up.
debug: Cached true with key engineup for {"persist":false,"ttl":5}
debug: Retrieved from memcache with key engineup
debug: Retrieved from memcache with key engineup
debug: Retrieved from memcache with key engineup
verbose: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
error:
debug: Logging metrics data {"devMode":false,"nodeVersion":"v8.9.0","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"17.6.0","arch":"x64"},"product":"lando","version":"3.0.0-beta.47","app":"1ad638742899bfb46c8781dd55c1c94d91c3f507","type":"wordpress","services":["php:7.1","mysql"],"action":"error","created":"2018-06-26T18:20:53.029Z","message":""}
```

## Tell us generally about your bug

It seems like wp-cli isn't available at the post-start event. The `error:` with no message is `which wp` responding with an empty response but exist code 1, which lando interprets as an error.

## Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Use my `.lando.yml` file from above
2. Start lando
3. See it fail
4. Remove / comment out the events section from the `yml` file 
5. `$ lando rebuild -y`
6. See it succeed

## Tell us more

I don't know when installing `wp-cli` happens inside the wordpress recipe. Ideally I would need a hook that I could use that would guarantee that runs after wp-cli has been installed, and is avaialble.

## Does this bug prevent you from using lando?

yes :(

**Comment by nullvariable** [comment]
I can confirm that using this .lando.yml I have the same issue in Ubuntu with v3.0.0-beta.47. In fact, commands after the `which wp` also seem not to run.

In this example, the "check complete" line fails to run, while the first echo works, and then is followed by `error: `

```
- appserver: echo "checking"
- appserver: which wp
- appserver: echo "check complete"
```

**Comment by nullvariable** [comment]
I dove into this a bit more.

with a `post-start` event that generates an exit code of `1: command not found` which the `which wp` above does, nothing after that is performed, including the standard build functions for the wp recipe. Just doing a plain echo on the start hook shows that the `post-start` events seem to be hooked prior to the build script for the wp recipe, which leaves anything trying to use wp-cli failing.

So, I think there are two distinct bugs here:
- Commands that fail should either have more feedback, or should not break commands after them
- The build hook needs to happen at a higher priority than the `post-start` commands defined in the .lando.yml file

**Comment by pirog** [comment]
@nullvariable your two bullet points here are improvements we are planning to make as part of the RC1! 

That said, i DO think the event should fail and not continue if one of its commands fails as opposed to continuing onto the next step. I prefer the first part of your either eg do a better job telling the user what happened eg "My oh my, your event looks absolutely broken! It failed on command SOME COMMAND. Get your house in order and try again!"
