### ISSUE TITLE
Drush PHP shell lacking command history

### ISSUE THREAD

**Issue by wturrell** [lando/lando#1065]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? 

v3.0.0-beta.47, MacOS Sierra 10.12.6
Drush 9.4-dev-g05ba561
(I'm using iTerm2 3.1.6, but the shell works correctly on a local macOS Drush install…)

**Tell us about your `.lando.yml`**

```yml
name: example
recipe: drupal8
config:
  webroot: web
  via: nginx
  xdebug: true
  php: '7.1'
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
```

**Tell us about the command you were running**

```bash
lando drush php
# AKA: core:cli, core-cli

# OR from within the container
lando ssh
drush php
```

The prompt I see looks like this:

```
www-data@136031dddbdb:/app$ drush php
Psy Shell v0.9.6 (PHP 7.1.18 — cli) by Justin Hileman
```

Here's the output of readline_info();

**Failing in Lando**
```
=> [
     "line_buffer" => "readline_info();\n",
     "point" => 0,
     "end" => 0,
     "library_version" => "EditLine wrapper",
     "readline_name" => "",
     "attempted_completion_over" => 0,
   ]
```

**Working correctly - Debian 9.4, Vagrant/Virtualbox**
```
>>> readline_info()
=> [
     "line_buffer" => "readline_info()\n",
     "point" => 0,
     "end" => 0,
     "library_version" => "EditLine wrapper",
     "readline_name" => "",
     "attempted_completion_over" => 0,
   ]
```

**Working correctly - macOS**
```
>>> readline_info();
=> [
     "line_buffer" => "readline_info();",
     "point" => 16,
     "end" => 16,
     "mark" => 0,
     "done" => 1,
     "pending_input" => 0,
     "prompt" => ">>> ",
     "terminal_name" => "xterm-256color",
     "library_version" => "6.2",
     "readline_name" => "other",
     "attempted_completion_over" => 0,
   ]
```

**Tell us generally about your bug**

I'm unable to use command history, or (less importantly) tab completion in the Drush interactive shell. Using the arrow keys prints control codes [[A^ or [[B^.

Afaik, this feature requires **readline** support, but running `phpinfo();` indicates it's got that:

```
readline

Readline Support => enabled
Readline library => EditLine wrapper
``` 

I'd also expect to see `>>>` at the beginning of each line, but there's no prompt at all.

Is this just me? Suggestions?

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Yes

Does this bug prevent you from using lando?

No. But it makes developing a lot slower.

**Comment by pirog** [comment]
@wturrell this *should* be fixed by the improvements we made to tooling in rc.2
