### ISSUE TITLE
Add official ruby 2.5 support

### ISSUE THREAD

**Issue by KludgeKML** [lando/lando#1068]
Feature Request
===============

As a developer evaluating lando for wider use in our company (drupal/rails based), I would like more up-to-date ruby types so that lando configurations for rails apps can keep up with with security patches.

The current list of ruby types does not include patch level specifications, nor does it have even a base ruby 2.5 type. Gem Lock files for Ruby specify ruby down to the patch level, so it's important to be able to install a matching version.

If the ruby versions available are constrained only by the list in ...
plugins/lando-services/ruby/ruby.js
...it should be fairly easy to expand the list to include 2.5 and patch level versions.

**Comment by pirog** [comment]
@KludgeKML for maintainability reasons we restrict the list that said adding ruby 2.5 is something we should do. In the meantime you should be able to try out that version (and patches) using the override pattern over at https://docs.devwithlando.io/services/ruby.html

**Comment by pirog** [comment]
@KludgeKML ruby 2.5 will be in RC2
