### ISSUE TITLE
JAMF MAC OS Release 

### ISSUE THREAD

**Issue by sanddevil** [lando/lando#1070]
Feature Request
===============
As a developer without sudo access on my Mac I would like to be able to use our in house JAMF Self Service app to install Lando. 

To achieve this I need a consistent url reference to the latest build so that the self service system can find the latest image. This is available on platforms such as NodeJS as a comparison. 

At the moment your download links are related to version numbers that cannot be used in our Self Service.

**Comment by pirog** [comment]
@sanddevil im going to close this as a DUP of #810 but +1. i know id personally benefit from this for our lando on travis ci flows. we are currently using the dev build for a consistent download URL but that obviously carries risk since dev releases are fickle
