### ISSUE TITLE
db-import

### ISSUE THREAD

**Issue by mperetz** [lando/lando#1073]
I am trying to import my DB using the following command 
lando db-import somedumpfile.sql.gz

it seems to work, but when loading my site, I don't see my DB, it is trying to open a new installation of Drupal. Any ideas? 

I am trying to locally setup my drupal site for development using Lando (I don't want to setup as a new installation).

Do I need to still configure the site as a new installation for the db-import to work, am I missing anything?

I am using Pantheon for the hosting.

**Comment by tormi** [comment]
You need to define DB credentials first, see https://github.com/lando/lando/issues/585#issuecomment-401641484
