### ISSUE TITLE
db-export format changed (gzip skipped)

### ISSUE THREAD

**Issue by kvij** [lando/lando#1079]
**Setup**

v3.0.0-beta.47 on Windows 10 Professional

**The command**

```lando db-export testset.sql```

**The bug**

The command mentioned above generates _testset.sql.gz_. This file is in fact _not_ gzipped as it used to in older versions. This of course causes errors in a script I use to test and import when the database is not yet filled.

**Comment by pirog** [comment]
@kvij i can't replicate this and we've got a test for it

its worth pointing out that if the file already has the `gz` extension then `gzip` will not do anything

**Comment by kvij** [comment]
We have not had this issue for quite a while now anyway and forgot to close it. Perhaps it was user error e.g. lando db-export testset.slq.gz
