### ISSUE TITLE
Feature request: allow 'drush' to be run from a project root with site code in sub directory.

### ISSUE THREAD

**Issue by alphex** [lando/lando#1084]
As a lando user who is using composer to manage his site builds, I'll have a `<project root>/web` directory structure, where the `index.php` . for drupal is in `web`.

Running drush from the <project root> doesn't work.
I have to CD in to `web/` to run it properly.

Adding this code to `~/.drush/drushrc.php` allows this to work 

    if (file_exists('./web/index.php') && file_exists('./web/core')) {
        $options['r'] = realpath('./web');
    }

This is of course specific to that pattern ... but it seems to be standard of sorts I've seen in the drupal community so far.

... could it detect what you select, when you declare the code base is in a sub directory when you init the lando project?

Thanks!

**Comment by lslinnet** [comment]
You should be able to override the default pattern of using `lando drush` so it executes in the correct folder.

This is the example from the [documentation pages](https://docs.devwithlando.io/config/tooling.html#overriding), which basically makes use the of --root option of drush to force a specific root directory for drush execution when called using `lando drush <insert command>`
```
tooling:
  drush:
    cmd:
      - "drush"
      - "--root=/app/web"
```

**Comment by alphex** [comment]
@lslinnet thank you!   I did a search in the code base for "/web" thinking I'd find something like that, but it didn't show up for me... thank you for pointing that out.
