### ISSUE TITLE
Can't swap back to Apache from NGINX

### ISSUE THREAD

**Issue by tanc** [lando/lando#1089]
Bug Report
==========

**Tell us about your setup**

**Tell us about your `.lando.yml`**

```name: drupal-8-core
recipe: drupal8
config:
  webroot: web
```

**Tell us about the error you got**

```
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
```

**Tell us generally about your bug**

1. I started an Apache (default) based Drupal 8 recipe and then tried using NGINX by adding `via: nginx` to `.lando.yml`.
2. After that successfully started I tried changing back to the default Apache by removing the `via: nginx` line in `.lando.yml`.
3. This resulted in `Waiting until nginx service is ready...` repeating endlessly.

I tried the following to reset the containers and allow me to start the Drupal 8 recipe but none of them worked:

- lando stop; lando start
- lando stop; lando destroy; lando start
- lando restart
- lando poweroff; lando start

All of them resulted in the same issue `Waiting until nginx service is ready...`
I've also tried to add `via: apache` to `.lando.yml` but that didn't work either.

**Comment by tanc** [comment]
Ah, I think I understand the issue. You must do a `lando destroy` to remove all the containers before removing `via: ngnix` from the `.lando.yml` file.

It seems a little odd that you can swap to nginx with no destroy but trying to swap back causes this problem unless you destroy the containers first.

**Comment by pirog** [comment]
@tanc this is a bug that should be fixed in rc2
