### ISSUE TITLE
Warning message on poweroff

### ISSUE THREAD

**Issue by lumpysimon** [lando/lando#1097]
Every time I run the `lando poweroff` command I get the following warning message:

```
Spinning containers down... Standby.
(node:8594) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
21 post-instantiate-app listeners added. 
Use emitter.setMaxListeners() to increase limit
```

The poweroff then completes successfully immediately afterwards, so it doesn't seem to be causing any serious failure.

Lando v3.0.0-beta.47
MacOS 10.13.5

**Comment by tylerssn** [comment]
Do you have any custom plugins in place? When developing plugins for Lando, I often have to tick Nodes max listeners +1 for each event listener that I add.

**Comment by lumpysimon** [comment]
I'm using the default Lando installation for MacOS, I've not added any plugins.

**Comment by agilec-paul** [comment]
I also get this on `lando poweroff`

On Ubuntu 18.04  
Lando v3.0.0-rc.1

**Comment by pirog** [comment]
Warnings generally do not cause "serious failures" eg "fatal errors". I also *think* warnings will only surface if youve configured node to print warnings (which is not the default). 

That said, we've bumped the max listeners to 64 in the forthcoming RC2 as that seems a more reasonable number esp if people are writing their own plugins
