### ISSUE TITLE
Install via Cask fails if Docker already installed

### ISSUE THREAD

**Issue by PieterDC** [lando/lando#1100]
Bug Report
==========
On Mac OS '10.13.5' with Docker '18.03.1-ce-mac65 (24312)' already installed:
```bash
$ brew cask install lando
```

```bash
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> Satisfying dependencies
==> Installing Cask dependencies: docker
==> Satisfying dependencies
==> Downloading https://download.docker.com/mac/stable/24312/Docker.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask docker
==> Installing Cask docker
==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future.
Password:
==> Purging files for version 18.03.1-ce-mac65,24312 of Cask docker
Error: It seems there is already an App at '/Applications/Docker.app'.
```

I might try to install Lando without Cask.

**Comment by tanc** [comment]
I just bumped into this too. You can remove your Docker app in `/Applications/` and then run the `brew` command again.

Another 'problem' is that after the large Docker.dmg download brew downloads the Lando disk image which includes Docker (`lando-v3.0.0-beta.47.dmg`). Is there any possibility of not bundling Docker with Lando or having brew download Lando on its own somehow?

**Comment by tanc** [comment]
Another potential issue with brew installation method is that lando depends on docker which means that brew will install the latest stable docker version and will not install the version of docker that comes with Lando. I'm not sure why Lando packages Docker alongside the Lando code but I would imagine it is to control the version and ensure a tested Docker version works with a specific Lando version.

**Comment by jerrylow** [comment]
Thanks @tanc - removing `/Applications/Docker.app` was the only way to proceed via homebrew.

**Comment by dustinleblanc** [comment]
We don't directly maintain the brew formula for Lando, so technically this isn't supported. We might automate updates to the formula at some future date, but until we do that, just consider it ymmv / caveat emptor territory.

**Comment by voraciousdev** [comment]
For others that stumble upon this... I ran into this same problem without a `Docker.app` install. Instead, I ran into this problem after trying to run `brew install --cask docker` _after_ running `brew install docker`. Running `brew remove docker` first solved it for me.

**Comment by tim-hub** [comment]
> For others that stumble upon this... I ran into this same problem without a `Docker.app` install. Instead, I ran into this problem after trying to run `brew install --cask docker` _after_ running `brew install docker`. Running `brew remove docker` first solved it for me.

yeah, same issue, it seems like a conflict between homebrew formula docker and homebrew cask docker(-dekstop)

**Comment by IllyaMoskvin** [comment]
Running `brew remove docker` for whatever reason did not work for me.

I had to delete the following items manually:

```
sudo rm /opt/homebrew/etc/bash_completion.d/docker
sudo rm /opt/homebrew/share/zsh/site-functions/_docker
sudo rm /opt/homebrew/share/fish/vendor_completions.d/docker.fish
```

**Comment by SanderMuller** [comment]
> Running `brew remove docker` for whatever reason did not work for me.
> 
> I had to delete the following items manually:
> 
> ```
> sudo rm /opt/homebrew/etc/bash_completion.d/docker
> sudo rm /opt/homebrew/share/zsh/site-functions/_docker
> sudo rm /opt/homebrew/share/fish/vendor_completions.d/docker.fish
> ```

I had the same issue, but `brew uninstall docker --force` worked for me

**Comment by bmelton-mdsol** [comment]
> I had the same issue, but `brew uninstall docker --force` worked for me

Same here.  I was having a ton of problems  with "Error: It seems there is already a binary at /usr/local/bin/docker", but there was no such folder/file.  This worked for me

**Comment by rhberro** [comment]
> Running `brew remove docker` for whatever reason did not work for me.
> 
> I had to delete the following items manually:
> 
> ```
> sudo rm /opt/homebrew/etc/bash_completion.d/docker
> sudo rm /opt/homebrew/share/zsh/site-functions/_docker
> sudo rm /opt/homebrew/share/fish/vendor_completions.d/docker.fish
> ```

Running `brew cleanup` and `brew autoremove` after removing using the command `brew remove docker` does that for you! This way you don't need to manually remove these files, but it also works!

**Comment by Vickysnipe** [comment]
i had similar issue, struggled for a while but brew uninstall docker --force worked for me.
after that i used brew install --cask docker and i was able to install cask docker and get the desktop app.

**Comment by kazhian** [comment]
This worked for me

```
brew uninstall docker
brew uninstall docker --force
brew cleanup
brew autoremove
brew install --cask docker
```

**Comment by haedoang** [comment]
i did under command when I reinstalled

```sh
sudo rm /usr/local/bin/hub-tool
```

**Comment by TCcjx** [comment]
> This worked for me
> 
> ```
> brew uninstall docker
> brew uninstall docker --force
> brew cleanup
> brew autoremove
> brew install --cask docker
> ```

this is also useful for me.
