### ISSUE TITLE
Docker Toolbox

### ISSUE THREAD

**Issue by eleftrik** [lando/lando#1101]
Is there a way to use Lando with Docker Toolbox on Mac OS?

**Comment by dustinleblanc** [comment]
@eleftrik It's not supported. What are you trying to accomplish with toolbox? Maybe we know of another way to do it :)

**Comment by eleftrik** [comment]
@dustinleblanc Thanks for your reply. I develope my projects on several machines (Mac OS or Windows), including one with some Mac OS version which only supports Docker Toolbox.
I also use Laradock, which runs even on top of Docker Toolbox; I'm wondering if there is a chance to use Lando the same way.

**Comment by iBobik** [comment]
Generally, Lando does not respect Docker Machine env variables, like Docker all clients does. It yould be useable if someone have old CPU not supporting virtualization (so wants to use VirtuaBox), wants some special config (e.g. Xhyve driver or NFS sync for performance reasons) or wants to use remote host.

Could we just request for Lando recognizing this environment variables? (output of docker-machine env)
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.5:2376"
export DOCKER_CERT_PATH="/Users/Bobik/.docker/machine/machines/local"
export DOCKER_MACHINE_NAME="local"
```

**Comment by pirog** [comment]
@iBobik this is by design. We also highly discourage people with older CPUs from using Lando because chances are their experience is not going to be that great.
