### ISSUE TITLE
drush status working on local and on remote server but not connected when using alias

### ISSUE THREAD

**Issue by GhostInTheMachines** [lando/lando#1111]
**Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!**

Security
--------

If you have discovered a security issue with Lando, please contact the Lando Security Team directly at
[security@devwithlando.io](mailto:security@devwithlando.io). We manage security issues separately in a private repository until the issue has been resolved.
Even if you're not sure if it's a security problem, please contact the security team before filing an issue, blogging, or
tweeting about it.

Feature Requests and Bug Reports
--------------------------------

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
3.  Fill out either the `BUG REPORT` or `FEATURE REQUEST` below.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
lando version
v3.0.0-beta.47
OS version Ubuntu bionic beaver LTS (v18)

*Example: v3.0.0-alpha1 on Windows 10 Professional*

**Tell us about your `.lando.yml`**
##Lando yml

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

###### PhpMyAdmin example
name: pma-id-cmrc

###### Start with a basic LEMP recipe
recipe: drupal8
config:
    webroot: docroot
    php: '7.0'
    drush: '~9'

###### Add in a proxy route to phpmyadmin
proxy:
  pma:
    - pma.lemp.lndo.site

###### Add in phpmyadmin
services:

  
###### Override the appsever to add some environment variables and install an extra VIM package
  appserver:
    extras:
      - apt-get update -y
      - apt-get install vim -y
    overrides:
      services:
        environment:
          MYCONFIGVAR1: secretpasscode
    composer:
      drush/drush: ~9
    php:
      extras:
        -"no-debug-non-zts"
###### Add in another database to help with this example
  database2:
    type: mariadb

  ###### Add a phpmyadmin db frontend
  pma:

    ###### Use the latest version of phpmyadmin
    type: phpmyadmin

    ###### The databases you want to look at, this will default to a service called
    ###### "database"
    ######
    ###### You might want to run `lando info` on your app to see what databases you
    ###### have available
    hosts:
      - database
      - database2

    ###### Optionally load in a custom config file. This is relative to the app root
    ######
    ###### You will not need to import the standard library or manage backends in this
    ###### file. Those are handled automatically.
    ######
    ###### config: config.user.inc.php

    ###### There are various envvars you can specify to further customize how your
    ###### pma works.
    ######
    ###### See: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
    ######
    ###### overrides:
      ###### services:
        ###### environment:
            ###### PMA_ARBITRARY: when set to 1 connection to the arbitrary server will be allowed
            ###### PMA_HOST: define address/host name of the MySQL server
            ###### PMA_VERBOSE: define verbose name of the MySQL server
            ###### PMA_PORT: define port of the MySQL server
            ###### PMA_HOSTS: define comma separated list of address/host names of the MySQL servers
            ###### PMA_VERBOSES: define comma separated list of verbose names of the MySQL servers
            ###### PMA_USER: define username to use for config authentication method
            ###### PMA_PASSWORD: define password to use for config authentication method
            ###### PMA_ABSOLUTE_URI: define user-facing URI

###### Add a lando vim command
tooling:
  vim:
    service: appserver

```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**
I am running "lando drush @dev

Paste in a series of commands that caused the bug.
Most lando drush commands produce script errors which I am suspect is due to the different versions that are being reported between environments.

Locally 
*Example:*
lando drush cr
Clears cache successfully

SSH into remote server and running the same command in the docroot folder
drush cr
Also clears the cache successfully
However, running drush locally from the docroot/ on a remote server using an alias (@dev)
lando drush @dev cr
Throws the  "command needs a higher bootsrap level" error.

Since this looked like a case of not running the drush command from the docroot/, I changed my alias file # from:
# # File: self.site.yml
dev:
 host: islanderdomains.com
 user: islande1
 root: /home/islande1/public_html/dev/
 uri: https://dev.islanderdomains.com

# to:
# # File: self.site.yml
dev:
 host: islanderdomains.com
 user: islande1
 root: /home/islande1/public_html/dev/docroot
 uri: https://dev.islanderdomains.com

## which allows the cache to be cleared but produces an error when running the status command
lando drush @dev status
## produces this error
± |develop ✓| → lando drush @dev status
Missing argument 2 for Drush\Sql\SqlBase::__construct()              [warning]
SqlBase.php:34
#0  Drush\Drush::getContainer() called at [/home/islande1/public_html/dev/vendor/drush/drush/src/Drush.php:193]
#1  Drush\Drush::service(config) called at [/home/islande1/public_html/dev/vendor/drush/drush/src/Drush.php:238]

# Just to reiterate a point
## lando drush status with my alias root set to my project root (i.e. where my composer file is) reports the wrong drush version and does not give database connection information (which generally means **not connected to the drupal installation) BUT changing the root to inside the docroot ( i.e. where all of the Drupal files are) allows drush commands like cache clearing to run but fails to report the status of the Drupal application..
```

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.
## Running lando @dev status in verbose mode with alias root set to docroot/ produces the following trace:

|develop ✓| → lando drush -vvv @dev status
 [preflight] Config paths: /var/www/.composer/vendor/drush/drush/drush.yml,/app/drush/drush.yml
 [preflight] Alias paths: /app/docroot/drush/sites,/app/drush/sites
 [preflight] Commandfile search paths: /var/www/.composer/vendor/drush/drush/src
 [debug] Redispatch hook -vvv [0.12 sec, 9 MB]
 [command] Backend invoke: ssh -o PasswordAuthentication=no -t islande1@islanderdomains.com 'drush  --verbose --debug --root=/home/islande1/public_html/dev/docroot/ --uri=https://dev.islanderdomains.com  -vvv status 2>&1' 2>&1 [0.12 sec, 9.01 MB]
Calling proc_open(ssh -o PasswordAuthentication=no -t islande1@islanderdomains.com 'drush  --verbose --debug --root=/home/islande1/public_html/dev/docroot/ --uri=https://dev.islanderdomains.com  -vvv status 2>&1' 2>&1);
Using the Drush script found at /home/islande1/.composer/vendor/drush/drush/drush.launcher using pcntl_exec
Drush preflight prepare loaded autoloader at                         [preflight]
/home/islande1/.composer/vendor/autoload.php [0.01 sec, 2.38 MB]
Starting Drush preflight. [0.01 sec, 2.38 MB]                        [preflight]
Cache HIT cid: 8.1.15-commandfiles-0-b5aff8d9eea3f05675d860b4813e9746    [debug]
[0.02 sec, 2.67 MB]
Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.04        [debug]
sec, 4.93 MB]
Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [0.04      [debug]
sec, 4.94 MB]
Scanning into /home/islande1/.composer/vendor/drush/drush/includes/..    [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/.composer/vendor/drush/drush/includes/..    [debug]
for /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/.drush for                                  [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/.drush for                                  [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/public_html/dev/docroot/../drush for        [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/public_html/dev/docroot/../drush for        [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/public_html/dev/docroot/drush for           [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/public_html/dev/docroot/drush for           [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/public_html/dev/docroot/sites/all/drush     [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into /home/islande1/public_html/dev/docroot/sites/all/drush     [debug]
for /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into                                                            [debug]
/home/islande1/public_html/dev/docroot/sites/dev.islanderdomains.com
for /.*aliases\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Scanning into                                                            [debug]
/home/islande1/public_html/dev/docroot/sites/dev.islanderdomains.com
for /self\.alias\.drush(8|)rc\.php$/ [0.04 sec, 4.94 MB]
Bootstrap to phase 0. [0.08 sec, 6.9 MB]                             [bootstrap]
Trying to bootstrap as far as we can. [0.08 sec, 6.91 MB]                [debug]
Drush bootstrap phase : bootstrap_drupal_root() [0.09 sec, 7.94 MB]  [bootstrap]
Initialized Drupal 8.5.5 root directory at                           [bootstrap]
/home/islande1/public_html/dev/docroot [0.09 sec, 7.94 MB]
Find command files for phase 1 (max=7) [0.09 sec, 6.66 MB]               [debug]
Cache HIT cid: 8.1.15-commandfiles-1-05570748a7517c63ef9d5c9f344b31d7    [debug]
[0.09 sec, 6.66 MB]
Cache HIT cid:                                                           [debug]
8.1.15-annotationfiles-1-dafd4f9c6e417145c7e83cac78f5f220 [0.1 sec,
6.8 MB]
Drush bootstrap phase : bootstrap_drupal_site() [0.1 sec, 7.26 MB]   [bootstrap]
Initialized Drupal site dev.islanderdomains.com at sites/default [0.1[bootstrap]
sec, 7.26 MB]
Find command files for phase 2 (max=7) [0.11 sec, 7.26 MB]               [debug]
Drush bootstrap phase : bootstrap_drupal_configuration() [0.11 sec,  [bootstrap]
7.26 MB]
Add service modifier [0.11 sec, 7.54 MB]                                 [debug]
Find command files for phase 3 (max=7) [0.11 sec, 7.55 MB]               [debug]
Missing argument 2 for Drush\Sql\SqlBase::__construct()              [warning]
SqlBase.php:34 [0.11 sec, 7.68 MB]
Undefined variable: options SqlBase.php:37 [0.11 sec, 7.68 MB]          [notice]
#0  Drush\Drush::getContainer() called at [/home/islande1/public_html/dev/vendor/drush/drush/src/Drush.php:193]
#1  Drush\Drush::service(config) called at [/home/islande1/public_html/dev/vendor/drush/drush/src/Drush.php:238]
#2  Drush\Drush::config() called at [/home/islande1/public_html/dev/vendor/drush/drush/src/Drush.php:274]
#3  Drush\Drush::simulate() called at [/home/islande1/public_html/dev/vendor/drush/drush/src/Sql/SqlBase.php:221]
#4  Drush\Sql\SqlBase->query(SELECT 1;) called at [/home/islande1/.composer/vendor/drush/drush/includes/environment.inc:393]
#5  drush_valid_db_credentials() called at [/home/islande1/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php:462]
#6  Drush\Boot\DrupalBoot->bootstrap_drupal_database_validate() called at [/home/islande1/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php:109]
#7  Drush\Boot\DrupalBoot8->bootstrap_drupal_database_validate() called at [/home/islande1/.composer/vendor/drush/drush/includes/bootstrap.inc:430]
#8  drush_bootstrap_validate(4) called at [/home/islande1/.composer/vendor/drush/drush/includes/bootstrap.inc:507]
#9  drush_bootstrap_max() called at [/home/islande1/.composer/vendor/drush/drush/includes/bootstrap.inc:456]
#10 drush_bootstrap_to_phase(-2) called at [/home/islande1/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php:59]
#11 Drush\Boot\BaseBoot->bootstrap_and_dispatch() called at [/home/islande1/.composer/vendor/drush/drush/includes/preflight.inc:66]
#12 drush_main() called at [/home/islande1/.composer/vendor/drush/drush/drush.php:12]
Checking DB credentials yielded error: Drush::$container is not          [debug]
initialized yet. \Drupal::setContainer() must be called with a real
container. [0.11 sec, 7.72 MB]
Bootstrap phase bootstrap_drupal_database() failed to validate;          [debug]
continuing at bootstrap_drupal_configuration(). [0.11 sec, 7.71 MB]
Found command: core-status (commandfile=core) [0.11 sec, 7.71 MB]    [bootstrap]
Loading outputformat engine. [0.13 sec, 9.08 MB]                        [notice]
Calling hook drush_core_status [0.13 sec, 9.36 MB]                       [debug]
Missing argument 2 for Drush\Sql\SqlBase::__construct()              [warning]
SqlBase.php:34 [0.13 sec, 9.36 MB]
Undefined variable: options SqlBase.php:37 [0.13 sec, 9.36 MB]          [notice]
Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.13        [debug]
sec, 9.37 MB]
Scanning into /etc/drush for /.*\.alias\.drush(8|)rc\.php$/ [0.13        [debug]
sec, 9.37 MB]
Scanning into /home/islande1/.composer/vendor/drush/drush/includes/..    [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.13 sec, 9.37 MB]
Scanning into /home/islande1/.composer/vendor/drush/drush/includes/..    [debug]
for /.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/.drush for                                  [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/.drush for                                  [debug]
/.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/drush for           [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/drush for           [debug]
/.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/sites/all/drush     [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/sites/all/drush     [debug]
for /.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/sites/default       [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/sites/default       [debug]
for /.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/../drush for        [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into /home/islande1/public_html/dev/docroot/../drush for        [debug]
/.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into                                                            [debug]
/home/islande1/public_html/dev/docroot/sites/dev.islanderdomains.com
for /.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Scanning into                                                            [debug]
/home/islande1/public_html/dev/docroot/sites/dev.islanderdomains.com
for /.*\.alias\.drush(8|)rc\.php$/ [0.14 sec, 9.37 MB]
Returned from hook drush_core_status [0.14 sec, 9.37 MB]                 [debug]
 Drupal version         :  8.5.5                                                
 Site URI               :  https://dev.islanderdomains.com                      
 Database driver        :  mysql                                                
 Database hostname      :  localhost                                            
 Database port          :  3306                                                 
 Database username      :  Redacted_database User Name                                       
 Database name          :  Redacted_Database Name                                     
 PHP executable         :  /usr/local/bin/php                                   
 PHP configuration      :  /opt/alt/php70/etc/php.ini                           
 PHP OS                 :  Linux                                                
 Drush script           :  /home/islande1/.composer/vendor/drush/drush/drush.ph 
                           p                                                    
 Drush version          :  8.1.15                                               
 Drush temp directory   :  /tmp                                                 
 Drush configuration    :                                                       
 Drush alias files      :                                                       
 Drupal root            :  /home/islande1/public_html/dev/docroot               
 Drupal Settings File   :  sites/default/settings.php                           
 Site path              :  sites/default                                        
 Sync config path       :  sites/default/files/config_Redacted-Hash

## I suspect this has something to do with the fact that Drush is setup by my hosting provider but it seems like I should be able to change Lando in some way to correct for this to correct these two issues:
1. initial error message
2. incorrect drush version (v8.1.15)

Could better documentation have prevented this issue? if so what should we change?

Yes, it would be helpful to have some information about the situation where composer and drush must be run from the remote server, rather than from within the project root.

Does this bug prevent you from using lando?
Yes, at the moment I need to ssh into the server and run drush locally which keeps me from automating multiple environments in a more efficient way.

Feature Request
===============

Please explain your request and its importance in the form of a user story.

*Example: As a lando user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how lando can help solve this problem
Provide a workaround or possibly a recipe example to allow lando to possibly symlink the local install to use drush from a /home/user location

This is just a guess, but I believe this would make it work locally and on a remote server.

Maybe some documentation about where drush is being run from when using aliases  (i.e. where it is run by default and how this can be modified to fit different scenarios)

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by amaisano** [comment]
I had a similar request and some back and forth regarding this [on another thread](https://github.com/lando/lando/issues/982#issuecomment-392083200). I settled on this recipe, which basically let's Drush do the DB syncing (sans cache junk):

```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  site: mysite
  id: 72b428fb-f8dd-4053-80a6-d06f5289d043
tooling:
  pull:
    options:
      code:
         default: none
      database:
         default: none
      files:
         default: live
      rsync:
        default: true
events:
  post-pull:
    - appserver: cd $LANDO_WEBROOT && drush sql-sync --create-db --skip-tables-list=cache,cache_* @pantheon.mysite.live @self -y && drush cr
```

**Comment by GhostInTheMachines** [comment]
This turned out to be a .composer directory on the shared server that was taking precedence over the actual version of Composer that was installed by the host.

Not a Lando issue at all as it turned out.
