### ISSUE TITLE
URLs stop working?

### ISSUE THREAD

**Issue by paul94010** [lando/lando#1115]
Documentation Issue
==========

I believe there are details about how the URLs work that is not in the documentation.

Here is the basic info about my system:

MacOS:  10.13.4

 lando info
{
  "appserver": {
    "type": "php",
    "version": "7.1",
    "hostnames": [
      "appserver",
      "appserver.drupal.internal"
    ],
    "via": "apache",
    "webroot": "web",
    "config": {
      "conf": "/Users/developer/.lando/services/config/drupal8/php.ini"
    },
    "urls": []
  },
  "database": {
    "type": "mysql",
    "version": "5.7",
    "hostnames": [
      "database",
      "database.drupal.internal"
    ],
    "creds": {
      "user": "drupal8",
      "password": "drupal8",
      "database": "drupal8"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "config": {
      "confd": "/Users/developer/.lando/services/config/drupal8/mysql"
    },
    "urls": []
  }
}

**Tell us about your `.lando.yml`**

name: drupal
recipe: drupal8
config:
  webroot: web

**Tell us about the command you were running**

```bash  lando start

Your app has started up correctly.
Here are some vitals:

 NAME            drupal                         
 LOCATION        /Users/developer/Sites/drupal8 
 SERVICES        appserver, database            
 APPSERVER URLS  https://localhost:32777  (in green)      
                 http://localhost:32778       (in green)
                 http://drupal.lndo.site        (in red)
                 https://drupal.lndo.site       (in red)
```

**Here is how it happened**

The system was running fine for several days.  I was adding a field in an entity.   When I went to save the change, my browser said the site was no longer available.   

I stopped and then restarted the lando app.   On restart I got the color for the URLs changed.   I was using the mysite.lndo.site URL.  It was now red.   I was able to use the green URL.   

I am unsure of how this URL would no longer be valid.   And I don't know the purpose of the .lndo.site URL and when it should be used.  

Could better documentation have prevented this issue? if so what should we change?
Yes.  An explanation of how the various URLs work and fail.

Does this bug prevent you from using lando?
 No

**Comment by f1rf1n** [comment]
Domain does seem to resolve:

> ~/ws/kdk/kdk> nslookup kdk.lndo.site
> Server:		127.0.1.1
> Address:	127.0.1.1#53
> 
> Non-authoritative answer:
> *** Can't find kdk.lndo.site: No answer
> 

I have tried (according to the docs on https://docs.devwithlando.io/config/proxy.html) adding the following to my .lando.yml file:
```
proxy:
  web:
    - kdk.lndo.site
```

But that just resulted in: 
>error: Duplicate URL detected: {"http://kdk.lndo.site":2,"https://kdk.lndo.site":2}
>ERROR: The Compose file is invalid because:
>Service web has neither an image nor a build context specified. At least one must be provided.
With the last two lines repeated another 4 times. Ican't find a solution for that error, so far.

Still really strange this just seems to happen out of the blue. This is a very fresh lando install mind you, beta 47 and that is the first (and only) version I ever installed of Lando.

For completeness, my .lando.yml file contents

```
name: kdk
recipe: drupal7
config:
  webroot: .
  php: 5.6
  xdebug: true 
#proxy:
#  web:
#    - kdk.lndo.site 
```

**Comment by f1rf1n** [comment]
Putting kdk.lndo.site in /etc/hosts works, although *.lndo.site does not. 
Which begs the question: Is it necessary to put every url you need into /etc/hosts ?

**Comment by f1rf1n** [comment]
Putting kdk.lndo.site in /etc/hosts works, although *.lndo.site does not. This seems like a workaround to me though ...
Which begs the question: Is it necessary to put any or every url you need into /etc/hosts at all?

**Comment by cklosowski** [comment]
I've been seeing this happen lately too, running on the latest June 1 release:
v3.0.0-beta.47

I was working on a site, and within 15 minutes it stopped working. I tried a `lando stop` and then `lando start` and the URLs are _red_ as described above. The local host URLs are green.

**Comment by dustinleblanc** [comment]
*.lndo.site urls are routes through Lando's proxy that are wired up to many services inside Lando's many recipes. They are convenience URLs to give you a standard url to use for a given site service. They work using a proxy out on the real internet that just redirects to your localhost. Once that gets to your machine, a traefik proxy listens on port 80/443 (in a standard setup) and then proxies the requests to your various docker containers to serve your site.

As to why this would randomly break? No idea, have you tried `lando poweroff` and then `lando start`? I say power off as that is the only way to restart the proxy.

**Comment by cklosowski** [comment]
I've not seen this issue since the last couple updates. Could have either been a docker-ce issue or something in one of the previous betas. I'm currently running and all is working fine:
`Docker version 18.06.1-ce, build e68fc7a`
`Lando v3.0.0-rc.1`

**Comment by f1rf1n** [comment]
@dustinleblanc Thank you for your explanation. It seems like my problem might have been (at least partly) to a flaky net connection. have not seen it lately.  Although, if connection just used to set up the preliminary connect it should not really matter, after the 10-20 minutes no?
Then again, I haven't experienced difficulties as of late.

**Comment by stephencapellic** [comment]
I am having this issue. Started a couple of weeks ago across all the sites I manage locally and it as been a consistent problem. I am running OS X Mojave with Docker Version 2.0.0.0-mac78 (28905) and Lando version v3.0.0-rc.1.

NGINX URLS
https://localhost:32789     <-- Green
http://localhost:32790       <-- Green                                           

EDGE URLS      
http://localhost:32792           <-- Red
http://cgc1base.lndo.site       <-- Red         
https://cgc1base.lndo.site     <-- Red

EDGE_SSL URLS
https://localhost:32793          <-- Red

**Comment by stephencapellic** [comment]
It was pointed out on the Slack channel that I should be running Docker Version 18.06.1-ce-mac73 (26764) with Lando version v3.0.0-rc.1. I uninstalled Docker and reinstalled Lando. That fixed it! All green!

**Comment by keenanpayne** [comment]
I was encountering this issue today and tried @dustinleblanc's suggestion to run `lando poweroff` and then `lando restart`. This didn't work for so I ended up running `lando rebuild` and it worked perfectly. All URLs are green and working correctly. 

Figured it might be worth sharing in case anyone else stumbles upon this.

**Comment by robbdavis** [comment]
For Drupal8, make sure that your webroot in the .lando.yml file is actually pointing to your webroot. In my case I copied a .lando.yml from another project. It was using 'docroot' as the webroot when it should have ben 'web' in the new project. 

After switching to the proper webroot, the urls went green again.

**Comment by jedgar1mx** [comment]
I tried all the suggestions and nothing worked. Finally I noticed there was an issue with my `host` file. One of the domains did not match so after fixing it all the urls turned green.

Hopefully this helps someone. 👍

**Comment by hissDev** [comment]
After 2 days, a simple but annoying fact was that i were sitting in a diffrent network, which made a diffrence.

Before i collected all hints i found in a script to fix the url problem. It removes all docker images so make sure you wont loose anything (run as sudo):

```
#!/bin/bash

apt-get install linux-generic-hwe-18.04
systemctl stop docker
sudo apt-get remove lando
sudo dpkg -i --ignore-depends=docker-ce
sudo rm -rf /etc/systemd/system/docker.service.d
sudo rm -rf /var/lib/docker
sudo rm -rf /var/lib/containerd
sudo rm -Rf /etc/docker
mv /var/lib/dpkg/info/docker-ce* /tmp
apt-get purge docker-ce docker-ce-cli containerd.io -y
apt-get remove docker docker-engine docker.io containerd runc
apt-get update
apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io
```

Hope it helps somehow.

**Comment by mathews-sunny** [comment]
I faced the very same issue today. I just turned off the VPN running on the machine, and everything was green again.

I hope it helps someone.

**Comment by ironisticdrupal** [comment]
I also faced this issue recently, here how I resolved it.

1) checked by using the cmds - lando poweroff & lando rebuild. ( can solve sometime )

2) checked if there is issue with any of your images ( container images ) . Check which service is not working by going to docker desktop. Open the container by just clicking the image name and check the log files.
( In my case , my nginx URLs was not working, so I checked the nginx image and found out there is an error).
this was my issue: https://github.com/lando/nginx/issues/24). If it is any other error just google it , you might find some github threads.
List of lando plugins repos ( for specific images ): https://github.com/orgs/lando/repositories?type=all

3) If there are no issues on any of the images, then the issue might be with DNS resolution.
a) first, check if there is any DNS rebinding issue: https://docs.lando.dev/help/dns-rebind.html 
  you can try `nslookup <sitename>.lndo.site` -> it should not fail.
  
b) If failed, Find out if any service listens on those ports.
sudo lsof -n -i :80 | grep LISTEN
sudo lsof -n -i :443 | grep LISTEN
https://docs.lando.dev/core/v3/proxy.html#automatic-port-assignment

c) Try Fix DNS resolution issue if all of the above failed: https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6
After doing the above again repeat step a. It now should not fail.

d) If None of the above worked, last but not least option
Try uninstalling and reinstalling lando OR updating/downgrading lando version.
Before doing them, if you have any other projects running with lando , try to check if they are working or not.
Because,
It can be due to some issue with ~/.lando/ files on your system.
some quick useful links:
 - https://docs.lando.dev/getting-started/installation.html ( install lando)
 - https://docs.lando.dev/getting-started/uninstalling.html ( uninstalling )
 
 Hope it helps
