### ISSUE TITLE
Provide configuration help in Laravel tutorial

### ISSUE THREAD

**Issue by jcandan** [lando/lando#1116]
The Laravel tutorial lacks a necessary instruction on setting up the `.env` file with the proper environment variables. I highly recommend something akin to [this](https://medium.com/@jcandan/the-untold-path-to-laravel-on-lando-d633c9cb8e8a) tutorial be provided in `docs/tutorials/laravel.md`

**Comment by serundeputy** [comment]
@jcandan the post on medium looks good.  Are you up for creating a PR against the laravel docs page?

https://docs.devwithlando.io/dev/started.html

**Comment by serundeputy** [comment]
@jcandan thanks; this is merged!
