### ISSUE TITLE
Lando / Drupal 8

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1127]
How we can set memory size of php ?

I try to add `ini_set('memory_limit', '1024M')` in file settings.php, but i not get changes. 

any idea ?

**Comment by james-agile-coop** [comment]
You're probably best using a custom .ini file, see this example: https://github.com/lando/lando/tree/master/examples/lamp2

**Comment by kamalkech** [comment]
@james-agile-coop in the example i can't find how to set php config !!

**Comment by james-agile-coop** [comment]
https://github.com/lando/lando/blob/master/examples/lamp2/.lando.yml#L52

**Comment by kamalkech** [comment]
@james-agile-coop yep thank you
