### ISSUE TITLE
WordPress example: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by timothyjensen** [lando/lando#1128]
Bug Report
==========

**Tell us about your setup**

Lando v3.0.0-beta.47
Mac Sierra

**Tell us about your `.lando.yml`**

I'm running the example .lando.yml in examples/wordpress

**Tell us about the command you were running**

I cloned this repo and ran `lando start` from the examples/wordpress directory.  The command seemed to run successfully but I am not able to connect to the database using the host and credentials listed by `lando info`. 

```
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'
```

**Comment by mortona42** [comment]
If you're using "localhost" as the host, try 127.0.0.1 instead.

**Comment by timothyjensen** [comment]
Unfortunately that had no effect.
<img width="400" alt="localhost-error" src="https://user-images.githubusercontent.com/16006205/43916537-cb56f7de-9bdb-11e8-80bd-7a24f741e016.png">

**Comment by mortona42** [comment]
Oh, that's what I had to use to connect with the mysql cli client.

Are you using "database" for the host? db/pass should be "wordpress" and default port.

**Comment by timothyjensen** [comment]
Oh wow, my bad.  I needed `database` for the host. Thanks for the help!
