### ISSUE TITLE
mysql client confuses special characters/encoding

### ISSUE THREAD

**Issue by mortona42** [lando/lando#1130]
Using .47, drupal8 recipe.

I have an m-dash character in a value I'm querying. When I use [lando mysql] to connect and query the table, I see this returned as a weird question mark character.

Connecting with my host mysql client will show the character correctly. I have the mariadb client installed with no additional config.

I'm hoping this can be a small tweak to the default settings.

**Comment by mortona42** [comment]
![mysql-special-char](https://user-images.githubusercontent.com/696005/43917023-dc19a610-9baa-11e8-923c-e52c47372583.png)

**Comment by pirog** [comment]
@mortona42 this will be fixed in RC2
