### ISSUE TITLE
Error about build path dockerfile

### ISSUE THREAD

**Issue by aimevp** [lando/lando#1131]
There's a project where I needed to enable an extra php plugin and with a little help from this issue queue I got this working (see yml & dockerfile below). However when I try to poweroff lando I get some errors about a dockerfile lando can't find in another project (where I didn't use a dockerfile).

**My setup**

Lando: v3.0.0-beta.47
Docker: 18.06.0-ce-mac69 (26398)
OS: MacOS High Sierra v10.13.5

**My project1 `.lando.yml` & `dockerfile`**

```yml
name: md-project1-d6
recipe: drupal6
config:
  webroot: ./www
  php: '5.5'
services:
  appserver:
    via: apache
    type: php:custom
    overrides:
      services:
        build: $LANDO_APP_ROOT/lando_assets/dockerfile
  database:
    portforward: 30101
    creds:
      user: project1_d6
      password: project1_d6
      database: project1_d6
    overrides:
      services:
        volumes:
          - $LANDO_APP_ROOT/lando_assets/db:/var/lib/mysql
```

```Dockerfile
FROM devwithlando/php:5.5-apache

RUN a2enmod headers
RUN apachectl restart
```

**My project2 `.lando.yml`**

```yml
name: md-project2
recipe: drupal7
config:
  webroot: ./www
  php: '5.6'
services:
  database:
    portforward: 30104
    creds:
      user: project2
      password: project2
      database: project2
    overrides:
      services:
        volumes:
          - $LANDO_APP_ROOT/lando_assets/db:/var/lib/mysql
```

**The command I was running**

```bash
lando poweroff -vvvv
```

**The error I got**

```bash
Lando containers have been spun down.
ERROR: build path /path/to/project2/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /path/to/project2/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /path/to/project2/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /path/to/project2/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /path/to/project2/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
error: Error
```

**Tell us more**

What I've also noticed is that whenever I create a new lando project the poweroff command will generate errors using that last created project. So after creating a new project the errors changed to:

```bash
Spinning containers down... Standby.
Killing landoproxyhyperion5000gandalfedition_proxy_1 ...
ERROR: build path /path/to/lando2d8test/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
Killing lando2d8test_appserver_1 ...
Killing landoproxyhyperion5000gandalfedition_proxy_1 ... done
Killing lando2d8test_appserver_1 ... done
Killing lando2d8test_database_1  ... done
ERROR: build path /path/to/lando2d8test/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /path/to/lando2d8test/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /path/to/lando2d8test/lando_assets/dockerfile either does not exist, is not accessible, or is not a valid URL.
error: Error
```

**Does this bug prevent you from using lando?**
No I don't think it's preventing me from continuing using Lando but I would prefer to fix it anyway.

Thanks in advance for the help.

**Update**

After the poweroff command and using the following command:

```bash
docker ps
```

I noticed there were 2 containers still running from the lando instance that was using the dockerfile.

```bash
549f996d9752        devwithlando/php:custom-apache   "/lando-entrypoint.s…"   26 minutes ago      Up 26 minutes             0.0.0.0:32817->80/tcp, 0.0.0.0:32816->443/tcp   project1_appserver_1
6f75f79c00ac        mysql:5.7                        "/lando-entrypoint.s…"   26 minutes ago      Up 26 minutes (healthy)   0.0.0.0:30101->3306/tcp                         project1_database_1
```

I was able to kill the containers using the command 

```bash
docker kill $(docker ps -q)
```
But after starting and powering off lando I keep getting the same errors on the last created lando project. After a new poweroff command there are however no docker containers running anymore so I'm not entirely sure if this was related. It could also have been some remaining containers after trying to get the project with the dockerfile running. That one wasn't an immediate success. ;o)

**Comment by dustinleblanc** [comment]
The build path should be a relative path from your project root as the file is used outside of the container, not inside of it. Not sure if that will fix this, but it could. The path should be something more like: `./lando_assets/dockerfile`

**Comment by aimevp** [comment]
@dustinleblanc Thx. That fixed it indeed.
