### ISSUE TITLE
xdebug enabled on PHP cli causing problems when PHPStorm listening for connections

### ISSUE THREAD

**Issue by tanc** [lando/lando#1140]
**Tell us about your setup**

MacOS 10.13.6
Lando v3.0.0-beta.47

**Tell us about your `.lando.yml`**

```
name: test
recipe: drupal8
config:
  xdebug: true
```

**Tell us about the command you were running**

`lando drush cr`

**Tell us generally about your bug**

As php.ini files are shared between the PHP CLI and PHP used by the web server it doesn't seem possible to disable xdebug on the command line while still having it enabled for the web server.

When PHPStorm is listening for debug connections and a drush command is run then xdebug captures and halts execution. This is a little frustrating when debugging as often cache rebuilds are needed.

To get around this problem a developer can stop PHPStorm listening for debug connections. Remembering to toggle this on and off in the IDE is difficult though.

Ideally PHP CLI would have a different set of ini files so they can be overridden and xdebug disabled.

**Comment by kevinquillen** [comment]
Just ran into this as well. Would be great to have.

**Comment by ccharlton** [comment]
My team ran into this as well. 👍

**Comment by rabauss** [comment]
We have this problem too!
solved it by adding individual php.ini in .lando.yml and not using ``xdebug: true``
```
services:
  appserver:
    config:
      conf: .lando/php/php.ini
```
php.ini:
```
; Xdebug
xdebug.remote_autostart = Off
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.remote_enable = 1
xdebug.remote_host = ${LANDO_HOST_IP}
```

**Comment by pirog** [comment]
Sadly its actually non-trivial to supply separate php/cli config files with the underlying images we are using. that said in hte forthcoming RC2 the xdebug extension will be disabled by default so it should be possible to spin up a webserver with it turned on and another cli container with it turned off

**Comment by ccharlton** [comment]
That sounds neat.
