### ISSUE TITLE
Level Up Functional Test Suite

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#1144]

**Comment by pirog** [comment]
@dustinleblanc lots of optimizing to do here including:

1. Build step caching (or figuring if we can use our own docker image with `machine`.
2. Purchase their `Docker Level Caching`
3. Purchase their max parallel option
4. Other things? 

But we are rolling!

**Comment by pirog** [comment]
@dustinleblanc @serundeputy im merging this into master, going to move onto other things and then return at the end to see how many actual tests i can write
