### ISSUE TITLE
Unable to override table prefix in Pantheon recipe

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1153]
Bug Report
==========
I inherited a Pantheon project with database tables that have a prefix.  I know, right?  Apparently, there is no way to override Lando to include the table prefix so I had to hard code the value in line 92 of `~/lando/plugins/lando-recipes/recipes/pantheon/pantheon.js`.  See below:

```javascript
 87     // Pressflow and backdrop database settings
 88     var pantheonDatabases = {
 89       default: {
 90         default: {
 91           driver: 'mysql',
 92           prefix: 'main_',
 93           database: 'pantheon',
 94           username: 'pantheon',
 95           password: 'pantheon',
 96           host: 'database',
 97           port: 3306
 98         }
 99       }
100     };
```
System specs:
```bash
$ uname -a
Linux Lenovo-Y70-70-Touch 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
$ lando version
v3.0.0-beta.47
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
$ docker-compose -v
docker-compose version 1.22.0, build f46880fe
```
Contents of `.lando.yml`:
```yml
name: mysite
recipe: pantheon
config:
  webroot: .
  framework: drupal
  drush: stable
  site: mysite
  id: <hash here>
...
```
Contents of `pantheon.yml`:
```yml
api_version: 1
php_version: 5.6
```
Command that failed:
```bash
lando pull
```

**Comment by tenken** [comment]
I may be wrong, but this usecase sounds like a custom `build:` step in your .lando file for appserver that modifies the `sites/default/settings.php` file using Awk or Sed to adjust the prefix value may be a solution worth documenting in the official documentation or faq.

I imagine typically users spin-up or inherit vanilla Pantheon configurations and making all $database values configurable could be cumbersome (in fact the array keys are vastly different between dbms systems).

**Comment by uberhacker** [comment]
@tenken: Thank you for the feedback.  It's a bit more complicated, actually.  The problem is Lando fixes the prefix value so it's always an empty string and there is no way to override.  I suppose you could remove the table prefix before you import the database into Lando but then you would need to export with the table prefix.  You could also just remove the prefix entirely from the database and fix on the Pantheon side.  These are all major workarounds, however.

**Comment by uberhacker** [comment]
Update: The prefix line is now 85 in `~/lando/plugins/lando-recipes/recipes/pantheon/pantheon.js` with `v3.0.0-rc.1`.

**Comment by amklose** [comment]
@uberhacker Were you able to override the table prefix? I've also been tasked with working on a Pantheon site with a table prefix.

**Comment by pirog** [comment]
Circling back around to this now that Lando is on the move. So looks like this is something you can actually do. from the pantheon docs

> Are table prefixes supported?
Pantheon injects the database configuration dynamically during bootstrap. In the PRESSFLOW_SETTINGS variable, the appropriate database connection information is passed in based upon the environment (Dev/Test/Live).

> You can technically use database prefixes, but Pantheon will not support database prefixes. As a best practice, allow Pantheon to populate your database configuration settings.

I'm guessing we should offer the same "you can do it but we dont support it" disclaimer. @uberhacker do you have a suggestion or proposal for what this would look like on the Lando side. Are you thinking something like this?

```yaml
name: mysite
recipe: pantheon
config:
  prefix: something
  framework: drupal
```

**Comment by pirog** [comment]
UNSTALE!
