### ISSUE TITLE
Detect .lando.yml, then .lando.yml.dist

### ISSUE THREAD

**Issue by ro0NL** [lando/lando#1154]
Feature Request
===============

I'd like to store a distribution lando config in my app, suffixed with the .dist extension. This way i can gitignore the actual .lando.yml, allowing users to modify it as needed.

However, the dist file works fine out-of-the-box, as such i'd like `lando start` to detect it in case no .lando.yml file is present.

Currently:

```bash
$ lando start
warn: Could not find app in this dir
```

Additionally the .yaml extension could take precedence.

```
.lando.yaml > .lando.yml > .lando.yaml.dist > .lando.yml.dist
```

**Comment by tylerssn** [comment]
What is your reasoning behind using a dist file? 

The only time I can envision this being appropriate is if it is packaged in a framework that you're distributing. In that case, I'd have your documentation instruct users on renaming the file appropriately.

If this is a matter of env customizations, I'd suggest taking advantage of .env files as Lando does a decent job of parsing env variables so that they can be used in the Lando YAML.

**Comment by ro0NL** [comment]
In general we'd like to put .lando.yml.dist in the repository, allowing colleagues to modify it to their needs.

Im fine either way, copying the dist file first or indeed try to see if env vars can help. Nevertheless proposed suggestion would be a nice little win IMHO :)

**Comment by dalin-** [comment]
Wouldn't it go the other way?  First you'd load `.lando.dist.yml`, then override that with what's in the `.lando.yml`?  

Also, which is better: `.dist` or `.upstream`?

**Comment by ro0NL** [comment]
> First you'd load .lando.dist.yml, then override that with what's in the .lando.yml?

Correct :)

> Also, which is better: .dist or .upstream?

I'd say .dist, never seen .upstream TBH

Also we had a little discussion about the usecase, for now e.g. mysql credentials, portforward would we like to customize,  but not commit.

**Comment by marcaddeo** [comment]
I could also see this being useful. For example, some people [may need to edit the .lando.yml file for their editors settings](https://docs.devwithlando.io/tutorials/lando-with-vscode.html).

**Comment by tylerssn** [comment]
My personal opinion is that a `.dist` file just shouldn't be. The Lando yml allows for environment variables to be passed to it, it also takes advantage of the `.env` and, in the context of PHP, the PHP.ini file allows for environment variables to be passed to it.

I'd consider my Lando setup fairly complex and robust and still I do not need to cater it to my devs environments. And, at the end of the day, I can trust my setup instructions on any OS. 


I guess to summarize my point, I see the Lando yml   as the definer and requirements of my application. Like the composer.json, its meant to tell you what it  requires.

**Comment by pirog** [comment]
In principle I totally agree with @tylerssn. I think if you find yourself in a situation where each of your devs need to provide their own overrides you are probably not using lando correctly. 

That said, i *do* think having a "base" lando file that you can ship as part of a project start state eg a Drupal distribution that does a lot of the repeatable "heavy lifting" and requires a very minimal `.lando.yml` to live on top of it is a good idea. 

See: https://github.com/lando/lando/issues/759#issuecomment-453877893 which details the "multi lando file" support we will ship with rc2

**Comment by simesy** [comment]
> In principle I totally agree with @tylerssn. I think if you find yourself in a situation where each of your devs need to provide their own overrides you are probably not using lando correctly.

I think that's not a useful assumption and at worst leads to "You want to override therefore you're using lando wrong".

**Comment by pirog** [comment]
@simesy seems likely that you are.
