### ISSUE TITLE
Access denied for user, confusing

### ISSUE THREAD

**Issue by mindbet** [lando/lando#1163]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Lando v3.0.0-beta.47

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

name: mcm-2019-e
recipe: drupal8
config:
  webroot: web
services:
  d7db:
    type: mariadb
    creds:
      user: pantheon
      password: pantheon
      database: pantheon

**Tell us about the command you were running**

lando drush migrate-upgrade --legacy-root=/filestoimport --legacy-db-key=migrate

**Tell us about the error you got**

 [info] Undefined index: scheme DrupalBoot8.php:121
 [info] Executing: mysql --defaults-file=/tmp/drush_yu0ndQ --database=drupal8 --host=database --port=3306 --silent  < /tmp/drush_upq3a7
 [info] Executing: mysql --defaults-file=/tmp/drush_s8p2ki --database=drupal8 --host=database --port=3306 --silent  < /tmp/drush_p1Zbhz
 [error]  SQLSTATE[HY000] [1045] Access denied for user 'pantheon'@'mcm2019e_appserver_1.mcm2019e_default' (using password: YES) 

**Tell us generally about your bug**

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

This is a Drupal 7 to Drupal 8 migration.

d7db is the Drupal 7 database.

Here are the steps:

1) Use .lando.yml to set up LANDO

Your app has started up correctly.
Here are some vitals:

 NAME            mcm2019e                        
 LOCATION        /Users/pd/Sites/mcm2019e/drupal 
 SERVICES        appserver, database, d7db       
 APPSERVER URLS  https://localhost:32773         
                 http://localhost:32774          
                 http://mcm2019e.lndo.site:8000  
                 https://mcm2019e.lndo.site:444  

2) load Drupal 7 database into d7db

lando ssh d7db -u root
mysql
use pantheon
source dump.sql.gz

The following lines are added to sites/default/settings.php

$databases['migrate']['default'] = array(
  'database' => 'pantheon',
  'username' => 'pantheon',
  'password' => 'pantheon',
  'prefix' => '',
  'host' => 'database',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);

3) install Drupal 8

4) install and enable migrate modules in Drupal 8

composer require drupal/migrate_plus:4.0-rc1
composer require drupal/migrate_tools:4.0
composer require drupal/migrate_upgrade:3.0-rc5

lando drush en migrate_plus migrate_tools migrate_upgrade

5) run 

lando drush migrate-upgrade --legacy-root=/filestoimport --legacy-db-key=migrate

/filestoimport is a directory with the Drupal 7 images files.

Get message:

 [error]  SQLSTATE[HY000] [1045] Access denied for user 'pantheon'@'mcm2019e_appserver_1.mcm2019e_default' (using password: YES) 

Here is the lando info

{
  "appserver": {
    "type": "php",
    "version": "7.1",
    "hostnames": [
      "appserver",
      "appserver.mcm2019e.internal"
    ],
    "via": "apache",
    "webroot": "web",
    "config": {
      "conf": "/Users/pd/.lando/services/config/drupal8/php.ini"
    },
    "urls": [
      "https://localhost:32773",
      "http://localhost:32774",
      "http://mcm2019e.lndo.site:8000",
      "https://mcm2019e.lndo.site:444"
    ]
  },
  "database": {
    "type": "mysql",
    "version": "5.7",
    "hostnames": [
      "database",
      "database.mcm2019e.internal"
    ],
    "creds": {
      "user": "drupal8",
      "password": "drupal8",
      "database": "drupal8"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32775"
    },
    "config": {
      "confd": "/Users/pd/.lando/services/config/drupal8/mysql"
    },
    "urls": []
  },
  "d7db": {
    "type": "mariadb",
    "version": "10.3",
    "hostnames": [
      "d7db",
      "d7db.mcm2019e.internal"
    ],
    "creds": {
      "user": "pantheon",
      "password": "pantheon",
      "database": "pantheon"
    },
    "internal_connection": {
      "host": "d7db",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "not forwarded"
    },
    "urls": []
  }
}

**Comment by serundeputy** [comment]
@mindbet I believe this:

```php
$databases['migrate']['default'] = array(
  'database' => 'pantheon',
  'username' => 'pantheon',
  'password' => 'pantheon',
  'prefix' => '',
  'host' => 'database',
  'port' => '3306',
  'namespace' => 'Drupal\Core\Database\Driver\mysql',
  'driver' => 'mysql',
);
```

should be:

```php
$databases['migrate']['default'] = array(
  'database' => 'pantheon',
  'username' => 'pantheon',
  'password' => 'pantheon',
  'prefix' => '',
  'host' => 'd7db',
  'port' => '3306',
  'namespace' => 'Drupal\Core\Database\Driver\mysql',
  'driver' => 'mysql',
);
```

i.e. your D7 database is not in the `database` container it is in the `d7dbb` container.

**Comment by mindbet** [comment]
Thanks very much for your help, @serundeputy.

Your suggestion fixed my mistake. Happy lando-ing.
