### ISSUE TITLE
Lando unable to pass through certain Drush commands with -- operator

### ISSUE THREAD

**Issue by johnpez** [lando/lando#1173]
I'm using the Drupal 8 recipe of Lando v3.0.0-beta.47 on Mac OSX High Sierra 10.13.6

This is a very specific error, but I bet it affects a fair amount of people using Drupal with Lando.

Essentially, the Drush rsync command allows you to pass arguments after a " -- " character, for instance:

`drush rsync @dev @prod -- --delete`

Using the drush command through lando, arguments after the -- are either not recognized or not respected.

The easiest way to recreate:

From a Drupal8 Lando instance run: `lando drush -s rsync a b -- --delete`
The output will be: `Calling system(rsync -e 'ssh ' -akz a b);`

Then, do a `lando ssh` and run `drush -s rsync a b -- --delete`
The output will be: `Calling system(rsync -e 'ssh ' -akz --delete --ansi a b);`

Note that --delete only shows up when calling drush directly, not when calling it through lando.

Any thoughts on possible workarounds? Any more information I can provide? Please let me know and ty for lando!

**Comment by serundeputy** [comment]
yeah that is going to be in conflict with lando commands, i.e.:

`lando drush cr -- -vvv`

all the things after the `--` are things that lando looks for so to get the drush stuff to work we'd have to implement some trickery.

I don't have any idea off the top of my head how to make the distinction between them.

**Comment by pirog** [comment]
@johnpez we've actually removed lando "global" options so this should be possible in the forthcoming rc2
