### ISSUE TITLE
'lando init' hangs

### ISSUE THREAD

**Issue by eleftrik** [lando/lando#1186]
Lando `3.0.0-rc.1` on Windows 10 Pro

`lando init`

then I answer all questions

```
? What recipe do you want to use? laravel
? Enter a Pantheon machine token [hidden]
? Where is your webroot relative to the init destination? public
? What do you want to call this app? lando
```

After answering the last question, the terminal hangs. I can't even stop it hitting CTRL-C or CTRL-Z.

Thanks

**Comment by pirog** [comment]
@eleftrik id try this on RC2+ and if you get the same thing feel free to post another issue
