### ISSUE TITLE
Feature request - lando destroy with/without deleting database volume

### ISSUE THREAD

**Issue by marceldobrica** [lando/lando#1189]
Feature Request
===============

lando destroy don't delete app files. I think it will be nice to have a solution to don't delete also database volume (like docker-compose down), or, better, a solution to bk database and save bk in main app folder on lando destroy... to be able to rebuild old database on lando start....

Database and app files are what we change / develop. If we'll keep app files and database volume we'll be able to start app again from where we left it as long as we don't change .lando.yml

**Comment by lestertarranza** [comment]
What was the solution to this?
