### ISSUE TITLE
"lando drush sql-cli" is not working

### ISSUE THREAD

**Issue by megadesk3000** [lando/lando#1193]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-rc.1 on Mac OsX 10.11.16*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```name: drupaleurope
recipe: drupal8
config:
  webroot: web
```

**Tell us about the command you were running**
```
lando drush sql-cli -vvv
 [preflight] Config paths: /app/vendor/drush/drush/drush.yml,/app/drush/drush.yml
 [preflight] Alias paths: /app/web/drush/sites,/app/drush/sites
 [preflight] Commandfile search paths: /app/vendor/drush/drush/src,/app/drush
 [bootstrap] Starting bootstrap to max [1.6 sec, 7.42 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [1.62 sec, 7.62 MB]
 [bootstrap] Change working directory to /app/web [1.62 sec, 7.62 MB]
 [bootstrap] Initialized Drupal 8.6.1 root directory at /app/web [1.62 sec, 7.62 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [1.64 sec, 8.07 MB]
 [bootstrap] Initialized Drupal site default at sites/default [1.64 sec, 8.07 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [1.64 sec, 8.07 MB]
 [debug] Add service modifier [1.67 sec, 8.33 MB]
Calling proc_open(mysql --defaults-file=/tmp/drush_gnN8bZ --database=drupal8 --host=database --port=3306);
``` 

**Tell us about the error you got**
Command hangs during step "Calling proc_open(mysql --defaults-file=/tmp/drush_gnN8bZ --database=drupal8 --host=database --port=3306)"

**Tell us more**

This works: lando mysql -u drupal8 -pdrupal8 -h database

I read https://github.com/lando/lando/issues/898 and tried to set database to mysql:5.7 like proposed there, but that did not change anything

**Comment by pirog** [comment]
Can't test this since its non-interactive but i cant replicate either and our func test does a drupal site install via drush which while not exactly the same is probably good enough for a test
