### ISSUE TITLE
Where is the donate button!?

### ISSUE THREAD

**Issue by generalredneck** [lando/lando#1198]
Ok guys... I've scowered the docs and the readme's and stuff and there is nothing out there that says "Take my moneys!!!!" I think it would be beneficial for Lando to consider adding a dontation button, service, or something to the documentation so that those of us who don't have time to code or test can at least throw beer money your way... Drunken History has to happen some how!

I get it... Money is not a motivator... a driver... etc... but every project needs it... even if it is to go chill with a 6-pack... or a bottle of Morgan.

**Comment by dustinleblanc** [comment]
@generalredneck Thanks! Get in touch with @reynoldsalec, we've got some ways you can support Lando, especially at the agency level. And yeah, the more money we can generate, the more dev hours we can put into making it better. Same goes to any others, if you have an agency that uses Lando and you'd like to support further development, we hope to make that simpler in the near future

**Comment by reynoldsalec** [comment]
Yep, definitely reach out! The [Tandem contact form](https://thinktandem.io/contact/) is a good way to get details for right now.
