### ISSUE TITLE
Feature Request: "depends on" service

### ISSUE THREAD

**Issue by upnica** [lando/lando#1215]
Feature Request
===============

I currently have a node application which uses MySQL with TypeORM, i setup a database connection during the bootstrap of the application, however the database service has not finished initialising when the app service is starting, this causes connection refused errors.

Is it possible to either have a *depends on* feature so that the service does not start until the service(s) it depends on have finished starting?

**Comment by pirog** [comment]
@upnica this is already possible using our docker overrides keys
https://docs.devwithlando.io/config/advanced.html#overriding-with-docker-compose

**Comment by xurizaemon** [comment]
```yaml
services:
  foo:
    depends_on:
      - bar
```

- https://github.com/lando/core/blob/d3fdc40179150488ca6e9f3700685ac9ebfc1b18/examples/networking/.lando.lemp.yml#L22
