### ISSUE TITLE
Max verbosity should show internal commands output with verbose mode

### ISSUE THREAD

**Issue by edurenye** [lando/lando#1217]
I think max verbosity should show the output of all commands is using internally with verbose mode.

For example this internal command:
`
/usr/share/lando/bin/docker-compose --project-name project_name --file /home/user/.lando/compose/project_name/project_name-1.yml --file /home/user/.lando/proxy/project_name-proxy-1.yml up -d --no-recreate --remove-orphans node
`

Should be:
`
/usr/share/lando/bin/docker-compose --project-name project_name --file /home/user/.lando/compose/project_name/project_name-1.yml --file /home/user/.lando/proxy/project_name-proxy-1.yml --verbose up -d --no-recreate --remove-orphans node
`

And display the output.

This will be good for debugging, in my case that command was failing and I was trying to figure out why, so -vvvv should add verbosity to all commands or another solution is to add a next level of verbosity that does it, let's say -vvvvv for example.

**Comment by pirog** [comment]
@edurenye i dont think it is possible to do this universally because not all commands use the same flags for verbose or debug output but in the forthcoming rc2 lando will pass its own verbosity flags to any tooling commands
