### ISSUE TITLE
Support bzip2 in db-import, db-export

### ISSUE THREAD

**Issue by benjifisher** [lando/lando#1220]
As a Lando user who works with database backups compressed with `bzip2`, I want the option to import and export databases using this compression format. I prefer not to follow extra steps to (un)compress my backups when using `lando db-import` and `lando db-export`.

Ideally, `lando db-import` would detect the format (or at least the file extension) automatically. We could add an option to `lando db-export` to specify the compression method, or it could automatically use `bzip2` when given a file name ending in `.bz2`.

Work-around: currently, we can use a single shell command, but it is a little awkward:

```bash
bzcat database.sql.bz2 | lando db-import
lando db-export --stdout | bzip2 -c > database.sql.bz2
```

According to the [Lando docs for db-import](https://docs.devwithlando.io/tutorials/db-import.html#examples),

> NOTE: this is a bit finicky right now [referring to using `db-import` with `stdin`]

In fact, it does not work in my testing.

**Comment by UltraBob** [comment]
I don't know if it is an update to lando that caused it or the environment I'm on, but this worked for me for db-import:  `lando db-import `bzcat filename_here.sql.bz2`
