### ISSUE TITLE
Docker-sync for mac

### ISSUE THREAD

**Issue by adriadrop** [lando/lando#1228]
How come docker-sync http://docker-sync.io/ is not implemented in lando?  Docker4drupal has that option and file synching is much faster there https://wodby.com/docs/stacks/drupal/local/#docker-sync

**Comment by pirog** [comment]
@adriadrop id encourage you to read through some of the other issues about file sharing to get an answer to this

**Comment by danepowell** [comment]
To be just a little more specific... I think this is one of the best issues discussing file sharing performance: https://github.com/lando/lando/issues/763

The tl;dr in regards to docker-sync is that people have tried it but it's unreliable enough at scale to not really be viable for Lando. (this is just my interpretation, I'm not a Lando maintainer)

Hopefully this helps future travellers like me landing here from Google and feeling a bit like they've hit a dead end...
