### ISSUE TITLE
Drupal Console not working - No such file or directory

### ISSUE THREAD

**Issue by mardenborough** [lando/lando#1229]
We have been unable to get  Drupal Console to work in Lando. We have tried all of the following, and still get "No such file or directory" when we run the command: **lando drupal**
 
lando rebuild
lando composer require drush/drush
lando composer require drupal/console:~1.0
lando composer update
lando restart
 
None of these worked. We have uninstalled/re-installed Lando and Docker, to no avail. Any help/suggestion is appreciated. Thanks

**Comment by mardenborough** [comment]
We are on PCs

**Comment by mardenborough** [comment]
Thank you Marcel! This works

**Comment by marceldobrica** [comment]
I think documentation is not so clear regarding what we may use  in config....
I found that is better not to mention drush and drupal in drupal8 config file at all. In fact if you mention drupal that means drupal: false (the only option you have - i beleave....).... drush has more options but for drupal8 (drupal 8 composer) is also better to not mention it at all.
I didn't realize also why from time to time after rebuild, restart, start you may have a situation in which drush and drupal are not installed ... (mv is not executed.. I have opened an issue also but I have closed it ... I hope today I'll better understand what is happening... in my opinion some containers are not rebuild with lando rebuild.... I'll verify)

**Comment by mardenborough** [comment]
Greetings Marcel, I have gotten both lando drush and lando drupal to work on my machine. With the others, only lando drush works
