### ISSUE TITLE
Proxy issue I had for a long time

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1235]
I'm using this proxy setting to access my site at local.project.com:

    proxy: 
      appserver:
        - local.project.com

But with this command both http and https are red on my system. I then found out a 'fix' for this from my colleague:

    services:
      appserver:
        portforward: 8080
        overrides:
          services:
            ports: ['8080:80']

This makes port 80 work but https has always been red for me (for many months). I've never seen it green.

Some of my colleagues are using linux and I found out that they don't need this port forwarding and both urls are ok.

Then I asked my other colleague again (who advised me on the port forward trick) and he said he got it working finally on his mac when he re-installed the OS. He said I should get it working by uninstalling any software that could potentially break it. So I tried removing different kinds of software that I had installed with Homebrew like php7, mysql etc. Didn't work.

I tried to find ports that are being used on 80 and 443. There aren't any.

Today I installed the latest version of Lando (v3.0.0-rc.1) in hopes of help but that did not help either.

Then finally I remembered that 2 softwares I've seen altering networking - Virtualbox and Vagrant. I uninstalled both, rebooted computer and now both http and https are green. For the very first time after using Lando for half a year. Wow!

I tried to find help from internet but could not find any so I'm posting this here for others. May be this could be more investigated and some kind of detection could be built in the Lando.

My OS version is MacOS Sierra 10.12.6

**Comment by hkirsman** [comment]
I take my words back, it's broken again and I don't know how to debug this. No errors, ports 80 and 443 are taken by Docker and they are free when Docker is closed.

**Comment by hkirsman** [comment]
Again.. I delete Docker, Lando, rm -rf ~/.lando

I start my app and I can access it without any hacks.
```
NAME            sitecom                                                     
 LOCATION        /Users/hannes/Sites/site_com                                
 SERVICES        appserver, database, ruby, elasticsearch, memcached, mailhog 
 APPSERVER URLS  https://localhost:32780                                      
                 http://localhost:8080                                        
                 http://localhost:32779                                       
                 http://local.www.site.com                                   
                 https://local.www.site.com                                  
 MAILHOG URLS    http://localhost:32774
```
I restart my app and and both http://local.www.site.com and https://local.www.site.com   are red.

 ```
NAME            sitecom                                                     
 LOCATION        /Users/hannes/Sites/site_com                                
 SERVICES        appserver, database, ruby, elasticsearch, memcached, mailhog 
 APPSERVER URLS  https://localhost:32863                                      
                 http://localhost:32864                                       
                 http://local.www.site.com                                   
                 https://local.www.site.com                                  
 MAILHOG URLS    http://localhost:32862 
```

**Comment by dustinleblanc** [comment]
It looks like you've altered the proxy domain, which will only work if you have a DNS resolver setup to route those domains to local, either via DNSMasq or a hosts file, etc. These configs are only suggested to use if absolutely needed. Currently, using a custom proxy domain is also incompatible with our certificates (though I think we fixed this in rc1, right @pirog?).

In regards to other programs hogging 80/443, Lando tries to fallback to other ports if that happens. Sometimes Docker does do some funky stuff and hog the ports itself. If that happens, just reboot.

**Comment by pirog** [comment]
@dustinleblanc in RC1 if you change the proxy domain it will generate a new CA for you to use at `~/.lando/certs/${PROXYDOMAIN}.[key|pem]` and you will need to go through the normal CA whitelisting procedure documented over at https://docs.devwithlando.io/config/security.html if that is something you care about.

**Comment by hkirsman** [comment]
I'm using hosts file and there's no certificate warnings. Browser just can't connect to the site without adding those portforward commands in Lando. The same config works fine on other Mac and Linux machines. What should I be looking for? Something that blocks port 80?

**Comment by dustinleblanc** [comment]
It looks like Traefik is up on 80/443 in your case so nothing is blocking those ports on your system. The need to do funky port forwarding is likely app specific. It sounds like your application is running on a non-standard port and I don't know why that would be. I would suggest testing with a vanilla Drupal, etc app to see if you still get funky results

**Comment by hkirsman** [comment]
Here's the results for clean install of Drupal 7.

.lando.yml
    name: d7-high-contrast
    recipe: drupal7
    config:
      webroot: web
      php: '7.2'
      database: mysql:5.6
    services:
      appserver:
        xdebug: true
    tooling:
      drush:
        service: appserver
        cmd:
          - "drush --root=/app/web/"

After starting Lando I get:

     NAME            d7highcontrast                       
     LOCATION        /Users/hannes/Sites/d7_high_contrast 
     SERVICES        appserver, database                  
     APPSERVER URLS  https://localhost:32768              
                     http://localhost:32769               
                     http://d7highcontrast.lndo.site      
                     https://d7highcontrast.lndo.site

Both localhost urls are green and they work in browser, both d7highcontrast.lndo.site are red and don't respond in browser. Basically same results as with all other apps.

When pinging the domain, it responds:

    ping d7highcontrast.lndo.site
    PING d7highcontrast.lndo.site (127.0.0.1): 56 data bytes
    64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.095 ms
    64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.206 ms
    64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.187 ms

**Comment by hkirsman** [comment]
I did uninstall lot of software but didn't help. Finally what helped was clean install of MacOS.
