### ISSUE TITLE
Passing an environment variable at start

### ISSUE THREAD

**Issue by miiimooo** [lando/lando#1239]
Hey, I'm pretty new to lando and I'm trying to solve a situation I couldn't find covered in the docs or examples.

I'm trying to do something like this:

```
ENV=site1 lando composer install
```
And have the ENV set in scripts called as part of composer.

Or more general:

```
export ENV=site1
lando start
```

And have that ENV set in lando containers (appserver for instance).

I know it's possible to set environment variables in the .env file.

Is this possible without putting it into the .env file?

**Comment by tylerssn** [comment]
You could do something like: `lando ssh -c "ENV=1 composer install"`.

If composer is not installed on the appserver service and instead installed on a service called, let's say, "composer-service" you could modify the command to: `lando ssh composer-service -c "ENV=site1 composer install"`

**Comment by pirog** [comment]
@miiimooo i would check out our documentation and examples as there are a few different ways you can do this
