### ISSUE TITLE
Lando poweroff should not output warnings about .env file

### ISSUE THREAD

**Issue by hailwood** [lando/lando#1242]
Bug Report
==========

v3.0.0-rc.1 on Ubuntu 18.04

When running `lando poweroff` you'll get a warning 
> warn: Trouble parsing .env file with Error: ENOENT: no such file or directory, open '.env'
Repeated, I believe, once for every lando project you have. 

While it doesn't stop lando from powering off, it seems like something that should not happen:
![image](https://user-images.githubusercontent.com/709773/46768567-1dba8280-cd45-11e8-9c5e-20f72633433d.png)

**Comment by tylerssn** [comment]
PR https://github.com/lando/lando/pull/1246 addresses this.

**Comment by pirog** [comment]
Should be fixed as part of https://github.com/lando/lando/pull/974#issuecomment-453836939 and will be in RC2
