### ISSUE TITLE
error: fatal: destination path '.' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by tbenice** [lando/lando#1251]
This might be hard to reproduce im just hoping someone can give me an idea of what might be wrong.

I use pantheon. I had a pantheon lando site running but then it failed to pull stating that i was not authenticated. I ran lando auth:login --machine-token=MYTOKEN and it executed with no feedback. I still could not pull.
So, i did what my colleagues advised and deleted/destroyed the app and started fresh. What im doing is pretty simple:

$ mkdir priority-marketplace

$ cd priority-marketplace

$ ls -la
total 0
drwxr-xr-x@  2 tbenice  staff    64 Oct 19 14:26 .
drwxr-xr-x  33 tbenice  staff  1056 Oct 19 14:26 ..

$ lando init pantheon
? Choose a Pantheon account ted@bythewaylabs.com
? Which site? priority-marketplace
Starting landoinitprioritymarketplace_util_1 ... done
Scanning /user/.ssh for keys...
Scanning /lando/keys for keys...
Checking whether /user/.ssh/prod.passwd is a private key...
Checking whether /user/.ssh/.DS_Store is a private key...
Checking whether /user/.ssh/evermind-shared.pem is a private key...
Checking whether /user/.ssh/evermind-shared.pem is formatted correctly...
Checking whether /user/.ssh/id_rsa is a private key...
Checking whether /user/.ssh/id_rsa is formatted correctly...
Checking whether /user/.ssh/nexus-prod.passwd is a private key...
Checking whether /user/.ssh/ted.passwd is a private key...
Checking whether /user/.ssh/prod.ovpn is a private key...
Checking whether /user/.ssh/prod.ovpn is formatted correctly...
Checking whether /user/.ssh/nexus-aws-keys.txt is a private key...
Checking whether /user/.ssh/evermind-prod.pem is a private key...
Checking whether /user/.ssh/evermind-prod.pem is formatted correctly...
Checking whether /user/.ssh/evermind-test.pem is a private key...
Checking whether /user/.ssh/evermind-test.pem is formatted correctly...
Checking whether /user/.ssh/nexus-prod.pem is a private key...
Checking whether /user/.ssh/nexus-prod.pem is formatted correctly...
Checking whether /user/.ssh/shared.ovpn is a private key...
Checking whether /user/.ssh/shared.ovpn is formatted correctly...
Checking whether /user/.ssh/shared.passwd is a private key...
Checking whether /user/.ssh/dev.ovpn is a private key...
Checking whether /user/.ssh/dev.ovpn is formatted correctly...
Checking whether /user/.ssh/dev.passwd is a private key...
Checking whether /user/.ssh/ted.ovpn is a private key...
Checking whether /user/.ssh/ted.ovpn is formatted correctly...
Checking whether /user/.ssh/prod-default.passwd is a private key...
Checking whether /user/.ssh/start.sh is a private key...
Checking whether /user/.ssh/prod-default.ovpn is a private key...
Checking whether /user/.ssh/prod-default.ovpn is formatted correctly...
Checking whether /user/.ssh/nexus-prod.ovpn is a private key...
Checking whether /user/.ssh/nexus-prod.ovpn is formatted correctly...
Checking whether /lando/keys/pantheon.lando.id_rsa is a private key...
Checking whether /lando/keys/pantheon.lando.id_rsa is formatted correctly...
Ensuring permissions for /user/.ssh/id_rsa...
Ensuring permissions for /lando/keys/pantheon.lando.id_rsa...
Using the following keys: /user/.ssh/id_rsa /lando/keys/pantheon.lando.id_rsa
Starting landoinitprioritymarketplace_util_1 ... done
fatal: destination path '.' already exists and is not an empty directory.
error: fatal: destination path '.' already exists and is not an empty directory.

------------------------------------
My Setup:

MacOS 10.3.6
lando version v3.0.0-rc.1
docker version 18.06.1-ce-mac73

any help at all will be awesome. I even tried rebooting my machine a few times to no avail ;)

thanks in advance,

Ted

**Comment by tbenice** [comment]
apparently i can init a different pantheon site, just not this one. strange.

**Comment by tbenice** [comment]
looks like i needed to find and stop/remove all containers that might be part of lando. i also just removed all images i had too. I had a hiccup at first with "Pantheon\Terminus\Exceptions\TerminusException: Could not save data to a file because the path /var/www/.terminus/cache/commands cannot be written to" but then i did a rebuild and it seems to be working.

**Comment by dutton242** [comment]
I ran into this too. Fixed by running the following commands:
`docker container ls`
Get the container ID of the problem child
`docker container kill CONTAINER_ID`
`docker container rm CONTAINER_ID`
`lando destroy APPNAME`
Delete the local files, recreate an empty directory and then:
`lando init pantheon`
