### ISSUE TITLE
Add PHP 5.2 image(s)

### ISSUE THREAD

**Issue by nylen** [lando/lando#1256]
Feature Request
===============

As a lando user who works with WordPress core and WordPress plugins, I'd like to be able to test my code on PHP 5.2 without trying to download and install that ancient version locally.

Ideally WordPress should have already ended support for 5.2 a long time ago, but I guess they have a lot to plan and consider before making that move.

The image `devwithlando/php:5.3-apache` already exists, so this issue is to request the creation of a similar image `devwithlando/php:5.2-apache`.

**Comment by dustinleblanc** [comment]
@nylen I don't think we're going to create a new docker image for a PHP version that old. It's a surprise we still have 5.3. There are various community docker images though that may work. We allow you to override default docker images for any service so you might just want to add in your own docker file that includes the customizations

**Comment by nylen** [comment]
> We allow you to override default docker images for any service

Reference: https://docs.devwithlando.io/config/advanced.html#using-dockerfiles

I'll look into this further.  Thanks!

**Comment by Ugoku** [comment]
FYI: WordPress has announced that starting in April, the minimum supported PHP version will be 5.6: https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/
