### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1264]
**System :** Archlinux (Cible : x86_64-pc-linux-gnu)

**Docker version :** 18.06.1-ce, build e68fc7a215

**Lando version :** v3.0.0-rc.1

**Project folder:**
![1](https://user-images.githubusercontent.com/1313428/47521476-045c1f00-d88b-11e8-9011-e4e4190cd55c.png)

**Lando file:**
```
name: lando-and-drupal
recipe: drupal8
config:
  webroot: .
```
**lando start:**
![2](https://user-images.githubusercontent.com/1313428/47521762-c8758980-d88b-11e8-9fbe-28229d123449.png)

**Check page:**
![deepin capture-ecran_zone de selection _20181025192717](https://user-images.githubusercontent.com/1313428/47521861-070b4400-d88c-11e8-9b3f-20b7b1005ac2.png)

**Containers list:**
![3](https://user-images.githubusercontent.com/1313428/47521720-aaa82480-d88b-11e8-9379-3638b58db8f3.png)

any idea to fixe this probleme ??

**Comment by mm4492** [comment]
Have you tried removing the webroot key all together? I believe it's only necessary if using a composer installation that would install drupal into a subdirectory (usually web)

**Comment by kamalkech** [comment]
@mm4492 i fixe this error with : 

```
lando poweroff
docker system prune
lando start
```

**Comment by thistehneisen** [comment]
Have the same issue, but did not fix by poweroff, prune and start.
```
nils at nilsdigital in ~/P/DEV
» docker system prune
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all build cache
Are you sure you want to continue? [y/N] y
Deleted Containers:
4fd44f9419810b3d18afafff1f8171c62d40a803a6f51d3f3785b6673f535125
a8b4e4367ad10207191084321376ba0f974d1b6b3d30c12c13cd75d9a9e41773
0353524531e7515d28fdb3d721e93bf7335f6172dad90ffa235777c36a2f51e3
1c3adbf8c1d87396cf3d72f24dc4fdd75c70fd7d511853c1f41bd37fc22c5eda

Deleted Networks:
dev_default
lando_bridge_network
landocasetupkenobi38ahsoka6b3b1063ecd7f3f957ac71dc2ddbbbbd73c3181c_default
landoproxyhyperion5000gandalfedition_edge

Total reclaimed space: 59.22MB
nils at nilsdigital in ~/P/DEV
» lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "dev_default" with the default driver
Creating dev_appserver_1 ... done
Creating dev_database_1  ... done
Creating dev_nginx_1     ... done
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...
Waiting until nginx service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME        dev
 LOCATION    /Users/nils/Projects/DEV
 SERVICES    appserver, nginx, database
 NGINX URLS  https://localhost:32787
             http://localhost:32788
             http://dev.lndo.site
             https://dev.lndo.site
```

Still returning 404 Error.

**Comment by kamalkech** [comment]
@thistehneisen
1- are u run forst "lando poweroff" ?
2- can you print version of lando and docker ?

**Comment by thistehneisen** [comment]
Yes, I did run poweroff.
```
nils at nilsdigital in ~/P/DEV
» docker -v
Docker version 18.06.1-ce, build e68fc7a
nils at nilsdigital in ~/P/DEV
» lando version
v3.0.0-rc.1
```

**Comment by thistehneisen** [comment]
Nevermind, my error was that webroot was /web/, but index.php was placed in parent directory.

**Comment by kamalkech** [comment]
update lando to v3.0.0-beta.47

**Comment by ElijahLynn** [comment]
> @mm4492 i fixe this error with :
> 
> ```
> lando poweroff
> docker system prune
> lando start
> ```

Dear internet, this answer is confirmed to still work for me on v3.0.0-rc.9 as of today.

**Comment by ibdf** [comment]
> > ```
> > lando start
> > ```

This magic also worked for me.

**Comment by cdubz** [comment]
In 2021 on Lando v3.1.4 just use `lando rebuild` -- it does effectively the same thing but doesn't affect other docker containers (as `docker system prune` does).

**Comment by neelam-chaudhary10** [comment]
```
lando poweroff
docker system prune
lando start
```
Didn't work for me but deleting the lando proxy container and doing lando start again worked.

**Comment by fractalf** [comment]
I get the same, but for me it seems to be connected to the fact that I'm using **nginx** instead of apache (default)

That also gives me this...
```
ERROR ==> You cannot assign url alf.lndo.site/:80 to more than one service! 
```

```yml
name: alf
recipe: laravel
config:
  via: nginx
  php: '8.1'
  webroot: public
  config:
    php: ./php.ini
proxy:
  appserver:
    - alf.lndo.site
services:
  appserver:
    extras:
      - apt-get -y update

```

**Comment by KishanThakurRspl** [comment]
> In 2021 on Lando v3.1.4 just use `lando rebuild` -- it does effectively the same thing but doesn't affect other docker containers (as `docker system prune` does).

Worked for me

**Comment by ahmedch1** [comment]
> In 2021 on Lando v3.1.4 just use `lando rebuild` -- it does effectively the same thing but doesn't affect other docker containers (as `docker system prune` does).
I have tested this solution lando rebuild and it has worked for me also.

**Comment by aabrah25** [comment]
> @mm4492 i fixe this error with :
> 
> ```
> lando poweroff
> docker system prune
> lando start
> ```

This worked for me. Thank you!

**Comment by ttrench** [comment]
> @mm4492 i fixe this error with :
> 
> ```
> lando poweroff
> docker system prune
> lando start
> ```

October 2023 and this fixes the issue perfectly! Thank you so much!

**Comment by Tshewang2022** [comment]
Sometimes you will get the 404 errors in the lando no matter what you try. In both Drupal and WordPress you will get. The problem is that your WordPress projects do not get connected to the default ports of 443, and:80. So that means that your port is already occupied by some projects or the projects that you might not deleted properly. So to fix that problem you have to first. Delete the port from the docker containers. To do that run the

sudo lsof -n -i :80 | grep LISTEN

This command will list port 443 and 80

After that remove that container using the docker rm command

Now if you restart the project you should get the connection error in the 3rd and 4th link, because port 80 is for the local server(http) and 443 is for the https://


Now delete the lando from your machine
sudo apt-get remove lando
sudo dpkg -P lando

this command will show and delete all the docker containers containing lando, that is left and when you delete the lando. 

docker rm -f $(docker ps --filter label=io.lando.container=TRUE --all -q)

Reinstall the lando and work perfectly fine for me.

**Comment by varodbr** [comment]
Hi there!

I was suffering with this problem and usually when this happened it was because I had previously started lando in another project, and then with `lando start` in the second project the traefik, for some reason I didn't look for, didn't start with the correct references. So, I usually had to stop and remove the traefik container and start again with `lando rebuild`.

This was not working this time, not even with
```
lando poweroff
docker system prune
lando start
```

After spending some hours with remove and rebuild, I decided to make the same with the PHP container `devwithlando`.
```
lando poweroff
docker rm php-container-id
lando rebuild -y
```

Voilá, no more error 404.

In my experience, until now, this problem happens usually with one of these two, traefik or php container.

**Comment by queenvictoria** [comment]
I'm getting this sporadically and recently never having had a problem before on Ubuntu 20.04. It seems like after a recent system update (or installation of some other package, or some kind of PEBSAK) Apache decides to become a default service. So stop that:
```bash
$ sudo systemctl stop apache2
$ sudo systemctl disable apache2
$ lando restart
```

**Comment by abitofbrit** [comment]
> @mm4492 i fixe this error with :
> 
> ```
> lando poweroff
> docker system prune
> lando start
> ```

Hallelujah! Confirmed this worked for me in 2024! 🎉

**Comment by ducviethaboo** [comment]
> > @mm4492 i fixe this error with :
> > ```
> > lando poweroff
> > docker system prune
> > lando start
> > ```
> 
> Hallelujah! Confirmed this worked for me in Oct 2024! 🎉

Still worked like a charm in Jan 2025 !

**Comment by jasperf** [comment]
I used
```
lando poweroff
docker system prune
lando start
```

I tried 
```
name: autentical
recipe: wordpress
config:
  webroot:
  php: "8.3"
  via: nginx
  database: mysql:8.0
```

and

```
name: autentical
recipe: wordpress
config:
  webroot: .
  php: "8.3"
  via: nginx
  database: mysql:8.0
```

But I keep on getting a 404 loading `index.php`. I use this in `wp-config.php`:
```
...
if (getenv(name: 'LANDO')) {
	error_log('LANDO environment variable is set.');
	/** The name of the database for WordPress */
	define('DB_NAME', 'wordpress');
	/** MySQL database username */
	define('DB_USER', 'wordpress');
	/** MySQL database password */
	define('DB_PASSWORD', 'wordpress');
	/** MySQL hostname */
	define('DB_HOST', 'database');
	/**
	 * Summary: Multisite configuration Lando
	 */
	define('MULTISITE', true);
	define('WP_ALLOW_MULTISITE', true);
	define('DOMAIN_CURRENT_SITE', 'autentical.lndo.site');
	define('SUBDOMAIN_INSTALL', value: false);
  
	/** URL routing (Optional, may not be necessary) */
	define('WP_HOME','https://autentical.lndo.site');
	define('WP_SITEURL','https://autentical.lndo.site');

  }
  else {
    error_log('LANDO environment variable is NOT set.');
}
...
```

and that seems to work, but I get a 404 and no other feedback. Also changed
```
define( 'SUNRISE', 'on' );
```

to 
```
define( 'SUNRISE', 'off' );
```

but that did not matter either. So why can I just not load main wp multi site site ? Database is there, core files are there..
