### ISSUE TITLE
Drupal 8 / Drush / Linux

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1270]
- System: archlinux

after start lando i get this message error : Failed to create the file drush.phar: Permission denied

any idea ?

**Comment by uberhacker** [comment]
@kamalkech:  Are you using version v3.0.0-rc.1?  There is a known problem with permissions in that release.  Try downgrading to v3.0.0-beta.47 until the next release is available.  Hope that helps.

**Comment by kamalkech** [comment]
@uberhacker yes it's work with downgrading !!, there are some bugs with v3.0.0-rc.1, thank you for your help.
