### ISSUE TITLE
Inter-service networking does not seem to work on the Pantheon recipe

### ISSUE THREAD

**Issue by acobster** [lando/lando#1274]
Bug Report
==========

In short, inter-service networking does not work for me on the `pantheon` recipe. The connection is refused when trying to `curl` from one service to another:

Lando config:

```yaml
name: my-app
recipe: pantheon
config:
  # ...
```

STR:

```bash
lando start
lando ssh -s database -c 'curl appserver'
```

This isn't specific to `database`-to-`appserver` communication: no other service seems to be able to talk to `appserver`. It does seem specific to the `pantheon` recipe, however. For example, this works when using the `wordpress` recipe.

PR with a failing functional test is forthcoming.

**Comment by pirog** [comment]
@acobster for the pantheon recipe `appserver` is just a php-fpm instance, it is not a webserver so this is actually the expected behavior. `nginx` is the webserver so you probably want to curl that or run `lando info` and choose a hostname from there.
