### ISSUE TITLE
`lando init pantheon` Failed after 5 retries with backoff 500 and error

### ISSUE THREAD

**Issue by ajsaucier** [lando/lando#1278]
Bug Report
==========

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests) and submit it as a pull request.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Mac OS High Sierra version 10.13.6

Lando v3.0.0-rc.1

**Tell us about your `.lando.yml`**

```yml
name: lando-local-test
recipe: pantheon
config:
  framework: wordpress
  site: lando-local-test
  id: 79405cd9-8104-4797-b06c-31caaabe4002
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

lando pull

**Tell us about the error you got**

```bash
lando pull -- -vvvv
```

``` bash
error: Error: Failed after 5 retries with backoff 500 and error Error: Request failed with status code 401
    at createError (/snapshot/lando/build/cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/lando/build/cli/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/snapshot/lando/build/cli/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at createError (/snapshot/lando/build/cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/lando/build/cli/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/snapshot/lando/build/cli/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Promise.resolve.then.Promise.try.fn.catch.err (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
From previous event:
    at Promise.resolve.then.Promise.try.fn.catch.err (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Tell us generally about your bug**

I've been trying to pull the just the code from my pantheon site and started getting this error when doing a pull. lando start works, the site spins up fine. I've tried logging out of terminus, revoking token, making a new token and logging back into terminus with that one. I've tried lando rebuild. I simply cannot get this to work anymore. It worked fine two days ago. No changes have been made.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. Followed the steps on your documentation of local development with Pantheon
2. After following those steps, was able to get lando working, created site change and pushed to Pantheon
3. Created multi-dev environment to make sure it worked if one developer was using SFTP connection mode instead of Git
4. Made a change via SFTP, made a change to the same file as lando, committed through Pantheon dashboard with file conflict
5. Undid change to file via SFTP, merged changes to dev environment
6. Tried doing a lando pull to make sure everything was in sync, started getting more simple error that I was not logged in and to check machine token
7. After trying a few more times, started getting the full error: Failed after 5 retries with backoff 500 and error Error: Request failed with status code 401
```

**Comment by ajsaucier** [comment]
Update: I tried deleting multidev environment again and doing lando pull, same error. I then tried running lando rebuild again, and this error comes up: [error]  
```Client error: `POST https://terminus.pantheon.io/api/authorize/machine-token` resulted in a `401 Unauthorized` response:
"Authorization failed. Please check that your machine token is valid."```

**Comment by ajsaucier** [comment]
```lando terminus auth:login --machine-token=MYSPECIALTOKEN``` returns nothing, ```lando pull``` still throws 500 error. I know the machine-token is valid.

**Comment by dustinleblanc** [comment]
@ajsaucier the last time I had this happen to me it was because I had a corrupt token in my Lando cache. try `rm -r ~/.lando/cache` and then re-try the pull

**Comment by d3vit** [comment]
> @ajsaucier the last time I had this happen to me it was because I had a corrupt token in my Lando cache. try `rm -r ~/.lando/cache` and then re-try the pull

How is this performed on a Windows machine? Have the same issue for this but am unable to find cache directory

**Comment by doostinharrell** [comment]
@dustinleblanc I had this same issue with `lando poweroff` and your solution of `rm -r ~/.lando/cache` appears to have resolved my issue.  I just recently updated lando from beta 48 to rc1 and macOS from High Sierra to Mojave when I first saw this issue if that's helpful.

**Comment by ahimsauzi** [comment]
@dustinleblanc unlike @doostinharrell, this did not work for me on mac Sierra running lando rc1. I tried empty .lando cache, fresh machine token still no love.

**Comment by betweenbrain** [comment]
I'm having the same issue as @ahimsauzi. I'm on macOS High Sierra (v10.13.6), Lando vv3.0.0-rc.1 and went as far as to:
1. `m -r ~/.lando/cache`
2. Generate a new machine token with Pantheon
3. `lando terminus auth:login --machine-token=XXXXX`
4. `terminus auth:whoami` responds with the correct user
5. `lando pull` responds with _error: Looks like you dont have a machine token!_

**Comment by ahimsauzi** [comment]
My apology, after running `m -r ~/.lando/cache `and creating a new token, I missed that the error change to: `Error: Failed after 5 retries with backoff 500 and error Error: Request failed with status code 404`

I solved the issue by verifying the id in my lando.yml against the Pantheon site. Somehow, the two were different.

**Comment by pirog** [comment]
We have implemented VASTLY superior auth handling in RC2 which we are going to release this week. Going to close this as solved in RC2. If after trying RC2 you are still experiencing issues please open a new ticket against that version
