### ISSUE TITLE
Generate CA signed certificate for wildcard domain *.lndo.site

### ISSUE THREAD

**Issue by com2** [lando/lando#1279]
Feature Request
===============

For my development work I always use Firefox first, then other browsers for testing. That is because I work for a company that only accepts this Firefox on its Intra- and Extranet sites. Firefox has a [known issue](https://www.thesslstore.com/blog/troubleshoot-firefoxs-tls-handshake-message/) with self signed certificates causing annoying TLS negotiation delays.

It would be very helpful when the Lando development team at some point would provide CA signed certificates for the *.lndo.site. The CA certificate itself does not need to be authoritative, can itself be self-signed, but it should be generated once by the Lando team and then kept the same in all releases (not regenerated when the container is build).  The with CA signed *.lndo.site certificate will cause the CA to appear in the Authorities tab of the certificate manager allowing the developer to approve its authority once and for all. From then on all *.lndo.site domains will stop showing the certificate warning and overrides are not longer necessary. It would both minimize the Firefox issue and make live easier for developers. All in all I only see advantages.

**Comment by com2** [comment]
[Here an example](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/) of generating CA cert

**Comment by dustinleblanc** [comment]
@com2 we actually do generate these certs, the only step we're missing is to automatically trust those certificates. If you know of some concise magic to get the CA cert trusted in all environments and browsers on all OSes, I'd love to finish up that ticket :)

See https://docs.devwithlando.io/config/security.html

**Comment by com2** [comment]
You can also distribute your CA certificate unsigned by any officially accepted authority. We can import it and manually approve trust. From then on it is valid until we remove it or untrust it. From then on, all certificates signed by your CA recognised as valid in our browser(s). 

Presently the *.lndo.site certificate is re-generated for every instance, which is completely unnecessary, because it is a wildcard certificate. The certificate manager has several different instances for the same domain, because in each lando container instance it is a different certificate. It needs only be generated once by you on your system, then distributed unchanged in lando. When your own fixed (not regenerated) CA is also distributed, then you can even change domain, as long as the CA cert is previously imported as Authority and trusted in our browser, and as long as you on your system do not re-generate the CA for a new domain, if you would ever do that. CA certificates and wildcard certificates are supposed to be generated once and reused. 

Added bonus is that it saves time, when the certificates are distributed ready for use in stead of regenerated at build.
