### ISSUE TITLE
Lando LAMP performance

### ISSUE THREAD

**Issue by vielhuber** [lando/lando#1282]
Hello!

I use Lando Bleeding Edge with Docker Community Edition on 18.0.6.1.

I setup a LAMP server with a basic WordPress site.

The site suffers from loading times around ~1-2s. On a production server I have 300ms.

I increased the docker settings: 
![image](https://user-images.githubusercontent.com/3183737/48036533-1c744e00-e169-11e8-942b-ad8807a3f004.png)

Response time are a bit better now (1s).

A simple question: Do I have to accept that in docker world or do you have better response times (like on production) also on your environments?

Perhaps this has something todo with the shared folders?

**Comment by vielhuber** [comment]
Another improvement: Switch to edge version of Docker (2.0.0.0-beta1-win75).
This is still a little bit better.

The bottleneck seems to be the filesharing speed.

Does everybody experience those problems?
Has somebody successfully included tools like docker-sync?

**Comment by vielhuber** [comment]
Other tools like devilbox now use the new "cached" filesystem directive:
See here: https://github.com/cytopia/devilbox/issues/105
Docker for mac native also includes this: https://github.com/docker/for-mac/issues/77

Does lando have plans to include that also? Seems to be a significant performance improvement.

**Comment by dustinleblanc** [comment]
Hi @vielhuber! See #763. I am going to close this as a duplicate. Thanks!
