### ISSUE TITLE
xdebug "html_errors" config never gets set

### ISSUE THREAD

**Issue by kevinquillen** [lando/lando#1285]
I have a php.ini config file that appears to make it into Lando, all except one value (which works on other projects):

`html_errors=On`

Lando reports html_errors as being Off, and nothing I do seems to reverse this. The only difference of this project vs the other 4 is this one is Drupal 8 based. Without this, all I can see is "The website encountered an unexpected error." and nothing more.

**Comment by pirog** [comment]
@kevinquillen i cant replicate this on latest RC release but i did add a test for it. 
https://github.com/lando/lando/tree/master/examples/php

id upgrade and see if you experience the same. id also note that if this works on a bunch of lando apps but not one there is a chance you are setting it somewhere in your applications code and that might be your issue
