### ISSUE TITLE
Feature Request: command-line support for ruby/node CJK (Chinese / Japanese / Korean languages)

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#1293]
Feature Request
--------------------------------

I'm using 3.0-rc1.  I have a Japanese language site and it would be great if there was better support for CJK (Asian language) ruby/node.  To be honest, I don't know exactly what needs to be done to get this working, but if I find out, I'll update this post with the necessary steps.

**Ruby**

* I installed ruby/compass following the documentation.  But, when I run `lando compass watch css`, I get this error:

>     error css/sass/style-sass-generated.scss (Line 47 of css/sass/component/_form.scss: Invalid US-ASCII character "\xE2")

If I install compass in Windows 10 and run "compass watch css" through Powershell (avoiding Lando), the SASS compiles without any trouble.

 **Node**

I installed backstopjs according to the documentation.  However, when I run `lando backstop reference`, all of the screenshots display the Japanese characters as the same square pattern.

**Comment by tylerssn** [comment]
Does adding `@charset "UTF-8";` to the top of the stylesheet resolve the issue for you?
