### ISSUE TITLE
error: (HTTP code 404) no such container - No such container:

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#1297]
Bug Report
==========

**Tell us about your setup**

*Lando Version*: v3.0.0-rc.1

*Mac OSx Version*: 10.14 Mojave

**Tell us about your `.lando.yml`**

There is none.

**Tell us about the command you were running**

I ran `lando init pantheon` to initiate a new app creation for a WordPress hosted on Pantheon.
I received the following output:
```
? Choose a Pantheon account my@email.com
? Which site? cloudsponge
Starting landoinitcloudsponge_util_1_3494c4dd07ed ... done
Starting landoinitcloudsponge_util_1_3494c4dd07ed ... done
error: (HTTP code 404) no such container - No such container: landoinitcloudsponge_util_1 
alexanders-MacBook-Pro-2:cloud-sponge alex-vasquez$ 

```

**Tell us more**

I also tried the following commands:
* In terminal i typed `docker ps -a` and did find a docker container with cloudsponge. I then ran `docker stop [container_name]` and then ran `docker rm [container_name]` which removed the container. I tried re-running the init command again and I still received the same error. There is also no config files and no log files.

The site i'm working with on Pantheon has a live environment, too. Not sure what's weird about this install.

**Comment by jimshreds** [comment]
Getting same error after updating Docker Desktop 

Docker Desktop Version 2.0.0.0-mac78 (28905) 
Lando  v3.0.0-rc.1
OSX 10.13.6

**Comment by jimshreds** [comment]
Getting error after updating Docker Desktop this morning.

Docker Desktop Version 2.0.0.0-mac78 (28905) 
Lando  v3.0.0-rc.1
OSX 10.13.6
lando.yml:
name: dfh
recipe: drupal7
config:
  webroot: .

**Comment by jimshreds** [comment]
downloaded previous version of Docker Desktop : https://docs.docker.com/docker-for-mac/release-notes/

lando rebuild a few times and am back up and running

**Comment by digisavvy** [comment]
That worked for me, too. Thank you!

**Comment by darthsteven** [comment]
I imagine this is error was because of the change in naming containers created by Docker compose in [1.23.0](https://github.com/docker/compose/releases/tag/1.23.0):

> . The default naming scheme for containers created by Compose in this version
has changed from <project>_<service>_<index> to <project>_<service>_<index>_<slug>, where <slug> is a randomly-generated hexadecimal string. Please make sure to update scripts relying on the old naming scheme accordingly before upgrading.

So I think lando will have to change and fix this, rather than getting everyone to stay with an older version of docker compose.

**Comment by tmountjr** [comment]
For anyone in the same situation as @digisavvy and @jimshreds, I discovered a shortcut to clearing out your broken builds - go into your `~/.lando` folder, delete any files or folders named the same as the one that was giving you an error, then build again. Simply destroying doesn't quite get everything but my experience was that deleting those files (at least the ones in the `compose` folder) let me get up and running quickly.

**Comment by nathandentzau** [comment]
This actually looks like a bug in RC1. I do not get this error rolling back Lando to Beta 47. Here are my docker versions:

<img width="558" alt="screen shot 2018-11-26 at 12 09 26 am" src="https://user-images.githubusercontent.com/15371196/48994134-93b95400-f10f-11e8-8872-9ec9e4a4e7c6.png">

**Comment by johnpicozzi** [comment]
I can confirm I was having the same issue. downgrading to Beta 47 worked for me as well. 

Used the following to install Beta 47 again via brew
`brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/645dbb8228ec2f1f217ed1431e188687aac13ca5/Casks/lando.rb`

Also noticed on the install that worked that it was able to create a cert and that seems to be where it failed before. 
![image](https://user-images.githubusercontent.com/6811770/49099246-f5c4a700-f23e-11e8-8e1e-ad8e90b8e677.png)

Hope this helps!

**Comment by astolfivincent** [comment]
This is happening to me to too after updating from docker 17.12.0-mac55 to 2.0.0.0-mac78

I'm getting the following error:

```
Looks like one of your build steps failed with Error: (HTTP code 404) no such container - No such container: project_appserver_1 
```

Upon a lando rebuild/start it starts an appserver that is named `project_appserver_1_a17c78ef8c82`, which it didn't used to, more evidence that supports @darthsteven's idea of what's happening here:

> I imagine this is error was because of the change in naming containers created by Docker compose in [1.23.0](https://github.com/docker/compose/releases/tag/1.23.0):
> 
> > . The default naming scheme for containers created by Compose in this version
> > has changed from  to _, where  is a randomly-generated hexadecimal string. Please make sure to update scripts relying on the old naming scheme accordingly before upgrading.
> 
> So I think lando will have to change and fix this, rather than getting everyone to stay with an older version of docker compose.
> 
> @digisavvy any chance you could re-open this issue please?

**Comment by dgpalmer** [comment]
Hi Mike,

When will RC2 come out?

Thanks!

**Comment by yuseferi** [comment]
the same issue after updating docker version ``` No such container: landoproxyhyperion5000gandalfedition_proxy_1```

**Comment by mdmattin** [comment]
Also having this issue after updating to Docker Version 19.03.5, with Lando Version v3.0.0-rc.22.

Error: Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
    at container.(anonymous function).catch.err (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at containerOpt (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at Landerode.remove (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at exports.destroy.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
From previous event:
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by mdmattin** [comment]
Updating to Lando Version v3.0.0-rc.22 fixed this problem. I guess the takeaway is don't update Docker independently of Lando.

**Comment by yuseferi** [comment]
@maddentim  I updated both, but the issue was there.  I tried on Mac Catalina 10.15.2

**Comment by wrg20** [comment]
> For anyone in the same situation as @digisavvy and @jimshreds, I discovered a shortcut to clearing out your broken builds - go into your `~/.lando` folder, delete any files or folders named the same as the one that was giving you an error, then build again. Simply destroying doesn't quite get everything but my experience was that deleting those files (at least the ones in the `compose` folder) let me get up and running quickly.

This worked for me.  I just deleted my app folder in ~/.lando and then did a lando start again after updating my docker desktop install.

**Comment by 1abdulaziz** [comment]
Thank you, @tmountjr , it worked for me.
