### ISSUE TITLE
Xdebug can't connect to host IP (timeout) 

### ISSUE THREAD

**Issue by MatthieuScarset** [lando/lando#1301]
Hi guys, 

Using the latest version of Lando `v3.0.0-beta.47`, I am having a hard time trying to use Xdebug.

I'm using VSCode with its xdebug extension. 
It is correctly listening on port 9000 and I've added the `pathMapping` as required (see https://docs.devwithlando.io/tutorials/lando-with-vscode.html).

I've added a custom `php.ini` file as follow : 
```bash
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0

; Extra custom Xdebug setting for debug to work in VSCode.
xdebug.remote_enable = 1 
xdebug.remote_autostart = 1
xdebug.remote_connect_back = 1
xdebug.remote_log = /tmp/xdebug.log
```

And this is the log in `/tmp/xdebug.log` : 
```bash
Log opened at 2018-11-19 12:52:57
I: Connecting to configured address/port: 192.168.1.67:9000.
E: Time-out connecting to client (Waited: 200 ms). :-(
Log closed at 2018-11-19 12:52:57
```

Issue seems to be that Xdebug does not manage to connect the host on port 9000.
I've double check and port 9000 seems to open and my client is listening on this port.

Do you know what could be the causes of this issue with remote debugging?

Any help will be much appreciated.

**Comment by agilec-paul** [comment]
Hi @MatthieuScarset ,
Can you upgrade your lando version? The latest is v3.0.0-rc.1 and there have been significant changes between the releases in the past.

Aside from that what is in your lando.yml file?

I've used VS Code with Lando Xdebug successfully on various projects so far.

**Comment by MatthieuScarset** [comment]
Oh Oh Oh ! I'm so happy it's working now...

I've upgraded to latest release.

I've forced port 9000 to open with:
`sudo iptables -A INPUT -p tcp -d 0/0 -s 0/0 --dport 9000 -j ACCEPT`

Here is my `.lando.yml`:
```
name: myapp
recipe: drupal8
config:
  webroot: web
  xdebug: true
  conf: 
    php: .vscode/php.ini  
```

Here is the custom `.vscode/php.ini` file:
```
[PHP]

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0

; Extra custom Xdebug settings to debug in VSCode.
xdebug.remote_enable = 1 
xdebug.remote_autostart = 1
xdebug.remote_host = ${LANDO_HOST_IP}
; xdebug.remote_connect_back = 1
xdebug.remote_log = /tmp/xdebug.log
```

Finally, here is the `.vscode/launch.json` file for VSCode:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "log": true,
      "pathMappings": {
        "/app/": "${workspaceFolder}/",
      }
    }
  ]
}
```

Hopefully this thread will help others in future.
