### ISSUE TITLE
Lando & Docker Desktop Community v2

### ISSUE THREAD

**Issue by sameronline** [lando/lando#1302]
When running Lando with the latest Docker v2  It seems to be stuck at the health checks "waiting until service is ready..." and doesn't move forward no matter how much you wait, using: Lando RC1, Docker 16 2.0.0.0-win78

The same Lando stack does work on another machine but has the previous version of docker v18.06.1-ce-win73

See also https://www.screencast.com/t/lThFxD0m

**Comment by pirog** [comment]
@sameronline please review the documentation, Lando only supports the version of docker we ship with.

**Comment by sameronline** [comment]
@pirog thanks for your feedback. I see, Where can i find out which version ships with latest Lando RC1?

**Comment by sameronline** [comment]
Ok i reverted back to 
```
Version 18.06.1-ce-win73 (19507)
Channel: stable
b0f14f1
```

I think we  need to look at why it doesnot work with the latest version though at later point

**Comment by dustinleblanc** [comment]
@sameronline agreed, we typically check against new docker releases when we are ready to cut a Lando release and go with the most up to date version we can that works properly, so this will probably happen when we next release, thanks!
