### ISSUE TITLE
[v3.0.0-rc.1] Docker 2.0.0.0-mac78 is not compatible with lando

### ISSUE THREAD

**Issue by wenzowski** [lando/lando#1307]
On MacOS 10.13.6 "High Sierra", installing with `brew cask install lando` does not reliably produce a working installation because the version of docker that lando relies on is now outdated. However, if the `dmg` file downloaded by caskroom is manually mounted and installed from gui, lando works correctly because the bundled docker is correctly installed at the right version. If docker is accidentally updated, almost all lando operations fail due to errors finding running containers by label.

Users presented with docker's auto-update window should skip `2.0.0.0-mac78` for lando `v3.0.0-rc.1`
![kfjgm0rsjh](https://user-images.githubusercontent.com/597920/48860236-53b04500-ed8e-11e8-9844-7179181d71ca.gif)

Since this is an evironment issue, a functional test cannot be created to isolate.

**Comment by GaxZE** [comment]
Duplicate of #1297

**Comment by wenzowski** [comment]
That issue’s older
