### ISSUE TITLE
Error packaging the CLI on Arch Linux

### ISSUE THREAD

**Issue by dmp1ce** [lando/lando#1309]
Trying to package lando cli on Arch Linux and I'm getting the following error:

```
> yarn pkg:cli
yarn run v1.12.3
$ node ./scripts/pkg.js
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/david/Projects/aur/lando-git/src/lando-git/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/david/Projects/aur/lando-git/src/lando-git/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/david/Projects/aur/lando-git/src/lando-git/node_modules/fs-extra/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Am I missing a dependency? Did I miss some documentation on how to package the CLI?

**Comment by dmp1ce** [comment]
I also get the same errors when trying to run `lando.js`. My version of node is

```
$ node --version
v11.2.0
```

**Comment by dmp1ce** [comment]
My original issue is solved by updating `fs-extra`. I had to run:

```
npm install fs-extra@0.18.4
npm install

yarn pkg:cli
```

**Comment by pirog** [comment]
@dmp1ce currently we expect that you run lando/build/compile with node `10.x`. I believe this requirement is documented.

**Comment by dmp1ce** [comment]
That makes sense. I can't find the documented requirements though.

**Comment by smmccabe** [comment]
I ran this with node 10.14.2 and I get the same error.

The problem seems to be that pkg changed it's requirements from fs-extra 6.0.1 to 7.0.1. Regenerating the lock file fixed this or just updating pkg.

I also couldn't find any mention of the node 10 requirement anywhere, I assume it should be in the build docs, but they just list the yarn commands and that is it.

**Comment by smmccabe** [comment]
Oh, wrong on the versioning of fs-extra, got crossed up with so many versions of fs-extra required. Updating it from 0.18.2 to 0.18.4 fixes it.

`yarn upgrade fs-extra`

**Comment by smmccabe** [comment]
I attempted to make a PR for this, but unit tests don't pass either with or without this fix. Looking at the CI jobs it appears node is only tested against node 8. I rolled back to node 8 and everything works without the need for any patches.

Is an PR to work with node 10 recommended or should I just update the docs to reference node 8.

**Comment by pirog** [comment]
We've updated `master` to run on node 10 and also made our dev deps doc more expliciy
https://docs.devwithlando.io/tutorials/drupal8.html#using-drush

**Comment by dmp1ce** [comment]
It also seems to be building on node 11 currently.
