### ISSUE TITLE
On more recent Docker versions, hashes added to container names, app fails to start

### ISSUE THREAD

**Issue by andileco** [lando/lando#1316]
***This is for future development: I know that only the version of Docker that comes with Lando is supported***

When using a more recent version of Docker (in my case, Version 2.0.0.0-mac77 (28700) Channel: Edge) and building a site for the first time in Lando, hashes get added to some containers, and then the app fails to start. Here's an example of the error:

<code>
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "myapp_default" with the default driver
Creating volume "myapp_data" with default driver
Creating volume "myapp_appserver" with default driver
Creating volume "myapp_data_database" with default driver
Creating volume "myapp_data_index" with default driver
Creating myapp_index_1_6a1c57b5617c ... done
Creating myapp_appserver_1_ae454b8b1420 ... done
error: Looks like one of your build steps failed with Error: (HTTP code 404) no such container - No such container: myapp_appserver_1
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
Starting myapp_index_1_64cf297fdc63 ... done
Creating myapp_cache_1_bb47a8b2ff77     ... done
Starting myapp_appserver_1_23c9915bfe49 ... done
Creating myapp_database_1_fbd1b8c60c23  ... done
Creating myapp_nginx_1_8abd3c0d8fe6     ... done
Creating myapp_edge_1_c8ef0eb4f148      ... done
Creating myapp_edge_ssl_1_708a46f2df6c  ... done
Waiting until edge_ssl service is ready...
Waiting until edge service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...
Waiting until cache service is ready...
Waiting until appserver service is ready...
Waiting until index service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
</code>
...
<code>
Builds, (re)creates, starts, and attaches to containers for a service.
Unless they are already running, this command also starts any linked services.
The `docker-compose up` command aggregates the output of each container. When
the command exits, all containers are stopped. Running `docker-compose up -d`
starts the containers in the background and leaves them running.
If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.
If you want to force Compose to stop and recreate all containers, use the
`--force-recreate` flag.
Usage: up [options] [--scale SERVICE=NUM...] [SERVICE...]
Options:
    -d, --detach               Detached mode: Run containers in the background,
                               print new container names. Incompatible with
                               --abort-on-container-exit.
    --no-color                 Produce monochrome output.
    --quiet-pull               Pull without printing progress information
    --no-deps                  Don't start linked services.
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
    --always-recreate-deps     Recreate dependent containers.
                               Incompatible with --no-recreate.
    --no-recreate              If containers already exist, don't recreate
                               them. Incompatible with --force-recreate and -V.
    --no-build                 Don't build an image, even if it's missing.
    --no-start                 Don't start the services after creating them.
    --build                    Build images before starting containers.
    --abort-on-container-exit  Stops all containers if any container was
                               stopped. Incompatible with -d.
    -t, --timeout TIMEOUT      Use this timeout in seconds for container
                               shutdown when attached or when containers are
                               already running. (default: 10)
    -V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving
                               data from the previous containers.
    --remove-orphans           Remove containers for services not defined
                               in the Compose file.
    --exit-code-from SERVICE   Return the exit code of the selected service
                               container. Implies --abort-on-container-exit.
    --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the
                               `scale` setting in the Compose file if present.

</code>
...
<code>
error: Failed after 5 retries with backoff 500 and error Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at dc (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at compose (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at exports.start.datum (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
</code>

I found the following issue on ServerFault, and it seems to explain what's happening with the hashes being added:
https://serverfault.com/questions/938050/how-to-prevent-docker-compose-appending-hashes-to-created-container-names

**Comment by ccharlton** [comment]
Roll back to previous Docker version. That fixed it for many of us.

**Comment by andileco** [comment]
Thanks for posting. I mostly just wanted to put this on the team's radar for future development.

**Comment by ccharlton** [comment]
> I think that at some point this change will find it's way back in...

That is my feeling too.

**Comment by pirog** [comment]
Newest `docker` and `docker-compose` will ship with RC2. We've spun up an internal ticket to track the possible re-introduction of the breaking change in future docker releases
