### ISSUE TITLE
Authentication fails on pull of files

### ISSUE THREAD

**Issue by rambletype** [lando/lando#1320]
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-rc.1 on Mac OS 10.14.1

**Tell us about your `.lando.yml`**

name: visitfredcom
recipe: pantheon
config:
  framework: wordpress
  site: visitfredcom
  id: ea5df46a-176c-4a27-9fbc-9e1c95f5a510

pantheon.yml is:
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1

**Tell us about the command you were running**
lando pull

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Note that `verbose` mode is run like this `lando command -- -vvv`. Paste in the error and the ~100 lines that proceeded it.

*Example:*

```bash
lando CMDTHATFAILED -- -vvvv
```

**Tell us generally about your bug**
When I do a pull, I'm getting my DB and my code, but it's giving an authentication failure on the files before it downloads anything
PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0
Logged in as xxx@xxxx.xxxx
Detected that xxxxxxxx is a wordpress site
Checking for /lando/keys/pantheon.lando.id_rsa
PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0
1543970501_backup_files
Pulling files from dev...
Received disconnect from 104.198.239.24 port 2222:2: too many authentication failures
Authentication failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [Receiver=3.1.2]

**Comment by rwohleb** [comment]
I'm currently seeing:
`Pulling files from dev...
ssh: Could not resolve hostname appserver.dev.INSTANCE_ID.drush.in: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.2]`

I removed my instance ID from the output for obvious reasons. The output is a bit different, so it may or may not be a different issue. Pulling the DB works just fine.

**Comment by rambletype** [comment]
You think maybe it's their server?

**Comment by rwohleb** [comment]
Doesn't seem to be the servers. I'm currently using the following work around:

In .lando.yml:
`
services:
  appserver:
    run:
      - mkdir -p ~/.terminus/plugins
      - composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1
      - composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-rsync-plugin:~1
      - cd /var/www/html/vendor/pantheon-systems/terminus && composer update
      - cd ~/.terminus/plugins/terminus-build-tools-plugin && composer update
      - cd ~/.terminus/plugins/terminus-rsync-plugin && composer update
`
Then in a shell:
`
lando rebuild
lando terminus self:clear-cache
cd web/sites/default
lando terminus rsync SITE_NAME.dev:files .
`
