### ISSUE TITLE
Lando / offline

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#1323]
1.  Lando version : v3.0.0-rc.1
2.  System and laptop : thinkpad p51, archlinux / manjaro
3.  Probleme : 
when the internet connection is offline all of hosts of my projects with lando not working and working if the connection is ON ?

there is a way to lando + projects safelly without internet ??

any idea ?

tnx a lot.

**Comment by kamalkech** [comment]
@calin-marian documentation is for osx not archlinux

**Comment by edurenye** [comment]
@pirog I agree with @kamalkech would be nice to have documentation for Linux [https://docs.lando.dev/guides/offline-dev.html#mac-specific-instructions](https://docs.lando.dev/guides/offline-dev.html#mac-specific-instructions)

**Comment by pirog** [comment]
@edurenye the first step to make that happen is to open up a ticket asking for it. I personally dont use linux so if documentation is provided its going to have to come from someone else
