### ISSUE TITLE
[REQUEST] Abstraction Diagram 

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#1324]
I am looking for a diagram showing how the 2 abstraction layers work on top of Docker Compose. If one doesn't exist can, an explanation will do and I can work on creating one. 

I think one of the layers is the command layer e.g. `lando behat`.

**Comment by pirog** [comment]
@ElijahLynn the layers are "services" and "recipes" which are already documented.

**Comment by ElijahLynn** [comment]
It appears that the event hooks are as well, correct?
