### ISSUE TITLE
Is it possible to restart only one service?

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1333]
I know it's possible to to 

    lando rebuild -s ruby

But anything more optimal? Could we implement -s for restart command?

**Comment by ccharlton** [comment]
I was looking for this too.

**Comment by dustinleblanc** [comment]
This seems like a sensible request

**Comment by marcaddeo** [comment]
Would also like to see this implemented.

**Comment by dalin-** [comment]
FWIW if you really want to do this, you can with Kitematic or Docker CLI.

**Comment by ccharlton** [comment]
@dalin- you saying just restarting the individual service container will auto-start that service? I assumed some basic flag needed to be passed in.

**Comment by hkirsman** [comment]
Hope this will still be implemented one day! :)

**Comment by zuernBernhard** [comment]
how could this be implemented ?

**Comment by snipebin** [comment]
I was able to restart a single container through the Docker Dashboard. The controls for a given container are available on the upper left menu above the log section.

<img width="1044" alt="Screen Shot 2020-05-05 at 7 10 36 AM" src="https://user-images.githubusercontent.com/3927939/81075826-b2448280-8e9f-11ea-9521-8b05416fac0b.png">

**Comment by tormi** [comment]
`docker container restart myproject_ruby_1` should do the trick.
