### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by robertgarrigos** [lando/lando#1336]
I'm having this error and cannot use lando today:

```
Creating femnoviolencia_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: github.com
```

These are the versions of lando and docker on ubuntu 18.04 just reinstalled:

```
robert@robert-MacBookPro:~/Documents/Desenvolupament/femnoviolencia$ lando version
v3.0.0-rc.1
robert@robert-MacBookPro:~/Documents/Desenvolupament/femnoviolencia$ docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by orkutmuratyilmaz** [comment]
Hello everyone,

I'm getting the same error message. When I made a search, I've just understood that the problem is about my docker container's DNS setting. I followed the docker tutorial and created a /etc/docker/daemon.json file, by putting the lines I paste below:
```
{
	"dns": ["8.8.8.8", "8.8.4.4"]
}
```
After that, I've tried "lando rebuild" once more and it didn't work. I'm still receiving the same error message.

Do I miss something?

Best,
Orkut

**Comment by orkutmuratyilmaz** [comment]
Well, it appears that my firewall was blocking my DNS settings. I've solved the problem over the firewall layer.

**Comment by LPIX-11** [comment]
All of my lando containers didn't have access to internet. I searched a solution for about a week. I searched the solution everywhere. I've also completely re-installed docker and lando and upgraded them to the latest versions; and guess what, it still didn't wokr. My firewall was inactive so my problem was not coming from there too.
After coming here I tried creating daemon.json file in /etc/docker, and and put this inside

```json
{
	"dns": ["8.8.8.8", "8.8.4.4"]
}
```
After that I stopped all containers, restarted docker service and everything worked!!!

Hope it can help someone.

**Comment by raymondcheung** [comment]
@LPIX-11 Thanks, that got mines working!

**Comment by landbryo** [comment]
@LPIX-11 this just happened to me as well and adding `daemon.json` in `/etc/docker` worked.
