### ISSUE TITLE
Place to share/find custom lando configs?

### ISSUE THREAD

**Issue by wesruv** [lando/lando#1341]
When I got started with Lando customizing my config was hard to understand and find the right docs or debug info.

I've made some recent breakthroughs using lando to compile Ruby Sass (Compass) without having to install Ruby on my host machine. Thought it'd be good to share, and thinking other people might want to share and peek at other people's setups.

https://gist.github.com/wesruv/cfc54c88a73314d6c3100c058d3a1146

Not sure where's a great place to do it, thought maybe there should be one?

**Comment by ccharlton** [comment]
Gotta start somewhere! 🥇

**Comment by wesruv** [comment]
@ccharlton Coincidentally, that Lando file for my local of the site that you mention in your bio :stuck_out_tongue: 

Small drupal world?

**Comment by ccharlton** [comment]
Well, Docker Containers _are_ reusable, just like 🚀  these days!

**Comment by hkirsman** [comment]
Maybe similar to Drupal https://drupal.stackexchange.com/ we could have https://lando.stackexchange.com/ It seems this is where one could send proposal https://area51.stackexchange.com/ Too early?

**Comment by pirog** [comment]
@hkirsman im guessing our slack channel is probably the best place for that
https://launchpass.com/kalabox in the #lando channel

@wesruv @ccharlton I love this idea and i know @uberhacker had mentioned previously about having some sort of snippet repository. Do you guys have any ideas or proposals on how we could do this? 

Some food for thought: 

* Does `gist` have a way to build out collections of snippets tied to a project or anything like that? 
* Does a separate git repo in lando make sense like an "awesome-lando" type thing?
* Does just having a page in our docs work?

@dustinleblanc @serundeputy interested to hear your thoughts here as well.

**Comment by hkirsman** [comment]
@pirog tx! Have account now.

**Comment by serundeputy** [comment]
@pirog I think the low hanging fruit here is to set up a `lando/lando-contrib` github org or maybe for an org it has to be just `lando-contrib` not sure.

Then we could use the wiki as a place for things like @wesruv 's gist on ruby sass and all the other awesome things people do that they want to document.

Then of course the org could grow to hold lando contrib plugins as people start to write them.

**Comment by wesruv** [comment]
I like @serundeputy 's idea, having a page in the docs where people could make PR's with links to gists or w/e also sounds good to me.

**Comment by ccharlton** [comment]
* `gist` hopefully could work.
* repo with it's own PR's and Issue queue usually works.
* Wiki can be good but real code/snippets smell better.

**Comment by wesruv** [comment]
Having links to gists would be good because of the commenting feature... could help improve the examples and raise gotchas for different setups

**Comment by pirog** [comment]
UNSTALE!

**Comment by ccharlton** [comment]
Preventing staleness...

**Comment by pirog** [comment]
Alright, this has not been OFFICIALLY rolled out yet but we now have a place to do this, see https://docs.lando.dev/contrib/guides-intro.html for more detail
