### ISSUE TITLE
WP Core Download throws error

### ISSUE THREAD

**Issue by adamdtoth** [lando/lando#1343]
After running the `lando wp core download` on a fresh lando instance I get the following error

`Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.6/?locale=en_US': cURL error 28: Resolving timed out after 10524 milliseconds.`

The same occurs when I specify a version of WP to download.  I ran a `lando init`, specified WP, ran a `lando start` and then attempted to run the `lando wp core download`

Lando Version: v3.0.0-beta.47

.lando.yml

```
name: mysite
recipe: wordpress
config:
  webroot: .
```

**Comment by sebastienserre** [comment]
Hello,
did you try to update to Lando 3.0 RC1 ?
https://github.com/lando/lando/releases

I didn't have these problems on RC1 (using WP & WP cli all the days on Lando)

**Comment by pirog** [comment]
+1 on @sebastienserre's comment re this should be resolved in RC1 +
