### ISSUE TITLE
Upgrade Default Version Of PHP For PHP-based Recipes

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#1344]
I usually use Lando these days to boot up Backdrop sites, and a PR I was testing related to PHP 5.3. When I looked at what I was running as a default, PHP 7.0.x, I thought I would check some other recipes. 

On the PHP service doc, it says the default is PHP 7.2, but in the recipes I looked at for Backdrop, Drupal 7, Drupal 8, and Laravel, the PHP version is less than 7.2. How do the defaults for the different recipes get updated as newer versions of PHP are released? 

Since Drupal 8 is the most modern of the projects I listed that has info on supported PHP versions (no idea why Laravel is ambiguous about that), I see that at least PHP 7.2 is supported. https://www.drupal.org/docs/8/system-requirements/php-requirements

I can make a PR to change the numbers, but I don't know what the policy is for upgrading versions per project.

**Comment by pirog** [comment]
@alexfinnarn i think `master` is set up to use 7.2 for all php recipes except drupal 6 so these should be up to date.

In the future i would ping in the contributors channel about updating the defaults, the likely result there will be we ask you to open up a PR. Changing the default versions is now REALLY easy in the RC2+ world
https://github.com/lando/lando/blob/master/plugins/lando-recipes/recipes/backdrop/builder.js#L52
