### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on Pantheon site with HTTPS / Global CDN

### ISSUE THREAD

**Issue by pi-ron** [lando/lando#135]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

`v3.0.0-alpha13` on MOSX 10.11.6 (el cap) 

Have you previously installed lando? If so, what version?

No (Yes, but not on this computer.)

**Tell us about your bug**

1. I created a new Lando app (Existing Drupal 8 Pantheon live site with Professional plan and SSH/Global CDN setup) following the *Working with Pantheon* tutorial.
2. I imported the database successfully.
3. ran `lando drush cr`
4. Visited the site, and got the home page, albeit, missing CSS and files (yet to be pulled / placed in sites/default)
5. Click on a second level page e.g. /about-us
6. Get redirect loop *ERR_TOO_MANY_REDIRECTS*
7. Checked all settings.php files and *.settings.php includes for redirects
8. Commented out the only redirects I found, but suspected they would have no effect as were within an if(env=pantheon live) statement.
9. Tried second level page again, got the redirect loop again.
10. Pulled down an existing Pantheon live site to test (all though, this one was Drupal 7)
11. No issues with redirects on second site.

I suspect that this issue is to do with the Pantheon SSL/Global CDN config, but to be honest, I've got no idea.  I didn't setup the live config for this site when it was done a few days back.

Also, this site works fine with no modifications to any settings.php files when using the drupal8 recipe.

**Comment by pi-ron** [comment]
Not sure how to test this further, but we do have one site on the 'old' style of SSL on Pantheon – Would it be worth testing that one?

**Comment by pirog** [comment]
@pi-ron i think it would be worth testing but im guessing the issue is some sort of interplay between your custom redirect logic and how we set the ENVIRONMENTAL variables that logic relies on.
