### ISSUE TITLE
Support request. Can you save Solr database files to location that is not rebuilt?

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1351]
Mysql database is not deleted when doing lando rebuild but any other image will be deleted and rebuilt. This will delete all Solr index data which takes a lot of time to rebuild. Is it possible somehow to mimic what Lando is doing for mysql?

**Comment by dustinleblanc** [comment]
Pretty sure this is just volume mounts under the hood, not sure if there is a reason Solr service isn't doing that, but that would be where to start the investigation

**Comment by pirog** [comment]
@dustinleblanc *pretty sure* we already do this.

that said i think there is an exception for solr `4.10` because its some random dudes image and maybe isnt set up for persistence. Since 4.10 is EOL i dont think we should fix it there though. If its not working for 5.x+ we should

**Comment by hkirsman** [comment]
We are using 4.10 yes.

**Comment by pirog** [comment]
Yeah sadly i dont think we can do this on 4.x but it might be worth trying this on 5.x since the schema differences arent huge

**Comment by pirog** [comment]
We've got some nice tests and an example to verify this now (including 4.x)
https://github.com/lando/lando/tree/master/examples/solr

Note that these examples and tests are against RC2 which is yet to be released so its worth waiting for that before you verify on your own
