### ISSUE TITLE
Feature request: Support current Node LTS dubnium

### ISSUE THREAD

**Issue by tanc** [lando/lando#1353]
It would be great if we could install the currently active Node LTS version 10.x, codename Dubnium. At the moment the supported versions only go up to version 9.x. The current LTS version became LTS on 2018-10-30 and will expire April 2020.

**Comment by tanc** [comment]
Ok, it looks like 10 is actually supported with `node:10` but the docs haven't been updated. It might be good to add `dubnium` as one of the options too.

**Comment by pirog** [comment]
@tanc this is already the case in our active dev branch
https://github.com/lando/lando/tree/leia
