### ISSUE TITLE
Tooling on Windows always as root

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1362]
Bug Report
==========

*v3.0.0-rc.1 on Windows 10 Pro with Docker 2.0.0.2*

```yml
name: test
recipe: lamp
```

Unfortunately, I have not found a suitable issue.
Is it intended or a must that all tooling commands for lando on Windows 10 are executed as ``root`` and not as ``www-data``?

For example, with ``lando ssh`` I always end up as ``root`` on the appserver - even ``lando ssh --user www-data`` logs me in as ``root``. The tooling ``lando composer`` is also executed as ``root`` in the appserver.

Does anyone have the same problems on Windows?

**Comment by pirog** [comment]
@rabauss this should be fixed in RC2
