### ISSUE TITLE
Default nginx in Drupal recipe seems greater than in Docs

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1364]
Latest nginx that can be defined is 1.3 according to docs and this is true (https://docs.devwithlando.io/services/nginx.html). I tried 1.4 and 1.5 but they didn't work. So when using configuration set below I get version 1.13.12 installed:

    name: drupal7.benchmark
    recipe: drupal7
    config:
      php: '7.0'
      via: nginx:1.13
      database: mariadb:10.3

When I don't define version, then 1.15.8 is installed:

    name: drupal7.benchmark
    recipe: drupal7
    config:
      php: '7.0'
      via: nginx
      database: mariadb:10.3

Why is that?

**Comment by pirog** [comment]
@hkirsman please refer to the dev docs on this as this will be the situation for RC2 and going forward
https://github.com/lando/lando/blob/leia/docs/tutorials/nginx.md

**Comment by hkirsman** [comment]
Ok, so the docs are more up do date than what can be downloaded. I don't get why it still says 1.14 there when it download 1.15.8 .

@pirog

**Comment by pirog** [comment]
Because in LAMP/Drupal recipes it probably pulls the latest tag eg isn’t
pinned to a version.

This is not going to be the case in RC2. It will inherit from the Nginx
service directly.

**Comment by hkirsman** [comment]
Ok, tx!
