### ISSUE TITLE
This increases PHP applications performance ~30%

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1365]
There's a feature I hope gets implemented into Lando. Namely disabling xdebug for real if it's disabled. Currently xdebug module is loaded even if xdebug is set to false. It only changes some environment variables and exposes the port to host machine. So for now I've created this script to work with Apache which renames the docker-php-ext-xdebug.ini file and restarts Apache:

    #!/bin/bash
    
    #
    # Remove XDebug from PHP if it's disabled in .lando.yml to make the site lot faster.
    # It seems xdebug: false/true disables and enables $XDEBUG_CONFIG variable.
    # By renaming the xdebug ini file and reloading Apache we can remove it from PHP.
    #
    
    export PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin
    set -e
    conf=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    conf_disabled="$conf.disabled"
    if [ -z "$XDEBUG_CONFIG" ]; then
      if [ -f "$conf" ]; then
        mv "$conf" "$conf_disabled"
      fi
    else
      if [ -f "$conf_disabled" ]; then
        mv "$conf_disabled" "$conf"
      fi
    fi
    service apache2 reload

And I execute it in run_as_root:

    services:
      appserver:
        xdebug: false
        run_as_root:
          # Speed up site by removing XDebug totally according to xdebug variable in this file.
          - sh $LANDO_MOUNT/.lando/xdebug.sh

Unfortunately I don't know how to restart php-fpm so it only starts to work with nginx when I restart the whole thing.

You can see if the module is disabled or not when you check the output of phpinfo(). There shuld't be section for xdebug if it's disabled.

**Comment by pirog** [comment]
@hkirsman this is already merged into our dev branch. try to check out the status of related issues before opening new ones

**Comment by hkirsman** [comment]
Sorry, thanks!
