### ISSUE TITLE
Support request: could you give example on how to add hkirsman/wunder-eslint-airbnb image to services?

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1367]
Do I understand correctly that you start from writing your own custom plugin?

There you write the new service into:

    lando.events.on('post-bootstrap', function(lando) {
    }

Currently I'm getting this:

     (node:6114) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 21 post-bootstrap listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by dustinleblanc** [comment]
Hi @hkirsman, to add a custom service, the easiest method is to just use the compose service: https://docs.devwithlando.io/tutorials/compose.html

Custom plugins will be changing significantly with this weeks RC2 release: https://docs.devwithlando.io/dev/plugins.html

If you need anything else, I suggest jumping into our slack org, thanks!

**Comment by hkirsman** [comment]
Tx!
