### ISSUE TITLE
POST RC2 notes for Pirog

### ISSUE THREAD

**Issue by pirog** [lando/lando#1375]
- [x] GO BACK AND MAKE NODE better with ssl eg a porthttps property
- [x] can we set server and/or vhosts in LAMPy recipe config?
- [x] update composer
- [x] update docker
- [x] update terminus
- [ ] update/verify terminus api calls
- [x] sshkey rsync

- [x] github release deploy weird for windows
- [x] get a better setup for windows dev
- [x] overrides normalize on windows
- [x] drush 9 on pantheon, status check fails 
- [x] test NODE cert dir value
- [x] lando apache .htaccess file
- [x] --help and --version mess with shit (this seems to be upstream in YARGS)
- [x] note /var/www and named volume persistence
- [x] note build step failure
- [x] db-export does not gzip if arg ends in .gz
- [x] better document linux install
- [x] pantheon solr index needs help, requires a restart for index posting
- [x] add tests for pantheon ENV
- [x] note morehttpporrts
- [x] select properties in `lando config`, filters etc for `lando list`
- [x] add port to dotnet just like with python/node/ruby etc
- [ ] ALIASES need to be service specific FPM and MAILHOG, we do this in varnish
- [x] vhost custom for php
- [ ] mssql database available for things?
- [ ]  nginx/apache caching issue re: js/css/etc max expiration?
- [ ] sort global help options? just the global ones now
- [ ] redo pantheon index and appserver as separate service?

**Comment by wss-chadical** [comment]
> @pirog "mssql database available for things?"
> "Available" as in pulling a database from pantheon during a build step in the appserver?
> Database service used to be available during appserver build in RC1....

Yeah, now that I re-read it, I was thinking mysql. I will open an issue for the lack of "depends_on: -database" for the appserver service in the pantheon recipe.

**Comment by pirog** [comment]
@wss-chadical check out the latest docs on build steps
https://docs.devwithlando.io/config/services.html#build-steps

Note that `build` and `build_as_root` now run **before** your app starts. `run` and `run_as_root` run **after** your app has started. This means that if you have a build step that requires a service outside of the service you are running a pre-start build step on to be up you need to use `run` or `run_as_root`

**Comment by wss-chadical** [comment]
@pirog 
"Note that build steps will **ONLY RUN THE FIRST TIME YOU SPIN UP YOUR APP**. That means that if you change them you will need to run lando rebuild for them to re-run."

Got it.

**Comment by pirog** [comment]
unstale
