### ISSUE TITLE
LANDO_INFO has lost service names and instead has integers as array keys

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1376]
When changing to v3.0.0-rc.2 I had to change the lando info a bit to make Drupal work:

    -    'database' => $lando_info['database']['creds']['database'],
    -    'username' => $lando_info['database']['creds']['user'],
    -    'password' => $lando_info['database']['creds']['password'],
    -    'host' => $lando_info['database']['internal_connection']['host'],
    -    'port' => $lando_info['database']['internal_connection']['port'],
    +    'database' => $lando_info[2]['creds']['database'],
    +    'username' => $lando_info[2]['creds']['user'],
    +    'password' => $lando_info[2]['creds']['password'],
    +    'host' => $lando_info[2]['internal_connection']['host'],
    +    'port' => $lando_info[2]['internal_connection']['port'],

I think the keys should still be service names as the integers might change.

This is my .lando.yml:

    name: drupal7.benchmark
    recipe: drupal7
    config:
      php: '7.0'
      via: nginx:1.14
      database: mariadb:10.1

**Comment by pirog** [comment]
makes sense, we changed info to an array of objects instead of an object. 

Only question now is whether we want to document this change or change it back to the way it was before

**Comment by pirog** [comment]
Ok yeah @hkirsman i think i agree with you that this needs to stay the same

**Comment by pirog** [comment]
ok @hkirsman ive fixed this in master

**Comment by hkirsman** [comment]
Tx! What's the plan for this fix? Will there be soon small update for current release?

**Comment by hkirsman** [comment]
Cool, you already did release. Will be testing.
