### ISSUE TITLE
Tooling command doubled when failure exit code returned

### ISSUE THREAD

**Issue by westonruter** [lando/lando#1378]
Something strange I'm noticing in regards to tooling: in my `.lando.yml` I have:

```yml
tooling:
# ...
  phpunit:
    service: appserver
```

When I run `lando phpunit` and all assertions pass, then the command is just run once:

![image](https://user-images.githubusercontent.com/134745/52153049-66b48080-262d-11e9-8b94-1adbff6044bc.png)

But if there was a test failure, then the `phpunit` command runs a second time:

![image](https://user-images.githubusercontent.com/134745/52153056-6fa55200-262d-11e9-9fe1-611ad5fa4e1a.png)

It's unexpected that a command returning a failing exit code would be executed twice.

This didn't happen in 3rc1.

I'm running v3.0.0-rc.2 on MacOS 10.14.2.

Ref Slack convo: https://kalabox.slack.com/archives/C5Q6XTY3S/p1549059456816400

**Comment by pirog** [comment]
@westonruter ok this should be fixed in master!

**Comment by pirog** [comment]
@westonruter pending tests passing anyway ;)

**Comment by pirog** [comment]
Alright alright alright this is in it to win it
