### ISSUE TITLE
Should lando set $_SERVER['HTTP_HOST'] in pantheon recipe?

### ISSUE THREAD

**Issue by wss-chadical** [lando/lando#1399]
RC3 & RC4
Coming from RC2

$ lando wp
PHP Notice:  Undefined index: HTTP_HOST in /app/web/wp-content/mu-plugins/pantheon/pantheon-login-form-mods.php on line 18
Notice: Undefined index: HTTP_HOST in /app/web/wp-content/mu-plugins/pantheon/pantheon-login-form-mods.php on line 18
...
(the wordpress client still works)
...

Code in question:
```php
$show_return_to_pantheon_button = apply_filters( 'show_return_to_pantheon_button', ( 
    ( ! defined('RETURN_TO_PANTHEON_BUTTON') || RETURN_TO_PANTHEON_BUTTON ) &&
    (
        false !== stripos( get_site_url(), 'pantheonsite.io') ||
        false !== stripos( $_SERVER['HTTP_HOST'], 'pantheonsite.io') 
     )
) );
```

Not sure what changed as this was not the behavior in RC2... php.ini setting? notice vs warning log settings?

**Comment by pirog** [comment]
@wss-chadical AFAIK we've never set `$_SERVER['HTTP_HOST']` so this should actually be a feature request

**Comment by wss-chadical** [comment]
@pirog Thx for the insight. It's not breaking anything. Seems like a php.ini logging change... was not surfacing notices prior. I will have pantheon address the code itself since they should be checking if it's set.

**Comment by wss-chadical** [comment]
well - since it's through the wp cli, $_SERVER wouldn't be set anyways right?

**Comment by pirog** [comment]
@wss-chadical yeah and on investigation it looks like we DO already set this so going to reclose
