### ISSUE TITLE
Why does the php version has to be string in config section?

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1400]
I guess this has been there for long time? When you change remove the quotes around php version then you get error.

Original config that works:

    name: site.com
    recipe: drupal7
    config:
      webroot: drupal/current
      php: '7.0'
      database: mysql:5.7
      drush: 8.1.15

Problematic config:

    name: site.com
    recipe: drupal7
    config:
      webroot: drupal/current
      php: 7.0
      database: mysql:5.7
      drush: 8.1.15

Error message is

> error: TypeError: Invalid Version: 7.0

**Comment by hkirsman** [comment]
And drush works because?

**Comment by pirog** [comment]
Because it doesn't end in a `0` the node YAML parser we have strips the trailing 0 so `7.0` becomes `7` 

Take some time and do some research.

**Comment by hkirsman** [comment]
Seems like better to quote everything. Some day there'll be Drush 8.1.20, mysql 5.10 etc.

**Comment by f1rf1n** [comment]
This might need a follow-up. But the docs (for I think all recipes but) at least for the drupal7 are in error then. 
https://docs.devwithlando.io/tutorials/drupal7.html#choosing-a-php-version states that php: 7.0 is correct. Very confusing.
