### ISSUE TITLE
[v3.0.0-rc.5] Unable to launch a simple Pantheon site

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1404]
See attached error log.

.lando.yml:
```
name: mysite
recipe: pantheon
config:
  framework: drupal8
  site: mysite
  id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
```
system specs:
```
$ uname -a
Linux dell-precision-m6700 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1~mx17+1 (2018-02-23) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	MX
Description:	MX 18 Continuum
Release:	18
Codename:	Continuum
$ free -g
              total        used        free      shared  buff/cache   available
Mem:             31          12           9           0           9          18
Swap:             4           0           4
$ lando version
v3.0.0-rc.5
$ docker -v
Docker version 18.09.1, build 4c52b90
$ docker-compose -v
docker-compose version 1.23.2, build 1110ad01
```
[mysite.txt](https://github.com/lando/lando/files/2829723/mysite.txt)

**Comment by uberhacker** [comment]
This site worked fine in `v3.0.0-beta.47`.

**Comment by pirog** [comment]
@uberhacker you can't rebuild sites built before RC2, you need to destroy and recreate them.
https://docs.devwithlando.io/guides/updating-to-rc2.html#new-images

FWIW We test pantheon out pretty extensively on every build and there are no reported errors in spinning up our test sites

**Comment by uberhacker** [comment]
I started fresh with this site.  I think I know my problem.  Out of disk space!  Closing...

**Comment by uberhacker** [comment]
It's worth noting the delay still occurs even with plenty of disk space on a fresh build.  I might just open another issue about the delay.
