### ISSUE TITLE
Port docs to vuepress

### ISSUE THREAD

**Issue by ro0NL** [lando/lando#1410]
Hi,

The number of menu items in the left pane at https://docs.devwithlando.io/ is huge. As such, finding the right content is a bit cumbersome, esp. since left and right panes scroll individually. Yet, this is only my personal UX experience; i find it hard to overview the available chapters.

Anyway, perhaps it's worth to see if it can be improved. E.g. using https://plugins.gitbook.com/plugin/folding-menu (example at https://feature-u.js.org/cur/index.html).

No fan of the animations, but it seems those can be disabled.

**Comment by pirog** [comment]
Totally agree with @ro0NL here. 

We have A LOT of documentation now and it would be nice to organize it better. That said, i'm not exactly sure how best to do that but i vote for anything that is easy to implement and doesn't include tacky animations and transitions ;)

**Comment by pirog** [comment]
UNSTALE!

**Comment by ro0NL** [comment]
nah :)

**Comment by pirog** [comment]
nice! thanks for that slackbot dismissal @ro0NL

**Comment by pirog** [comment]
unstale

this might actually portend a larger issue; we've recently started using "VuePress" to power other documentation sites and its a vast improvement over GitBook... and specific to this concern has much better mechanisms to arrange content.

**Comment by pirog** [comment]
@ro0NL we've significantly improved the docs 
https://docs.lando.dev

That said you can always do better so feel free to open any new issues if you've got feedback or suggestions!

**Comment by ro0NL** [comment]
wow :+1:
