### ISSUE TITLE
Bedrock compatibility with rc.5. Usage of ${WP_HOME} in .env file.

### ISSUE THREAD

**Issue by bweiler-marketingflotte** [lando/lando#1411]
In WordPress projects that uses the bedrock stack by roots.io there is a compatibility issue with the default syntax in the projects .env files. 

By default the WP Constants part looks like this:

WP_ENV=development
WP_HOME=http://wpb4.test
WP_SITEURL=${WP_HOME}/wp

Since lando rc.5 the ${WP_HOME} is not working anymore. You have to replace it with the actual url.
Would be nice to mention that in the docs:
https://docs.devwithlando.io/guides/updating-to-rc2.html#environment-files
https://docs.devwithlando.io/config/env.html#environment-files

**Comment by pirog** [comment]
https://docs.devwithlando.io/guides/updating-to-rc2.html#environment-files
https://docs.devwithlando.io/config/env.html#environment-files
