### ISSUE TITLE
Requesting unbundled lando for use in Scoop and other Installers

### ISSUE THREAD

**Issue by r15ch13** [lando/lando#1414]
Hi,
I would like to add Lando to the [Scoop Installer](https://github.com/lukesampson/scoop) repository. A command line installer for Windows inspired by homebrew.

Some small changes to the CI would make maintaining the Lando package a bit easier and the installation faster.
I would suggest providing the `lando.exe` (or a zip containing the License, Readme, and Docu) separated from then Docker for Windows installer.

Scoop handles downloading and updating the Lando package on a users Computer.
An automated updated service will update the installation script, so no maintenance from your Team is needed.

Docker for Windows could be installed as a dependency or just shown as a suggestion to the user. If a user has already a running Docker installation, then redownloading the installer just to get the `lando.exe` is a bit much.

An example for installing Docker for Windows via Scoop was also created https://github.com/lukesampson/scoop/issues/3082#issuecomment-460714955
This will download the Docker installer, run it and after that the package can be removed without uninstalling Docker. (The user has to uninstall it manually)

Separating the `lando.exe` would only require coping `build\cli\lando-win32-x64-v*.exe` to the `release` directory by using the [build-releases-appveyor.ps1](https://github.com/lando/lando/blob/master/scripts/build-releases-appveyor.ps1)
```powershell
Copy-Item "build\cli\lando-win32-x64-v*.exe" -Destination "release\lando-$env:APPVEYOR_REPO_TAG_NAME.exe" -Force
```

Providing checksums for each file would also be a nice addition by adding:
```powershell
Get-ChildItem release\ -Exclude *.txt | ForEach-Object { "$((Get-FileHash $_).Hash) *$_" >> release\checksums.txt }
```

Related issue in Scoop Repository: https://github.com/lukesampson/scoop/issues/3082

Thank you for your time :smile:

**Comment by pirog** [comment]
@r15ch13 that would be awesome. We definitely want to try and get Lando easily available by other means so will definitely try to make this happen.

Just to clarify, i assume you just want us to isolate our CLI executable right? Not a Lando installer exe sans Docker for Windows?

**Comment by pirog** [comment]
unstale
