### ISSUE TITLE
Connecting to database on localhost

### ISSUE THREAD

**Issue by couloir007** [lando/lando#1433]
I have a postgres with postgis db running on my local machine. Is it possible to connect to my localhost DB instead of the lando created DB? I tried running:

lando ssh -c "env" | grep LANDO_HOST_IP

and used the ip as the host but that did not seem to work.

Thank you,
Sean

**Comment by pirog** [comment]
@couloir007 AFAIK you should be able to use `$LANDO_HOST_IP` to connect back to your host.

Obviously you will need to make sure your host database is running on `0.0.0.0` and not `127.0.0.1` so that it can receive connections from outside itself and that your credentials are correct.
