### ISSUE TITLE
Lando will not install on Ubuntu 18.10  - git dependency fails

### ISSUE THREAD

**Issue by dansrocks** [lando/lando#1437]
I just download Lando lando-v3.0.0-rc.8.deb
I have a Ubuntu 18.10 (updated today)

When i tried to install lando from .deb, QApt (GUI for apt) returns an error: Cannot satisfy dependencies.

I just check dependencies and found that _my system use  **git** instead **git-core** package_.

----

> Solution?  (only valid for Ubuntu 18.10+ ? )
> I rebuilt the .deb package changing   git-core with git on  control file and rebuild .deb package.
> Doing this, i could to install the package

**Comment by pirog** [comment]
Thanks for posting this @dansrocks! 

I actually don't think we need `git` as a dependency so seems like the quick and easy solution here is to just remove that. @dustinleblanc im guessing this might eb vestigial from the Kalabox days, can you think of any reason why lando _needs_ `git`?

**Comment by dustinleblanc** [comment]
No, since all Git ops that Lando does happen within a util container with Git installed, I don't think we need it.

**Comment by pirog** [comment]
@dansrocks this dependency has been removed in rc10
