### ISSUE TITLE
Windows: Installer Doesn't Update Lando-Installed Docker

### ISSUE THREAD

**Issue by AaronFeledy** [lando/lando#1447]
Running v3.0.0-rc.9 on Windows 10 Professional

Installing Lando RC1 installs Docker 18.06.1, which is expected.

When installing one of the newer RCs, such as RC9, the docker installer tells you that you're already up to date and does not update to 2.0.0.2.

It appears that the Lando installer copies the Docker installer to `C:\Program Files\Lando\installers\docker\docker.exe` and runs that during the installation process. It, however, does not replace that `docker.exe` in subsequent installs. So, when updating Lando, that old installer runs again and docker is not updated.

**Comment by AaronFeledy** [comment]
Just confirming that I'm seeing this issue on a second Windows machine.

**Comment by pirog** [comment]
unstale
