### ISSUE TITLE
Cannot use single quotes in drush commands

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#1474]
**Tell us about your setup**

3.0-rc10 on Win10 Pro

*Example: v3.0.0-rc.2 on Windows 10 Professional*

**Tell us about your `.lando.yml`**
```

  devmeup:
    service: appserver
    cmd: cd /app/web && drush role-add-perm anonymous 'access kint'

```
**Tell us about the command you were running**

```devmeup```

**Tell us about the error you got**

> Could not find the permission: access

**Tell us generally about your bug**

In rc1, using single quotes allowed me to grant permissions with drush.  After upgrading to rc10, this doesn't work anymore.  How should I format the command so that I can grant permissions in drush?

**Comment by ptmkenny** [comment]
This is still an issue; if the format has been changed, how can I reformat the command to add permissions with drush via lando?

**Comment by dsnopek** [comment]
This has been driving me crazy with build steps. I have a step using `awk`, and I just can't figure out the magic incantation to allow me to quote the script.

**Comment by philwolstenholme** [comment]
I have the same issue
