### ISSUE TITLE
docker run options

### ISSUE THREAD

**Issue by com2** [lando/lando#1477]
Is there a feature or work around to add options like [--add-host to "docker run"](https://docs.docker.com/engine/reference/run/#network-settings)?  it would be nice if this could be stored in .lando.yml. I tried this in build_as_root but [apparently this cannot be set at build time](https://stackoverflow.com/questions/38302867/how-to-update-etc-hosts-file-in-docker-image-during-docker-build#40721996). Or how can I use the [suggested docker-compose extra_hosts directive](https://stackoverflow.com/questions/38302867/how-to-update-etc-hosts-file-in-docker-image-during-docker-build#38306666)?

**Comment by com2** [comment]
I see that the same option [exist for docker build](https://docs.docker.com/engine/reference/commandline/build/). So another question could be how you can add custom options to docker build with lando?

**Comment by pirog** [comment]
@com2 you can specify `extra_hosts` using a service override
https://docs.devwithlando.io/config/services.html#overrides

Also worth pointing out that GitHub is meant primary for bug fixes and feature request. If you have a general support question id recommend joining our slack channel over at 
https://launchpass.com/kalabox and in the #lando channel
