### ISSUE TITLE
RC11 - sh: 0: getcwd() failed: No such file or directory

### ISSUE THREAD

**Issue by davideprevosto** [lando/lando#1480]
After upgrade to RC11:

`lando ssh` returns:

`sh: 0: getcwd() failed: No such file or directory`
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`

and the consequence is lando `wp db import filename.sql `doesn't works.
It returns Pass --path=`path/to/wordpress` or run `wp core download`.

**Comment by davideprevosto** [comment]
I was able to import SQL DB using:

`lando ssh`
`wp db import filename.sql --path=../app`

It happens only in one project. Any idea?

**Comment by pirog** [comment]
@davideprevosto ive seen other people restart docker to resolve issues like this.

**Comment by davideprevosto** [comment]
@pirog you're totally right. thank you.
