### ISSUE TITLE
devwithlando/php builds are failing for past 20 days

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#1488]
![image](https://user-images.githubusercontent.com/1504756/53277204-9a784880-36b7-11e9-8df9-0793e40f9e4f.png)

https://hub.docker.com/r/devwithlando/php/builds?page=31

**Comment by pirog** [comment]
@ElijahLynn it's actually ok for these to be failing, lando will always use the latest "good" image. That said they've been updated to build successfully so going to close
