### ISSUE TITLE
Support for RabbitMQ

### ISSUE THREAD

**Issue by sarath49** [lando/lando#1489]
Request for adding support for RabbitMQ in lando.

What is RabbitMQ?
RabbitMQ is an open source message broker software that implements the Advanced Message Queuing Protocol (AMQP). The RabbitMQ server is written in the Erlang programming language and is built on the Open Telecom Platform framework for clustering and failover. Client libraries to interface with the broker are available for all major programming languages.

Offcial page:
https://www.rabbitmq.com/

Bitnami Docker hub for RabbitMQ:
https://hub.docker.com/r/bitnami/rabbitmq

**Comment by philoSurfer** [comment]
https://docs.devwithlando.io/config/services.html#building-a-custom-service

**Comment by Tim-MultiSafepay** [comment]
If someone needs an example of a RabbitMQ custom service for Lando you can check my repo and give it a try! :smile:

https://github.com/Tim-MultiSafepay/Lando-RabbitMQ
