### ISSUE TITLE
Solr config not working with Pantheon recipe

### ISSUE THREAD

**Issue by chazchumley** [lando/lando#1491]
Please complete the following steps.

Lando Version:
v3.0.0-rc.10 on MAC MOjave 10.14.2

Lando.yml
-----------
name: eurasianet-en
recipe: pantheon
config:
  framework: drupal8
  site: eurasianet-en

Pantheon.yml
---------------
api_version: 1
web_docroot: true
php_version: 7.1
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php

**Tell us about the error you got**
Drupal 8 Solr Server cannot be reached.
https://cl.ly/2a73aa2b3abc

This worked fine until updating Lando.
I followed the steps in a previously closed issue.  Including doing a Lando destroy, Lando rebuild and still have the same error.  Solr works fine on Pantheon but locally no.

**Comment by pirog** [comment]
@chazchumley yup i can definitely replicate this. Looks like a regression caused by some upstream fixes we did to our normal solr service.

**Comment by chazchumley** [comment]
@pirog thanks for your attention looking into this.  Let me know if you need me to test anything or when the fix will be rolled into next release.

**Comment by pirog** [comment]
@chazchumley sure thing! We considered this a pretty bad breaking change so it triggered a release on our end.
https://github.com/lando/lando/releases/tag/v3.0.0-rc.13

Guessing you'll need to `lando rebuild` to reset things. Going to close for now but feel free to reopen if it doesn't work for you.
