### ISSUE TITLE
Drush/Drupal console not working for postgres

### ISSUE THREAD

**Issue by sarath49** [lando/lando#1493]
Continuing with closed issue #1479 

I re-setup my lando environment configuration with webroot to `.` instead of a directory `drupalintegration`.

I also updated to rc12 from rc9.

I performed `lando drush cr` from root of drupal site, got:

`/usr/bin/env: 'sh\r': No such file or directory`

I performed `lando drupal cr` from root of drupal site, got:

` [ERROR] Drupal Console is not installed at: "
         /app"`

**Comment by pirog** [comment]
@sarath49 this issue was closed previously because it is almost for sure a user configuration issue and not something in lando. From the looks of it you are using windows new lines instead of linux ones.
