### ISSUE TITLE
uninstall doesn't remove config files

### ISSUE THREAD

**Issue by robertgarrigos** [lando/lando#1495]
I've been struggling with a problem (#1490) for which I uninstalled lando and docker several times in order to test things. Finally, I realized that the lando uninstaller script doesn't delete the directory `~/.lando` where it was, actually, the problem. So I only had to delete that directory and let lando to recreate it again. Problem fixed.

I see there is an issue (#505) which set this as a documentation problem and fixed, but I never go down the page, as uninstalling on mac is high in the page and when you say "uninstall" it means "remove everyhting about lando", isn't it? So you don't see necessary to get down in the page to do whatever else. you already read about uninstalling.

I would say the uninstaller should get rid of the config files as well.

Or, at least, add a line within the mac section, and others also, in that page (https://docs.devwithlando.io/installation/uninstalling.html) referencing to the other steps down the page ;-)

**Comment by pirog** [comment]
@robertgarrigos generally i dont think its a great idea to remove user configuration as part of an uninstall so we follow that pattern eg this is the expected behavior and not a bug.

**Comment by robertgarrigos** [comment]
thanks @pirog however, uninstalling means for me leave no trace in the computer. Once read the mac part of the uninstalling lando in the docs, I did not think it was needed to go down the page to read more about the topic. I would recommend to add, at least, a line within those sections about deleting the configurations in order to clean up lando completely.

**Comment by pirog** [comment]
@robertgarrigos i hear you. that said what it means to you stands in pretty strong opposition to how most package managers or os's handle uninstall. 

I think what makes sense here is

1. Add some language to the uninstaller that tells the user they may still have lingering config/containers with a link to resolve said issue
2. Add a section to the RC2 update guide noting that in some cases users may need to nuke `~/.lando` to get things rolling correctly and then link to any relevant known issues where this might be the case

**Comment by robertgarrigos** [comment]
@pirog I'm used to go against the general flow, no problem. your solution would help people like me ;-) thanks
