### ISSUE TITLE
Can't run `lando poweroff`, Duplicate mount points for nginx config

### ISSUE THREAD

**Issue by alxvallejo** [lando/lando#1496]
I can't rebuild my lando project, I can't power down lando .. because i get this error:

```
Killing lisahdiusha ...
ERROR: Duplicate mount points: [/Users/alexvallejo/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/alexvallejo/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/alexvallejo/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/alexvallejo/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/alexvallejo/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/alexvallejo/.lando/services/config/pantheon/nginx.conf:Killing landoproxyhyperion5000gandalfedition_proxy_1 ... done
```

So I can't run anything basically because of this error. Please send help.

**Comment by aimevp** [comment]
I had a very similar issue after updating docker (I'm using the edge version). Reverting Docker back to the previous version I was using fixed my problems. If someone knows or finds a better solution that is compatible with the latest docker update I would be interested in that solution as well.

My error was: 
ERROR: Duplicate mount points: [data_database:/var/lib/mysql:rw, /path/to/project/lando_assets/db:/var/lib/mysql:rw]

**Comment by benjaminmerkley** [comment]
I am also having this issue when updating my docker

**Comment by gradywoodruff** [comment]
Also having the error:
ERROR:  Duplicate mount points: [/Users/<user name>/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/<user name>/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]

**Comment by platypusjones** [comment]
Can confirm, having same issue.

**Comment by benjaminmerkley** [comment]
I updated lando and completely reinstalled docker, that was able to do it for me :/

**Comment by platypusjones** [comment]
@benjaminmerkley Ouch. Thanks for the info!

**Comment by blachawk** [comment]
Can confirm, having the same issue and would really hate to re-install everything.  Any push for a fix yet?

**Comment by akalata** [comment]
I can't even uninstall lando with this error, using the dmg for the specific version I have.
