### ISSUE TITLE
Docker Borks Because I Need to Access it Via VPN

### ISSUE THREAD

**Issue by shaigluskin** [lando/lando#1499]
I'm trying to set up a Drupal/Pantheon local development environment.

My underlying problem:

- Firewall at work (large corporation -- won't be easy to change firewall settings) won't allow ssh access to Pantheon. My workaround is to use a VPN
- Docker, by default won't allow access through a vpn.

Ideas?

Here is a solution which looks good. 

https://stackoverflow.com/a/53085494

It requires my creating a docker-compose .yml file. I'm not sure what to name the file. I assume that I would put it in

`~/.lando/compose/<lando-project-name>/` 

Thank you for the great software.

Not sure how this got assigned the "task" label. It's meant to be a support request.

**Comment by pirog** [comment]
@shaigluskin this is something you would need to configure outside of Lando on the docker level. Not sure what OS you are using but you'd either start up the docker daemon directly or add config in the Docker Desktop

**Comment by shaigluskin** [comment]
Okay thanks. I'm using Ubuntu 18.04.

Looks like I should be able to use:

`docker config create [OPTIONS] CONFIG file|-`

I'll report back in case others find themselves on this journey.
