### ISSUE TITLE
option to skip setting permissions on /app, solr, named volumes

### ISSUE THREAD

**Issue by troseman** [lando/lando#1505]
As a developer using a named volume for /app, I'd like for ownership of /app to be set the same in all containers or left alone.

I'm using docker-sync to get better performance from docker/mac, so I'm using a named volume for all /app volumes using overrides, which works well for most containers.

Solr uses a default config user id of 8983. This isn't a problem for the solr container itself. But the lando script helpers set the ownership of all files in /app to solr:solr (8983:8983) in this container. Since /app is a named volume, this ownership change is reflected in the shared volume. 

When appserver changes a file, docker changes the host file attributes to include extended attributes. Sometimes the entire host source tree is changed to have these extended attributes.
xattr -l index.php
com.docker.owner: 0:33:33

Occassionally docker-sync will fail to copy because of permissions on named volume. 

These problems don't occur when all containers use same UID/GID for /app volume (so far in my testing).

The workaround for now is to set the UID/GID for Solr to the same values as the other containers.
services:

~~~~
  solr-service:
    type: solr:7
    overrides:
      volumes:
        - "${LANDO_VOLUME}:/app:nocopy"
      environment:
        LANDO_WEBROOT_UID: 33
        LANDO_WEBROOT_GID: 33
        LANDO_WEBROOT_USER: 'www-data'
        LANDO_WEBROOT_GROUP: 'www-data'
~~~~

It would great if we had a flag that told the container lando helpers to ignore /app, and not perform any changes to ownership/permissions on the volume. 

I understand that if overrides of Solr config files are given they'll need to be changed to solr ownership, but the main /app volume could be left unchanged.

thanks

**Comment by pirog** [comment]
@troseman there is an undocumented envvars called `LANDO_NO_USER_PERMS` that you can set to anything and this will skip the user perm stuff from happening. You can see that in action, as well as some other undocumented ENVVARS over here
https://github.com/lando/lando/blob/master/plugins/lando-core/scripts/lando-entrypoint.sh

We don't intend to document these or provide additional functionality beyond that

**Comment by troseman** [comment]
awesome, thanks! I missed that

**Comment by pirog** [comment]
totally understandable considering its mostly for us to use internally and not publicly documented anywhere ;)

**Comment by wimvds** [comment]
Setting LANDO_NO_USER_PERMS currently also prevents the user remapping. Is that intentional? Because we *need* the user remapping but don't want the perm_sweep. How would we be able to achieve this?

**Comment by wimvds** [comment]
Never mind, I just found out that we can overwrite the script from our plugin. So I took that approach for now and it seems to work just fine.

**Comment by pirog** [comment]
For more context: A lot of these envvar based mechanisms were _originally_ intended for internal usage by the Lando team in the work they do creating services, recipes, plugins etc. However, over the course of the last year or so its become more obvious that these internal "workarounds" need to be better, more feature rich and exposed via the Landofile so that users can manipulate them as needed. 

This would be a pretty deep change to Lando so it will likely happen in the next major version release eg not super soon. That said, wanted to just plant a flag here to say its on our radar to change how this all works.
