### ISSUE TITLE
pantheon recipe support for phantomjs

### ISSUE THREAD

**Issue by rbertolette** [lando/lando#1507]
**SETUP**
lando version: v3.0.0-rc.13
MacBook Pro (Retina, 15-inch, Late 2013)
Processor: 2.3 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3

(I use the PHPstorm 2018.3.4)

The Drupal 7 module phantomjs_capture requires that phantomjs be installed on the server. Pantheon does this.

_From the Pantheon Docs:_
`PhantomJS (1.7.0) is located at /srv/bin/phantomjs on your application container.`
`PhantomJS (2.1.1) is located at /srv/bin/phantomjs-2.1.1 on your application container.`

From what I can see, PhantomJS isn't in the environment installed by the recipe. (I'm admittedly no unix wizard.) I've had limited success ssh'ing in as root, installing node, then running `npm install phantomjs-prebuilt`, then going to the config panel of the phantomjs_capture module and setting the install location of phantomjs.

There's gotta be an easier way to do this. Any help would be greatly appreciated. Thanks for your work on this great utility.

PS Slacked pirog on this last week, he mentioned I should open this bug if it's not installed by the recipe.

**Comment by rbertolette** [comment]
Just discovered that in lando version: v3.0.0-rc.13, phantom-2.1.1 is installed at:
`/srv/bin/phantomjs`
so changing the path to phantomjs (set at /admin/config/user-interface/phantomjs_capture)
from `/srv/bin/phantomjs-2.1.1` to `/srv/bin/phantomjs` was all In needed to do.

**Comment by pirog** [comment]
@rbertolette yup exactly! Not sure how easy it is to get phantom 1.7.0 at this point but we should definitely be able to handle at least both `/srv/bin/phantomjs` and `/srv/bin/phantomjs-2.1.1`

**Comment by pirog** [comment]
ok @rbertolette , the latest rc.14 should have *both* versions of `phantomjs` now and at the same paths that `pantheon` has them
