### ISSUE TITLE
Bug with RC13 - ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'

### ISSUE THREAD

**Issue by Markus-Schmitt** [lando/lando#1510]
I already posted about my problem in a closed issue (https://github.com/lando/lando/issues/1004#issuecomment-470023559), wrongly thinking it would reopen with a new reply. But I did some additional tests and think it deserves a new issue.
Old post from link above:
> 
> 
> 
> I have the same problem with the newest Lando version.
> I am trying to setup the project for platform.sh from here: https://github.com/thinktandem/template-drupal8.
> 
> > # Bug Report
> > **Tell us about your setup**
> > Lando v3.0.0-rc.13 and Docker Version 18.03.1-ce-win65 (17513) on Windows 10 Professional
> > **Tell us about your `.lando.yml`**
> > ```yaml
> > # Change this name to something that makes sense for your project
> > name: translationupdates
> > # Excludes rarely edited folder / files to win performance.
> > excludes:
> >  - drush
> >  - scripts
> >  - vendor
> >  - web/core
> >  - web/modules/contrib
> >  - web/profiles/contrib
> >  - web/sites/default/files
> >  - web/themes/contrib
> > # Use the recipe appropriate for your application.
> > recipe: drupal8
> > # Configure the D8 recipe to match up closer to a vanilla platform.sh stack
> > config:
> >  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
> >  via: nginx
> >  # Set the webroot to match your .platform.app.yaml.
> >  webroot: web
> >  # Set this to match the version in your .platform.app.yaml.
> >  php: 7.2
> >  # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
> >  # Specify the version to match what's in services.yaml.
> >  database: mariadb
> > # The following additional build step will install the Platform CLI
> > # in the application container and auto-run `composer install`
> > services:
> >  appserver:
> >    run:
> >      - "mkdir -p /var/www/.platformsh/bin"
> >      - "curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.40.2/platform.phar"
> >      - "chmod ug+x /var/www/.platformsh/bin/platform"
> >      - "cd /app && composer install"
> >    overrides:
> >      environment:
> >        BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'
> >        PLATFORMSH_CLI_TOKEN: "$PLATFORMSH_CLI_TOKEN"
> >        PLATFORMSH_PROJECT_ID: "t5lb5eonwa4uq"
> > # The following entry creates a `lando platform` command that will run
> > # any Platform CLI command from inside the container if desired.
> > tooling:
> >  platform:
> >    service: appserver
> >    description: Run Platform CLI commands
> >    cmd: /var/www/.platformsh/bin/platform
> >  phplint:
> >    service: appserver
> >    cmd: /app/vendor/bin/phplint
> >  phpcs:
> >    service: appserver
> >    cmd: /app/vendor/bin/phpcs
> >  phpunit:
> >    service: appserver
> >    cmd: /app/vendor/bin/phpunit
> >  phpstan:
> >    service: appserver
> >    cmd: /app/vendor/bin/phpstan
> >  behat:
> >    service: appserver
> >    cmd: /app/vendor/bin/behat
> > ```
> > 
> > 
> > **Tell us about the command you were running**
> > ```shell
> > lando start
> > ```
> > 
> > 
> > **Tell us about the error you got**
> 
> ```
> Let's get this party started! Starting app..
> Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
> Creating network "translationupdates_default" with the default driver
> Creating volume "translationupdates_exclude_drush" with default driver
> Creating volume "translationupdates_exclude_scripts" with default driver
> Creating volume "translationupdates_exclude_vendor" with default driver
> Creating volume "translationupdates_exclude_web_core" with default driver
> Creating volume "translationupdates_exclude_web_modules_contrib" with default driver
> Creating volume "translationupdates_exclude_web_profiles_contrib" with default driver
> Creating volume "translationupdates_exclude_web_sites_default_files" with default driver
> Creating volume "translationupdates_exclude_web_themes_contrib" with default driver
> Creating volume "translationupdates_data_mounter" with default driver
> Creating volume "translationupdates_home_mounter" with default driver
> Creating translationupdates_mounter_1 ... error
> 
> ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
> 
> ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> Creating translationupdates_mounter_1 ... error
> 
> ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_profiles_contrib:\\\\tmp\\\\web\\\\profiles\\\\contrib"\nis not a valid Windows path'
> 
> ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_profiles_contrib:\\\\tmp\\\\web\\\\profiles\\\\contrib"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> Creating translationupdates_mounter_1 ... error
> 
> ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_sites_default_files:\\\\tmp\\\\web\\\\sites\\\\default\\\\files"\nis not a valid Windows path'
> 
> ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_sites_default_files:\\\\tmp\\\\web\\\\sites\\\\default\\\\files"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> Creating translationupdates_mounter_1 ... error
> 
> ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
> 
> ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> Creating translationupdates_mounter_1 ... error
> 
> ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
> 
> ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_vendor:\\\\tmp\\\\vendor"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> Creating translationupdates_mounter_1 ... error
> 
> ERROR: for translationupdates_mounter_1  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_themes_contrib:\\\\tmp\\\\web\\\\themes\\\\contrib"\nis not a valid Windows path'
> 
> ERROR: for mounter  Cannot create container for service mounter: b'Mount denied:\nThe source path "translationupdates_exclude_web_themes_contrib:\\\\tmp\\\\web\\\\themes\\\\contrib"\nis not a valid Windows path'
> ERROR: Encountered errors while bringing up the project.
> Removing network translationupdates_default
> Removing volume translationupdates_exclude_drush
> Removing volume translationupdates_exclude_scripts
> Removing volume translationupdates_exclude_vendor
> Removing volume translationupdates_exclude_web_core
> Removing volume translationupdates_exclude_web_modules_contrib
> Removing volume translationupdates_exclude_web_profiles_contrib
> Removing volume translationupdates_exclude_web_sites_default_files
> Removing volume translationupdates_exclude_web_themes_contrib
> Removing volume translationupdates_data_mounter
> Removing volume translationupdates_home_mounter
> error: Error
>     at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
>     at runCallback (timers.js:696:18)
>     at tryOnImmediate (timers.js:667:5)
>     at processImmediate (timers.js:649:5)
> From previous event:
>     at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
>     at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
>     at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
>     at exports.start.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
>     at Promise.each.Promise.retry (C:\snapshot\lando\build\cli\lib\router.js:0:0)
>     at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
>     at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
>     at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
>     at ontimeout (timers.js:427:11)
>     at tryOnTimeout (timers.js:289:5)
> ```
> 
> > **Tell us generally about your bug**
> > After switching from beta 47 to rc13, whenever I attempt to lando start  I get the error above. It happens with a completely new site and installing Lando and Docker from scratch. I am not sure, if I am supposed to use the base.lando.yml file or create my own lando.yml file, but the problem happens with both.
> > Please detail the steps we can take to replicate this bug. Be as detailed as possible.
> > ```shell
> > git clone https://github.com/thinktandem/template-drupal8 translationupdates
> > lando start
> > ```
> > 
> > 
> > **Tell us more**
> > Does this bug prevent you from using lando? Yes (at least rc13)
> > I've tried (unsuccessfully) to fix this by uninstalling Lando and Docker, rebooting, sharing Drive C: and reinstalling.

New findings:
Installing rc12 with the corresponding Docker version doesn't show the error. But as soon as I upgrade to rc13 without installing Docker, I get the "not a valid windows path" error. So something must have changed there.
After uninstalling rc13 and installing rc12, everything works fine again.

**Comment by pirog** [comment]
@Markus-Schmitt this is actually a separate issue and has to do with the experimental performance feature we added to rc13 over at #1460. 

While we definitely should fix this devs over thereat #1460 should be using `.lando.local.yml`s to test this feature out and not committing it to their repos since it could negatively impact other users as evidenced by this issue itself.

**Comment by pirog** [comment]
OK this should be fixed in latest release
https://github.com/lando/lando/releases

**Comment by sameronline** [comment]
@pirog i'm running lando RC14 and i still ahve this issue

```
ERROR: for solr  Cannot create container for service solr: b'Mount denied:\nThe source path "/w/sw.ndm/co
debase/nema/docroot/modules/contrib/search_api_solr/solr-conf/4.x:\\\\opt\\\\solr\\\\example\\\\multicore
\\\\core0\\\\conf"\nis not a valid Windows path'
```

**Comment by pirog** [comment]
@sameronline note that this is a different path eg a separate issue. I'd open a different ticket.

**Comment by sameronline** [comment]
@pirog got it, i will open a different issue, i will open a new issue, it happens when you define a new custom volumes in windows like this...
``` 
  solr:
    type: compose
    services:
      image: guywithnose/solr:4.5.1
      #@see https://github.com/guywithnose/docker-solr/blob/master/4.5.1/Dockerfile
      working_dir: /opt/solr/example
      command: java -Dsolr.solr.home=multicore -jar start.jar
      volumes:
        ##- 'codebase/nema/docroot/modules/contrib/search_api_solr/solr-conf/4.x:/opt/solr/example/multicore/core0/conf:ro'
        ##- '.lando/data/solr:/opt/solr/example/multicore/core0/data:rw'
      ports:
        - '8983'
```

**Comment by pirog** [comment]
@sameronline AFAIK that should work you might just need to play around with the paths

**Comment by sameronline** [comment]
@pirog i tried, these pathes does exist but it still reporting this mount denied issues, I looked into the the ~/.lando/compose files and it seems to be good

**Comment by sameronline** [comment]
@pirog the workaround seems to be using volumes like this

```
      volumes:
        - '${LANDO_APP_ROOT_BIND}/codebase/nema/docroot/modules/contrib/search_api_solr/solr-conf/4.x:/opt/solr/example/multicore/core0/conf:ro'
        - '${LANDO_APP_ROOT_BIND}/.lando//data/solr:/opt/solr/example/multicore/core0/data:rw'
```
