### ISSUE TITLE
Lando Push Failed but the 'Push complete!' message still appeared

### ISSUE THREAD

**Issue by oscarmrom** [lando/lando#1522]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

Version v3.0.0-rc.13

**Please explain your request and its importance in the form of a user story.**

As a Lando user, I'd like a clearer error message upon a failed _lando push_. I'm new to Lando and at first, I believed the _lando push_ command had succeeded. The message is green and says "Push complete!" no matter the outcome.

Upon closer investigation, there were hints that mentioned why the push may have failed some lines above the "Push complete" message. 

**Please provide some detail on how lando can help solve this problem**

If you could instead say "Push failed" in red text to be clearer and easier to spot when a "lando push" has failed. 

**Describe the solution you'd like**
Change the message after a _lando push_ to reflect whether it failed in red text "Push failed", please.

Thank you

**Comment by pirog** [comment]
Unstale
