### ISSUE TITLE
Document ability to override nginx settings for LEMP

### ISSUE THREAD

**Issue by nlighteneddesign** [lando/lando#1523]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/tutorials/lemp.html#using-custom-config-files

**Describe the change you'd like**
Landofile using custom LEMP config

Mention you can override nginx.conf with the vhosts key

```recipe: lemp
config:
  config:
    php: config/php.ini
    database: config/my-custom.cnf
    vhosts: config/nginx.conf
```

**Comment by pirog** [comment]
@nlighteneddesign docs should be updated across the board to reflect that you can set `server` and `vhosts` config in various areas
