### ISSUE TITLE
Allow services to be removed from recipes via a null service

### ISSUE THREAD

**Issue by danielnitsche** [lando/lando#1532]
**Please explain your request and its importance in the form of a user story.**

As a lando user who uses recipes
I want to be able to turn off certain services in a recipe
So that I can benefit from recipes, but not have to run every service in them

As a team of developers using lando with multiple services in one application
I want each developers to be able to turn off services when they are not required
So that less resources are required to run an application locally

**Please provide some detail on how lando can help solve this problem**

Lando RC2 and up provides the ability to override services via a `.lando.local.yml` file. This works great for adding/override services, but it's difficult to use to remove services. The ability to easily turn off a service would be of great use.

**Is your feature request related to a problem? Please describe.**

It's difficult to turn off services at the moment, because the `services` object is merged, not overwritten. This means there is no way to "unset" a service, other than nulling the services completely in one place (eg. `services: ~`) then setting each individual services you want in another file.

**Describe the solution you'd like**
If it's possible, a null service may be a good way to address this. So for example, if I wanted a laravel recipe with no database, I could define something like this:

```
name: My Laravel App
recipe: laravel
config:
    webroot: public
services:
    database: nullService
```

**Describe alternatives you've considered**
As above, overriding via multiple `.lando.base.yml`/`.lando.yml`/`.lando.yml` is the only way I've found to do this, but it sort of defeats the purpose of a recipe if you need to redefine everything again.

I've also looked at trying to use yaml to achieve this, but it seems too limited to work.

**Comment by martin-klima** [comment]
@pirog Could be this feature request reopened, please? I think it is a good idea for teamwork. Thanks.

**Comment by pirog** [comment]
@martin-klima we dont plan on adding support for this feature because it should be already possible to do if you structure your services and landofiles correctly.

**Comment by martin-klima** [comment]
@pirog Thank you for your answer. Can I get more information (link) about the correct structure of services?

**Comment by jcmartinez** [comment]
@pirog Could you explain more?

I have a similar situation with a multisite installation of Drupal and I'd like to remove the `database` service that comes with the Drupal recipe by default because my computer is getting a bit slow.

In my case, I can't use the default database for one of the multisites. It would be helpful if you could provide some idea on how to achieve removing or renaming a service from a recipe.

As far as I can tell, my best option is not to use a recipe like "drupal8", but rather configuring a .lando.yml file with each service listed. Correct?

**Comment by danielnitsche** [comment]
The way I solved this in the end was to use a single database service. This is in my lando file:

`services:
  # Use a single container for all databases to reduce the resources needed locally.
  database:
    run_as_root:
      - /bin/sh -c "for i in `ls -d /app/web/sites/* | grep -v '\.' | sed 's#/app/web/sites/##'`; do /app/scripts/create-database.sh $i; done"
`

And this is the create-database.sh:
`#!/bin/sh
mysql -u root -e "CREATE DATABASE IF NOT EXISTS \`$1\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -u root -e "CREATE USER IF NOT EXISTS '$1@%' IDENTIFIED BY 'password';"
mysql -u root -e "GRANT ALL PRIVILEGES ON \`$1\`.* TO '$1'@'%' IDENTIFIED by 'password';" `

Nice this about this is even if you have 50 Multisites, you only have a single db service with 50 empty databases.

**Comment by pirog** [comment]
Nice @danielnitsche, any interest in turning that into a guide?
https://docs.lando.dev/contrib/guides-intro.html

Let me know!

**Comment by jcmartinez** [comment]
That's clever @danielnitsche.

**Comment by danielnitsche** [comment]
> Nice @danielnitsche, any interest in turning that into a guide?
> https://docs.lando.dev/contrib/guides-intro.html
> 
> Let me know!

I’m not using lando or Drupal day to day anymore, so I won’t have time sorry. Thanks for all you work with this project though, I think it’s great.

**Comment by garrettw** [comment]
I, too, would like to know the proper way to disable the database portion of a recipe.
