### ISSUE TITLE
Get Remote URL for remote source doesn't allow for URLs not ending with a file extension

### ISSUE THREAD

**Issue by GMSteuart** [lando/lando#1549]
### Description
When using a remote source without a file extension, say a GitHub tarball URL, `get-remote-url.sh` will fail to uncompress the file because the scripts assumes there is an extension.

### Criticals
v3.0.0-rc.14 on Mac OSX 10.13.6
.lando.yml not applicable

### Reproduce
```bash
mkdir drupal-test
cd drupal-test

lando init \
--source remote \
--remote-url=https://github.com/drupal-composer/drupal-project/tarball/8.x \
--recipe drupal8 \
--webroot web \
--name drupal-test

ls -la
```

Notice nothings was uncompressed into the directory

### Reason
[get-remote-url.sh](https://github.com/lando/lando/blob/master/plugins/lando-recipes/scripts/get-remote-url.sh)

```bash
cd "$SRC_DIR" && curl -fsSL -O "$URL"
```

forces the archive to be downloaded as `8.x`

```bash
DOWNLOADED_FILE=( "$SRC_DIR"/* )
  [[ -e $DOWNLOADED_FILE ]] && echo "Downloaded to $DOWNLOADED_FILE" || { echo "Matched no files" >&2; exit 1; }

  FILENAME="${DOWNLOADED_FILE##*/}"
  EXTENSION="${FILENAME##*.}"
```

EXTENSION ends up equalling `x` resulting in none of the conditions below being satisfied

```bash
OPTIONS="-C /app $OPTIONS"
  if [ "$EXTENSION" = "gz" ]; then
    tar -xvzf "$DOWNLOADED_FILE" $OPTIONS
  elif [ "$EXTENSION" = "bz2" ]; then
    tar -xvjf "$DOWNLOADED_FILE" $OPTIONS
  elif [ "$EXTENSION" = "xz" ]; then
    tar -xvJf "$DOWNLOADED_FILE" $OPTIONS
  elif [ "$EXTENSION" = "zip" ]; then
    unzip -o "$DOWNLOADED_FILE" -d /app
  fi
```

### Q/A

Could better documentation have prevented this issue? 
- Yes, specifying that the remote URL needs to end with file type would have helped

if so what should we change?
1. Update docs to reflect that the only currently supported remote URLs are ones ending in `.gz`, `.bz2`, `.xz`, and `.zip`.
2. Add an else in the file extension check that outputs an error saying file was downloaded, but could not be uncompressed.
3. Considerations:
 - Option 1: adding a third argument to `get-remote-url.sh` that is `filename`. Could be set in the init process with something like `--remote-filename`. When this option is set, instead of running `curl -fsSL -O "$URL"` run `curl -fsSL "$URL -o $FILENAME"
- Option 2: adding a third argument to `get-remote-url.sh` that is `extension` set via init process with something like `--remote-ext`. When this option is set, the script skips trying to determine what the extension is and executes normally. This can be used in tandem with point 2 above informing user to set `remote-ext` if init process is not working due to URL not having a file extension because of the `-O` parameter currently being used.

There are other possibilities as well, like searching for `tarball` in url, but I will end here with what I have listed above.

Does this bug prevent you from using lando?
No

**Comment by pirog** [comment]
unstale
