### ISSUE TITLE
Trust Lndo Cert Documentation needs update for Debian

### ISSUE THREAD

**Issue by tenken** [lando/lando#1550]
This is also related to a recent issue: #1250

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/config/security.html

**Describe the change you'd like**
The directions are in general down the right path, but for Ubuntu the *.pem files for the lando self-signed certs will not be implicitly added by the `ca-certificate-update --fresh` command. The certs are generated with a file suffix that is not handled by Ubuntu 16.04 utilities. The certs must be `.crt` files to be added to the local trust store.

This is documented at:
http://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html

> Furthermore  all  certificates  with  a  .crt  extension  found below /usr/local/share/ca-
       certificates are also included as implicitly trusted.

**Comment by pirog** [comment]
Ahh nice, good to know @tenken. I think the resolution here should be two fold

1. Also make sure CA generation produces a .crt file
2. Update the docs so they copy both pem and crt files to the correct location

**Comment by pirog** [comment]
Alright, im guessing this is an improvement
https://github.com/lando/lando/commit/a0b6ac315743cdd9e9a3bcb12a05f4ad123ffb09
