### ISSUE TITLE
Adding Magento 2 recipe to Lando

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1553]
I'd like to open up a conversation around adding Magento 2 support to Lando and get a feel of if there is enough demand to justify it being part of the core Lando package. I've gone over in detail my opinionated version of what this might look like in Lando within this PR https://github.com/lando/lando/pull/1552.

Here are some of the details from said PR:

> - A Magento 2 recipe (currently locked to NGINX)
>   - Redis & Database service versions are default to Magento 2.3 suggested versions
> - Additional tooling:
>   - Magento Cli 
>   - Magerun Cli (Additional open source Magento tooling)
>   - `magento:env:apply` tooling for configuring Magento to use Lando services
>   - `magento:fresh` tooling for devs who want a "quick install" and "quick reset" option for new projects
> 
> Items to consider:
> - Option to disable the cache & session redis created by the recipe
> ...
> - Magento recommends using ElasticSearch 5.2. For now, this is not included in the recipe because it tends to load slowly and, in general, just piss Lando off. If this PR is of interest to the Lando team then we may have to consider how or if we deal with ElasticSearch at all.

**Comment by tylerssn** [comment]
I'd like to see this remain open just a little longer. I will not "unstale" if it "staled" again.

**Comment by rhuffstedtler** [comment]
I'd like to see it. I appreciate the work you did with that gist you posted for getting it running on the lemp recipe, but I'm four hours into fighting with it and don't have it up yet.

**Comment by tylerssn** [comment]
Are you referring to the PR https://github.com/lando/lando/pull/1552? If so, I'll come that branch tomorrow and follow the documentation I added to see if I missed anything. 

Though I only tested this on Ubuntu, the tests were passing at the time I opened the PR. There are probably issues with recent updates to Lando vs the version I developed this recipe

**Comment by tylerssn** [comment]
Ah, the gist you're referring to must be https://gist.github.com/tylerssn/48c6ec37d45a3f96da3d6549cbc67d00.

This was developed on an earlier RC - I think everything >=RC12 is intended to be much more stable. If I have some down time at work tomorrow I'll update it for you. I imagine the biggest issue is the outdated NGINX config for Lando.

**Comment by tylerssn** [comment]
Some interest in this expressed here: https://github.com/improper/lando-magento2-template/issues/3
