### ISSUE TITLE
Cannot use Drush/Drupal with Pantheon recipie

### ISSUE THREAD

**Issue by a-c-engler** [lando/lando#1555]
Lando v3.0.0-rc14

Windows 10

lando.yml

> name: xxx
> recipe: pantheon
> config:
>   framework: drupal8
>   site: xxx
>   id: xxx

Can't use drush.
I've tried destroying/rebuilding/adding tooling, but nothing seems to work.

> lando drush
> **/usr/bin/env: 'php\r': No such file or directory**

I've gone into lando ssh and can find drush there.

> which drush
> /app/vendor/bin/drush

Same error appears when doing a rebuild:

> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   599    0   599    0     0   3299      0 --:--:-- --:--:-- --:--:--  3309
> 100 4580k  100 4580k    0     0  3998k      0  0:00:01  0:00:01 --:--:-- 5370k
> 
> **/usr/bin/env: 'php\r': No such file or directory**
> error: Looks like one of your build steps failed! with Error
>     at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
> From previous event:
>     at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
>     at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
>     at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
>     at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
> From previous event:
>     at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
>     at runCallback (timers.js:696:18)
>     at tryOnImmediate (timers.js:667:5)
>     at processImmediate (timers.js:649:5)
> From previous event:
>     at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
>     at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
>     at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
> From previous event:
>     at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
>     at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
>     at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
>     at Object.exports.runBuild (C:\snapshot\lando\build\cli\plugins\lando-services\lib\utils.js:0:0)
>     at AsyncEvents.module.exports.app.events.on.app.events.on (C:\snapshot\lando\build\cli\plugins\lando-services\app.js:0:0)
>     at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js:0:0)
>     at emit.Promise.each.fn (C:\snapshot\lando\build\cli\lib\events.js:0:0)
> From previous event:
>     at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js:0:0)
>     at module.exports.start.initAndReport.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
> From previous event:
>     at App.start (C:\snapshot\lando\build\cli\lib\app.js:0:0)
>     at module.exports.rebuild.initAndReport.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
> From previous event:
>     at App.rebuild (C:\snapshot\lando\build\cli\lib\app.js:0:0)
>     at Object.exports.appToggle (C:\snapshot\lando\build\cli\plugins\lando-core\lib\utils.js:0:0)
>     at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\rebuild.js:0:0)
>     at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
> From previous event:
>     at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
> From previous event:
>     at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
>     at runCallback (timers.js:696:18)
>     at tryOnImmediate (timers.js:667:5)
>     at processImmediate (timers.js:649:5)
> From previous event:
>     at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
>     at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
>     at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
>     at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
>     at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
>     at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
>     at Module._compile (pkg/prelude/bootstrap.js:1254:22)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
>     at Module.load (internal/modules/cjs/loader.js:610:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:541:3)
>     at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
>     at startup (internal/bootstrap/node.js:274:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
> warn: This **MAY** prevent your app from working
> warn: Check for errors above, fix them, and try again

**Comment by fafunas** [comment]
I have the same problem, and the same configuration. The only thing i found is to clone the site from pantheon with the Ubuntu terminal in Windows
