### ISSUE TITLE
Typo on Services page

### ISSUE THREAD

**Issue by RichardDavies** [lando/lando#1556]
**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/config/services.html

**Describe the change you'd like**
There is a typo in the 4th paragraph:

> Note that you will need to set the type and its optional version to be **eitehr** one of the supported services below or as defined in one you create your own.

**Comment by RichardDavies** [comment]
keepalive

**Comment by pirog** [comment]
Thanks for the report @RichardDavies!

also worth pointing out that its super easy to submit a PR for these kinds of changes directly in the github ui ;)

**Comment by RichardDavies** [comment]
@pirog 	PR submitted. https://github.com/lando/lando/pull/1609

**Comment by pirog** [comment]
much appreciated!
