### ISSUE TITLE
Read from stdin for php

### ISSUE THREAD

**Issue by rotemreiss** [lando/lando#1558]
*v3.0.0-rc.7 on Ubuntu 18.04*

The contents of my `.lando.yml`:

```yml
name: myapp
recipe: drupal8
config:
  webroot: docroot
  xdebug: true
```

*About to problem:*
Seems like `lando php` doesn't support piping data into it (e.g. read from stdin) and more than that - the program doesn't run.

*Reproduce the issue*
Running the command `echo "test" | lando php -r "fwrite(STDOUT, 'foo');"` ends with empty response, while running `lando php -r "fwrite(STDOUT, 'foo');"` does prints "foo". I also tried with `fopen` and looks like the command is not being executed.

**Tell us about the error you got**
The output of the above with -vvv:
```
[36mverbose[39m: Running ["/usr/bin/docker","exec","--tty","--interactive","--user","www-data","--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","myapp_appserver_1","php","-vvv","-r","fwrite(STDOUT, 'foo');"] in /var/www/html/myapp with options {"mode":"attach","detached":false}
[36mverbose[39m: /usr/bin/docker,exec,--tty,--interactive,--user,www-data,--workdir,/app,--env,PHP_MEMORY_LIMIT=-1,myapp_appserver_1,php,-vvv,-r,fwrite(STDOUT, 'foo'); finished with code 1
```

while the working one's output is:
```
[36mverbose[39m: Running ["/usr/bin/docker","exec","--tty","--interactive","--user","www-data","--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","myapp_appserver_1","php","-vvv","-r","fwrite(STDOUT, 'foo');"] in /var/www/html/myapp with options {"mode":"attach","detached":false}
PHP 7.2.14 (cli) (built: Jan 22 2019 22:30:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.14, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans
[36mverbose[39m: /usr/bin/docker,exec,--tty,--interactive,--user,www-data,--workdir,/app,--env,PHP_MEMORY_LIMIT=-1,myapp_appserver_1,php,-vvv,-r,fwrite(STDOUT, 'foo'); finished with code 0
```

Thanks.

**Comment by rotemreiss** [comment]
Can a maintainer take a look on that one and point me to the relevant piece of code? I'll be happy to look into it and provide a patch, but not sure where to start from.

**Comment by rotemreiss** [comment]
I think that newer version of Lando fixed the issue that it just hanged up, so now the program continues, but still not getting the value of STDIN.
Tested it now again with Lando v3.0.0-rc.14 and the following command `echo 'Hello, World!' | lando php -r 'echo file_get_contents("php://stdin");'`.

@pirog Thanks for reopening that one. Maybe you can point me to the relevant piece of code and I'll look into it?

**Comment by pirog** [comment]
unstale
