### ISSUE TITLE
lando npm and lando yarn require custom tooling definitions

### ISSUE THREAD

**Issue by RichardDavies** [lando/lando#1559]
**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/tutorials/node.html#installing-global-dependencies

**Describe the change you'd like**
The instructions under "Use package.json if you can" refer to running _lando npm_ or _lando yarn_, but fail to mention that these are custom tooling commands that must first be defined in your landofile. A bit more explanation on how to set that up would be helpful.

**Comment by GMSteuart** [comment]
@RichardDavies probably best to reference [tooling](https://docs.devwithlando.io/guides/frontend.html) somewhere in there

**Comment by pirog** [comment]
Yup totally agreed a note here makes sense. I'm doing a general pass on doc updates so let me try and sneak this in as well.

**Comment by pirog** [comment]
Alright, we will be adding a few clarifying sentences when we roll the next release
https://github.com/lando/lando/commit/f2ae54e9ed364026317da5178b143cf2d8d5e2c3
