### ISSUE TITLE
lando rebuild with "Disable pulling images" option

### ISSUE THREAD

**Issue by martin-klima** [lando/lando#1565]
It would be great to have some option to disable pulling a docker images after `lando rebuild` command when we need it. 

This feature request is a fresh version of #681 with one change: If we change the Landofiles we always need to explicitly use `lando rebuild` since Lando RC2.

Regarding comment on https://github.com/lando/lando/issues/681#issuecomment-373282662 Lando pulls image only if a new one is available, otherwise it will use the local one. This feature is the best solution for most of cases. But there are some situations where this feature could cause problems, for example workshop and trainings.

Let's have group of developers on training in some hotel or school. They have all images downloaded from previous day, because they started lando with prepared and posted landofile with exactly defined images, like php: 7.2 etc... Everything is ready to start... 
After `lando rebuild` the whole group is starting to download several GBs, hotel's WiFi is overloaded, everyone's waiting and the workshop is gone.

**Proposed solution**

Examples:
`lando rebuild --no-pull`
`lando rebuild --local-images`
or any similar option/switch/flag.

Thank you for considering it.

**Comment by pirog** [comment]
unstale

**Comment by martin-klima** [comment]
Thank you @pirog for constantly removing the `wontfix` label. I really appreciate it.
Is there any plan to actually implement this feature? It'd be a very useful time saver.
Meanwhile is it possible to use any workaround (e.g. delete some cached files and restart)?

**Comment by pirog** [comment]
@martin-klima as soon as we have time and money to do so!
