### ISSUE TITLE
Add Lando logo to main README.md

### ISSUE THREAD

**Issue by co16353sidak** [lando/lando#1568]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io
https://github.com/lando/lando

**Describe the change you'd like**
Would love it if we were to add the Lando logo in the main README.md 🥇

**Comment by pirog** [comment]
Im down for _something_ like this but i'd love for us to have some better design assets first

**Comment by co16353sidak** [comment]
@pirog  If you are looking for a logo, how about we create a simple one for now ?
