### ISSUE TITLE
config.js is missing require('path')

### ISSUE THREAD

**Issue by jnous** [lando/lando#1571]
I was experimenting with using a custom Docker host with lando, and ran into issue as I had to set `certPath` in `~/.lando/config.yml`.

I get `ReferenceError: path is not defined`, and it looks to me like it is simply because `lib/config.js` does not require `path`, so maybe this could be fixed with simply adding `const path = require('path');` at the top? Setting the `engineConfig.ca` etc. uses `path.join()` when `engineConfig.certPath` is defined, so the error won't be hit "in normal circumstances".

I know the remote Docker hosts are an unsupported feature, but the error is simple enough, I think.

**Comment by pirog** [comment]
ahh nice catch @jnous, definitely a bug and likely a regression from our big RC2 refactor
