### ISSUE TITLE
[v3.0.0-rc.14] `lando --clear` not working

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1572]
Expected result:
`lando --clear` purges the cache (ie. rm -rf ~/.lando/cache)

Actual result:
`You need at least one command before moving on`

It appears lando expects at least one non-switch option (aka command) before it can execute.

System specs:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	MX
Description:	MX 18.1 Continuum
Release:	18.1
Codename:	Continuum
$ uname -a
Linux dell-precision-m6700 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1~mx17+1 (2018-02-23) x86_64 GNU/Linux
$ lando version
v3.0.0-rc.14
$ docker -v
Docker version 18.09.4, build d14af54
$ docker-compose -v
docker-compose version 1.23.2, build 1110ad01
```

**Comment by pirog** [comment]
@uberhacker this (`lando --clear`) seems to work as expected for me. Note that it clears the "tasks cache" and not the entire cache

**Comment by uberhacker** [comment]
oh...I guess I was expecting some feedback other than `You need at least one command before moving on`.  Maybe we need to update the notice?

**Comment by pirog** [comment]
Could be, seems easy enough to add better feedback.

**Comment by pirog** [comment]
alright @uberhacker i added some more obvious feedback after this happens. next release.

**Comment by uberhacker** [comment]
I see that.  Nice!  Now we need a `lando clear` command that is the equivalent of `rm -rf ~/.lando/cache`. :)
