### ISSUE TITLE
Pkg: FLAGS_MISMATCH error on OSX

### ISSUE THREAD

**Issue by wansooseo** [lando/lando#1577]
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*Mac Mojave version: 10.14.4*
*node: v11.12.0*
*Homebrew 2.1.0
Homebrew/homebrew-core (git revision 1867; last commit 2019-04-08)
Homebrew/homebrew-cask (git revision 7228b33; last commit 2019-04-08)*

1. Installed lando using Homebrew
`brew cask install lando`
version: 3.0.0-rc.14

2. Install successful.

3. Run `lando version`

4. Getting `Pkg: FLAGS_MISMATCH` error

5. Run `lando start`

6. Getting `Pkg: FLAGS_MISMATCH` error every single time

7. `brew info lando
Error: No available formula with the name "lando"
Found a cask named "lando" instead.
lando: 3.0.0-rc.14
https://docs.devwithlando.io/
/usr/local/Caskroom/lando/3.0.0-rc.14 (5 files, 541.0MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lando.rb
==> Name
Lando
==> Artifacts
LandoInstaller.pkg (Pkg)`

8. Try to run the installer rather than Homebrew but getting the same error

**Comment by pirog** [comment]
@wansooseo never seen this before but after googling it a bit im _guessing_ its because you've got `NODE_OPTIONS` set in your `env` and this is "mismatched" with the NODE_OPTIONS the lando binary is compiled with.
https://spectrum.chat/zeit/now/warning-in-docs-to-unset-node-options-when-installing-now-cli~1f784938-bb12-4ddb-bd18-f86431b84ebd

Going to see if this is something we can UNSET during the lando runtime.

**Comment by pirog** [comment]
SO AFAICT this is something we cannot mitigate directly in lando and is tracked upstream in https://github.com/zeit/pkg over at https://github.com/zeit/pkg/issues/484

Workarounds for people experiencing this are

1. `unset NODE_OPTIONS` and then run `lando`
2. Install `lando` [from source](https://docs.devwithlando.io/installation/source.html)
3. run `NODE_OPTIONS="" lando`
4. Set up a bash alias or wrapper that unsets NODE_OPTIONS before you run `lando`

**Comment by khandar-william** [comment]
mitigation that I found:
use `pkg . --options max_old_space_size=4096`
the executable will no longer look at NODE_OPTIONS `max_old_space_size`
