### ISSUE TITLE
`lando share` command not working in v3.0.0-rc.14

### ISSUE THREAD

**Issue by snize** [lando/lando#1582]
**Tell us about your setup**

v3.0.0-rc.14 on macOS 10.14.4

**Tell us about your `.lando.yml`**

```yml
name: my-project
recipe: drupal8
config:
  webroot: web
```

**Tell us about the command you were running**

```bash
❯ lando start
Let's get this party started! Starting app..
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting myproject_database_1  ... done
Starting myproject_appserver_1 ... done
...
Waiting until database service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            my-project
 LOCATION        /Users/snize/dev/myproject/base
 SERVICES        appserver, database
 APPSERVER URLS  https://localhost:32782
                 http://localhost:32783
                 http://my-project.lndo.site
                 https://my-project.lndo.site
```
then
```bash
❯ lando share -u http://localhost:32783
About to share your app to a whole new world!
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting myproject_database_1  ... done
Starting myproject_appserver_1 ... done
Waiting until database service is ready...
Waiting until appserver service is ready...

YOU ARE NOW SHARED WITH THE WORLD!!!

A local tunnel to your app has been established.

Here is your public url:

https://myproject.localtunnel.me

Press any key to close the tunnel.
```

**Tell us about the error you got**

Got 504 Gateway Time-out on my browser. 

**Tell us generally about your bug**

This is because of `lando share -u http://localhost:32783` reboots containers and change the port number. So, `url` is not valid for the localtunnel option.

```bash
❯ lando share -u http://localhost:32783 -v
info: Bootstraping...
info: config bootstrap beginning...
info: config bootstrap completed.
info: tasks bootstrap beginning...
info: tasks bootstrap completed.
info: engine bootstrap beginning...
info: engine bootstrap completed.
info: app bootstrap beginning...
info: app bootstrap completed.
info: Bootstrap completed.
info: App config files found at ["/Users/snize/dev/myproject/base/.lando.yml"]
About to share your app to a whole new world!
info: Starting app name my-project!
info: App my-project is ready!
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting myproject_database_1  ... done
Starting myproject_appserver_1 ... done
Waiting until database service is ready...
info: Waiting until database service is ready...
Waiting until appserver service is ready...
info: Waiting until appserver service is ready...
info: Connected myproject_database_1 to the landonet
info: Connected myproject_appserver_1 to the landonet
info: Checking to see if https://localhost:32823 is ready.
info: Checking to see if http://localhost:32824 is ready.
info: Checking to see if http://my-project.lndo.site is ready.
info: Checking to see if https://my-project.lndo.site is ready.
info: http://my-project.lndo.site is ready
info: https://my-project.lndo.site is ready
info: http://localhost:32824 is ready
info: https://localhost:32823 is ready

YOU ARE NOW SHARED WITH THE WORLD!!!

A local tunnel to your app has been established.

Here is your public url:

https://myproject.localtunnel.me

Press any key to close the tunnel.
```

**Tell us more**

Can it be changed to automatically set the URL?

**Comment by pirog** [comment]
@snize i think the expectation here is the user has already started their app. That expectation should be made more clear

**Comment by kvij** [comment]
@pirog Doesn't matter what the expectation is. `lando share` _always_ does a `lando start` messing up the provided port number

**Comment by GusboDev** [comment]
Can confirm, having exact same issue.  If it was possible to fix the port for the main appserver (as it is with other services which are portforwarded) then that would solve the issue, however I can't find how to do this within the lando.yaml

**Comment by pirog** [comment]
Fixing ports is definitely not the default behavior we want to have. I'm
guessing this might just be a bug.

**Comment by GusboDev** [comment]
Yeah, I can understand that.  

The issue is that the port changes when the share command is run because the share command runs lando start (or something very close to it), yet needs to have the URL of localhost with the port passed in to the share command.  So it assumes that lando has started already, however the share command runs a start again, causing the port to be randomly assigned away from the port that was passed in to the share command.  Catch 22.

If it was possible then to either have the share command either take the port from the running containers and use that to start new ones (assuming that lando share requires to run lando start), then that would solve the issue.

**Comment by pirog** [comment]
Yup! I think your last statement there is right on the money.

**Comment by GusboDev** [comment]
Just tested on rc16 just in case it had been dealt with, but had the same issue.  For the record, I'm using a Drupal7 recipe, although I think this might be recipe agnostic.  

Also for the record, lando is pretty awesome and has made a huge improvement to streamlining our devops processes.  I only need the share functionality for accessibility testing on a range of devices.

**Comment by mishac** [comment]
Not sure if it's the same error or not, but I just tried rc17 and I get 502 gateway error whenever using lando share.  Tried with both the pantheon recipe and a vanilla drupal 8.

**Comment by pirog** [comment]
different error, you need to make sure you are using the correct URL or its
not going to work. sadly this is not always immediately obvious if your app
is complicated but running `lando info` should help

**Comment by mishac** [comment]
I am using the correct url, AFAIK:
```
$ lando info                                                                                                                             
[                                                                                                                                                                                          
  {                                                                                                                                                                                        
    service: 'appserver',                                                                                                                                                                  
    urls: [                                                                                                                                                                                
      'https://localhost:32994',                                                                                                                                                           
      'http://localhost:32995',                                                                                                                                                            
      'http://share-test.lndo.site',                                                                                                                                                           
      'https://share-test.lndo.site'                                                                                                                                                           
    ],                                                                                                                                                                                     
    type: 'php',                                                                                                                                                                           
    via: 'apache', 
...
```

And then:

```
$ lando share --url http://localhost:32995
About to share your app to a whole new world!

YOU ARE NOW SHARED WITH THE WORLD!!!

A local tunnel to your app has been established.

Here is your public url:

https://fast-wasp-72.localtunnel.me 

Press any key to close the tunnel.
```

And then I go to the browser and get 502.  Unless I'm missing something the url is correct (http://localhost:32995).    And the site is accessible just fine from all 4 URLs locally:

```
$ curl -I localhost:32995
HTTP/1.1 200 OK
...
```

**Comment by mishac** [comment]
One thing I noticed is that the localtunnel.me version says nginx but the local version is Apache, but I don't know if that's relevant or not.

**Comment by pirog** [comment]
Shouldn't matter, localtunnel.me probably just uses nginx as a reverse
proxy.

I'd spin up another issue with steps to replicate. FWIW i've just tried it
on a few difference kinds of lando apps and its been working fine :/

>

**Comment by mikedotexe** [comment]
> I am using the correct url, AFAIK:
> 
> ```
> $ lando info                                                                                                                             
> [                                                                                                                                                                                          
>   {                                                                                                                                                                                        
>     service: 'appserver',                                                                                                                                                                  
>     urls: [                                                                                                                                                                                
>       'https://localhost:32994',                                                                                                                                                           
>       'http://localhost:32995',                                                                                                                                                            
>       'http://share-test.lndo.site',                                                                                                                                                           
>       'https://share-test.lndo.site'                                                                                                                                                           
>     ],                                                                                                                                                                                     
>     type: 'php',                                                                                                                                                                           
>     via: 'apache', 
> ...
> ```
> 
> And then:
> 
> ```
> $ lando share --url http://localhost:32995
> About to share your app to a whole new world!
> 
> YOU ARE NOW SHARED WITH THE WORLD!!!
> 
> A local tunnel to your app has been established.
> 
> Here is your public url:
> 
> https://fast-wasp-72.localtunnel.me 
> 
> Press any key to close the tunnel.
> ```
> 
> And then I go to the browser and get 502. Unless I'm missing something the url is correct (http://localhost:32995).
> 
> ```
> $ curl -I https://fast-wasp-72.localtunnel.me
> HTTP/2 502 
> server: nginx/1.10.1
> ...
> ```
> 
> And the site is accessible just fine from all 4 URLs locally:
> 
> ```
> $ curl -I localhost:32995
> HTTP/1.1 200 OK
> Server: Apache/2.4.25 (Debian)                                                                                                                                                             
> ...
> ```

I'm experiencing the same issue. Not absolutely necessary to have, but was looking forward to playing with `lando share` I'm on `v3.0.0-rc.7`
