### ISSUE TITLE
Installation fails when vm.max_map_count doesn't exist

### ISSUE THREAD

**Issue by w-biggs** [lando/lando#1586]
**Tell us about your setup**

`v3.0.0-rc.14` on WSL - `Ubuntu 18.04.1 LTS`.

**Tell us about the command you were running**

`sudo dpkg -i lando-v3.0.0-rc.14.deb`

**Tell us about the error you got**

`sysctl: cannot stat /proc/sys/vm/max_map_count: No such file or directory`

Max_map_count doesn't exist in WSL - they haven't implemented a dummy version of it like they have with some other /proc/sys/ files.

**Tell us more**

Wrapping this line in an if statement that checks whether `/proc/sys/vm/max_map_count` exists fixes the issue and allows Lando to be installed in WSL:

https://github.com/lando/lando/blob/85dc5ff0bb550842d88e85fd2b06970ac72f31ec/installer/linux/scripts/postinst#L22

```
if [ -f /proc/sys/vm/max_map_count ]; then
  sysctl -w vm.max_map_count=262144
fi
```

I've confirmed this works and Lando properly installs. I'll submit a pull request with this change.

**Comment by pirog** [comment]
@w-biggs nice. sorry for the delay here but this seems like a completely reasonable and good change to me. Will def merge it in!
