### ISSUE TITLE
Elasticsearch fails to start after first successful run

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#1591]
**Using:** Lando 3 RC.14 on Ubuntu 18.04
```yaml
  search:
    type: elasticsearch:6
    plugins:
      - analysis-icu
```

**Recreate Issue:**

```bash
lando destroy -y # Destroys successfully
lando start # Starts Successfully
lando restart # Or `lando poweroff && lando restart` - Fails to start search service
```

**Log**

`lando logs -s search`:

```log
search_1            | Welcome to the Bitnami elasticsearch container
search_1            | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
search_1            | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
search_1            | Send us your feedback at containers@bitnami.com
search_1            | 
search_1            | INFO  ==> ** Starting Elasticsearch setup **
search_1            | DEBUG ==> Validating Kernel settings...
search_1            | DEBUG ==> Validating settings in ELASTICSEARCH_* env vars...
search_1            | INFO  ==> Configuring/Initializing Elasticsearch...
search_1            | DEBUG ==> Detected persisted data from previous deployments
search_1            | DEBUG ==> Ensuring expected directories/files exist...
search_1            | INFO  ==> Custom configuration file detected, using it...
search_1            | DEBUG ==> Using specified values for Xmx and Xms heap options...
search_1            | DEBUG ==> Setting '-Xmx1025m -Xms1025m' heap options...
search_1            | DEBUG ==> Installing plugins: analysis-icu
search_1            | DEBUG ==> Installing plugin: analysis-icu
search_1            | warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME
search_1            | Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-linux-x86_64-6.7.1.zip
search_1            | -> Downloading analysis-icu from elastic
search_1            | Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-6.7.1.zip
search_1            | ERROR: plugin directory [/opt/bitnami/elasticsearch/plugins/analysis-icu] already exists; if you need to update the plugin, uninstall it first using command 'remove analysis-icu'
search_1            | DEBUG ==> Stopping Elasticsearch...
```

**Comment by pirog** [comment]
@tylerssn interesting. This looks like a legit bug to me. Have you tried looking at the underlying bitnami image issue queue for this at all?

**Comment by pirog** [comment]
@tylerssn i closed the other issue you had since it looks like the same underlying cause to me. Here is a link to the relevant comment over there https://github.com/lando/lando/issues/1592#issue-436772365

**Comment by pirog** [comment]
@tylerssn so for resolution here, i think we will need to consult the BITNAMI options a bit better but _seems like_ we just want to install plugins on "first start" and "rebuilds"?

**Comment by tylerssn** [comment]
@pirog - that's right.

**Comment by pirog** [comment]
unstale

**Comment by pirog** [comment]
@tylerssn so finally did some research here. 

I can _definitely_ replicate this but i think it might actually be an upstream bug with the `bitnami/elasticsearch` image either an actual tech bug or a failure on how to document this properly. 

My _guess_ is they need to do better handling around here https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/7/debian-9/rootfs/libelasticsearch.sh#L426
Either by removing/reinstalling the plugin or detecting the plugin already exists and then not trying to install again. 

I'd recommend spinning up an issue there and see what they say. In the meantime i'll keep this open so you can report back.

**Comment by tormi** [comment]
Had the same issue. Seems like this is the upstream at the ES repo: https://github.com/elastic/elasticsearch/pull/41620

**Comment by tormi** [comment]
This helped me out: https://github.com/wunderio/drupal-project/pull/54/commits/d672fc0d3a6755220e026e23b12498f01900b2ce

**Comment by rabauss** [comment]
We cannot start the current `bitnami/elasticsearch:6` with lando and docker for windows anymore!
The `bitnami/elasticsearch:6.5.4` can be started without problems.

By the way, the supported Versions should maybe get an update to switch to a previous `6.8.x`

https://github.com/lando/lando/blob/a82d181f11fdb21bd446b8b50a85849379bf207d/plugins/lando-services/services/elasticsearch/builder.js#L11
