### ISSUE TITLE
[v3.0.0-rc.16] Drupal 7 recipe does not include mysql pdo support

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1615]
Expected behavior: MySQL _"just works"_.

Actual behavior: `PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /app/includes/database/mysql/database.inc:56`

Apparently, the mysql pdo driver is not installed.  It shows up in cli but not in the browser.

```
$ lando ssh
www-data@2d07801f7393:/app$ php -i|grep -i "pdo drivers"
PDO drivers => sqlite, mysql, pgsql
```
```
http://mysite.lndo.site/phpinfo.php
PDO support	enabled
PDO drivers	sqlite
```
I'm using just a basic Drupal 7 recipe as shown in `.lando.yml` below:
```
name: mysite
recipe: drupal7
config:
  webroot: .
```
System specs:
```
$ lando version
v3.0.0-rc.16
$ uname -a
Linux dell-precision-m6700 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1~mx17+1 (2018-02-23) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	MX
Description:	MX 18.2 Continuum
Release:	18.2
Codename:	Continuum
$ docker -v
Docker version 18.09.6, build 481bc77
$ docker-compose -v
docker-compose version 1.23.2, build 1110ad01
```

**Comment by uberhacker** [comment]
FWIW, rebuilding the 7.2-apache docker image from scratch didn't help.  Also, restarting the docker service didn't make a difference.

**Comment by tormi** [comment]
Works for me:

```
recipe: drupal7
config:
  php: '5.6'
  webroot: .
```

<img width="953" alt="Screenshot 2019-05-14 at 17 03 27" src="https://user-images.githubusercontent.com/146800/57704372-70a54100-766a-11e9-9350-06b3dff801ac.png">

**Comment by uberhacker** [comment]
Thank you for the feedback @tormi.  Does this work for you?
```
name: mysite
recipe: drupal7
config:
  php: 7.2 
  webroot: .
```

**Comment by uberhacker** [comment]
I figured out what was the problem.  I had a custom php.ini in web root that was overriding the default /usr/local/etc/php/php.ini used by the cli.  Once i removed the php.ini, order was restored.  Even though this was tough to troubleshoot, it's nice to know that you can override this easily without explicitly specifying a config section in .lando.yml to load a custom php.ini.
