### ISSUE TITLE
Setting xdebug.remote_autostart = 0 on PHP 7.3 results in PHP warning

### ISSUE THREAD

**Issue by calebdelnay** [lando/lando#1618]
I'm running the Drupal 8 recipe with PHP 7.3 and with xdebug enabled. I've tweaked my `php.ini` to set `xdebug.remote_autostart = 0` because I want to control when xdebug tries to start a debug session. After doing so, all hits to PHP result in the following:
```
Warning: Header may not contain NUL bytes in /app/app/index.php on line 14
```

Some searching led me to this bug in xdebug:
https://bugs.xdebug.org/bug_view_page.php?bug_id=00001642

That bug has since been fixed in xdebug 2.7.0. Lando is using xdebug 2.7.0-RC2 for PHP 7.3. Lando should use the latest xdebug for PHP 7.3, which is 2.7.2 as of this writing.

https://github.com/lando/lando/blob/3a89a29e0b2b9fa8c3bf42181e086ada23380838/plugins/lando-services/services/php/7.3-apache/Dockerfile#L40
https://github.com/lando/lando/blob/3a89a29e0b2b9fa8c3bf42181e086ada23380838/plugins/lando-services/services/php/7.3-fpm/Dockerfile#L40

I think those lines could be `pecl install xdebug` now that stable versions are available? Or `pecl install xdebug-2.7.2` if being more deterministic is desired.

It looks like PHP 7.2 needs to be updated too, as it is using 2.6.0beta1. As well as the README files along side the Dockerfiles.

**Comment by AhmadTawila** [comment]
I still have this issue too

**Comment by chrillep** [comment]
is there any reason for this? Its the same on php7.2 it uses xdebug-2.6.0beta1
