### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by james-agile-coop** [lando/lando#1627]
Hi Lando team!

Firstly, thank you for all your hard work on Lando - it's been hugely beneficial for us.

We are currently using RC1 with a large number of projects. We are keen to upgrade as soon as possible but, as this is going to be quite a task, we're a bit worried we'll need to repeat the process if there are further breaking changes before a stable release. Is this something you're aiming to avoid between now and a stable release?

Thanks!

**Comment by pirog** [comment]
@james-agile-coop heyo!

Sorry for the late reply here. So we don't have a stable release yet so we cannot make a 100% guarantee about breaking changes between now and said stable release.

That said i _can_ tell you that we are about 97% sure there will not be any breaking changes from here on out eg the API that exists now will almost for sure be the API in the stable release. 

To back that up a bit more, we do not have any bugs/features currently queued up that would result in such a breaking change. We do not anticipate there being such changes and our primary focus currently wrt getting to stable is adding two more features and fixing bugs.

Hopefully that intel helps guide your decision making a bit better!

**Comment by james-agile-coop** [comment]
Thanks @pirog. That's a big help!
