### ISSUE TITLE
"permission denied" error running lando start

### ISSUE THREAD

**Issue by dfwpamike** [lando/lando#1636]
**Tell us about your setup**

v3.0.0-rc.16 on Windows 10 Enterprise 1709

**Tell us about your `.lando.yml`**

```yml
name: d8-test
recipe: drupal8
config:
  webroot: .
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

```bash
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","landocasetupkenobi38ahsoka6311b8a4b376aef9adf41b3f282f7a5648cb8a6d","--file","C:\\Users\\eatonmse\\.lando\\certs\\ca-0.yml","--file","C:\\Users\\eatonmse\\.lando\\certs\\ca-1.yml","--file","C:\\Users\\eatonmse\\.lando\\certs\\ca-2.yml","--file","C:\\Users\\eatonmse\\.lando\\certs\\ca-3.yml","up","--detach","--no-recreate","--remove-orphans","ca"] in C:\data\lando with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=C:\data\lando
Starting landocasetupkenobi38ahsoka6311b8a4b376aef9adf41b3f282f7a5648cb8a6d_ca_1 ... error

ERROR: for landocasetupkenobi38ahsoka6311b8a4b376aef9adf41b3f282f7a5648cb8a6d_ca_1  Cannot start service ca: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for ca  Cannot start service ca: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
```

**Tell us generally about your bug**

When I installed Lando I had to provide an administrator password, however when I run Docker and Lando I am not running them as administrator. (Although I did try starting Docker and running *lando start* in a command window opened as administrator, with the same results as above.)

**Tell us more**

I have tried uninstalling Lando and Docker for Windows twice now but can't seem to get past this basic error. Working for a state agency my computer is locked down more than most but I'm hoping this is just something simple in the setup process I've missed. I've read good things about Lando and am eager to try it for Drupal development.

Thanks in advance for your help!

**Comment by OlofHaglund** [comment]
I have the same problem but I use lando in WSL instead and docker in windows. The file `lando-entrypoint.sh` has full Write, Read and execute rights (777) and I still get permission denied.

It looks like we have the same issue on different platforms.
**Error**
```
Starting landocasetupkenobi38ahsoka726f301ed44266760cef01d62b1e016b2bb7250e_ca_1 ... error

ERROR: for landocasetupkenobi38ahsoka726f301ed44266760cef01d62b1e016b2bb7250e_ca_1  Cannot start service ca: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for ca  Cannot start service ca: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
````

**Comment by harrysbaraini** [comment]
Exactly same error here, with v3.0.0-rc.16 on Windows 10 Pro 1903.

Interestingly, it was working yesterday.

**Comment by harrysbaraini** [comment]
I've just fixed it. Steps I did:

- Uninstalled Lando
- Uninstalled Docker
- Installed Lando, with Docker for Windows checked.

Previously I've installed Docker using Boxstarter+Chocolatey, and Lando installer opened right after Docker get installed (automatically by my Boxstarter script).

Maybe just installing docker back again with Chocolatey would work.

**Comment by rabauss** [comment]
I also had some trouble with starting lando on windows in the past.
Then I realized that the malware scanner blocked lando.exe and the lando scripts.

By the way you could update windows to a newer version - 1709 is quite old ;-)

**Comment by dfwpamike** [comment]
@rabauss I'll double-check the malware scanner. As for updating Windows, unfortunately being on a government-managed computer means I get Windows updates only when they are approved and released from central IT.
