### ISSUE TITLE
Lando exe download fails every time.

### ISSUE THREAD

**Issue by macronomicus** [lando/lando#1639]
The windows exe will not download, it goes alright for a while then crawls slow then hangs and fails every time, I have tried for the last few months same thing every time.  Is there a problem with exe files and it needs to be a compressed folder?  Is there another place to download aside from github?  My lando install does not work anymore because pantheon api changes so im having to go back to old school methods to dev.  

Is anyone able to download it?

Windows 10 Pro

**Comment by pirog** [comment]
@macronomicus we have a few thousand windows users so im guessing the vast majority of people are able to download it.

**Comment by macronomicus** [comment]
@pirog, thats interesting, I thought it might only be an issue with the file so I waited for another release, but same thing in all releases over the last few months, also thought it might be the browser so tried others to the same ends, or perhaps it might be my windows install but thats been updated to a new release since then too.  Very odd thing, ive never had such a problem on github before.  It just failed twice in a row, gets about half way then hangs and fails.

**Comment by macronomicus** [comment]
It just failed again a fourth time so I went ahead and downloaded it with windows CLI (power shell) worked first try, what an oddity!  Im just glad I got it after about 40 or so failed downloads over the last few months.  lol should have thought to use CLI ... below is the command i used in case anyone needs it.

`(new-object System.Net.WebClient).DownloadFile("https://github.com/lando/lando/releases/download/v3.0.0-rc.16/lando-v3.0.0-rc.16.exe","lando.exe")`

**Comment by harrysbaraini** [comment]
I've just downloaded it two times in the last hour. No problem at all.

**Comment by macronomicus** [comment]
@harrysbaraini Yeah its an odd issue, no telling what it could be, it really perplexed me given the usual culprits for such a thing proved not to be the problem.  I also noticed that it downloaded at least twice the speed using CLI too, the normal download attempts crawled slowly below usually 300kbps or much lower and failed, once even reached nearly 90% downloaded and failed.  I was surprised to see it continue doing the same thing over months as I was sure it was just some random oddity but it persisted.

**Comment by rabauss** [comment]
The download speed of github was/is sometimes a litle bit slow.
But at the moment I have no problems - download on Windows 1809 Chrome 74 with > 3 MB/sec

**Comment by macronomicus** [comment]
Im going to close it since its most likely a github or windows security thing or who knows what? lol anyway its here in the issues if anyone has a similar thing going on and easily gotten around by using CLI to download.
