### ISSUE TITLE
Add "config.xhprof: true" setting to .lando.local.yml to enable XHProf

### ISSUE THREAD

**Issue by synterra** [lando/lando#1642]
As a Lando user that needs to debug slow PHP applications (see: Drupal) I'd like to use the XHProf tool. I'd like to be able to enable/disable it via the local Lando config file. 

In https://github.com/lando/lando/issues/356 there's a proposed change to a recipe that installs XHProf, but it may no longer be valid. It would be preferred to have XHProf already part of the Drupal recipe, so it can be enabled via local config.

**Comment by synterra** [comment]
Looks like XHProf doesn't work on PHP 7.1 and above, you'll need to look at https://github.com/longxinH/xhprof/

**Comment by generalredneck** [comment]
I would like to add some documentation to a PHP 7.0+ version of this found over here: https://agileadam.com/2019/03/tideways-xhgui-using-lando/
