### ISSUE TITLE
Permanent load on solr

### ISSUE THREAD

**Issue by zuernBernhard** [lando/lando#1645]
We have a Drupal 8 Project based on the drupal8 recipe with solr 7.6

solrsearch:
    type: 'solr:7.6'
    core: search

--> after lando start we have permanent load on the solr container without any drupal cron or something like that:

```
solrsearch_1   | 2019-06-03 07:06:33.277 INFO  (qtp1095352419-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/admin/ping params={} hits=14939 status=0 QTime=2
solrsearch_1   | 2019-06-03 07:06:33.278 INFO  (qtp1095352419-16) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/admin/ping params={} status=0 QTime=3
solrsearch_1   | 2019-06-03 07:06:36.018 INFO  (qtp1095352419-15) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/admin/ping params={} hits=14939 status=0 QTime=0
solrsearch_1   | 2019-06-03 07:06:36.018 INFO  (qtp1095352419-15) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/admin/ping params={} status=0 QTime=1
solrsearch_1   | 2019-06-03 07:06:38.870 INFO  (qtp1095352419-21) [   x:search] o.a.s.c.S.Request [search]  webapp=/solr path=/admin/ping params={} hits=14939 status=0 QTime=1
...
```

Is that a lando-specific solr-healthcheck ? How can it be disabled ?

**Comment by pirog** [comment]
Lando leverages docker-compose's healthcheck ability to make sure certain services start correctly. Periodically pinging a service to make sure its still good to go should not cause significant load, certainly not to the point where it would disrupt your ability to develop so its unlikely this is something we will change unless its negatively impacted a huge amount of users.

That said, you _probably_ can disable it by doing a lando service level override and directly modifying the healthcheck so it doesnt do anything, or does some sort of no-load activity.
https://docs.devwithlando.io/config/services.html#overrides

**Comment by gonssal** [comment]
Sorry to comment on a closed issue. I've just noticed this same problem and didn't want to open a new issue. 

While I agree that healthcheck is a good idea, it's currently happening arround every 2 seconds, which creates 2 lines in the Solr log every 2 seconds, which I think we can agree it's a bit too much and makes developing with the log tailed honestly annoying. Maybe setting the ping to 30 or 60 seconds by default instead would be a good idea?

**Comment by pirog** [comment]
AFAIK there hasn’t been an ever present polling healthcheck in lando for
quite some time.
