### ISSUE TITLE
error: Error: Not found error message and pantheon

### ISSUE THREAD

**Issue by jaredlevi** [lando/lando#1654]
When trying to pull from pantheon with a valid token and that token isn't valid for that particular site the following error message is presented:

`error: Error: Not found.

    at Promise.retry.request.(anonymous function).then.catch.err (/snapshot/lando/build/cli/plugins/lando-pantheon/lib/client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

It would be more helpful if a more meaningful error message were presented.

**Comment by pirog** [comment]
Generally we just pass through the error message we get from Pantheon so _its possible_ this is an improvement that needs to be made on their end

**Comment by merlinpatt** [comment]
I'm seeing this issue now too. Lando was working a month ago, and now it's not. I haven't made any configuration changes either.
