### ISSUE TITLE
Document how to enable PHP Sockets inside Lando

### ISSUE THREAD

**Issue by greggmarshall** [lando/lando#1658]
How would I enable the PHP sockets  extension in Lando.  Mink-zombie-driver is complaining about it not being enabled.  I've tried the
     - apt-get update -y
     - apt-get install sockets -y
     - pecl install sockets
     - docker-php-ext-enable sockets
but apt-get install can't find sockets.  it is possible it has a different name, but I can't find it.

**Describe the change you'd like**
I'd like to see documentation that would tell me how to have a lando environment that would run the Drupal behat mink-zombie-driver which requires sockets.

**Comment by eelkeblok** [comment]
For those stumbling upon this from a Google search, you can do this by adding a build step:

```
  build_as_root:
    - docker-php-ext-install sockets
```

**Comment by pirog** [comment]
Going to remove the `wontfix` here and suggest we add augment
https://docs.lando.dev/config/php.html#adding-or-removing-extensions
with some more details (probably just a link to the underlying docker mechanisms) about how to install php extensions

optionally we could create a guide for sockets in particular

**Comment by alphex** [comment]
Add this to your `.lando.yml` file.
Where "appserver" is the default service thats already running in your lando install.  This details the added tasks it has to run when you build it.   IF you want to add this, you'll need to `lando rebuild`.

(check your spacing, for YML requirements)

```
services:
  appserver:
    type: php
    build_as_root:
      - docker-php-ext-install sockets
```
