### ISSUE TITLE
Issue using PHP CLI tool when running via lando

### ISSUE THREAD

**Issue by 0aveRyan** [lando/lando#1662]
**v3.0.0-rc.17 running on macOS 10.13.6**

```yml
name: cli-app
recipe: wordpress
config:
  webroot: .
```

**Tell us about the command you were running**

* Using `league/climate` composer package inside a WP-CLI command
* Running `lando wp [my-custom-command]`

**Tell us about the error you got**

Seems to be an issue with the `lando` command passthrough rendering Checkboxes and Radio Buttons. 

Whenever I run my WP-CLI command, the spacing is off on the list of items. Then, as keyboard input is used to navigate through options the UI, the render is duplicated.

The select tools render fine when I `lando ssh`, running on other servers and local dev environments, etc.

Initial appearance using `lando wp [my-custom-command]`:
<img width="593" alt="Screen Shot 2019-06-12 at 9 13 19 PM" src="https://user-images.githubusercontent.com/9565066/59403335-1675c980-8d57-11e9-8dcc-f55c574e8d69.png">

Upon using up/down arrow keys:
<img width="607" alt="Screen Shot 2019-06-12 at 9 15 08 PM" src="https://user-images.githubusercontent.com/9565066/59403356-31483e00-8d57-11e9-8f0f-1118871e78a2.png">

Expected (when `lando ssh`'d and run natively `wp [my-custom-command]`):
<img width="567" alt="Screen Shot 2019-06-12 at 9 11 56 PM" src="https://user-images.githubusercontent.com/9565066/59403266-d1519780-8d56-11e9-8488-03ae3777d203.png">

**Comment by pirog** [comment]
@0aveRyan we usually just shell out these kinds of things directly to `docker-compose` so it might be worth running the analogous command in `docker-compose` and see if you get the same result. If you do i'd close this and open an issue directly with them. I'm guessing the command should look _something_ like

```bash
docker-compose exec cli-app_appserver_1 wp custom-command
```
