### ISSUE TITLE
lando terminus failed to install on pantheon recipe

### ISSUE THREAD

**Issue by cjyabraham** [lando/lando#1669]
I am running lando v3.0.0-rc.17 and MacOS 10.14.5.

My .lando.yml:
```yml
name: cncf
recipe: pantheon
config:
  framework: wordpress
  site: cncf
  id: e0484f71-2ec0-410d-87af-04b33c4b4939
```

I have been following the instructions [here](https://docs.devwithlando.io/tutorials/pantheon.html) to setup my pantheon site for local development.  All went well up `lando pull`.  I can view the site in my browser etc.  When I go to do `lando pull` I get the following:

```
[~/Sites/cncf]$ lando pull --files=none --code=none
? Pull database from? dev
Attempting to login via terminus...
/helpers/auth.sh: line 12: terminus: command not found
/helpers/auth.sh: line 12: terminus: command not found
/helpers/auth.sh: line 12: terminus: command not found
Destroying all current tables in database... 
/helpers/pull.sh: line 131: terminus: command not found
/helpers/pull.sh: line 161: terminus: command not found
Pulling database from dev...
/helpers/pull.sh: eval: line 171: syntax error near unexpected token `|'
/helpers/pull.sh: eval: line 171: ` | pv | mysql --user=pantheon --password=pantheon --database=pantheon --host=database --port=3306'
Doing the ole post-migration search-replace on WordPress...
/helpers/pull.sh: line 176: wp: command not found

Pull complete!
```

When I try just `lando terminus` I get:
```
[~/Sites/cncf]$ lando terminus
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"terminus\": executable file not found in $PATH": unknown
```

So it looks like terminus is not installed.  Any idea why that didn't get installed or what else I could do to rectify this issue?

**Comment by kylebehse** [comment]
I just updated to rc.17 and am experiencing the same thing.

**Comment by kylebehse** [comment]
Got this:
Killing 123passwords_appserver_1 ... done
Starting 123passwords_appserver_1 ... done
Attempting to login via terminus...
/helpers/auth.sh: line 12: terminus: command not found
/helpers/auth.sh: line 12: terminus: command not found
/helpers/auth.sh: line 12: terminus: command not found

Looked in ~/.lando/services/helpers/ and there is no auth.sh file, just 4 sql/mysql import/export files.

**Comment by kylebehse** [comment]
I spun up a new container with a different name. That seemed to work. Wondering if it's an issue with name-spacing!?!

**Comment by kclarkson** [comment]
@kylebehse thanks! I did a `lando reubild` and everything back.

**Comment by mchelen** [comment]
Same issue here on RC19, `lando rebuild` doesn't seem to help. Getting an error when running:
```bash
lando terminus --version
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"terminus\": executable file not found in $PATH": unknown
```

**Comment by RobertAKARobin** [comment]
@mchelen I'm having the same issue. What did you change the `name` value to?

**Comment by mchelen** [comment]
@RobertAKARobin I just changed it to something else, like from `my-drupal` to `my-drupal-new`

**Comment by plato1123** [comment]
Changing the site "name" in the .lando.yml file seems to have fixed it for me, thanks to @mchelen for the recommendation.
