### ISSUE TITLE
Increase docs body copy legibility

### ISSUE THREAD

**Issue by akolbo** [lando/lando#1677]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/

**Describe the change you'd like**
Bump up the weight and legibility of the body font.

**Remove:**
font-family : "Montserrat" 
font-weight: 300;

**Go with:**
font-family: helvetica neue
font-weight: normal
color: black

![image](https://user-images.githubusercontent.com/11195197/60315646-04865000-992d-11e9-9c75-7ed475d8832f.png)

**Comment by pirog** [comment]
@akolbo good suggestion, however, i'm going to close this in favor of our larger initiative to move our docs over to #1410 and make a note there
