### ISSUE TITLE
PHP appserver Postgres Client version mismatch from default

### ISSUE THREAD

**Issue by jcandan** [lando/lando#1680]
PR #1679 with a functional test has been submitted.

**Tell us about your setup**

v3.0.0-rc.17 on macOS 10.14.5

**Tell us about your `.lando.yml`**

```yml
name: landscan
recipe: drupal8
config:
  webroot: web
  database: postgres
```

**Tell us about the command you were running**

```bash
lando drush sql:sync @source @destination
```

**Tell us about the error you got**

```bash
  Error Output:
  ================
  > pg_dump: server version: 10.8; pg_dump version: 9.6.13
  > pg_dump: aborting because of server version mismatch
```

**Tell us generally about your bug**

I tried to sync databases with drush site aliases.

**Tell us more**

Basically, it boils down to having a different `postgresql-client` version in the `appserver` than the `database`. If you look at the `devwithlando/php` [Dockerfile](https://hub.docker.com/r/devwithlando/php/dockerfile), it installs version `9.x` of the client, even though the `postgres` service defaults to `10.x`.

This proves the mismatch:

```bash
$ lando ssh -c "psql --version"
psql (PostgreSQL) 9.6.13
$ lando psql --version
psql (PostgreSQL) 10.8
```

**Workaround**

For those interested in a temporary fix while waiting for this ticket to be addressed, you may do something like the following:

```bash
services:
  appserver:
    run_as_root:
      - "apt -y update && apt-get install -y gnupg2 && echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list.d/pgdg.list && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && apt -y update && apt-get install -y postgresql-client-10"
```

**Comment by pirog** [comment]
alright @jcandan i've updated all our "supported" php images to use version 10 of the postgres client!
