### ISSUE TITLE
QUERY_STRING is blank

### ISSUE THREAD

**Issue by davideprevosto** [lando/lando#1683]
Hi there, 

I am using your last version v3.0.0-rc.17 and I am notice my $_SERVER['QUERY_STRING] is empty.

Same web application, same codebase, same branch, same lando recipe: all my colleagues can view query string values (they runs another lando version: eg. 13).

May I ask anybody could check if with version v3.0.0-rc.17 she/he can get populated $_SERVER['QUERY_STRING]?

My best

**Comment by davideprevosto** [comment]
Hello @pirog,
did you close because it is not a bug?

**Comment by pirog** [comment]
@davideprevosto i closed it because it provides insufficient information. Follow the instructions that are provided when you open a bug ticket. We will care about an issue as much as it seems you do ;)

**Comment by davideprevosto** [comment]
Ok, gotcha. Disagree, but of course it's fine for me. I will retry with a new post, later.
Thank you.

**Comment by pirog** [comment]
Yeah you very well may disagree but if we can't easily replicate your problem or you don't minimally follow the pretty explicit instructions we lay out for bug reports then you should not expect a ton of help.

If you do follow those instructions and we *can* recreate your problem then we are happy to help.

**Comment by davideprevosto** [comment]
Complaining, it's the last thing I want. Maybe it's about my bad english.
You wrote:
"_We will care about an issue **as much as it seems you do** ;)_"
Well, I disagree with this. You can't desume what I care, and what I do not care ;-) No?

I have to be more detailed -> I will do it. I did understand the point.
