### ISSUE TITLE
Building with 'apt install jpegoptim optipng' does not make the them available

### ISSUE THREAD

**Issue by basepack** [lando/lando#1691]
**Setup**
v3.0.0-rc.17 on Windows 10 Pro

**.lando.yml**

```yml
name: laravelapp
recipe: laravel
config:
  webroot: public
  via: 'nginx'
  cache: 'redis'
  php: 7.3

services:
  appserver:
    type: php:7.3
    build_as_root:
      - apt update -y && apt install jpegoptim optipng pngquant gifsicle
```

When I run `lando build -y` I see that they are installed. Even when I do `lando ssh -s appserver`, I see that they are in fact installed:

```
www-data@c1bea3a22f33:/app$ jpegoptim
jpegoptim: file arguments missing
Try 'jpegoptim --help' for more information.
```

However in Laravel, by using the default setup of [spatie/laravel-image-optimizer](https://github.com/spatie/laravel-image-optimizer) I get these entries in the log file:
```
[2019-07-09 11:04:08] testing.INFO: Using optimizer: `Spatie\ImageOptimizer\Optimizers\Pngquant`  
[2019-07-09 11:04:08] testing.INFO: Executing `"pngquant" --force '/opt/project/storage/app/public/product/test.jpg' --output='/opt/project/storage/app/public/product/test.jpg'`  
[2019-07-09 11:04:08] testing.ERROR: Process errored with `sh: 1: pngquant: not found
`  
[2019-07-09 11:04:08] testing.INFO: Using optimizer: `Spatie\ImageOptimizer\Optimizers\Optipng`  
[2019-07-09 11:04:08] testing.INFO: Executing `"optipng" -i0 -o2 -quiet '/opt/project/storage/app/public/product/test.jpg'`  
[2019-07-09 11:04:08] testing.ERROR: Process errored with `sh: 1: optipng: not found
```

*Example:*

```bash
1. Start a new Laravel project
2. Install spatie/laravel-image-optimizer:  `composer require spatie/laravel-image-optimizer` 
3. Add:
services:
  appserver:
    type: php:7.3
    build_as_root:
      - apt update -y && apt install jpegoptim optipng pngquant gifsicle 
to your .lando.yml and run `lando rebuild -y`

3. Optimize an image:
use Spatie\LaravelImageOptimizer\Facades\ImageOptimizer;

ImageOptimizer::optimize( \Storage::disk( 'public' )->path( $pathToImage) );

4. Try to run it, and see it failing
``` 

What is going wrong here? Do I miss something very obvious? 

Thanks!

**Comment by pirog** [comment]
@basepack if you've `lando ssh -s appserver` and verified the packages install correctly then that more-or-less should confirm that lando has done its part. 

My best advice beyond that is to make sure you are configuring these tools correctly specifically make sure you are invoking the binaries correctly. It could be as simple as 

`"optipng" -i0 -o2 -quiet '/opt/project/storage/app/public/product/test.jpg'`
vs
`optipng -i0 -o2 -quiet '/opt/project/storage/app/public/product/test.jpg'
note the lack of quote wrapping of the binary in the second.

if you think that lando is somehow responsible for that please reopen with _clear_ steps to replicate. Eg as non-laravel expert its not clear to me how i do `4` or `5` in your list of steps
