### ISSUE TITLE
Upgrade from v3.0.0-beta.47 to v3.0.0-rc.17 does not create the domains

### ISSUE THREAD

**Issue by rageshchalil** [lando/lando#1693]
Lando version: v3.0.0-rc.17 on Mac
Docker version: 18.09.2, build 6247962

.lando.yml:
```yml
name: testinglando
recipe: lemp
config:
  webroot: .
```

Output after running: lando start

```cmd
Your app has started up correctly.
Here are some vitals:

 NAME                  testinglando                         
 LOCATION              /Users/User/Sites/testlando        
 SERVICES              appserver_nginx, appserver, database 
 APPSERVER_NGINX URLS  https://localhost:32817              
                       http://localhost:32818               
                       http://testinglando.lndo.site:8000   
                       https://testinglando.lndo.site   
```
![image](https://user-images.githubusercontent.com/8214107/61046869-15779c80-a3d6-11e9-9d78-57d5f1099ce9.png)

I upgraded lando from v3.0.0-beta.47 to v3.0.0-rc.17, did a lando rebuild on my an app, the local domains do not work eg: http://testinglando.lndo.site:8000 and  https://testinglando.lndo.site.

**Comment by rageshchalil** [comment]
Additional steps done are:
1. Uninstalled lando
2. delete ~/.lando
3. Uninstall Docker
4. Restarted the system
5. Installed docker
6. Installed lando
7. lando init [created a new lando lemp app ]
8. lando start

Result:
Still the same errors

**Comment by pirog** [comment]
@rageshchalil we havent changed how this works in a very long time so there isnt anything obvious that lando could be doing to cause this. fwiw i also havent seen anyone else report this and have a good amount of people upgraded to rc17+ at this point.

best advice would be to investigate any networking or router config that maybe be preventing this
