### ISSUE TITLE
Tooling does not respect redirected lando file and always uses .lando.yml

### ISSUE THREAD

**Issue by colin-campbell** [lando/lando#1702]
Lando version: v3.0.0-rc.18 on Ubuntu 18.04

Lando tooling does not respect a custom lando.yml set with the environment, but always reads .lando.yml.

Steps to reproduce:
1. create .lando-custom.yml.

```yaml
tooling:
  mytool:
    service: appserver
    description: "Run mytool commands"
    cmd: /usr/local/bin/mytool
```
2. Run lando with clean config and redirected landofile.
```bash
$ rm -rf  ~/.lando
$ export LANDO_LANDO_FILE=.lando-custom.yml
$ lando
Usage: lando <command> [args] [options]

Commands:
  lando config    Displays the lando configuration
  lando destroy   Destroys your app
  lando info      Prints info about your app
  lando init      Initializes code for use with lando
  lando list      Lists all running lando apps and containers
  lando logs      Displays logs for your app
  lando poweroff  Spins down all lando related containers
  lando rebuild   Rebuilds your app from scratch, preserving data
  lando restart   Restarts your app
  lando share     Shares your local site publicly
  lando ssh       Drops into a shell on a service, runs commands
  lando start     Starts your app
  lando stop      Stops your app
  lando version   Displays the lando version
```
3. Copy .lando-custom.yml to .lando.yml and run with clean config, leaving environment in place.
```bash
$ cp .lando-custom.yml .lando.yml
$ rm -rf ~/.lando
$ lando
Usage: lando <command> [args] [options]

Commands:
  lando config    Displays the lando configuration
  lando destroy   Destroys your app
  lando info      Prints info about your app
  lando init      Initializes code for use with lando
  lando list      Lists all running lando apps and containers
  lando logs      Displays logs for your app
#### "mytool" now available ###
  lando mytool    Run mytool commands  
  lando poweroff  Spins down all lando related containers
  lando rebuild   Rebuilds your app from scratch, preserving data
  lando restart   Restarts your app
  lando share     Shares your local site publicly
  lando ssh       Drops into a shell on a service, runs commands
  lando start     Starts your app
  lando stop      Stops your app
  lando version   Displays the lando version
```

We use different landofiles for testing/upgrading and approving different lando versions, and this is awkward.

**Comment by pirog** [comment]
@colin-campbell this is not what `LANDO_LANDO_FILE` is for so its not surprising this doesn't work the way you want. 

Check out the Landofile documentation which lets you use various base and override files to achieve things like this
https://docs.devwithlando.io/config/lando.html#landofile

**Comment by colin-campbell** [comment]
Ah ok. I was following this: https://docs.devwithlando.io/config/config.html#environment-variables and it works perfectly apart from tooling.
 How would you suggest supporting both pre and post-rc2 installations (necessary at the moment due to our mix of projects/developers) with pure landofiles?

**Comment by pirog** [comment]
I mean that feature just straight up doesn't exist pre-RC2 so sort of tricky to suggest a way to magically backport a feature to a legacy version.

That said, my best _advice_ is to take the time to upgrade everyone and your projects at the same time. It's going to be annoying up front but its going to save you lots of time and frustration in the long run.
