### ISSUE TITLE
Document File Permission Changes

### ISSUE THREAD

**Issue by gcalex5** [lando/lando#1711]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/tutorials/pantheon.html

**Describe the change you'd like**
When running Drupal 8 and Drupal 7 installs on Lando with the Pantheon recipe the files directory and settings.php files frequently are swapped to read-only. Should document this functionality as well as a method for preventing the behavior if desired.

**Comment by pirog** [comment]
@gcalex5 not exactly sure what you mean. Can you be more specific?

**Comment by gcalex5** [comment]
Sorry, used the wrong wording. Was referring to them having their file status/permissions changed to "read-only"(not "default"). I've updated the original post to reflect that.

This occurs seemingly randomly but potentially more frequently after a "lando drush" or "lando pull' command.
