### ISSUE TITLE
docker-credential-desktop not installed or not available in PATH, when running `lando init` the first time,

### ISSUE THREAD

**Issue by souhaiebtar** [lando/lando#1712]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

* lando version: v3.0.0-rc.18
* OS: macOS mojave 10.14.5
* docker: 2.0.0.3 (31259) ( the one included in the `lando-v3.0.0-rc.18.dmg` file from github)

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando init \
  --source remote \
  --remote-url https://github.com/bcit-ci/CodeIgniter/archive/3.1.10.tar.gz \
  --remote-options="--strip-components 1" \
  --recipe lamp \
  --webroot . \
  --name my-first-lamp-app
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

```
dockerpycreds.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
```

**Tell us generally about your bug**

i tried to use the default config from lando documentation, and i used the same step, but it didn't work

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?

i don't think so, because no info can be found on  the requested `docker-credential-desktop` resource/program 

**solution**

after searching, i found out that this error can be fixed by adding `"credsStore" : "osxkeychain"`
in `~/.docker/config.json` file which become:

```json
{
  "stackOrchestrator" : "swarm",
  "credsStore" : "osxkeychain"
}
```

but generally thanks for your effort and this great tool

**Comment by xinyoDeputy** [comment]
Thank you that solved my problem.

**Comment by souhaiebtar** [comment]
@xinyoDeputy  you are welcome,

**Comment by rempefelix** [comment]
I experienced the same issue after updating to Mojave and newest docker.  "brew install docker-credential-helper" solved the issue for me.

**Comment by tzaranek123** [comment]
in my case I had "credsStore":"desktop" twice, removed one of those and it things moved along after that
