### ISSUE TITLE
Add webp support for php-gd.

### ISSUE THREAD

**Issue by travis-bradbury** [lando/lando#1715]
**Please explain your request and its importance in the form of a user story.**

As a lando user who works with Drupal sites, I want the option to create webp images with php's gd extension.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

Add libwebp in the php images like libjpeg and libpng are and configure gd with `--with-webp-dir` the same as `--with-jpeg-dir` is currently used.[1][2]

[1] https://hub.docker.com/r/devwithlando/php
[2] https://www.php.net/manual/en/image.installation.php

**Describe alternatives you've considered**
I believe I can solve this by creating an image based on devwithlando/php but since webp is already well supported[1] I think it's fair to add directly to lando.

[1] https://en.wikipedia.org/wiki/WebP

**Additional context**
I'm trying to use https://www.drupal.org/project/webp, which requires webp support in ext-gd.

**Comment by travis-bradbury** [comment]
A work-around is to use lando's overrides support to swap out appserver's image.

```
FROM devwithlando/php:7.2-fpm-2

# Add webp support to php-gd. See https://github.com/lando/lando/issues/1715.
RUN apt-get update && apt-get install -y \
    libwebp-dev \
  && docker-php-ext-configure gd --with-freetype-dir=/usr --with-png-dir=/usr --with-jpeg-dir=/usr --with-webp-dir=/usr \
  && docker-php-ext-install gd \
  && apt-get -y clean \
  && apt-get -y autoclean \
  && apt-get -y autoremove \
  && rm -rf /var/lib/apt/lists/* && rm -rf && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*
```

The custom image has to be specified in the lando file: https://docs.devwithlando.io/config/services.html#overrides https://docs.devwithlando.io/config/services.html#using-dockerfiles

**Comment by mherchel** [comment]
+1 on this. Also Imagemagick support for webp. 

Note that DDEV does support this. See https://twitter.com/drud/status/1054196725123031040

**Comment by alex-moreno** [comment]
+1 for support on this, same reason, webp module in Drupal needs that desperately, so this is is a blocker of using lando or Acquia Dev Studio with webp.

**Comment by alex-moreno** [comment]
quick workaround as well, although probably better practice to do the fix from @travis-bradbury :

https://dev.acquia.com/blog/webp-and-drupal

`* lando ssh --user root
 
* apt-get install libwebp-dev \
&& docker-php-ext-configure gd --with-freetype-dir=/usr --with-png-dir=/usr --with-jpeg-dir=/usr --with-webp-dir=/usr \ && docker-php-ext-install gd
 
* lando restart`

**Comment by pirog** [comment]
Alright `webp` support will be in the next release, if you already have a lando site spun up you'll need to `lando rebuild` in order to get the updates images
