### ISSUE TITLE
A stand-alone installer excluding Docker?

### ISSUE THREAD

**Issue by jigarius** [lando/lando#1721]
Please complete the following steps.

* A month ago, I was choosing between Lando and some other tool.
* I saw that the Lando installer was pretty heavy at around 500MB for MacOS while the other tool was just 50MB or so.
  * I was scared to download / use Lando because if the installer weights 500MB, I thought the installation might weigh even more.
  * Apple charges a tonne of money for Mac laptops with more storage space, so many Mac users use 256MB / 512MB SSDs.
* This morning I found that the Lando installer is heavy mostly because it contains a Docker installation?
* I think that it'll be much better if Lando could just require a minimum version of Docker instead of trying to manage the Docker installation itself.
  * If that is not possible, then some note should be added to the readme to let potential users know why the Docker installation had to be included in the Lando installer.

Thanks for the awesome tool! Much love, Team Lando.

**Comment by pirog** [comment]
@jigarius obviously we should generally not be motivated by fear. Have courage!!!

So the current installers allow you to deselect the docker installation so we already have an installer that does that. That said i think adding some documentation about _why_ lando is so huge makes sense so 100% agreed there.

I'm going to add that to our docs and close this out.

**Comment by pirog** [comment]
@jigarius also note that you can always "install from source" if you want to avoid the package and the deps we ship!
