### ISSUE TITLE
lando-v3.0.0-rc.19.exe shipping with docker 2.0.0.3 instead of 2.1.0.0

### ISSUE THREAD

**Issue by mrweiner** [lando/lando#1728]
[Release notes for v3.0.0-rc.19](https://github.com/lando/lando/releases/tag/v3.0.0-rc.19) state "Updated to Docker Desktop 2.1.0.0 and docker-compose 1.24.1" but after installation the Docker version on my system is 2.0.0.3. I've tried fully uninstalling docker + lando and removing my Lando folder prior to installation but the issue persists.

EDIT: I've tried this all again and while 2.0.0.3 was still installed, Docker updater opened up afterward to upgrade the installation to 2.1.0.0. If this is expected behavior then this can probably be closed.

**Comment by AaronFeledy** [comment]
Are you on Windows? If so, see #1447

**Comment by AaronFeledy** [comment]
Actually, I just checked it out and the workaround above does not apply here. The exe package does appear to be shipping with 2.0.0.3.

**Comment by mrweiner** [comment]
@AaronFeledy yeah I tried that workaround out prior to posting. Makes sense that that wouldn't work if 2.0.0.3 is being shipped. Thanks for checking that out
