### ISSUE TITLE
Add a `lando info --format=human` option or `lando summary` command

### ISSUE THREAD

**Issue by hailwood** [lando/lando#1737]
Please complete the following steps.

**Please explain your request and its importance in the form of a user story.**

As a lando user who often uses the share feature for working with webhooks it would be useful to be able to quickly pull up the same info we get shown when we first start the app.

![image](https://user-images.githubusercontent.com/709773/62841130-aead1200-bcf8-11e9-9653-9573c6fb0062.png)

I understand we can run `lando info` and get a json dump but this is annoying to quickly scan.
It would be great if we could add a `human` option for formatting, or even a `lando summary` if we wanted a different command which would just output the startup banner.

**Comment by nylen** [comment]
+1 This would be nice. Also I wonder if `wontfix` is really the best label for stale issues?

**Comment by hailwood** [comment]
@nylen just as a quick update, I'm currently using this alias

```bash
lurls='lando info -p '\''0.urls'\'
```
Which looks like this
![image](https://user-images.githubusercontent.com/709773/64935048-b8e7a080-d8a2-11e9-9466-ff91ce893388.png)


Would definitely prefer the `lando summary` because the service names and that display are helpful.
But in the meantime I thought you might find this useful.

**Comment by acobster** [comment]
Would also love to see this. Scanning is annoying, especially now that output is not true JSON (keys are not quoted strings), so I can't pipe it into `jq` or another generic JSON parser.

**Comment by barraponto** [comment]
@acobster output is actually json if you pass `--format=json`.

**Comment by uberhacker** [comment]
@barraponto: That is true but the point is `--format=json` is not digestable for humans. :)

**Comment by hailwood** [comment]
unstale

**Comment by uberhacker** [comment]
I might add it would be nice to default to human readable and have an option such as `--format=json` to output in a form machines can easily understand.

**Comment by nylen** [comment]
:ok_hand:

**Comment by pirog** [comment]
Housekeeping: closing this out because its now in `master`
