### ISSUE TITLE
MySQL doesn't connect after lando restart (follow-up to #1718)

### ISSUE THREAD

**Issue by danepowell** [lando/lando#1739]
This is a follow-up to #1718 

That issue was partially fixed by the following commit in rc19: https://github.com/lando/lando/commit/63b09e40cbc0fdcf43aa9a59da7db0e926e91b50

However, that fix is incomplete and fails in some environments because the following file is not executable:
`~/.lando/config/mysql/mysql-flush.sh`

This results in the following warning during restarts, and a recurrence of the original symptoms from #1718: `find: '/scripts/mysql-flush.sh': Permission denied`

Simply making that file executable solves the issue. I'd be happy to submit a PR if you can point to where in Lando that file is getting created (it's executable in the Github repo, I don't know why it's not executable on disk)

This doesn't seem to be a problem for everyone so it could be specific to Linux or upgrading users.

**Comment by pirog** [comment]
@danepowell scripts that are put in that directory are made executable before they run
https://github.com/lando/lando/blob/master/plugins/lando-core/scripts/lando-entrypoint.sh#L18

So i'm guessing its not as straightforward as "just make the script executable"

**Comment by danepowell** [comment]
Perhaps I should have attached the full log: 
[out.txt](https://github.com/lando/lando/files/3498434/out.txt)

Here you can see that the chmod is failing:
> chmod: changing permissions of '/scripts/mysql-flush.sh': Operation not permitted

Indeed if I ssh into the container and run chmod manually, I get the same error. If I run it as root, it works fine, so maybe that script just needs to run as root?

Additionally, I've confirmed this happens on Linux but not Mac. On Mac you can freely chmod those scripts as www-data. This makes me wonder if Linux has anything in common with Windows in terms of the inability to chmod, as described here: https://github.com/lando/lando/blob/1bf336e927f16a97fb0dea79bc1fdf9d0409ebe0/plugins/lando-core/scripts/load-keys.sh#L25

**Comment by pirog** [comment]
@danepowell booted up elementary os and i can definitely see this now

**Comment by pirog** [comment]
also see why the test failed, we ran it against an older version of mysql that did not need the socket removal!

**Comment by danepowell** [comment]
Awesome, thanks for the quick fix!

**Comment by pirog** [comment]
Looks like this was finally fixed upstream so we can revert to our faster shutdown flow
https://github.com/bitnami/bitnami-docker-mysql/commit/a765f2f93ed493c8d784a48428e010e543e002af
