### ISSUE TITLE
MySQL doesn't connect after lando restart on Windows (follow-up to #1739)

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1755]
This is a follow-up to #1739

*v3.0.0-rc.20 on Windows 10 Professional + Docker 2.1.0.1*

Unfortunately the socket fix `mysql-flush.sh` is not mounted into my database container and so the restart issue remains on windows. If I do the following:
```bash
lando ssh -s database -u root
ls -la /scripts
````
then there is no `mysql-flush.sh` listed. On startup there is no error shown for incorrect volume mounting or similar. But the script is available in my home config folder!
Also lando destroy && lando rebuild won't change the mounted volumes.

Here's the output of `docker inspect -f '{{ .Mounts }}' <containerId>` - perhaps it will help:
```bash
[{volume testapp_home_database /var/lib/docker/volumes/testapp_home_database/_data /var/www local rw true } 
{volume testapp_data_database /var/lib/docker/volumes/testapp_data_database/_data /bitnami/mysql/data local rw true }
{bind  /host_mnt/d/htdocs/testapp/.lando/mysql/my.cnf /opt/bitnami/mysql/conf/my_custom.cnf  rw true rprivate} 
{bind  /host_mnt/c/Users/<user>/.lando/scripts /helpers  rw true rprivate} 
{bind  /host_mnt/c/Users/<user> /user  delegated true rprivate} 
{bind  /host_mnt/c/Users/<user>/.lando/scripts/lando-entrypoint.sh /lando-entrypoint.sh  rw true rprivate} 
{bind  /host_mnt/c/Users/<user>/.lando /lando  delegated true rprivate}
{bind  /host_mnt/c/Users/<user>/.lando/scripts/load-keys.sh /scripts/load-keys.sh  rw true rprivate} 
{bind  /host_mnt/d/htdocs/testapp /app  delegated true rprivate}]
```

As workaround I added an custom tooling to my .lando.yml:
```yaml
tooling:
  mysql-flush:
    service: database
    user: root
    description: Flush mysql.sock
    cmd: "rm -rf /opt/bitnami/mysql/tmp/mysql.sock*"
````
so I can run `lando mysql-flush` and afterwards `lando restart` to get the database running.

**Comment by rabauss** [comment]
I can report that the socket-file is only a problem if the container was not stopped correctly on the last boot. But the workaround script `mysql-flush.sh` is not mounted yet on windows!

**Comment by eelkeblok** [comment]
Looks like this might also be a problem on MacOS.

**Comment by nacr** [comment]
I can confirm the problem exists in MacOS

**Comment by Canidl** [comment]
Looks like this might also be a problem on GNU/Linux too.
