### ISSUE TITLE
lando drush "Could not find a Drupal settings.php file at sites/default/settings.php"

### ISSUE THREAD

**Issue by eriksays** [lando/lando#1757]
running latest version of lando:
lando version
v3.0.0-rc.20

my process to recreate
create empty directory
cd into directory
lando init (go through steps to pull from pantheon)
lando start
lando pull ( to get database and assets)

lando drush pm-updatestatus
Command pm-updatestatus needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.

**Comment by Taiger** [comment]
Same issue. My settings file has vanished.

**Comment by nco71** [comment]
I had some issues and solved it by copying /sites/defauldefault.settings.php to settings.php 
I added the database settings inside the /sites/default./setttings.php using lando info
