### ISSUE TITLE
Have to run `lando rebuild` on every PHP change

### ISSUE THREAD

**Issue by musicaljoeker** [lando/lando#1761]
**Tell us about your setup**

What is your lando version and operating system?  v3.0.0-rc.20 on macOS 10.14.6*

**Tell us about your `.lando.yml`**

```yml
name: wordpress-test-site
recipe: wordpress
config:
  webroot: wordpress
```

I'm building a pretty standard plugin in the `/wp-content/plugins/` directory using Lando.

My problem is every time I make a modification to a PHP file, I have to run a `lando rebuild` before I see the change propagate to my web browser. I have _made sure_ that I'm saving the files and everything (even rubber duckied this with other co-workers) and we are all scratching our heads on this one. It's adding many extra minutes to my dev work.

I have SSH'd into the lando docker container to peek at the files docker sees, and strangely enough the updated files are in docker yet still not showing up in the application. I have also completely uninstalled docker and lando and reinstalled and the problem persists.

**Comment by delzhand** [comment]
Are you by any chance running multiple sites? I'm working through a similar issue on OSX 10.14.6. When I ran `lando list` I saw I had two sites. I ran `lando poweroff` to disable everything, then started the site I was have the issue with. Files started updating when edited after that.

**Comment by musicaljoeker** [comment]
Interesting @delzhand, thanks for that comment. I don't _remember_ running two sites when I had this problem (it seems to happen rather sporadically for me), but the next time I encounter this issue I will check to make sure I don't have two sites running.

**Comment by musicaljoeker** [comment]
@philltran I am not.

**Comment by claytron5000** [comment]
Any chance you've recently updated or restored from backup? We're discussing a similar issue when a coworker moved computers from a backup.

**Comment by gayathrics** [comment]
I am facing this issue. I have updated lando to latest, restarted docker, lando poweroff and rebuild. None of my php changes take effect until lando rebuild.

**Comment by paupenin** [comment]
This is still happening, can't work with lando because of this.
Happens both in LAMP and Wordpress projects on Windows

**Comment by philoSurfer** [comment]
I want to make sure that people having this issue understand the following:

If you have any `exclude:` declarations in your `.lando.yml` file (aka Turbo mode), the folder paths listed after a Lando rebuild, will not see changes as they have been cloned into the container for performance and will no longer be a network mounted folder to your local machine.  Any changes to those folders in `exclude` would require a `lando rebuild`   

If you are still having an issue, I recommend backing up your database and then closing Docker.
Then destroy the `~/.lando` folder (macOS) and then do a Lando start and then import your db. 

I have seen instances where the containers go to shit and act weird and the only thing that fixes them is destroying them and their cache altogether.  

WARNING NOTE:  destroying `~/.lando` folder will blow up ALL Lando containers

**Comment by nolafs** [comment]
Got the same issue with latest version. This used to work, with an identical .lando.yml few month back for another project using Bedrock.

**Comment by gatsby0121** [comment]
I'm getting this as well.  I even rebuilt my container, nothing seems to work.  Destroying and recreating caused my missing file to appear, but any changes after that are not being reflected.

ssh-ing into the server and checking the time stamp on the changed file also shows it hasn't changed.

**Comment by eleftrik** [comment]
Same problem here. 

In my case it's a Laravel project with nginx and PHP 7.4. Everything goes right, but suddenly an endpoint of my application starts to return the same fixed content, it doesn't matter what I'm updating in my .php file.

I tried
- lando restart
- lando rebuild -y

After a "reboot" the problem seems to be solved, but then it appears again.
Has this issue something to deal with OPCache? 

Can we please reopen this issue?
Thanks

**Comment by paupenin** [comment]
Hello everyone!

After some checking I figured out how to solve it on different computers.

**Each version of Lando has a matching Docker Desktop version** and sometimes Docker updates much sooner than Lando causing all kind of problems like this one.

Go to Lando releases on Github and check which Docker Desktop version is supported and install that specific one from https://docs.docker.com/docker-for-windows/release-notes/.

For example on Lando v3.0.0-rrc.3 change log says: Updated to Docker Desktop 2.2.0.5

I hope this helps someone!

**Comment by eleftrik** [comment]
@paupenin 

> For example on Lando v3.0.0-rrc.3 change log says: Updated to Docker Desktop 2.2.0.5
> 
> I hope this helps someone!

I'm running Lando v3.0.0-rrc.4 with Docker Desktop 2.2.0.5 (on MacOS)

**Comment by RobDana** [comment]
I'm having the same problem. Was running Lando v3.0.0-rrc.2. Multiple projects, all Laravel. No changes to the .lando files in months. Upgraded to Lando v3.0.0-rrc5 and the problem persists. It's a complete dealbreaker, unable to work. I've been using Lando for most of a year and now need to figure out another option

**Comment by RistoNiinemets** [comment]
Yep, same here.

**Comment by web-assistant** [comment]
I've been using Lando for a month now, been through the various new versions (including a few Docker updated versions) and I seem to get this issue randomly. Usually a Windows restart gets things back to normal but it's quite frustrating, especially when Lando takes a while to start each time.

I'm wondering if it has to do with xdebug? Might be a coincidence but I think it's happened when using `xdebug_break();`

**Comment by RistoNiinemets** [comment]
I haven't used xdebug, so might not be the issue.
For me, usually it breaks when a PHP error occours.

**Comment by nolafs** [comment]
Just updated to the latest version and seems is has getting worst. Previous version, at least I could work for few hours till it would break. Now it is pretty consistent. It pretty useless tool for development now.

**Comment by serundeputy** [comment]
As mentioned by people in the above comments a few things could be amiss here including lando/docker version mismatches.

One thing I did not see mentioned yet in this thread is the disk space allotted to docker.  If you are close to running out or over the allotment things go awry.  You can in this case:

* allot more disk space to docker 
* clean up unused docker images, volumes, containters, and networks
  * `docker system prune` does a good job of this (i think you need to pass a separate flag for volumes)

Anywho that is worth a try if you know you have the right versions of lando/docker.

**Comment by web-assistant** [comment]
I have the correct version of docker for lando. I increased disk space and used `docker system prune` and I'm still getting the issue. As @nolafs above, seems like the issue has got a lot worse with the new versions (currently using v3.0.2). Unfortunately Lando is become usable for me now as I'm not getting much work done with the constant need to restart 😭

**Comment by RistoNiinemets** [comment]
Also latest versions and Lando installed the docker also.
I've noticed that it does not have to be a error that causes it. Sometimes just changes in PHP. And if I wait for a minute or more, it will eventually change...

**Comment by GiuB** [comment]
Same here :(

**Comment by heidimark** [comment]
I am experiencing this same issue as well. I've run into it before and somehow it got cleared up. Definitely running the newest version of Lando. No excludes in my yml file. Lando will not pick up any code updates to PHP files unless I run lando restart (or rebuild).

**Comment by brianjohnhanna** [comment]
Still having this problem today. I did find that the advice recommended [in this StackOverflow post](https://stackoverflow.com/a/58678227/2611917) helped me immensely. Do not understand why though.

Add this to your composer.json (assuming it's a composer-based project) and run `composer install`

```php
"config": {
    "optimize-autoloader": true
},
```

**Comment by thetwopct** [comment]
My composer.json already has the `"optimize-autoloader": true` line in it but the problem still remains. Happens multiple times per day, quite frustrating as it makes you question your own code first ("Why isn't this working?!") and then realisation ("FFS Lando"). Seems to affect PHP **and** CSS files, any changes seem to be cached somehow and never updated in the browser regardless of cache, refresh and browser.

Could we re-open this issue to get some visibility on it?

**Comment by thetwopct** [comment]
Got some good input for this issue on the Lando Slack and some potential causes:

- a common issue where the Docker VM runs out of storage space (Docker > Preferences -> Resources -> Advanced and check disk image size)
- another issue seems to crop up when there are just TONS of files in the application, causing the file-system in Docker to choke

In my case I had 12GB of uploads in a recent WordPress site. I cleaned those out ([a cool plugin to pull in the images from remote)](https://github.com/agencychief/remote-media-resolver), and also ran `docker system prune` and the problem seems to be solved 👍

**Comment by xtfer** [comment]
All the Laravel devs where I work have this issue. Seems to be pretty prevalent.

**Comment by ptcampbell** [comment]
Sorry for the "me too" — but it doesn't hurt to have another data point. I'm facing the same trouble. It doesn't seem to be disk space or memory related.

**Comment by Scoottykun** [comment]
Same issue here :/ It's pretty annoying as it happen in very random cases (mostly when debugging errors in my case).

**Comment by folofse** [comment]
I solved it by adding this to .lando.yml. and the runned `lando rebuild`.  I use the Wordpress recipe which uses appserver, not sure if some other recipe uses some other service name.

`services:
  appserver:
    app_mount: default`

**Comment by syzygy333** [comment]
Just want to avoid this thread getting closed from inactivity. This started happening to me recently. I have to destroy and rebuild for Composer to function properly (it's not updating the lock file as it should). My Docker version is the correct one for the Lando version I'm using and I'm not even close to out of space in Docker. I'm not running multiple sites and I don't have any exclude declarations. The `optimize-autoloader` fix also doesn't do anything for me. I'm not using the most up-to-date Composer because some of my required packages haven't been updated to support it.

**Comment by mm-xp** [comment]
I struggled with this one too. I'm using platformsh as a recipe. What ended up working for me was mentioned by @folofse. I used an override setting to specify the mount point.

```
...
recipe: platformsh 
config:
  ...
  overrides:
    webroot: public
```

**Comment by skaltenegger** [comment]
I'm still experiencing this issue randomly, again the very moment I'm writing this post. 
When I do a `lando ssh` I do not see the file being updated inside the container. 

What can I do to avoid this? Any hint/help is very much appreciated.

Thanks,
Stefan

**Comment by rtvenge** [comment]
@skaltenegger restarting docker desktop usually works for me.

**Comment by skaltenegger** [comment]
Thanks @rtvenge - that does seem to work for me as well. 
Do you have any idea what could be the root cause for this? This definitely slows me down quite a lot since it happens quite often...

**Comment by rtvenge** [comment]
@skaltenegger heh, I do not know the underlying issue. It's pretty rare for me, so the restart isn't such a pain. 

I do have my resources cranked up on Docker, though. Just a hunch, but it could be a resource issue? Docker can be a hog sometimes. I think I got that hunch from [@serundeputy's comment](https://github.com/lando/lando/issues/1761#issuecomment-629273070).

Here is what I have:

<img width="1362" alt="Screen Shot 2021-04-01 at 1 24 56 PM" src="https://user-images.githubusercontent.com/303836/113349976-acdcfb80-92ed-11eb-976a-83dfe8cf166e.png">

**Comment by skaltenegger** [comment]
Thanks @rtvenge - I will apply these changes and keep you posted if the crashes get less on my end. 👍 👍

**Comment by RistoNiinemets** [comment]
Never had the issue again after migrating to WSL2 on Windows.
