### ISSUE TITLE
Add configure option to set a max size for lando logs

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1774]
Over time, the logs in a container can potentially use up a lot of disk space.  It would be a nice feature to be able to configure the max size a log file can use inside a service container.

**Comment by pirog** [comment]
👍

**Comment by osopolar** [comment]
See also #1790

**Comment by uberhacker** [comment]
No @probot, you are not marking this stale after only 30 days!

**Comment by uberhacker** [comment]
No @probot!

**Comment by uberhacker** [comment]
Unstale

**Comment by uberhacker** [comment]
Unstale.

**Comment by pirog** [comment]
Alright, sane limits have been set for logs, they can be changed per-service in the usual way with service level overrides. 

Will be in the next release

**Comment by JosielFaleiros** [comment]
How can I set the max size for lando logs?

**Comment by ryanbrownell** [comment]
Adding this here for future me/others to find when I need it.

An example of the override for logs can be found here: https://github.com/lando/lando/blob/fa2a1578d969daf267d19fcc944a642efe7a6557/examples/mysql/.lando.yml#L16
