### ISSUE TITLE
Add option to truncate logs

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1775]
Something like `lando logs -s appserver --truncate`.

**Comment by uberhacker** [comment]
No @probot, you are not marking this stale after only 30 days!

**Comment by uberhacker** [comment]
No @probot!

**Comment by wss-chadical** [comment]
Bad @probot ty

**Comment by wss-chadical** [comment]
[https://www.youtube.com/watch?v=GM2T7-annUI](south park bad kitty)

**Comment by uberhacker** [comment]
Shut up @stalebot. :)

**Comment by uberhacker** [comment]
Unstale

**Comment by uberhacker** [comment]
Unstale.

**Comment by pirog** [comment]
closing this in favor of #1774
