### ISSUE TITLE
Offline flag

### ISSUE THREAD

**Issue by edurenye** [lando/lando#1776]
Would be nice to be able to do a rebuild even when you are offline, maybe we could add a flag, like 'lando rebuild --offline' that then skips checking docker containers and skips running composer, and also maybe we could state in the lando file custom things to run just when is offline and some others when is online.
It's just an idea of how to improve the current situation, but for sure might be there a better approach.

**Comment by edurenye** [comment]
This is important if you work remote, and want to develop without Internet connection.

**Comment by martin-klima** [comment]
I think the goal is very similar to #1565

**Comment by edurenye** [comment]
This issue it's not just about pulling images, as I said composer and other things might be a problem too, this is about having a flag that allows 2 different start one for on for online and other for offline.

**Comment by edurenye** [comment]
Also inside the lando.yml file there should be as there is 'run' or 'run_as_root' a 'run_offline' for example.

**Comment by gitressa** [comment]
I agree @edurenye. It's pretty complicated to get offline mode to work, so being able to start Lando without internet access with something like `lando start --offline` would be fantastic.
