### ISSUE TITLE
npm run dev error since Laravel upgrade to 6.0

### ISSUE THREAD

**Issue by robertgarrigos** [lando/lando#1777]
Since Laravel has been updated to 6.0 I cannot run npm for sass and js compiling. I'm having this error:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

I believe this is because of the node version shipped with lando. I'm running node 11.4 (latest with lando) and npm 6.11.3 (latest) within lando and got that error.

However, I tried on the same files by running plain node (node 12.9.1 and npm 6.11.3) and got no error.

**Comment by pirog** [comment]
@robertgarrigos i dont think this is a bug. sounds like maybe you want to make a feature request for us to add node 12 support?
