### ISSUE TITLE
Lando Docs Site is Down

### ISSUE THREAD

**Issue by phatsk** [lando/lando#1778]
I honestly don't know how to file this, so this is my best guess.

http://docs.devwithlando.io/started.html returns 404s after redirecting to https://docs.lando.dev/started.html

**Comment by pirog** [comment]
im not able to replicate this

```bash
curl -IL http://docs.devwithlando.io/started.html                                                            ✔  10752  12:02:42
HTTP/1.1 301 Moved Permanently
Date: Fri, 06 Sep 2019 04:17:44 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Fri, 06 Sep 2019 05:17:44 GMT
Location: https://docs.devwithlando.io/started.html
Server: cloudflare
CF-RAY: 511da28e9c5764af-FRA

HTTP/2 301
date: Fri, 06 Sep 2019 04:17:46 GMT
content-type: text/html
set-cookie: __cfduid=d7f3712ebe47b8d06a092a50723d6d8d11567743465; expires=Sat, 05-Sep-20 04:17:45 GMT; path=/; domain=.devwithlando.io; HttpOnly; Secure
location: http://docs.lando.dev/started.html
strict-transport-security: max-age=0
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cluster: iaimrn624qfk6-master-7rqtwti
x-platform-router: iaimrn624qfk6-master-7rqtwti--router
x-request-id: ovp2sysndjwk3rgc7cskjdeo
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 511da2953ffd96e6-FRA

HTTP/1.1 301 Moved Permanently
Date: Fri, 06 Sep 2019 04:17:46 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Fri, 06 Sep 2019 05:17:46 GMT
Location: https://docs.lando.dev/started.html
Server: cloudflare
CF-RAY: 511da29a7fa9c2d6-FRA

HTTP/2 301
date: Fri, 06 Sep 2019 04:17:47 GMT
cache-control: max-age=3600
expires: Fri, 06 Sep 2019 05:17:47 GMT
location: https://docs.lando.dev/basics/
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 511da2a09bb6c2c2-FRA

HTTP/2 200
date: Fri, 06 Sep 2019 04:17:48 GMT
content-type: text/html
set-cookie: __cfduid=dfd56bdcfbaeeb3dcfe760789b30f78751567743467; expires=Sat, 05-Sep-20 04:17:47 GMT; path=/; domain=.lando.dev; HttpOnly; Secure
cache-control: max-age=300
expires: Fri, 06 Sep 2019 04:22:47 GMT
last-modified: Thu, 05 Sep 2019 10:41:08 GMT
strict-transport-security: max-age=0
vary: Accept-Encoding
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cache: MISS
x-platform-cluster: iaimrn624qfk6-master-7rqtwti
x-platform-processor: iaimrn624qfk6-master-7rqtwti--docs
x-platform-router: iaimrn624qfk6-master-7rqtwti--router
x-request-id: cynwntmkildvcixbahmthtt7
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 511da2a22e88c2c2-FRA
```

**Comment by JMStewart00** [comment]
@pirog I've been seeing similar problems the last few days while trying to access the site. Here's what I get trying to visit the site from Chrome.

> docs.lando.dev normally uses encryption to protect your information. When Google Chrome tried to connect to docs.lando.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be docs.lando.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
> 
> You cannot visit docs.lando.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by matiasfh** [comment]
I have the same problem now.

**Comment by startinggravity** [comment]
I am having this problem too, regardless of browser.

`curl -IL http://docs.devwithlando.io/started.html
HTTP/1.1 301 Moved Permanently
Date: Fri, 29 Nov 2019 17:06:14 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Fri, 29 Nov 2019 18:06:14 GMT
Location: https://docs.devwithlando.io/started.html
Server: cloudflare
CF-RAY: 53d62bc83e6e5e0e-BNA

HTTP/2 301
date: Fri, 29 Nov 2019 17:06:14 GMT
content-type: text/html
set-cookie: __cfduid=d3d357f090f6c776185020be25b9669c71575047174; expires=Sun, 29-Dec-19 17:06:14 GMT; path=/; domain=.devwithlando.io; HttpOnly; Secure
location: http://docs.lando.dev/started.html
strict-transport-security: max-age=0
x-debug-info: eyJyZXRyaWVzIjowfQ==
x-platform-cluster: iaimrn624qfk6-master-7rqtwti
x-platform-router: iaimrn624qfk6-master-7rqtwti--router
x-request-id: gmxt5sdwvtl4xxvghwnhrsyz
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 53d62bc8ec975dfc-BNA

HTTP/1.1 404 Not Found
Date: Fri, 29 Nov 2019 17:06:14 GMT
Server: Apache/2.4.41 (Unix)
Content-Type: text/html; charset=iso-8859-1`

**Comment by a-barbieri** [comment]
Hey guys, anyone knows how to get around this issue?

**Comment by a-barbieri** [comment]
@pirog I don't know how you can replicate that, but on Chrome and Safari desktop I get:

> unknown app

<img width="375" alt="Schermata 2020-02-11 alle 12 17 39" src="https://user-images.githubusercontent.com/1528468/74232351-e6f1d500-4cc8-11ea-8691-f2a41c2f198b.png">

On Firefox desktop I have @JMStewart00 problem with HSTS.

The weird thing is that on another Mac I can see the website. Same on my iPhone, all  good.I cannot understand.
