### ISSUE TITLE
Add laravel 6 support

### ISSUE THREAD

**Issue by robertgarrigos** [lando/lando#1782]
As described here (https://github.com/lando/lando/issues/1777), node would need to be updated to 12 in order to have full support for laravel 6. It would be nice :-)

**Comment by robertgarrigos** [comment]
:-(

**Comment by brunolorente** [comment]
Still happening to me from Laravel 5.8.

`curl -sL https://deb.nodesource.com/setup_12.x | bash -`
`apt-get install -y nodejs`

In web root:
`npm install`

Returns:
`Build failed with error code: 1`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`


Some news about this issue @pirog? @robertgarrigos?

Thanks!
