### ISSUE TITLE
Last devilwithlando/php:7.1-apache-2 image does not display xdebug on PhpStorm

### ISSUE THREAD

**Issue by marceldobrica** [lando/lando#1783]
**Tell us about your setup**
*Lando v3.0.0-rc.20 on Ubuntu 18.04.3 LTS, 16GB, PhpStorm 2019.2.1 - build #PS-192.6262.66*

**Tell us about your `.lando.yml`**
```yml
name: drupalcore
recipe: drupal8
config:
  webroot: .
  php: '7.1'
  database: mariadb
  xdebug: true
```

**Tell us about the command you were running**
Old image - devwithlando/php:7.1-apache - Debugger is visible for PhpStorm
![image](https://user-images.githubusercontent.com/3274512/64672383-05cb1180-d474-11e9-8de3-13202754bd83.png)

New image - devwithlando/php:7.1-apache-2 - Debugger is no longer visible for PhpStorm
![image](https://user-images.githubusercontent.com/3274512/64672451-37dc7380-d474-11e9-9991-62d2f6ed58c4.png)

Xdebug is present in phpinfo() and I'm able to debug my code, BUT because PhpStorm don't see any debuger present on CLI interpreter is no more able to debug phpunit tests

**Tell us more**

I'm using Lando since V.3.0.-rc2, for drupal development, on Ubuntu 18 and I'm still struggling to find a solution to debug drupal tests on phpstorm: unit, kernel, functional, functionaljavascript, behat... phpunit works ok until devwithlando/php:7.1-apache-2 (rest of them are also possible but with some complications)

**Comment by Quevin** [comment]
This may help @marceldobrica 
* https://untoldhq.com/blog/2019/08/02/when-lando-phpstorm-and-xdebug-setup-gets-hairy

**Comment by marceldobrica** [comment]
@Quevin 
Thank you Quevin,
Was a nice reading and it point me to solve the problem. Maybe documentation should mention we have to write on debugger extension.
Have you ever tried to debug drupal tests using lando and PhpStorm? especially FunctionalJavascript and Behat ? I'm starting tests from console and intercept breakpoints in phpstorm using PHP_IDE_CONFIG: "serverName=appserver".... but is far away as nice as in classical LAMP stack where it seams PhpStorm controls everything...

**Comment by Quevin** [comment]
Welcome, @marceldobrica -- It's great when it works! 
Now just hoping to learn more about speeding it all up or waiting for that in the next RC.
Looking at a few issues here about using rsync like I read about with docker-rsync but don't yet understand and turning off/on xdebug w/o rebuild.

This is my speedy friend: `lando rebuild -s appserver`
