### ISSUE TITLE
Allow PHP recipes to detect PHP version from composer.json

### ISSUE THREAD

**Issue by mparker17** [lando/lando#1784]
# Problem / motivation

## User story

> In order for composer to run consistently in development and on my continuous integration server (which does not use Lando),
> As a devops maintaining both a Landofile and a `composer.json`
> I want Lando to be able to read the php version specified in `composer.json`

## Background

Composer uses the version of PHP that it is being run with, plus the versions of the currently-loaded PHP extensions and libraries when determining which packages to install. _This happens even if you have not specified any [platform package requirements](https://getcomposer.org/doc/01-basic-usage.md#platform-packages) in `require` or `require-dev`._ (note you can see the current version of PHP and the versions of the extensions it is using with `composer show --platform`)

If your development environment is running a different version of PHP than your CI runner, for example, you can have a `composer update` run correctly on your local machine, but fail on the CI runner. 

This can be mitigated by remembering to update both your Landofile, and your CI configuration file (`.travis.yml`, `.circleci/config.yml`, `.gitlab-ci.yml`) at the same time. However, "remembering to do" something is prone to human error.

However, it is possible to tell Composer to ignore the environment it is running on, and prepare packages for a specific environment by using the [`platform` configuration option](https://getcomposer.org/doc/06-config.md#platform) "to emulate a production env or define your target platform". This would allow the site to at least build on a simple CI step/environment (tests might still fail, but at least you have something to work with).

## Feature request

As of Lando v3.0.0-rc.20, there does not appear to be a [documented] way to tell Lando to look at `composer.json` -> `config` -> `platform` -> `php` for the PHP version. I request a way to do this.

# Proposed resolution

Allow specifying the PHP version as a path to a `composer.json` file. Lando reads `composer.json`, and determines the PHP string from the `config.platform.php` property.

Example `.lando.yml`:
```
name: bespin
recipe: drupal8
config:
  webroot: docroot
  php: 'docroot/composer.json'
```

Example `composer.json`:

```
{
    "name": "example/bespin",
    "config": {
        "platform": {
            "php": "7.3"
        }
    }
}
```

Note that values like `7.3` and `7.3.8` are both valid ways to specify the php version in `composer.json`'s `config.platform.php`. 

Note also that, as near as I can tell, [wildcards/version-constraints](https://getcomposer.org/doc/articles/versions.md) (e.g.: `^7.3`, `~7.3.8`, `7.3.*`) are NOT permitted in `config.platform.php` - or at least, I get an error from composer 1.9.0 when I try to use them. (wildcards/constraints _are_ permitted in [platform package requirements](https://getcomposer.org/doc/01-basic-usage.md#platform-packages); but Lando shouldn't care about those).

## Alternatives considered

The only alternative I've considered thus far is "manually keep `composer.json`, `.lando.yml` and `.travis.yml` in sync with changes to the version of PHP running on production"

**Comment by osopolar** [comment]
Maybe you can use [Events](https://docs.lando.dev/config/events.html) to call your own script to compare the versions and print an error on version mismatch.
