### ISSUE TITLE
`lando info` should only colorize its output when printing to a terminal

### ISSUE THREAD

**Issue by nylen** [lando/lando#1789]
Steps to reproduce:

- Run `lando info` and note colorized output - ok, this is good.
- Run `lando info | cat` and note colorized output - this is not good. Scripts should be able to parse this output ~as JSON~ without ANSI escape sequences involved.

For now I am using `lando info --format=json` for my scripts, but this is not really the right way to handle colorized output.  Instead, `lando` should detect whether its stdout is a TTY or not, and only colorize output if it is.  This is standard for every Unix tool that colorizes output, for example `git` and `ls` and `grep`.  Here's how to do this check in Node.js: https://stackoverflow.com/a/20585886

This worked as expected in 3.0.0-rc1 (the last version I used). I'm currently running 3.0.0-rc20.

**Comment by acobster** [comment]
Agree 100%. The way it works now is not UNIX-y!

However, even without the control characters for terminal colors, what `lando info` currently outputs (as of rc.22) is not true JSON, since it doesn't use quoted strings for keys and values are single-quoted.

**Comment by nylen** [comment]
`lando info --format=json` is valid JSON.

**Comment by philoSurfer** [comment]
For us jq lovers...  

The above --format=json switch does the trick ;) 

eg.   to get the external dB port for things you should not be doing. ;) 
`lando info --format=json | jq -r '.[] | {service, external_connection} | select(.service == "database").external_connection.port'`

**Comment by philoSurfer** [comment]
This ticket should be closed :)

**Comment by acobster** [comment]
@philoSurfer I disagree: although I find the `jq` workaround completely acceptable (thanks for the one-liner btw! def gonna use that for evil 😈), this issue runs deeper than that. :) As @nylen pointed out in their original description of the issue:

> `lando` should detect whether its stdout is a TTY or not, and only colorize output if it is. This is standard for every Unix tool that colorizes output, for example `git` and `ls` and `grep`.

So it's not just a cosmetic issue (which we can solve for piping to tools like `jq` using `--format=json`), but an issue of composability with other Unix-style tools. Strict JSON formatting aside, I think there's a perfectly reasonable expectation here for a CLI tool to follow the Unix conventions for use-cases where it's interacting with other tools.

**Comment by nylen** [comment]
> note colorized output - this is not good. Scripts should be able to parse this output as JSON.

So, `lando info` without `--format=json` is not strict JSON - this does not invalidate this issue.

Another reason to only colorize output when stdout is a terminal is that such things often end up in various log files. You don't want the ANSI escape sequences cluttering them up in that case.

**Comment by pirog** [comment]
Good call @nylen!

I think we sort of assumed `node` itself had smart handling around ANSI and `isTTY`. Consider that assumption invalidated.

Good news is this should be pretty easy to wire up to get better behavior

**Comment by nylen** [comment]
:ok_hand:

**Comment by nylen** [comment]
> I think we sort of assumed `node` itself had smart handling around ANSI and `isTTY`. Consider that assumption invalidated.

For most of the standard functions like `console.log` it does. However if you ask for colors with `util.inspect(..., {colors: true})` then I guess you'll get colors no matter what.

It looks like this issue was fixed in c5b3a2e?

**Comment by pirog** [comment]
yup this should be gtg now, closing
