### ISSUE TITLE
Clear logs / Enable log rotation

### ISSUE THREAD

**Issue by davilera** [lando/lando#1790]
I'm currently using Lando for my WordPress projects. The problem is, Apache's log is getting bigger and bigger, and `tail`ing it to review what's going on with my plugins is complicated.

I don't know how to properly clear logs or if it's possible to enable log rotation. If it is, I'd appreciate if someone could point me in the right direction. If it isn't, I think it'd be a good idea to have a command to achieve precisely that.

Right now, I'm using a combination of `lando info` to retrieve the `LogPath` of the Docker container and then I `sudo` overwrite it. Unfortunately, I can't help but feel this is a poor hack.

**Comment by osopolar** [comment]
Maybe you can improve your workaround by defining a [tooling](https://docs.lando.dev/config/tooling.html#usage) command.

**Comment by davilera** [comment]
Thanks @osopolar. Unfortunately, I don't know how to use this feature. As far as I can tell, a tooling is a command that runs inside one of the services managed by Lando, right?

If that's the case, then I don't know how it can help me, as the log file I retrieve with `lando info` is stored in the host. I think this has something to do with how Docker manages logs, but I'm too inexperienced to find a correct solution :-(

**Comment by osopolar** [comment]
@davilera you are right, tooling is to run commands inside the container. I incorrectly assumed, that the logs are inside the container (/var/log/) but that's not the case for logs in /var/log/apache2 as they are redirected to `stdout` or `stderr` to be displayed by `lando logs`, which is a light wrapper around docker logs (https://docs.lando.dev/basics/logs.html#logs).

In my project `lando info` does not show the  `LogPath` and I did not investigate further, but maybe documentation on how to [Logrotate for Docker container](https://sandro-keil.de/blog/logrotate-for-docker-container/) or [How to setup log rotation for a Docker container](https://www.freecodecamp.org/news/how-to-setup-log-rotation-for-a-docker-container-a508093912b2/) could help you.

**Comment by davilera** [comment]
I look at the references and see if I can come up with a better solution, unless somebody else has one and shares it with us ;-)

> In my project `lando info` does not show the `LogPath`

Yup, that's right. You have to use `lando info --deep`.

**Comment by mlbrgl** [comment]
As a workaround, `lando rebuild` does the job.

**Comment by pirog** [comment]
closing this in favor of #1774
