### ISSUE TITLE
db-import doesn't work with subdirectories anymore

### ISSUE THREAD

**Issue by ccjjmartin** [lando/lando#1815]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-rc.21 on Linux Mint 19.1*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: acquiasite
recipe: drupal8
config:
  webroot: ./docroot
  drush: 9
  php: '7.2'
  via: apache:2.4

tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/docroot --uri=https://acquiasite.lndo.site"
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

*Example:*

```bash
# Downloaded a backup database from a GUI
# Copied the backup database to the site's reference subdirectory /reference

$ lando db-import reference/prod-acquiasite-2019-10-04.sql.gz 
File /app/reference/prod-acquiasite-2019-10-04.sql.gz not found!
# NOTE: When I did a `lando ssh` the file was where it should be

# NOTE: This has been working for the last year
# NOTE: I upgraded from rc.13 to rc.21 and this broke

# Workaround for now:
mv reference/prod-acquiasite-2019-10-04.sql.gz ./
lando db-import prod-acquiasite-2019-10-04.sql.gz 
# When it is in the root it works just fine
```

**Comment by uberhacker** [comment]
@ccjjmartin:  This is working fine for me.  Since that is a relative path, did you make sure you were in your project root before executing?

**Comment by ccjjmartin** [comment]
Yes, I was in the repo root during this process and the import process works when I move the file to the repo root so we know that the mysql container is running and working properly.

**Comment by ccjjmartin** [comment]
Not stale

**Comment by pirog** [comment]
@ccjjmartin i also could not replicate this. i did add a functional test though.

**Comment by ccjjmartin** [comment]
This might have been a bug only on rc21, it is working for me using `rrc1` should I go ahead and close this or leave it open for the functional test to reference?  @pirog

**Comment by pirog** [comment]
@ccjjmartin should be safe to close!

**Comment by ccjjmartin** [comment]
Closing thanks for writing a test for this @pirog

**Comment by kinglouie** [comment]
I have the same issue that the `db-import` command won't find the file. I'm using the rrc1 package form the arch user repository https://aur.archlinux.org/packages/lando/.

when I run `lando db-export test.sql` the sql.gz file is created successfully. When I ssh into lando the file is also there. But when running `lando db-import test.sql` the file can not be found.

**Comment by Tigatok** [comment]
Also experiencing this issue. Fairly simple lando setup with wordpress. The database.sql file is located in the webroot directory.

File /app/database.sql not found!

**Comment by ccjjmartin** [comment]
@kinglouie @Tigatok I would suggest opening another issue for these.  This issue was related to the database not importing when it was located in a subdirectory.  Example would be `/app/backups/database.sql.gz`

For kinglouie I would try making sure the file wasn't exported as a gzip.

For Tigatok I would downgrade to `rrc1` I think `rrc3` is still considered pre-release so it may have some bugs.
