### ISSUE TITLE
Permission issue connecting to docker daemon after install on Linux

### ISSUE THREAD

**Issue by bennlich** [lando/lando#1817]
**Tell us about your setup**

v3.0.0-rc.22 on Debian Buster

**Tell us about the command you were running**

```
lando start
```

**Tell us about the error you got**
```
Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info: dial unix /var/run/docker.sock: connect: permission denied
```

**The Deets**

TL;DR It looks like the Lando installer added me to the "docker" user group so that it could communicate with the docker daemon without root, but this didn't seem to work. `lando start` resulted in a docker daemon permission error until I did the following:

```
sudo usermod -aG docker <my-username>
newgrp docker
```

Maybe if I had opened a fresh shell after installing lando from the .deb, everything would have worked fine?

Thinking it would be helpful for future linux users if the install script magically made this work or if the install docs were updated to reflect this.

**Comment by dustinleblanc** [comment]
Hey @bennlich!

This is actually an issue with docker itself, you have to add your user to the docker group, and then log out, and back in. For Lando to work correctly you should be able to run `docker run hello-world` without `sudo` first. We do call this out in the docs here: https://docs.lando.dev/basics/installation.html#linux

However, this is also in the docker install docs themselves.

Lando can't actually control this process, it does require some familiarity with the normal docker install process. We do try to call it out for instance when using [Hyperdrive](https://github.com/lando/hyperdrive) to setup a machine.

Just make sure to log out and back in and you'll be good!

Thanks!
