### ISSUE TITLE
traefik 2.0 and better cert handling

### ISSUE THREAD

**Issue by JasonTheAdams** [lando/lando#1819]
As a developer working on a SaaS platform using wildcard subdomains, I want to have https for my domain and sub-domain, so that I can work in parity with how the site actually operates.

**Please provide some detail on how lando can help solve this problem**

Spin up a wildcard certificate for each proxy url specified (as suggested in #1744).

**Is your feature request related to a problem? Please describe.**

Our team works on a Laravel SaaS platform which uses wildcard subdomains — there are teams on the platform, and each platform has a subdomain (i.e. {team-slug}.example.com). When working locally we need these to continue to work. It's important to use actual subdomains as this affects how cookies and such work. The more parity we can have between local dev and production the better.

We would really like to use Lando, but this is a showstopper for us as the subdomains are very important.

**Describe the solution you'd like**
I would like for it to be possible to have subdomains which have SSL support.

**Describe alternatives you've considered**
It's possible to go the non-subdomain route (the suggested hyphenated domain), but then we'd have to change our code to specifically handle this for dev, creating disparity.

UPDATE BY @pirog: https://github.com/lando/lando/issues/1819#issuecomment-614610841

**Comment by JasonTheAdams** [comment]
@pirog Can this please be reopened? I didn't catch the stale bot and this remains a dealbreaker for my team to be able to use Lando.

**Comment by pirog** [comment]
@JasonTheAdams i can reopen this but i'm not sure this feature is possible due to how wildcard certificates work wrt our proxy container. Certainly open to a proposal.

**Comment by pirog** [comment]
@JasonTheAdams going to update this ticket to increase the scope. This should now be possible using traefik 2.0

Here are some notes for me about things that should be part of this card.

- installers use docker run and heredoc to make CA and whitelist it
- Users can drop certs in ~/.lando/certs  named all.DOMAIN or app.DOMAIN and lando will add those on top of its own
- Lando add-cert should support all proxy routes to that service in altnames as well as the basics, app prop that can be augmented
- Upgrade to traefix 2.0 and use pass through, this should allow us to add labels based on the apps http/https status. Also use file provider for custom certs?
- What about subdirs and wildcards?
- Disable the dashboard 
- Make a security doc

**Comment by JasonTheAdams** [comment]
That's awesome, @pirog! Thanks for keeping this issue alive. I think having real support in Lando for subdomains will be very handy. The reality is that having folks just hyphenate subdomains into a single domain not the same as a real subdomain, which removes parity from production and makes the local dev less valuable. For us it would be _very_ cool to have wildcard subdomains (and, as a bonus, wildcard certificates), but not 100% necessary. So long as each subdomain can be set up and given a certificate, that's a great start.

**Comment by pirog** [comment]
I actually personally don’t think having parity with production in this way
is hugely important. Having application logic that determines these things
based on the environment is what we’ve always done and seems to be the
recommendation of many PaaS providers as well.

Regardless there is no doubt that the current way we handle certs is pretty
janky and should be improved. If that also makes peoples experience with
lando better than double bonus!

**Comment by pirog** [comment]
@JasonTheAdams this will be in the next release!
