### ISSUE TITLE
update brew cask fomula to v3.0.0-rc.22

### ISSUE THREAD

**Issue by chrillep** [lando/lando#1821]
brew cask install lando installs  -> v3.0.0-rc.21
https://formulae.brew.sh/cask/lando#default

update to rc.22

**Comment by chrillep** [comment]
>brew cask install lando installs  -> v3.0.0-rc.21 ...

@chrillep please 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by philltran** [comment]
Hi. I updated brew cask this morning. Please try it out.

**Comment by chrillep** [comment]
sry for late feedback but it worked :)

**Comment by chrillep** [comment]
but now it is rc.23 =)

**Comment by chrillep** [comment]
cheers updated =)

**Comment by chrillep** [comment]
should be automated somehow 🤔

**Comment by philltran** [comment]
I agree on automation. You are welcome.
