### ISSUE TITLE
3.0.0-rc.22: Opening LandoInstaller.pkg on MacOS Catalina not allowed

### ISSUE THREAD

**Issue by ChandeepKhosa** [lando/lando#1829]
My current version of Lando is v3.0.0-rc.16 on MacOS Catalina

ISSUE:
I downloaded the latest .dmg from github, then once downloaded it, opened LandoInstaller.pkg but got the Mac error
""LandoInstaller.pkg" can't be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information."

RESOLUTION:
I went to "Security & Privacy" and told my Mac to allow the blocked application, then successfully managed to upgrade from rc.16 to rc.22

**Comment by victorkane** [comment]
Got the same warning for 3.0.0-rc.22 this morning on Catalina (Mac). Says "LandoInstaller.pkg can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information. This item is on the disk image "lando-v.3.0.0-rc.22.dmg"

**Comment by pirog** [comment]
As of rc.23 we are notarizing our software and complying with the dictates of our apple overlords
