### ISSUE TITLE
drush gives "OCI run time exec failed" on Mojave with zsh

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#1842]
Initially described in this issue:
https://github.com/lando/lando/issues/1542

Re-opening here because I have specific steps to reproduce and the old issue is closed without resolution.

**Tell us about your setup**

Lando 3.0-rc22
Mojave 10.14.6

**Tell us about the command you were running**

`lando drush`

**Tell us about the error you got**

`OCI runtime exec failed`

**Tell us more**

Steps to reproduce:

1. Switch the user default shell to zsh. (I did this to prep for Catalina.)
2. Pull a D8 site from Pantheon.
3. The site builds correctly, but when you try to run drush, you get the error.

Switching the shell: Go to System Preferences, Accounts, right-click on the user name, advanced options, and then change the shell.

Switching the user's default shell back to bash, restarting the system, and then running `lando rebuild` will allow lando to work again... but you can't switch shells then.

**Comment by pirog** [comment]
@ptmkenny ive been running `/bin/zsh` as my default shell in `iTerm2` for quite some time eg years and have no encountered this so we might need some additional details to repro

**Comment by ptmkenny** [comment]
@pirog This happened when I switched the default shell in System Preferences for my user account.  I just tried setting the shell to `/bin/zsh` in `iTerm2` (leave the user shell as `bash` in System Preferences -> Accounts) and I can still use drush.

So the problem appears to originate from setting the shell to zsh in System Preferences -> Accounts and then spinning up a lando environment locally.

**Comment by dalin-** [comment]
Since a `lando rebuild` is part of the steps to fix, this might not have anything to do with zsh, but instead this more general bug:
https://github.com/lando/lando/issues/1836
