### ISSUE TITLE
Add a notice about the risks of setting a user in docker group

### ISSUE THREAD

**Issue by gilbsgilbs** [lando/lando#1853]
**Link to the page that needs to be updated or changed.**

https://docs.lando.dev/basics/installation.html#additional-setup

**Describe the change you'd like**

The installation documentation for Linux recommends to set your own user into `docker` group. I'm concerned by the fact that there isn't any security notice about doing so because it is equivalent to giving your user full root privileges.

By the way, is there an alternative way to run lando on Linux? The CLI doesn't let you run lando as root (which is a good thing I guess), but using lando through TCP with a docker server in a VM doesn't work either. It ends up crashing with `Cannot start service ca: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown`. This makes lando close to unusable on Linux IMO :disappointed: .

**Comment by arabdevelop** [comment]
@stale bullshit
