### ISSUE TITLE
Custom tooling in global config.yml

### ISSUE THREAD

**Issue by barraponto** [lando/lando#1858]
As a lando user working on several Drupal/WP projects, I want to have my custom tooling in config.yml so I don't have to copy it from project to project.

**Comment by tormi** [comment]
This should work:

```
postLandoFiles:
  - /PATH/TO/.lando.tools.yml
```

**Comment by barraponto** [comment]
Works great. Running `lando config --format=json | jq .postLandoFiles` shows my tooling _after_ `.lando.local.yml` which I'm not sure is the best solution, since project-local wouldn't override host-local. I guess I should add my tooling config to the beginning of `preLandoFiles` to have it overridden by any lando file (host-local is less specific than project-global or project-local).

**Comment by barraponto** [comment]
both `preLandoFiles` and `postLandoFiles` are loaded [in bootstrap.js][1] using [`getLandoFiles`][2] which in turn looks at the lando root and upwards -- never reaches `~/.lando`. I could put my custom tooling file in the home folder I guess...
