### ISSUE TITLE
Docker Edge v2.1.5.0 error on lando start: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ccharlton** [lando/lando#1862]
New edge version of Docker Desktop v2.1.5.0 shows errors on `lando start` (lemp recipe):

**Tell us about your setup**

**What is your lando version and operating system?**

Lando v3.0.0-rc.22 on Mac OS 10.14.6 (18G1012)

**Tell us about your `.lando.yml`**
Standard lemp recipe, no customizations.

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

```ERROR: for mysite_appserver_nginx_1  a bytes-like object is required, not 'str'

ERROR: for appserver_nginx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.36/containers/1dbb8eefc76tyug6adf7220bd50137c9d5e08e4cdd2bc359c26eb3105f67/start
```

**Tell us generally about your bug**

I wanted to try the new early migration of Kitematic in Docker Desktop edge, so I upgraded Docker to edge v2.1.5.0 and thought I'd share this potential [behavior] change.

*Example:*

```
1. Install Lando
2. Upgrade to edge Docker v2.1.5.0
3. Try to start Lando app
```

**Comment by Xilonz** [comment]
This also happens with docker v2.1.6.0,  Lando v3.0.0-rc.22, Windows 19025.1

**Comment by ccharlton** [comment]
Docker desktop edge 2.1.6.0 (40807) resolved this.
