### ISSUE TITLE
Include lando as pacakge in snapcraft/chocolaty

### ISSUE THREAD

**Issue by sarath49** [lando/lando#1864]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

**Please explain your request and its importance in the form of a user story.**

*Example: As a lando user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

**Please provide some detail on how lando can help solve this problem**

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pirog** [comment]
@sarath49  im closing this out in favor of the meta issue over here which seeks to bring a bunch of related tickets together so we can figure out a plan. would love to get your feedback
https://github.com/lando/lando/issues/2217
