### ISSUE TITLE
No "git for windows" program after install.

### ISSUE THREAD

**Issue by dpagini** [lando/lando#1865]
**Tell us about your setup**

Just installed Lando 3.0-rc22 on Windows 10 Professional.

**Tell us generally about your bug**

The installer tells me that "Git for Windows" will be installed along with Lando. I cannot find git for windows on my system at all after I install the tool. Am I missing something here?

**Comment by dpagini** [comment]
Is this that uncommon? Should I be expecting this program to be installed?

**Comment by dpagini** [comment]
Is it common to get no response on an issue? I'm sorry, I have been somewhat monitoring this, and it just seems to get ignored and moved to this `wontfix` label. Any help/thoughts would be appreciated.

**Comment by pirog** [comment]
@dpagini not that uncommon but we generally prioritize issues with lots of participants and feedback first. This is also free and open source software run by volunteers so response times can be extremely variable. We are striving to address this concern as we get more users and you can read more about that here if you are interested
https://blog.lando.dev/2020/02/14/announcing-lando-alliance/

That all said, we've got this issue in the next sprint and the `tl;dr` on it is we no longer install `Git for Windows` as part of Lando but the option was mistakenly left in the installer UI, it will be removed in the next release.

**Comment by dpagini** [comment]
Thanks Mike. I actually heard you today on the Drupaleasy podcast, which reminded me of this issue. Honestly, I tried to download/use Lando at work (corporate lockdown laptop/network), and I got caught up on this issue, and it seemed like it was a relatively easy answer and I just never heard anything, so I had moved on. I'll have to give it a try again...

**Comment by pirog** [comment]
@dpagini fair enough! lando on windows has always been a challenge for some of the reasons you state.  That said Docker recently released a new version which claims to help some of these things. We will be cutting a release this Friday that includes support for this new version. I'd try that out and if you have any issues jump into our Slack channel and someone will try to help you out!
https://launchpass.com/devwithlando
