### ISSUE TITLE
Feature request: Support current Node LTS Erbium (12)

### ISSUE THREAD

**Issue by fafnirical** [lando/lando#1866]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

**Please explain your request and its importance in the form of a user story.**

As a Lando user who works with Node, I want the option to use Node 12, the current LTS version, without having to specify it as a custom image override.

**Please provide some detail on how lando can help solve this problem**

Add `12` to the supported version list for Node.

**Is your feature request related to a problem? Please describe.**
Trying to run Lando with a service of type `node:12` fails with the following error message:
> Error: node version 12 is not supported

**Describe the solution you'd like**
Support for Node 12 (`node:12`) baked in. Ideally, there'd also be a way to specify just `node:lts`, but I would consider support for Node 12 a higher priority.

**Describe alternatives you've considered**
Setting the service as `node:custom` and creating an override for the image to be `node:12`:
```yaml
type: node:custom
overrides:
  image: node:12
```

**Additional context**
Node 12 is the latest active LTS version of Node. Additionally, Node 8 is EOL. <https://nodejs.org/en/about/releases/>

**Comment by runofthemill** [comment]
please don't close this, stalebot :)

**Comment by JorisInsign** [comment]
Is there any reason why we can't add node 12 to lando ?

Thanks,
