### ISSUE TITLE
Lando install creating directory instead of file.

### ISSUE THREAD

**Issue by jarkin13** [lando/lando#1870]
I recently updated my Lando, and when I did I got 2 errors:
```
error: Error: EPERM: operation not permitted, unlink '~/.lando/config/varnish/chaperone.sh'
error: Error: EPERM: operation not permitted, unlink '~/.lando/config/solr/start-solr.sh'
```
When I went to review these files I found they were empty directories. I found a working copy of the files and now my lando is working, I just wanted to flag this.

**Comment by davereid-pfg** [comment]
If anyone encounters this in the future, deleting the directory it's complaining about, and then re-running your lando start/rebuild command seems to work just fine.
