### ISSUE TITLE
[v3.0.0-rc.22] TERMINUS_VERSION envar should not be set in the Dockerfile for Pantheon recipes

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1872]
Apparently, recent versions of terminus are now using the `TERMINUS_VERSION` environment variable to display the version which can be set in config/constants.yml.  This makes it impossible to update the terminus version in a build step since this value is hardcoded in the image that subsequently generates the containers.  We probably shouldn't use envars that are prefixed with `TERMINUS_` in our current scheme.

**Comment by uberhacker** [comment]
Not so fast @stalebot.

**Comment by uberhacker** [comment]
Unstable

**Comment by pirog** [comment]
@uberhacker good call!
