### ISSUE TITLE
Add support for PHP 7.4

### ISSUE THREAD

**Issue by BramDriesen** [lando/lando#1891]
**Request**

PHP 7.4 is releases, so it would be good if we can set the 7.4 version in the lando configuration file.
(Release post: https://www.php.net/archive/2019.php#2019-11-28-1)

**Steps to take**

- [ ] Add the new PHP 7.4 container
- [ ] Updated all the documentation pages that are needed (e.g: https://docs.lando.dev/config/php.html#supported-versions)

**Comment by rikvanderkemp** [comment]
For those interested I've started to see if I could get the container ready. https://github.com/rikvanderkemp/lando/tree/1891-php-7.4-support

Right now fpm seems to build just fine except for imap support.

**Comment by rikvanderkemp** [comment]
Just to be complete. There is a working PR open (https://github.com/lando/lando/pull/1892) and covers both checks in this issue.

It's only possible to provide 7.4 through buster. All other underlying containers are based on stretch.

I personally haven't seen issues with this setup but would appreciated feedback and more people testing this container.

**Comment by BramDriesen** [comment]
That's lame 😞

**Comment by tlorens** [comment]
A few Symfony libraries require PHP 7.4 now which is tagged as Stable.

**Comment by tlorens** [comment]
> Just to be complete. There is a working PR open (#1892) and covers both checks in this issue.
> 
> It's only possible to provide 7.4 through buster. All other underlying containers are based on stretch.
> 
> I personally haven't seen issues with this setup but would appreciated feedback and more people testing this container.

7.4.1-fpm-alpine3.11, 7.4-fpm-alpine3.11, 7-fpm-alpine3.11, fpm-alpine3.11, 7.4.1-fpm-alpine, 7.4-fpm-alpine, 7-fpm-alpine, fpm-alpine tags appear in the official PHP docker image

**Comment by rabauss** [comment]
@stale stop automatically marking

**Comment by francesco-taioli** [comment]
Hi, any idea when we could use php 7.4 with lando?

**Comment by yumyo** [comment]
Using v3.0.0-rc.23, still getting `php version 7.4 is not supported`

**Comment by yumyo** [comment]
Ok duplicate of #1892 and #2030 ... not having it listed in the docs would have saved some time ...

**Comment by francesco-taioli** [comment]
> Using v3.0.0-rc.23, still getting `php version 7.4 is not supported` while https://docs.lando.dev/config/php.html#supported-versions states the opposite.

yeah, i've tried this morning.. they update the docs but it doesn't work

**Comment by BramDriesen** [comment]
It makes sense, the v23 release is from last year ;-) you need to wait until a new version is released.

**Comment by BramDriesen** [comment]
Looks like we will be jumping to V3 https://github.com/lando/lando/milestone/30

**Comment by pirog** [comment]
The docs reflect `master` _not_ the last release so sometimes there is a disconnect especially a few days before we cut a new release.
