### ISSUE TITLE
Unhelpful error when docker-compose isn't installed

### ISSUE THREAD

**Issue by ar1a** [lando/lando#1901]
Inside of bootstrap.js https://github.com/lando/lando/blob/master/lib/bootstrap.js#L107 this doesn't check for failure of not being able to find docker-compose binary. if this fails it gives the very unhelpful error message of LITERALLY just `error: spawn . EACCES`

we had to dig through source code and sprinkle `console.trace`s everywhere, and this seems like a common error to have (when not installing from a package)

**Comment by ar1a** [comment]
this is still an issue

**Comment by pirog** [comment]
@ar1a good suggestion! Definitely worth addressing.

**Comment by nielsvm** [comment]
This just threw me off as well:
```
 ~/proj $ lando start
Let's get this party started! Starting app hello-lando...
Error: spawn . EACCES
Error: spawn . EACCES
Error: spawn . EACCES
Error: spawn . EACCES
Error: spawn . EACCES
Error: spawn . EACCES
```

Good this issue exists, but would be best to have a clearer error message! :-)

**Comment by pirog** [comment]
Alright starting in rrc.8 there will be a much more helpful message for people who end up here!
