### ISSUE TITLE
lando share not working because certificate expired

### ISSUE THREAD

**Issue by daliborstojakovic** [lando/lando#1903]
Self explanatory issue:
Getting error below on lando share --url http:://some_link:some_port :
tunnel server offline: certificate has expired, retry 1s

Workaround:
Rollback date on local machine some days earlier

**Comment by Xilonz** [comment]
https://github.com/localtunnel/localtunnel/issues/332

**Comment by Xilonz** [comment]
It would be nice if the lando devs would set up their own local tunnel instance or use/recomend another service. There's no response from the localtunnel devs so far.

**Comment by jan-di** [comment]
As a workaround you can use ssh-based services on your host machine:

e.g. [localhost.run](https://localhost.run/):
`ssh -R 80:localhost:<http port from lando info> ssh.localhost.run`

Inside the appserver its not working for me, so you have to get the dynamic http port everytime after lando starts.

**Comment by Xilonz** [comment]
Yes, but that's not the purpose of lando share; you can't share with others that way. Ngrok is much easier to use as alternative, or don't use lando share at all, change the .lndo.dev to your own domain and use cloudflare flexible ssl or similar (not tested)

**Comment by jan-di** [comment]
You can, you get an domain like *****.localhost.run which is publicly available and forwards the traffic to your local machine/lando. Just like ngrok, but with less options.
I think it would be great to add the possibility to use other providers like ngrok/localhost.run with the share command.

**Comment by TMFEspresso** [comment]
bumping this since localtunnel.me is down atm, and it looks like it's transitioning to abandonware. 

https://twitter.com/defunctzombie/status/1219768900537081856

^ here's the maintainer of localtunnel telling someone:

> Give https://ngrok.com a try - I don't spend time on localtunnel these days.

**Comment by pirog** [comment]
Going to close this in favor of the proposed resolution over at #1675 
also see @TMFEspresso's related ticket over at #2088. 

Let's consolidate work on this over at #1675
