### ISSUE TITLE
Combination lando poweroff + lando start

### ISSUE THREAD

**Issue by mrweiner** [lando/lando#1905]
I often find myself running `lando poweroff` prior to `lando start` in order to shut down all running containers when starting work on a different project. It would be great to have a command that executes `lando stop` on all existing containers and then runs `lando start` on the current directory without shutting down the lando proxy. It might even make more sense as on option, as in `lando start --poweroff` or something.

**Comment by pirog** [comment]
https://github.com/lando/lando/pull/1896

**Comment by mrweiner** [comment]
Ah great, thank you @pirog
