### ISSUE TITLE
Clarification on events (post-start vs post-restart)

### ISSUE THREAD

**Issue by AlchemyUnited** [lando/lando#1908]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/config/events.html

**Describe the change you'd like**

I have a series of run: steps that I want to do on start, but not restart. example: pull DB update from remote DB (e.g., pantheon). 

i tried using post-start, presuming that would shield them from a restart. that didn't seem to be the case. the post-start ran even when doing a restart.

Note: I'm new to Lando, so it could be a misunderstanding on my part.

i was able to use post-rebuild, and then do a rebuild after a start, but not after a restart. that works but i don't think that's right. right?

**Comment by runofthemill** [comment]
The API doc shows which events are emitted in which steps: https://docs.lando.dev/api/app.html#app-%E2%87%92-app – from that it doesn't look like there's anything unique to do post_start but not post_restart :\ Could you use a build/run step?

**Comment by AlchemyUnited** [comment]
i guess so? as i said, i'm new here :)

my work around worked, but not very clean and proper in a Lando-y sorta way :) I would think that if there's going to be a restart it should be able to be slightly different from start. the pantheon db example might not be typical, but i'm sure there's other things that fall into this scenario.

**Comment by runofthemill** [comment]
I'm also relatively new here :P

I guess it depends on when you want the DB update to happen. When you say start, do you mean every time you run the app, _but_ not if you restart it? Or just the first time it's built? If the latter, a [build/run step](https://docs.lando.dev/config/services.html#build-steps) is probably what you want.

**Comment by AlchemyUnited** [comment]
@runofthemill - for me, i understand start to be the full-top to bottom build. and then sooner or later i want to stop, so i do :) i then took restart to be picking up where i left off after the stop; not doing a start all over again. as it is, restart is more like "reboot". 

but now that i'm typing this "out loud" perhaps what i'm looking for is "pause" and "unpause" or simply "resume"; or maybe "init" which would be the build and that auto segues into start. once you init the project, it's start and restart - san a destroy. 

maybe there's some other way to have certain things run at certain times (again, e.g.,, pull down a copy of the DB) but i wasn't able to sort that out, eloquently. but that could be my n00b-ness.

**Comment by runofthemill** [comment]
Yeah, the nomenclature is a little confusing:

`lando init` just creates the lando file, and if necessary, pulls in whatever the source is (in your case, the WP site from your pantheon account, I'm assuming)

`lando start` only triggers build/run steps **the first run after `lando init` or after `lando destroy`**; every other time, e.g. after `lando stop`, the build/run steps in your `.lando.yml` will **not** run.

If you only want to download the db when you build the app (e.g. the first run or after `lando destroy`, use a build/run step.

If you want to download the db every time you run `lando start`, use an event hook (sounds like this is what you tried, and wasn't working for you).

If you want to download the db every time you run `lando start`, *but not* on `lando restart`, you'll probably have to do some custom scripting to achieve that. Maybe you can see if there's anything unique emitted in `lando restart` (see [Discovering Events](If you want to download the db every time you run `lando start`)) and add that as a condition to check before doing the db download. You also might be able to achieve what you're looking for via a [plugin](https://docs.lando.dev/contrib/plugins.html).

If all else fails...hopefully someone with more knowledge will help you out here 😂 - also see the "Support" options in the side bar on https://docs.lando.dev/help/logs.html

**Comment by AlchemyUnited** [comment]
@runofthemill - thanks for your help. much appreciated. 

i shouldn't have used init, as it's already taken. 

**"the build/run steps in your .lando.yml will not run."**
- i thought this was true. however, that's not what i was experiencing w/ the  .yando that was provided to me. 

**'If you want to download the db every time you run lando start"**
- to clarify, i was getting the opposite. it was always getting the db. and i was looking for a way to make that optional. 

**"plugin"**
- i'll look into that, thanks
