### ISSUE TITLE
lando-entrypoint.sh permission denied

### ISSUE THREAD

**Issue by arabdevelop** [lando/lando#1915]
`lando version v3.0.0-rc.23`
`System : windows 10`

realy this issue take me a lot and lot of time, when i try to start i get this error message

lando start
Let's get this party started! Starting app..
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
Starting landoproxyhyperion5000gandalfedition_proxy_1 ...
ERROR: Aborting.

**Comment by uberhacker** [comment]
I can confirm this issue occurs in WSL also.  It looks like the proxy is unable to start.
```
Creating network "landocasetupkenobi38ahsokab441d8ccf364a5dd6d1606e02ef707c731eccf37_default" with the default driver
Creating landocasetupkenobi38ahsokab441d8ccf364a5dd6d1606e02ef707c731eccf37_ca_1 ... error                                                                                                                                                   
ERROR: for landocasetupkenobi38ahsokab441d8ccf364a5dd6d1606e02ef707c731eccf37_ca_1  Cannot start service ca: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for ca  Cannot start service ca: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
Starting landocasetupkenobi38ahsokab441d8ccf364a5dd6d1606e02ef707c731eccf37_ca_1 ... error
```
Windoze! :/

**Comment by uberhacker** [comment]
PowerShell seems to work fine so this appears to be a WSL only issue.  @arabdevelop:  What terminal app are you using?

**Comment by uberhacker** [comment]
Not sure if this is helpful but this is more output from the WSL terminal:
```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 12
  Paused: 0
  Stopped: 1
 Images: 14
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.786GiB
 Name: docker-desktop
 ID: G4YK:EWVU:DX52:S6Z5:NZPV:PEYH:XC2J:IBVE:HBGH:F3L5:2PGH:PCPT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 121
  Goroutines: 120
  System Time: 2019-12-30T01:56:21.675431Z
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
Docker seems to be running fine.  I used this guide to get Docker working in WSL: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

**Comment by uberhacker** [comment]
I'd like to get this working in Windows eventually.

**Comment by smutlord** [comment]
WSL2 is not officially supported by Lando. Check out https://github.com/lando/lando/issues/1723
