### ISSUE TITLE
Changing 'landoFile' in ~/.lando/config.yml prevents tooling from working

### ISSUE THREAD

**Issue by dsnopek** [lando/lando#1919]
Per the docs [here](https://docs.lando.dev/config/lando.html#base-file) you can set 'landoFile' in ~/.lando/config.yml to something other than '.lando.yml'.

We were going to start using this to set 'landoFile' to '.lando.wizdev.yml' so that we could make a Landofile in a customer's repository without it conflicting with their .lando.yml file, which may work in a totally weird way that's dependent on their environment and tools.

However, once I make that change, I can start/stop/rebuild the app and get the expected result, but any tooling (from either the recipe or the site's .lando.wizdev.yml) doesn't work.

For example, using the 'pantheon' recipe, before the change I can run:

```
$ lando composer --version
Composer version 1.9.1 2019-11-01 17:20:17
```

But afterwards, I just get no output. And if I run `lando` it doesn't include 'composer' in the list of commands. 'composer' is from the 'pantheon' recipe, but this also goes for tooling declared in this site's .lando.wizdev.yml.

Lando appears to still be looking for .lando.yml when figuring out tooling, because if I rename the file back to '.lando.yml', it will suddenly find the tooling, even though trying to start/stop/rebuild the app will now fail with "warn: Could not find app in this dir or a reasonable amount of directories above it!", because I've changed the configuration to use .lando.wizdev.yml.

My theory, is that the bootstrap process doesn't go far enough to actually load the ~/.lando/config.yml when figuring out tooling, and so it still uses the default .lando.yml file for that. But if the bootstrap process gets further (like to start/stop/rebuild the app) then it'll know that it's supposed to be using .lando.wizdev.yml now, and work as expected.

**Tell us about your setup**

Ubuntu 18.04 with Lando 3.0.0-rc.23

**Tell us about your `.lando.yml`**

```yml
name: customer
recipe: pantheon
config:
  framework: drupal8
  site: customer
  id: xxxxx
```

I anonymized the site name and Pantheon id.

**Comment by dsnopek** [comment]
Poking around in bin/lando.js, I think my theory is right... It's using the default 'landoFile' initially:

```js
const landoFile = cli.defaultConfig().landoFile;
const preLandoFiles = cli.defaultConfig().preLandoFiles;
const postLandoFiles = cli.defaultConfig().postLandoFiles;
const landoFiles = bootstrap.getLandoFiles(_.flatten([preLandoFiles, [landoFile], postLandoFiles], process.cwd()));
const config = (!_.isEmpty(landoFiles)) ? bootstrap.getApp(landoFiles, cli.defaultConfig().userConfRoot) : {};
```

(From https://github.com/lando/lando/blob/master/bin/lando.js#L30)

... which it's using to figure out tooling in `bootstrap.getTasks()` in bin/bootstrap.js:

```
exports.getTasks = (config = {}, argv = {}, tasks = []) => {
  // If we have a recipe lets rebase on that
  if (_.has(config, 'recipe')) config.tooling = _.merge({}, loadCacheFile(config.toolingCache), config.tooling);
  // If the tooling command is being called lets assess whether we can get away with engine bootstrap level
  const level = (_.includes(_.keys(config.tooling), argv._[0])) ? getBsLevel(config, argv._[0]) : 'app';
  // Load all the tasks
  _.forEach(_.get(config, 'tooling', {}), (task, command) => {
    tasks.push({
      command,
      level,
      describe: _.get(task, 'description', `Runs ${command} commands`),
      options: _.get(task, 'options', {}),
      run: (level === 'app') ? appRunner(command) : engineRunner(config, command),
      delegate: _.isEmpty(_.get(task, 'options', {})),
    });
  });
  return tasks.concat(loadCacheFile(process.landoTaskCacheFile));
};
```

(From https://github.com/lando/lando/blob/master/lib/bootstrap.js#L146)

I think for the 'landoFile' (and also the 'preLandoFiles' and 'postLandoFiles') to really work as documented, then bin/lando.js needs to load the ~/.lando/config.yml right away, rather than just using the default config.

**Comment by dsnopek** [comment]
This is still a thing! Not sure how to unstale it :-/

**Comment by dsnopek** [comment]
Oh, ok, that's how :-)

**Comment by dsnopek** [comment]
Pre-empting the re-adding of the stale label!

**Comment by pirog** [comment]
Sorry for the massive delay here @dsnopek my friend but finally got a chance to look into this!

**Comment by smutlord** [comment]
@dsnopek i got slightly different behavior but can certainly confirm this is an issue.

**Comment by smutlord** [comment]
the change here https://github.com/lando/lando/commit/e0cc5ef4ead1a77bec9c77bd83165d225f85c38c should fix this. added a test to help confirm.

this does slow things down a tad but probably acceptable

**Comment by pirog** [comment]
ok this should be fixed in the next edge release!

**Comment by dsnopek** [comment]
Thanks, I'll test this soon!
