### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by hailwood** [lando/lando#1925]
In the docs it states you need

- 8-core processor
- 16GB+ RAM
- 100GB+ of available disk space

That's pretty hefty, can someone please explain why we recommend these specs and how it would compare to the specs you'd need if you were running a db, service container (e.g. php), and webserver though docker-compose?

As right now this is [actively dissuading users from trying lando](https://www.reddit.com/r/PHP/comments/ekc0i0/improved_php_workflow_with_lando_and_docker/fd99hcd).

**Comment by philoSurfer** [comment]
short answer... Docker's network file mounts run like shit.  So throw hardware at the problem. 
 
Honestly half of those specs are fine (except for disk space) .. just tune your docker to use 2 cores and 2GB of RAM. 

Several of my devs are on 4-core 8GB machines and it runs fine... (as long as other virtualization things are not running at the same time)

**Comment by Taiger** [comment]
Its snappy fast on a Linux Desktop! Even on an older machine.

I finally gave up on Windows and Mac for good, because of the Docker slowness and other annoying OS issues.

There is no better time to ditch to finally Mac and Windows for good!

I highly recommend Linux Mint. If you need Mac or Windows for work, just use them in virtualbox.

**Comment by philoSurfer** [comment]
#nah

**Comment by pirog** [comment]
@hailwood i think this is just poor documentation, "hardware requirements" should be "hardware recommendations", probably would be good to differentiate between "minimum requirements" and "recommendations" 

that said, we dont want people to use lando and have a bad experience if we can avoid it so i think its ok to be honest that you probably want to have a good machine.

**Comment by pirog** [comment]
alright, ive made improvements! closing this out
