### ISSUE TITLE
lando rebuild -> Rebuild aborted

### ISSUE THREAD

**Issue by djboris88** [lando/lando#1928]
I am not able to rebuild my lando project, as it constantly gives me `Rebuild aborted` message.

Here is the same with the `-v` option:

```bash
$ lando rebuild -v
info: Bootstraping...
info: config bootstrap beginning...
info: config bootstrap completed.
info: tasks bootstrap beginning...
info: tasks bootstrap completed.
info: engine bootstrap beginning...
info: engine bootstrap completed.
info: app bootstrap beginning...
info: app bootstrap completed.
info: Bootstrap completed.
info: App config files found at ["/home/___/work/___/.lando.yml"]
info: App ___ is ready!
Rebuild aborted
```

Yet I have changed my .lando.yml file, and the changes are not resolved (xdebug extension is not loaded into the php appserver container).

I'm using Ubuntu 19.10, 
Docker version 19.03.3, build a872fc2f86
Lando v3.0.0-rc.23

**Comment by djboris88** [comment]
I have just tried `lando destroy` and then `lando start`, which rebuilt the project (and destroyed my db), and now the `.lando.yml` changes are resolved correctly. This is not very convenient way of applying the changes to the project. :)

**Comment by philoSurfer** [comment]
in the future.. run a `lando db-export` if it can run and backup your db...

For my I tend to have to destroy all the things when it is not working... I created a shell script with the following:

landoSmash.sh
```
#!/bin/sh
# file: landoSmash.sh

echo "LANDO SMASH!!!";

echo "Exporting dB...\n";
lando db-export;
lando destroy -y;
rm -Rf ~/.lando;

killall Docker;

rm -Rf vendor/ node_modules/ web/themes/custom/limber/node_modules web/core/ web/modules/contrib/;

composer install;

lando start;

say "all done.";
echo "ALL DONE =)";
```

**Comment by djboris88** [comment]
> in the future.. run a `lando db-export` if it can run and backup your db...

Thanks, I got that in the meantime. But still, is that `lando rebuild` behavior considered normal? Shouldn't it rebuild the setup acknowledging the changes in the `.lando.yml` file?

Also, running `lando rebuild -y` seems to do the job, but the output is still kind of confusing:

```bash
info: Bootstraping...
info: config bootstrap beginning...
info: config bootstrap completed.
info: tasks bootstrap beginning...
info: tasks bootstrap completed.
info: engine bootstrap beginning...
info: engine bootstrap completed.
info: app bootstrap beginning...
info: app bootstrap completed.
info: Bootstrap completed.
info: App config files found at ["/home/___/work/___/.lando.yml"]
info: App ___ is ready!
info: App config files found at ["/home/___/work/___/.lando.yml"]
Rising anew like a fire phoenix from the ashes! Rebuilding app...
info: Rebuilding ___
info: App ___ is ready!
info: Stopping ___
... # here it starts stopping all services and rebuilding them ...
```

**Comment by djboris88** [comment]
Looks like the issue was that the `.lando.yml` file I was using had in it a `rebuild` tooling defined. This is what caused the issues with the default `lando rebuild` command.
