### ISSUE TITLE
Composer and exclude

### ISSUE THREAD

**Issue by AlchemyUnited** [lando/lando#1930]
Basically any other task or issue should go here. Try to frame it as a user story if it makes sense.

The .lando.yaml that was provided to me has this:

excludes:
  - vendor
  - web/wp-content/uploads
  - web/wp-content/themes/xyz/node_modules
  - web/wp-content/themes/xyz/vendor

ultimately, as i understand it, this means those will only exist in the container, and will not be used by lando / the container as a mounted volume. i'm told this makes the overall setup for more efficient / faster. 

the issue is, in trying to track down issues (think speed bottlenecks and/or bugs) anything in those folders is not available to my ide (phpstorm). i can ssh into the containers but that's hardly the same experience. 

the question is: can i continue to run composer inside my containers, but also do it manually outside so i can also review that code? but not effect lando in putting "stuff" in those folders? the folder in question are already in the .gitignore so they're not going to end up in the repo. 

i would expect lando to respect the exclude as long as it there, but lando has some serious magic going on and i didn't want to create something unforeseen and then stuck messing with that.

**Comment by philoSurfer** [comment]
Anything in the "exclude" folders will only exist in the container and will not write to your local disk for those folders.   I find composer runs much slower in the container and I run it in my local and then run `lando rebuild` to sync the changes (PITA, but faster in my case)

Also note if you want to not exclude a specific folder within an existing defined exclude path you can explicitly call that as well (remember to rebuild afterwards) 

eg. if you wanted to keep the `web/modules/contrib` folder mounted for local development but had previously excluded everything in the `web/modules` folder you can:  

excludes:
  - web/core
  - web/modules
  -'!web/modules/contrib'


I tend to do this to specific things I am working on and run a `lando rebuild` prior to doing work.

**Comment by AlchemyUnited** [comment]
@philoSurfer - great! this helps. 

fyi - composer in the container was the client's decision. the composer install and composer update might run faster but (i think he said) the application will run faster not having to access the local mount. it makes sense. the install / update is occasional. but using what's in /vendor is always./ 

thanks again.
