### ISSUE TITLE
How do i spin up my first app?

### ISSUE THREAD

**Issue by pirog** [lando/lando#1940]
@serundeputy care to create the first guide in our onboarding series? 

On a high level the user journey you should be thinking about is:

> New user joins our "training" mailing list, which will send them a guide once in some time interval. say a month. 

The goal is to teach them how to use lando in small iterative chunks. Each chunk should have a single focus and should only take maybe 30 minutes tops to read and try. Each should also revolve around commands users can run or config they can copy/paste. Ideally each would have a repo with working examples/code that the user can visit and try out afterwards. It might be useful to think of these guides as glorified gists with some words to tie the code/config samples together. Also note that it might be a good strategy to visit the config docs for each thing you are working on 
aka https://docs.lando.dev/config/recipes.html#usage for recipes, choosing ONE thing from them you want to showcase eg "overriding recipes" and crafting a guide around that.

It also makes sense to me to cover the most useful basics/popular features first and then increasingly move to less used but more powerful features as we go. Here are some guides that might be worth tackling first.

1. Spinning up your first app
2. Using recipes (this could probably be split into multiple guides)
3. Using services  (this could probably be split into multiple guides)
4. Using the proxy  (this could probably be split into multiple guides)
5. Using tooling  (this could probably be split into multiple guides)
6. Using events (this could probably be split into multiple guides)

In order to get started you will need to get set up to make guides. I would follow this flow https://docs.lando.dev/contrib/guides-intro.html#getting-started-writing-guides and if you see any places for improvement please include those in the PR for this guide as well.

Once you are done i'd also create new issues (use the "question" issue template) for the next five guides we want to do.

Note that we do already have some "first spin up" docs over [here](https://docs.lando.dev/basics/first-app.html#vanilla-drupal-7) but these are sort of teasers and not particularly useful for training purposes.

**Comment by serundeputy** [comment]
When `generate:guide` w/ Team Lando as the author I get an error:

```
└─ $ ∴ lando.dev guide:generate
? Guide title? Gff
? Guide description? what gff wants?
? Written by? Team Lando
? Best category? General
? URL of original content? 
? URL of example repo? example_replace
error: pic is not defined
```

I'll spin up a follow up issue for this.

**Comment by serundeputy** [comment]
Guide: Drupal 7 Landoize and Extant App

PR: https://github.com/lando/lando/pull/1944
