### ISSUE TITLE
Unable to connect to db - fatal alert: protocol_version.

### ISSUE THREAD

**Issue by francesco-taioli** [lando/lando#1952]
Hi, after the `lando rebuild -y` i'm unable to connect to the db via phpstorm.
the error is 
`[08001] Could not create connection to database server. Attempted reconnect 3 times. Giving up. javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version.`
I run lando info and the connection properties are always the same.
Phpstorm db tools work until this morning. Any suggestion?
please help

**Comment by CodeJourneymen** [comment]
I also have this problem.
Initially this worked using PHPStorm using the random port number lando generates.
I then updated `.lando.yml` to use a fixed port of 37001, and I get this error every time too - even after going back not specifying a port.
So after "lando rebuild -y" it never worked again - even after reverting to original `.lando.yml`.

**Comment by CodeJourneymen** [comment]
I tried Sequel Pro, and the connection there works. (default port, and fixed portforward after a rebuild)
So this is a PHPStorm problem, not Lando?

**Comment by francesco-taioli** [comment]
> I tried Sequel Pro, and the connection there works. (default port, and fixed portforward after a rebuild)
> So this is a PHPStorm problem, not Lando?

I've tried two different program. One of them work ( dbeaver ).

**Comment by martin-klima** [comment]
I just spent a lot of time on it. Here is a solution:

In PhpStorm go to Settings, find your failing MySQL connection (or click Datasource properties icon).
Go to the Advanced tab, search for "useSSL" in the Name column and set it to FALSE. Go back to General tab and test your connection. You should get the green checkmark.

**Comment by CodeJourneymen** [comment]
@martin-klima you are a saint. That is exactly the problem.

**Comment by martin-klima** [comment]
Note for someone who searches this issue by error messages in the database container log. This problem causes several "**Bad handshake**" notices in the log during PhpStorm is trying to connect to the database.

**Comment by djallits** [comment]
@martin-klima That allows me to connect to the DB with the `Test Connection` functionality, but I am still unable to see schemas. Any suggestions?

**Comment by jstramel** [comment]
Another vote for @martin-klima being a saint. This solved the issue for me as well.

**Comment by Leamsi9** [comment]
Saint @martin-klima is definitely being canonised. The Vatican has confirmed he worked several miracles for un/deserving devs, calmed the PHPStorm, and made us better people. Thank you for saving me even more hours.
