### ISSUE TITLE
Improve automatic cleanup of orphaned Docker components if lando apps are manually removed

### ISSUE THREAD

**Issue by mattwaler** [lando/lando#1953]
The `stopall` command is very helpful for shutting down all Lando containers, but there is no way to globally remove all lando related docker stuff. 

If you delete a project and it's `.lando.yml` file, there is no easy way to remove its docker components without listing out all containers and volumes.

A command like `lando destroyall` would be very helpful for quickly cleaning up your entire computer's lando footprint, so you can start from scratch.

**Comment by rabauss** [comment]
You could use `docker system prune -a --volumes` - see: https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by trustypelletgun** [comment]
Pruning does not distinguish items created by Lando from anything else that may exist. The request here is to only remove items created via Lando and I agree this would be a good addition. 

Lando would better coexist alongside other development tools and workflows if it could easily cleanup after itself without modifying anything that doesn't belong to it.

**Comment by mattwaler** [comment]
^ Cannot agree more with this guy @trustypelletgun

**Comment by pirog** [comment]
I think giving users the ability to delete ALL lando things in this way is probably going to cause more problems then it solves. I'd like to propose a two-pronged alternative.

1. Augment the extant uninstall documentation and/or uninstall scripts to better inform users on ways they can clean things up 
https://docs.lando.dev/basics/uninstalling.html#removing-lingering-lando-containers
2. Expand the scope of lando's automatic cleanup functionality, IIRC right now if someone deletes a landofile, lando should be able to detect that there are orphaned containers and remove them, this could be expanded to include docker volumes, networks, etc.

anyway, them be my thoughts

**Comment by trustypelletgun** [comment]
That's a reasonable approach. I was unaware of automatic cleanup of orphaned containers. Is that documented somewhere? (I did look)

**Comment by pirog** [comment]
i dont think its documented anywhere because its _supposed_ to be one of those things that "just works". The relevant part of the code is here
https://github.com/lando/lando/blob/0cb0151d7f7aa5b4e535eebd86908d5995b47a8b/lib/docker.js#L81-L88

The caveat is that the cleanup does not happen until the next time you run a lando command that runs that list command eg `lando start`, `lando list` etc.

**Comment by pirog** [comment]
@mattwaler im going to reopen and retitle this
