### ISSUE TITLE
Fast xdebug profiling on/off toggling

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#1954]
**Please explain your request and its importance in the form of a user story.**

As a lando user who works with Drupal sites you sometimes need to profile your code to see what part of code takes longer time to execute. XDebug allows you to dump cachegrind file and then you can open it for example with KCachegrind https://kcachegrind.github.io/html/Home.html

It's possible to enable this feature in Lando if you define custom php.ini location and enable xdebug:

    config:
      webroot: web
      php: '7.2'
      config:
        php: .lando/php.ini
      xdebug: true

And then in .lando/php.ini (I've added also max_execution_time as the site gets slower with this enabled).

    max_execution_time = 300
    
    # XDebug Profiling
    xdebug.profiler_enable = 1
    xdebug.profiler_output_dir = "/app"
    xdebug.profiler_output_name = cachegrind.out.%u.%p.%r.%s

 And then ofcourse:

    lando rebuild

**Is your feature request related to a problem? Please describe.**
Problem is the speed of how to set this feature up and when done, also the removal part.

**Describe the solution you'd like**
This is solution that would already work - to have *lando profiling-on* and *lando profiling-off* command. This is based on https://github.com/lando/lando/issues/1668

    tooling:
      profiling-on:
        service: appserver
        description: Enable XDebug profiling for Apache.
        cmd: "docker-php-ext-enable xdebug &&  echo 'max_execution_time=300' > z && echo 'xdebug.profiler_enable=1 >> z && echo 'xdebug.profiler_output_dir=/app >> z && echo 'xdebug.profiler_output_name=cachegrind.out.%u.%p.%r.%s' >> z && mv z /usr/local/etc/php/conf.d/zzz-lando-xdebug-profiling.ini && service apache2 reload"
        user: root
      profiling-off:
        service: appserver
        description: Disable XDebug profiling for Apache.
        cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && rm /usr/local/etc/php/conf.d/zzz-lando-xdebug-profiling.ini && service apache2 reload"
        user: root

**Describe alternatives you've considered**
Alternative would be to install some tool on the server like New Relic and profile the code on the go.

**Additional context**
![DeepinScreenshot_dde-desktop_20200128124331](https://user-images.githubusercontent.com/492375/73257240-0c141d00-41cc-11ea-805b-60059e2f829c.png)

**Comment by tormi** [comment]
This should cover profiling mode as well: https://github.com/lando/lando/issues/2718#issuecomment-770769207

**Comment by tormi** [comment]
You can use `lando xdebug profile` now with this recipe: https://github.com/lando/lando/issues/1668#issuecomment-772829423.

**Comment by Preen** [comment]
@tormi does your recipe solve the log location as well?

**Comment by tormi** [comment]
@Preen , what about the log location? You can define a custom [xdebug.output_dir](https://xdebug.org/docs/all_settings#output_dir) in the `.lando/php.ini` of my recipe https://github.com/lando/lando/issues/1668#issuecomment-772829423.

**Comment by Preen** [comment]
Yeah sorry, that solved it. Thanks for a great recipe! :)
