### ISSUE TITLE
Cassandra Service?

### ISSUE THREAD

**Issue by SpaceBoiNate** [lando/lando#1955]
Currently Lando does seem to support MongoDB, however, it would be nice to have Cassandra support as a service. I'm willing to give a stab at creating a pull request, however, I want to make sure that it is worth developing and if there is anything that I should note when developing/adding a service. I've already reviewed the service plugin.

**Comment by SpaceBoiNate** [comment]
Created #1959

**Comment by serundeputy** [comment]
@SpaceBoiNate would you be willing to attend a [`Lando Contributors Meeting`](https://docs.google.com/document/d/1t2lAP3wLiBpaWR90GE7sMT-d6UJ9-GiTe2y50kDuumc/edit#) as the Cassandra representative to give the current state of the PR and determine how to move forward with it?

**Comment by SpaceBoiNate** [comment]
@serundeputy Sorry for the delay, I've been really busy. However, I can look into joining a meeting.
