### ISSUE TITLE
Ability to disable service from .lando.local.yml

### ISSUE THREAD

**Issue by thejacer87** [lando/lando#1965]
for a while, it was just me on the project at work. just recently a new member was added, and since he's on a mac and has sequel pro, he doesnt need the phpmyadmin service that i created. 

obviously i could remove the service from the main lando file, and i could add it in my own local config. but there might be other scenarios where it makes more sense to just disable the service on a per user basis

**Please provide some detail on how lando can help solve this problem**

add an `enabled: false` option in the lanod yml. obvioulsy defaults to true for every service. but in the local lando file adding it will not spin up the service

**Comment by pirog** [comment]
@thejacer87 going to close in favor of #1860
