### ISSUE TITLE
Elasticsearch failing to start

### ISSUE THREAD

**Issue by craigwillis85** [lando/lando#1967]
Hi

I'm trying to get Elasticsearch working. I've seen other people having problems as well, but I'd thought I'd raise this.

I have the following in my .lando.yml file

    services:
      elasticsearch:
        type: elasticsearch:7
        portforward: false

When I run `lando start` I get the following:

    Starting integrationlayer_elasticsearch_1 ... done
    ERROR: No container found for elasticsearch_1
    error: Looks like elasticsearch is not running! It should be so this is a problem.
    warn: Try running `lando logs -s elasticsearch` to help locate the problem!

The output from `lando logs -s elasticsearch` is:

    elasticsearch_1  |  09:46:33.23 
    elasticsearch_1  |  09:46:33.24 Welcome to the Bitnami elasticsearch container
    elasticsearch_1  |  09:46:33.24 Subscribe to project updates by watching 
    https://github.com/bitnami/bitnami-docker-elasticsearch
    elasticsearch_1  |  09:46:33.24 Submit issues and feature requests at  
    https://github.com/bitnami/bitnami-docker-elasticsearch/issues
    elasticsearch_1  |  09:46:33.24 Send us your feedback at containers@bitnami.com
    elasticsearch_1  |  09:46:33.24 
    elasticsearch_1  |  09:46:33.24 INFO  ==> ** Starting Elasticsearch setup **
    elasticsearch_1  |  09:46:33.25 DEBUG ==> Validating Kernel settings...
    elasticsearch_1  |  09:46:33.25 ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144
    elasticsearch_1  | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
    elasticsearch_1  | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
    elasticsearch_1  | mkdir: cannot create directory '/etc/ssh': Permission denied
    elasticsearch_1  | Running command /entrypoint.sh /run.sh
    elasticsearch_1  | Running with exec!

I'm using RC23 on Ubuntu 18.04

I've tried Elasticsearch 6 and 7 and got the same output

**Comment by hkirsman** [comment]
Was having the issue too for pretty long time although I hadn't changed anything related to ES in configuration. Today started debugging this.
  
Both are failing - native and compose:

    services:
      elasticsearch:
        type: elasticsearch:6

and 

    services:
      elasticsearch:
        type: compose
        services:
          image: blacktop/elasticsearch:6.3
          command: /elastic-entrypoint.sh elasticsearch
          ports:
            - "9200"

The solution lies in the above logs:

    elasticsearch_1  |  09:46:33.25 ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144


So the issue is in your host system. Here's the answer: https://github.com/bitnami/bitnami-docker-elasticsearch/issues/61

Run (prepend sudo if not under root):

    sysctl -w vm.max_map_count=262144

More info about the setting:

https://stackoverflow.com/questions/11683850/how-much-memory-could-vm-use
> max_map_count:
> 
> This file contains the maximum number of memory map areas a process may have. Memory map areas are used as a side-effect of calling malloc, directly by mmap and mprotect, and also when loading shared libraries.
> 
> While most applications need less than a thousand maps, certain programs, particularly malloc debuggers, may consume lots of them, e.g., up to one or two maps per allocation.
> 
> The default value is 65536.

**I think Lando should alert about this or set it during install.**

**Comment by hkirsman** [comment]
There was issue also here https://github.com/lando/lando/issues/817

**Comment by hkirsman** [comment]
I'll leave this here as the above command makes it only temporary:
https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

**Comment by pirog** [comment]
@craigwillis85  @hkirsman Docker Desktop for Mac and Windows set this automatically. For our linux packages we set this on install, see:
https://github.com/lando/lando/blob/master/installer/linux/scripts/postinst#L23

That said, this will not be set if you dont install by any of the above methods so i am going to update the docs to reflect this!

**Comment by pirog** [comment]
docs fixed!

**Comment by tormi** [comment]
> Docker Desktop for Mac and Windows set this automatically. **For our linux packages we set this on install**
Thanks for the clarification!

**Comment by pirog** [comment]
Sure thing! and here are the updated docs
https://docs.lando.dev/config/elasticsearch.html#other-requirements

**Comment by hkirsman** [comment]
sysctl -w only might help temporarily until reboot. Just leaving this here for others.

**Comment by thursdaybw** [comment]
I just installed lando on a pretty new install of ubuntu 20.04 and ran into this issue.
```
elasticsearch_1  | INFO  ==> ** Starting Elasticsearch setup **
elasticsearch_1  | DEBUG ==> Validating Kernel settings...
elasticsearch_1  | ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144
drupal8blank_elasticsearch_1 exited with code 1
```

Quick google search lead me to this issue. hkirsman is correct, the `sysctl -w vm.max_map_count=262144` only works until linux reboots.
So the fix at https://github.com/lando/lando/blob/master/installer/linux/scripts/postinst#L23 only temporally fixes this issue.

As per https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
the value `vm.max_map_count` needs to be set in `/etc/sysctl.conf`

**Comment by thursdaybw** [comment]
I notice that elasticsearch's docs said that elasticsearch will set this value when installing with a deb or rpm. So I dug into their installer see https://github.com/elastic/elasticsearch/pull/21507/files#diff-3328b46abab2fc1acf7375d5fab5f79a - I don't believe this PR shows the whole picture though.

If I inspect their deb package directly, I do see that PR reflected.

file: ./DEBIAN/postinst
```
...
# to pick up /usr/lib/sysctl.d/elasticsearch.conf
if command -v systemctl > /dev/null; then
    systemctl restart systemd-sysctl.service || true
fi
...
```
file: ./usr/lib/sysctl.d/elasticsearch.conf
```
vm.max_map_count=262144
```

That seems a stable solution, provide the same elasticsearch.conf file on install of lando.
Or we could just go ahead and write `vm.max_map_count=262144` directly to `/etc/syctl.conf` and restart the service.

Perhaps though rather than setting this on install and permanently modifying the OS's default, 
`sysctl -w vm.max_map_count=262144` could be called during `lando start` where elasticsearch is a defined service.

The benefit being that the elasticsearch service will always have that setting available, and the value sets back to the OS default on reboot. So if someone were to stop using elasticsearch in lando then reboot, that setting self cleans.

Could this be done in the elasticsearch recipe?

**Comment by pirog** [comment]
I think the problem is that invoking `sysctl` in this way would require `sudo`. 

See #2101
