### ISSUE TITLE
Custom Project Plugins

### ISSUE THREAD

**Issue by SpaceBoiNate** [lando/lando#1970]
Hello,

I'm currently trying to ship my lando development environment with plugins that I have written. I know that the current global config only loads plugins from my .lando/ directory. However, how can I load them from my project directory. I would find it very inconvenient if I would have to tell my team to change their global config. 

Thank you

**Comment by smutlord** [comment]
@SpaceBoiNate this is not currently possible but plugin distribution is going to be the main deliverable of the `3.2` release. 

Current implementation idea is something like 

```yarn
name: app
plugins:
  - lando-someplugin
  - githubgorg/repo
```
And lando will auto-install them before it starts the app
