### ISSUE TITLE
Support Docker Desktop 2.2

### ISSUE THREAD

**Issue by jan-di** [lando/lando#1975]
**Please explain your request and its importance in the form of a user story.**

Official Support for Docker Desktop 2.2. This would allow Windows users the use of docker with the WSL2 engine.

**Describe the solution you'd like**
Lando support for docker desktop v2.2.

**Describe alternatives you've considered**
Using the latest edge Release of v2.1.x works, but isnt a stable version.
With  Docker Desktopnv2.2 and the current RC there are a few bugs (e.g. xdebug isn't working)

**Comment by nexujin** [comment]
As much i would like to see this feature come to be as I'm running Lando on Windows and have WSL2 enabled. It would seem rather contradictionary with what's written in the Installation documentations, as WSL/WSL2 is a specific Windows feature.:

> Lando is designed to work on a wide range of computers. 

 But I'm happy to be wrong on this.

**Comment by jan-di** [comment]
Oh, i think my description was a bit misleading. Lando does not have to support WSL2 explicitly, as it comes with docker desktop v2.2. this issue should be a reason to upgrade the shipped/official supported version of docker desktop (which i guess is the same on windows and mac) and is currently v2.1.x

**Comment by BramDriesen** [comment]
Can we remove the windows tag? 😄 We also need to support Docker for Mac 2.2 & Linux as well

**Comment by pirog** [comment]
Alright support for Docker Desktop 2.2 is in `master` now and will be rolled out in the next release which _should_ be this Friday!

**Comment by yuseferi** [comment]
today is Saturday but it has not released yet:(. when will you release it?

**Comment by pirog** [comment]
dude, contribute or shut the fuck up

**Comment by yuseferi** [comment]
@pirog  dude, fuck yourself, don't say something that can't do it. ASS HOLE !!!

**Comment by pirog** [comment]
im sorry what?

**Comment by yuseferi** [comment]
I asked about when are you going to release? 
I have time to participate if you don't have time to release it today. but I don't know how can I participate in releasing  :)

**Comment by esteinborn** [comment]
does this bug affect Lando? https://github.com/docker/for-mac/issues/4209

its the reason im still on 2.1 on macOS

**Comment by pirog** [comment]
@esteinborn in its normal operation not that i am aware of. ive been using 2.2 for the last week or so and been ok. there might be circumstances where you customize or override a landofile and see this but i am not aware of what they are.
