### ISSUE TITLE
How to upgrade from v3.0.0-rc.22 to v3.0.0-rc.25 on Mac OS 10.15.3 Catalina

### ISSUE THREAD

**Issue by north-krimsly-hp** [lando/lando#1977]
Greetings,

How do I upgrade Lando on Mac OS X? v3.0.0-rc.25 includes a specific Docker version, which probably won't work with the older version of Docker I have installed as part of Lando v3.0.0-rc.22. What are the steps to upgrade? This is probably actually a more general question -- how does one upgrade Lando in general? I couldn't find it in the documentation.
Thanks.

**Comment by spuky** [comment]
guess you mean rc.23 (there is no 25 yet..)just download the dmg and double click the icon... it will install the docker version needed... just do not say yes to the upgrade of docker to version 2.2 which is the newest and is not working with lando yet...

**Comment by north-krimsly-hp** [comment]
Hello,
Thanks for your quick answer. So just to be sure I understand correctly, when I install from the new .dmg file, the Docker version I have will be over-written. So there is no need to un-install my old version of Docker or anything else. Is this correct?
Thanks again.

**Comment by spuky** [comment]
should be the case... not 100% shure.. because my last install was after uninstalling docker... (because I clicked yes for the 2.2 docker update...)

**Comment by pirog** [comment]
There is no rc.25 release. this was an error in our documentation and has been corrected to reflect the in progress status of the next release
https://docs.lando.dev/help/2020-changelog.html
