### ISSUE TITLE
Update Apache vhosts config to be read only

### ISSUE THREAD

**Issue by GMSteuart** [lando/lando#1986]
Current

https://github.com/lando/lando/blob/0ed940ee525d7383bf8d652be6c8080435b21054/plugins/lando-services/services/apache/builder.js#L47

Suggested
```javascript
`${options.confDest}/${options.defaultFiles.vhosts}:${options.remoteFiles.vhosts}:ro`,
```

This will prevent any issues where user's may experience volume mounted configuration files being overwritten after container creation.

**Comment by smutlord** [comment]
@GMSteuart good suggestion, this is also what Bitnami recommends in their own docs for Apache

**Comment by pirog** [comment]
@GMSteuart this will be in the next edge release
