### ISSUE TITLE
Make tar silent during lando init with --remote-url

### ISSUE THREAD

**Issue by aangelinsf** [lando/lando#1988]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.

Running rc23
Reviewed the issues.

I'd like just the tar part of the following command to be silent:
`lando init --recipe drupal8 --webroot . --name component-tester --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components=1"`

**Describe alternatives you've considered**
I didn’t set the -v flag and there is no “silent” option for tar. Sending the entire command to /dev/null doesn’t work because I want to see everything else, like errors.

Matt Obert on the @lando channel suggested this workaround:

`lando init --recipe drupal8 --webroot . --name component-tester --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components=1" | grep -v 'drupal-8.8.2' `

**Request**
Would be great to turn off verbose mode for tar and allow the user to add it to --remote-options if they want it since there is no way to make tar silent once the -v is turned on.

**Comment by pirog** [comment]
@aangelinsf i certainly can understand the desire for less noise. 

the primary reason we have this set the way it is is so the user is getting feedback that something is actually happening. Our concern is if you have a particularly large tar you might not be patient enough to wait for it to complete, assume something is wrong with Lando and then end up filing a false positive bug report. As we know we dont have tons of time to work on this so we try to do what we can to make things more efficient. I guess it didnt work so well in this case though ;)

I'd be amenable to some sort of flag to quiet things down. I'd also be interested in hearing more feedback from other users on this.

**Comment by aangelinsf** [comment]
Completely get it...seems to me that a switch is a good way to go for this since the default would be to verbose and would still accomplish your goal of keeping down false positives. Thanks for being open to the suggestion.
