### ISSUE TITLE
Support Drupal 9

### ISSUE THREAD

**Issue by anavarre** [lando/lando#1993]
Currently, Lando doesn't seem to support Drupal 9.

```
$ lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use?
backdrop
drupal6
drupal7
❯ drupal8
joomla
lamp
laravel
```

By default, we'd need support for PHP 7.3, MySQL 5.7 and Drush 10 to best support Drupal 9. See https://www.drupal.org/docs/9/how-drupal-9-is-made-and-what-is-included/environment-requirements-of-drupal-9

**Comment by BramDriesen** [comment]
Cant we simply re-use the Drupal 8 template. Like a lot of modules are also just being updated in the .info file and not a whole new module/develop branch.

**Comment by mstrelan** [comment]
@BramDriesen yes we just need to update the versions as per OP.

**Comment by tormi** [comment]
D9 is D8 minus deprecated code + new versions of foreign dependencies, so nothing special here.

## Install Drupal 9

```
lando init --source cwd --webroot web --name drupal9 --recipe drupal8 --option php=7.3
lando start
lando composer create-project drupal/recommended-project:^9@dev drupal
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? y
mv drupal/* drupal/.* . && rm -rf drupal
lando drush si demo_umami --db-url=mysql://drupal8:drupal8@database:3306/drupal8 -y
```

## Add latest Drush

`lando composer require drush/drush`

**Comment by anavarre** [comment]
Plenty of choices are being made ATM, which will influence which LAMP stack will be able to run Drupal 9 sites. I mentioned https://www.drupal.org/docs/9/how-drupal-9-is-made-and-what-is-included/environment-requirements-of-drupal-9 above, but in more details I can think of the following at the very least:

* [[policy] Decide on MySQL/MariaDB/Percona Server version support status for Drupal 9](https://www.drupal.org/project/drupal/issues/3107113)
* [Raise the minimum MySQL version to 5.7 and MariaDB version to 10.2 in Drupal 9](https://www.drupal.org/project/drupal/issues/3109534)
* [[policy] Decide on PostgreSQL 9.x/10.x support status](https://www.drupal.org/project/drupal/issues/3106077)
* [Bump minimum PHP for Drupal 9 to PHP 7.3](https://www.drupal.org/project/drupal/issues/3106075)

So this means the Lando recipe that would work OOTB for D9 isn't going to be exactly the same as for D8. An alternative would be to bump the default PHP / MySQL version for D8, so we have only one recipe for both major versions.

**Comment by gitressa** [comment]
Thanks @anavarre and @AaronFeledy for working on this. Drupal 9.0.0-beta1 was released today, and [Drupal 9](https://www.drupal.org/project/drupal/releases/9.0.0-beta1 ) is on track to be released on June 3 2020.
