### ISSUE TITLE
Add option of defining database type during init

### ISSUE THREAD

**Issue by gitressa** [lando/lando#1994]
You can define database type during `lando init` with this:
`lando init --source cwd --recipe drupal8 --webroot web --name d8 && echo "  database: postgres" >> .lando.yml`

Is it worth considering adding a `database` option to lando init?
`lando init --source cwd --recipe drupal8 --webroot web --database postgres --name d8`

**Comment by pirog** [comment]
@gitressa i think this is already supported using the `option` flag that comes with `lando init`

Example:

```bash
lando init \
  --source remote \
  --remote-url https://ftp.drupal.org/files/projects/drupal-7.69.tar.gz \
  --remote-options="--strip-components 1" \
  --recipe drupal7 \
  --webroot . \
  --option database=mariadb \
  --name my-first-drupal7-app
```

that would install latest Drupal 7 and use `mariadb` instead of the default `mysql`. I'm going to update the `lando init` docs with that specific example

**Comment by pirog** [comment]
@gitressa going to close this out
https://github.com/lando/lando/commit/4c8377ffa1e10fcf0dd795fb6db95f0539d88469

**Comment by gitressa** [comment]
Thanks @pirog, you're right, that works just perfectly, thanks! And thanks for adding it to the documentation at the same time.

```
$ lando init --source cwd --recipe drupal8 --webroot web --option database=postgres --name psqltest
$ drush site:install --db-url=pgsql://postgres:@database/drupal8 -y
...
Congratulations, you installed Drupal!   [status]
```
It isn't entirely clear to me why one is set with `--webroot` whereas `--option database` is needed for the other, since both config options are at the same level in `.lando-yml`, but there is probably a good reason :-)

```
config:
  webroot: web
  database: postgres
```
