### ISSUE TITLE
Is there a way to utilize .dockerignore in lando?

### ISSUE THREAD

**Issue by bgreater** [lando/lando#2001]
I'm trying to keep `node_modules` from being synced to the mounted volume.

**Comment by dalin-** [comment]
Take a look at 
https://github.com/lando/lando/issues/1460

**Comment by bgreater** [comment]
@dalin- any idea when this feature will be officially supported? So far this is a game changer in my initial testing!

**Comment by dustinleblanc** [comment]
@bgreater it hath happened: https://docs.lando.dev/config/performance.html#performance
