### ISSUE TITLE
Add MaridaDB V10.4 support.

### ISSUE THREAD

**Issue by CodeJourneymen** [lando/lando#2004]
I need to use Temporal Data Tables (added in 10.3.4) https://mariadb.com/kb/en/temporal-data-tables/
But latest docker image for `bitnami/mariadb` V10.3 is only 10.3.22
There is a `bitnami/mariadb10.4` image but the landofile will hard crash when using 
`type: mariadb:10.4`  
when issuing a `lando start` 
with error
`Unhandled rejection Error: mariadb version 10.4.12 is not supported`

**Comment by pirog** [comment]
this should be added in the next release!
