### ISSUE TITLE
Homebrew may be broken when docker is updated and lando is not

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2005]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/installation.html

**Reason for change**

When installing lando via homebrew, the latest version of Docker is always pulled, which may be incompatible with lando (for example, [it is broken at the moment](https://github.com/lando/lando/issues/1943).

[Homebrew has stated they will not support versioning now or in the future,](https://github.com/Homebrew/homebrew-cask/issues/471). One potential long-term workaround would be to create a special tap for lando that contains the compatible docker versions, as suggested in [Homebrew cask versions](https://github.com/Homebrew/homebrew-cask-versions).

**Describe the change you'd like**

Add this: "If docker has been updated since lando was released, the version installed by brew may be incompatible with lando. In this case, install via the .dmg."

**Comment by RobertAKARobin** [comment]
Related to https://github.com/lando/lando/issues/1941

**Comment by pirog** [comment]
@ptmkenny good suggestion. we also do not maintain the homebrew stuff at all so it would also be good to reflect that in our docs
