### ISSUE TITLE
Documentation references db-import --host flag but code comments claim it does not do anything

### ISSUE THREAD

**Issue by markdorison** [lando/lando#2007]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/guides/db-import.html#usage

**Describe the change you'd like**
[Documentation for the db-import command](https://github.com/lando/lando/blob/master/docs/guides/db-import.md#adding-the-db-import-command) references the `--host` flag but [code comments claim](https://github.com/lando/lando/blob/53e531810fcbb0a13bdf3d986479672d05dc9a75/plugins/lando-services/scripts/sql-import.sh#L25-L33) it "doesn't do anything anymore". Only one of these can be true, right? Maybe the code comments are just misleading? If so, could they be clarified?

https://github.com/lando/lando/blob/53e531810fcbb0a13bdf3d986479672d05dc9a75/plugins/lando-services/scripts/sql-import.sh#L25-L33

**Comment by pirog** [comment]
I think the key part of this is the second line of the comment `we just keep it around for option validation `. 

The comment is not intended to suggest the host flag doesnt work just that the "work" doesn't happen in this place and file anymore. If we wanted to be more clear we could say something like

```
case "$1" in 
   #  This option is now handled with landos built in dynamic options
   # we just keep it around for option validation 
   -h|--host|--host=*) 
     if [ "${1##--database=}" != "$1" ]; then 
       shift 
     else 
       shift 2 
     fi 
```

**Comment by markdorison** [comment]
> The comment is not intended to suggest the host flag doesnt work just that the "work" doesn't happen in this place and file anymore.

@pirog That makes sense now, but when I was debugging an issue related to importing databases, and I ran into that comment, my eyes popped out of my head for a minute. 😆 

I will create a PR with the change you suggested.

**Comment by pirog** [comment]
@markdorison that would be most helpful, thanks mark

**Comment by markdorison** [comment]
@pirog One follow-up: you stated:

> The comment is not intended to suggest the host flag doesnt work just that the "work" doesn't happen in this place and file anymore.

Where is the work happening now? I am having trouble finding it while searching the repo.

**Comment by pirog** [comment]
@markdorison once we introduced dynamic service tooling commands we moved the "host" toggle to be handled with that mechanism
https://docs.lando.dev/config/tooling.html#dynamic-service-commands

and the code part, which basically says "use the service specified by the host flag"
https://github.com/lando/lando/blob/master/plugins/lando-recipes/types/laemp/builder.js#L15

**Comment by markdorison** [comment]
@pirog Thank you!

**Comment by osopolar** [comment]
Just commenting my experience here in case somebody runs into the same:

I was looking for a solution, why my command `lando db-import --host=database_legacy database_legacy.sql.gz` didn't work anymore as before (instead of importing the database the MySQL monitor was started with no db selected). This happend because of the aditional "=" sign. It seems that it was allowed before but now it's not, as shown in [db-import documentation](https://docs.lando.dev/guides/db-import.html#usage), the command needs to be executed as: `lando db-import --host database_legacy database_legacy.sql.gz`.

**Comment by pirog** [comment]
@osopolar i could not replicate this using `master` so im guessing it may be fixed in the next release
