### ISSUE TITLE
Please Update Supported Versions for the Go Service

### ISSUE THREAD

**Issue by tmoffett-centrify** [lando/lando#2009]
**Please explain your request and its importance in the form of a user story.**
As a lando user who works with the Go service, it would be great if the supported versions (https://github.com/lando/lando/blob/master/plugins/lando-services/services/go/builder.js#L11) can be updated to reflect the latest version of Go, so that using the newer version(s) can be simply done in the config without requiring entry into "THE DANGER ZONE" by going the "custom" route.

**Describe the solution you'd like**
It's been about 1.5 years since Go version 1.11 came out with many changes and security fixes since then (https://golang.org/doc/devel/release.html). I'm not sure if the process of changing the supported versions requires any time-consuming testing besides just changing the version numbers, so I didn't make a PR with the change myself. At the very least, maybe the new version numbers can be added to the supported versions and still leave the default at 1.11?

**Comment by pirog** [comment]
this should be available in the next release!
