### ISSUE TITLE
Pull Pantheon test environment

### ISSUE THREAD

**Issue by gaddman** [lando/lando#2021]
**Tell us about your setup**
v3.0.0-rc.3 on WSL2 (Ubuntu 18.04) in Windows 10 Professional

**Tell us about your `.lando.yml`**
```yml
name: my-greens
recipe: pantheon
config:
  webroot: .
  framework: drupal8
  site: my-sitename
  id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

`pantheon.yml`
```yml
api_version: 1
web_docroot: true
php_version: 7.2
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer install'
        script: private/scripts/deploy_product/composer-install.php
      -
        type: webphp
        description: 'Run composer drupal-scaffold'
        script: private/scripts/deploy_product/drupal-scaffold.php
```
**Tell us about the command you were running**

After initialising with ```lando init --source pantheon``` and then starting with ```lando start``` I want to pull code, database, and files from Pantheon's _test_ environment. Select _test_ interactively, or via arguments as below:
```bash
$ lando pull --code=test --files=test --database=test
```

**Tell us about the error you got**
Lando appears to try to get the _test_ branch from the _dev_ environment, rather than the _master_ branch from the _test_ environment as expected:
```bash
$ lando pull --code=test --files=none --database=none
Validating whether dev is a valid environment and that you have access to it
  dev          2016-07-14 21:08:23   dev-my-sitename.pantheonsite.io          git               true     true
Fetching origin
Pulling code from test...
error: pathspec 'test' did not match any file(s) known to git.
fatal: Couldn't find remote ref test
```
Attempting to switch to the _test_ environment also fails, although now it appears to be looking for the _test_ branch in the _test_ environment:
```bash
$ lando switch --env=test
Validating whether test is a valid environment and that you have access to it
  test         2016-07-14 21:08:27   test-my-sitename.pantheonsite.io         git               true     true
Switching to test...
Fetching origin
Pulling code from test...
error: pathspec 'test' did not match any file(s) known to git.
fatal: Couldn't find remote ref test
```

**Tell us generally about your bug**
I'd like to create a copy of Pantheon's _test_ environment (code+database+files), not the _dev_ environment. Choosing 'test' interactively in a `lando pull` command works for the database and files, but not for the code. Am I doing this wrong?

**Comment by dustinleblanc** [comment]
On Pantheon, the test environment is a tag, not a branch, which is probably the root of the issue with checking it out

**Comment by pirog** [comment]
Looks like there is a PR which addresses this already!
https://github.com/lando/lando/pull/1601

**Comment by pirog** [comment]
Alright this is fixed in master and should be in the next release
