### ISSUE TITLE
Notarization and other signing problems

### ISSUE THREAD

**Issue by pirog** [lando/lando#2037]
We are now blocked from our next release because macOS notarization is now smart enough to see that our binary is not signed correctly. This is due to an upstream bug in `pkg`
https://github.com/zeit/pkg/issues/128

Going to create this issue so we can track that but also going to wrap in 

- [x] Upgrade to node 12
- [ ] Get Windows things signed
- [x] Upgrade hyperdrive?
- [x] Update travis certs

**Comment by saurabh-deep** [comment]
Hey @pirog! Were you able to proceed with the signing of Mac OS binary created with `pkg`? Which version of Node js you ended up with?
