### ISSUE TITLE
Unknown TLS certificate issuer

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2047]
**Tell us about your setup**
* lando 3.0.0-aft.1
* Windows 10 Pro, 1909
* Docker Desktop 2.2.0.4

**Tell us about your `.lando.yml`**
```yml
name: test
recipe: lemp
config:
  webroot: public
```

**Tell us about the command you were running**
```bash
lando start
```

**Tell us generally about your bug**
Opening https://project.lndo.site/ shows a TLS certificate error in Firefox developer edition, the error displayed in Chrome is similar/related.
```
Warning: Potential Security Risk Ahead
Peer’s Certificate issuer is not recognized.
Error code: SEC_ERROR_UNKNOWN_ISSUER
HTTP Strict Transport Security: false
HTTP Public Key Pinning: false
```

**Comment by thasmo** [comment]
By the way, very nice work with 3.0.0-aft.1, I wasn't able to get lando running on Windows before but now it seems to work mostly and I really enjoy it. I really appreciate your work on lando, in my opinion it's the successor to Vagrant. :)

**Comment by serundeputy** [comment]
hello @thasmo glad you are enjoying `lando`!

Have you tried this: https://docs.lando.dev/config/security.html#trusting-the-ca

firefox will still complain, but we've had good success w/ that on other browsers.

**Comment by pirog** [comment]
@thasmo we use a self-generated CA to sign all the Lando certs which means you need to do the step @serundeputy has flagged first in order to have them show up as trusted. 

We periodically investigate options that would allow us to skip this manual step but as of right now there arent any great ones.

**Comment by thasmo** [comment]
@serundeputy @pirog Thanks for your help! :)

**Comment by gitressa** [comment]
I agree with @thasmo, Lando is great! But the documentation for Firefox on https://docs.lando.dev/config/security.html#trusting-the-ca is misleading: I still get the `Error code: SEC_ERROR_UNKNOWN_ISSUER` warning, even after setting `security.enterprise_roots.enabled` to `true`. So it would be more precise to state that "Firefox will give a warning, which is unfortunate".

It would be so great to get https and Lando to work in Firefox, is there no way to fix this?

**Comment by pirog** [comment]
FWIW and as far as we can tell the additional steps work required for firefox work as expected

**Comment by gitressa** [comment]
I tried rebuilding, and all the other steps, but still get `Error code: SEC_ERROR_UNKNOWN_ISSUER` ... I am ready to try other methods, if you have any suggestions? Have you gotten it to work with Firefox?

- Ubuntu 18.04
- Firefox 78.0.1

**Comment by pirog** [comment]
I dont have any suggestions beyond googling and helping us update the docs if needed.

I use Chrome as my main browser but i ran through the steps in the docs for Firefox 78 on my Mac and that seemed to work for me.

**Comment by gitressa** [comment]
Thanks for confirming that it works with Firefox and Mac, I'll try to see if I can dig something up.

**Comment by gitressa** [comment]
I noticed this bit in the description of the `SEC_ERROR_UNKNOWN_ISSUER` error message: 

> ... or the server is not sending the correct intermediate certificates.

So perhaps Firefox needs the complete chain of certificates? Perhaps you can share the intermediate and root certificate, so I can try to append it to the present certificate? So long as it isn't a security risk, of course ...

```
-----BEGIN CERTIFICATE-----
(Your Primary SSL certificate: your_domain_name.crt)
This is the one presently used by Lando.
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
(Your Intermediate certificate: DigiCertCA.crt)
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
(Your Root certificate: TrustedRoot.crt)
-----END CERTIFICATE----- 
```

https://www.digicert.com/kb/ssl-support/pem-ssl-creation.htm

**Comment by pirog** [comment]
@gitressa the CA that Lando generated for me is going to be different from the CA Lando generated for you unless we get like once in a universe lucky.

**Comment by gitressa** [comment]
@pirog: Ah, I didn't realize they were that unique :-) ... Do you know if there is a way for me to dig out the root and intermediate certificates from my machine, so I can put them together?

**Comment by gitressa** [comment]
I have had some success by manually importing the `~/.lando/certs/lndo.site.pem` CA certificate in Firefox via `about:preferences#privacy` > `View Certificates` > `Authorities` > `Import`, checking "Trust this CA to identify websites.", and I longer get a warning visiting the `https`-version. I made sure to first run the steps under [# Remove Lando CA](https://docs.lando.dev/config/security.html#trusting-the-ca), to remove any lingering certificates. Also, I don't seem to need to set `security.enterprise_roots.enabled` to `True`.

It would be great to get feedback from other Ubuntu + Firefox users, both whether the [current documentation](https://docs.lando.dev/config/security.html#trusting-the-ca) works for them, and if this new approach gets rid of the warning.

If I `View` the certificate, there is both a `PEM (cert)` and `PEM (chain)`, where the second chained one contains both `PEM (cert)`, and another certificate, which I suspect is the intermediate certificate:

**PEM (cert)**
```
-----BEGIN CERTIFICATE-----
MIIECjCCAvKgAwIBAgIJAOwW5eCDhon/MA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNp
c2NvMQ4wDAYDVQQKDAVMYW5kbzEPMA0GA1UECwwGQmVzcGluMRcwFQYDVQQDDA5M
YW5kbyBMb2NhbCBDQTAeFw0yMDA3MDcwOTM5NDJaFw0yMjEwMTAwOTM5NDJaMHsx
CzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4g
RnJhbmNpc2NvMQ4wDAYDVQQKDAVMYW5kbzEPMA0GA1UECwwGQmVzcGluMR4wHAYD
VQQDDBVhcHBzZXJ2ZXIuZDkuaW50ZXJuYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQC803+00jWa1F7XWwMv8n4fhHWRU4PA1i43/XXKuAE3s5WgdkvN
LYV26gXNJn4N0uM9HFY4ndNwGGuVqz3auchur6cpnmLnVfs2QlsoWI0Yc/lD/Dfo
QbULgHkIQDrkUMa5e5ZC9cP/RaLFGN5ynx6rsrISBEplBwKyS6Kpe99GbDb2G36B
MJw1wqZiWxKH4nVfbB/z0Stno1NlqKFqiEk9Jv1x5gq7QX5gKXziZI+H9uzB2tWs
z1ely7DwKbQ5OPxJmcmMopi3Xc+ZmADdG+uj2Vw6t3dWm0d5KCkwj07Pr+vYp183
HX27AafuhsAD40MSxrNgpSVRiJVSApiHgtHBAgMBAAGjgZcwgZQwHwYDVR0jBBgw
FoAUgnIowU5C8e1WougJKBSzt+DjHQ0wCQYDVR0TBAIwADALBgNVHQ8EBAMCBPAw
EwYDVR0lBAwwCgYIKwYBBQUHAwEwRAYDVR0RBD0wO4IVYXBwc2VydmVyLmQ5Lmlu
dGVybmFsgglhcHBzZXJ2ZXKCCWxvY2FsaG9zdIIMZDkubG5kby5zaXRlMA0GCSqG
SIb3DQEBCwUAA4IBAQCCT4+gWgl+oxnBG7F9VE6JmZnnEY2Ed4XdEnaall0L+Z7R
A3tK+89IQNqUgtaI5auhD/TkRBKmEjjExWjWGCri6qUjqB3A9ipwnUuS2DE+3VJP
9oxb1z5PpBG1tRYtz3uydb62XSOMXo8HyHwT2AQwoo8xD+zcpXTE8QnTlXvxbdft
lX1eGhZGqrCgQqhlQUxonpAozXcIaOf7NntcmzMUIZXbtoABFKNsyDIPK0yNL3Cg
YxKbNq51HcGaLwRm111oyXuGYrD6jFpjCiyHTVJD20hjbXV1psAmYAyiax0sxxT/
TF11ATcW/2TDHxaF5AEGaIHJ31gDxtaFFl44/nhd
-----END CERTIFICATE-----
```

**PEM (chain)**
```
-----BEGIN CERTIFICATE-----
MIIECjCCAvKgAwIBAgIJAOwW5eCDhon/MA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMQ4wDAYDVQQKDAVMYW5kbzEPMA0GA1UECwwGQmVzcGluMRcwFQYDVQQDDA5MYW5kbyBMb2NhbCBDQTAeFw0yMDA3MDcwOTM5NDJaFw0yMjEwMTAwOTM5NDJaMHsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMQ4wDAYDVQQKDAVMYW5kbzEPMA0GA1UECwwGQmVzcGluMR4wHAYDVQQDDBVhcHBzZXJ2ZXIuZDkuaW50ZXJuYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC803+00jWa1F7XWwMv8n4fhHWRU4PA1i43/XXKuAE3s5WgdkvNLYV26gXNJn4N0uM9HFY4ndNwGGuVqz3auchur6cpnmLnVfs2QlsoWI0Yc/lD/DfoQbULgHkIQDrkUMa5e5ZC9cP/RaLFGN5ynx6rsrISBEplBwKyS6Kpe99GbDb2G36BMJw1wqZiWxKH4nVfbB/z0Stno1NlqKFqiEk9Jv1x5gq7QX5gKXziZI+H9uzB2tWsz1ely7DwKbQ5OPxJmcmMopi3Xc+ZmADdG+uj2Vw6t3dWm0d5KCkwj07Pr+vYp183HX27AafuhsAD40MSxrNgpSVRiJVSApiHgtHBAgMBAAGjgZcwgZQwHwYDVR0jBBgwFoAUgnIowU5C8e1WougJKBSzt+DjHQ0wCQYDVR0TBAIwADALBgNVHQ8EBAMCBPAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwRAYDVR0RBD0wO4IVYXBwc2VydmVyLmQ5LmludGVybmFsgglhcHBzZXJ2ZXKCCWxvY2FsaG9zdIIMZDkubG5kby5zaXRlMA0GCSqGSIb3DQEBCwUAA4IBAQCCT4+gWgl+oxnBG7F9VE6JmZnnEY2Ed4XdEnaall0L+Z7RA3tK+89IQNqUgtaI5auhD/TkRBKmEjjExWjWGCri6qUjqB3A9ipwnUuS2DE+3VJP9oxb1z5PpBG1tRYtz3uydb62XSOMXo8HyHwT2AQwoo8xD+zcpXTE8QnTlXvxbdftlX1eGhZGqrCgQqhlQUxonpAozXcIaOf7NntcmzMUIZXbtoABFKNsyDIPK0yNL3CgYxKbNq51HcGaLwRm111oyXuGYrD6jFpjCiyHTVJD20hjbXV1psAmYAyiax0sxxT/TF11ATcW/2TDHxaF5AEGaIHJ31gDxtaFFl44/nhd
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDuzCCAqOgAwIBAgIJANlde9WYeka4MA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMQ4wDAYDVQQKDAVMYW5kbzEPMA0GA1UECwwGQmVzcGluMRcwFQYDVQQDDA5MYW5kbyBMb2NhbCBDQTAeFw0yMDA0MzAwOTEwMDhaFw00NDAxMzAwOTEwMDhaMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2NvMQ4wDAYDVQQKDAVMYW5kbzEPMA0GA1UECwwGQmVzcGluMRcwFQYDVQQDDA5MYW5kbyBMb2NhbCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALQRpbuSPinMRfiX0zGnagt5aOJrRm4KoUQDRlKwz4ai+1DESC7qNqGLgDmbk4ep1nqRLM6xmavFZABUYICkTu9SzhLTU7eMa+6vzPon9SKoBrjsw2+thI4wawJCStQdxQaGXKzoRAlEAyXWaDIBKk5EyPW+XHlP5quprdlPJ6bezer9jM+pPS9GIBuJMgfJLTRXatxkmSFC9lZVa8/3/2PQXMEq6wNBMrk/fQLJbHU7yTZBB6en4CaHTWlq13ja39ZuVdIIlBdbts0wv0cVvM5Y7BkpSPSw652FdRUV9VPLZ8AYaYFxnxXGiP0xQ60HjwhK//XUY+ekpRbfqY5W7VMCAwEAAaNQME4wHQYDVR0OBBYEFIJyKMFOQvHtVqLoCSgUs7fg4x0NMB8GA1UdIwQYMBaAFIJyKMFOQvHtVqLoCSgUs7fg4x0NMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAEr6t/Qhp0WoB0pxbHIfgD3dXuWnituJ7+jxxBuKamiMLJit8Ib0sPIZnt91oqvYJeu49ddA+4Ny7pxtqDs5CQDOk3E9x4u912F7keZssb5Iwtqt2MIWq+060S7h/uCBtp2I5gcA9gpMkgvSrKAjCN0abTtJavz5quWfSMBY3scYNadz+JnnA1svgIckaoCv8J7e34JD6t2PXreWWqvn8aqWup+JclTjwmKKNk96HmhHuS8zGfg/pSQcBfv8zkcSjTF8CcYBh8fTj7L7s6WcBNfVH/zvgwmY7Bzb+0spx0dUBmayVw+IFahexmVaLcG6MfHRYIhpUDynLVlQ76wF8a0=
-----END CERTIFICATE-----
```

**Comment by gitressa** [comment]
I have just verified that this problem is also present on another machine, with the same versions:

- Ubuntu 18.04
- Docker: 19.03.12
- Lando: 3.0.7
- Firefox: 78.0.1 (64-bit)

I have created a PR which updates the documentation: #2457.

**Comment by gitressa** [comment]
I just installed Ubuntu 20.04 and ran into this issue again, with error messages like `Secure Connection Failed`,  `Did Not Connect: Potential Security Issue` and `Error code: SEC_ERROR_BAD_SIGNATURE` in my Firefox browser.

Adding the certificates, and importing the Lando CA certificate afterwards fixed it:
https://docs.lando.dev/config/security.html#debian
https://docs.lando.dev/config/security.html#ubuntu-with-firefox

**Comment by xurizaemon** [comment]
Thanks for the docs update #2457 on this @gitressa 

Observing this on one of two Ubuntu systems ... at least I can click through and not lose much sleep over it now :)
