### ISSUE TITLE
What does "aft" mean inside the version?

### ISSUE THREAD

**Issue by jan-di** [lando/lando#2048]
Might be a silly question, but what does `aft` mean in `v3.0.0-aft.1`? Are those releases supposed to be as equal as stable as a release candidate?

**Comment by thasmo** [comment]
Was wondering the same, thought it's similar to a release candidate.

**Comment by pirog** [comment]
the `rc` series was getting a little long in the tooth but we arent quite ready to go to the full `3.0.0` yet so `aft` is a new release class that we invented to sit between `rc` and the stable release. It means `almost there`, the `f` is flexible, publicly we are saying it means "finally" but internally we use a different word that starts with `f`
