### ISSUE TITLE
Update notice although on latest version (v3.0.0-aft.1)

### ISSUE THREAD

**Issue by osopolar** [lando/lando#2049]
**Tell us about your setup**

v3.0.0-aft.1 on maOS 10.15.3

**Tell us about the command you were running**

`lando version` says:

```
  __  __        __     __        ___            _ __     __   __    ______
 / / / /__  ___/ /__ _/ /____   / _ |_  _____ _(_) /__ _/ /  / /__ / / / /
/ /_/ / _ \/ _  / _ `/ __/ -_) / __ | |/ / _ `/ / / _ `/ _ \/ / -_)_/_/_/
\____/ .__/\_,_/\_,_/\__/\__/ /_/ |_|___/\_,_/_/_/\_,_/_.__/_/\__(_|_|_)
    /_/

Updating helps us provide the best support and saves us tons of time

Use the link below to get the latest and greatest


If updating from 3.0.0-rc.1 or below it is CRITICAL you visit both
https://thinktandem.io/blog/2019/02/01/lando-is-ready-for-the-masses-with-rc2-release/
https://docs.devwithlando.io/guides/updating-to-rc2.html

v3.0.0-aft.1
```

**Comment by BramDriesen** [comment]
Any lando command gives this pompt, I guess because there is some kind of check on the tag, but it doesn't recognise `aft` and thus defaults to the message for RC2. Or maybe it simply checks for the version `.1` 😄

**Comment by BramDriesen** [comment]
I assume this is the problem because `aft` is not in the semver standards.

```
  updateAvailable(version1, version2) {
    return semver.lt(version1, version2);
  };
```

**Comment by rabauss** [comment]
Yesterday I had the update hints as well.
But for now they are gone.

**Comment by pirog** [comment]
As a workaround you should be able to just delete `~/.lando/cache/updates`

**Comment by BramDriesen** [comment]
Yes, deleting the cache does the trick 😄

**Comment by pirog** [comment]
Alright this should be fixed in the next release!
