### ISSUE TITLE
Debian / Ubuntu Repo

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#2050]
Hello,

It should be great to have a Debian Repo to host the .deb and get updates directly on our system.

Many thanks

**Comment by sebastienserre** [comment]
Maybe the easiest should be a PPA
https://askubuntu.com/questions/71510/how-do-i-create-a-ppa

**Comment by pirog** [comment]
Summoning @mishac to helo out on this!

**Comment by pirog** [comment]
@sebastienserre  im closing this out in favor of the meta issue over here which seeks to bring a bunch of related tickets together so we can figure out a plan. would love to get your feedback
https://github.com/lando/lando/issues/2217
