### ISSUE TITLE
EISDIR Error after updating to v3.0.0-aft.1

### ISSUE THREAD

**Issue by edurenye** [lando/lando#2051]
In Ubuntu 19.10 after updating from v3.0.0-rc.23 to v3.0.0-aft.1 apart from finding this issue #2049 I got the following error trying to run lando start on a project.

> Let's get this party started! Starting app application_name...
error: EISDIR: illegal operation on a directory, unlink '/home/user/.lando/config/memcached/launch.sh'

I fixed the error removing the folder '/home/user/.lando/config/memcached/launch.sh', as yes, it was a folder.

**Comment by ben-hamelin** [comment]
Same for me this morning: on MAC 10.14.6, upgrading from rc-23 to rrc1
My first command was a rebuild and I received the same error.

**Comment by nicrodgers** [comment]
I had the same. Deleting ~/.lando fixed the issue for me, once I'd done that then I could lando rebuild fine.

**Comment by pirog** [comment]
This is not something we can fix because it requires `sudo` perms, however this thread is good since it is the workaround

**Comment by jimafisk** [comment]
Similar issue, fixed it by changing these folders to files:
- `rmdir ~/.lando/certs/appserver.mysite.crt`
- `rmdir ~/.lando/certs/appserver.mysite.key`
- `touch ~/.lando/certs/appserver.mysite.crt`
- `touch ~/.lando/certs/appserver.mysite.key`

**Comment by jcandan** [comment]
Ran into this yesterday. The above helped. Thanks.

**Comment by Mgrmjp** [comment]
Ran into this as well where certs where folder and removing and creating and files did the trick. 💪🏻

**Comment by jcandan** [comment]
> ...Deleting ~/.lando fixed the issue for me...

A clarification. If you blow away the whole `~/.lando` directory, you'll lose `~/.lando/bin/lando`, which breaks lando.

Note: If you've done that, you'll likely need to reinstall Lando.

You'd be better off running `rm -rf ~/.lando/certs/*`.

I'm not sure the suggestion to create empty files with `touch` is a good idea. Could cause other problems. I'd remove those files if they do exist so Lando can regenerate.

**Comment by jcandan** [comment]
I noticed I also had to `rmdir ~/.lando/scripts/lando-entrypoint.sh/`.
