### ISSUE TITLE
Custom URL for PhpMyAdmin and Mailhog

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#2055]
Hello,

When building a lando app with a WordPress recipe we got several vitals urls.

Should it be possible to also have pma.my-lando-name.lndo.site and mailhog.my-lando-name.lndo.site to avoid the localhost:PORT ?

Many thanks

**Comment by GoonerW** [comment]
It's not done automatically but it can be configured easily in your .lando.yml file.

Add the following (customize as appropriate):
>proxy:
  mailhog:
    - mailhog.lndo.site
  phpmyadmin:
    - pma.lndo.site

Note that if you go one more deep in the hostname (e.g. pma.yoursite.lndo.site), the inbuilt Lando certs won't cover it.  :(

**Comment by sebastienserre** [comment]
Many thanks @GoonerW 
If I have several Lando running. It's better to customize to have a different URL on each lando. right ?

**Comment by GoonerW** [comment]
Yes.  You can't use the same URL for different containers that are running at the same time.  If only one is running at once, then it doesn't matter.

**Comment by sebastienserre** [comment]
yes it's logical.
Many thanks again
