### ISSUE TITLE
Mysql cannot start - Operation not permitted

### ISSUE THREAD

**Issue by craigwillis85** [lando/lando#2060]
Hi

Just done a `destroy` and `rebuild` and now I'm getting an error with all mysql/mariadb containers (not sure if any are affected)

Logs display the following:

    admindatabase_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
    admindatabase_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
    admindatabase_1   | Running command /bin/sh -c chmod +x /launch.sh && /launch.sh
    admindatabase_1   | Running with exec!
    admindatabase_1   | chmod: changing permissions of '/launch.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
    admindatabase_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
    admindatabase_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
    admindatabase_1   | Running command /bin/sh -c chmod +x /launch.sh && /launch.sh
    admindatabase_1   | Running with exec!
    admindatabase_1   | chmod: changing permissions of '/launch.sh': Operation not permitted

I'm running `Docker v19.03.7`

Anyone experiencing the same issue?

Thanks

**Comment by rorymcdaniel** [comment]
Same issue. Latest release. Docker 19.03.8 on Ubuntu 19.10.

**Comment by craigwillis85** [comment]
I've had to remove docker and re-install

I'm now running `19.03.6` on Ubuntu 19.10

**Comment by rorymcdaniel** [comment]
Downlgrading to aft1, then destroying and rebuilding got me up and running, but I had to add this to my .lando.yml (Saw this in another issue yesterday)
```
services:
  database:
    type: mysql
    overrides:
      image: bitnami/mysql:5.7.28```

**Comment by pirog** [comment]
Alright everyone on this thread, rerolling `aft.2` now with the fix!

**Comment by jjpeleato** [comment]
Same issue with v3.0.0-aft.2 and Docker 19.03.8 on Ubuntu 18.04.4

**Comment by rabauss** [comment]
On Windows with Docker 19.03.8 and `atf.2` (updated from `rc.23`) everything is fine after upate to `mysql:5.7.29`. With `rc.23` we had to pin the mysql-version `5.7.28` to rebuild and run mysql.

**Comment by pirog** [comment]
yup makes sense @rabauss, this issue only impacts linux users

**Comment by pirog** [comment]
alright, i'd recommend everyone try the reroll of the aft.2 if they are experiencing this
https://github.com/lando/lando/releases/tag/v3.0.0-aft.2

**Comment by paulpopus** [comment]
@pirog the new aft2 package is working for me.
Thanks for the fix!

**Comment by pirog** [comment]
awesome @paulpopus, sorry for the hiccup! please continue with your regularly scheduled programming!

**Comment by NickDaelemans** [comment]
> alright, i'd recommend everyone try the reroll of the aft.2 if they are experiencing this
> https://github.com/lando/lando/releases/tag/v3.0.0-aft.2

Is there also .dmg version?

**Comment by pirog** [comment]
@NickDaelemans should be momentarily, dmg usually takes a bit longer to post

**Comment by pirog** [comment]
should be there now @NickDaelemans https://github.com/lando/lando/releases

**Comment by NickDaelemans** [comment]
Thanks, got it now! What was the issue (and the fix)?

**Comment by mikalahtinen** [comment]
Works now with Debian 10 & Docker 19.03.8, thanks for the fix!

**Comment by daliborstojakovic** [comment]
Got same thing with mariadb and v3.0.0-aft.2. Will check with aft1

**Comment by pirog** [comment]
@daliborstojakovic you'll want to reinstall the `aft.2` and try that

**Comment by daliborstojakovic** [comment]
Ok. Will try. Thanks

**Comment by daliborstojakovic** [comment]
Confirming it works now.

**Comment by pirog** [comment]
Excellent news @daliborstojakovic

**Comment by francesco-taioli** [comment]
> Same issue. Latest release. Docker 19.03.8 on Ubuntu 19.10.

fix with setting    type: mysql:5.7.28 and then lando rebuild

**Comment by wassimbns** [comment]
@francesco-taioli  setting type: mysql:5.7.28 and then lando rebuild works for me too

**Comment by pirog** [comment]
Best bet if you are here is to upgrade to the latest Lando and run `lando rebuild`

**Comment by carcam** [comment]
Still experimenting this issue in 3.0.4 and in Debian :(

**Comment by avaleske** [comment]
I'm having a similar issue but pinning the mysql version didn't fix it. It's #3030

**Comment by drjayvee** [comment]
I'm pretty sure this is a duplicate of #2527. I'll share my findings and resolution there.
