### ISSUE TITLE
[v3.0.0-aft.2] Mac upgrade Docker error: (Docker.VmnetdError error 1.)

### ISSUE THREAD

**Issue by ccharlton** [lando/lando#2064]
Upgrading from last RC to 'aft-2'. Saw this pop up in MacOS Catalina:

> The operation couldn’t be completed. (Docker.VmnetdError error 1.)

Will try again and report back.

**Comment by pirog** [comment]
@ccharlton might be worth posting this over in the Docker queue. I think there was some guidance that you need to do a factory reset if you hit this.

**Comment by ccharlton** [comment]
Yep. Choosing to reset to factory defaults helped move it along.

`
warn: Version 1 Landonet detected, attempting upgrade...
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Creating volume "landoproxyhyperion5000gandalfedition_data_proxy" with default driver
Creating volume "landoproxyhyperion5000gandalfedition_home_proxy" with default driver
Pulling proxy (traefik:1.6.3-alpine)...
1.6.3-alpine: Pulling from library/traefik
605ce1bd3f31: Pull complete
9e3eb27e4ab8: Pull complete
c3e998f85b4a: Pull complete
0908932c917b: Pull complete
Digest: sha256:3fde9ec7692454d29663e6d16ceb9255bc128f93d9f33fbca17ce1f3bbd9ca19
Status: Downloaded newer image for traefik:1.6.3-alpine
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
`
👍
