### ISSUE TITLE
Website & Blog Fixes

### ISSUE THREAD

**Issue by mayankguptadotcom** [lando/lando#2067]
1. Not sure if it was intentional but the blog's logo says **landob**.log

2. On Google Pixel 2, the ad is right aligned and the text is wrapping around it. For better readability, can we please remove the right align and keep the ad in center.

![Screenshot_20200320-121400](https://user-images.githubusercontent.com/8931305/77202483-d5200080-6ac4-11ea-89ec-a1c096b6275f.jpg)

**Comment by pirog** [comment]
1 was 100% intentional. See cultural reference here https://www.youtube.com/watch?v=FOtDNXfMyD0
2 should be addressed.

**Comment by AlchemyUnited** [comment]
Since you're on the subject of such things, on the main .dev site the letter-spacing on the h3's is ok when they're large (in the main content), but in the footer they're unnecessarily difficult to read.

**Comment by serundeputy** [comment]
Let's address `2.` here
>On Google Pixel 2, the ad is right aligned and the text is wrapping around it. For better readability, can we please remove the right align and keep the ad in center.

@AlchemyUnited i think that is a separate issue, i.e. if it is a problem open a new issue to keep this issue focused as tightly as possible.
