### ISSUE TITLE
Error: A later version is already installed

### ISSUE THREAD

**Issue by jcmartinez** [lando/lando#2072]
**Tell us about your setup**

What is your lando version and operating system?

v3.0.0-rc.23 on Linux Mint 19.2 Cinnamon

I'm trying to update to the latest version, which I'm downloading from https://github.com/lando/lando/releases/download/v3.0.0-aft.2/lando-v3.0.0-aft.2.deb

**Tell us about the error you got**

After downloading the .deb file, I double click on it to install it. Then, the package installer window opens with a message highlighted in red that says: `Error: A later version is already installed`

I can't install this version.

**Comment by pirog** [comment]
you can if you follow the instruction steps in the documentation
https://docs.lando.dev/basics/installation.html#debian

**Comment by pirog** [comment]
@jcmartinez we've named the latest release `3.0.0-rrc.1` which _i think_ should resolve this. If not feel free to reopn
