### ISSUE TITLE
Can't wp plugin list

### ISSUE THREAD

**Issue by Epistol** [lando/lando#2075]
**Tell us about your setup**

Ubuntu - Lando v.3.0.0-aft.2

**Tell us about your `.lando.yml`**

```yml
name: my-first-wordpress-app
recipe: wordpress
config:
  webroot: wordpress
```

**Tell us about the command you were running**

*Example:*

```bash
lando wp plugin list
```

**Tell us about the error you got**

*Example:*

```bash
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"wp\": executable file not found in $PATH": unknown
```

**Tell us generally about your bug**

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. Setup a new wordpress lando
2. Try to see the list of plugin installed (normally two)
```

**Comment by sebastienserre** [comment]
Hello, 
I can't reproduce on a WordPress recipe but as you speak about Pantheaon, do you use WP or Pantheon recipe? https://docs.lando.dev/config/pantheon.html#getting-started

**Comment by serundeputy** [comment]
@Epistol thanks for opening this issue.

I could not reproduce this behavior either. I was using the default wordpress recipe.

I can say that I have seen that exact error using `drush` on drupal recipes intermittently, in all my cases, a `lando rebuild -y` got things back into working order.

@Epistol can you see if a `rebuild` fixes it for you and if not nail down the steps to reproduce reliably or determine the cause of the intermittent behavior?

**Comment by dedavidson** [comment]
I was getting same error using `drush`:

`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"drush\": executable file not found in $PATH": unknown`

and a `lando rebuild -y` fixed it.

**Comment by pirog** [comment]
I _believe_ we have better protection for this with https://github.com/lando/lando/issues/2079, going to close for now but def reopen if you see it again after updating to the latest
