### ISSUE TITLE
lando share no longer working

### ISSUE THREAD

**Issue by kimdcottrell** [lando/lando#2088]
I've posted something similar [here](https://github.com/lando/lando/issues/1903) to bump the thread, but the issue may be so stale that it's unseen. 

```
$ echo -e "\nsystem details:" && sw_vers && echo -e "\nlando version:" && lando version && echo -e "\ndocker version:" && docker --version && echo -e "\ndocker-compose version:" && docker-compose --version

system details:
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

lando version:
v3.0.0-rc.23

docker version:
Docker version 19.03.5, build 633a0ea

docker-compose version:
docker-compose version 1.24.1, build 4667896b
```

For the wordpress lando recipe, there's a `lando share` command. This command no longer functions as intended, since https://localtunnel.me is down and has probably fully transitioned to abandonware. 

https://twitter.com/defunctzombie/status/1219768900537081856

^ here's the maintainer of localtunnel telling someone:

> Give https://ngrok.com a try - I don't spend time on localtunnel these days.

**Comment by pirog** [comment]
@kimdcottrell i was actually just reviewing issues related to this. Sadly i don't think `ngrok` is going to be an option for various reasons but we probably will investigate again if we cant get the current proposed solution to work.

I'm going to close this in favor of #1675 so id encourage you to post over there!
