### ISSUE TITLE
mkdir: cannot create directory '/var/www/.ssh': Permission denied

### ISSUE THREAD

**Issue by eliforeman** [lando/lando#2095]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

I tried on both lando (v3.0.0-rrc.1)  and v3.0.0-rrc.2 (pre-release). macOS Mojave (10.14.6)

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

name: test_app
recipe: laravel
config:
  via: nginx
  ssl: true
  webroot: ./public
  config:
    database: lando_conf/my.cnf
services:
    database:
      type: mysql:8.0
      portforward: 32948
     

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.
I've tried lando poweroff and lando start, lando rebuild -y, lando restart, lando destroy && lando start, uninstalling/reinstalling docker.

**Tell us about the error you got**

lando start. it seems like the docker image for bitnami/mysql:8.0.19 is created since I am getting this when I list my docker containers:

8a4fb8df94ca        bitnami/mysql:8.0.19-debian-10-r57   "/lando-entrypoint.s…"   2 hours ago         Up 14 minutes (healthy)   0.0.0.0:32948->3306/tcp                                                                     osu_database_1

However, I can't actually connect to the mysql server. 

**Tell us more**

I think this is related to this issue from yesterday: #2084 and these issues from the past #1718  #1486

**Comment by pirog** [comment]
@eliforeman this looks more related to this #2135 than the issues you've referenced.
