### ISSUE TITLE
How do I set my WordPress site URI in Lando for easy wp-cli?

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#2104]
Let's write a guide to show how to set up the `wp` cli tooling to know about the app webroot and app URI.

Similar to what we do here for `drush`, but as a specific guide.

inspiration: https://github.com/lando/lando/issues/2080

**Comment by pirog** [comment]
@serundeputy https://github.com/lando/lando/issues/2080#issuecomment-667114326 may be relevant here as well
