### ISSUE TITLE
How to setup drupal 8 multi site in lando with different databases and the url should be http://mysite.lndo.site/, http://mysite.lndo.site/uk, http://mysite.lndo.site/ca, http://mysite.lndo.site/za....

### ISSUE THREAD

**Issue by arjunpws** [lando/lando#2117]
How to setup drupal 8 multi site in lando with different databases and the url should be http://mysite.lndo.site/, http://mysite.lndo.site/uk, http://mysite.lndo.site/ca, http://mysite.lndo.site/za

multi site setup in Vagrant box we have "blt recipes:multisite:init" but in lando what is the procedure to setup. please help me on this.

Thanks!

**Comment by pirog** [comment]
dup of #433
