### ISSUE TITLE
Solr 8.4 is not supported

### ISSUE THREAD

**Issue by chazchumley** [lando/lando#2119]
Lando v3.0.0-rrc.1 on MAC 10.15.3

name: agrilinks
recipe: drupal8

config:
  via: apache
  webroot: web
  php: 7.3
  xdebug: false
  drush: false
  conf:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf

proxy:
  search:
    - search.agrilinks.lndo.site:8983
  pma:
    - db-agrilinks.lndo.site
  mailhog:
    - mail-agrilinks.lndo.site

services:
  search:
    type: solr:8.4
    portforward: true
    core: agrilinks
    config:
      dir: solr-conf
  database:
    type: mariadb:10.1
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: 8
      behat/behat: 3.3.1
    run:
      - "ln -s /usr/local/bin/composer /usr/local/bin/composer.phar"
    run_as_root:
      - "bash /app/lando/scripts/build.sh"
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://agrilinks.lndo.site"  # TODO Get this out of this file, but it doesn't seem to work in .lando.base.yml
  node:
    type: node:10
    globals:
      gulp-cli: latest
    build:
      - "cd $LANDO_MOUNT && npm install"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  drush:
    service: appserver
    description: run drush commands
    cmd: /app/vendor/drush/drush/drush
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  mailhog:
    service: mailhog
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node

Trying to get Solr 8.4 installed.  However, when I run Lando start, restart or even rebuild I get the following error:

**error: solr verion 8.4 is not supported**

The documentation states the 8.4 is supported.  I am confused as to how to get 8.4 installed since I am following the documentation exactly and still getting the error.  Please advise how to fix this.  Thanks...

**Comment by pirog** [comment]
@chazchumley support was added in https://github.com/lando/lando/releases/tag/v3.0.0-rrc.2 so guessing you need to update. If you do and this still does not work feel free to reopen

**Comment by chazchumley** [comment]
Just updated.  After lando destroy and lando start Solr 8.4 working like a
charm.  Thanks...
