### ISSUE TITLE
I need to update Lando to a newer version so I can use lando pull with Pantheon

### ISSUE THREAD

**Issue by fozzieblue** [lando/lando#2121]
I was running a very old version of Lando (but I do not remember what version it was when I started work today). I tried to update by doing the following things: 

1. Tried 'lando poweroff' and got an error:

`Spinning containers down... Standby.
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
error: Failed after 5 retries with backoff 500 and error Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at dc (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at compose (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at exports.stop.datum (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
ERROR: Duplicate mount points: [/Users/jellis/.lando/services/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw, /Users/jellis/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf:rw]
`
2. Went ahead and turned off Docker. 

3. Installed latest Lando version v3.0.0-rrc.1: https://github.com/lando/lando/releases/tag/v3.0.0-rrc.1

4. Tried 'lando start' and got CRASH. Then got error: "error: node version 6.10 is not supported"

5. I tried several things: 
     a. rm -rf node_modules
     b. updated .lando.yml file so it had type: 'node:6.10'
     c. lando npm install
     d. lando rebuild

I'm able to do lando pull, so something is working. 

I'm able to do lando start, but I get an error when I load the page: PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in lock_may_be_available() (line 167 of /app/includes/lock.inc).

The developer who helped me set up Lando is no longer on the project. I'm not sure what to try next. I'm pretty new to troubleshooting local development environments. Any help would be very appreciated.

**Comment by pirog** [comment]
@fozzieblue we've prepared this update guide for people who are upgrading some super old versions
https://docs.lando.dev/guides/updating-to-rc2.html

It also might be worth completely uninstalling lando before installing the latest if you are like REALLLY far behind
https://docs.lando.dev/basics/uninstalling.html

**Comment by fozzieblue** [comment]
@pirog I will go through both those guides and see how I do. Thank you!

**Comment by pirog** [comment]
sounds good! if you have trouble beyond that id recommend jumping in our slack channel and maybe someone there can help you better!
https://launchpass.com/devwithlando
