### ISSUE TITLE
Docker Version in latest release (rrc2) has problems with Windows.

### ISSUE THREAD

**Issue by nickwilde1990** [lando/lando#2122]
As well [documented/discussed](https://github.com/docker/for-win/issues/5530) (200+ comments), Docker 2.2.0.x has issues of file consistency, specifically on Windows.
I'm not sure if this should be flagged as a bug or a dev-ops problem.
2.2.0.5 test build in that thread seems to fix the issue for a few people using various docker composer implementations, and for me with lando.
As soon as a new stable version of docker is released that fixes this issue, I strongly think a new lando build should also be released.

**Comment by pirog** [comment]
@nickwilde1990 thats the plan!

**Comment by rabauss** [comment]
Yes, Docker 2.2.0.x on Windows also annoyed me - that's why I downgraded to 2.1.0.5.
That's more stable with Lando rrc.2 - thanks for all the work!

**Comment by mrweiner** [comment]
Dropped an update in https://github.com/lando/lando/issues/2052#issuecomment-608039474, but since this refers to 2.2.0.5 figure I'll note this here as well. Docker 2.2.0.5 stable has shipped which should fix a number of issues floating around.

**Comment by rabauss** [comment]
Unfortunately, the Docker problem is not solved for me with Version 2.2.0.5 and the Issue https://github.com/docker/for-win/issues/5530 is still open.
