### ISSUE TITLE
Anyone else got Blackfire.io working with Lando?

### ISSUE THREAD

**Issue by basepack** [lando/lando#2125]
Trying to get Blackfire.io working with Lando. 

I saw some PR's from 2018, which didn't make it in the end, to use Blackfire with Lando.

Anyone who got this working who want to share how?

**Comment by lochmueller** [comment]
Hey @basepack 

my latest changes... but not tested with most current releases.

install.sh
```#!/bin/bash

# Add blackfire gpg key
wget -q -O - https://packages.blackfire.io/gpg.key | apt-key add -
# Add blackfire repository
echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list

# Install blackfire-agent and gmp
apt-get update -y
apt-get install libgmp-dev blackfire-agent -y

# Configure and restart blackfire-agent
printf "%s\n" $BLACKFIRE_CLIENT_ID $BLACKFIRE_CLIENT_TOKEN | blackfire config
/etc/init.d/blackfire-agent restart

# Install blackfire probe
version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;")
curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version
tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp
mv /tmp/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so

# Enable blackfire probe
docker-php-ext-enable blackfire
```

.lando.yml
```services:
  appserver:
    build_as_root:
      - /app/config/install.sh
    run_as_root:
      - /etc/init.d/blackfire-agent restart
```

**Comment by basepack** [comment]
@lochmueller Many thanks! However I run into errors, where I think this is the causing one: `OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/app/config/install.sh\": stat /app/config/install.sh: no such file or directory": unknown`

**Comment by basepack** [comment]
Turns out, Lando does not use the .env variables set in my .env file. 

Also, the command `printf "%s\n" $BLACKFIRE_CLIENT_ID $BLACKFIRE_CLIENT_TOKEN | blackfire config` is changed into:
`- blackfire config --client-id=$BLACKFIRE_CLIENT_ID--client-token=$BLACKFIRE_CLIENT_TOKEN`

Where in my case: 
```
`- blackfire config --client-id=$BLACKFIRE_CLIENT_ID --client-token=$BLACKFIRE_CLIENT_TOKEN`
```
does not work. I have to put the real values in the place of the environment variables for some reason.

I do see them however when running `lando ssh -s appserver -c env`.

**Comment by lochmueller** [comment]
Hey @basepack 
Sorry about the path. Ther was /app/config/install.sh in my example. That means, the install.sh have to be in the config folder of your project. My problem was often, that it works after a build/rebuild but do not work after a few start/stop of the container.
Would be cool if we find a bulletproof solution for blackbird in PHP container.
Regards,
Tim

**Comment by neclimdul** [comment]
I took a different approach of adding these files to projects when I need to use blackfire. Quick to add and remove and pretty portable. 

Getting the php extension installed might still be a little tricky and require some build steps, I've got it included in my development container that I use so I don't have a hack. `kill -USR2 1` can be a killer tool if you get in a pinch and need to load an extension or change a setting while a container is running. https://stackoverflow.com/questions/37806188/how-to-restart-php-fpm-inside-a-docker-container

`.lando.local.yml`:
```
env_file:
  - .lando.env
services:
  blackfire:
    type: compose
    services:
      image: blackfire/blackfire
      command: blackfire-agent
````
`.lando.env`:
```
BLACKFIRE_CLIENT_ID=<GUID>
BLACKFIRE_CLIENT_TOKEN=<HASH>
BLACKFIRE_SERVER_ID=<GUID>
BLACKFIRE_SERVER_TOKEN=<HASH>
```
and this one line in a .ini extra file that's part of a project(uncomment and rebuild when you need it)
```
; uncomment this line and rebuild to enable blackfire traces.
;blackfire.agent_socket=tcp://blackfire:8707
```

Good luck!

**Comment by basepack** [comment]
@neclimdul That sounds great!

However one question, where do you put that .ini file? I struggle to get that part working.

**Comment by neclimdul** [comment]
as part of my `.lando.yml` I generally have something like this 
```
services:
  appserver:
    config:
      php: resources/fpm/lando.ini
```

**Comment by basepack** [comment]
@neclimdul Thanks for the insight! However is that within your project path (I cannot get this part working) where do you put this path under your project files?

So, say you have your project at `/projectX`, your lando file under `/projectX/.lando.yml`, do you then put that .ini file under `/projectX/resources/fpm/lando.ini`?

Maybe my Lando/Docker setup is not right configured, but I am still trying.

**Comment by tylerssn** [comment]
I updated my GIST this morning if helpful. It's an automated setup on `lando rebuild`:

https://gist.github.com/tylerssn/8923149702d4a796c5e103412c2370c3
