### ISSUE TITLE
Missing dev guide page

### ISSUE THREAD

**Issue by gitressa** [lando/lando#2131]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/contrib/how.html#committing-code

**Describe the change you'd like**
The link to the dev guide at https://docs.lando.dev/dev/started.html cannot be found.

**Comment by pirog** [comment]
@gitressa how did you get to https://docs.lando.dev/contrib/how.html? i dont even think this page is in the menu anymore.

**Comment by gitressa** [comment]
Great, thanks for fixing it! :+1:

**Comment by pirog** [comment]
removed and redirected, might take a bit to propagate. thanks for reporting
