### ISSUE TITLE
Pantheon recipe: Make it possible to pull code without specifying database or files 

### ISSUE THREAD

**Issue by hades200082** [lando/lando#2134]
As a pantheon site developer I'd like to be able to pull/push my code changes without needing to specify "none" for database and files every time.

e.g.

```
lando pull --code=dev
```

The above command should automatically assume `--database=none` and `--files=none`. Likewise for the `lando push` command.

This saves a lot of typing over the course of a project.

If you want to avoid changing this behaviour, how about a new flag such as...

```
lando pull --codeonly=dev
```

**Comment by pirog** [comment]
Use git?

**Comment by smutlord** [comment]
@hades200082 i can see the value in something like this. In the meantime id recommend checking out this: https://docs.lando.dev/config/pantheon.html#customizing-pantheon-tooling which may allow you to get the desired result

**Comment by hades200082** [comment]
Just because no-one has replied recently doesn't mean this doesn't still need doing.
