### ISSUE TITLE
How to access PHP logs in fpm/pantheon Lando apps?

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#2142]
Let's write a guide on how to `tail` the pantheon/fpm logs.

I think it is as easy as:

```bash
lando logs -s appserver -f
```

That seems to spit out the PHP errors when I create a syntax error or undefined function in my Pantheon app.

Let's turn it into a guide: https://docs.lando.dev/contrib/guides-intro.html

**Comment by nikitakhera85** [comment]
Guest Blog Post   Service
As a developer working on a SaaS platform using wildcard subdomains, I want to have https for my domain and sub-domain, so that I can work in parity with how the site actually operates.

https://guestpostingindia.com/
--
