### ISSUE TITLE
`lando pull` fails if you're on a branch that doesn't have a corresponding environment

### ISSUE THREAD

**Issue by ssteigen** [lando/lando#2153]
`v3.0.0-rrc.3` on Windows 10 Professional

If I have the `develop` branched checked out and perform `lando pull --code=none --database=none --files=live` from inside my site's directory, it validates that I haves access to the `develop` environment, because that is the branch I have checked out. The expected behavior is that it will validate access against the `live` environment, because that is where I am requesting to pull the files from.

**This behavior is problematic if I have a branch checked out that does not have a valid multidev instance associated with it.** 

Ex. If I create a new local branch called `feature-asdf` and attempt to pull the database and files from `live`, lando fails when validating that I have access to `feature-asdf` because the environment does not exist.

```
>$ lando pull --code=none --database=live --files=live
Attempting to login via terminus...
 [notice] Logging in via machine token.
Logged in as steigen@theinstitutes.org
Verifying that you have accesss to ti-west...
 ------------------ -------------------------------------------------------------------------------------
  ID                 9f521f67-f6a1-412f-8eb7-4740472843c3
  Name               ti-west
  Label              TI West
  Created            2018-11-15 14:37:11
  Framework          drupal8
  Region             us-central1
  Organization       c71e97b2-860a-4ac3-8aa3-987a2ff436e5
  Plan               Elite
  Max Multidevs      20
  Upstream           4c7176de-e079-eed1-154d-44d5a9945b65: https://github.com/pantheon-systems/empty.git
  Holder Type        organization
  Holder ID          c71e97b2-860a-4ac3-8aa3-987a2ff436e5
  Owner              fb96a5de-c6a4-43dd-bf35-865e91c293f2
  Is Frozen?         false
  Date Last Frozen   1970-01-01 00:00:00
 ------------------ -------------------------------------------------------------------------------------
Certificate will not expire
Cert is good!
Validating whether feature-asdf is a valid environment and that you have access to it
>$
```

`Validating whether feature-asdf is a valid environment and that you have access to it` is the part I believe is problematic. After this line, the tool just dies and returns me to my console without pulling the db or files.

Using `lando pull` with no arguments and selecting interactively yields the same behavior.

According to @dustinleblanc the following files are probably involved.
* https://github.com/lando/lando/blob/1213d3d4f97c35b9d39866088eb321c029397e9c/plugins/lando-pantheon/lib/pull.js
* https://github.com/lando/lando/blob/eb6b16e9315be69d195048d5aa0205364652f3ed/plugins/lando-pantheon/scripts/pull.sh

**Comment by uberhacker** [comment]
@ssteigen: What are you using for a terminal session in Windows?  Regular command prompt, Powershell or Git Bash?  I've noticed weird behavior with Git Bash.

**Comment by ssteigen** [comment]
@uberhacker I've done some experimenting and further isolated the issue. I updated the issue description.

**Comment by ssteigen** [comment]
I suspect that previously `lando pull` would validate that you had access to the site as a whole (in my case ti-west) rather than a specific environment.

I'd have to downgrade to check...

**Comment by pirog** [comment]
@ssteigen can definitely replicate now. Great report!

**Comment by pirog** [comment]
Alright merged into master and will be in next release! Thanks again @ssteigen
