### ISSUE TITLE
Typo `accesss` should be `access` 

### ISSUE THREAD

**Issue by ssteigen** [lando/lando#2156]
https://github.com/lando/lando/blob/1213d3d4f97c35b9d39866088eb321c029397e9c/plugins/lando-pantheon/scripts/auth.sh#L18

https://github.com/lando/lando/blob/8821449444f7c5bf77155ee2e99b3284cab61b3b/website/.vuepress/theme/components/SponsorshipTiers.vue#L44

`accesss` should be `access`

**Comment by pirog** [comment]
thanks! merged
