### ISSUE TITLE
Unable to run lando commands without sudo

### ISSUE THREAD

**Issue by jacob-morin** [lando/lando#2164]
System:
- Ubuntu 18.04
- Docker version 19.03.8
- docker-compose version 1.25.0
- lando v3.0.0-rrc.3

Issue:
Running lando commands as a non-superuser outputs nothing and does nothing.

Steps:
1. Installed docker from https://docs.docker.com/engine/install/
2. Installed lando v3.0.0-rrc.3 by downloading the .deb at https://github.com/lando/lando/releases/tag/v3.0.0-rrc.3 and running on my local software manager.
3. Tried to run the example from https://docs.lando.dev/basics/first-app.html#hello-world

Any lando commands I run from a non-superuser output nothing and don't appear to do anything. For example:
```
user@system:~/hello$ docker -v
Docker version 19.03.8, build afacb8b7f0
user@system:~/hello$ docker-compose -v
docker-compose version 1.25.0, build 0a186604
user@system:~/hello$ lando -v
user@system:~/hello$ lando --help
user@system:~/hello$ sudo lando -v
Lando should never ever ever be run as root...
   ___ __                          ______
  / (_) /_____   ___ _  _____ ____/ / / /
 / / /  '_/ -_) / -_) |/ / -_) __/_/_/_/ 
/_/_/_/\_\\__/  \__/|___/\__/_/ (_|_|_)  
                                          
```
`apt` confirms that I have lando installed, running `sudo apt list | grep lando` returns `lando/now 3.0.0-rrc.3 amd64 [installed,local]`

I have added myself to the `docker` group on my system and have rebooted multiple times since.

I thought this might be a permissions issue, so I checked the permissions of my local install. The entire install directory (/usr/share/lando) has permissions `rwxr-xr-x`. 

I would appreciate thoughts or suggestions about making this work on my system. Thanks!

**Comment by smutlord** [comment]
@jacob-morin recommend you upgrade to the latest lando, make sure you've followed the installation docs https://docs.lando.dev/basics/installation.html#linux including the caveats and if the issue persists then reopen this

for context, we run ALL of our functional tests against `Ubuntu 18.04` on CircleCI as non-root and do not experience this

**Comment by reduanmasud** [comment]
```sudo chown "$USER":"$USER" /home/"$USER"/.lando -R
sudo chmod g+rwx "$HOME/.lando" -R```

Now Run without ```sudo```. 
It works for me
