### ISSUE TITLE
Add a lando update command to update lando from cli

### ISSUE THREAD

**Issue by hades200082** [lando/lando#2168]
If you already have lando installed it could be faster to do cli based updates rather than requiring the whole installation package be downloaded again.

Allowing users to update or select their lando version via a command such as `lando update [--version="v3.0.0-rc2"] ` might encourage more people to update and would also allow you to prompt them to do so when they run commands in older versions.

**Comment by uberhacker** [comment]
Totally agree with you @hades200082.  A self-update command would be nice.

**Comment by pirog** [comment]
@hades200082  im closing this out in favor of the meta issue over here which seeks to bring a bunch of related tickets together so we can figure out a plan. would love to get your feedback
https://github.com/lando/lando/issues/2217
