### ISSUE TITLE
lando yarn install

### ISSUE THREAD

**Issue by yleal** [lando/lando#2171]
Best regards!

I have a problem installing yarn on lando.
I am installing OpenDialog on a doker with Lando, but in the set_up_od.sh installation process there is an instruction that says "lando yarn install", when it gets there the installation is interrupted because the command is not recognized by Lando.
https://github.com/opendialogai/opendialog/blob/develop/scripts/set_up_od.sh

Looking for the documentation, yarn can be installed as a global dependency but it doesn't work, or I'm doing it wrong.

Any comments would be helpful!

**Comment by pirog** [comment]
@yleal the best comment i can give us to ask the OpenDialog people as they probably know better how their stuff is supposed to work than we do

**Comment by specbeeravi** [comment]
I have installed lando.
Now how can add Lando Yarn?
