### ISSUE TITLE
'lando pull' progress display error

### ISSUE THREAD

**Issue by sdubois** [lando/lando#2178]
On macOS, when I run `lando pull` the output is not updating the progress, but rather is rendering a new line for every update. This seems to have only started after I upgraded to v3.0.0-rrc.3

![Screen Shot 2020-04-23 at 2 51 54 PM](https://user-images.githubusercontent.com/479460/80137957-1303bf00-8572-11ea-9ff8-a933ae9b1d37.png)

**Comment by pirog** [comment]
@sdubois should be fixed in the next release!
