### ISSUE TITLE
keys: false is not honoured

### ISSUE THREAD

**Issue by marklabrecque** [lando/lando#2186]
Just upgraded to v3.0.0-rrc.5 and started seeing the "You have a lot of keys!" warning. I looked at the docs that said you could stop sharing your ~/.ssh folder by adding a top-level `keys: false` in a projects .lando.yml, but this was ignored in my case. Am I doing something wrong, or is this supposed to work this way?

**Comment by pirog** [comment]
@marklabrecque i think the warning shows up regardless of the `keys` setting, we should change that.

if you `lando logs -s SERVICEWITHKEYS` you should be able to see wat keys get loaded

**Comment by marklabrecque** [comment]
Yeah I was able to sequester some of my extra, not-oft used keys outside of ~/.ssh to fix the issue for now. For what it's worth I'm on Ubuntu 19.10 when I see this issue.

Thanks! Keep up the great work with Lando! :D

**Comment by pirog** [comment]
thanks @marklabrecque! This should be fixed in rrc.6 which should be up in a bit!
