### ISSUE TITLE
PATH_TRANSLATED is not set correctly

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2192]
**Versions**
*v3.0.0-rrc.5 on Windows 10 Professional*

**lando.yml**
```yml
name: typo3
recipe: lemp
config:
  webroot: public
  php: '7.4'
  xdebug: true
  database: mysql
```

I believe `$_SERVER['PATH_TRANSLATED']` should give the absolute path to the PHP script but instead it only holds part of the path, so instead of `/app/public/directory/index.php` it only shows `/app/public`. It seems the path is truncated after the public path.

Could it be that Nginx, configured with `fastcgi_param PATH_TRANSLATED         $document_root$fastcgi_path_info;` does not set or substitute `$fastcgi_path_info` correctly? May it be empty?

**Comment by pirog** [comment]
@dustinleblanc ^

**Comment by dustinleblanc** [comment]
We set the value here: https://github.com/lando/lando/blob/master/plugins/lando-services/services/nginx/fastcgi_params#L9 so my guess is that yep, the value of $fastcgi_path_info might be wrong, but I am not sure where that value comes from

**Comment by pirog** [comment]
AFAIK it comes directly from nginx and https://github.com/lando/lando/blob/master/plugins/lando-services/services/nginx/fastcgi_params#L9 is taken directly from what nginx recommends as the default

**Comment by dustinleblanc** [comment]
Reading about it some more, looks like it gets determined by another value: http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info

from what others have said, there is some way it gets messed up if you set the values in different places maybe? https://stackoverflow.com/questions/20848899/nginx-phpfpm-path-info-always-empty

**Comment by dustinleblanc** [comment]
Looks like we set `fastcgi_split_path_info ^(.+?\.php)(\|/.*)$;` in a bunch of our recipes, but given @thasmo is rolling with `lemp` and we don't set it there, that might be the root of the issue.

https://github.com/lando/lando/search?q=fastcgi_split_path_info&unscoped_q=fastcgi_split_path_info

**Comment by thasmo** [comment]
After some research I believe the reason may be that it's not set in a `location` section. I was not able to find the relevant Nginx vhost/server configuration where, inside a `location` block, this should be set.

Is it maybe missing here?
https://github.com/lando/lando/blob/6a37c0912104861684be3346fa60de76abf38cbc/plugins/lando-services/services/php/default-ssl.conf.tpl

**Comment by dustinleblanc** [comment]
@thasmo you actually are probably right, see the post right before yours

**Comment by pirog** [comment]
I think maybe the question here is do we think its reasonable, wise, reliable, etc for Lando to set a default for this when the user is using a more generic recipe like LAMP/LEMP?

It makes sense to me that we could do this for things like Drupal, WordPress that likely have a single agreed upon implementation but i'm not sure there is something universally true for all LAMP/LEMP stacks. It would be sweet to get guidance on that.

**Comment by thasmo** [comment]
I'd argue that that's a PHP related environment variable which should be set anyway.
https://www.php.net/manual/en/reserved.variables.server.php

**Comment by pirog** [comment]
I'm not sure how you get that to conclusion based on the link you just shared. The second sentence of the docs is literally

>  The entries in this array are created by the web server. There is no guarantee that every web server will provide any of these; servers may omit some, or provide others not listed here. 

That seems pretty explicit about these being SERVER variables that PHP may or may not inherit and NOT that these are php ENV variables that MUST exist under all circumstances. Further down it even says that apache doesnt even set this by default in some situation.

I'm still not sure what the solution is here but if there is one then im pretty sure its something that the webserver eg nginx or apache and not php itself

**Comment by thasmo** [comment]
I guess different web applications use different ways to determine the absolute path to the currently executed script. [TYPO3](https://github.com/TYPO3/TYPO3.CMS/blob/e67853b5c4b2afa0f68675e3d2f7360f60669392/typo3/sysext/core/Classes/Core/SystemEnvironmentBuilder.php#L308-L315) uses `PATH_TRANSLATED` for PHP running via CGI but falls back to `SCRIPT_FILENAME` if `PATH_TRANSLATED` is not set. [Symfony](https://github.com/symfony/symfony/search?q=SCRIPT_FILENAME&unscoped_q=SCRIPT_FILENAME) seems to use `SCRIPT_FILENAME` exclusively, [Drupal](https://github.com/drupal/drupal/blob/16726375965ae2dddc600582467cc8fc55b67486/core/lib/Drupal/Core/DrupalKernel.php#L389) seems to something similar.

I'm not sure about how the CGI specification defines this.
> $_SERVER is an array containing information such as headers, paths, and script locations. The entries in this array are created by the web server. There is no guarantee that every web server will provide any of these; servers may omit some, or provide others not listed here. That said, a large number of these variables are accounted for in the » CGI/1.1 specification, so you should be able to expect those.

What I understand is that `PATH_TRANSLATED` should be set to the absolute path of the currently executed script, or it should not be set at all.

At the moment it is set to an invalid value, which causes issues (at least in my case using TYPO3).

**Comment by pirog** [comment]
So, to clarify the steps i think we need to take here, i think what we need to determine is

1. Why is the default setting of `PATH_INFO` and `PATH_TRANSLATED` not producing the result we desire? Since we are using the recommended default setting provided by nginx are we doing something wrong or is this expected and its assumed some other configuration eg in a `location` block or elsewhere be provided?
2. If additional configuration is required is this something that Lando can set globally in a reliable way or is it something that needs to be set on a per-framework/recipe sort of level? Eg if a `location` block is required to set this correctly then presumably that would be fairly framework specific?

These are questions i definitely do not know the answers too and Googling has not produced anything that seems actionable with a large degree of confidence.

**Comment by pirog** [comment]
@dustinleblanc do you have an opinion on ^

Should we just include something like the below for our default lamp/lemp recipe?
```
fastcgi_split_path_info ^(.+?\.php)(/.*)$;
```

https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#connecting-nginx-to-php-fpm

**Comment by dustinleblanc** [comment]
Yeah it seems safe to me to always assume this, not sure why some l*mp recipe would not want it

**Comment by pirog** [comment]
Ok, i was able to replicate this using both a php service with `via: nginx` and the default `lemp` recipe. https://github.com/lando/lando/commit/0d81932fad150dd2432604c2e1992982d135d715 should resolve this

**Comment by pirog** [comment]
Alright, this should be fixed in the next release!

**Comment by thasmo** [comment]
@pirog I've installed the new version and I noticed that the line `fastcgi_split_path_info ^(.+?\.php)(/.*)$;` is present in the nginx vhost configuration, but `$fastcgi_path_info` still seems to be empty which results in `PATHINFO` being empty and `PATH_TRANSLATED` being truncated.

My configuration is mentioned above; alternatively I tried this (PHP 7.2, no xdebug) - but without success:
```
name: typo3
recipe: lemp
config:
  webroot: public
  php: '7.2'
  database: mysql
```

I can't figure out why this won't work.

**Comment by pirog** [comment]
We are testing this over here
https://github.com/lando/lando/tree/master/examples/php

So I’d use that as a starting point. As far as I can tell this now works as
expected though

**Comment by dustinleblanc** [comment]
Might be worth making sure a rebuild has occurred and that no custom config files are hanging out

**Comment by thasmo** [comment]
@pirog FYI, tested this with the latest Lando version and `PATH_TRANSLATED` is set to `/app/public` when using the `lemp` recipe, when it actually should be set to `/app/public/typo3/index.php`, which would be the actual correct path to the script.
