### ISSUE TITLE
Event lando db-export fails

### ISSUE THREAD

**Issue by michaelrimbach** [lando/lando#2195]
Hi,

Im trying to create a db export after each "post-start" event:

events:
  post-start:
    - echo "Exporting Database..."
    - appserver: lando db-export

But im getting the following error:

OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"lando\": executable file not found in $PATH": unknown
warn: One of your event commands has failed! This may prevent your app from working correctly
error: Event failed with code undefined and message

Same if I try it without "appserver:". 
Im using Lando v3.0.0-rc.23.

Would be really nice if someone can help me out.

Thanks, Michael

**Comment by pirog** [comment]
This is the expected behavior. Event commands run inside of services and lando is a tool that exists on your host.
