### ISSUE TITLE
Guide for Node in a PHP container

### ISSUE THREAD

**Issue by ccjjmartin** [lando/lando#2196]
Please complete the following:

**Link to the page that needs to be updated or changed.**
No guide exists for this yet

**Describe the change you'd like**
Add a guide on how to setup node in a PHP container

**Comment by smutlord** [comment]
https://docs.lando.dev/guides/installing-node-in-your-lando-php-service.html

**Comment by ccjjmartin** [comment]
@smutlord Thank you for creating this.  Your method looks great!
