### ISSUE TITLE
Old version of MariaDB prevents Drupal 9 install with Pantheon recipe

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2197]
**Is your feature request related to a problem? Please describe.**

I'm trying to install Drupal 9 for testing purposes using Pantheon and the Pantheon Build Tools.  First I created a site in Drupal 8 and then edited the composer.json to install Drupal 9.  I then wiped the database and tried to install Drupal 9 in lando, which gave me this error:

> The database server version 10.1.44-MariaDB is less than the minimum required version 10.3.7.

**Describe the solution you'd like**
Use MariaDB 10.3+ as required by Drupal 9 for the pantheon recipe.  According to the [Lando docs on MariaDB](https://docs.lando.dev/config/mariadb.html), 10.3 is already the default for non-Pantheon projects.

**Comment by ptmkenny** [comment]
Workaround for now in .lando.yml:

```
services:
  database:
    type: mariadb:10.3
```

**Comment by pirog** [comment]
@ptmkenny going to close this in favor of #2371 which should address this concern
