### ISSUE TITLE
solrcore.properties.old created during Lando start

### ISSUE THREAD

**Issue by gitressa** [lando/lando#2198]
Mostly just to share a little oddity: I had a "left over" `solrcore.properties` file I had forgotten to delete. It seems like Lando copies it into `solrcore.properties.old` and edits `solrcore.properties` during Lando start. I was puzzled to see `git clone my_repo && git status` giving `nothing to commit`, and then changing into this, after running `lando start`:

```
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified: config/solr-conf/7.x/conf/solrcore.properties

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    config/solr-conf/7.x/conf/solrcore.properties.old
    config/sync/.htaccess

no changes added to commit (use "git add" and/or "git commit -a")
```

Cleaning up and removing the redundant `solrcore.properties` file solved it.

**Comment by pirog** [comment]
@gitressa going to close this out just for housekeeping but thanks for dropping the note!

**Comment by gitressa** [comment]
I didn't fully understand what happened back then, and now think this a bug, not so much an oddity.

It looks like Lando renames the original `solrcore.properties` to `solrcore.properties.old`, makes a new `solrcore.properties` but with a new the path to Solr which is `solr.install.dir=/opt/solr` ...

Original `solrcore.properties`, renamed to `solrcore.properties.old` by Lando:
```
solr.replication.master=false
solr.replication.slave=false
solr.replication.pollInterval=00:00:60
solr.replication.masterUrl=http://localhost:8983/solr
solr.replication.confFiles=schema.xml,schema_extra_types.xml,schema_extra_fields.xml,elevate.xml,stopwords_en.txt,synonyms_en.txt,protwords_en.txt,accents_en.txt,stopwords_und.txt,synonyms_und.txt,protwords_und.txt,accents_und.txt
solr.mlt.timeAllowed=2000
solr.selectSearchHandler.timeAllowed=-1
solr.autoCommit.MaxDocs=-1
solr.autoCommit.MaxTime=15000
solr.autoSoftCommit.MaxDocs=-1
solr.autoSoftCommit.MaxTime=-1
solr.install.dir=/solr/server/solr
solr.luceneMatchVersion=7.0
```

New `solrcore.properties` file generated by Lando, with added `solr.install.dir=/opt/solr`:
```
solr.replication.master=false
solr.replication.slave=false
solr.replication.pollInterval=00:00:60
solr.replication.masterUrl=http://localhost:8983/solr
solr.replication.confFiles=schema.xml,schema_extra_types.xml,schema_extra_fields.xml,elevate.xml,stopwords_en.txt,synonyms_en.txt,protwords_en.txt,accents_en.txt,stopwords_und.txt,synonyms_und.txt,protwords_und.txt,accents_und.txt
solr.mlt.timeAllowed=2000
solr.selectSearchHandler.timeAllowed=-1
solr.autoCommit.MaxDocs=-1
solr.autoCommit.MaxTime=15000
solr.autoSoftCommit.MaxDocs=-1
solr.autoSoftCommit.MaxTime=-1
solr.install.dir=/solr/server/solr
solr.luceneMatchVersion=7.0
solr.install.dir=/opt/solr
```

Lando and Search API Solr has had a discussion (see #1319), but the problem is that with this change a wrong path to Solr can get deployed on the production server, which is unfortunate ...

I am not sure what a solution would be, until Lando and Search API Solr reach an agreement ... commit the intended original `solrcore.properties`, and then remember in the future to not commit the new `solrcore.properties` created by Lando?

**Comment by gitressa** [comment]
On the Search API Solr Server configuration page, under "Advanced server configuration" > "solr.install.dir" field it says that:

> [...] Modern Solr installations should set that virtual machine option correctly in their start script by themselves. In this case this field should be left empty!

... and it does work without defining the path in Lando. So that probably is the way forward, if the production server allows it.
