### ISSUE TITLE
Connect to DB from external

### ISSUE THREAD

**Issue by couloir007** [lando/lando#2199]
Generally these questions should end up as guides
https://docs.lando.dev/contrib/guides-intro.html#what-is-a-guide

I'm migrating from D7 to D8 and had everything working fine until recently after upgrading Lando. I have the current D7 site running in one instance of Lando and the new D8 in another. I need to connect from to the other and using "lando ssh -c "env" | grep LANDO_HOST_IP" I was able to get the IP of the D7 site.

My D7 has this.

services:
  database:
    portforward: 3307

On the D8 side in the settings.php file.

`$databases['migrate']['default'] = array (
  'database' => 'drupal7',
  'username' => 'drupal7',
  'password' => 'drupal7',
  'host' => '192.168.1.141',
  'port' => '3307',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);`

I test the connection with:

mysql -h 192.168.1.141 -p 3307 -u drupal7 -pdrupal7

and I get ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.1.141' (111)

Has something changed? There is not a lot of info out there on how to connect to a lando db externally.

Thanks!
Sean

**Comment by pirog** [comment]
There is literally a guide that is called "Accessing Your Services Externally"
https://docs.lando.dev/guides/external-access.html#checking-connection-info

However, you do not want to be accessing services across apps in this way. Check out the networking documentation, in particular the `.internal` hostnames which allow you to connect to services across apps
https://docs.lando.dev/config/networking.html#networking
