### ISSUE TITLE
How to force HTTPS in a Lando environment

### ISSUE THREAD

**Issue by north-krimsly-hp** [lando/lando#2202]
Greetings all,

I have a working Lando environment using the Drupal 7 recipe. But, it will work with either http:// or https://. I want to force it to always use https://. What is the best way to configure Lando to require https:// ?
Thanks

**Comment by web-assistant** [comment]
I've tried doing this in htaccess but get errors saying "The page isn't redirecting properly" so would also like to know how to do it in lando config

**Comment by north-krimsly-hp** [comment]
Anyone have thoughts on how to force https:// in Lando?

**Comment by serundeputy** [comment]
For a drupal app you can force it at the application level https://www.drupal.org/https-information#settings-php-redirect if you just need that for Lando you could put it into a `settings.local.php` or a `settings.lando.php` file and have your `settings.php` file check if you are in a Lando environment and load the file you need.

You could also load custom apache or nginx config https://docs.lando.dev/config/apache.html#configuration

If those work it might be nice to write up a [Guide](https://docs.lando.dev/contrib/guides-intro.html) for it so others can leverage the solution.

**Comment by web-assistant** [comment]
I forced https at application level as shown in [https://www.drupal.org/https-information#settings-php-redirect ](url) but the problem for me is it breaks my functionality when using `chr_curl_http_request` (or `drupal_http_request`) when a Lando site communicates with another Lando site.

**Comment by davereid-pfg** [comment]
I can confirm that this snippet also doesn't work if a CURL or drupal_http_request() is used from another Lando container.

**Comment by zdenekgebauer** [comment]
This works for me (lando 3.0.26):
```
RewriteCond %{ENV:HTTPS} !^.*on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
