### ISSUE TITLE
LandoInstaller.pkg error "OS X 10.8 or later" is outdated

### ISSUE THREAD

**Issue by phillipadsmith** [lando/lando#2203]
**Tell us about your setup**
v3.0.0-rrc.6 on OSX 10.13.6

**Tell us about your `.lando.yml`**

Haven't gotten that far yet

**Tell us about the command you were running**

Double-clicking on the ```LandoInstaller.pkg```

**Tell us about the error you got**

![Screenshot_2020-04-30__1_01_PM](https://user-images.githubusercontent.com/34128/80753962-11db1080-8ae3-11ea-926b-804157c72fc1.jpg)

**Tell us generally about your bug**

I understood before trying to install that the minimum requirement for Lando was OSX 10.14 or higher. However, not wanting to screw up my laptop, I was hoping to install it on 10.13.6. 

So, no surprise that it didn't install, but the error message reports that I need "10.8 or later," which I most certainly am running (10.13.6).

Anyway, that's the bug I'm reporting.

And, if there's work-around to install this on 10.13 -- where Docker and everything else work fine -- I'd be grateful to know it. :)

**Comment by pirog** [comment]
@phillipadsmith weird, looks like 10.13 is the lowest version docker supports so lando should be using that too. going to roll a hotfix release with changes for this.

also, for people who run into a similar problem, you can always install lando from source if you want to try it on an supported version

**Comment by pirog** [comment]
ok this should be in the next release

**Comment by phillipadsmith** [comment]
👋 Hey there @pirog: Thanks for the suggestion of building from source -- that's helpful. And I'll try the next release as soon as it's out the door 👍
