### ISSUE TITLE
Improve DevOps

### ISSUE THREAD

**Issue by pirog** [lando/lando#2216]
Now that we have committed to a stable we need to improve our DevOps to help power the next level of improvements. Specifically this means we need

- [ ] To create a dedicated `edge` branch from which we can use to cut all our future `edge` releases
- [ ] To create a separate `edge` deploy step or a more sophisticated current deploy step in Travis so we can also push `edge` flavored aliases like `lando-edge.dmg` and `lando-latest-dev-edge.dmg`
- [ ] To also push up CLI only build artifacts to S3 so they can be ingested by update scripts and other package managers
- [ ] To version our documentation so it is at least toggleable between `edge` and `stable`
- [ ] To automatically set the github release to draft/prerelease as needed depending on the release channel

**Comment by pirog** [comment]
Note: doc versioning may be possible using:
https://www.npmjs.com/package/vuepress-plugin-versioning
https://docs.platform.sh/configuration/app/source-operations.html

**Comment by allanlaal** [comment]
unstale! #2217 still depends on this
