### ISSUE TITLE
Improve install and update experience

### ISSUE THREAD

**Issue by pirog** [lando/lando#2217]
Now that we have a stable release we need to turn our eye towards improving the installation and update DX so that we can 

1. Reduce barriers and improve first touch
2. Provide as many on ramps as possible
2. Encourage updating 

Currently Lando packages all its dependencies into a one-click installer package. This is great for the first installation, especially for a new user who doesnt understand the dependency tree. However, asking users to continue this flow on updates becomes a bit arduous especially if the user is not in the US and gets slow download speeds from GitHub. A GUI one click installer is also not the ideal pathway for power users who might want to use tools like `brew` or `chocolatey`. On a high level i think that lando needs to do the folllowing

1. Continue to provide installers with ALL dependencies as the OFFICIALLY recommended  _installation_ pathway.
2. Provide a secondary download link of the above (maybe the S3 version?) somewhere else (maybe the lando site?) so there is a faster option for downlaod
3. Once the user has installed lando there needs to be an easy update mechanism. A self-update command will probably not working given the architecture but we could at least provide the user with a one liner or utility script of some kind. This would _only_ update the lando CLI and not require ALL the dependencies be reinstalled. This is probably OK to do now that we have better Docker version dep checking. 
4. Provide more ways to get and manage lando eg `snap`, `brew`, `cholotaey` etc so power users can do their thang as well.

Note that we need to complete most of #2216 before these suggestions are actionable.

See the related and now closed issues that helped spawn this ticket
* #2050 
* #2169 
* #2050 
* #2109 
* #2168

**Comment by sebastienserre** [comment]
In Ubuntu/Debian world, I really prefer deb repo as @mishac spoke about in #2050 as it's really install only the main software and not all depedencies as Snap package do.
Pros for Snap package is embedding all depedencies and beeing available in all other Linux Distros (I think, not sure)

**Comment by gitressa** [comment]
I am using Ubuntu, and also not a Snap fan, and would prefer a deb repo.

**Comment by uberhacker** [comment]
I have to say I disagree with 1.  It would be a better approach if the release only included the Lando specific files and the installer was smart enough to detect if the supported Docker Desktop is currently installed and continue with the install or upgrade.  If Docker Desktop isn't installed, it should then go ahead and download the supported version and configure as necessary.  This could also be true for Linux installs.  You don't need to bundle Docker but it would be helpful if the installer was intelligent enough to download and configure for you, if necessary.  I agree it would be a challenge with all the different Linux distros but definitely a worthwhile effort to help gain more traction with new and seasoned users alike.  The releases page would then only need one installer for each platform.  I'm not totally convinced a self-update command is not possible also.

**Comment by pirog** [comment]
I'm curious to know in what way you think that is better. Because in my mind this would definitely be:

1. A _lot_ more work to implement
2. More moving parts (eg probably less reliable/more brittle)
3. Able to break at any point if Docker changes their download links or versioning
4. Harder to maintain (keeping up with Linux distros, which weve tried to do in the past, is not for the faint of heart)

To me the one key benefit here is just having reduced package sizes. This is important _only_ because some users see the large package size and "get scared". I think this is part of the reason why 2 and 4 in https://github.com/lando/lando/issues/2217#issue-612324079 are suggested. 

For 2 you arent going to see the package size beforehand and its likely going to download fast. For 4 it seems like we could just have a notice on the releases page like "Look for a smaller package? Try these alternate install methods."

It's also worth pointing out that i think 3 from https://github.com/lando/lando/issues/2217#issue-612324079 is really the focus/important improvement here.

**Comment by uberhacker** [comment]
Definitely agree with 1. and I fully expect it to be a challenge.  Not sure how 2. is much different than it is now.  You can still choose not to install Docker Desktop and run the risk of breaking everything with an unsupported version.  3. is not an issue if you pin the supported version which is what I would expect anyway.  4. is a challenge, for sure, but would be well worth the effort.

**Comment by pirog** [comment]
2. is significantly different than now which is why 1. is a thing. The risk is with the installer being less stable not the subsequent install of Lando. There are way more things that can go wrong when you need for the installer to do a version check, download something on the fly and then _probably_ do a scripted installation of the download instead of using what the installer software generally uses to install things.

The point of 3 is that even if you were to do _all of that ^_ there is nothing that is stopping Docker from changing the version scheme or the download link, which is to say you can only pin to something that exists. If you package everything together _you control_ what you are pinning to, if you dont then you are putting your trust into someone else not changing something. 

If they do change those things, which they have done in the past, the worst case scenario for the packaged version is it fails before it can be deployed, you fix it, and then you deploy the package. The worst case scenario in the non-packaged model is that the installer fails when the user is trying to get started.

**Comment by ChrisWiegman** [comment]
I've actually tackled this very problem rather recently. I was one of two on the DevKit project by WP Engine which was, essentially, a WordPress-centric alternative to Lando written in GoLang. That said, at least from the Linux side, here's where we were successful with largely the same dependencies (Docker/Compose).

For Linux we spun up an S3 bucket and used it as an APT repo for distributions that could use .deb files.

For Mac and Linux we created a brew tab so the CLI app could be installed with `brew install wpe-cli`. 

This differs from the existing, unofficial, approach where Lando is a cask as casks are intended for Mac GUI apps and don't work on Linux. Making it a normal install follows Homebrew's own guidelines and allows for the install with a notice on how to install Docker depending on OS. While we had plenty of support calls, dependencies were never one of them.

If I can help at all with setups here, please let me know. In our case, all of our release was handled via CI in Jenkins including release tagging, updating the homebrew tab, etc.

**Comment by GuyPaddock** [comment]
Would it be a possibility to provide a WSL variant of Lando that just installs a _dummy_ `docker-ce` package that satisfies the hard dependency? That way, devs who already have Docker on the host machine would just be instructed to install that, and all will be well when it comes to packages like Lando that require the dep.

**Comment by pirog** [comment]
Not sure if that is possible but regardless it's not something we plan to do. That said, Lando 4 will be designed in a way that alleviates this concern so you should be good.

**Comment by chrishappy** [comment]
Getting the update message below and looking for a bash command line I can just run to update lando...

```
  __  __        __     __        ___            _ __     __   __    ______
 / / / /__  ___/ /__ _/ /____   / _ |_  _____ _(_) /__ _/ /  / /__ / / / /
/ /_/ / _ \/ _  / _ `/ __/ -_) / __ | |/ / _ `/ / / _ `/ _ \/ / -_)_/_/_/ 
\____/ .__/\_,_/\_,_/\__/\__/ /_/ |_|___/\_,_/_/_/\_,_/_.__/_/\__(_|_|_)  
    /_/                                                                   

Updating helps us provide the best support and saves us tons of time

Use the link below to get the latest and greatest
https://github.com/lando/lando/releases/tag/v3.21.0-beta.1

Lando is FREE and OPEN SOURCE software that relies on contributions from developers like you!
If you like Lando then help us spend more time making, updating and supporting it by contributing at the link below
https://github.com/sponsors/lando

If you would like to customize the behavior of this message then check out:
https://docs.lando.dev/config/releases.html
```

**Comment by AaronFeledy** [comment]
v3.21.0 ships with a `lando update` command that will update Lando.

**Comment by J-Trudell** [comment]
v3.20.4 ships with `lando update` command that doesn't do anything.
