### ISSUE TITLE
Is release v3.0.0 a stable release?

### ISSUE THREAD

**Issue by tanc** [lando/lando#2222]
Just noticed version 3.0.0 was added as a release a few hours ago but it is marked as `Pre-release` on the releases page, is it in fact a stable release and should be marked as `Latest-release`?
Also... CONGRATULATIONS!!!
![2020-05-05_09-50](https://user-images.githubusercontent.com/76320/81045358-51747480-8eb6-11ea-8eee-083a0e515d2f.png)

**Comment by tormi** [comment]
https://devwithlando.slack.com/archives/C2XBSHX8R/p1588600724005100

**Comment by pirog** [comment]
im guessing we will probably switch it from edge to stable next monday unless there are any serious issues reporting before then
