### ISSUE TITLE
Can't update to v3.0.0 on Linux Mint

### ISSUE THREAD

**Issue by jcmartinez** [lando/lando#2224]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Operating System: Linux Mint 19.2
Kernel: Linux 5.3.0-51-generic
Architecture: x86-64

lando version
v3.0.0-rrc.4

**Tell us more**

I downloaded https://github.com/lando/lando/releases/download/v3.0.0/lando-v3.0.0.deb

When I double click the file lando-v3.0.0.deb to try to update, I get the following message:

Error: A later version is already installed.

![Screenshot from 2020-05-05 15-34-42](https://user-images.githubusercontent.com/746915/81073807-784b9e80-8ee8-11ea-9c7e-fe4741f019fa.png)

Could better documentation have prevented this issue? if so what should we change?

Not necessarily.

Does this bug prevent you from using lando?

No, only prevented me me from updating.

**Comment by pirog** [comment]
Not sure what we can do about that TBH. Try using the CLI install method https://docs.lando.dev/basics/installation.html#install-via-cli

**Comment by BWPanda** [comment]
I had the same problem on Mint 19.3, so as per @pirog's suggestion I tried installing via the terminal. Instead of `wget`-ing the stable release (since v3.0.0 is currently tagged as an 'edge' release), I just ran `sudo dpkg -i lando-v3.0.0.deb`. I got `dpkg: warning: downgrading lando from 3.0.0-rrc.1 to 3.0.0` and `Unpacking lando (3.0.0) over (3.0.0-rrc.1) ...` but otherwise it went fine and now I have Lando v3.0.0 running.

**Comment by gitressa** [comment]
I just used the [Debian install commands](https://docs.lando.dev/basics/installation.html#debian) to upgrade from `3.0.0-rrc.6` to the latest version `3.0.0` on Ubuntu 18 with no problems.

It does say "downgrading", so it seems like Linux interprets `3.0.0-rrc.6` as newer than the latest version `3.0.0`.

```
$ wget https://files.devwithlando.io/lando-stable.deb
$ sudo dpkg -i lando-stable.deb 
dpkg: warning: downgrading lando from 3.0.0-rrc.6 to 3.0.0
...
Unpacking lando (3.0.0) over (3.0.0-rrc.6) ...
Setting up lando (3.0.0) ...
...
$ lando version
v3.0.0
```

**Comment by jcmartinez** [comment]
I was able to upgrade using the method above. Thank you very much for the tip!

I did get the downgrading warning; which makes me think that the way the versions are being named isn't what Linux (in my case Mint) expects. I'm not an expert on this. Perhaps, someone with more knowledge could shine some light.

Keeping the version naming the way it is, could keep some folks that use the GUI from upgrading.

**Comment by gitressa** [comment]
Great, you're welcome @jcmartinez! And I do think it's a bug that Debian/Ubuntu/Mint sees `3.0.0` as an older version than `3.0.0-rrc.6`, since it can cause problems like the one you ran into, but also the confusing `downgrading` warning message in the command line.

**Comment by pirog** [comment]
Since we are out of prerelease and there isn’t anything we can do about
versions that already exist this is something we won’t, and can’t, fix.

The good news is that I’m guessing there will be no confusion for package
managers once 3.0.1 is released

**Comment by gitressa** [comment]
Thanks for clarifying @pirog. You are probably right, that going forward, the next version will be understood as such by Debian/Ubuntu/Mint systems.

**Comment by gitressa** [comment]
I just upgraded from Lando 3.0.0 to 3.0.1, and it went smoothly:

```
$ wget https://files.devwithlando.io/lando-stable.deb

$ sudo dpkg -i lando-stable.deb
(Reading database ... 338477 files and directories currently installed.)
Preparing to unpack lando-stable.deb ...
Unpacking lando (3.0.1) over (3.0.0) ...
Setting up lando (3.0.1) ...

$ lando version
v3.0.1
```

**Comment by BWPanda** [comment]
I installed the v3.0.1 .deb via the GUI in Mint and it worked fine with no problems. I'd say this issue can be closed now :slightly_smiling_face:
