### ISSUE TITLE
Linux 'DMG' installation instructions

### ISSUE THREAD

**Issue by BWPanda** [lando/lando#2225]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/installation.html#install-dmg-via-direct-download-recommended-2

**Describe the change you'd like**
The first heading under the Linux installation instructions refers to 'DMG'. I don't know what that is, though from the looks of it it's a Mac-specific thing and this was copied and pasted from the Mac instructions but not updated for Linux...

**Comment by pirog** [comment]
good catch @BWPanda
