### ISSUE TITLE
[v3.0.1] Windows 10 cannot execute bash shell script

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#2235]
Apparently, Windows 10 has trouble executing a bash shell script in any "shell" environment.  For example, I receive an error during `lando rebuild -y` as shown below:
```bash
/bin/sh: 1: /app/lando/scripts/build.sh: not found
ERROR ==> /bin/sh: 1: /app/lando/scripts/build.sh: not found
```
My simple build.sh script is shown below:
```bash
#!/bin/bash
cp /app/lando/wp-config.php /app/
```
This script is executable both outside and inside the container as shown below:
```bash
~/projects/mysite/lando/scripts (develop)
$ ls -la
total 19
drwxr-xr-x 1 ed 197609    0 May  8 08:02 ./
drwxr-xr-x 1 ed 197609    0 May  8 08:02 ../
-rwxr-xr-x 1 ed 197609   48 May  8 08:02 build.sh*
~/projects/mysite (develop)
$ lando ssh
www-data@55a1d7e446d1:/app$ cd lando/scripts/
www-data@55a1d7e446d1:/app/lando/scripts$ ls -la
total 0
drwxrwxrwx 1 root root 4096 May  8 13:02 .
drwxrwxrwx 1 root root    0 May  8 13:02 ..
-rwxr-xr-x 1 root root   48 May  8 13:02 build.sh
```
The build script is called from my `.lando.yml` below:
```yaml
name: mysite
recipe: wordpress
config:
  webroot: .
  php: 7.2
services:
  appserver:
    build:
      - /app/lando/scripts/build.sh
```
This error is reproduceable in PowerShell, Git Bash, Cmder and the normal command prompt cmd.exe.  This same exact configuration works fine in Linux.
System specs below:
```bash
$ lando version
v3.0.1
$ php -v
PHP 7.3.10 (cli) (built: Sep 24 2019 11:58:16) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
$ composer -V
Composer version 1.10.5 2020-04-10 11:44:22
$ docker -v
Docker version 19.03.8, build afacb8b
$ docker-compose -v
docker-compose version 1.25.4, build 8d51620a
```
![windows-specs](https://user-images.githubusercontent.com/387945/81479290-f14c3e00-91e7-11ea-8f70-10c709b72ba0.png)
![docker-desktop](https://user-images.githubusercontent.com/387945/81479408-98c97080-91e8-11ea-8b7a-627b806ccbef.png)

**Comment by smutlord** [comment]
@uberhacker i was able to repro this on `master` with Docker Desktop 2.3.0.2 although based on my findings i dont thing those things are relevant. 

Steps to replicate for me were

1. Installed Docker Desktop 2.3.02
2. Using Lando, installed from source at commit https://github.com/lando/lando/commit/659cd45610dbf56b0981ca8b70449ab3c7c319bb
3. Initialized the `wordpress` example repo
4. Modified its `.lando.yml` to include the same details as above
5. Created similar `build.sh` script
6. `lando start`

When i drilled down into things i got this:

```bash
lando ssh
cd /app/lando/scripts
./build.sh

> bash: ./build.sh: /bin/sh^M: bad interpreter: No such file or directory
```

Right away this tells me i have a line ending problem. To resolve I:

1. Opened `build.sh` in my text editor (Sublime Text 3)
2. In the ST3 menu `View -> Line Endings -> Unix`
3. Save the file
4. `lando rebuild`

Error did not occur.

**Comment by pirog** [comment]
Nice! Thanks @smutlord.

That confirms what i suspected especially after having talked to @uberhacker for a bit about it. I'm not sure if this is something Lando can handle, might be better as docs somewhere. Open to other suggestions.

**Comment by uberhacker** [comment]
Yes, nice sleuthing @smutlord!  I imagine this has something to with git checkout to CRLF instead of keeping the LF format.  There is also a dos2unix command I can try.  I will report back.

**Comment by smutlord** [comment]
@uberhacker it might, the thing that is interesting to note here, and probably why @pirog could not replicate is that all of landos internal scripts automatically force `LF` so they all run fine, but user added scripts that end up `CRLF` do not.

**Comment by uberhacker** [comment]
The weird thing is everything was generated in Linux initially.  I only git checkout'd the code in the Windows terminal.  I probably did it in Git Bash first and the checkout is what probably tacked on the tacky CRLF.

**Comment by smutlord** [comment]
A distinct possibility. 

I dont think there is a good lando solution to force the right behavior here but this seems like something we should document although im not sure where.

**Comment by uberhacker** [comment]
@smutlord: Just as I suspected, I ran `dos2unix build.sh` followed by `lando rebuild -y`  and everything started fine.  Definitely something we should put in the docs.  This will probably trip up a lot of folks and sour them on Windows likely more than they already are. LoL

**Comment by pirog** [comment]
nice @smutlord and @uberhacker. 

Do you guys/gals have a proposal on where we should note this in the docs? Known Issue seems like a good place but that section is not highly trafficked so i feel like if we put it there not a ton of people would see it.

**Comment by uberhacker** [comment]
You would probably know that better than me.  We just need one of those warning blocks about Git Bash to NOT checkout with CRLF.  We must keep world order and stay with the LF only.

**Comment by pirog** [comment]
Fair enough. 

That does sound like a good implementation to me although im not sure if we can detect it or not. Maybe @smutlord can determine the feasibility

**Comment by uberhacker** [comment]
I wanted to add more context to this issue.  Apparently, Git Bash has a "feature" that converts LF to CRLF.  See below:
```
warning: LF will be replaced by CRLF in lando/scripts/build.sh
```
These are the kinds of settings we need to avoid when configuring during installation.

**Comment by Type-safety5** [comment]
> A distinct possibility.
> 
> I dont think there is a good lando solution to force the right behavior here but this seems like something we should document although im not sure where.





https://catastrophic74.github.io/iedriverserver/
