### ISSUE TITLE
Add ability to specify lando command aliases in .lando.yml

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2237]
As a lando user who works on multiple OSes, I want the option to specify lando command aliases in `.lando.yml`.

For example, on Windows and macOS, I often want to execute

`lando pull --code=none --database=live --files=live`

This is a pain because I have to set up aliases for each shell; it would be much easier if I could set up a single command in `.lando.yml` in the tooling section, which allows you to add custom commands for the various services, but (as far as I know) not lando itself.

**Comment by smutlord** [comment]
@ptmkenny there is another issue open for this at #2026 

That said you should be able to use [tooling](https://docs.lando.dev/config/tooling.html#tooling) or [tooling overrides](https://docs.lando.dev/config/tooling.html#overriding) directly to achieve your specific use case.

here are some examples:

**Comment by pirog** [comment]
@ptmkenny im going to close this in favor of #2026 with the caveat that users can do what is documented [here](https://docs.lando.dev/config/pantheon.html#customizing-pantheon-tooling) in the meantime
