### ISSUE TITLE
Docker engine version range detection not correct

### ISSUE THREAD

**Issue by rikvanderkemp** [lando/lando#2239]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.1 on Manjaro Linux

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

I don't think it has side effects, however the range detection of version numbers for the Docker Engine is not quite right. But since it does give this message it feels like it does have side effects.

The message received:

```
 You have version 19.03.8-ce but Lando wants something in the 18.09.3 - 19.04.0 range.
   If you have purposefully installed an unsupported version and know what you are doing
   you can probably ignore this warning. If not we recommend you use a supported version
   as this ensures we can provide the best support and stability.
   https://docs.docker.com/engine/install/
```

**Tell us generally about your bug**

This happened after package upgrades in Manjaro, it seems to use a different versioning scheme then what they used previously.

**Comment by pirog** [comment]
@rikvanderkemp nice, i can replicate this. 

Looks like its getting tripped up on the hanging `-ce`.

**Comment by pirog** [comment]
@rikvanderkemp alright look like https://github.com/lando/lando/commit/ed9e9c45f9c8190eb66429692f7359cda859f18c was merged into `master` so this should be resolved in the next release
