### ISSUE TITLE
Get connection refused after update to v3.0.1

### ISSUE THREAD

**Issue by Adrianm6254** [lando/lando#2241]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**
I'm running Debian 10 vm on Windows 7.

Docker version:
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.1 on Debian Buster

**Tell us about your `.lando.yml`**

name: flexaco
recipe: pantheon
config:
  framework: drupal8
  site: flexaco
  id: 7e7d0925-239c-4554-8ed9-c19b67145210

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

pantheon.yml
---
api_version: 1

# PHP Version: 
# https://pantheon.io/docs/pantheon-yml#php-version
# Set site's PHP version to 7.0
# php_version: 7.2

# Drush Version
# https://pantheon.io/docs/pantheon-yml/#drush-version
drush_version: 8

# Protected Web Paths
# https://pantheon.io/docs/pantheon-yml#protected-web-paths
protected_web_paths:
  - /CHANGELOG.txt
  - /README.txt

# Quicksilver Platform Integration Hooks
# https://pantheon.io/docs/pantheon-yml#quicksilver
workflows:
  # deploy:
  #   after:
  #     - type: webphp
  #       description: Import configuration from .yml files
  #       script: private/scripts/drush_config_import/drush_config_import.php
  clone_database:
    after:
      - type: webphp
        description: Enable development modules on dev
        script: private/scripts/enable_dev_modules/enable_dev_modules.php

**Tell us about the command you were running**

lando start
lando rebuild
lando destroy

**Tell us about the error you got**

Everything would look okay after starting but I am unable to connect to the site.  I tried all the ports and will get a "connection refused" with Chrome and Firefox.

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

*Example:*

```bash
lando php -e "phpinfo();" -vvvv
[log.txt](https://github.com/lando/lando/files/4611489/log.txt)
[log.txt](https://github.com/lando/lando/files/4611492/log.txt)


```

**Tell us generally about your bug**

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?

**Comment by Adrianm6254** [comment]
output of lando log:
[lando-log.txt](https://github.com/lando/lando/files/4611519/lando-log.txt)

**Comment by pirog** [comment]
@Adrianm6254 if you want us to take a bug report seriously you need to submit something that is intelligible.
