### ISSUE TITLE
Add support for MongoDB 4.2

### ISSUE THREAD

**Issue by rikvanderkemp** [lando/lando#2246]
**Please explain your request and its importance in the form of a user story.**

As a lando user who uses MongoDB, I would like to have the latest 4.2 available as a service. 4.1 seems to have no official stable release and 4.0 is a old release.

**Steps**

- [x] add the latest [bitnami mongodb](https://github.com/bitnami/bitnami-docker-mongodb/tree/4.2.6-debian-10-r33/4.2) container to the service provider
- [x] update documentation https://docs.lando.dev/config/mongo.html#configuration
- [x] add a unit test for the latest version to verify implementation

**Caveat**

Container is only available with Debian 10. I do not foresee issues here this is in a similar context of the PHP 7.4 container (which is also using Debian 10)

**Comment by pirog** [comment]
@rikvanderkemp have you tried overriding Lando and using the 4.2 image to see what happens?

**Comment by rikvanderkemp** [comment]
I just finished on code changes to make it work. So I'll be submitting a PR in a minute if that is alright?

**Comment by pirog** [comment]
@rikvanderkemp perfect

**Comment by rikvanderkemp** [comment]
Can I add you as the pinged project committer @pirog ?

**Comment by smutlord** [comment]
@rikvanderkemp im on it. will post some comments on the PR
