### ISSUE TITLE
Update Drupal Download Links for D9 Release

### ISSUE THREAD

**Issue by AaronFeledy** [lando/lando#2249]
When Drupal 9 is released, the `latest` download link used in the Drupal 8 example will begin to download Drupal 9 during automated tests. When Drupal 9 is released, this link should be updated to download the latest Drupal 8, and the Drupal 9 example should be updated to use the `latest` link.

**Comment by pirog** [comment]
@AaronFeledy is this something you are down to be responsible for when the time comes?

**Comment by AaronFeledy** [comment]
Yep. I'll make a PR once the D9 recipe is in master.

**Comment by AaronFeledy** [comment]
I'll shout loudly on D9 launch day to merge it.

**Comment by pirog** [comment]
To that, good sir, i say "holla"

**Comment by pirog** [comment]
perfect, i respond to loud noises

**Comment by AaronFeledy** [comment]
@pirog AAAAAAHHHHHH MEEEERRRRGGGGEEE!!!!
https://www.drupal.org/project/drupal/releases/9.0.0
