### ISSUE TITLE
After updating lando to v3.0.1 my site's urls are not accessible.

### ISSUE THREAD

**Issue by ivanovf** [lando/lando#2258]
Hi guys, since I updated lando to v3.0.1 my sites stopped working, I am not able to use any url of the list, but I can use commands like drush.

I have an Ubunutu 20.04 and here is my .lando.yml file

`name: mysite
recipe: drupal8
config:
  webroot: web
  xdebug: true
  conf:
    php: .vscode/php.ini

~                 `

I also added a bindAddress to my lando's config file.
bindAddress: 192.168.0.10

when I run lando start this is what I get:

`$ lando start -vvv
lando 09:44:30 DEBUG ==> No update available. 
lando 09:44:30 VERBOSE ==> starting bootstrap at level app... 
lando 09:44:30 VERBOSE ==> config bootstrap beginning... 
lando 09:44:30 DEBUG ==> emitting event pre-bootstrap-config 
lando 09:44:30 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js 
lando 09:44:30 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js 
lando 09:44:30 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js 
lando 09:44:30 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/index.js 
lando 09:44:30 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js 
lando 09:44:30 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js 
lando 09:44:30 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js 
lando 09:44:30 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js 
lando 09:44:30 DEBUG ==> plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js 
lando 09:44:30 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js 
lando 09:44:30 DEBUG ==> emitting event post-bootstrap-config 
lando 09:44:30 VERBOSE ==> building proxy config... 
lando 09:44:30 VERBOSE ==> config bootstrap completed. 
lando 09:44:30 VERBOSE ==> tasks bootstrap beginning... 
lando 09:44:30 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 09:44:30 DEBUG ==> autoloaded task config 
lando 09:44:30 DEBUG ==> autoloaded task destroy 
lando 09:44:30 DEBUG ==> autoloaded task info 
lando 09:44:30 DEBUG ==> autoloaded task list 
lando 09:44:30 DEBUG ==> autoloaded task logs 
lando 09:44:30 DEBUG ==> autoloaded task poweroff 
lando 09:44:30 DEBUG ==> autoloaded task rebuild 
lando 09:44:30 DEBUG ==> autoloaded task restart 
lando 09:44:30 DEBUG ==> autoloaded task share 
lando 09:44:30 DEBUG ==> autoloaded task start 
lando 09:44:30 DEBUG ==> autoloaded task stop 
lando 09:44:30 DEBUG ==> autoloaded task version 
lando 09:44:30 DEBUG ==> autoloaded task init 
lando 09:44:30 DEBUG ==> autoloaded task ssh 
lando 09:44:30 DEBUG ==> emitting event post-bootstrap-tasks 
lando 09:44:30 VERBOSE ==> tasks bootstrap completed. 
lando 09:44:30 VERBOSE ==> engine bootstrap beginning... 
lando 09:44:30 DEBUG ==> emitting event pre-bootstrap-engine 
lando 09:44:30 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /home/ivanchavarro/.lando/scripts and set to mode 755 
lando 09:44:30 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-pantheon/scripts to /home/ivanchavarro/.lando/scripts and set to mode 755 
lando 09:44:30 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-proxy/scripts to /home/ivanchavarro/.lando/scripts and set to mode 755 
lando 09:44:30 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /home/ivanchavarro/.lando/scripts and set to mode 755 
lando 09:44:30 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /home/ivanchavarro/.lando/scripts and set to mode 755 
lando 09:44:30 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-sharing/scripts to /home/ivanchavarro/.lando/scripts and set to mode 755 
lando 09:44:30 DEBUG ==> emitting event post-bootstrap-engine 
lando 09:44:30 VERBOSE ==> engine bootstrap completed. 
lando 09:44:30 VERBOSE ==> app bootstrap beginning... 
lando 09:44:30 DEBUG ==> emitting event pre-bootstrap-app 
lando 09:44:30 DEBUG ==> autoloaded builder LandoCompose 
lando 09:44:30 DEBUG ==> autoloaded builder LandoAppserver 
lando 09:44:30 DEBUG ==> autoloaded builder LandoService 
lando 09:44:30 DEBUG ==> autoloaded builder LandoUtility 
lando 09:44:30 DEBUG ==> autoloaded builder LandoWebServer 
lando 09:44:30 DEBUG ==> autoloaded builder LandoDrupal 
lando 09:44:30 DEBUG ==> autoloaded builder LandoLaemp 
lando 09:44:30 DEBUG ==> autoloaded builder LandoCa 
lando 09:44:30 DEBUG ==> autoloaded builder LandoProxy 
lando 09:44:30 DEBUG ==> autoloaded builder LandoInit 
lando 09:44:30 DEBUG ==> autoloaded builder LandoApache 
lando 09:44:30 DEBUG ==> autoloaded builder LandoCompose 
lando 09:44:30 DEBUG ==> autoloaded builder LandoDotNet 
lando 09:44:30 DEBUG ==> autoloaded builder LandoElasticSearch 
lando 09:44:30 DEBUG ==> autoloaded builder LandoGo 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMailHog 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMariaDb 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMemcached 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMongoDb 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMsSql 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMySql 
lando 09:44:30 DEBUG ==> autoloaded builder LandoNginx 
lando 09:44:30 DEBUG ==> autoloaded builder LandoNode 
lando 09:44:30 DEBUG ==> autoloaded builder LandoPhp 
lando 09:44:30 DEBUG ==> autoloaded builder LandoPma 
lando 09:44:30 DEBUG ==> autoloaded builder LandoPostgres 
lando 09:44:30 DEBUG ==> autoloaded builder LandoPython 
lando 09:44:30 DEBUG ==> autoloaded builder LandoRedis 
lando 09:44:30 DEBUG ==> autoloaded builder LandoRuby 
lando 09:44:30 DEBUG ==> autoloaded builder LandoSolr 
lando 09:44:30 DEBUG ==> autoloaded builder LandoTomcat 
lando 09:44:30 DEBUG ==> autoloaded builder LandoVarnish 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMounter 
lando 09:44:30 DEBUG ==> autoloaded builder LandoPantheon 
lando 09:44:30 DEBUG ==> autoloaded builder LandoBackdrop 
lando 09:44:30 DEBUG ==> autoloaded builder LandoDrupal6 
lando 09:44:30 DEBUG ==> autoloaded builder LandoDrupal7 
lando 09:44:30 DEBUG ==> autoloaded builder LandoDrupal8 
lando 09:44:30 DEBUG ==> autoloaded builder LandoDrupal9 
lando 09:44:30 DEBUG ==> autoloaded builder LandoJoomla 
lando 09:44:30 DEBUG ==> autoloaded builder LandoLamp 
lando 09:44:30 DEBUG ==> autoloaded builder LandoLaravel 
lando 09:44:30 DEBUG ==> autoloaded builder LandoLamp 
lando 09:44:30 DEBUG ==> autoloaded builder LandoMean 
lando 09:44:30 DEBUG ==> autoloaded builder LandoWordPress 
lando 09:44:30 DEBUG ==> emitting event post-bootstrap-app 
lando 09:44:30 VERBOSE ==> app bootstrap completed. 
lando 09:44:30 VERBOSE ==> bootstrap completed. 
lando 09:44:30 DEBUG ==> emitting event post-bootstrap 
lando 09:44:30 VERBOSE ==> docker-engine exists: true 
lando 09:44:30 VERBOSE ==> docker-compose exists: true 
lando 09:44:30 DEBUG ==> emitting event cli-answers 
lando 09:44:30 DEBUG ==> emitting event cli-start-answers 
lando 09:44:30 DEBUG ==> emitting event cli-run 
lando 09:44:30 DEBUG ==> emitting event cli-start-run 
lando 09:44:30 INFO ==> loading app mysite from config files 0=/home/ivanchavarro/Projects/mysite/.lando.yml
lando 09:44:30 DEBUG ==> app mysite has config name=mysite, recipe=drupal8, webroot=web, xdebug=true, php=.vscode/php.ini, description=Makes a deploy to Dev ENV in pantheon., cmd=[sh /app/scripts/pantheon/deploy.sh], service=appserver, alias=deploy
Let's get this party started! Starting app mysite...
mysite 09:44:30 INFO ==> starting app... 
mysite 09:44:30 VERBOSE ==> initiatilizing app at /home/ivanchavarro/Projects/mysite... 
lando     09:44:30 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/app.js 
lando     09:44:30 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/app.js 
lando     09:44:30 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/app.js 
lando     09:44:30 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/app.js 
mysite 09:44:30 VERBOSE ==> proxy settings detected. 
lando     09:44:30 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/app.js 
lando     09:44:30 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/app.js 
lando     09:44:30 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/app.js 
lando     09:44:30 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/app.js 
lando     09:44:30 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/app.js 
mysite 09:44:30 DEBUG ==> emitting event pre-init 
mysite 09:44:30 VERBOSE ==> building drupal8 recipe named 
lando     09:44:30 VERBOSE ==> proxy is ON. 
lando     09:44:30 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt 
mysite 09:44:30 VERBOSE ==> building php service appserver 
mysite 09:44:30 VERBOSE ==> building mysql service database 
mysite 09:44:30 DEBUG ==> emitting event post-init 
mysite 09:44:30 DEBUG ==> adding hostnames to the app... 
mysite 09:44:30 DEBUG ==> hostnames added to appserver 0=appserver.mysite.internal
mysite 09:44:30 DEBUG ==> hostnames added to database 0=database.mysite.internal
mysite 09:44:30 VERBOSE ==> attempting to find open services... 
lando     09:44:30 DEBUG ==> engine is up. 
lando     09:44:30 DEBUG ==> docker is running. 
mysite 09:44:30 DEBUG ==> engine is up. 
mysite 09:44:30 VERBOSE ==> refreshing certificates... 0=appserver, 1=database
mysite 09:44:30 VERBOSE ==> analyzing user ssh keys... using 1 of 1 
mysite 09:44:30 DEBUG ==> key config...  none 
mysite 09:44:30 VERBOSE ==> additional tooling detected 
mysite 09:44:30 DEBUG ==> adding app cli task composer 
mysite 09:44:30 DEBUG ==> adding app cli task db-import <file> 
mysite 09:44:30 DEBUG ==> adding app cli task db-export [file] 
mysite 09:44:30 DEBUG ==> adding app cli task php 
mysite 09:44:30 DEBUG ==> adding app cli task mysql 
mysite 09:44:30 DEBUG ==> adding app cli task drush 
mysite 09:44:30 DEBUG ==> adding app cli task drupal 
mysite 09:44:30 DEBUG ==> adding app cli task deploy 
mysite 09:44:30 VERBOSE ==> setting LANDO_INFO... 
mysite 09:44:30 DEBUG ==> ensuring exposed ports on appserver are bound to 192.168.0.10 
mysite 09:44:30 DEBUG ==> ensuring exposed ports on appserver are bound to 192.168.0.10 
mysite 09:44:30 DEBUG ==> ensuring exposed ports on database are bound to 192.168.0.10 
mysite 09:44:30 VERBOSE ==> app is ready! 
mysite 09:44:30 DEBUG ==> emitting event ready 
mysite 09:44:30 VERBOSE ==> discovering dynamic portforward info... 
mysite 09:44:30 VERBOSE ==> reporting start action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
mysite 09:44:30 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=9cc8207e423e3c21fa6ac1872c3d13b4b67b639b, nodeVersion=v12.13.1, mode=cli, type=Linux, platform=linux, release=5.4.0-29-generic, arch=x64, product=lando, version=3.0.2, app=33f590dbd9165e3264ec44ed5bf45334e528bc94, type=drupal8, services=[php:7.2, mysql], action=start, created=2020-05-14T14:44:30.861Z
mysite 09:44:30 DEBUG ==> emitting event pre-start 
lando     09:44:30 DEBUG ==> process pid5 running /usr/share/lando/bin/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
lando     09:44:31 VERBOSE ==> checking docker version compatibility... 
lando     09:44:31 DEBUG ==> compatibility results name=compose, link=https://docs.docker.com/compose/install/#install-compose-on-linux-systems, wants=1.23.0 - 1.25.5, version=1.25.5, semversion=1.25.5, semmin=1.23.0, semmax=1.25.5, dockerVersion=true, satisfied=true, name=engine, link=https://docs.docker.com/engine/install/, wants=18.09.3 - 19.04.0, version=19.03.8, semversion=19.3.8, semmin=18.9.3, semmax=19.4.0, dockerVersion=true, satisfied=true
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
lando     09:44:31 DEBUG ==> process pid5 finished with exit code 0 
mysite 09:44:31 DEBUG ==> app has proxy compose files 0=/home/ivanchavarro/.lando/compose/mysite/proxy-0.yml
mysite 09:44:31 DEBUG ==> process pid6 running /usr/share/lando/bin/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting mysite_appserver_1 ... done
Starting mysite_database_1  ... done
mysite 09:44:33 DEBUG ==> process pid6 finished with exit code 0 
mysite 09:44:33 DEBUG ==> emitting event post-start 
mysite 09:44:33 DEBUG ==> process pid7 running /usr/share/lando/bin/docker-compose exec database bash [ -f /bitnami/mysql/.mysql_initialized ] cstdio=pipe, silent=true, mode=spawn, detached=false
mysite 09:44:34 DEBUG ==> process pid7 finished with exit code 0 
mysite 09:44:34 DEBUG ==> connected mysite_database_1 to the landonet 
mysite 09:44:34 DEBUG ==> connected mysite_appserver_1 to the landonet 
mysite 09:44:34 VERBOSE ==> attempting to find open services... 
Scanning to determine which services are ready... Please standby...
mysite 09:44:34 VERBOSE ==> about to scan urls 
mysite 09:44:34 DEBUG ==> scanning data urls=[https://localhost:32816, http://localhost:32817, http://mysite.lndo.site/, https://mysite.lndo.site/], max=16, waitCodes=[400, 502, 404]
mysite 09:44:34 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:34 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:34 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:34 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:35 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:35 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:35 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:35 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:36 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:36 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:36 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:36 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:37 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:37 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:37 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:37 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:39 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:39 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:39 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:39 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:42 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:42 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:42 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:42 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:45 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:45 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:45 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:45 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:48 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:48 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:48 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:48 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:52 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:52 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:52 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:52 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:44:57 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:44:57 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:44:57 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:44:57 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:02 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:02 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:02 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:02 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:07 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:07 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:07 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:07 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:13 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:13 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:13 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:13 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:20 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:20 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:20 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:20 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:27 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:27 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:27 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:27 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:34 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:34 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:34 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:34 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:42 DEBUG ==> checking to see if https://localhost:32816 is ready. 
mysite 09:45:42 DEBUG ==> checking to see if http://localhost:32817 is ready. 
mysite 09:45:42 DEBUG ==> checking to see if http://mysite.lndo.site/ is ready. 
mysite 09:45:42 DEBUG ==> checking to see if https://mysite.lndo.site/ is ready. 
mysite 09:45:42 DEBUG ==> https://localhost:32816 not currently accessible 
mysite 09:45:42 DEBUG ==> http://localhost:32817 not currently accessible 
mysite 09:45:42 DEBUG ==> http://mysite.lndo.site/ not currently accessible 
mysite 09:45:42 DEBUG ==> https://mysite.lndo.site/ not currently accessible 
mysite 09:45:42 VERBOSE ==> scan completed. 
mysite 09:45:42 DEBUG ==> scan results. url=https://localhost:32816, status=false, color=red, url=http://localhost:32817, status=false, color=red, url=http://mysite.lndo.site/, status=false, color=red, url=https://mysite.lndo.site/, status=false, color=red
mysite 09:45:42 DEBUG ==> engine is up. 
mysite 09:45:42 DEBUG ==> process pid9 running /usr/share/lando/bin/docker-compose exec appserver /bin/sh mkdir -p /certs && /helpers/refresh-certs.sh > /certs/refresh.log cstdio=inherit, silent=false, mode=spawn, detached=false
mysite 09:45:43 DEBUG ==> process pid9 finished with exit code 0 
mysite 09:45:43 DEBUG ==> process pid10 running /usr/share/lando/bin/docker-compose exec database /bin/sh mkdir -p /certs && /helpers/refresh-certs.sh > /certs/refresh.log cstdio=inherit, silent=false, mode=spawn, detached=false
mysite 09:45:44 DEBUG ==> process pid10 finished with exit code 0 
mysite 09:45:44 INFO ==> started app. 

   ___                      __        __        __     __        ______
  / _ )___  ___  __ _  ___ / /  ___ _/ /_____ _/ /__ _/ /_____ _/ / / /
 / _  / _ \/ _ \/  ' \(_-</ _ \/ _ `/  '_/ _ `/ / _ `/  '_/ _ `/_/_/_/ 
/____/\___/\___/_/_/_/___/_//_/\_,_/_/\_\\_,_/_/\_,_/_/\_\\_,_(_|_|_)  
                                                                       

Your app has started up correctly.
Here are some vitals:

 NAME            mysite                             
 LOCATION        /home/ivanchavarro/Projects/mysite 
 SERVICES        appserver, database                   
 APPSERVER URLS  https://localhost:32816               
                 http://localhost:32817                
                 http://mysite.lndo.site/           
                 https://mysite.lndo.site/          
`
All suggested urls are in red.

Thanks in advance.

**Comment by pirog** [comment]
@ivanovf if it works without the `bindAddress`, which based on our tests it does, then thats all that lando officially supports. If you are modifying the `bindAddress` then its up to you to configure it correctly.

**Comment by ivanovf** [comment]
I removed that config and it worked again, thank you.
How can I configure a bindAddress propertly?, I have a local network where I share the site.

**Comment by pirog** [comment]
you would know better than me. 

that said binding to `0.0.0.0` might be the most straightforward way although it has security implications which is why we dont bind to it anymore
