### ISSUE TITLE
Support PHP 7.4 for pantheon recipe

### ISSUE THREAD

**Issue by a-sukhodolsky** [lando/lando#2259]
**Issue overview**

Lando >= v3.0.0-aft.1 supports PHP 7.4 (#1892), and Pantheon supports PHP 7.4 via `pantheon.yml`, but `lando start` fails.

**What is your lando version and operating system?**

v3.0.1 on macOS 10.15.4

**Tell us about your `.lando.yml`**
*.lando.yml*
```yml
name: lando-pantheon-php74
recipe: pantheon
config:
  framework: drupal8
  site: ***
  id: ***
```

*pantheon.yml*
```yml
api_version: 1
php_version: 7.4
```

**Tell us about the command you were running**

```bash
lando init --source=pantheon --pantheon-site=pantheon-site-php74
lando start
```

**Tell us about the error you got**

```
Pulling appserver (devwithlando/pantheon-appserver:7.4-2)...
ERROR: manifest for devwithlando/pantheon-appserver:7.4-2 not found: manifest unknown: manifest unknown
```

**Tell us generally about your bug**

Any attempt to run PHP 7.4 site hosted on Pantheon fails.

**Tell us more**

`plugins/lando-pantheon/recipes/pantheon/7.4-fpm` folder does not exists.
This issue prevents using lando in case the site is hosted on Pantheon and requires PHP 7.4.

**Comment by pirog** [comment]
@a-sukhodolsky this should be available in https://github.com/lando/lando/releases/tag/v3.0.3, releases are still building so might take a few
