### ISSUE TITLE
Don't  "Symlinked users known_hosts" if `keys: false`

### ISSUE THREAD

**Issue by calevans** [lando/lando#2278]
The new `keys: false` option is fantastic. With it I can now control my keys very simply in a post-start event.

That having been said, I have to add a couple extra steps to delete and re-copy my `known_hosts`. Because Lando is not processing my keys anymore, I am handling it. but then it is overwriting my `known_hosts` with a symlink. It LOOKS LIKE this is happening but then the step that handles permissions is skipped because `keys: false`. The end result is a `known_hosts` that is owned by root. 

I get around this by simply deleting it and copying my good one back in it's place.

My request is that ``keys: false` remove ALL Lando processing of the .ssh directory. Allow me to do it the way I want it done. 

Thanks! :)

Cheers!
=C=

**Comment by calevans** [comment]
p.s. Obviously I did something wrong. This is not a documentation issue, this is a feature requet. :)

=C=

**Comment by bfuzze** [comment]
I'm seeing this on my environment too using the drupal9 recipe, but I'm not using the keys directive.  @calevans Can you provide the work-around?
