### ISSUE TITLE
How to export specific database tables with Lando?

### ISSUE THREAD

**Issue by Kees-kees** [lando/lando#2297]
Normally speaking i would use `lando db-export` in order to dump my database.

What command should i then run for dumping (one or more) specific table(s) from a database?

**Comment by jcmartinez** [comment]
Exporting a single table using db-export isn't available; however, you can use the `mysqldump` command that is available inside your database service:

1- Create a directory inside your project to backup your data (E.g. call it `data_backups`).

2- Drop into the Mysql service as root:
`lando ssh -s database`

3- Dump your table:
`mysqldump -u lamp -p lamp my_table_name > data_backups/my_table_name.sql`

Note, in my case `lamp` is my recipe as well as the name of my database and its username.
