### ISSUE TITLE
Unnecessary highlight (bgBlack) makes the text unreadable

### ISSUE THREAD

**Issue by pendashteh** [lando/lando#2302]
This is a quick fix which will improve readibility of the printed messages.

In the welcome message, there are certain pieces that are styled with a black background (bgColor).

That makes it impossible to read the text.

The solution is to simply not do that. It's not good practice to touch the background color in Terminal.

Definition:
https://github.com/lando/lando/blob/7af5e8ab13fa0528bdf3840df7e6b60fd95f1ac5/lib/art.js#L12

In-code comment:
https://github.com/lando/lando/commit/5dafa1de2642c38476ba4417c9133c714477e762#r39537262

**Comment by pirog** [comment]
@pendashteh i can read it perfectly fine so maybe "impossible" is not the word you want.

**Comment by pendashteh** [comment]
@pirog fair enough. Still, I consider it an issue if it's not readable on a standard Ubuntu terminal. Screenshot below:
https://imgur.com/a/1IB4gan
https://imgur.com/V54Y31j (after selecting the text)

The background color is not adding much value, however it makes it *very hard* to read for *some users*.

**Comment by pirog** [comment]
There we go! https://github.com/lando/lando/issues/2302#issuecomment-636155979 is an issue report i can get behind.

**Comment by pendashteh** [comment]
I came across an example where the highlight works perfectly well for me.

https://github.com/lando/lando/blob/e59ba848debc373e9f347fb9872c20dcfd1cd74c/lib/art.js#L123

Defined as bellow:
https://github.com/lando/lando/blob/e59ba848debc373e9f347fb9872c20dcfd1cd74c/lib/art.js#L17

Screenshots below:
https://imgur.com/a/6BHf8RY

**Comment by pirog** [comment]
Alright this will be fixed in the next release
