### ISSUE TITLE
Provide better guards in `recreate-users.sh`

### ISSUE THREAD

**Issue by pirog** [lando/lando#2318]
Right now our `recreate-users` script is "bad" in that it always runs and never errors. We should only attempt to run the commands in this script when we need to and they should actually report failure if they fail in those circumstances. 
https://github.com/lando/lando/blob/master/experimental/plugins/lando-platformsh/scripts/psh-recreate-users.sh 

The guards we need are 

1. If `web` user exists and is set correctly (eg has UID = `$LANDO_HOST_UID` and correct HOME and SHELL) then we dont need to recreate `web`
2. If `app` user exists and is NOT set to `$LANDO_HOST_UID` then we do not need to recreate. 

Note that we need to end up with a result where the `web` user has `$LANDO_HOST_UID` and the `app` user does not. This can be tricky because on `linux` user `1000` is common and `app` is set to `1000` by default. This means we need to remove the `app` user first, then create `web` next so that then we create `app` its not going to be to `1000` if `$LANDO_HOST_UID` is also `1000`

**Comment by mikemilano** [comment]
Updates in PR in #2338

It works successfully with a `lando rebuild` and `lando restart`.
