### ISSUE TITLE
How does lando determine/assign CPU use?

### ISSUE THREAD

**Issue by mrweiner** [lando/lando#2325]
Taking a look at `htop` when running `lando drush cr -vvv`, I see one CPU being pegged at ~100% while the rest are essentially completely idle. Curious whether this is something that could be addressed by the lando/docker configuration or is it just a result of how drupal/drush/php utilize CPUs?

Realizing that this question may not be related to lando itself at all but I'm going to leave it here anyway.

**Comment by pirog** [comment]
@mrweiner lando just inherits dockers usage settings so it doesnt do anything. 

on linux i think the default is to basically burn as hard as possible. on docker desktop for mac/windows you can set the resource usage in the preferences.
