### ISSUE TITLE
A typo in the dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [lando/lando#2326]
https://github.com/lando/lando/blob/c1ad89e5b14807d3ccd94711c46e82d5e5ac76a3/plugins/lando-services/services/php/7.1-apache/Dockerfile#L83
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential typo above. There is a command line "rm -rf" which is basically doing nothing. Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by pirog** [comment]
Your tool is annoying and unwanted.
