### ISSUE TITLE
404 on config systems link

### ISSUE THREAD

**Issue by nullvariable** [lando/lando#2329]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/config.html
https://github.com/lando/lando/blob/master/docs/basics/config.md

**Describe the change you'd like**
"See the config system for more info." Links `config/config.md` which no longer exists in the latest version of the docs. This line should be removed, or maybe updated to link to `config/global`?

**Comment by pirog** [comment]
thanks @nullvariable, this will be live on the next release
