### ISSUE TITLE
Is lndo.site down?

### ISSUE THREAD

**Issue by SpaceBoiNate** [lando/lando#2336]
There seems to be an issue to get lndo.site, I'm not sure if it is forwarding traffic anymore. https://mxtoolbox.com/SuperTool.aspx?action=a%3alndo.site&run=toolpage

**Comment by pirog** [comment]
as far as we can tell its working as expected @SpaceBoiNate

**Comment by SpaceBoiNate** [comment]
@pirog Sorry about that, I think something was up with my VPN's DNS resolver... Thank you for the quick response. I just rebooted my computer to resolve the issue.
