### ISSUE TITLE
Remove obsolete frontend tooling page

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2337]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/guides/frontend.html

**Describe the change you'd like**
This guide should be deleted. It is the first hit in google for "lando gulp" but the configuration info is incorrect for current versions of lando.

All of the content is already covered by the up-to-date https://docs.lando.dev/config/node.html except for the section "make tooling available on the CLI."  (This section could be added to the config/node page, but I think it is already covered elsewhere in the config guide.)

**Comment by pirog** [comment]
@ptmkenny what is obsolete about those docs? As far as we know this document is still valid.

We also don't put tooling considerations into service config docs. This provides a clean separation of concerns and keeps service documentation focused on the service config itself.

**Comment by ptmkenny** [comment]
@pirog The example for gulp shows this:

```
    build:
      - npm install
      - gulp
    globals:
      gulp-cli: latest
```

But on my site, this failed.  When I skipped the build step and added only the globals as descirbed on the node config page, everything worked as expected.

```
    globals:
      gulp-cli: latest
```

**Comment by pirog** [comment]
@ptmkenny if you dont have a default `gulp` task defined then i wouldnt expect it to work.

**Comment by ptmkenny** [comment]
Ah ok, my mistake.  I checked now and the repo I was working on didn't have a default gulp task; the original repo did, and that's why I thought it had changed.

**Comment by pirog** [comment]
@ptmkenny im going to keep this open so we can update the docs to make it explicit you need a gulp task defined
