### ISSUE TITLE
Document lando magic

### ISSUE THREAD

**Issue by gitressa** [lando/lando#2352]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/usage.html#default-commands

**Describe the change you'd like**
1. Add `lando magic` to the list of commands, as well as what it actually does, more descriptive than "Runs magic commands". I.e, does it hook into project-specific custom-tailored functions?
2. Create https://docs.lando.dev/basics/magic.html describing in detail how `magic` works.

**Comment by pirog** [comment]
@gitressa what is `lando magic`?

**Comment by pirog** [comment]
Ahhh very nice! I suspected you _might_ be looking at something else besides Lando proper but part of me was hoping there was some secret lando command that someone snuck in without me noticing!

**Comment by gitressa** [comment]
Heh, sneaking it into the code base would have been quite the feat, with all the eyes on the code here :-)
