### ISSUE TITLE
How do i get two databases into a single DB service?

### ISSUE THREAD

**Issue by pirog** [lando/lando#2355]
Lando's model is basically one database per database service. It is set up this way because that is the easiest way for lando manage and maintain things and that is how the underlying images work.

While this is fine for the vast majority of use cases it doesn't scale super great if you are, for example, running a Drupal Multisite that needs 50+ DBs

Some users have figured out how to work around that
https://github.com/lando/lando/issues/1532#issuecomment-603171149

Let's get this into an official and tested guide so we can point other users to it. It also is probably a good pre-req for finally finishing up #433

**Comment by gitressa** [comment]
I just saw this, perhaps it can be used for inspiration? https://thinktandem.io/blog/2017/12/18/lando-backdrop-civicrm/

**Comment by gitressa** [comment]
I have got it working for CiviCRM, see https://github.com/lando/lando/issues/1854#issuecomment-676055333.
Is it worth considering a dedicated CiviCRM page in the Lando documentation?

**Comment by gitressa** [comment]
Thanks Stalebot, but this issue is still relevant.
