### ISSUE TITLE
Add remaining p.sh services

### ISSUE THREAD

**Issue by pirog** [lando/lando#2366]
We should wait until #2311 is done so we can easily dev and test these. Here are the other services we need to add, roughly ordered by priority:

- [x] https://docs.platform.sh/configuration/services/rabbitmq.html
- [x] https://docs.platform.sh/configuration/services/influxdb.html
- [x] https://docs.platform.sh/configuration/services/kafka.html
- ~~[ ] https://docs.platform.sh/configuration/services/varnish.html~~ #2462 
- ~~[ ] https://docs.platform.sh/configuration/services/headless-chrome.html~~ #2461 
- ~~[ ] https://docs.platform.sh/configuration/services/network-storage.html~~ (This is now covered over here #2393)

For all of these services we will also want to add them to the kitchen sink and tests them as in https://github.com/lando/lando/issues/2394

We should also make sure we persist their data like we did in https://github.com/lando/lando/issues/2397 if applicable.

**Comment by mikemilano** [comment]
Influxdb has no user credentials installed by default. I added a test to make sure the process is running but we'll need to mount a script that runs some auth commands to either remove authentication or create a user if we want to test PHP functionality.

**Comment by mikemilano** [comment]
Kafka isn't starting and there is an error that reminds me of one of the elasticsearch errors. (`my_ip` in `/etc/platform/kafka.properties`)

> kafka_1          | 2020-06-26 17:31:04,058 platformsh.agent.service ERROR Unable to render template /etc/platform/kafka.properties: 
> kafka_1          | 
> kafka_1          | Traceback (most recent call last):
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 369, in generate_config_files
> kafka_1          |     safe_write(path, template.render(**self.config), mode=output_mode)
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/template.py", line 462, in render
> kafka_1          |     return runtime._render(self, self.callable_, args, data)
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 838, in _render
> kafka_1          |     **_kwargs_for_callable(callable_, data))
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
> kafka_1          |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
> kafka_1          |     callable_(context, *args, **kwargs)
> kafka_1          |   File "/etc/platform/kafka.properties.psh-tmpl", line 0, in render_body
> kafka_1          |     
> kafka_1          | NameError: 'my_ip' is not defined
> kafka_1          | Traceback (most recent call last):
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 369, in generate_config_files
> kafka_1          |     safe_write(path, template.render(**self.config), mode=output_mode)
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/template.py", line 462, in render
> kafka_1          |     return runtime._render(self, self.callable_, args, data)
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 838, in _render
> kafka_1          |     **_kwargs_for_callable(callable_, data))
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
> kafka_1          |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
> kafka_1          |   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
> kafka_1          |     callable_(context, *args, **kwargs)
> kafka_1          |   File "_etc_platform_kafka_properties_psh_tmpl", line 23, in render_body
> kafka_1          | NameError: 'my_ip' is not defined
>

**Comment by pirog** [comment]
@mikemilano interesting. If it is the case that we need to actually set an IP, we are currently doing that over here:
https://github.com/lando/lando/blob/master/experimental/plugins/lando-platformsh/app.js#L152-L171
you might be able to replicate this pattern elsewhere

**Comment by mikemilano** [comment]
This one is held up until we figure out the name of the chrome image. It does not follow the same naming pattern as the others.

**Comment by mikemilano** [comment]
@pirog I updated the PR which is ready for your eyes.

- Moving varnish & headless chrome to another ticket
- Kafka will startup and the process will run, but `lando rebuild` hangs when it is enabled

**Comment by pirog** [comment]
Sounds good @mikemilano, i should be able to get this merged in shortly
