### ISSUE TITLE
Allow post-start events to launch/reference lando tooling commands

### ISSUE THREAD

**Issue by gabrys** [lando/lando#2378]
As a Lando administrator (the person maintaining the project's `.lando.yml`), I'd like to be able to use the custom lando tooling commands as post-start commands to reduce the duplication in the Landofile.

Example:

Let's say we have a command clearing a bunch of caches of our application: `lando clearcache`. I'd like the cache clearing to happen also after the application starts using post-start events. Currently I need to copy and paste the command code defined in the `tooling` section to the `events` sections. Alternatively I can store a script in the repo and reference it twice from the Landofile (once in `events` and once in `tooling`), but I'd like to have the option to simply reference the `clearcache` tooling command in the `events` section.

**Comment by rogermarley-com-au** [comment]
This would be valuable, and is a common desire from colleagues when working with Lando.

The key reason is that abstracting out to scripts is insufficient when different series of commands need to be executed in different containers (services).

For instance I had a case where, in order: 
- a custom service (a container using a custom image) was used to execute a database dump (using 3rd party programs to gain the access required to perform the dump)
- the dump file was then imported in the mysql service
- the appserver (WordPress) service was then used to do some post-processing

And that series of commands across those containers was something that was something desired to be done both on rebuild as well as ad hoc (as tooling).

Hence the ability to abstract further e.g. by calling tooling commands in events, or some intermediate concept like "lando functions" which both events and tooling could use, would be very valuable.

Such "lando functions" might simply look like how events look now, a series of commands with the name of the service to be used next to each of them.

**Comment by pirog** [comment]
@gabrys @rogermarley-com-au i dont think anyone doubts that this would be valuable. IIRC a previous implementation suggestion was to do something like

```bash
events:
  post-start:
    - lando: some-tooling-command
    - appserver: echo "more stuff"
```

I _think_ the implementation here would be to basically replace `lando: some-tooling-command` with the underlying tooling command. 

@rogermarley-com-au is that more or less what you are thinking?

**Comment by rogermarley-com-au** [comment]
@pirog and then it would take args like it would at the shell? Like `- lando: some-tooling-command arg1 arg2`? Yeah that's more or less what I was thinking. Shall I go ahead with making a PR for that feature (after my current issues)?

**Comment by pirog** [comment]
@rogermarley-com-au i'm not sure if args would work or not. 

I do suspect that this feature will be a significant engineering challenge but at the very least it would be great for someone to _try_ to do it so we know specifically what the limitations of our current model are and what changes we would have to make to easily accommodate it.

**Comment by rogermarley-com-au** [comment]
@pirog I'm ok with significant engineering challenge :) Alright, I'll take a crack at it then, please assign to me

**Comment by ptmkenny** [comment]
This is still a relevant request, even if it's not being actively worked on. Please re-open.
