### ISSUE TITLE
Lando pull database from pantheon incorrectly reports success.

### ISSUE THREAD

**Issue by NickDickinsonWilde** [lando/lando#2382]
# System/Setup
Windows 10 - most recently with Docker in WSL2 mode but seen it in HyperV mode as well.
Seen it in at least half a dozen Lando versions, but it is a minor issue and only when I'm working from a phone tether or other bad internet connection, so keep not getting around to it.
```yaml
recipe: pantheon
config:
  framework: drupal8
  xdebug: false
```
(also other config like the pantheon ID/name - but that is unrelated to the issue]

# Issue
Running `lando pull [options including a database]`,
Get this response:
```bash
Pulling your database... This miiiiight take a minute
mysqldump: Error 2013: Lost connection to MySQL server during query when dumping table `cache_dynamic_page_cache` at row: 18
15.1MiB 0:01:19 [ 193KiB/s] [                              <=>                 ]
*GREEN*Pull completed successfully!*GREEN*
```

Expected behaviour would be a *RED* or even white text failure ending.

Seems to not be properly catching the error which was output. (To be clear, the database is left at an unusable state, but that's expected). This may be fixed in other work when doing #2371 I suppose, but wanted to surface it at least.

**Comment by pirog** [comment]
@NickDickinsonWilde the pull script uses `set -e` so any errors will cause the script to stop. If you are on the most recent version my best guess is that the error you are seeing just doesnt return a non-zero code so its not being detected as an error. If so there isn't much we can do.
