### ISSUE TITLE
Lando Pull 401

### ISSUE THREAD

**Issue by dchaffin** [lando/lando#2388]
I'm running:
Windows 10
Lando 3.0.5
Docker 2.3.0.3 (45519)

If I run:
`terminus auth:login --machine-token={key}`
OR:
`lando terminus auth:login --machine-token={key}`

If returns:
`[notice] Logging in via machine token.`

Which I guess is successful.

If I then run:
`lando pull`

I get:
`ERROR ==> POST request to https://terminus.pantheon.io/api/authorize/machine-token failed with code 401: Unauthorized. The server responded with the message Authorization failed. Please check that your machine token is valid..`

I've tried recreating my machine token at Pantheon a number of times, but I'm still getting this. I tried lando rebuild and restarting as well.

What else am I missing? Thanks!

**Comment by pirog** [comment]
@dchaffin `lando pull` has an `--auth` flag that you can use to reset the machine token eg `lando pull --auth=MYTOKEN`. If the pull completes successfully lando will use that token for subsequent `lando pull/push`. It may also be advisable to `lando rebuild` after you switch tokens.

We also have some work in progress over at #2403 to provide a better overall experience for when tokens get revoked so im going to close this out as "wontfix" with the note that there is a workaround posted in this comment and #2403 covers improvements to this flow.

cc @dustinleblanc
