### ISSUE TITLE
LAMP stack Apache file negotiation errors

### ISSUE THREAD

**Issue by danielkorte** [lando/lando#2390]
Any .htaccess rewrites like the one used for index.php in WordPress/Drupal/Laravel/etc. do not work on the LAMP stack:

AH00687: Negotiation: discovered file(s) matching request: /app/test/ (None could be negotiated)

The issue is solved by adding `AddType application/x-httpd-php .php` to the .htaccess file at the document root. It would be nice if the LAMP stack was already configured for Apache to look for PHP files.

**Comment by pirog** [comment]
@danielkorte you are going to need to provide steps to replicate or explain what you are seeing a bit better because as far as we can tell this is how it works by default.

For example running a normal drupal 7 site using the `lamp` recipe works as expected

```
lando init --source remote --remote-url https://ftp.drupal.org/files/projects/drupal-7.71.tar.gz --remote-options="--strip-components 1" --recipe lamp --webroot . --name lando-drupal7
```

**Comment by danielkorte** [comment]
@pirog Thanks for the reply. That does appear to work. I’ll have to take another look.
