### ISSUE TITLE
Figure out which currently supported services need to persist data and then get them to persist data

### ISSUE THREAD

**Issue by pirog** [lando/lando#2397]
Right now we are persisting data for the following platform services:

1. mysql/postgres
2. redis (although we should only do this for the "persistent" variant, currently we do it for both)
3. postgres

We need to figure out which of our _currently supported_ services _should_ persist and which _shouldnt_. We can worry about the persistence of non-supported services as we add them. 

My guess is that persistence will work with _most_ services OOTB with the following volume mount:

```js
${options.data}:/mnt/data`,
```

Services like `postgres` and likely `elasticsearch` may require a different mount points to work.

My guess is that we should support persistence for the following in addition to the ones we already support:

* `elasticsearch`
* `mongodb`
*  `solr`
* `redis` - only the `redis-persistence` image variant 

We dont have a great way to func test persistence yet so lets not worry about tests for now.

**Comment by ralt** [comment]
Just saw this, you can check `runtime.platformsh.storage_mount_point` in the `/etc/manifest.yaml` file to see which folder should be persistent. If the property doesn't exist (e.g. redis), then you don't need persistent storage.

**Comment by pirog** [comment]
Ahhh very nice. That is helpful!

**Comment by mikemilano** [comment]
I added mounts for elasticsearch, influxdb, mongodb, php, and rabbitmq.
