### ISSUE TITLE
Improve pantheon database pull

### ISSUE THREAD

**Issue by pirog** [lando/lando#2402]
In [Part 2 of the Pantheon Recipe V2 Proposal](https://github.com/lando/lando/issues/2371) it was discovered that `terminus remote:drush -- sql-dump --extra=--column-statistics=0` provides that fastest sql dump. 

We should update our `pull` and probably `push` scripts to leverage this discovery. There are, of course, some caveats:

1. The dump command is going to differ depending on `wordpress` vs `drupal` and also `drush` version. 
2. It's not clear whether we can use `remote:wp` and `remote:drush` to push up a database quickly so that needs to be investigated more.
3. We _probably_ want to preserve auxiliary operations around pulling and pushing like making sure caches are clear on non-live environments, making sure the site is awake, etc.

Here is an implementation idea:

Lando now lets you set ENVVARS for specific tooling commands. This means that we can construct the appropriate `DB_PULL` command on the lando side and set it into an envvar that can be referenced/used in the script. This likely prevents us from needing overly complex and unfortunate BASH logic to determine things like drush version etc.

We likely can do the same for the push command and script. 

Here is a rough sketch of what the bash script logic would look like with the above, this is the stuff that would go into the `DATABASE != "none"` block

1. Validate you can pull from the database
2. dump existing tables
3. wake up the site with terminus (this ensures the DB is active)
4. if drupaly: grab drupal aliases (this might not actually be necessary anymore if we are using `remote:drush` now, if its no longer necessary do we still want to do it elsewhere (eg pantheon.sh) as a convenience)?
5. run the `CACHE_CLEAR` command (this should also be an envvar set by lando depending on wp/drush/drush things) if we arent on live, this minimized download size and removes env specific stuff
6. run the `DB_PULL` command stored in the envvar and pipe it into the local db
7. do any other framework specific things eg wp search-replace

@dustinleblanc im assigning this to you but i might also have some time to work on it so lets stay in communication. I'm also happy to help you work through the engineering.

**Comment by dustinleblanc** [comment]
remote:drush and remote:wp won't be useful for pushing since they both operate the cli tool on the platform. They could potentially be used to execute imports after the push completes though.

**Comment by pirog** [comment]
@dustinleblanc so i think what i was _hoping_ for is something like

```
some-command-to-dump-local-db | terminus remote:wp -- some-command-to-import-to-db --some-option-to-accept-from-stdin
```

**Comment by mchelen** [comment]
hey just wanted to say a big thank you for this! using 3.0.8 i'm seeing database pull from pantheon at over 500KiB/s compared with ~10KiB/s before :tada:

**Comment by dustinleblanc** [comment]
Awesome. Thanks for the kind words @mchelen! Glad its having an impact :)
