### ISSUE TITLE
Improve terminus auth/reauth

### ISSUE THREAD

**Issue by pirog** [lando/lando#2403]
It is probably useful to check out a similar concern we have with the platform cli over here: https://github.com/lando/lando/issues/2398

Mapping those concerns into the pantheon context we probably want to do something like:

1. Also set `TERMINUS_TOKEN` on a per tooling command basis and unset it in the application container, this way its value can float without needing to `lando rebuild`
2. Get `lando pull` and `lando push` to prompt for auth if there is no saved token (which is currently does) OR if the saved token is now invalid/revoked/deleted/etc (which it DOES NOT currently do)

Those two things should provide a better overall experience since Lando can more or less manage a token for the things it need and other auth concerns can be handled by the user directly.

There are a few other things we probably want to improve in addition to the above:

1. `auth.sh` currently runs before ALL lando things eg lando pull that require auth. It is currently set to run when `$AUTH` is set. However, what would probably be better is something like 

```bash
# Try to login if we arent
if ! terminus auth:whoami 2>/dev/null; then
  # If we cannot login exit non zero with a helpful message
  if ! terminus auth:login --machine-token="$AUTH" || terminus auth:login --email="$TERMINUS_USER" || terminus auth:login; then
    lando_error "Could not authenticate you... HELPFUL MESSAGE TO REMEDIATE
  fi
fi 

# If we get here then we are authenticated and good to go
proceed with all auth based logic
```

2. `auth.sh` currently contains a bunch of logic to set LOCKR based things. This does not seem like the right place to do this. `auth.sh` also runs by itself in a build step. This also does not seem right. I'm not exactly sure what to do about the above but

* We probably want to decouple the lockr stuff from `auth.sh`. 
* We cant always guarantee that auth will be set when we start/rebuild the app eg its really only true if you `lando init` first so it feels like we generally need a better place to do all of this. If LOCKR was not a consideration then we wouldnt even need to do any authy things during start/rebuild.

@dustinleblanc im also down to assist/pair on this.

**Comment by dustinleblanc** [comment]
Got started on this today. Accomplished 1, working on 2.

@pirog I assume the way we validate the machine token is to attempt to auth with Pantheon? That is what my working code is doing so far and it seems to be tanking during the auth process so I'll have to figure that out or pivot.

**Comment by pirog** [comment]
@dustinleblanc yes we use the code in `api.js` to do that auth. 

I think the implementation is we only want to show the `auth` option interactively the way it currently does OR if the currently set token fails auth. This should happen in the `when` key on the interactive options.

**Comment by dustinleblanc** [comment]
Spent some time on this today. The issue that I am running into is that if a token doesn't validate, we're currently immediately bailing in the client, so I think we might want to log those failures instead, and allow control to continue to flow to the call sites that make a request and allow them to the error themselves, which in this case would let me catch the 401 and just return false. Does that make sense?

**Comment by pirog** [comment]
Let’s take a few minutes to go over what you are doing because this
actually doesn’t make sense to me. I don’t think we should even be getting
to this level of things.
