### ISSUE TITLE
Fail on hello container test on W10

### ISSUE THREAD

**Issue by webmasterpf** [lando/lando#2412]
Hello,

Trying to run lando on a W10 machine with docker engine installed before and running.
After creating the lando file with cmd (not bash) I face off these errors on starting:

```
 ERROR ==>  message=, stack=Error
    at C:\snapshot\lando\build\cli\lib\shell.js

ERROR: for ca  Cannot create container for service ca: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"
```

Any idea o what's wrong ? I'm able to create ocntainers as a part with docker4drupal for example.
My version of Lando is 3.0.5 and Docker Desktop 2.3.03 and Docker Engine is 19.03.8

Thanks

**Comment by dustinleblanc** [comment]
Based on the error message. It would seem that you aren't sharing the default directories Docker usually uses, which Lando depends on to function properly. Docker4Drupal doesn't use the same folders we do to function, so it would be expected that they would behave differently.

**Comment by webmasterpf** [comment]
Fixed by adding C:\ in file sharing setting in docker desktop.
Then containers can be created and test is ok, but only reachable via http://localhost:32779 , vhost is not functionnal, proxy issue I think.. I can go forward to install a D8 multisite ( dockerize my existing LAMP multisite), a little bit more complicated ? :)

**Comment by dustinleblanc** [comment]
It will definitely be easier if you can figure out your proxy issue. Might want to just make sure nothing else is running on Port 80 on the machine and that you don't have a DNS rebinding issue or something.
