### ISSUE TITLE
p.sh custom solr config is not loading correctly

### ISSUE THREAD

**Issue by pirog** [lando/lando#2416]
Steps to replicate:

1. Start up the `lando-kitchensink` example

You should then be able to verify this in two ways:

1. `lando logs -s search`

If you backscroll a bit you should see something like

```bash
search_1         | 2020-06-24 14:00:54,711 platformsh.agent.service ERROR Unable to unpack the custom configuration archive: not a gzip file
search_1         | Traceback (most recent call last):
search_1         |   File "/etc/platform/config.py", line 257, in _extract_configure_files
search_1         |     self._extract_archive(archive, destination)
search_1         |   File "/etc/platform/config.py", line 279, in _extract_archive
search_1         |     tf = tarfile.open(mode="r|gz", fileobj=f)
search_1         |   File "/usr/lib/python2.7/tarfile.py", line 1703, in open
search_1         |     stream = _Stream(name, filemode, comptype, fileobj, bufsize)
search_1         |   File "/usr/lib/python2.7/tarfile.py", line 430, in __init__
search_1         |     self._init_read_gz()
search_1         |   File "/usr/lib/python2.7/tarfile.py", line 524, in _init_read_gz
search_1         |     raise ReadError("not a gzip file")
search_1         | ReadError: not a gzip file
```

2. `lando info -s search` 

Click on the solr admin ui link, it should be the `localhost` address in the `urls` key. Once there:

1. Select `maincore` and then navigate to `files->schema.xml` and scroll down. You should see something like this

```
<schema name="drupal-5.4-solr-6.x" version="1.6">
```

This is not the same name as the `schema.xml` in `.platform/solrconfig-6.x` which is `drupal-5.5-solr-6.x`.

**Comment by mikemilano** [comment]
Questions to work through with Platform.sh:

## 1. gzip File Error
The solr logs show a gzip file error triggered by `/etc/platform/config.py`. If this error is not OK to ignore, what file is it expecting to find?

## 2. `!archive` breaks our YAML parsing
[This](https://docs.platform.sh/frameworks/drupal8/solr.html) documentation instructs the user to set the solr config directory as below. `!archive` breaks our yaml parsing. Is `!archive` required? Then if so, should it work on platform's end if we wrap the entire value in single quotes? i.e. `'!archive "solr_8.x_config/"'`
```
search:
    type: solr:8.0
    disk: 1024
    configuration:
        cores:
            maincore:
                conf_dir: !archive "solr_8.x_config/"
        endpoints:
            main:
                core: maincore
```

## 3. Path to Solr config
With #2 resolved, according to the [Drupal/Solr documentation](https://docs.platform.sh/frameworks/drupal8/solr.html), the solr config directory is placed in the `.platform` directory.

For example, a service definition with `conf_dir: !archive "solr_8.x_config/"` reflects an absolute path from within the container of `/app/.platform/solr_8.x_config/schema.xml`.

- Are we understanding this correctly?
- Should the Solr image copy the contents of this config to `/mnt/data/solr/maincore/conf/`?
  - If not, how do we evaluate if this should work?

## 3. Solr Schema version
The platform documentation references version `8.0` for the solr service, but the [search_api_solr](https://www.drupal.org/project/search_api_solr) module does not contain `8.x` schema. The highest version of solr config in that module is 6.x.

What is the recommended schema and service version to test with?

**Comment by pirog** [comment]
@mikemilano so my guess is that on platform the following happens

1. `!archive` instructs the `dir` eg `"solr_8.x_config/"` to be compressed into an archive 
2. That archive is then extracted into the config directory for the core its associated with eg `/mnt/data/solr/maincore/conf/` and things work as expected.

I think the two most obvious paths forward here are:

1. Figure out how to get `!archive` to work correctly (we'd probably need the assist from @ralt here)
2. Just directly mount or copy `conf_dir` to `/mnt/data/solr/CORENAME/conf/`

IIRC you can use the `search_api_solr` 6.x config on 8.x. If you can't we should just find some other 8.x compatible config to test this with. It need not be drupal specific config.

**Comment by ralt** [comment]
What ends up in the config.json is a base64 of the .tar.gz when `!archive` is used.

**Comment by pirog** [comment]
@mikemilano https://docs.platform.sh/configuration/yaml.html

**Comment by mikemilano** [comment]
I'm testing `conf_dir: !archive "solrconfig-6.x/"` on the `master` platform.sh environment and there is no `cores.maincore.configdir` defined in `/run/config.json`.

With Lando, I do see a value in `/run/config.json`. I wanted to compare what it was doing on the remote environment vs local.

@ralt should `config.json` be populated the same way with respect to the solr core config directory whether it is in Lando or on the remote env?

**Comment by ralt** [comment]
@mikemilano you're looking at the application container. Try using !archive in a random property of the app.yaml, and you should see it in the config.json.

**Comment by pirog** [comment]
As i understand it as long we we implement `!archive` in Lando's YAML spec so that it tars the given directory and then `base64` encodes that everything else should "just work"

@mikemilano im guessing we could test that assumption by archiving and `base64` encoding `solrconfig-6.x/` manually and then setting `conf_dir` with that value.

@ralt does that sound about right?

**Comment by pirog** [comment]
ok, i can confirm that directly setting `conf_dir` to the expected `base64` string works so i'm going to spin up another ticket for us to implement `!archive` and `!includes` since having those things working correctly should resolve this.

**Comment by ralt** [comment]
:+1:

**Comment by pirog** [comment]
alright @mikemilano i was able to implement `!archive` which resolves this
https://github.com/lando/lando/pull/2424

ill spin up a separate ticket so we can also implement `!includes`
