### ISSUE TITLE
Configure pluginDirs in .lando.yml

### ISSUE THREAD

**Issue by iluuu1994** [lando/lando#2425]
Thanks for Lando! I wanted to ask this question on Slack but for some reason the form for joining would just submit doing nothing.

We have our own CMS and would like to create our own recipe because the configuration for all of our dozens of project would be pretty much the same. We were planning to distribute the config as a Git submodule and just mark the submodule as a plugin directory. However, reading the docs I'm not entirely sure it that is possible.

> Lando will search in the plugins directory for any path listed in lando.config.pluginDirs and automatically load in any plugins that it finds. By default, these directories are the Lando source directory and ~/.lando but note that they are configurable via the Lando global config.

Am I interpreting it correctly that `pluginDirs` can only be configured system wide and not on a project by project basis?

Thanks for your response!

**Comment by dustinleblanc** [comment]
Hey @iluuu1994! Thanks for sponsoring!

I believe you are correct and we currently disallow adding plugins in the application directory. We're currently in the middle of planning the next phase of the plugin system, so this question is pretty relavent. For now, the easiest way to get this rolling, which is probably less than ideal, would be to include instructions for the dev to download the plugin as a oneliner (git clone to `~/.lando/plugins/awesome-plugin`). We're definitely looking to improve this workflow so all folks would have to do is run `lando start` and we'll just fetch plugins you list in your .lando.yml for you, but we aren't there yet.

**Comment by iluuu1994** [comment]
Hi @dustinleblanc, thanks for your very fast response! Your suggestion should work well enough until application plugins are available for which we'll be patiently waiting 🙂 Thanks!

**Comment by pirog** [comment]
@iluuu1994 in the forthcoming lando 3.0.8 release you will be able to do this
https://docs.lando.dev/config/plugins.html

**Comment by iluuu1994** [comment]
That's amazing, thank you so much! 😊
