### ISSUE TITLE
Lando tooling should take the option delimiters (--) into account

### ISSUE THREAD

**Issue by codebymikey** [lando/lando#2439]
Lando version: v3.0.5 on Windows 10 Professional

.lando.yml:
```yml
name: my-first-drupal8-app
recipe: drupal8
config:
  webroot: .
```

Lando tooling should take into account where `--` [option delimiters](https://unix.stackexchange.com/a/570733) are passed in, and stop processing the options, passing everything directly to the relevant tooling command.

This makes it difficult to run commands like `lando drush status -vv` which also share a similar `-vvv` argument without it also affecting lando.

We should instead be able to run it like:
```bash
lando -- drush status -vv
```
such that all the typical lando arguments are ignored, and everything else is passed into the relevant tooling script for processing.

**Comment by pirog** [comment]
@codebymikey i dont think this is something we plan on doing. afaik the only place where the options are shared by both lando and the tooling command is `-vvv` and that is actually by design.

i also am not sure this format would play with with the options parser we use under the hood or for tooling commands that themselves require use of `--`

**Comment by codebymikey** [comment]
> i also am not sure this format would play with with the options parser we use under the hood or for tooling commands that themselves require use of --

My thinking for this would be to detect the sole use of `lando --` directly (when tooling is involved) and act accordingly rather than all instances of `--`, as I can imagine that would break existing tools.
Such that:
- `lando -- drush -vvv` => `drush -vvv` (lando arguments aren't parsed)
- `lando -- drush -- status -vvv` => `drush -- status -vvv` (lando arguments aren't parsed)
- `lando drush -- status -vvv` => `drush -- status -vvv` (keeps existing behaviour, where `-vvv` also affects `lando`)

This approach shouldn't break existing tooling commands, and I think makes the tooling more flexible when the internal tooling shares similar arguments to Lando that you don't want Lando using, the main ones being `--help` and `--verbose`, but more obscure tooling might conflict with other Lando arguments in the future, and I think it should be possible to avoid those scenarios if needed.

I haven't looked at the tooling code in much detail, but I understand if it's not high priority especially if the code is particular complex.

Is this something you're looking to accept if it was implemented as a PR?

**Comment by pirog** [comment]
@codebymikey i think we would merge a PR for this as long as:

1. This would be a secondary syntax for tooling commands, eg this would not change the existing tooling syntax. It probably also makes sense to document this syntax as an explicit way to separate args from `lando` and a subcommand. im not sure what other purpose it would serve..
2. Your spec makes sense to me but its particularly important that any `--` AFTER the subcommand is not interpreted by lando eg in `lando drush -- status -vvv` the `--` needs to be handled by `drush` and not by `lando`. 

Again, its worth pointing out that the _only_ place i am currently aware of this being a problem is with `--verbose`, Lando is usually smart enough to figure out `--help` so this seems like a lot of effort to address a concern that probably ranks very low in our currently list of concerns.

This would also require

* Updates to the documentation to reflect this as a secondary usage and WHY this usage should be used in some circumstances
* Updates to the tooling example functional test to make sure things work as expected

How does that all sound?

**Comment by codebymikey** [comment]
@pirog, that all makes sense to me.

I agree that it's not that important in the grand scheme of things (I can live with the verbose logs, I'd just like a way to hide it if possible).

I'll have a play around with the lando code in my spare time and see how feasible it'd be to implement without having to refactor much of the code.
