### ISSUE TITLE
Research lagoon init/pull/push from lagoon api

### ISSUE THREAD

**Issue by pirog** [lando/lando#2450]
Just a place to take notes for @pirog 

### Lagoon CLI

```bash
curl -L "https://github.com/amazeeio/lagoon-cli/releases/download/0.9.1/lagoon-cli-0.9.1-linux-amd64" -o /usr/local/bin/lagoon
chmod +x /usr/local/bin/lagoon
```

Above worked on my mac but not inside the lagoon cli container:

```bash
lagoon
bash: /usr/local/bin/lagoon: No such file or directory
bash lagoon
lagoon: lagoon: cannot execute binary file
``` 

More notes:

* Docs https://amazeeio.github.io/lagoon-cli/commands/lagoon/

```bash
lagoon login 
lagoon whoami
lagoon get project -i ~/.ssh/id_rsa2 -p drupal9-example-simple -e drupal9-example-simple-9-x
lagoon list projects
```

### Lagoon API

Get a token

```
 ssh -p 32222 -t lagoon@ssh.lagoon.amazeeio.cloud -i "~/.ssh/id_rsa2" token 2>/dev/null
```

Easier way to get token eg some request we can make?
GRAPHQL setup docs are pretty good: https://lagoon.readthedocs.io/en/latest/using_lagoon/graphql_api/ as is the GQL client req. 

Easy to check out the GQL query with `--debug` as in
```bash
lagoon list projects --debug
lagoon whoami --debug
```

Note that not all commands currently provide the nice response.

### Pull/Push

Use `drush la` and then use drush aliases for db and files sync. Either set the default pull environment to `current` (eg the environment that matches the branch you are on) or `production`.

### Lando init flow

This is just a place to start

1. on first init a public key is generated and lando requests user to add to amazee as needed (eventually we might need to handle more than one key)
2. subsequent inits use that key for auth unless the key is revoked for some reason, if so it goes back to 1.
3. use key to get token (better way to do this?)
4. List projects like we do for other flows? (what about environments?) default branch?
5. Clone project down using metadata

Note that for getting a token we should run the `ssh` command straight up if we can but otherwise we will need to run it inside of a container eg on Windows.

### Things we need

- [x] A Lagoon CLI binary that works inside the Lagoon CLI image eg alpine linux, or a lagoon CLI container
- [x] Augment metadata for `lagoon list environments` to include the prod branch
- [ ] `--debug` working consistently would greatly help with GQL query discovery, see diff between `lagoon whoami --debug` and `lagoon list projects --debug`. 
- [x] Better guidance around getting a token
- [x] `drush la` should have a way to specify the ssh key to use
- [x] Figuring out the flow for `lando init`

@thom8 @tobybellwood these are just notes for now but wanted to give you some visibility

**Comment by pirog** [comment]
Alright @tobybellwood and @thom8 i updated the description above with notes from our call.

**Comment by thom8** [comment]
Removed dependency on `LAGOON_PROJECT` being set as an environment variable --

https://github.com/amazeeio/drupal-example-simple/commit/f16c78a00b21555829a04aefe9698b9ad4060a8a

The only place the lagoon project name needs to be defined is in `.lagoon.yml` -- https://github.com/amazeeio/drupal-example-simple/blob/9.x/.lagoon.yml#L3

and needs to match the lagoon project name in the Lagoon API to authenticate via SSH and use drush aliases.

**Comment by thom8** [comment]
- Production branch is now included in output of `lagoon list projects` from version [0.9.2](https://github.com/amazeeio/lagoon-cli/releases/tag/0.9.2)
-  `amazeeio/lagoon-cli` image released, requires home directory to be mounted for authentication. eg. `docker run -ti -v $HOME:/root amazeeio/lagoon-cli list projects`
