### ISSUE TITLE
chmod folders as post-destroy event

### ISSUE THREAD

**Issue by gitressa** [lando/lando#2452]
I like the way `lando destroy` removes the `web` folder in [Drupal Contributions](https://github.com/thinktandem/drupal-contributions), so I can do a `cd .. && rm drupal-contributions -rf` immediately afterwards, without having to `chmod -R 755 web/sites/default` first. Is it worth considering making this bit a part of the default `destroy` command in Lando?

```
events:
  post-destroy:
    - rm -rfv web
```
From https://github.com/thinktandem/drupal-contributions/blob/master/.lando.yml#L52

A less destructive, but still quite helpful feature would be adding `chmod -R 755 sites/default` and/or `chmod -R 755 web/sites/default` as a `post-destroy` event.

**Comment by pirog** [comment]
I'd be very much against this. 

Lando is not drupal specific and even if this were targeted to just drupal recipes we cant make a ton of assumptions about how a users Drupal site is setup. I know if i were using this and unaware of this automation id probably be like WTF did my `web` folder go?

On a higher level i think the idea of Lando is to provide users with a bunch of tools so they can easily construct automations, etc that make sense for them. If Lando _knows_ that something can be set universally to make things easy it will try to do that, but if i cant then its likely helping the people who shares its opinions at the expense of those who do not.

**Comment by gitressa** [comment]
I get your point about deleting a folder, though I don't think running a `chmod -R 755` is that big of a deal, since it's not likely to break anything.

**Comment by gitressa** [comment]
I thought more about it, and you're right, deleting folders is going too far. I actually just used `lando destroy` repeatedly in a project, where I certainly didn't want any folders to disappear.

I still think an innocent `chmod -R 755` in `sites/default` after `lando destroy` would be worth contemplating.

**Comment by naveenvalecha** [comment]
@gitressa I'm using the drupal-contributions package with 10.x branch, and I'm getting this error 
`chmod: changing permissions of '/app/web/sites/default': Permission denied`
On debugging, I found this is coming from [rebuild.sh](https://github.com/lando/drupal-contributions/blob/10.x/scripts/rebuild.sh#L5), which is in Lando.yml post-rebuild event
Did you get any solution for it?

**Comment by gitressa** [comment]
I just tried installing it, and everything works fine ... can you perhaps share the steps required to reproduce the error?

**Comment by naveenvalecha** [comment]
@gitressa After switching to 9.x of https://github.com/lando/drupal-contributions I'm no longer seeing this error.

**Comment by gitressa** [comment]
Great to hear that you got it working @naveenvalecha.
