### ISSUE TITLE
lando push to pantheon with selection, selected unexpected behavior.

### ISSUE THREAD

**Issue by philwilliammee** [lando/lando#2456]
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
Lando: v3.0.7
OS: Ubuntu 20.04 LTS

**Tell us about your `.lando.yml`**

```yml
name: xxx
recipe: pantheon
config:
  framework: drupal8
  site: xxx
  id: fxxx-xxxx
```

**Tell us about the command you were running**
```bash
lando push
? Push code to? none
? Push database to? dev
? Push files to? none
```

**Tell us about the error you got**
No Errors

**Tell us generally about your bug**
After `lando push` selections were ignored and lando pushed (and committed) code, database, and files to multidev" .

```bash
Connected with git
Pushing code to MULTIDEV as  ...
Already on 'MULTIDEV'
Your branch is up-to-date with 'origin/MULTIDEV'.
[MULTIDEV] My Awesome Lando-based commit
 1 file changed, 74 insertions(+)
...
Pushing your database... This miiiiight take a minute
Validating you can push files to MULTIDEV...

```

**Tell us more**
retested two times with same results. 
pushing with cli args worked as expected.
```bash
lando push --code=none --database=dev --files=none
Making sure your database is awake!
 [notice] OK >> dev-SITE.pantheonsite.io responded
...
```

**Comment by danny2p** [comment]
Same on pull for me.

**Comment by romerocs** [comment]
Also experiencing this issue on with v3.0.7

**Comment by dustintitus** [comment]
Also experiencing the message "My Awesome Lando-based commit" after a lando push (code-y; db-no; files-no) w commit message "My custom commit message". Why would it not push my custom message with the push to pantheon? Thanks!

**Comment by tripflex** [comment]
Yeah for me it's constantly pulling from dev instead of the multidev env i selected, took me a minute to figure out that was happening

**Comment by pirog** [comment]
This is definitely a regression but will be fixed in our next release which should roll out sometime in the next 24 hours.
