### ISSUE TITLE
 port to the url in the proxy not working

### ISSUE THREAD

**Issue by yuseferi** [lando/lando#2463]
Generally these questions should end up as guides
https://docs.lando.dev/config/proxy.html#routing-to-a-different-port

this is my land file 

```
name: baxter
services:
  appserver:
    type: apache
    webroot: ./dist
    ssl: false
proxy:
  appserver:
    - febaxter.lndo.site:33777
```
and as you can see in result of `lando start` ( `lando rebuild`) , **there is no sign of my custom port on URL**
```
Your app has started up correctly.
Here are some vitals:

 NAME            febaxter                                        
 LOCATION        /Users/yuseferi/project/vuejs 
 SERVICES        appserver                                       
 APPSERVER URLS  http://localhost:32833                          
                 http://febaxter.lndo.site/                      
```

the question is how can I set custom port for that . 

my lando version is the latest at the moment 3.0.7.

Thanks

**Comment by pirog** [comment]
@yuseferi read the docs over again. I do not think this feature does what you think it does.

**Comment by yuseferi** [comment]
Hi @pirog ,

thanks a lot for your replying,  it seems that port is just for exposing port in the container not external one that I access through the URL.

So, let me change the question, 
is there any way to define a specified port for app that makes the app accessible via it.

instead of that partially random port number "http://localhost:32833"  make it available on defined port "http://localhost:xxxxx" or even through custom URL with a custom port like "febaxter.lndo.site:xxxxx".

Thanks a lot.

**Comment by pirog** [comment]
You can use Lando service overrides and set the ports directly using Docker Compose
https://docs.lando.dev/config/services.html#overrides

You could also configure the proxy itself to run on a different port
https://docs.lando.dev/config/proxy.html#configuration

All that said im curious what your use case is? It's not very common to need to lock down the ports in this way for localdev.

**Comment by yuseferi** [comment]
Thanks @pirog for the reply.

the case is that, we use lando for drupal development, and in a decoupled solution, a FE team develop  FE part based on Vuejs, 
we have 4 environments,
local
dev
qa(stage)
prod

for each environment, we should use different  BE endpoints, 
as a backend developer, I'd like to do not create a build for debugging so I suggested a solution to FE guy to detect BE base URL base on the url.


```
const urls = [
  {
    domain: 'prjqa.aws.domain.com',
    url: 'https://prjqa-admin.aws.domain.com',
  },
  {
    domain: 'prjdev.aws.domain.com',
    url: 'https://prjdev-admin.aws.domain.com',
  },
  {
    domain: 'localhost:32769',
    url: 'http://domain-admin.lndo.site',
  },
  {
    domain: 'localhost:8080',
    url: 'https://prjdev-admin.aws.domain.com',
  },
];

export function getEnvBaseApiUrl() {
  const { host } = window.location;

  const activeUrl = urls.find((url) => url.domain === host);

  if (activeUrl && activeUrl.url !== '') {
    return activeUrl.url;
  }

  return process.env.VUE_APP_BASE_API_URL || '';
}

export default {
  getEnvBaseApiUrl,
};

```

but if     **domain: 'localhost:32769',** change in any `lando start` then I need to create another build.

**Comment by yuseferi** [comment]
additionally, I have two lando app, one for BE and one for FE. I think 
>You could also configure the proxy itself to run on a different port
>https://docs.lando.dev/config/proxy.html#configuration

not working for me. but I'll try to override the port. 

Thank you.

**Comment by yuseferi** [comment]
**The solution for my case**


```
name: myapp
services:
  appserver:
    type: apache
    webroot: ./dist
    ssl: false
    moreHttpPorts:
      - '33666'
    overrides:
      ports:
          - 33666:80
```

now it's available on localhost:33666 every time I run it.

**Comment by pirog** [comment]
@yuseferi its not clear to me why you need to use localhost instead of just using the lando proxy domains straight up. Either way be careful locking down a port like that.
