### ISSUE TITLE
Lando pull -- pulling from wrong environment

### ISSUE THREAD

**Issue by tripflex** [lando/lando#2471]
After upgrading to 3.0.7 seems when you use the menu to select a multidev (or at least the environment) to pull data from, for me it results in using the `dev` environment:

```
➜  mysite git:(master) ✗ lando pull
? Pull code from? multidevsite
? Pull database from? multidevsite
? Pull files from? multidevsite
Attempting to login via terminus...
 [notice] Logging in via machine token.
Logged in as ***
Verifying that you have access to NAME...
 ------------------ -------------------------------------------------------------------------------------
XXX
 ------------------ -------------------------------------------------------------------------------------
Access confirmed!
Certificate will not expire
Cert is good!
Validating you can pull code from dev...
```

Whereas using:
` lando pull --code=multidevsite --database=multidevsite --files=multidevsite`

Seems to work correctly, not sure if it's related to my ZSH environment or something else in the latest release, just wanted to mention it :)

Possibly related to #2456

**Comment by pirog** [comment]
This is definitely a regression but will be fixed in our next release which should roll out sometime in the next 24 hours.
