### ISSUE TITLE
github oauth chaos: token not read by composer, wrong symlink etc.

### ISSUE THREAD

**Issue by com2** [lando/lando#2474]
"lando composer update" has lost it charme in lando. I get repeatedly this error message: 

> Your GitHub credentials are required to fetch private repository metadata (a long github package path)
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ff6ef4357540+2020-07-14+2331
> to retrieve a token. It will be stored in "/app/auth.json" for future use by Composer.
> Token (hidden): 
> 

When I add a valid (resently reset or created) token the process continues and supposedly should not ask this again, because it is from then on stored in /app/auth.json ( I confirmed that it is ). 

So to get around this irritating bug I tried other options. One is to put the oauth token in the composer.json but that apparently is ignored too. The last option I tried was the one that is suggested when you provide an invalid token:

> You can also add it manually later by using "composer config --global --auth github-oauth.github.com <token>"
> 
> Could not fetch "a long github path" , please review your configured GitHub OAuth token or enter a new one to access private repos
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ff6ef4357540+2020-07-14+2331
> to retrieve a token. It will be stored in "/app/auth.json" for future use by Composer.
> 

So I tried the "composer config --global --auth github-oauth.github.com mytoken" but that comes back with another error: 

> [ErrorException]                                                                                 
>   touch(): Unable to create file /var/www/.composer/config.json because No such file or directory

Then I followed through on this one a bit. Using lando ssh I found out that /var/www/.composer/config.json is a symlink to /user/.composer/config.json which on my system would be /home/my-linux-user>/.composer/config.json where it does NOT exist  but in /home/my-linux-user/.config/composer/config.json ( composer global user path for Ubuntu 16.04LTS also in 18.04LTS) where it would have picked up the right token I still had stored from before Lando.  

So with _lando ssh_ I changed the symlink to /user/.config/composer/config.json. So it is now actually pointing to my system's composer config.json .  When I do _composer config --global --auth github-oauth.github.com mytoken_ again, it returns without error but there is no change in the config.json file! So this won't help me either. 

Btw I also did a _lando composer selfupdate_ to be sure it was not an issue of composer itself and I am using lando version 3.0.7 and the app has been recently rebuild. 

The only work around left to me is to attend the long update process and to repeatedly manually paste the token. I hope you find a way to fix this.

**Comment by pirog** [comment]
We use this method pretty frequently without error so I’m not really convinced this is a problem with lando. However if you want provide useful steps to replicate the bug instead of just ranting then we can look into it.
