### ISSUE TITLE
Ignore xdebug when clearing Drupal cache via Drush?

### ISSUE THREAD

**Issue by web-assistant** [lando/lando#2480]
I use xdebug a lot and I clear Drupal caches a lot via Drush. When I clear the cache using Drush it triggers xdebug. Is there a way I can make drush not trigger xdebug when clearing the cache? 

At the moment, I have to disable listening to connections (in PhpStorm) each time I clear the cache in Drush, and then enable it again to start debugging - or use a custom command created in the tooling section of the lando file. What I want is for the drush clear cache command to ignore xdebug.

**Comment by pirog** [comment]
@web-assistant i would search the issue queue here, there are people who have created tooling commands that will disable xdebug easily

**Comment by web-assistant** [comment]
Sorry, I should have been clearer. I don't want to disable xdebug (already have used tooling to quickly enable/disable xdebug), what I'm really looking for is for xdebug to ignore the drush cache clear command.

I have changed the title to make it more clear.

**Comment by pirog** [comment]
Got it. No idea whether that is possible but maybe someone else knows.

**Comment by mrweiner** [comment]
@web-assistant if you've got drush in your project, you can setup a tooling command just for rebuilding the cache

>   cr:
>     service: appserver
>     description: Disable xdbebug, clear drush cache
>     user: root
>     cmd:
>       - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm || /etc/init.d/apache2 reload
>       - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
>       - echo 'Rebuilding Cache ...' && 'echo'
>       - /app/path_to_your_vendor/bin/drush cr --root=/app/path_to_project_root

You'll just need to re-enable xdebug afterward unless you add that to as well
