### ISSUE TITLE
`lando push` message only passing the first word in interactive mode

### ISSUE THREAD

**Issue by wonkeythemonkey** [lando/lando#2492]
### Problem Description

When I use `lando push` in interactive mode to push a code change to my Pantheon site,
only the first word of the `What did you change?` message is passed as the git commit message.

I can work around this problem by including quotation marks explicitly around my message, but it seems like the message should be implicitly assumed to be a single string without needing quotes.

### Steps to Reproduce

Run a simple `lando push` command, setting "files" to the dev environment and everything else to "none" using the interactive interface:

```bash
$ lando push
lando push
? Push code to? dev
? Push database to? none
? Push files to? none
? What did you change? Added new config file
```

### Results

The push completes without any error messages, but the commit message passed to the Pantheon repository only contains the first word:

![aerovistainnovations___Pantheon_Dashboard](https://user-images.githubusercontent.com/4974766/87796786-d31e4200-c817-11ea-9a3f-c3982f91fa20.png)

The terminal output for the command showed no errors. Below are the relevant lines from my terminal output:

```
Attempting to login via terminus...
 [notice] Logging in via machine token.
Logged in as [user_id]
Verifying that you have access to site_name...
 ------------------ ------------------------------------------------------------------------------------- 
[site details removed for this report]       
 ------------------ ------------------------------------------------------------------------------------- 
Access confirmed!
Certificate will not expire
Cert is good!
Validating you can push code to dev...
 ----------------- ------------------------------------------ 
[site details removed for this report]                                
 ----------------- ------------------------------------------ 
Confirmed!
Checking connection mode
Connected with git
Pushing code to dev as [user name] ...
M       .lando.yml
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[master dc79f273e] Updated
 1 file changed, 10 insertions(+), 10 deletions(-)
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 360 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To [url of git repository]
   77238eadb..dc79f273e  master -> master
Push completed successfully!
```

### Workaround

By including quotation marks around the message, I can get the entire message to show up:

```bash
$ lando push
lando push
? Push code to? dev
? Push database to? none
? Push files to? none
? What did you change? "Modified lando config file"
```
![aerovistainnovations___Pantheon_Dashboard](https://user-images.githubusercontent.com/4974766/87797576-e1b92900-c818-11ea-9819-9fcc083d0497.png)

### Environment Setup

* Lando v3.0.8
* MacOS 10.15.4
* zsh 5.8 (x86_64-apple-darwin19.3.0)

**`.lando.yml`**

```yml
name: site_name
recipe: pantheon
config:
  framework: wordpress
  site: site_name
  id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  xdebug: true
```

**`pantheon.yml`**

```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

**Comment by pirog** [comment]
This is a regression likely caused by this commit https://github.com/lando/lando/commit/97827f140605dc6df074cf10e6666954733df464

This should be worthy of a hotfix release

**Comment by pirog** [comment]
alright, thanks for the report @wonkeythemonkey, there will be a hotfix release later today/tonight with this fixed!
