### ISSUE TITLE
Create global plugin mgtm commands

### ISSUE THREAD

**Issue by pirog** [lando/lando#2493]
We need some lando commands to better assist in plugin management. For now lets start with "global" plugins 

#### CLI Usage

**Global**

```bash
# Add/remove a plugin globally
lando plugin:add -g myplugin
lando plugin:remove -g myplugin

# The "package" convention should be the same as the YARN spec but should also 
# resolve "official lando packages"
lando plugin:add -g lando-power@1.2 # behind the scenes this might actually do `yarn add lando/lando-power#1.2`
lando plugin:add -g pirog/piroplugin#commitref
lando plugin:add -g my-plugin-on-npm@^1
```

### Action Items

- [ ] Implement commands
- [ ] Create func tests
- [ ] Update plugin docs and cli usage docs

See https://github.com/lando/lando/issues/2434 for more details

**Comment by dustinleblanc** [comment]
I started work on this last week when I had a tiny gap before vacation as a way to wind down before I left. Registering the command was easy, next thing to figure out is how we want to start a node container to execute the npm commands.
