### ISSUE TITLE
[v3.0.9] WSL2 issue

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#2499]
Important to note is this behavior happens in the WSL2 terminal and Lando was installed within the environment.

```bash
$ lando init
? From where should we get your app's codebase? pantheon
? Enter a Pantheon machine token [hidden]
? Which site? mysite
Creating network "landoinitmysite_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.24.0.0/16 ! -o br-040674f79886 -j MASQUERADE: iptables: No chain/target/match by that name.
 (exit status 1))
Removing network landoinitmysite_default
WARNING: Network landoinitmysite_default not found.
Removing volume landoinitmysite_data_init
WARNING: Volume landoinitmysite_data_init not found.
Removing volume landoinitmysite_home_init
WARNING: Volume landoinitmysite_home_init not found.
ERROR ==>
```
This error is not isolated to Pantheon recipes.  It happens on a basic Drupal 8 recipe as well.

System specs below:
```bash
$ lando version
v3.0.9
$ uname -a
Linux DELL-PRECISION-M6700 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ docker -v
Docker version 19.03.12, build 48a66213fe
$ docker-compose -v
docker-compose version 1.25.3, build unknown
```

![image](https://user-images.githubusercontent.com/387945/81479290-f14c3e00-91e7-11ea-8f70-10c709b72ba0.png)

![image](https://user-images.githubusercontent.com/387945/87858522-1a7a0080-c8f4-11ea-8158-a4147a7cb60d.png)

**Comment by lsmith77** [comment]
the issue might be related to the warning here https://blog.calevans.com/2020/06/18/making-lando-work-inside-wsl2/
ie. recommendation is to install docker inside WSL2 and disable docker integration from windows.

**Comment by uberhacker** [comment]
Thank you @lsmith77.  I had talked to @dustinleblanc earlier today about the same thing.

**Comment by lsmith77** [comment]
@dustinleblanc those hints should likely in some form be added to the docs?

**Comment by dustinleblanc** [comment]
@lsmith77 we have a ticket on here to write a WSL2 guide. Ironically, the Linux drivers for my laptop finally got good enough in the latest kernel that I am running Fedora 32 on the machine I used to set it up originally. I do still have a Win 10 box that I could run through the steps on again though. Cal Evans blog post did a good job outlining how to do it.

**Comment by uberhacker** [comment]
@dustinleblanc: I followed all the instructions at https://blog.calevans.com/2020/06/18/making-lando-work-inside-wsl2/ and I'm still unable to get docker running inside WSL2.

**Comment by ayalon** [comment]
I have a running setup and it's super fast.
I setup Lando inside Ubuntu 20.04 and Windows Docker Desktop (WSL2). My test project has more than 40'000 files and it is amazing to see how fast composer runs.
The speed is absolutely amazing, is basically native, because all files are saved on an ext4 hd inside WSL2.

I also found a viable way to work on my projects using PHPStorm in Windows.
I setup mutagen.io to sync my docker container back to a Windows folder, which gives my native performance while working with PHPStorm.

The only thing I was not able to get working was xdebug with lando because the networking quite complex, but I'm pretty sure I also manage to fix this issue.

My recipe:
- Docker Desktop Edge installed on Windows
- Ubuntu 20.04 WSL2 enabled
- Lando 3.0.9 installed on Ubuntu 20.04 (you have to hack the dependancy docer-ce)
- Project saved on ext4 aka ~/ folder
- mutagen.io sync from container back to a Windows NTFS folder.

**Comment by uberhacker** [comment]
Thank you for the feedback @ayalon.  Any way you can expand on what you mean by hacking the dependency docker-ce?  I am unable to start the docker service inside the WSL2 terminal session.  I assume this means I need to configure Docker Desktop instead.  One thing I did find out is WSL2 will not work unless Docker Desktop is running which completely eliminates any "native" performance claims.

**Comment by ayalon** [comment]
Forget about trying to install docker inside Ubuntu. Uninstall docker inside WSL2.
Install Windows Docker Desktop Edge.

Then install Lando inside Ubuntu 20.04. Follow the documentation about Linux / CLI
https://docs.lando.dev/basics/installation.html

`
wget https://github.com/lando/lando/releases/download/v3.0.9/lando-v3.0.9.deb
sudo dpkg -i  --ignore-depends=docker-ce lando-stable.deb
`
Then delete lando from `/var/lib/dpkg/status` as stated in the documentation.

Double check, that your WSL Ubuntu20.04 is running with WSL2
`wsl --list --verbose`

And make sure in Windows Docker Desktop WSL2 is enabled. When starting lando, I had an error about the credential manager. Do a `docker login` inside your WSL2 Command line.

**Comment by uberhacker** [comment]
Thanks @ayalon.  FWIW, my distro was stuck on WSL1 because of [this issue](https://github.com/microsoft/WSL/issues/4103).  Windows is always a total PITA.  I will close since this is not related to Lando.
