### ISSUE TITLE
MacOS Height Seirra | ENOTDIR

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#2501]
OS : MacOS High Sierra version 10.13.6

Docker : version 19.03.8, build afacb8b

Lando : v3.0.9

when try to start lando with command line "lando start", i get this error : 

`==> ENOTDIR: not a directory, scandir '/Users/kamal/.ssh'`

 any idea how to fixe this issue ??

Thank you

**Comment by pirog** [comment]
@kamalkech this is likely a regression. as a workaround you can probably just create that directory manually and then proceed

```
mkdir -p ~/.ssh
```

**Comment by pirog** [comment]
this will be fixed in the next release
