### ISSUE TITLE
Create commands for app level plugin management

### ISSUE THREAD

**Issue by pirog** [lando/lando#2502]
This will work the same as installing global plugins (see #2493) but with the following differences

* The `-g` flag should not be used
* The command requires a Landofile exist in the CWD, it should error if you arent "in an app". 
* The command should install the plugins into `.lando/plugins` (or other dir if we dont like that one) relative to the Landofile
* The command should update the Landofile to list the plugins like this, note that the syntax here should be the YAML version of whats in a normal `node` `package.json`

```yaml
name: myapp
plugins:
  myplugin: "1.2"
  lando-power: "^1
```

Some questions that still need to be answers:

* Do we want to automatically create/update `.gitignore` with `.lando/plugins`, tell the user they need to do this, do nothing? something else?
* Do we want to also automatically add `.lando/plugins` to `pluginDirs` or should `.lando/plugins` _always_ be scanned for plugins eg always added to https://github.com/lando/lando/blob/master/bin/lando.js#L44?

For reference this is the proposed syntax:

```bash
# Add/remove a plugin globally
lando plugin:add myplugin
lando plugin:remove myplugin

# The "package" convention should be the same as the YARN spec but should also 
# resolve "official lando packages"
lando plugin:add lando-power@1.2 # behind the scenes this might actually do `yarn add lando/lando-power#1.2`
lando plugin:add pirog/piroplugin#commitref
lando plugin:add my-plugin-on-npm@^1

# Install plugins that are found in the users Landofile, error if no app is found
# Note this command does not have a global variant
lando plugin:add 
```

See https://github.com/lando/lando/issues/2434 for more detail

**Comment by serundeputy** [comment]
> Do we want to automatically create/update .gitignore with .lando/plugins, tell the user they need to do this, do nothing? something else?

  1. I would say recommend to them in docs that the user `.gitignore` the `.lando/plugins` directory
  2. If we are going to touch their code base I would prompt asking if they want us to add a `.gitignore` entry and they can say yes or no

1. is easier.

> Do we want to also automatically add .lando/plugins to pluginDirs or should .lando/plugins always be scanned for plugins eg always added to https://github.com/lando/lando/blob/master/bin/lando.js#L44?

  * Is there a big hit performancewise to add `.lando/plugins to https://github.com/lando/lando/blob/master/bin/lando.js#L44? If not that seems the most seamless UX

**Comment by pirog** [comment]
@serundeputy 

> I would say recommend to them in docs that the user .gitignore the .lando/plugins directory

definitely needs to go in the docs

> If we are going to touch their code base I would prompt asking if they want us to add a .gitignore entry and they can say yes or no

I agree with this in theory but im not sure what a good implementation would be eg do we want this to auto-prompt and thus be blocking? should it be opt-in via manual flag? we could do something like:

```yaml
# PLugin install and add .lando/plugins to gitignore
lando plugin:add --gitignore
```

And if the user runs `lando plugin:add` without `--gitignore` then we scan the gitignore and if there is no entry we can warn the user and recommend they run the command again with the `--gitignore` option

**Comment by hockdudu** [comment]
This issue has apparently become stale. Is this being tracked somewhere else, or has the development stopped?

**Comment by pirog** [comment]
@hockdudu these commands are going to live in the hyperdrive project which is soon to be under active development

**Comment by hockdudu** [comment]
@pirog Oh, I didn't know Hyperdrive. It sounds promising 😄
