### ISSUE TITLE
Document the difference between pre-release and other releases

### ISSUE THREAD

**Issue by hussainweb** [lando/lando#2505]
**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/installation.html#macos

**Describe the change you'd like**
I see that there some of the releases on GitHub releases page are marked as pre-release and others are not. For example, right now, 3.0.7 is marked as the latest release whereas 3.0.8 and 3.0.9 are marked as pre-release. It's not clear what's different and if the pre-release versions are considered less stable. It would be useful to understand this better and even document it on the installation page.

**Comment by pirog** [comment]
https://docs.lando.dev/config/releases.html

**Comment by hussainweb** [comment]
@pirog, thanks. I did research but didn't scan through the entire guide. I thought something like this would be in "Getting started", possibly in "Installation". Would you consider adding a link there or do you think that's not relevant?

**Comment by hussainweb** [comment]
@pirog I did a little more research and found another issue #2430. I can understand your frustration better now. In any case, I think it is not that straight forward to find and this is not mentioned on the releases pages either. It would certainly help to mention this in installation. That's just my suggestion.
