### ISSUE TITLE
add "lando urls" or "lando vitals" command

### ISSUE THREAD

**Issue by lsmith77** [lando/lando#2506]
Please complete the following:

**Link to the page that needs to be updated or changed.**
https://docs.lando.dev/basics/usage.html

**Describe the change you'd like**
A command that lists the URLs shown at the very end when starting up lando containers. Especially for serivces with dynamic urls (like mailhog) this would be nice to have, since extracting this out of `lando info` is tedious.

```
$ lando urls
 APPSERVER_NGINX URLS  https://localhost:33278
                       http://localhost:33279
                       http://foo.lndo.site/
                       https://foo.lndo.site/
 MAILHOG URLS          http://localhost:33280
```

It could also be everything shown at the very end .. ie

```
$ lando vitals
Here are some vitals:

 NAME                  recruit
 LOCATION              /home/bar/foo
 SERVICES              appserver_nginx, appserver, database, node, mailhog
 APPSERVER_NGINX URLS  https://localhost:33278
                       http://localhost:33279
                       http://foo.lndo.site/
                       https://foo.lndo.site/
 MAILHOG URLS          http://localhost:33280
```

**Comment by pirog** [comment]
There have been various issues with this proposed in the past and generally we've prioritized other things. The usual response is we'd accept a PR for this but we'd prefer it be implemented as a flag to `lando info` as opposed to a separate command.

**Comment by lsmith77** [comment]
ok understood .. BTW since posting this I also learned that I can of course define a proxy for mailhog. I still think it would  be nice to have .. but really its just a nice to have.

**Comment by ops-webhead** [comment]
I concur. Usually this is all the info I would want, not all that JSON spit out by the current `info` command.

**Comment by garrettw** [comment]
I concur. Usually this is all the info I would want, not all that JSON spit out by the current info command.

**Comment by gitressa** [comment]
I agree, something like `lando info --vitals` would be nice. For now `lando stop && lando start` takes a few seconds but works.

**Comment by klonos** [comment]
I also find `lando info` too much, and would prefer the short version with `lando vitals` 👍🏼 

Please reopen this.

**Comment by gitressa** [comment]
Thanks @klonos that's a great temporary solution. I also have Search URLs defined, so to get them displayed I added `,2` to your solution:

`lando info --format json | jq '.[0,2].urls' | jq -r .[]`

I tried to only get `https` addresses shown, but in vain ...

**Comment by klonos** [comment]
This issue is labeled "documentation", while it is actually a feature request. I don't think it should be closed until you can actually achieve this with lando.
