### ISSUE TITLE
platformsh recipe: HTTPS

### ISSUE THREAD

**Issue by lsmith77** [lando/lando#2507]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
lando 3.0.9
Ubuntu 20.04 using docker inside WSL2

**Tell us about your `.lando.yml`**
`recipe: platformsh`

**Tell us about the error you got**

Absolute URLs generated use `http` and not `https`.

**Tell us generally about your bug**

`$_SERVER['HTTPS']` is not set to true when going to an `https` URL, this in turn means that Symfony based apps will not be aware that the site is running on `https` and will therefore default to `http` when generating absolute URLs pointing back to the app.

See also https://github.com/symfony/http-foundation/blob/master/Request.php#L1143

**Tell us more**

@pirog already confirmed this bug on a Drupal site. I saw the issue on a Laravel app.

**Comment by pirog** [comment]
Yup this is definitely a bug and we've got a pathway to resolving it.

**Comment by pirog** [comment]
alright this should be fixed in the next release
