### ISSUE TITLE
platfromsh recipe: default routes to "primary" false

### ISSUE THREAD

**Issue by lsmith77** [lando/lando#2508]
**Tell us about your setup**

What is your lando version and operating system? (note that the older your version the less likely we are to reply)

lando 3.0.9
Ubuntu 20.04 using docker inside WSL2

**Tell us about your `.lando.yml`**
recipe: platformsh

**Tell us about the command you were running**

`lando artisan`

**Tell us about the error you got**

`PHP Notice:  Undefined index: primary in /app/vendor/platformsh/laravel-bridge/platformsh-laravel-env.php on line 107`

**Tell us generally about your bug**

The issue is caused if there are routes in `.platform/routes.yaml` that do not have the primary key set explicitly. platform.sh sets a default here. AFAIK it defaults to false, except if no route is explicitly set to true, then the first route default to true. But this needs to be confirmed.

**Tell us more**

Temporary fix is to simply explicitly define `primary` `true` or `false` for each route.

**Comment by pirog** [comment]
@lsmith77 im interested to know why you think this is a problem with lando and not with the underlying composer project eg 
https://github.com/platformsh/laravel-bridge

seems to me that this is something that should be fixed there, also worth pointing out that this is just a notice, not a warning or error

**Comment by lsmith77** [comment]
@pirog from my understanding the aim of the platformsh recipe is to mimic the platform.sh environment. what I describe above is the platform.sh behavior. now obviously all of the code interpreting the env data could also implement these defaults but this would mean this behavior must be re-implemented in all bridges. as such imho it seems more feasible to have fewer canonical places that define defaults, rather than individual bridges.

**Comment by pirog** [comment]
@lsmith77 mimicking is not the same as making it 100% the same. There definitely are things about the local environment that  should and in fact must be different. im not sure if this is one of those things but that is how we are going about making the integration.

if you are going to submit a bug report the most useful thing you can do for us is provide the relevant config and steps to replicate the issue.

**Comment by lsmith77** [comment]
ok .. will provide you with relevant platform.sh configs to reproduce later today.

for now I think all it requires is a platform.sh project with a routes.yaml with 2 routes and none explicitly marked as primary.

**Comment by pirog** [comment]
@lsmith77 thanks, we have many route defined like that and havent seen the bug so it might require more

**Comment by lsmith77** [comment]
I have seen the issue with these routes. Adding “primary: false” to all the routes with a “primary” key seemed to have fixed the notices.

```
# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.
https://diversifier.{default}/:
    type: upstream
    primary: true
    upstream: "recruit:http"
https://www.diversifier.{default}/:
    type: redirect
    to: https://diversifier.{default}/
https://www.debias.{default}/:
    type: redirect
    to: https://diversifier.{default}/
https://debias.{default}/:
    type: redirect
    to: https://diversifier.{default}/
"https://jobs.{default}/":
    type: upstream
    upstream: "recruit:http"
https://www.jobs.{default}/:
    type: redirect
    to: https://jobs.{default}/
https://www.job.{default}/:
    type: redirect
    to: https://jobs.{default}/
https://job.{default}/:
    type: redirect
    to: https://jobs.{default}/
```

**Comment by pirog** [comment]
alright @lsmith77 we are now setting this behind the scenes, should be in the next release
