### ISSUE TITLE
platformsh recipe: automatic redirect from http to https missing

### ISSUE THREAD

**Issue by lsmith77** [lando/lando#2509]
**Tell us about your setup**

What is your lando version and operating system? (note that the older your version the less likely we are to reply)
lando 3.0.9
Ubuntu 20.04 using docker inside WSL2

**Tell us about your `.lando.yml`**

`recipe: platformsh`

**Tell us about the error you got**

https is not enforced

**Tell us generally about your bug**

platform.sh by default redirects any request to `http` to `https` when available.

**Tell us more**

**Comment by lsmith77** [comment]
the redirect behavior is documented here https://docs.platform.sh/configuration/routes/https.html

**Comment by pirog** [comment]
Thanks, we've read it. It definitely does not say that redirecting http to https is the default behavior. it does recommend doing that. perhaps more importantly im not sure we want lando to be doing redirects in this way anyway.

**Comment by lsmith77** [comment]
it does say that this redirect is the explicit behavior *if* only https routes are defined
```
How HTTPS redirection is handled depends on the routes you have defined. Platform.sh recommends specifying all HTTPS routes in your routes.yaml file. That will result in all pages being served over SSL, and any requests for an HTTP URL will automatically be redirected to HTTPS.
```

**Comment by pirog** [comment]
@lsmith77 right. good call. i did not read that correctly.

still, im not sure we want lando to do this.

**Comment by pirog** [comment]
ok @lsmith77, we had an internal chat about this with platform and its something we will probably address after we take the integration into beta status. 

there wasnt clear agreement on whether this made sense as the default for local. more feedback from users would likely make it clearer so "wait and see" is what we will do for now.

**Comment by lsmith77** [comment]
sounds good. thx
