### ISSUE TITLE
clone lando container

### ISSUE THREAD

**Issue by vmkazakoff** [lando/lando#2510]
Hi. Is here a way to clone newly created container with all databases, proxy and all other stuff as new one? Just to have test env. ready to use and easy to delete and start over.

Or some option to "freeze" the moment and after making some changes have option to make all "as it was"?

**Comment by pirog** [comment]
@vmkazakoff im not sure what it is you are asking here.

**Comment by vmkazakoff** [comment]
May be this is wrong place, but I try to clarify my question:
1) I just create new environment for website
2) install app, create database, tune configs etc
3) now I'm going to to change something on the site (run a path or update...)

Is here a way, if i broke something, to revert all to current version?

Sorry, if my question is not clear or if this is not right place for it.

**Comment by dustinleblanc** [comment]
Hey @vmkazakoff you can run `lando db-export` to export your database state, and then `lando db-import` to restore it. You can also use git to track the state of your code and do a `git checkout .` to reset the code to the last commit. The only thing not covered here is files/uploads

**Comment by vmkazakoff** [comment]
Thanks @dustinleblanc!
Just hope this is some option to "freeze" like on virtual machine.

**Comment by dustinleblanc** [comment]
Container state should always be thought of as ephemeral, state should be offloaded if it needs to be kept. In our case that's db import/export and version control :)
