### ISSUE TITLE
"lando pull" from "none" is ignored. v3.0.7

### ISSUE THREAD

**Issue by johnpennweb** [lando/lando#2512]
v3.0.7 on MacOS 10.14.6
Pantheon/ Drupal recipe. 

Ran a "lando pull", specified database only, yet code and files were pulled. I got the same result across several different Drupal projects.

$ lando pull
? Pull code from? none
? Pull database from? dev
? Pull files from? none

**Comment by pirog** [comment]
@johnpennweb this was fixed in 3.0.8 so id upgrade
