### ISSUE TITLE
P.sh Typo3 support

### ISSUE THREAD

**Issue by mikemilano** [lando/lando#2515]
*Updated 7/30 to represent the current issues.*

## 1. trustedHostsPattern

Problem: `localhost:[port]` routes return 500 errors due to the `trustedHostsPattern` config.

By default, `$GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern']`  is set to `SERVER`, which works for the named routes, but not for `localhost:port`.

Setting this value to `.*` resolves the issue and should be fine for local development. 

Configuration for these vars exists in `public/typo3conf`.

In order to make this work for `localhost:port` patters on Lando, we will need to either:

1. Set it at the network level as Platform.sh does. 

2. Add the following config to one of the templates in `public/typo3conf`
```php
if (isset($_ENV['LANDO'])) {
  $GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] = '.*';
}
```

3. Document for users to add it to the config themselves, if they need this support

For reference, this is the error when the trustedHostsPattern does not match:

> [22-Jul-2020 23:51:15 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The current host header value does not match the configured trusted hosts pattern! Check the pattern defined in $GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] and adapt it, if you want to allow the current host header 'localhost:32926' for your installation. in /app/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php:2717

## 2. Redis module warning

`lando build` (or start, or rebuild) triggers the platform build which runs [this](https://github.com/platformsh-templates/typo3/blob/master/install-redis.sh#L18), creating a new `extension=redis.so` in the `php.ini` file.

This causes an module load warning each time a PHP command is run, breaking functionality such as `lando pull`.

A work around is to delete the extension definition before a rebuild but it would be more ideal if the script that creates that definition is refactored.

## 3. 404 in Lando with all code, relations, and files in sync

platform.sh master env: https://master-7rqtwti-5gggzrgoxlm4c.us-2.platformsh.site/

Even though we have all code, database & mounts in sync in Lando, the home page of this new Typo3 site returns a 404.

Routing and PHP works since I can access and modify settings in the install tool, but the home page reports there is no config.

<img width="672" alt="Screen Shot 2020-07-30 at 12 16 32 PM" src="https://user-images.githubusercontent.com/1287855/88977827-68d3bb80-d273-11ea-932b-0561c545e2e9.png">

**Comment by lsmith77** [comment]
let me know if you need support from a TYPO3 expert. then I can ping someone from that community

**Comment by pirog** [comment]
@mikemilano i was able to run our vanilla typo3 project successfully and didnt run into any of the painpoints you did so i think we can assume "fixed upstream". I'm going to submit a base Landofile to the platform typo3 template and we can go from there but i think its safe to close this for now.
