### ISSUE TITLE
lando db-import is choking on a view in my sql file

### ISSUE THREAD

**Issue by brockness** [lando/lando#2516]
![Screenshot from 2020-07-21 23-46-36](https://user-images.githubusercontent.com/3128403/88252635-f401ef80-cc7c-11ea-9c52-5d33563614c4.png)
Running Pop! OS 20
lando version 3.0.9
standard Pantheon Wordpress YAML config

running `lando pull` or `lando db-import mysql_file.sql` fails and gives this error

ERROR 1965 (42502) at line 2: 'pantheon.user_x_meta' is a view

**Comment by pirog** [comment]
@brockness this will be fixed in the next release! thanks for reporting!
