### ISSUE TITLE
Problem with lando pull

### ISSUE THREAD

**Issue by dolly-k** [lando/lando#2524]
Hi,

I am working on a drupal pantheon website.

Currently I am in branches and when I do Lando Pull
Code [branch name]
Database [none]
Files [none]

It still downloads the database and files.

I never had this problem before but have been having this lately.

However if I use the command lando pull --database=none --code=branch-name --files=none then it works fine.

Also lately doing lando pull, the database download is pretty slow. It was perfectly fine on my old laptop which had a different version of lando but since I moved to a new one the database download takes ages.
I have a good internet speed 70mbps though.

**Comment by pirog** [comment]
@dolly-k upgrade to a more recent version of lando

**Comment by dolly-k** [comment]
Hi I did that, but it still takes ages :(


------------------------------

*Dolly **Katiyar*
Developer
408 899 8998

*baunfire.com <http://baunfire.com>*
