### ISSUE TITLE
Add --destination support to platform local build when passthru file does not exist

### ISSUE THREAD

**Issue by mikemilano** [lando/lando#2529]
When using the Drupal 7 p.sh template (and potentially others), `web.locations` (in `.platform.app.yaml`) path to `index.php` does not exist. As a result, Lando cannot serve the site.

`_www` is the default destination created by `platform build` however using this adds other concerns in breaking with the definitions of `web.locations`.

## Solution

- On `lando build`, if `web.locations./.passthru` has a file defined, and that path does not exist, set the path as the `--destionation` value on `platform local:build` in `psh-build.sh` (line 35)
- Add p.sh destination path support to `.lando.yml`
  - This will be an undocumented escape hatch to override anything we've set, or cover any case we haven't

## Notes

- p.sh config data in `integrations/lando-platformsh/app.js` -> `app.platformsh`
- `.platform.app.yaml` is parsed and set in `config.js` -> `parseApps` 
- `lib/run.js` -> `getDocRoot` may work to identify the root path for 90%+ cases

If we go with passing as an argument
- 'lib/services.js` is where `helpers/psh-build.sh` is called
  - add `--destination`

If we go with env vars
- Set it in `types/platformsh-appserver/builder.js`

**Comment by pirog** [comment]
@mikemilano long term we will eventually move to use `/etc/platform/commands/build` but i think that might be a post-beta activity so lets def do this for now.
