### ISSUE TITLE
How to not load .env file

### ISSUE THREAD

**Issue by Eldair** [lando/lando#2531]
Hello,

I'm new to this but I couldn't find any solution for this.
I have installed lando inside wsl 2. I am trying to start it but I keep getting errors due to .env file having multiline variables (cannot be changed atm). I tried setting different file for `env_file` option in .lando.yml file but it keeps loading .env file and causing that error. I am using laravel recipe.

Am I missing something? Does it always load .env file regardless of env_file option?

**Comment by dustinleblanc** [comment]
Yep, Laravel's phpdotenv system will automatically include those files for you. More than likely Laravel itself is just not going to work until you resolve the loading of those variables by either inlining them or doing something else within Laravel to handle it.

**Comment by Eldair** [comment]
Hi,
The exact error is `In file ./.env: environment variable name '-----END RSA PRIVATE KEY-----"' may not contain whitespace.` and it appears on `lando start`. Everything worked fine on virtualbox.
I have `env_file: defaults.env` in my .lando.yaml

**Comment by Eldair** [comment]
How can it be laravel issue if it appears before any code is ran?

**Comment by pirog** [comment]
@Eldair i can say with a large degree of confidence that lando does not load `.env` unless you tell it to. If you are running a very old version of lando then this might be different. It's worth pointing out that `env_file` is an array and not a string so that might be part of your problem.

**Comment by pirog** [comment]
It looks like docker-compose`, which lando uses under the hood, does this and there is a lengthy debate about it
https://github.com/docker/compose/issues/6741

@dustinleblanc i wonder if we should do something like `docker-compose --env-file /dev/null` as indicated in the commend of the issue above because right now Lando is not working the way it is documented to work. Sort of surprising this hasn't been flagged before.

**Comment by dustinleblanc** [comment]
Oh did this change at some point? I was like a 1000% certain we didn't load the default .env file

**Comment by pirog** [comment]
I dont think _we_ do, but there are some threads about docker compose doing this. To add more fun to the problem i cannot replicate this, nothing i put in `.env` is injected into the container unless i explicitly set `env_file`.

**Comment by dustinleblanc** [comment]
So maybe it gets read by docker-compose (for use in variable sub in docker-compose files?) but then doesn't actually get injected into containers.

**Comment by pirog** [comment]
I _think_ that is what the docs i linked to are saying. doesnt seem to explain the behavior though.

**Comment by pirog** [comment]
`.env`
```
PIROG=stuff
```

`.lando.yaml`
```yaml
services:
  appserver:
    overrides:
      environment:
        PIROG2: $PIROG
```

so that ends up setting `PIROG2` to `stuff`

**Comment by pirog** [comment]
Ahh looks like this is something they fixed in docker-compose and is pending release
https://github.com/docker/compose/issues/6511#issuecomment-603756467

**Comment by dustinleblanc** [comment]
Sorry for speed closing your issue @Eldair! Looks like we've got an upstream issue to contend with for docker-compose :(

@pirog, I am guessing the fix is that we're going to update our docker-compose version?

**Comment by pirog** [comment]
@dustinleblanc yes i think that is exactly what we need to do. Looks like `1.26.2` was released with Docker Desktop `2.3.0.4` so we'd just need to upgrade to that and make sure we bump the docker compose version in the linux package script

**Comment by Eldair** [comment]
@dustinleblanc no problem, I'm glad it will be fixed :)
@pirog what would eta be? I see that 1.26.2 is already released

**Comment by pirog** [comment]
no idea, we usually release maybe every ten days. that said you can definitely just download the latest docker compose and put it in `/usr/share/lando/bin` and i think that should allow you to work around it for now

**Comment by Eldair** [comment]
@pirog yup, that did the trick! thanks a lot

**Comment by pirog** [comment]
@Eldair ok we are going to do a release later today which should fix this. thanks for the report
