### ISSUE TITLE
change root directory for node service

### ISSUE THREAD

**Issue by Lisendra** [lando/lando#2544]
I was searching in the guides/documentation but wasn't able to find anything, my team is developing an app with laravel as backend and vue.js as frontend, there basicly a subfolder in the laravel directory for vue.js.

I would like to specify that the root directory of the node service.

Also unrelated is there a Lando comunity on somewhere to ask questions instead of flooding github?
edit: found the lando slack!

**Comment by dustinleblanc** [comment]
Hey Lisendra!

You can absolutely run Node with a target in a certain directory, probably like this:

```yml
services:
  node:
    type: node
    command: node /app/frontend/script.js
```
You can also run npm in a sub-dir, like I do in this proiect I used for a talk at DrupalCamp: https://github.com/dustinleblanc/hydra/blob/master/.lando.yml#L30

Let us know if you have more questions in Slack!

Thanks!
