### ISSUE TITLE
[v3.0.11] Unable to enable core module with drush

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#2546]
Not sure if `update` is acting like a keyword but...
```bash
$ lando drush en update -y

                                                     
  Too many arguments, expected arguments "command".  
                                                     

entity:updates [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command>                                                                                                                                                                                    

$ lando ssh
www-data@27bb3e2f9286:/app$ drush en update -y
 [success] Successfully enabled: update
```
Contents of `.lando.yml`:
```yaml
name: mysite
recipe: drupal8
config:
  via: nginx
  webroot: web
  database: mariadb:10.2
keys:
  - id_rsa
events:
  post-db-import:
    - appserver: /app/lando/scripts/post-db-import.sh
services:
  appserver:
    run:
      - /app/lando/scripts/build.sh
tooling:
  drush:
    service: appserver
    cmd: drush -r /app/web -l mysite.lndo.site
```
System specs:
```bash
$ lando version
v3.0.11
$ lsb_release -a
No LSB modules are available.
Distributor ID: MX
Description:    MX 18.3 Continuum
Release:        18.3
Codename:       Continuum
$ uname -a
Linux dell-precision-m6700 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux
$ docker -v
Docker version 19.03.12, build 48a66213fe
$ docker-compose -v
docker-compose version 1.25.1, build a82fef07
$ lando drush status
 Drupal version   : 8.9.2                             
 Site URI         : http://mysite.lndo.site        
 DB driver        : mysql                             
 DB hostname      : database                          
 DB port          : 3306                              
 DB username      : drupal8                           
 DB name          : drupal8                           
 Database         : Connected                         
 Drupal bootstrap : Successful                        
 Default theme    : mytheme                           
 Admin theme      : seven                             
 PHP binary       : /usr/local/bin/php                
 PHP config       :                                   
 PHP OS           : Linux                             
 Drush script     : /app/vendor/drush/drush/drush     
 Drush version    : 9.7.2                             
 Drush temp       : /tmp                              
 Drush configs    : /app/vendor/drush/drush/drush.yml 
                    /app/drush/drush.yml              
 Install profile  : standard                          
 Drupal root      : /app/web                          
 Site path        : sites/default                     
 Files, Public    : sites/default/files               
 Files, Temp      : /tmp
```

**Comment by pirog** [comment]
@uberhacker this is probably caused by your override of the drush command to include options eg `cmd: drush -r /app/web -l mysite.lndo.site`

**Comment by pirog** [comment]
@dustinleblanc i can replicate WITH @uberhacker's tooling override but works as expected without. 

I don't really think there is anything Lando should do about this. If the tooling command is overridden its effectively in YMMV territory. What do you think? Feel free to close or keep open at your discretion.

Relatedly, worth noting that `envvars` can now be used in tooling commands and that might be a more effective way of setting defaults eg `DRUSH_OPTIONS_URI` since that is non-commutative..

**Comment by dustinleblanc** [comment]
Yeah I absolutely agree, if the tooling command is overridden, I think positional arguments can't really be handled unless you are passing them to a script and parsing them, I would also recommend just setting the drush options env vars instead. I think you can even just set them on the appserver service pretty safely as well.

**Comment by uberhacker** [comment]
I think it should work either way?  The real question is, why wouldn't / shouldn't it work this way?

**Comment by pirog** [comment]
@uberhacker guessing that drush 9 handles positional arguments differently which is @dustinleblanc's point. 

so overriding things the way that you did is only going to work the way you want if the underlying command, eg drush in this case, is smart enough to interpret the positional args regardless of their ordering. note that under the hood you are running

```
drush -r /app/web -l mysite.lndo.site en update -y
```

could be as simple as drush not liking options on one of or both sides of the subcommands

**Comment by dustinleblanc** [comment]
Yep that is eactly what I was thinking, passing options split around the sub commands. I think drush is fine taking those flags before or after the sub commands, but I am guessing it isn't happy about both

**Comment by uberhacker** [comment]
That is a good theory, however, I don't think it is simple as that.  I get the same error even without the `-y` at the end.  I believe this issue should be reopened.  Lots of cli apps can handle unordered switch options.

**Comment by dustinleblanc** [comment]
@uberhacker Lando is a bit different because we need to handle arguments passed to the CLI itself as well as sub-command arguments, so its twice as complicated as the average CLI app. I don't think we'll ever be able to handle every case, there are too many possibilities.

As far as still getting the same error, does ` lando drush "en modulename"` still produce the same result? I am not sure how to tell a tooling command to ingest `n` arguments

**Comment by uberhacker** [comment]
Sorry @dustinleblanc: Got pull into another project.  See below:
```bash
$ lando drush "en update"

                                       
  Command "en update" is not defined.  
                                       
  Did you mean one of these?
```
I thought to myself: `Did you mean one of what?` LoL

**Comment by pirog** [comment]
It's not landos responsibility to handle unordered switch options, its the underlying command's responsibility, lando's responsibility is to pass args in "as is" a much as it is possible for it do so. 

Cases in point the commands below all fail when run directly with drush. These include the extrapolated command you are running under the hood via lando.

```
drush -r /app -l https://lando-drupal8.lndo.site en update -y
drush -y -r /app -l https://lando-drupal8.lndo.site en update
```

However, this does work

```
drush en update -y -r /app -l https://lando-drupal8.lndo.site
```

So while the result may not be what you want Lando is returning the expected result which is same result the underlying command gives.

**Comment by uberhacker** [comment]
@pirog: That is fair.  I appreciate the explanation.  I guess I need to contact g1a concerning drush.

**Comment by joshuami** [comment]
While dropping in some research on https://github.com/lando/lando/issues/2549, I noticed this related issue. If it helps anyone trying to get the drush tooling to work, we seem to have luck with the following even after upgrading past v3.0.9:

```
  drush:
    description: CUSTOM Run drush commands
    service: appserver
    cmd: drush --root=/app/web
```

All our drush commands  work fine using that syntax. Node commands are a whole different issue :)

**Comment by garrettw** [comment]
I have this issue as well, with the following tooling command:
```yaml
  phpunit:
    service: appserver
    cmd: cd api && vendor/bin/phpunit -v --cache-result --order-by=defects,default --stop-on-failure
```

If I do `lando phpunit --filter ClassName`, nothing gets filtered, as if it didn't even pass in the extra args.
