### ISSUE TITLE
Lando pull database failing

### ISSUE THREAD

**Issue by nikunp** [lando/lando#2561]
Lando Version 3.0.9 on MacOS 10.15.6

lando.yml
name: foacommercial
recipe: pantheon
config:
  framework: wordpress
  site: foacommercial
  id: ac69d228-d6f8-42bd-8e47-82461c6eff12

pantheon.yml
api_version: 1
web_docroot: true
php_version: 7.2

workflows:
  sync_code:
    after:
      - type: webphp
        description: Webhook
        script: private/scripts/plugin_monitor.php

What causes the issue is lando pull database

lando 11:58:07 INFO ==> loading app foacommercial from config files 0=/Users/nikunpatel/foacommercial/.lando.yml
? Pull code from? none
? Pull database from? develop
? Pull files from? develop
lando 11:58:22 INFO ==> loading app foacommercial from config files 0=/Users/nikunpatel/foacommercial/.lando.yml
Attempting to login via terminus...
 [notice] Logging in via machine token.
Logged in as nipatel@financeofamerica.com
Verifying that you have access to foacommercial...
 ------------------ ----------------------------------------------------------------------------------------------------
  ID                 ac69d228-d6f8-42bd-8e47-82461c6eff12
  Name               foacommercial
  Label              foacommercial
  Created            2018-06-07 23:13:53
  Framework          wordpress
  Region             United States
  Organization       e430e35d-784e-8f8c-0a3f-de9fd2a9d1b4
  Plan               Performance Small
  Max Multidevs      10
  Upstream           1c07b622-cfa9-41d8-961a-b5587363e62f: https://bitbucket.org/financeofamerica/pantheon-upstream.git
  Holder Type        organization
  Holder ID          e430e35d-784e-8f8c-0a3f-de9fd2a9d1b4
  Owner              71e0a69b-56c2-4f7e-8ea3-012daaefb9cc
  Is Frozen?         false
  Date Last Frozen   1970-01-01 00:00:00
 ------------------ ----------------------------------------------------------------------------------------------------
Access confirmed!
Certificate will not expire
Cert is good!
Validating you can pull the database from develop...
 ----------------- ---------------------------------------
  ID                develop
  Created           2018-07-03 16:46:38
  Domain            develop-foacommercial.pantheonsite.io
  Locked            false
  Initialized       true
  Connection Mode   git
  PHP Version       7.2
 ----------------- ---------------------------------------
Confirmed!
Destroying all current tables in database if needed...
Making sure your site is awake...
 [notice] OK >> develop-foacommercial.pantheonsite.io responded
Pulling your database... This miiiiight take a minute
 [warning] This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'pantheon' AND TABLE_NAME = '_pantheon_heartbeat';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
 [notice] Command: foacommercial.develop -- wp db export [Exit: 2]
 [error]
Notice: Undefined index: HTTP_HOST in /code/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(873) : eval()'d code on line 90
-- MySQL dump 10.13  Distrib 8.0.17, for Linux (x86_64)
--
-- Host: 10.128.0.243    Database: pantheon
-- ------------------------------------------------------
-- Server version	5.5.5-10.0.23-MariaDB-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `_pantheon_heartbeat`
--

DROP TABLE IF EXISTS `_pantheon_heartbeat`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `_pantheon_heartbeat` (
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `actor` varchar(64) NOT NULL,
  PRIMARY KEY (`actor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `_pantheon_heartbeat`
--

LOCK TABLES `_pantheon_heartbeat` WRITE;
/*!40000 ALTER TABLE `_pantheon_heartbeat` DISABLE KEYS */;
INSERT INTO `_pantheon_heartbeat` VALUES ('2020-08-11 15:58:38','resurrection');
/*!40000 ALTER TABLE `_pantheon_heartbeat` ENABLE KEYS */;
UNLOCK TABLES;

1.68KiB 0:00:04 [ 382 B/s] [<=>                                                ]
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Notice: Undefined index: HTTP_HOST in /code/vendor/wp-cli/wp-cli/php/WP_CLI/Runn' at line 1

**Comment by pirog** [comment]
this will be fixed in the next release but we recommend you figure out how to resolve the php notice as this will improve the DB pull speed and your apps performance generally
