### ISSUE TITLE
Pantheon VCL unsets cookies improperly

### ISSUE THREAD

**Issue by nullvariable** [lando/lando#2566]
VCL unsets cookies for full request strings that end in file types like jpg or gif.
This has been resolved in the upstream.
Example:
`/asdf.php` -- cookies operate with same rules as pantheon
`/file.jpg` -- cookies stripped (as expected)
`/asdf.php?file=file.jpg` -- cookies stripped, not expected
`/asdf.php?file=file.jpg&1=1` -- cookies not stripped

**Comment by pirog** [comment]
@nullvariable i dont think this is something we currently plan to fix on our end. #2371 is more of what we are shooting for eg there is some mechanism/container/image/spec we can ingest from pantheon 

cc @dustinleblanc

**Comment by nullvariable** [comment]
I'm putting together a quick PR to at least bring the current logic into the vcl until other fixes are made, just testing the changes now. Also I have a feeling that we'll still have to manage the varnish container even if we can make other parts of the stack into Docker images
