### ISSUE TITLE
Overriding nginx config in Pantheon recipe?

### ISSUE THREAD

**Issue by arcataroger** [lando/lando#2581]
Is it possible to use the [custom config for services overrides](https://docs.lando.dev/config/nginx.html#configuration) with another recipe, like [Pantheon](https://docs.lando.dev/config/pantheon.html#getting-started)?

I'm trying to add a custom location handler to the nginx vhosts file in order to download any files (such as images) that's not on my local copy:

```
    location /sites/default/files/ {
    try_files $uri $uri/ @grabfromlive;
    }

    location @grabfromlive {
    return 302 https://www.mywebsite.com$uri;
    }
```

I added to a new file called `.lando/nginx/default.conf` and added to my `.lando.yml` like so:
```
services:
  appserver_nginx:
    type: nginx
    config:
      vhosts: .lando/nginx/default.conf
```

But it doesn't seem to take. If I change the `appserver_nginx` service name (which is what Pantheon calls it by default), Lando does spawn a new nginx instance with that name and the config works fine. But how do I make it override an existing one inside a recipe?

**Comment by arcataroger** [comment]
Aha, making progress. Two issues:

1) Actually, the override just needs a `lando rebuild` instead of `restart`. Oops.
2) The default nginx service file breaks the Pantheon recipe. Now trying to find the correct nginx conf that Pantheon actually uses... there's a lot of layers. Maybe this one? `https://github.com/lando/lando/blob/master/integrations/lando-pantheon/recipes/pantheon/drupal.conf.tpl`

**Comment by techieshark** [comment]
@arcataroger just stumbled on this. I assume you figured it out? I had a similar issue and learned that one needs to find the nginx conf that was in use (which it seems you were aware of too), and copy/paste that entire base config (basically forking it) to override it.

It can also help to `lando ssh -s appserver_nginx`, then `cd /etc/nginx/` and poke around there to see what kind of settings are in use by default.

**Comment by arcataroger** [comment]
Sorry, this was a few months ago and I don't remember 100%, but what you said sounds right. I think you were correct in that there was no way to add just one thing to the config. I was reluctant to copy/fork the entire file because that would desync us from Lando and potentially break during future updates.

We never did fully resolve this issue because Lando/Docker was just too slow on macOS, so we gave up and switched to a bare-metal LEMP stack (and even that was still slow). Nonetheless, having the ability to inject additional nginx config (like a servers file/folder) without losing the Lando base config could be a valuable feature.

**Comment by bob-hinrichs** [comment]
Same question, because we have encountered https://github.com/lando/lando/issues/704
