### ISSUE TITLE
Solr 8.5 or 8.6 is not supported

### ISSUE THREAD

**Issue by vlyalko1972** [lando/lando#2599]
I have the latest lando version installed: 3.0.11, MAcOS,Catalina 10.15.5 (19F101)

name: agrilinks
recipe: drupal8

config:
  via: apache
  webroot: web
  php: 7.3
  xdebug: true
  drush: false
  conf:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf

proxy:
  search:
    - search.agrilinks.lndo.site:8983
  pma:
    - db-agrilinks.lndo.site
  mailhog:
    - mail-agrilinks.lndo.site

services:
  search:
    type: solr:8.5
    portforward: true
    core: agrilinks
    config:
      dir: solr-conf
  database:
    type: mariadb:10.1
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: 8
      behat/behat: 3.3.1
    run:
      - "ln -s /usr/local/bin/composer /usr/local/bin/composer.phar"
    run_as_root:
      - "bash /app/lando/scripts/build.sh"
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://agrilinks.lndo.site" 
  node:
    type: node:10
    globals:
      gulp-cli: latest
    build:
      - "cd $LANDO_MOUNT && npm install"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  drush:
    service: appserver
    description: run drush commands
    cmd: /app/vendor/drush/drush/drush
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  mailhog:
    service: mailhog
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node

Trying to get Solr 8.5 or 8.6 installed. But, when I run any Lando commands, I get the following error:

error: solr verion 8.5 (or 8.6) is not supported

The documentation states the Solr 8... is supported

<img width="1792" alt="Screen Shot 2020-09-10 at 2 33 16 PM" src="https://user-images.githubusercontent.com/69919863/92782000-9d5a8d00-f372-11ea-9d01-373a2031a44a.png">
 I am not sure as to how to get 8.5 or 8.6 versions installed since I am following the documentation exactly and still getting the error. Please advise how to fix this. Thanks...

**Comment by jcmartinez** [comment]
Same problem here using Ubuntu.

**Comment by pirog** [comment]
these versions are not currently supported, however they will be in the next release. in the meantime you can always override your landofile to use an "unsupported" version
