### ISSUE TITLE
I can't access any website at Lando.dev

### ISSUE THREAD

**Issue by david-j-davis** [lando/lando#2601]
I receive an ERR_NAME_NOT_RESOLVED issue whenever I try to access any url and subdomain of lando.dev. THis happened to me a couple years ago living in California, and now Im on a different computer in a different state still can't access. Both OSX, but I don't get it, never experienced this before.

**Comment by garrettw** [comment]
Do you have custom DNS resolver(s) set up on your computer?

**Comment by david-j-davis** [comment]
Hi @garrettw I do not have a custom DNS setup at my new house.

**Comment by garrettw** [comment]
Can you open a terminal and run `nslookup`?
When you get the `> ` prompt, type `server`, hit enter, and paste the output here.

**Comment by david-j-davis** [comment]
Default server: 192.168.86.1
Address: 192.168.86.1#53

**Comment by david-j-davis** [comment]
Can I ask what your conclusion is for this matter?

**Comment by garrettw** [comment]
Just trying to troubleshoot as I am not sitting there at your computer able to figure it out myself.

So next I would try: `nslookup lando.dev`
Followed by:
```
nslookup
> server 8.8.8.8
> lando.dev
```
I'm assuming the first one fails but the second one might work.

**Comment by david-j-davis** [comment]
Here is the output: https://paste.lucko.me/eSKbTbQD11

**Comment by garrettw** [comment]
Ok, both worked, so it's not your router or ISP or computer. All that leaves is your browser.

**Comment by david-j-davis** [comment]
Well, I cannot open lando.dev on Chrome, Firefox or Safari though.

**Comment by david-j-davis** [comment]
I just dug up my Chromebook, and can access lando.dev from that computer.
So I guess it's my Macbook, and the one before it. I can't make sense of
this but my main computers I develop on have never been able to access your
site.
