### ISSUE TITLE
Support installing Lando within a WSL2 Linux distro

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2611]
As a lando user working on `Windows 10` via `WSL2` and `Docker for Windows` I want to install Lando within my Ubuntu 20.04 WSL2 environment.

I am running `Docker for Windows` with the `Use the WSL 2 based engine` option enabled which means that the Docker environment is shared between `Docker for Windows` and the Ubuntu 20.04 WSL2 environment. In other words, running `docker` within the WSL2 distro actually accesses the same Docker instance/context than the one running directly in Windows.

Currently when trying to install the Lando `deb` file within the WSL2 distro this error message comes up:
```
dpkg: dependency problems prevent configuration of lando:
 lando depends on docker-ce; however:
  Package docker-ce is not installed.
```

This is confusing as running the `docker` command within the WSL2 Ubuntu environment works as expected.
```
docker --version
Docker version 19.03.12, build 48a66213fe
```

Could it be that the Lando installer (deb) has to be adpated to actually determine docker within the WSL2 environment correctly?

```
Lando v3.0.12
Windows 10.0.19041 Build 19041
Docker for Windows 2.3.0.5 (48029)
Docker Engine 19.03.12
Hyper-V 10.0.19041.488
Hyper-V Manager 10.0.19041.1
WSL2 Ubuntu 20.04
```

**Comment by thasmo** [comment]
After [installing `docker-ce` on the Ubuntu 20.04 distro](https://docs.docker.com/engine/install/ubuntu/) in addition to the already "existing" docker version provided by WSL2 I was able to install Lando without problems.

I'm not sure how this all works together but without installing `docker-ce` manually in the WSL2 environment, installing Lando does not work although the `docker` command was already available as part of the `Docker for Windows` integration in WSL2, which I had enabled.

**Comment by dustinleblanc** [comment]
@thasmo this whole area is still technically not supported, but fwiw, I just treat WSL2 as 100% a linux machine. I don't install Docker on Windows, just inside WSL. WHen doing this, make sure to also only run your sites within the Linux code mount (under `~/` or `/home/username/Sites` or some other Linux path, NOT under the default directory WSL drops you into (which is a mount of your Windows file system that is really, really slow). Enjoy the MASSIVE speed boost once all this setup!

**Comment by lsmith77** [comment]
same here .. a co-worker went the other direction and documented it here https://www.liip.ch/en/blog/setup-drupal-and-lando-with-wsl2-on-windows

**Comment by Xilonz** [comment]
I install Lando using [this part](https://docs.lando.dev/basics/installation.html#caveats) from the installation guide on my WSL distro and install Docker on Windows. Works perfectly.

**Comment by thasmo** [comment]
@Xilonz Didn't see that one but seems to be the prefered solution for now. Thanks!
