### ISSUE TITLE
Private file path on lando with Pantheon

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#2617]
Generally these questions should end up as guides
https://docs.lando.dev/contrib/guides-intro.html#what-is-a-guide

Does anyone have private files working on lando?

After specifying the file_private_path in settings.php, when I go to `/admin/reports/status`, I keep getting this error:

Warning: file_exists(): Unable to find the wrapper "private" - did you forget to enable it when you configured PHP? in Drupal\Component\FileSecurity\FileSecurity::writeFile() (line 152 of /app/web/core/lib/Drupal/Component/FileSecurity/FileSecurity.php).`

lando v3.0.13 on ubuntu (running via wsl2)
Drupal 8.9.4

Using a Pantheon recipe (composer build tools)

settings.php:

`      $settings['file_private_path'] = 'sites/default/files/private';
`

The directory exists; I know because if I change the line to a non-existent directory, I get a non-existent directory error.

Based on these [Steps for fixing the missing private wrapper on Drupal Answers](https://drupal.stackexchange.com/questions/277826/site-seems-to-miss-the-private-wrapper-how-can-i-fix-it), I tried deleting `.htaccess` in `/files/private` and rebuilding the cache.  This has worked a couple times, but it doesn't work consistently; when I wipe my db and pull in a new db from a local backup, the error comes back.

Any insight into fixing this would be much appreciated.

**Comment by xaqrox** [comment]
I just ran into this as well. I suspect the trouble spot is in Pantheon's settings.php. The `$settings` variable gets completely overwritten with the contents of the `settings` property from `PRESSFLOW_SETTINGS` if it exists:

https://github.com/pantheon-systems/drupal-integrations/blob/b452b9767cbd6f2aa1991ed855556169c68dba07/assets/settings.pantheon.php#L120

And as of [this](https://github.com/lando/lando/commit/5c6c621a0e636567c944fe5682df3ee762df6b36) commit Lando provides a settings object that only has one value: https://github.com/lando/lando/blob/ec75e0de4a5ffbb24840ec4aa687e7e493260e80/integrations/lando-pantheon/lib/utils.js#L109-L111

Working on it now, will update this issue with developments...

**Comment by pirog** [comment]
@xaqrox good catch, also thats annoying that it replaces the ENTIRE settings variable. Automatic `skip_permissions_hardening: 1` for local is definitely more a "nice to have" than a must have we we could consider rolling it back. Beyond that i think we'd have to get Pantheon to change their settings.php 

cc @dustinleblanc it definitely would be useful to set this for Localdev so we can more reliably clean up code, thoughts?

**Comment by xaqrox** [comment]
@pirog I think I have a fix, putting together the PR now. It's just that 'conf' is D7 and 'settings' is D8+ if we just duplicate the values for those it seems to work fine. Maybe would be smarter to do the correct one depending on the platform buuut 🤷‍♂️

**Comment by dustinleblanc** [comment]
@xaqrox awesome that it seems you found something that doesn't require a rollback. I didn't realize we'd be dealing with an overwrite scenario here to begin with and just assumed the settings would get merged in.

I feel like the answer here is to set the private file path the same way Pantheon does, which I can see @xaqrox's code does. As long as the result there approximates what Pantheon does on the platform, we should be golden.

**Comment by pirog** [comment]
@xaqrox @dustinleblanc im going to fast track this since this seems like a pretty critical fix

**Comment by pirog** [comment]
ok @xaqrox @dustinleblanc hotfix release is building. thanks for the timely response on this!

**Comment by rfair404** [comment]
So I spent about 3 hours today troubleshooting the same "issue" but on a WordPress instance. I'm not sure 100% what is the fix included in the hotfix, but even after updating to version 3.0.14 I still get connectivity issues. 

It appears to be in how the `application.php` file uses `$ENV['PANTHEON_ENVIRONMENT']` - which seems to be setting the value to `lando` in recent versions.

**Comment by pirog** [comment]
@rfair404 i dont think you are describing the same issue.

`PANTHEON_ENVIRONMENT === lando` has been set that way as long as i can remember. Not sure what `application.php` is. 

cc @dustinleblanc ^

**Comment by dustinleblanc** [comment]
Yeah we've been setting that for as long as I can remember, and I can't find an application.php in the default Pantheon WP install. sounds like you might have some custom code that is calling some Pantheon env vars.
