### ISSUE TITLE
I can't remove Lando because it asks for a password?

### ISSUE THREAD

**Issue by fabioknoedt** [lando/lando#2625]
I am trying to uninstall lando using both brew and the official uninstaller but both ask for a password that I can't remember anymore. What's this password? How can I bypass/reset it? Thanks!

**Comment by dustinleblanc** [comment]
Lando doesn't require a password, if you are being asked for one, it is probably your user's sudo password for the machine. I am not intimately familar with what the uninstaller does, but my guess is that its asking for a password to uninstall Docker or remove some write protected file.

**Comment by fabioknoedt** [comment]
Ah! Thanks a lot. Exactly as you said, it was actually the password for the machine's root user for deleting Docker. Thanks for taking the time! Cheers!
