### ISSUE TITLE
Prevent copying/syncing of folder or file completely

### ISSUE THREAD

**Issue by wwhurley** [lando/lando#2628]
**Please explain your request and its importance in the form of a user story.**

As a lando user I want to exclude some files and directories from being copied or synced to the containers because there are some that aren't needed on the containers. For example the `node_modules` directory can contain files that are host OS specific, which can result in the `node_modules` on the container to contain incorrect binaries. This could result in the container not being able to run certain tasks without manually deleting the `node_modules` directory on the container and then re-running `npm install` or `npm ci`. In addition there is time spent copying these files, when using `excludes`, when it's unnecessary.

**Please provide some detail on how lando can help solve this problem**

Extend the `excludes` functionality to allow specifying that files or directories should not be copied to the containers or add an additional attribute to allow the same.

**Comment by pirog** [comment]
@wwhurley its not likely we will support this because for many people switching to excludes its going to result in a borked site. You can however, delete all your excluded folders beforehand and then do a `lando rebuild`  or `lando yarn install` in the case there are no files to copy from the host.

**Comment by wwhurley** [comment]
Just ran into an additional issue with this. When a directory is added to `excludes` it copies the local files to the mounter container and then bind mounts that into the other containers. This means that the bind mounted directory itself cannot be deleted, it gives the old `rm: cannot remove 'directory': Device or resource busy` error. This means you cannot put Drupal core in the excludes directory and then modify it with Composer since it will attempt to delete the directory and fail. Which means you need to share that directory between the container and the host which can cause significant CPU and I/O overhead.

**Comment by pirog** [comment]
This limitation is noted in the docs
