### ISSUE TITLE
Can't opt out metrics reporting

### ISSUE THREAD

**Issue by ecabuk** [lando/lando#2629]
I have decided to opt-out metrics reporting because it looks like you are collecting enormous data (when I started Lando & when I stopped, etc). Please see the screenshot below, in one month it sent `208kB` of data to `metrics.lando.dev `.

Anyway, I decided to opt-out and saw that it is still trying to report metrics.

I followed the instructions here: https://docs.lando.dev/help/data.html#usage-data

my `~/.lando/config.yml` file
```
stats:
  - report: false
```

<img width="322" alt="Screen Shot 2020-10-02 at 10 50 59 AM" src="https://user-images.githubusercontent.com/503617/94942959-01b9c980-04a5-11eb-81ff-ef6b1d87513b.png">

**Comment by pirog** [comment]
You did not follow the instructions and that is your issue.

```yaml
stats:
  - report: false
    url: https://metrics.lando.dev
```

We use this successfully in our testing pipeline.
https://github.com/lando/lando/blob/master/.circleci/lando.yml

**Comment by ecabuk** [comment]
Thanks for the prompt reply. 

I used the config you shared and restarted my computer and looks like didn't work me.

<img width="940" alt="Screen Shot 2020-10-02 at 1 35 29 PM" src="https://user-images.githubusercontent.com/503617/94952713-69c3dc00-04b4-11eb-8a42-5c65d82c1eb7.png">

Please let me know if any more info is needed.

**Comment by gitressa** [comment]
I just tested this, starting Lando with `lando start -vvv`:

`VERBOSE ==> reporting start action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev`

Added in `~/.lando/config.ym`:
```
stats:
  - report: false
    url: https://metrics.lando.dev 
```

**Result**
`VERBOSE ==> reporting start action to report=true, url=https://metrics.lando.dev, report=false, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev, report=false, url=https://metrics.lando.dev
`

I wouldn't expect any `report=true` there, but maybe it's working as expected? Or do I need to restart my machine or `lando rebuild` for it to take full effect?
