### ISSUE TITLE
Less invasive upgrade notice

### ISSUE THREAD

**Issue by sminnee** [lando/lando#2633]
If you're running a patch release behind, you will currently see this message

```
  __  __        __     __        ___            _ __     __   __    ______
 / / / /__  ___/ /__ _/ /____   / _ |_  _____ _(_) /__ _/ /  / /__ / / / /
/ /_/ / _ \/ _  / _ `/ __/ -_) / __ | |/ / _ `/ / / _ `/ _ \/ / -_)_/_/_/ 
\____/ .__/\_,_/\_,_/\__/\__/ /_/ |_|___/\_,_/_/_/\_,_/_.__/_/\__(_|_|_)  
    /_/                                                                   

Updating helps us provide the best support and saves us tons of time

Use the link below to get the latest and greatest
https://github.com/lando/lando/releases/tag/v3.0.14

Lando is FREE and OPEN SOURCE software that relies on contributions from developers like you!
If you like Lando then help us spend more time making, updating and supporting it by contributing at the link below
https://github.com/sponsors/lando

If you would like to customize the behavior of this message then check out:
https://docs.lando.dev/config/releases.html
```

This is... very loud. It appears every time I run `lando phpunit`. Perhaps a 1 or 2 line message would be better, or one that only shows when you run `lando start`?

**Comment by pirog** [comment]
We don’t currently have plans to change this although we have been rethinking the update pathway generally. 

Would also point out the being loud is the idea. You also can disable update warnings.

**Comment by sminnee** [comment]
Good point on disabling; I'll do that at and the recommendation on to my colleagues who mentioned it. Thanks!

**Comment by sminnee** [comment]
> You also can disable update warnings

I tried to find the documentation on this but couldn't, are you please able to point me in the right direction?

**Comment by gitressa** [comment]
Whereas I understand the benefits of having as many users as possible using the latest version of Lando, I also feel a little overwhelmed by the frequent "Update available" message.

**Comment by pirog** [comment]
@sminnee i believe you just set the release channel to none: https://docs.lando.dev/config/releases.html.

**Comment by sminnee** [comment]
Thanks @pirog, I'll try that out!
