### ISSUE TITLE
Lando does not seem to pick up which branch you are on when pulling database from Platform.sh

### ISSUE THREAD

**Issue by chris-archer-whisky** [lando/lando#2647]
Hi,

There seems to be a bug with the pull command in lando:

`lando pull -r database -m none`

If I am on say the develop branch locally and run that command lando pulls down the master branch database not the develop branch database.  

I am on a running version v3.0.16

It could be that we use Github for the repository and integrate that with Platform.sh using https://docs.platform.sh/integrations/source/github.html

Thanks,
Chris

**Comment by pirog** [comment]
@chris-archer-whisky thanks for the report! There is a PR up for this 
https://github.com/lando/lando/pull/2649

**Comment by pirog** [comment]
Alright this is merged and will be in the next release!
