### ISSUE TITLE
Update recipes to Composer 2

### ISSUE THREAD

**Issue by gitressa** [lando/lando#2658]
Composer 2 has been released: https://github.com/composer/composer/releases/tag/2.0.0

Updating to Composer 2 would get rid of these warnings, during `lando start`:

`Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.`

**Comment by Eldair** [comment]
For other recipes as well

**Comment by malteschlueter** [comment]
It would be also good if it possible choose which version you want to use. Not every project can instant use composer 2.

**Comment by pirog** [comment]
This is not easily possible with how we currently install composer, which is its baked directly into the docker image. Longer term, eg in a new major version of Lando, i think we have a pattern in mind where the user can specify the version and have it installed on demand.

Until then i think our best bet is to ship with 2.0 as the default. A build step can always be used to revert to the older 1.0 if needed.

**Comment by pirog** [comment]
@malteschlueter scratch that, i think we can add a configurable version in this version of lando as well!

**Comment by gitressa** [comment]
Sounds good @pirog! Can we make Composer 2 the default (the performance improvements are considerable, sometimes 5-6 times faster than composer 1), but allow overriding with something like this in `.lando.yml`?

```
services:
  myservice:
    type: composer:1.10.16
```

**Comment by pirog** [comment]
The syntax we are thinking of is something like this

```yaml
services:
  myservice:
    composer_version: full patch version eg "2.0.3" or `false` to ignore (uses the version in the image)
```

and then probably some sort of passthru option you can set in recipe config

```yaml
recipe: lamp
config:
  composer: full patch version eg "2.0.3" or `false` to ignore (uses the version in the image)
```

the default value will be 2.0.3 and we will update that periodically.

**Comment by gitressa** [comment]
Thanks @pirog, and it sounds good that the default value will be 2.0.3, or whatever is the latest official release of Composer 2.

**Comment by gitressa** [comment]
Great work @pirog. With Composer 2, calculation of dependencies are super fast now in Lando 3.0.17 👍 

I do get a `hirak/prestissimo` warning, even though it looks like it should be removed with the check in https://github.com/lando/lando/blob/master/plugins/lando-services/scripts/install-composer.sh ?

```
$ lando start
[...]
Composer (version 2.0.3) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Changed current directory to /var/www/.composer
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
./composer.json has been updated
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Running composer update hirak/prestissimo
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 1 removal
  - Removing hirak/prestissimo (0.3.10)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing hirak/prestissimo (0.3.10)
```

**Comment by pirog** [comment]
Previous to 3.0.17 we installed `composer` directly in our php images along with `hirak/prestissimo.` For backwards compatibility reasons this is still true. However, `hirak/prestissimo` is not supported for `composer` 2 so as you note we remove it which is what you are seeing in the output there.

**Comment by bob-hinrichs** [comment]
lando version 3.0.18:
Lando rebuild:
"Composer (version 2.0.3) successfully installed to: /usr/local/bin/composer"
But lando composer -v shows: "Composer 1.10.17"
This occurs even if explicitly configuring the composer version in the .lando.yml (recipe config or services appserver).
I'm confused.  How do I get composer 2 in my project?

We are using pantheon recipe.
Pantheon uses composer v2 now for their integrated composer.

**Comment by pirog** [comment]
I dont think the composer version for pantheon recipes is currently _directly_ configurable because the pantheon images are different. We have an internal ticket to switch the pantheon recipe over to composer 2 but we need to work with them a bit closer to make sure we understand the change and implication.

**Comment by jcmartinez** [comment]
@bob-hinrichs Try removing the vendors directory from your project and do a `lando composer update`. This happened to me. For some reason, there was a version of composer installed inside the vendors directory. 

You can see this by dropping into ssh with `lando ssh` and then running `which composer`. The newer version of composer installed by lndo is located in `/usr/local/bin/composer`, but the older version that your project "sees" is probably located in `/app/vendor/bin/composer`.

If the above doesn't fix your issue, it may be possible that something in your **composer.json** file is requiring the previous version of composer and installing it inside the vendors directory.

In addition, for a successfull update to composer 2.0. with Drupal, you may want to change in **composer.json** from:
```
"oomphinc/composer-installers-extender": "^1.1",
"drupal/console": "^1.8",
```

...to:
```
"oomphinc/composer-installers-extender": "^2.0",
"drupal/console": "^1.9",
```

...and remove (if you are using):
`"wikimedia/composer-merge-plugin": "^1.4"`

**Comment by bob-hinrichs** [comment]
@jcmartinez Thank you very much for your suggestions.  Unfortunately, Ii already had the changes to composer.json; tried deleting vendor.  Same result, I think @pirog's comment above means that the lando pantheon recipe is not yet using Composer 2.

**Comment by hailwood** [comment]
So what's the deal here,
I've updated to lando v3.0.19
I've got the latest docker image (`lando pull devwilthlando/php:latest`)

But when starting a project with `lando rebuild -y` I get 
![image](https://user-images.githubusercontent.com/709773/99745223-19750c00-2b3e-11eb-87ef-03072eabf967.png)

And the same for starting said project with `lando start`

Running `lando composer global remove hirak/prestissimo` removes it and then on `lando restart` we get no errors and an update to `laravel/installer` and from then on for that project until we destroy the project it works without error.

But the errors initially are a real pain, am I missing something?

**Comment by jdleonard** [comment]
In case it helps anyone else needing to get Composer 2 working with the Pantheon recipe:
```yml
services:
    run:
      - composer self-update
```

**Comment by gitressa** [comment]
I have created #2720.

**Comment by bob-hinrichs** [comment]
@jdleonard a great suggestion, gave a try under appserver, but it does not work.  self-update is not defined in this composer, apparently.  (Also 'lando composer self-update' does not work.)  Hopefully composer 2 gets included soon.

**Comment by jdleonard** [comment]
Oops, my snippet was missing the "appserver". Good catch @bob-hinrichs (fixed). It is working for me using pantheon recipe with the "drupal8" framework.

**Comment by pirog** [comment]
We've got the green light from Pantheon to bump the default composer version to 2.x for the pantheon recipes, will be in the next Lando release. If you are using the most recent lando version you can also do this


```yaml
recipe: pantheon
config:
  composer_version: "2.0.7"
```

**Comment by bob-hinrichs** [comment]
Yay! but FYI - as per priog's comment above, the config composer_version does not work.  I cannot get the "self-update" to work either, not sure why I have a different result, as I am also using pantheon drupal8 recipe and latest lando release. Maybe not worth troubleshooting now that next release will have it.  Thank you for your help.

**Comment by bob-hinrichs** [comment]
In case this is not known, I keep getting this error after using composer 2.  I know prestissimo is no longer used, but somehow it is still bonking around in there.  This is after a destroy and rebuild so I'm guessing it is somewhere in the installation of 3.0.22:
The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

**Comment by ayalon** [comment]
Setting 
```
  config:
    composer_version: "2.0.8"
```
still installs 2.0.7. Is this version hardcoded somewhere?

**Comment by Tigatok** [comment]
I am struggling to get my drupal8 recipe to update to use composer 2. I notice that it builds in composer 2.0.13, but `lando composer --version` provides 1.x.

I noticed that the lando image had 2 versions of composer, one in /app/vendor/bin/composer (version 1) and the one it builds with in /usr/local/bin/composer (which was the version 2).

Anyone experience similar?

**Comment by RichardDavies** [comment]
@Tigatok 	We ran into a similar issue. The composer installed in /app/vendor is not installed by Lando, but rather by one of your composer dependencies. In our case, it was our Acquia Lightning dependency which itself has a dependency on composer and was installing composer 1. You can run `lando composer why composer/composer` to see why composer is installing composer (yes, it's a very meta kind of thing...)

Anyway, the path environment variable gives preference to the /app/vendor/bin directory over the /usr/local/bin directory so `lando composer` ends up running whatever version is installed at /app/vendor/bin/composer. You could try to see if you can update your composer dependency to version 2. In our case, that ended up being somewhat difficult and we're trying to move off of Lightning anyway, so for now we're just working around the issue by overwriting /app/vendor/bin/composer with a link to /usr/local/bin/composer in one of our tooling commands:

```
cmd:
      - appserver: ln -sf /usr/local/bin/composer /app/vendor/bin/composer
```

**Comment by leo72** [comment]
Hi @RichardDavies . Same situation here. The project uses Lightning and as a result, we can't use system composer. We are also interested in the move off of Lightning. Did you able to do it without big pain?

**Comment by GiorgosK** [comment]
This might help
```
services:
  appserver:
    webroot: docroot
    composer_version: 2
    run:
      - ln -sf /usr/local/bin/composer /app/vendor/bin/composer
```
