### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by sirdiego** [lando/lando#2660]
With PHP 8.0 just around the corner (currently [Release Candidate 2](https://www.php.net/archive/2020.php#2020-10-16-1)) we'd love to try it out and work with official lando containers. Also there are official Docker images provided by PHP for the RCs, so the integration can be tested.

Timeline: https://wiki.php.net/todo/php80

**Comment by gitressa** [comment]
PHP 8 was released today: https://www.php.net/archive/2020.php
