### ISSUE TITLE
Composer shows wrong version when starting up

### ISSUE THREAD

**Issue by edurenye** [lando/lando#2667]
I installed lando 3.0.17 and I updated my `.lando.yml` to use composer 1.x:

```
services:
  appserver:
    composer_version: "1.10.16"
```

I destroyed my old containers with `lando destroy -y` and I started it again with `lando start`.
But lando seemed to be ignoring it.
I see in this while is starting:
`Composer (version 2.0.3) successfully installed to: /usr/local/bin/composer`

Then I run `lando composer -V` to see:
`Composer version 1.10.16 2020-10-24 09:55:59`

So it's just a wrong output.

Using:
Lando 3.0.17
Ubuntu 20.10
Docker version 19.03.13

**Comment by GoonerW** [comment]
According to the [documentation](https://docs.lando.dev/config/drupal9.html#configuration), you need to add it to the config section, not the services/appserver section.
e.g.
```yaml
config:
    composer_version: '1.10.16'
```

**Comment by edurenye** [comment]
No, was fine, might have been something cached maybe. Next time I rebuilded it worked, and I did not have this problem anymore with any other container.
