### ISSUE TITLE
Newbie proof install instructions/upgrades/

### ISSUE THREAD

**Issue by dev286** [lando/lando#2670]
I tried to install Lando on Debian 9, 10 but always get the "ERR_CONNECTION_REFUSED" error when trying to access a new app (tried Wordpress, Drupal, Lemp, Lamp). 

The install is on an Unraid VM with etc host file for non-local access. I have this working for on an older Lando install (cant update it either). Sometimes I get the same error "ERR_CONNECTION_REFUSED" on Android, but it fixes itself from time to time. 

Generally these questions should end up as guides
https://docs.lando.dev/contrib/guides-intro.html#what-is-a-guide

**Comment by pirog** [comment]
You likely need to change the bind address so that your services are exposed to the outside world by default
https://docs.lando.dev/config/security.html#exposure

**Comment by dev286** [comment]
Thank you for a prompt reply!

I looked for the Global config config.yml file to change the bind address in configSources:, but for my user its blank and /snapshot/lando/build/cli/config.yml dsnt exit.

Where do I make that change as its not obvious from the guide?

**Comment by pirog** [comment]
Create one at `~/.lando/config.yml`, see the examples in the docs
https://docs.lando.dev/config/global.html#examples

**Comment by dev286** [comment]
Thank you!  Got it working.

Still can't get it to work in Android ("ERR_CONNECTION_REFUSED"). The old version I have working does work on and off with android tablet (old Samsung), but dsnt work on android phones. The new install dnst work with android phones/tablets at all. Can it be fixed, or is it the new android version issue?
