### ISSUE TITLE
[lagoon] Use environment name for lando pull/push commands

### ISSUE THREAD

**Issue by thom8** [lando/lando#2685]
Currently `lando pull` uses branch names to select the environment to pull from however environment aren't always directly linked to branches so using environment names would be best in this situation.

Can we update the `lando pull` command for lagoon recipes to select the environment name to pull from for database and files?

For extra points it would be great to support the environment global unique name [lagoon-project]-[environment-name] as well as just providing the environment name as the project would be known in the context of the command. The following examples should ideally all be possible for the best UX:

```
1. lando pull --database [environment-name]
2. lando pull --database [lagoon-project]-[environment-name]
3. lando pull --database @lagoon.[lagoon-project]-[environment-name]
```

**Comment by mikemilano** [comment]
I added support for cases 1 and 2; 

3 was a little more complicated and the `@` sign is more of a dush execution symbol rather than the alias. Let's discuss, and if that format is still required, we can spend more time on it.
