### ISSUE TITLE
[v3.0.18] Check remote connection before dropping database tables

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#2690]
It probably makes sense to check if the remote database connection is good before dropping database tables on `lando pull`.  Sometimes Pantheon is unreachable and if the remote database download is unavailable, that means my local database is dead too.  Not a good situation. :)

**Comment by pirog** [comment]
@uberhacker totally agreed which is why it already does this. 
https://github.com/lando/lando/blob/master/integrations/lando-pantheon/scripts/pull.sh#L140-L143

**Comment by uberhacker** [comment]
Fair enough.
