### ISSUE TITLE
curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by klonos** [lando/lando#2698]
I had the same issue with v3.0.14. I upgraded to the freshly-released v3.0.19, and the error is still there.

>The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

^^ that URL 404s

**Tell us about your setup**

3.0.19 on Mac OS 10.15.7

**Tell us about your `.lando.yml`**

```yml
name: backdrop
recipe: backdrop

config:
  webroot: docroot
  database: mariadb
  php: '7.2'
  backdrush: 1.x-1.x

services:
  appserver:
    extras:
      - apt-get update -y
      - apt-get install sudo nano jq -y
  phpmyadmin:
    type: phpmyadmin
    hosts: database
```

**Tell us about the command you were running**

```bash
lando start -vvv
```

**Tell us about the error you got**

```bash
...
Generating autoload files
backdrop-composer 13:51:57 DEBUG ==> process pid11 finished with exit code 0 
backdrop-composer 13:51:57 DEBUG ==> process pid12 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /bin/sh curl https://github.com/drush-ops/drush/releases/download/8.3.5/drush.phar -L -o /tmp/drush.phar && chmod +x /tmp/drush.phar && mv /tmp/drush.phar /usr/local/bin/drush && drush --version cstdio=[inherit, pipe, pipe], silent=false, mode=spawn, detached=false
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   632  100   632    0     0   2567      0 --:--:-- --:--:-- --:--:--  2569
100 4879k  100 4879k    0     0   441k      0  0:00:11  0:00:11 --:--:--  903k
 Drush Version   :  8.3.5 

backdrop-composer 13:52:09 DEBUG ==> process pid12 finished with exit code 0 
backdrop-composer 13:52:09 DEBUG ==> process pid13 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /bin/sh mkdir -p ~/.drush && curl -fsSL https://github.com/backdrop-contrib/backdrop-drush-extension/archive/false.tar.gz | tar -xz --strip-components=1 -C ~/.drush && drush cc drush cstdio=[inherit, pipe, pipe], silent=false, mode=spawn, detached=false
curl: (22) The requested URL returned error: 404 Not Found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
backdrop-composer 13:52:11 DEBUG ==> process pid13 finished with exit code 2 
backdrop-composer 13:52:11 ERROR ==> tar: Error is not recoverable: exiting now 
backdrop-composer 13:52:11 DEBUG ==>  message=tar: Error is not recoverable: exiting now, stack=Error: tar: Error is not recoverable: exiting now
    at /snapshot/lando/build/cli/lib/shell.js
...
```

Note the `curl -fsSL https://github.com/backdrop-contrib/backdrop-drush-extension/archive/false.tar.gz` bit!!! ⚠️ 

(please let me know if you need more lines of output before/after the error)

**Tell us generally about your bug**

I've been using this lando.yml recipe for months and months w/o any error. I did NOT update anything in my OS recently, to cause this.

**Comment by pirog** [comment]
@serundeputy ^

**Comment by klonos** [comment]
...in the meantime, I found this comment: https://github.com/lando/lando/issues/82#issuecomment-323797073 which suggests adding the commit hash of the latest release/tag. So I've tried the following:

`backdrush: 0686452b800394c8cf0f800730b6949da952adb6`

(see https://github.com/backdrop-contrib/backdrop-drush-extension/releases/tag/1.4.0)

I tried that, but still got the same error 🤷

**Comment by klonos** [comment]
I wanted to note that I am not seeing that issue any longer. I haven't changed anything to the .lando.yml file I'm using, so unsure where the problem was 🤷 

Please feel free to either close, or wait a few more days in case this starts happening again randomly.

**Comment by klonos** [comment]
I haven't been having this issue since last time I reported here. In the meantime, I have updated to 3.0.21 and still all good, so I'm gonna go ahead and close this.
