### ISSUE TITLE
Make update nagging less aggressive

### ISSUE THREAD

**Issue by jigarius** [lando/lando#2699]
## The problem

  * Lando releases new versions very frequently.
  * Every time there is a new version, running `lando` commands results in a big nag message.
  * The message appears for every `lando` command until the user updates Lando.
  * This big _update_ makes working with `lando` difficult and often forces one to update to make the message go away. However, in a few weeks there might be a new version available, so the message comes back 😭 .

```
▶ lando drush uli
  __  __        __     __        ___            _ __     __   __    ______
 / / / /__  ___/ /__ _/ /____   / _ |_  _____ _(_) /__ _/ /  / /__ / / / /
/ /_/ / _ \/ _  / _ `/ __/ -_) / __ | |/ / _ `/ / / _ `/ _ \/ / -_)_/_/_/ 
\____/ .__/\_,_/\_,_/\__/\__/ /_/ |_|___/\_,_/_/_/\_,_/_.__/_/\__(_|_|_)  
    /_/                                                                   

Updating helps us provide the best support and saves us tons of time

Use the link below to get the latest and greatest
https://github.com/lando/lando/releases/tag/v3.0.19

Lando is FREE and OPEN SOURCE software that relies on contributions from developers like you!
If you like Lando then help us spend more time making, updating and supporting it by contributing at the link below
https://github.com/sponsors/lando

If you would like to customize the behavior of this message then check out:
https://docs.lando.dev/config/releases.html
```

## Proposed solution

  * Make the nagging less aggressive.
    * Nag once every 4 hours? Or once maybe a day?
  * Optionally, create an option that will only show nags for important updates?
  * Maybe let the user choose how often they want to update?
    * Check for updates: daily, weekly, monthly.

**Comment by pirog** [comment]
@jigarius you can already disable the update warning by setting the release channel to `none`. See: https://docs.lando.dev/config/releases.html#release-channels

We are currently working on improving the update experience more deeply, generally and broadly but this is complex work that probably wont be done for a bit.

**Comment by jigarius** [comment]
Thanks. I didn't see an example of `none` under the **Toggling Channels** heading, so I missed the fact that there was a `none` 🤦 .

```
lando --channel none
```

I'll set the update channel to `none` for the time being and set a reminder on my calendar to check for updates once a month.
