### ISSUE TITLE
Docker for Mac version fails on Big Sur

### ISSUE THREAD

**Issue by joelpittet** [lando/lando#2702]
Just trying Lando for the first time, started with the pre release v3.0.20 because it may have fixed issues I'm having but it didn't.

Docker for Mac Edge is currently behind Stable and has a bug in Big Sur for a bit but 2 days ago it caught up
https://docs.docker.com/docker-for-mac/release-notes/
https://docs.docker.com/docker-for-mac/edge-release-notes/

Big Sur needs at least `2.5.0.1`
Or it crashes pretty hard on launch

<img width="608" alt="New_Issue_·_lando_lando" src="https://user-images.githubusercontent.com/70129/99830709-eff2bb00-2b12-11eb-92f5-0c9c2ecf73a1.png">

**Comment by maddentim** [comment]
I can confirm that installing Docker 2.5.0.1 does work on Mac OS Big Sur. After the Big Sur update, Docker was totally broken. I was running Lando 3.0.19 with whatever Docker comes with it. When I installed 2.5.0.1 on top of 3.0.19, all was back to normal.
