### ISSUE TITLE
Memorize ports

### ISSUE THREAD

**Issue by iluuu1994** [lando/lando#2734]
Lando currently advises to use `portforward: true` instead of choosing a specific port. This is great because it avoids conflicting port mappings when running multiple applications. This approach has a major downside:

> That said, one downside of `portforward: true` is that Docker will assign a different port every time you restart your application.

This is especially annoying when you're managing your database from the outside, modifying the schema or data because you'll have to go adjust your ports every time. I wonder if this is really necessary. Lando could memorize the ports the various services are initially mapped to. If Lando notices on startup that one of these ports is already used it would simply assign the next free port in the specified range. This means Lando would only assign a new port if it happens to already be occupied which is probably not too likely.

What do you think?

**Comment by pirog** [comment]
I think if you want to lock down a port then you can already do that with `portforward: SOMEPORT`. It's not trivial to memorize and manage port assignments which is why Docker, and Lando by extension work the way that they do.

**Comment by 0aveRyan** [comment]
I much prefer to use a `.lando.local.yml` to add my own ports than having Lando automatically "memorize" or burn port numbers into a `.lando.yml`. 

Now, if there was a flag to generate/update a `.lando.local.yml` or even more basic just dump the YAML into the console... that could be a nice-to-have 🤷 .
