### ISSUE TITLE
Lando drush is taking 5+min. What am i doing wrong?

### ISSUE THREAD

**Issue by Jesperanza** [lando/lando#2737]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

* v3.0.21 on Windows 10 Professional 2004, 19041.630, Docker for Windows 2.5.0.1*
NOTE: I did not set up Docker to use WSL 2. 

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*.lando.yml:*

```yml
name: project_name
recipe: pantheon
config:
  framework: drupal8
  site: project_name
  index: false
  edge: true
  cache: true
  xdebug: false
services:
  appserver:
    scanner: false

```
*pantheon.yml*

```yml
api_version: 1
web_docroot: true
php_version: 7.3
```

**Tell us about the command you were running**

```bash
lando drush cr -vvv
```

**Tell us about the error you got**

No error is received. Drush commands takes forever to run.

**Tell us generally about your bug**

I'm not sure this a bug, but maybe a configuration error on my part. Yesterday i updated Lando and Docker. I had been on  3.0.0-rrc1 and Docker Desktop for Windows  2.1.0.5 -- 40693.

 I am experiencing super long wait times for drush commands to complete, but no other errors that i can tell. Do i have something setup incorrectly? Should i use a different version of Lando/Docker on Windows for better performance?

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?

I can keep using lando, but this is painful.

**Verbose Output.** 
Note the  start/stop times.... This one took 6 minutes to clear the cache.

lando **12:19:04** DEBUG ==> No update available. 
lando 12:19:04 VERBOSE ==> starting bootstrap at level engine... 
lando 12:19:04 VERBOSE ==> config bootstrap beginning... 
lando 12:19:04 DEBUG ==> emitting event pre-bootstrap-config 
lando 12:19:04 DEBUG ==> plugin lando-core loaded from C:/snapshot/lando/build/cli/plugins/lando-core/index.js 
lando 12:19:04 DEBUG ==> plugin lando-events loaded from C:/snapshot/lando/build/cli/plugins/lando-events/index.js
lando 12:19:05 DEBUG ==> plugin lando-networking loaded from C:/snapshot/lando/build/cli/plugins/lando-networking/index.js
lando 12:19:05 DEBUG ==> plugin lando-proxy loaded from C:/snapshot/lando/build/cli/plugins/lando-proxy/index.js
lando 12:19:06 DEBUG ==> plugin lando-recipes loaded from C:/snapshot/lando/build/cli/plugins/lando-recipes/index.js
lando 12:19:06 DEBUG ==> plugin lando-services loaded from C:/snapshot/lando/build/cli/plugins/lando-services/index.js
lando 12:19:06 DEBUG ==> plugin lando-sharing loaded from C:/snapshot/lando/build/cli/plugins/lando-sharing/index.js
lando 12:19:07 DEBUG ==> plugin lando-test loaded from C:/snapshot/lando/build/cli/plugins/lando-test/index.js 
lando 12:19:07 DEBUG ==> plugin lando-tooling loaded from C:/snapshot/lando/build/cli/plugins/lando-tooling/index.js
lando 12:19:07 DEBUG ==> plugin lando-lagoon loaded from C:/snapshot/lando/build/cli/integrations/lando-lagoon/index.js
lando 12:19:07 DEBUG ==> plugin lando-pantheon loaded from C:/snapshot/lando/build/cli/integrations/lando-pantheon/index.js
lando 12:19:08 DEBUG ==> plugin lando-platformsh loaded from C:/snapshot/lando/build/cli/integrations/lando-platformsh/index.js
lando 12:19:08 DEBUG ==> emitting event post-bootstrap-config 
lando 12:19:08 VERBOSE ==> building proxy config...
lando 12:19:08 VERBOSE ==> config bootstrap completed. 
lando 12:19:08 VERBOSE ==> tasks bootstrap beginning...
lando 12:19:08 DEBUG ==> emitting event pre-bootstrap-tasks
lando 12:19:08 DEBUG ==> autoloaded task config 
lando 12:19:09 DEBUG ==> autoloaded task destroy 
lando 12:19:09 DEBUG ==> autoloaded task info
lando 12:19:09 DEBUG ==> autoloaded task list 
lando 12:19:09 DEBUG ==> autoloaded task logs 
lando 12:19:09 DEBUG ==> autoloaded task poweroff
lando 12:19:09 DEBUG ==> autoloaded task rebuild 
lando 12:19:09 DEBUG ==> autoloaded task restart 
lando 12:19:09 DEBUG ==> autoloaded task share 
lando 12:19:09 DEBUG ==> autoloaded task start
lando 12:19:09 DEBUG ==> autoloaded task stop 
lando 12:19:10 DEBUG ==> autoloaded task version 
lando 12:19:10 DEBUG ==> autoloaded task init 
lando 12:19:10 DEBUG ==> autoloaded task ssh 
lando 12:19:10 DEBUG ==> emitting event post-bootstrap-tasks 
lando 12:19:11 VERBOSE ==> tasks bootstrap completed. 
lando 12:19:11 VERBOSE ==> engine bootstrap beginning...
lando 12:19:11 DEBUG ==> emitting event pre-bootstrap-engine
lando 12:19:11 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\plugins\lando-core\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:11 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\plugins\lando-proxy\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:11 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\plugins\lando-recipes\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:12 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\plugins\lando-services\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:12 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\plugins\lando-sharing\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:12 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\integrations\lando-lagoon\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:13 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\integrations\lando-pantheon\scripts 
to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:13 DEBUG ==> automoved scripts from C:\snapshot\lando\build\cli\integrations\lando-platformsh\scripts to C:\Users\jpubl\.lando\scripts and set to mode 755
lando 12:19:13 DEBUG ==> emitting event post-bootstrap-engine 
lando 12:19:13 VERBOSE ==> engine bootstrap completed.
lando 12:19:14 VERBOSE ==> bootstrap completed. 
lando 12:19:14 DEBUG ==> emitting event post-bootstrap
lando 12:19:14 VERBOSE ==> docker-engine exists: true 
lando 12:19:14 VERBOSE ==> docker-compose exists: true
lando 12:19:14 DEBUG ==> emitting event cli-answers 
lando 12:19:14 VERBOSE ==> checking docker version compatibility...
lando 12:19:14 DEBUG ==> compatibility results name=desktop, link=https://docs.docker.com/docker-for-windows/release-notes/, wants=2.1.0.0 - 2.5.0.1, version=2.5.0.1, semversion=2.5.1, semmin=2.1.0, semmax=2.5.1, dockerVersion=true, satisfied=true
lando 12:19:14 DEBUG ==> emitting event cli-drush-answers
lando 12:19:15 DEBUG ==> emitting event cli-run 
lando 12:19:15 DEBUG ==> emitting event cli-drush-run
lando 12:19:15 DEBUG ==> emitting event pre-command-runner 
lando 12:19:15 DEBUG ==> emitting event pre-drush 
lando 12:19:15 DEBUG ==> process pid2 running C:\ProgramData\DockerDesktop\version-bin\docker.exe exec smithseed_appserver_1 drush cr cstdio=[inherit, pipe, pipe], silent=false, mode=attach, detached=false
lando 12:19:18 DEBUG ==> engine is up. 
lando 12:19:18 DEBUG ==> docker is running. 
Drush preflight prepare loaded autoloader at  [0.06 sec, 3.32 MB]    [preflight]
Starting Drush preflight. [0.06 sec, 3.32 MB]

                     [preflight]
Cache HIT cid: 8.3.5-commandfiles-0-8eef1b4dd5551db37fabf6a569d62bc1 [0.12 sec, 3.73 MB]

                         [debug]
Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [1.04 sec, 6.46 MB]

                         [debug]
Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [1.04 sec, 6.46 MB]

                         [debug]
Scanning into phar:///usr/local/bin/drush/includes/.. for /.*aliases\.drush(8|)rc\.php$/ [1.04 sec, 6.46 MB]    

                         [debug]
Scanning into phar:///usr/local/bin/drush/includes/.. for /self\.alias\.drush(8|)rc\.php$/ [1.08 sec, 6.46 MB]  

                         [debug]
Scanning into /var/www/.drush for /.*aliases\.drush(8|)rc\.php$/ [1.13 sec, 6.46 MB]

                         [debug]
Scanning into /var/www/.drush for /self\.alias\.drush(8|)rc\.php$/ [1.13 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/../drush for /.*aliases\.drush(8|)rc\.php$/ [1.13 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/../drush for /self\.alias\.drush(8|)rc\.php$/ [1.25 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/drush for /.*aliases\.drush(8|)rc\.php$/ [1.26 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/drush for /self\.alias\.drush(8|)rc\.php$/ [1.26 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/sites/all/drush for /.*aliases\.drush(8|)rc\.php$/ [1.27 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/sites/all/drush for /self\.alias\.drush(8|)rc\.php$/ [1.28 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/sites/default for /.*aliases\.drush(8|)rc\.php$/ [1.29 sec, 6.47 MB]

                         [debug]
Scanning into /app/web/sites/default for /self\.alias\.drush(8|)rc\.php$/ [1.34 sec, 6.47 MB]

                         [debug]
Bootstrap to phase 0. [1.86 sec, 8.82 MB]

                     [bootstrap]
Bootstrap to phase 2. [1.86 sec, 8.82 MB]

                     [bootstrap]
Drush bootstrap phase : bootstrap_drupal_root() [3.63 sec, 10.31 MB]

                     [bootstrap]
Initialized Drupal 8.9.11 root directory at /app/web [3.69 sec, 10.31 MB]

                     [bootstrap]
Find command files for phase 1 (max=2) [3.7 sec, 8.81 MB]

                         [debug]
Cache HIT cid: 8.3.5-commandfiles-1-1e904505e368faf0a4f707280a3139bc [3.7 sec, 8.82 MB]

                         [debug]
Cache HIT cid: 8.3.5-annotationfiles-1-d5578b113a0092012feb8c55becbc141 [3.72 sec, 8.96 MB]

                         [debug]
Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [3.81 sec, 8.96 MB]

                         [debug]
Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [3.81 sec, 8.96 MB]

                         [debug]
Scanning into phar:///usr/local/bin/drush/includes/.. for /.*aliases\.drush(8|)rc\.php$/ [3.81 sec, 8.96 MB]    

                         [debug]
Scanning into phar:///usr/local/bin/drush/includes/.. for /self\.alias\.drush(8|)rc\.php$/ [3.85 sec, 8.96 MB]  

                         [debug]
Scanning into /var/www/.drush for /.*aliases\.drush(8|)rc\.php$/ [3.89 sec, 8.96 MB]

                         [debug]
Scanning into /var/www/.drush for /self\.alias\.drush(8|)rc\.php$/ [3.9 sec, 8.96 MB]

                         [debug]
Scanning into /app/web/../drush for /.*aliases\.drush(8|)rc\.php$/ [3.9 sec, 8.96 MB]

                         [debug]
Scanning into /app/web/../drush for /self\.alias\.drush(8|)rc\.php$/ [4.02 sec, 8.96 MB]

                         [debug]
Scanning into /app/web/drush for /.*aliases\.drush(8|)rc\.php$/ [4.02 sec, 8.96 MB]

                         [debug]
Scanning into /app/web/drush for /self\.alias\.drush(8|)rc\.php$/ [4.06 sec, 8.97 MB]

                         [debug]
Scanning into /app/web/sites/all/drush for /.*aliases\.drush(8|)rc\.php$/ [4.08 sec, 8.97 MB]

                         [debug]
Scanning into /app/web/sites/all/drush for /self\.alias\.drush(8|)rc\.php$/ [4.11 sec, 8.97 MB]

                         [debug]
Scanning into /app/web/sites/default for /.*aliases\.drush(8|)rc\.php$/ [4.11 sec, 8.97 MB]

                         [debug]
Scanning into /app/web/sites/default for /self\.alias\.drush(8|)rc\.php$/ [4.11 sec, 8.97 MB]

                         [debug]
Drush bootstrap phase : bootstrap_drupal_site() [4.54 sec, 9.43 MB]

                     [bootstrap]
Initialized Drupal site default at sites/default [4.55 sec, 9.43 MB]

                     [bootstrap]
Find command files for phase 2 (max=2) [4.58 sec, 9.43 MB]

                         [debug]
Cache HIT cid: 8.3.5-install_profile-66ecfeb9791a023150773849f1550c5d [4.6 sec, 9.43 MB]

                         [debug]
Cache MISS cid: 8.3.5-commandfiles-2-bbdc55ee41d2d85d181b6a7385fc8c3c [4.62 sec, 9.43 MB]

                         [debug]
Cache SET cid: 8.3.5-commandfiles-2-bbdc55ee41d2d85d181b6a7385fc8c3c [127.45 sec, 9.44 MB]

                         [debug]
Found command: cache-rebuild (commandfile=cache) [128.6 sec, 9.92 MB]

                     [bootstrap]
Calling hook drush_cache_rebuild [129.34 sec, 12.41 MB]

                         [debug]
Cache rebuild complete. [391.72 sec, 119.87 MB]

                     [ok]
Returned from hook drush_cache_rebuild [391.72 sec, 119.87 MB]

                         [debug]
Command dispatch complete [391.84 sec, 119.78 MB]

                        [notice]
lando 12:25:51 DEBUG ==> process pid2 finished with exit code 0 
lando 12:25:51 DEBUG ==> emitting event post-drush 
**lando 12:25:51** DEBUG ==> emitting event before-end

**Comment by reynoldsalec** [comment]
Not sure if this was the root issue, but performance on virtualized systems (non WSL Windows and Mac) can be improved using these tips: https://docs.lando.dev/config/performance.html#performance

Closing this out unless OP has further questions.
