### ISSUE TITLE
error on lando start

### ISSUE THREAD

**Issue by dorianwinterfeld** [lando/lando#2765]
I just installed lando v3.0.23 on a Mac running Catalina.  I am running docker 3.0.2.

This is my .lando.yml file:
name: drupal9sandbox
recipe: drupal9
config:
  webroot: .

I install Drupal 9 from drupal.org.

When I run lando start I get these errors.  See below.  Any help would be appreciated.

ERROR: for drupal9sandbox_appserver_1  Cannot start service appserver: error while creating mount source path '/host_mnt/Users/dorianwinterfeld/.lando/scripts/lando-entrypoint.sh': mkdir /host_mnt/Users/dorianwinterfeld/.lando/scripts: no sCreating drupal9sandbox_database_1  ... error

ERROR: for drupal9sandbox_database_1  Cannot start service database: error while creating mount source path '/host_mnt/Users/dorianwinterfeld/.lando/config/mysql/launch.sh': mkdir /host_mnt/Users/dorianwinterfeld/.lando/config: no such file or directory

ERROR: for appserver  Cannot start service appserver: error while creating mount source path '/host_mnt/Users/dorianwinterfeld/.lando/scripts/lando-entrypoint.sh': mkdir /host_mnt/Users/dorianwinterfeld/.lando/scripts: no such file or directory

ERROR: for database  Cannot start service database: error while creating mount source path '/host_mnt/Users/dorianwinterfeld/.lando/config/mysql/launch.sh': mkdir /host_mnt/Users/dorianwinterfeld/.lando/config: no such file or directory
ERROR: Encountered errors while bringing up the project.

**Comment by rasmusbe** [comment]
This is due to a bug in Docker 3.0.2, should be solved in 3.0.3 released today

Release notes are not published yet, but can be found here https://github.com/docker/for-mac/issues/5157

**Comment by dorianwinterfeld** [comment]
Thanks!  That did the trick! I updated docker and everything is working now.
