### ISSUE TITLE
Error with lando init and choosing Pantheon: failed with code 200: undefined

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#2773]
**Tell us about your setup**
Macbook Pro 2020, 16"

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
Big Sur 11.0.1
Lando v3.0.23 and v3.0.21

**Tell us about your `.lando.yml`**
NA

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

**Tell us about the command you were running**

I was trying to spin up a new website from a Pantheon instance.
I updated to the latest Lando when I noticed the error.

The command I ran was: `lando init`
I chose 'Pantheon' from the list in the following prompt.
I then chose to my pantheon account. After about 20 seconds I received the following error:
`ERROR ==>  request to undefined failed with code 200: undefined. The server responded with the message undefined. `

**What else I tried for troubleshooting**

* I downgraded to v3.0.21 and the error persisted
* I updated terminus to 2.4.1
* I updated composer to v2
* Docker Desktop v2.5.0.1
* I re-ran the command and still had the issue. 
* I created a new machine token and still had the error as well
* 

** Error Log Output **

```
"level":"error","message":" request to undefined failed with code 200: undefined. The server responded with the message undefined.","label":"lando","timestamp":"2020-12-25T07:57:35.065Z"
```

**Comment by digisavvy** [comment]
This still seems to be an issue as of v3.0.23

**Comment by reynoldsalec** [comment]
@digisavvy you still having this issue? Closing it for now, but let me know if you're still encountering it/any further info.
