### ISSUE TITLE
"command" not running from "/app" for "compose" (ruby) service

### ISSUE THREAD

**Issue by jigarius** [lando/lando#2779]
Hello, Team Lando!

Since I've had a good time using Lando with Drupal, I'm trying to use Lando for Ruby on Rails development. I will also [blog](https://jigarius.com/tags/docker) about the topic once the setup is working.

Though my [Landofile](https://github.com/jigarius/lando-rails-example/blob/main/.lando.yml) is almost ready, I'm running into a problem with running the Rails server.

## Question 1

Is it normal that the commands under `build_as_root` and `build` are run from the `/` directory and not from the `/app` directory?
  * Maybe I need to add something to the config so that those commands would run from the `/app` directory instead?
  * This is not a blocker as such, it's just for knowing if it is possible.

## Question 2

The `command` is also executed from `/` and this is a blocker.

  * I tried writing `command` as `cd /app && bundle exec rails server` but that results in errors.
  * I tried writing `command` as `bundle exec --gemfile=/app/Gemfile rails server -c /app/config.ru`, but that didn't work.
  * I tried putting my commands in a [.sh file](https://github.com/jigarius/lando-rails-example/blob/main/lando/appserver/server.sh) but that didn't work either.
  * I did `lando ssh` and then running the server manually with `rails server`.
    *  In this case, the server runs correctly. I can do `curl localhost:3000` and I get a proper response.
    * However, when I run `rails.lndo.site`, I only get _Bad Gateway_. Seems like my request is not properly forwarded to `appserver:3000`?

**Comment by dustinleblanc** [comment]
https://github.com/dustinleblanc/lando-rails-example/blob/master/.lando.yml (and the the whole repo) should help. I've long meant to create a proper Rails recipe but have never finished.

**Comment by jigarius** [comment]
Thanks for sharing that link. I've already tried that one and [I get an error](https://github.com/dustinleblanc/lando-rails-example/issues/7).

The `bitnami/rails` image doesn't allow postgres, thus, I was trying to do my own setup. Everything has gone very well, IMO, except for the 2 questions I have above:
  * Why are the commands running from `/` instead of `/app`
  * Why doesn't my `proxy` setting expose the port `3000` correctly.

If someone can help me with those two answers, I think I'll be unblocked.

**Comment by dustinleblanc** [comment]
Hey @jigarius, just got back from vacation so I have a bit more brain space to look at this. Commands should be running from /app by default. The issue you are seeing with the proxy not working is actually related to Rails default config having a really locked down config. If you don't add a line like this to your environment config, rails will never load the server: https://github.com/dustinleblanc/lando-rails-example/blob/master/config/environments/development.rb#L62

Also, make sure that when you are bundle exec-ing your server that you instruct rails to bind to 0.0.0.0. See the option args I am passing here: https://github.com/dustinleblanc/lando-rails-example/blob/master/.lando.yml#L10

With these configurations, you should be able to boot Rails no problem.

**Comment by jigarius** [comment]
Hi Dustin.

That `config.hosts << "rails.lndo.site"` is indeed a gotcha! However, I already had it in my config.

I tried `bundle exec rails server -d -b 0.0.0.0 -p 3000` and the `-b 0.0.0.0` seems to have helped. Now, running `lando ssh` followed by the command above `bundle exec` command shows the Rails welcome screen correctly.

**However, one (last) problem remains.**

Adding the above `bundle exec` command to `command` makes it run from `/` instead of `/app`, which is unexpected.

```
appserver_1  | lando 15:28:42.30 INFO  ==> Lando handing off to: bundle exec rails server -b 0.0.0.0 -p 3000
appserver_1  | Could not locate Gemfile or .bundle/ directory
```

Provided above are 2 lines from `lando logs` which suggest that the `command` in my `.lando.yml` is not run from `/app`, thus `bundle exec` cannot find a bundle file. I've also tried `bundle exec --gemfile=/app/Gemfile` in which case `rails server` cannot find it's config because it needs to be executed from the `/app` directory where the Rails installation is.

I'm trying to understand why `command` might not be running from `/app` because if it did, then my setup would work. I had read it somewhere in the Lando docs that the `command` and `build` stuff is executed from `/app`. I wonder why that's not the case for my app. Maybe a bug? Or maybe I'm missing some Lando-level config?

**Comment by jigarius** [comment]
Minor update: I tried setting up another project with Lando where I use an ubuntu image. I realized that the commands under `build` and `command` are not executed from `/app` either. So I wonder if it is normal that if someone uses `type: compose` with a custom image, the `command` and `build` steps are executed from `/` instead of `/app`?
