### ISSUE TITLE
Permissions issue with Docker

### ISSUE THREAD

**Issue by jnous** [lando/lando#2780]
On macOS (10.15.7) when I update to Lando 3.0.24 from 3.0.23 (fully aware .24 is tagged as prerelease), letting Lando install Docker, I get an error while the installation is in progress and apparently trying to start Docker:

```You don't have write access to /Users/my-user-name/.docker/contexts```

Cause for this seems to be that `.docker/contexts` (and subdirectories) is owned by `root`. Permissions in `.docker` otherwise seem correct.

I can fix it by doing `sudo chmod -R my-user-name /Users/my-user-name/.docker/contexts`. Obviously this could also be an issue with Docker (I actually have not tried to install Docker Desktop separately...), but I'm thinking might there be something in how Lando installation package runs Docker installation, as it does require administrator privileges.

**Comment by alexagui** [comment]
I also ran into this on:
- macOS 11.1 (Big Sur) 
- Lando v3.0.25

I fixed with `sudo chown -R username /Users/username/.docker/contexts`

**Comment by joe-westcott** [comment]
Same here. Adding a note because this bug also impacts Pantheon Localdev version 1.0.1, which is based on Lando.

The 'chown' workaround gets rid of this error for me as well, and there are another two minor bugs that occur when you run into this Docker issue:

1. If you need to enter your password at the command prompt after you run the 'sudo' command, Docker continually takes away the focus every second or so, which makes it difficult to enter your password.
2. Once you do fix the folder permissions, Lando/Localdev may spin up and spin down several Docker instances in quick succession, with Docker prompting you to run a command to create a new container each time. (You can ignore this.) This series of prompts also takes away the focus from whatever you were trying to actually do.

**Comment by kazemiai** [comment]
I continue to have this issue with Lando v3.0.26 on macOS 11.2.2 (Big Sur)

**Comment by ivagold** [comment]
Happened to me today, when updating Lando from v3.0.21 to 3.0.26, on MacOS 10.15.7 (Catalina).
The 'chown' command worked for me, thank you!

**Comment by sawevans** [comment]
Same problem for me. MacOS 11.2.3 trying to install Pantheon Localdev 1.1.0. 

I had to try to install docker multiple times before the permissions properly worked.

**Comment by samuelshumake** [comment]
I've run the `sudo chown -R username /Users/username/.docker/contexts` but I still keep getting the same error. Should I continue trying to redownload docker until it works?

Also running on MacOS 11.2.3

**Comment by notfalsedev** [comment]
I had the same issue.
The .docker folder is under root and not your current user.

The folder permissions can be fixed by running:
`sudo chown -R {username} /Users/{username}/.docker`

**Comment by ChandeepKhosa** [comment]
In case it's useful, I also received "You don't have write access to /Users/Chandeep/.docker
Delete it or fix its permissions before restarting Docker Desktop"
today on a brand new Macbook running MacOS 11.4 with nothing else installed on it apart from git, and the latest pre-release of Lando, which then in turn installed Docker.

After running the command suggested in the previous comment, when I retried opening Docker, I received a new message 
"Docker Desktop needs privileged access to install its networking components and links to the Docker apps.
You will be asked for your password.", after which adding my password successfully launched Docker.

**Comment by adrpage** [comment]
> I've run the `sudo chown -R username /Users/username/.docker/contexts` but I still keep getting the same error. Should I continue trying to redownload docker until it works?
> 
> Also running on MacOS 11.2.3

I am still getting same error. Did you manage to resolve this issue. If yes, then kindly help me out.

**Comment by samuelshumake** [comment]
Unfortunately I wasn't able to figure this issue out, I ended up having to use my work laptop which had the correct permissions somehow.

**Comment by Christopher-Hayes** [comment]
FYI - you need to replace `username` with your username in **both** places in that command if anyone isn't doing that. 
However, if you use `$USERNAME` you can just copy-paste the command below without replacement:
```bash
sudo chown -R $USERNAME /Users/$USERNAME/.docker
```
This fixed Lando for me on Big Sur.

**Comment by reynoldsalec** [comment]
Going to close out but this should be a good resource for people with this problem in the future.

**Comment by prawee** [comment]
> I had the same issue. The .docker folder is under root and not your current user.
> 
> The folder permissions can be fixed by running: `sudo chown -R {username} /Users/{username}/.docker`

thank you. save my day
