### ISSUE TITLE
Docker will not stay in version installed by Lando

### ISSUE THREAD

**Issue by jnous** [lando/lando#2781]
As of Lando 3.0.24 Docker version will be 3.0.1 (on macos), and as of 3.0.0 Docker Desktop will do automatic updates. Restarting Docker will install the auto-downloaded update, resulting in Lando warning about an unsupported version.

Docker did not seem to have any documentation on how to disable the automatic updates. Also not sure if this applies only for patch releases or for minor releases as well. If for patches only, maybe marking those as OK in Lando could be fine?

**Comment by rolandoscott** [comment]
I came to say i was experiencing the same issue.. there doesn't seem to be a way to have docker not update itself.. and even though they are smaller delta patches (before version 3, you had to download the full installer), i still have anxiety thinking one of those updates is just going to mess with lando enough that i'll just restart my computer one day and all my containers / sites will fail to initialize..

**Comment by pirog** [comment]
See this https://github.com/docker/roadmap/issues/183

**Comment by iKlsR** [comment]
@rolandoscott Yh really messed me up the other day for a demo. Thankfully it wasn't super critical but was scary to almost lose volume data specifically prepared for clients by just restarting your machine. I have to manually say no each time docker asks to update to keep it stuck to a version.

**Comment by pirog** [comment]
Not sure why you would lose volume data unless you explicitly uninstall Docker. The only thing Lando does here is print out a warning if you are on an unsupported version.

**Comment by iKlsR** [comment]
@pirog Docker auto-updated and I couldn't see anything in it and it also reverted some of my settings and switched back to wsl 2 engine so I panicked a bit initially, nothing was working. Also kept getting that weird *the rpc server isn't available error* so I ultimately did have to uninstall everything and downgrade.

**Comment by pirog** [comment]
Probably worth chiming in on https://github.com/docker/roadmap/issues/183 and letting them know then

**Comment by iKlsR** [comment]
They have enough and similar feedback I think. For now I never update unless you do as I do all my work through lando exclusively I will watch that thread and see if they change something down the road. UAC on windows will prevent the auto update, I had actually allowed the updater it to run at startup unknowingly now that I recall.

**Comment by aangelinsf** [comment]
I just added my comment to let them know this was a terrible decision on their part. I pointed out that Localdev requesting a specific version of Docker Desktop until you folks have verified newer ones is a sensible and responsible choice. Forcing people to upgrade their software for something more critical than just a browser (Chrome) or GitHub Desktop is not a sensible and responsible choice.

They seem to be dragging their feet; perhaps the best choice from Localdev's perspective is to verify the more recent version sooner rather than later. After all, even if they update Docker Desktop, it will be a version after 3.5 in which they remove or allow people to turn off the auto-update feature.

**Comment by pirog** [comment]
For localdev specifically you can disable the compatibility check.

**Comment by aangelinsf** [comment]
yep...already on that, thx.

**Comment by AlexanderAllen** [comment]
Just ran into the warning after installing the latest version of Docker Desktop (3.2.x). I installed Docker Desktop before installing Lando. Is there a reason Lando does not support the 3.2.x DD branch?

**Comment by pirog** [comment]
The reason is its not trivial to stay up to date consistently with an upstream dependency while also ensuring that it works as expected.

**Comment by basepack** [comment]
Current status:

> The current schedule for releases is that we will do a 3.2.2 patch release early next week to fix three (relatively rare, but blocking when they occur) regressions present in 3.2 (docker/for-win#10563, docker/for-win#10594 and docker/for-win#10601) . **The next release after that (assuming we don't need another patch release) will be 3.3 and will fix the automated updates: expect that in the first half of April**.
