### ISSUE TITLE
 Command "self-update" is not defined.  Error while trying to update composer.

### ISSUE THREAD

**Issue by gulsah-k** [lando/lando#2792]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
 v3.0.17 on CentOS 7 

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
**.lando.yml**

name: project-name
recipe: drupal8
config:
  webroot: web

**Tell us about the command you were running**
`lando composer self-update`

**Tell us about the error you got**
```
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "self-update" is not defined. 
```

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

**Tell us generally about your bug**
I used command `lando composer self-update 1.10.19` in another lando directory. And I realized that my currently project has also composer 1.10.19v too.
I tried to update composer which version is 1.10.19 but it didn't work with `lando composer self-update` command.
Also I tried:
Delete "composer.lock" and "vendor" folder and then started `lando composer update` command but composer version still same.

**Comment by pirog** [comment]
Probably best to put this on the composer issue queue

**Comment by gulsah-k** [comment]
I checked on composer issues, they suggest to remove it with `sudo apt-get remove composer` and reinstall, I didn't install it manually so I tried rearrange lando.yml file and lando rebuild but it didnt work. Do you suggest any reinstall option?

**Comment by gulsah-k** [comment]
This issue should be on the lando queue because editing lando.yml and rebuilding doesn't work. Composer version staying same after lando rebuild.

**Comment by gulsah-k** [comment]
This is my lando.yml file currently;

```
name: project-name
recipe: drupal8
services:
  myservice:
    type: php
    webroot: web
    composer_version: "2.0.8"
```
and `lando rebuild` but composer version is still 1.10.19  @pirog

**Comment by Developer-Rocha** [comment]
@gulsah-k try to put apache as your server.

name: project-name
recipe: drupal8
config:
  via: apache
services:
  myservice:
    type: php
    webroot: web
    composer_version: "2.0.8"

**Comment by gnuget** [comment]
As far as I remember `self-update` is only available when you use the composer `phar` file and I think that is what Lando uses.

Being said that,  something that happened to me in a recent project is that I had `composer` defined in the composer.json file, so that was making that the initial `composer install` command was changing the version of the composer file that I had defined in the `.lando` file.

Removing composer from my own composer.json file fixed the problem.

**Comment by lsmith77** [comment]
indeed .. it seems like `barryvdh/laravel-ide-helper` has a dependency on `composer/composer` because of https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L324 .. will check with them if maybe this dependency could be removed.

**Comment by lsmith77** [comment]
FYI Jordi responded that he will look into making sure that having a `composer/composer` dep doesn’t disable `self-update` of the PHAR https://twitter.com/seldaek/status/1396153270905851904?s=21
