### ISSUE TITLE
How to configure TiDB in lando in place of mysql as database

### ISSUE THREAD

**Issue by sarath49** [lando/lando#2793]
I want to have TiDB in place of mysql as database, how to implement this as service in lando.
https://pingcap.com/download

**Comment by dustinleblanc** [comment]
Hey @sarath49!

We don't offer this as a service option, so you're going to have to add a custom service using their official docker image: 

https://hub.docker.com/r/pingcap/tidb
https://docs.lando.dev/config/compose.html#compose

Those two docs should point you in the right direction to wire it up with Lando :)

Good Luck!
