### ISSUE TITLE
Windows 10 issue with gulp watcher, it doesn't refresh!!

### ISSUE THREAD

**Issue by MoemenGaber** [lando/lando#2794]
This still seems to be an issue. Using Lando 3.0.24 on Windows 10, gulp watch doesn't seem to do anything (it says it's watching, but it doesn't actually pick up any changes). 
The same settings do work fine with Lando on other mac machine (not mine) , which seems to indicate a Windows issue..
Any hope to fix that one ?

**Comment by Xilonz** [comment]
I've seen similar issues on windows (+ performance was horrible). I've end up installing lando inside WSL2 + the docker WSL2 integration enabled, and make sure the files live inside WSL. ( [why](https://levelup.gitconnected.com/docker-desktop-on-wsl2-the-problem-with-mixing-file-systems-a8b5dcd79b22?gi=d12884ed0c1c))
The way docker has to mount windows folders means that there's no inotify available. This might be only an issue with wsl2 integration enabled on Docker (see link above), i'm not sure.
