### ISSUE TITLE
Switch to PHP 7.4 and using composer with Lando

### ISSUE THREAD

**Issue by Kees-kees** [lando/lando#2800]
Hi,

I have installed the last available Lando version (from this github repository) on Debian. When typing `lando php -v` the outcome is 7.3. I was then wondering how i can run PHP 7.4 when using Lando.

Furthermore, when typing `lando composer install` (or any other composer command)  the outcome is the same as when typing `lando composer` (so nothing more happens than showing the current composer commands). Any help on this would be highly appreciated.

**Comment by miloskroulik** [comment]
Hi,
did you read https://docs.lando.dev/config/php.html#configuration before asking this question? If so, we would need to see the relevant parts of your `.lando.yml` file to be able to help.

**Comment by Kees-kees** [comment]
Hi @miloskroulik 

Thanks for your reaction. I was editing the wrong file at the wrong location.

Another issue i experience is when executing `lando ssh`, which automatically uses `www-data` as webroot user and webroot group. Is there a way to assign different webroot user and webroot group, once typed `lando ssh`? This returns some unauthorized mentions on the frontend when running the app-server.

Any idea, as well, why any `lando composer` command does not execute, and only shows the available lando composer commands?

**Comment by videohead** [comment]
https://docs.lando.dev/php/#configuration is the correct location for the documentation on this issue.
