### ISSUE TITLE
Why does Lando run the platform.sh build and deploy hooks on every `lando start`?

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2804]
[Documentation](https://docs.lando.dev/config/platformsh.html#platform-app-yaml) states that `.platform.app.yaml`'s `build` and `deploy` hooks are executed by Lando.

This seems to be the case, which is fine, although Lando will run these scripts on every `lando start`, even when the project's containers were already created after an initial `lando start`.

In other words, running `lando start`, then `lando stop` and then `lando start` again will run the `build` and `deploy` hooks for both `lando start` commands.

Is there a reason for this?

I think the `build` and `deploy` hooks should maybe be run only on the initial `lando start` during creation of the project.

`build` and `deploy` hooks potentially contain scripts which run for a longer duration which does result in unnecessary long startup times if the project has been set up already.

Thanks!

**Comment by pirog** [comment]
@thasmo they will only run again if the build or deploy hooks return a non-zero status code eg they fail while running.

**Comment by thasmo** [comment]
> only run again if the build or deploy hooks return a non-zero status code eg they fail while running.

Ah, thanks for the quick response. I'm gonna have a look at it again asap. Thanks!

**Comment by thasmo** [comment]
Works. My bad!
