### ISSUE TITLE
How to change default app mount directory from /app to something else

### ISSUE THREAD

**Issue by hrishikesh** [lando/lando#2805]
How to change default app mount directory from `/app` to something else

Ex: I want my application to be mounted inside the container in `/approot` instead of default `/app`

The `/app` is conflicting with `web/app` of bedrock wordpress for a specific plugin

**Comment by jigarius** [comment]
Same question. I want to use Lando for a Drupal module project. So, the code, i.e. `.`, needs to be mounted to `/app/web/modules/custom/`. Is that possible?

**Comment by hrishikesh** [comment]
I Tried overriding the appEnv with 
```
➥ cat .lando/config.yml 
appEnv:
  LANDO_MOUNT: /application

```

I can see the value reflected in container but it is not changing mount dir in real, it is just updating the ENV variable

**Comment by hrishikesh** [comment]
> Same question. I want to use Lando for a Drupal module project. So, the code, i.e. `.`, needs to be mounted to `/app/web/modules/custom/`. Is that possible?

As per the document, it is possible with custom dockerfile but I just  want to change the mound dir dont want any other customisation

**Comment by jigarius** [comment]
@hrishikesh, I decided to solve this with a `docker-compose.yml` for a non-Drupal project.

However, I wanted to stick to Lando for my Drupal project, so I decided to cheat a little. If you're interested, you can take a look at the [context_active_trail](https://git.drupalcode.org/project/context_active_trail/-/tree/8.x-2.x) module's source code. It now includes a Lando file.
