### ISSUE TITLE
Running Lando on a remote server

### ISSUE THREAD

**Issue by sgurlt** [lando/lando#2807]
Hey,

I know that lando is not intended to be used on production and we are not planning to do this!
But we would like to use lando for our automated integration tests for Drupal and therefor it would be perfect if we could have lando running on one of our dev servers having a DNS server pointing to it.

Is there anything specific I have to configure to get this running?
By just pointing the DNS entry to the server and telling lando to listen to an additional url on the appserver I am currently facing a response timeout.

Best regards
Sebastian

**Comment by sgurlt** [comment]
Figured it out, had to adjust the bind address :)

```
~/.lando/config.yml

bindAddress: 0.0.0.0
```

**Comment by dustinleblanc** [comment]
Hey @sgurlt! I would actually change that bindAddress to your server IP and also add `proxyDomain: whateverdomainyouproxywith.com`. 

Also, caveat emptor, ymmv, etc, etc, ;)
