### ISSUE TITLE
Use Composer 2 with Platform.sh config

### ISSUE THREAD

**Issue by pianomansam** [lando/lando#2812]
Platform.sh supports using composer 2 by adding it as a PHP dependency to `.platform.app.yaml`.

https://community.platform.sh/t/how-to-use-composer-2-in-php-applications/684

```
dependencies:
    php:
        composer/composer: '^2.0'
```

This doesn't seem to be detected, currently. Additionally, adding a manual entry for `composer_version` to lando's config doesn't seem to be honored for the platformsh recipe.

**Comment by xaqrox** [comment]
Same here. In my case it looks like the `$PATH` is not configured to prefer the composer installed in the `.platform`:

```sh
web@bfe686c1243a:/app/.platform$ which -a composer
/usr/bin/composer
/app/.platform/local/deps/php/vendor/bin/composer
web@bfe686c1243a:/app/.platform$ /usr/bin/composer --version
Composer version 1.10.6 2020-05-06 10:28:10
web@bfe686c1243a:/app/.platform$ /app/.platform/local/deps/php/vendor/bin/composer --version
Composer 2.0.8 2020-12-03 17:20:38
```

I'm using the Drupal 8 template, and have looked all over for for changes to `$PATH` on my end, but got nothing. I have not tested this on platform.sh itself, so I don't know if it's necessarily a Lando thing or if their documentation is leaving something out.

2 potential solutions, neither of which I have time to dig into right now:
- Can we prevent `/usr/bin/composer` from being created? Then the only composer would be the local one.
- Is there some way to override the `$PATH`?

**Comment by xaqrox** [comment]
Looked into this a bit more, discovered that the composer executable ends up in a different place on a live platform.sh env:

```
web@app.0:~$ which -a composer
/app/.global/vendor/bin/composer
/usr/bin/composer
web@app.0:~$ /app/.global/vendor/bin/composer --version
Cannot create cache directory /app/.global/cache/repo/https---packages.drupal.org-8/, or directory is not writable. Proceeding without cache
Cannot create cache directory /app/.global/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /app/.global/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /app/.global/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Composer 2.0.9 2021-01-27 16:09:27
```

This would seem to strengthen the case for this being a Lando bug.

**Comment by xaqrox** [comment]
Perhaps a change should be made here? Shouldn't the build deps come first so more specific/custom things are preferred over global defaults?

https://github.com/lando/lando/blob/546051ef6915653808db87abfa8c8244f195c97e/integrations/lando-platformsh/types/platformsh-appserver/builder.js#L7-L26

**Comment by pirog** [comment]
holla at dat @xaqrox. i can def replicate this and the pr proposed in #2826 looks like the way to solve it. i'll give it a pass and see where that gets us.
