### ISSUE TITLE
On Mac OS Big Sur 11.1 files are not syncing

### ISSUE THREAD

**Issue by chris-archer-whisky** [lando/lando#2813]
I am using Lando v3.0.23 on Mac OS Big Sur 11.1 and files are not been synced with docker.  I have tried re-installing Lando I have also tried Lando v3.0.24 and I get the same issue.

If I restart lando or rebuild the changes are then synced.

In my lando file I am also using the Platform Recipe.

**Comment by chris-archer-whisky** [comment]
After some investigation it seems to be the platform recipe thats the issue if I use drupal7 it all works fine.  Here is the lando file for Platform

`name: PLATFORMNAME
recipe: platformsh
config:
  id: PLATFORMID
  variables: null
env_file:
  - .env
services:
  chrome:
    type: compose
    app_mount: delegated
    services:
      image: yukinying/chrome-headless-browser:latest
      #command: ["--no-sandbox", "--disable-gpu", "--headless", "--disable-dev-shm-usage", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--user-data-dir=/data"]
      command: google-chrome-stable --no-sandbox --disable-gpu --headless --disable-dev-shm-usage --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --user-data-dir=/data
    labels:
      - traefik.enable=false
    networks:
      private:
tooling:
  # Here are some utilities that should exist in every application
  # container
  node:
    service: PLATFORMNAME
  npm:
    service: PLATFORMNAME
  ruby:
    service: PLATFORMNAME

  # And some utilities we installed in the `build.flavor`
  # or `dependencies` key
  grunt:
    service: PLATFORMNAME
  sass:
    service: PLATFORMNAME
  drush:
    service: PLATFORMNAME
`

Here is the platform yml file

`# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'PLATFORMNAME'

# The runtime the application uses.
type: 'php:7.2'

# Configuration of the build of this application.
build:
    flavor: drupal

# The build-time dependencies of the app.
dependencies:
    php:
        "drush/drush": "^8.0"

# Increase the PHP memnory limites.
variables:
   php:
       memory_limit: 4024M
       opcache.max_accelerated_files: 20000
       opcache.memory_consumption: 512
       opcache.validate_timestamps: Off
# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'db:mysql'
    redis: 'cache:redis'

runtime:
    extensions:
        - redis
        - newrelic

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            # Everything in root should be safely cache for 1d.
            expires: 1d

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true
                '^/loaderio-610e4b361d3351a383120b4040fe038e\.html$':
                    allow: true

        '/sites/default/files':
            # Allow access to all files in the public files directory.
            allow: true
            # Drupal anyways uses itok for generated images. So upon any cache clear
            # images going to be fetched with different itok. There should not
            # issues with stale images, files.
            expires: 2w
            passthru: '/index.php'
            root: 'web/sites/default/files'

            # Do not execute PHP scripts.
            scripts: false

            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/default/files/(css|js)':
                    expires: 2w

# The size of the persistent disk of the application (in MB).
disk: 9216

# The mounts that will be performed when the package is deployed.
mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/keys':
        source: local
        source_path: 'keys'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
        curl -sS https://platform.sh/cli/installer | php
    # We run deploy hook after your application has been deployed and started.
    deploy: |
        set -e
        cd web
        if [ "$PLATFORM_BRANCH" = main ]; then
            # Use Drush to disable the Devel module on the Master environment.
            drush dis devel -y
            # Use Drush to enable the Fastly module on the Master environment.
            drush en fastly -y
        else
            # Use Drush to enable the Devel module on other environments.
            drush en devel -y
            # Sanitize your database and get rid of sensitive information from Master environment.
            drush -y sql-sanitize
        fi
        drush -y cc all
        drush -y updatedb
        drush -y fra

# The configuration of scheduled execution.
crons:
    drupal:
        spec: '*/5 * * * *'
        cmd: 'cd web ; drush elysia-cron run'
    backup:
        spec: '0 5 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = main ]; then
                platform backup:create --yes --no-wait
            fi
            if [ "$PLATFORM_BRANCH" = develop ]; then
                platform backup:create --yes --no-wait
            fi
`

**Comment by chris-archer-whisky** [comment]
Turns out it was Opache causing the issue so overrode it in the lando file.

**Comment by yuseferi** [comment]
Hi @chris-archer-whisky ,
I have the same issue in drupal 9 recipe. files not updated inside the container when I edit them through my IDE.
could you please tell how "Opache" can be overrode? I haven't found anything in doc.

Thanks,

**Comment by chris-archer-whisky** [comment]
Hi,

Your lando file would looks something like this:

name: LANDOSITENAME
recipe: platformsh
config:
  id: PSH_ID
  overrides:
    LANDOSITENAME:
      variables:
        php:
          opcache.validate_timestamps: On

Thanks,
Chris


[cid:WA_logo_bb83c036-3784-4871-858a-5ca0235e919b.png]<https://whiskyauctioneer.com/>

[cid:WineA_logo_a7a310d0-581a-43f0-beef-9cfad98cec57.png]<https://wineauctioneer.com/>

[cid:RA_logo_115bf3b1-d79f-4d23-b588-5cf8aacc2b3b.png]<https://rumauctioneer.com/>



Chris Archer
Senior Drupal Developer
Whisky Auctioneer Ltd


[cid:dash_d24745c6-b6b1-4043-bb24-5fca1abcd7e5.png]

E: ***@***.******@***.***>



Please consider the environment before printing this email - think before you print! Confidentiality Notice: All information in this email and any files attached to it are intended solely for the person to whom it is addressed. If you are not the intended recipient please delete this email from your computer system and on no account copy, distribute, disclose or take any action in reliance on it. Any opinions expressed in this message are those of the author and are not necessarily those of Whisky Auctioneer Limited.


On 23 Aug 2021, at 00:15, Yusef Mohamadi ***@***.******@***.***>> wrote:



Hi @chris-archer-whisky<https://github.com/chris-archer-whisky> ,
I have the same issue in drupal 9 recipe. files not updated inside the container when I edit them through my IDE.
could you please tell how "Opache" can be overrode? I haven't found anything in doc.

Thanks,
