### ISSUE TITLE
Mac connect to host/docker from local network access from other devices

### ISSUE THREAD

**Issue by stillworks** [lando/lando#2816]
Hello,

Lando works fine on my host machine. As far as I found out it is not possible to access Lando eg. the Docker container from another device within my network. I can ping my Mac, but not accessing my lando container at for example http://192.168.22.5:32772 

I guess this is related to the Docker Bridge and the general something how Docker Mac is build. There is no link between Docker and the Macs network.

Setting up another VM with Linux and make everything work through the VM and it's network interface is way to complicated.

Is there another simple way to maybe expose .lndo.site to the network?

Big Sur 11.1
Lando 3.0.23

**Comment by globalmatt** [comment]
I would also love to know how to do this. Can't find a simple solution.
