### ISSUE TITLE
Unable to resolve any local domains, proxy fails to start

### ISSUE THREAD

**Issue by OnGitHubSchatz** [lando/lando#2825]
**Tell us about your setup**

**lando** v.3.0.23
**docker** 19.03.14_ce-lp152.4.1
on OpenSUSE Leap 15.2

**Tell us about your `.lando.yml`**

```yml
name: demo-local-d7
recipe: drupal7
config:
  webroot: web
  php: '7.2'
  via: apache:2.4
  database: mariadb
  xdebug: true

services:
  appserver:
    type: php
    build_as_root:
      - pear install File_MARC-stable
      - pear install Validate_ISPN-alpha
 
  proxy:
    appserver:
      - demo.local
```

**~/.lando/config.yml**

```yaml
domain: local
```
Set this after lndo.site domains were not working. I have entry in my **/etc/hosts** for it: ``127.0.0.1 demo.local``

**Tell us about the error you got**

After ``lando start``
- Appserver URLs with the custom domain are red and do not resolve
- localhost:port links resolve fine

**Tell us generally about your bug**

I notice that the traefik proxy container does not remain up (exits) after starting the app, which does not seem normal. When I show logs for it, it seems to be failing to install dependencies and fetch from remotes.

``docker logs landoproxyhyperion5000gandalfedition_proxy_1``

```bash ===============================================================

addcert 00:25:08.INFO  ==> Installing openssl...
/scripts/000-add-cert: line 70: apt-get: not found
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
run-parts: /scripts/000-add-cert: exit status 1
  openssl (missing):
    required by: world[openssl]
proxycerts 00:25:18.INFO  ==> We have proxy certs!
proxycerts 00:25:18.INFO  ==> Dumped config to /proxy_config/proxy.yaml
proxycerts 00:25:18.DEBUG ==> tls: certificates: - certFile: "/lando/certs/proxy._lando_.crt" keyFile: "/lando/certs/proxy._lando_.key"
addcert 00:25:18.INFO  ==> Installing openssl...
/helpers/add-cert.sh: line 70: apt-get: not found
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  openssl (missing):
    required by: world[openssl]
run-parts: /scripts/999-refresh-certs: exit status 1
```
I have tried removing this network and recreating, many cycles of lando poweroff and rebuild, and finally wiping out docker to reinstall from scratch.

**Comment by maxdev** [comment]
I have the same issue. More over I have these errors while running `lando rebuild` or `land start`.
```
lando rebuild
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
Killing drupal8_database_1  ... done
Killing drupal8_appserver_1 ... done
Going to remove drupal8_database_1, drupal8_appserver_1
Removing drupal8_database_1  ... done
Removing drupal8_appserver_1 ... done
Pulling database  ... done
Pulling appserver ... done
appserver uses an image, skipping
database uses an image, skipping
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Removing orphan container "drupal8_appserver_nginx_1"
Creating drupal8_appserver_1 ... done
PHP Warning:  copy(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in Command line code on line 1

Warning: copy(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in Command line code on line 1
PHP Warning:  copy(https://getcomposer.org/installer): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in Command line code on line 1
Could not open input file: /tmp/composer-setup.php
ERROR ==> Could not open input file: /tmp/composer-setup.php
Creating drupal8_database_1 ... done
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please standby...

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)
                             /___/

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ One of your build steps failed
   This **MAY** prevent your app from working.
   Check for errors above, fix them in your Landofile, and try again by running:
   lando rebuild
```

**Comment by benperiton** [comment]
I had a similar issue, it turned out to be a local DNS problem for me
I think I ended up changing the symlink for /etc/resolv.conf so that systemd didn't control it 

https://github.com/lando/lando/issues/2754

**Comment by maxdev** [comment]
Update. I use WSL2 + Docker inside Linux. This solution seems fixed my issue https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6 (but it's strange why it worked without fix before?)

**Comment by OnGitHubSchatz** [comment]
Thanks for the replies. These did not apply to my environment but there is a common thread. There multiple ways DNS within container can go awry.

The proxy happened to be functioning for me after a reboot when even total reset of docker network and containers did not. I think a total reinstall of Lando would be in order next time, networking-related state is retained with it.

I checked kernel parameters after reading some docker setup documentation and found that I needed `net.ipv4.ip_forward = 1` set in sysctl, which is not enabled by default for distributions that use systemd.

Have not had a proxy container issue since enabling across reboots.

**Comment by lems3** [comment]
> Update. I use WSL2 + Docker inside Linux. This solution seems fixed my issue https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6 (but it's strange why it worked without fix before?)

The issue with that solution is that xdebug stops working for us. That's not really an option in our case... so we're still stuck with a broken anvironment from time to time...

**Comment by reynoldsalec** [comment]
Note: typically these problems are indicative of a DNS issue that is related to the user's setup. Recommend checking some of the suggestions in this thread and visiting the [Lando Slack](https://launchpass.com/devwithlando) for help if all else fails.

**Comment by treedbk** [comment]
My work network changed their firewall settings and caused this problem with all my Lando apps. Fortunately, following the instructions at the bottom of this article fixed the problem for me: https://docs.lando.dev/core/v3/proxy.html

On my mac I navigated to /etc/hosts, opened the file and added the app URLs as described in the above article:

`# Lando apps`
`127.0.0.1 <yourappname>.lndo.site`
`127.0.0.1 <servicename>.lndo.site`

That's it. I didn't need to change anything else. The only downside is needing to do this for each app and service that I want to run, such as solar or phpmyadmin URLs.
