### ISSUE TITLE
Lagoon: Lando fails to start when a non-lagoon service is added to docker-compose.yml

### ISSUE THREAD

**Issue by jonpugh** [lando/lando#2828]
I am testing lando with the lagoon containers, plus an extra API example container for the special site I am building.

Normally with Lagoon and a Drupal site, you can add to the `docker-compose` services by adding to `docker-compose.yml`, and using the Lagoon-recommended method for local development, `docker-compose up` works just fine. 

I tried this using Lando instead, and got a big warning and it didn't start my containers because the services were considered "unsupported".

**UPDATE:** I found the lando `compose` service type, which fills the use case. This is still an example of a slight incompatibility between lando and lagoon. https://docs.lando.dev/config/compose.html#configuration

## Steps to reproduce

1. Clone the example project: 

        https://github.com/amazeeio/drupal-example-simple/blob/9.x/docker-compose.yml

2. Add the following service to `docker-compose.yml`:
          
        hello-world:
          image: hello-world
          labels:
            lagoon.type: none

3. `lando start`: Most things will work until the end:

        Creating drupal9examplesimple_nginx_1     ... done
        Starting drupal9examplesimple_php_1       ... done
        Scanning to determine which services are ready... Please standby...
        
          _      __              _           __
         | | /| / /__ ________  (_)__  ___ _/ /
         | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
         |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                                     /___/     
        
        Your app started up but we detected some things you may wish to investigate.
        These only may be a problem.
        
        
         ■ Detected some unsupported Lagoon services
           Lando has detected some services in your Lagoon config are not yet supported.
           This may result in reduced functionality for your app.
           The unsupported services are: hello-world
           See below for more details:
           https://docs.lando.dev/config/lagoon.html#customizing-the-stack

## Solution

I spoke with @Schnitzel and he pointed me at the docs which say that a container with the label `lagoon.type=none` will be ignored by Lagoon: https://docs.lagoon.sh/lagoon/using-lagoon-the-basics/docker-compose-yml#skip-ignore-containers

I found the section where it validates the services. If you check for the label `lagoon.type` == `none` you can safely ignore that service: https://github.com/lando/lando/blob/master/integrations/lando-lagoon/app.js#L80-L100

Additionally, you might have to validate against that label instead of just the service name to ensure full compatibility with Lagoon?

I am not sure yet if a container with no `lagoon.type` label is ignored by lagoon as well, but whatever it is, the validation logic in `lando` should match `lagoon`.

**Comment by pirog** [comment]
@jonpugh ahh interesting. Honestly was not aware of `lagoon.type=none` but definitely should support that. Thanks for posting!
