### ISSUE TITLE
Non-existent commands produce inconsistent exit statuses

### ISSUE THREAD

**Issue by tebb** [lando/lando#2832]
As a devops, when scripting using the lando command, I'd expect predictable return codes.

lando wibble; alert   # Notification -> Success
lando blah; alert      # Notification -> Failure

Using the commands literally, just cut and paste.  I don't have wibble or blah files, directories, commands or aliases, nor tooling in .lando.* files.  Easter egg?

There was a 'serious' side to this.  I was testing display of alerts on 'lando phpunit' test pass/fail.

Only really reporting this in case it's a pointer towards another bug that's difficult to trace or there's a prize.

**Comment by pirog** [comment]
@tebb i am not able to replicate this at least as far as i understand it but maybe im doing something wrong. Can you provide the tooling section in your landofile? 

FWIW i dont know of anything that would cause this to happen. Lando just passes the command along to the container and then gets the error code back so 🤷

**Comment by xaqrox** [comment]
I *can* reproduce this on v3.0.25, very strange. To clarify the OP, `wibble` and `blah` are "commands" that don't exist. One would expect both to exit with non-zero status, but `wibble` does not (i.e. exits with `0`, "successfully"), while `blah` does. I got the same results in a running app, and in my (app-free) home directory. Behold:
```sh
~> lando wibble;echo $?
0
~> lando blah;echo $?
Usage: lando <command> [args] [options]

Commands:
  lando config    Displays the lando configuration
  lando destroy   Destroys your app
  lando info      Prints info about your app
  lando init      Initializes code for use with lando
  lando list      Lists all running lando apps and containers
  lando logs      Displays logs for your app
  lando poweroff  Spins down all lando related containers
  lando rebuild   Rebuilds your app from scratch, preserving data
  lando restart   Restarts your app
  lando share     Shares your local site publicly
  lando ssh       Drops into a shell on a service, runs commands
  lando start     Starts your app
  lando stop      Stops your app
  lando version   Displays the lando version

Options:
  --channel       Sets the update channel                                                [array] [choices: "edge", "none", "stable"]
  --clear         Clears the lando tasks cache                                                                             [boolean]
  --experimental  Activates experimental features                                                                          [boolean]
  --help          Shows lando or delegated command help if applicable                                                      [boolean]
  --verbose, -v   Runs with extra verbosity                                                                                  [count]

Examples:
  lando start            Run lando start
  lando rebuild --help   Get help about using the lando rebuild command
  lando destroy -y -vvv  Run lando destroy non-interactively and with maximum verbosity
  lando --clear          Clear the lando tasks cache

Did you mean ssh?
1
~>

**Comment by xaqrox** [comment]
One more experiment (this output is not exactly copy-pasted, but is true to my results):

```sh
~> lando a
1 # did you mean ssh?
~> lando aa
1 # did you mean ssh?
~> lando aaa
1 # did you mean ssh?
~> lando aaaa
0
~> lando aaaaa
0
```

So commands with no match 4 or characters long fail silently? Weird. But not quite:

```sh
~> lando dengar
0
~> lando bossk
1 # did you mean logs?
~> lando han
1 # did you mean share?
~> lando vader
0
```

Hope this data helps...?

**Comment by tebb** [comment]
Thanks @xaqrox.  Yes, exacltly.  Nicely put.

Yes.  Helps me.  Reassures me I haven't totally lost the (Star Wars) plot.

**Comment by xaqrox** [comment]
Np. You may want to update the issue title to something boring such as  "Non-existent commands produce inconsistent exit statuses"...

**Comment by dalin-** [comment]
Still a problem.  Ran into this today where an engineer told me "I ran `lando custom-command` and there was no output.  It took a while to figure out it was because they were on the wrong branch.

**Comment by AaronFeledy** [comment]
It appears to be an issue with the implementation of the "Did you mean ____?" feature of the yargs package where it suggests a command based on how closely it relates to what you entered. Currently, it properly throws a code when activated by a command that is close enough to something to trigger a suggestion. It fails if you're too far from anything to get a suggestion.. Lando just exits cleanly without doing anything at all.

```bash
$ lando ass
Did you mean ssh?
$ lando booty

$
```

That said, this is unlikely to be fixed until Lando 4 because v4 is doing away with the yargs framework, which will make this a non-issue.

**Comment by pirog** [comment]
@AaronFeledy oh thats interesting. 

we will probably run a "hybrid cli" model of OCLIF/YARGS as we prototype `@lando/cli-next` alongside `@lando/core-next` so this probably wont be "naturally fixed" until we move that prototype eg https://github.com/lando/cli/blob/main/lib/cli-next.js into its own `@lando/cli-next` repo. 

That said event the prototype will still technically be cli version 4 so we have good cover to introduce breaking changes.
