### ISSUE TITLE
Default xdebug configuration mixes version 2 and 3 resulting in error

### ISSUE THREAD

**Issue by jorissteyn** [lando/lando#2845]
I'm using lando 3.0.24 on Arch. Trying to define a simple service with PHP8/Xdebug3:

```yml
services:
  web:
    type: php:8.0
    xdebug: true
```

This setup will show an error on every request because Xdebug 3 emits errors when it encounters Xdebug 2 configuration options.:

```
Xdebug: [Config] The setting 'xdebug.remote_autostart' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
```

This is cause by `xxx-lando-default.ini` mixing v2 and v3 options. This works for v2, but is problematic for v3.

Using `xdebug: false` and installing xdebug myself doesn't help, the xdebug config is still written. Overwriting the value is also not an option because you can't unset an INI value once it's set. I don't see any other workaround.

I believe Lando should use an `xdebug.ini` file and only write the options applicable for that the configured version.

**Comment by pirog** [comment]
Until we make some foundational changes in how our images work we have to ship a config file that can be used in both versions. Also, to be clear, these are just notices and not errors eg they should not actually prevent xdebug3 from working.

**Comment by pascal-splotches** [comment]
Perhaps an idea to ship without an `xdebug.remote_autostart`? That way people won't continuously get a very distracting notice whenever they run lando commands, and people who need it, can still enable it.

I think ignoring it because it's just a notice would set bad precedent and is bad practice. We shouldn't want to condition people to ignore warnings.

**Comment by jorissteyn** [comment]
We've set error_reporting to exclude E_DEPRECATED errors, and xdebug is now silent. That resolves the immediate problem for us. I didn't expect that to help since the message is not a true error with E_DEPRECATED severity, but xdebug outputs it only when the error level allows derecation warnings.

Thanks for your help @pirog
