### ISSUE TITLE
XDebug with Lando in WSL2 doesn't work

### ISSUE THREAD

**Issue by mrtronje** [lando/lando#2858]
I could not figure out how to setup xdebug 3 with lando in wsl2 and phpstorm. Docker is running inside of the wsl2 so no docker-desktop is installen on windows. 

*Lando Setup*
Lando Recipe: lemp
Lando Version: v3.0.24

xdebug settings
```
; Xdebug
xdebug.max_nesting_level = 512
xdebug.remote_autostart = 1
xdebug.start_with_request = trigger
xdebug.mode = debug
```

*PHPStorm Setup*
In PHPstorm I did the following configuration
![php](https://user-images.githubusercontent.com/15194959/107779965-608e2a00-6d46-11eb-9bb5-28fd7b963cd2.PNG)

Then i set a breakpoint and started the listen mode:
![image](https://user-images.githubusercontent.com/15194959/107773467-fa9da480-6d3d-11eb-8afa-2885ced41859.png)

In the Browser I use the xdebug plugin. 

But nothing happens.

*XDebug* 
If I output  `xdebug_info();die;` in the browser, I'll see the following errors
![image](https://user-images.githubusercontent.com/15194959/107772745-edcc8100-6d3c-11eb-806c-c470051e2321.png)

Any help is appreciated 😄

**Comment by marklabrecque** [comment]
The Xdebug configuration you are using is for XDebug 2.x.

Try adding following:
xdebug.start_with_request = yes

You shouldn't need the browser plugin with this configuration. You can also replace "yes" with "trigger" to use the browser plugin, but I've found this to be a bit tricky to get working with VSCode or PHPStorm.

Also in XDebug the default port has changed to 9003, so make sure you listening on the proper port.

**Comment by marklabrecque** [comment]
You can also take a look at the updated docs for XDebug 3 [here](https://docs.lando.dev/guides/lando-with-vscode.html#getting-started)

**Comment by mrtronje** [comment]
> The Xdebug configuration you are using is for XDebug 2.x.
> 
> Try adding following:
> xdebug.start_with_request = yes
> 
> You shouldn't need the browser plugin with this configuration. You can also replace "yes" with "trigger" to use the browser plugin, but I've found this to be a bit tricky to get working with VSCode or PHPStorm.
> 
> Also in XDebug the default port has changed to 9003, so make sure you listening on the proper port.

Thank you for your answer.  But as you can see in the initial post I've already set this setting (to `trigger`, but i tried to change it to `yes` - but it doesn't work neither.

**Comment by marklabrecque** [comment]
What port are you listening on?

**Comment by mrtronje** [comment]
9003

**Comment by Xilonz** [comment]
I didn't know you could run Docker within WSL2, I don't think this is supported by Docker. WSL2 has many network-related issues, I'd suggest to install on Windows and enable wsl2 support. This way you docker containers can do networking correctly without WSL2 interference.

If that's not an option;
Doest PHPStorm, like VS Code run inside WSL2? If not, make sure that you can listen to xDebug within WSL2, so you can make sure that your configuration is set up correctly. Note that the internal IP of WSL might not be detected correctly by Lando. If the configuration within WSL2 is working correctly the next step is to fix the WSL2 network issues, which can be one of many.

**Comment by mrtronje** [comment]
@Xilonz  

> I didn't know you could run Docker within WSL2, I don't think this is supported by Docker

Lando suggests to use docker inside of wsl instead of in the windows host:
https://docs.lando.dev/guides/setup-lando-on-windows-with-wsl-2.html#prerequisites

So I've to go this way.  I tried to run PHPStorm inside of WSL but thats quite buggy at the moment (phpstorm hangs, freezes, ...). I think it's a more networkling related issuem, like xdebug can't find or connect to the host where phpstorm is running.

**Comment by vaggelis-net** [comment]
No need to run anything under wsl2. Docker for windows is already accessible from inside the Linux subsystem.

So about XDebug you could try to set a PHP CLI Interpreter under PHPStorm options using the PHP image e.g. `devwithlando/php:7.4-apache-2`

**Comment by lems3** [comment]
Have you done the "fix" where you set your resolv.conf file yourself instead of letting WSL set it for you ?

That fix which solve the DNS resolution issue for Lando breaks Xdebug for us. Our current solution is to take the less problematic issue and live with it...
