### ISSUE TITLE
Acquia test applications required to test

### ISSUE THREAD

**Issue by mikemilano** [lando/lando#2863]
We would like to be able to test the following features but require access to existing apps, or the ability to re-create apps with these features. Apps configured by Acquia staff would be preferred to assure they represent common setups.

- [ ] Multi-site
- [ ] Memcached
- [ ] Solr

**Comment by rubenvarela** [comment]
I'm available with sites running on Acquia using memcache, solr, multisite and multiple domains on Acquia. 

Let me know if I can help.
