### ISSUE TITLE
Slack: https://launchpass.com/devwithlando doesn't send email (not in spam)

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#2864]
Having trouble getting an email from https://launchpass.com/devwithlando. Can anyone confirm this still works to get access to Slack?

**Comment by pirog** [comment]
@ElijahLynn i received these more or less instantaneously:
<img width="1579" alt="Screen Shot 2021-02-17 at 3 33 01 PM" src="https://user-images.githubusercontent.com/713424/108264434-872cd600-7135-11eb-8be4-ad75924f28f1.png">
<img width="827" alt="Screen Shot 2021-02-17 at 3 33 11 PM" src="https://user-images.githubusercontent.com/713424/108264456-8c8a2080-7135-11eb-962d-fe3033b4e553.png">

**Comment by ElijahLynn** [comment]
Thank you @pirog, I haven't had issues with my email but something must be going on with it. Checked spam and everything, will triple check again, thanks for confirming!

**Comment by ElijahLynn** [comment]
The odd thing is that after I submit the form, I get no indication it was sent, just a page refresh. Wonder if it is Brave....

**Comment by ElijahLynn** [comment]
Yup, Brave was blocking this pop up:

![image](https://user-images.githubusercontent.com/1504756/108272972-d23fec80-7127-11eb-954a-cf23be20790a.png)

**Comment by ElijahLynn** [comment]
So I guess I'll reset the pass via Slack and that should work.

**Comment by Preen** [comment]
My problem was that I had Ad Blocker activated, once I disabled that it worked.
