### ISSUE TITLE
Add instructions/suggestions for how to send a single, one-time donation/purchase

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#2868]
I see now, that OpenCollective allows for one-time donations. Might be good to highlight that option with instructions for that type of audience > https://opencollective.com/lando

_Originally posted by @ElijahLynn in https://github.com/lando/lando/pull/2862#issuecomment-780887914_

**Comment by reynoldsalec** [comment]
Included this, thanks for that insight @ElijahLynn!
