### ISSUE TITLE
Update the PHP 8 docker images?

### ISSUE THREAD

**Issue by iluuu1994** [lando/lando#2871]
The PHP 8 docker images still contain PHP 8.0.0. PHP 8.0.2 is out and some packages (e.g. php-cs-fixer) don't run with PHP 8.0.0. Would be great if the images could be updated automatically when a new PHP patch is out :slightly_smiling_face: 

https://hub.docker.com/r/devwithlando/php/tags?page=1&name=8.0&ordering=last_updated

Thanks!

**Comment by pirog** [comment]
hmmm, it actually should work that way already. let me investigate.

**Comment by pirog** [comment]
Ok, image rebuilds were stuck for some reason. Manually unstuck them so should be able to `lando rebuild` as soon as they are rebuilt and get `8.0.2`. Going to close this but def reopen and call me a liar if you can't rebuild onto `8.0.2` sometime later  today.,

**Comment by iluuu1994** [comment]
Great, thank you!
