### ISSUE TITLE
Unable to start lando with elastic service in ubuntu

### ISSUE THREAD

**Issue by mktomanikandan** [lando/lando#2877]
**The following error I am getting in logs after ran lando start.**

**lando.yml**

name: xxxx
recipe: drupal8
config:
  webroot: .
proxy:
  appserver:
    - xxxx.lndo.site
    - xxxxx.lndo.site
    - xxxx.lndo.site
    - xxxxx.lndo.site

services:
  elsservice:
    type: elasticsearch

**Logs**

elsservice_1  | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/install-composer.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/lagoon-auth.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/lagoon-generate-key.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/lagoon-pull.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/lagoon-push.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/log.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/proxy-certs.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-boot.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-build.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-clone.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-exec.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-fake-rpc.py': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-open.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-pull.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-push.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/psh-recreate-users.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
elsservice_1  | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
elsservice_1  | userperms 03:59:47.93 WARN  ==> Only the root user can reset permissions! This is probably ok though...
elsservice_1  | loadkeys 03:59:47.96 WARN  ==> Only the root user can load ssh keys! This is probably ok though...
elsservice_1  | lando 03:59:47.96 INFO  ==> Lando handing off to: /launch.sh
elsservice_1  | lando 03:59:47.96 DEBUG ==> Running command with exec...
elsservice_1  |  03:59:48.02 
elsservice_1  |  03:59:48.02 Welcome to the Bitnami elasticsearch container
elsservice_1  |  03:59:48.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elsservice_1  |  03:59:48.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elsservice_1  |  03:59:48.03 Send us your feedback at containers@bitnami.com
elsservice_1  |  03:59:48.03 
elsservice_1  |  03:59:48.03 INFO  ==> ** Starting Elasticsearch setup **
elsservice_1  |  03:59:48.06 DEBUG ==> Validating Kernel settings...
elsservice_1  |  03:59:48.13 ERROR ==> Invalid kernel settings. Elasticsearch requires at least: vm.max_map_count = 262144

**Lando Info**

{ service: 'elsservice',
    urls: [],
    type: 'elasticsearch',
    healthy: true,
    environment:
     { ELASTICSEARCH_IS_DEDICATED_NODE: 'no',
       ELASTICSEARCH_CLUSTER_NAME: 'bespin',
       ELASTICSEARCH_NODE_NAME: 'lando',
       ELASTICSEARCH_PORT_NUMBER: 9200,
       ELASTICSEARCH_PLUGINS: '',
       ELASTICSEARCH_HEAP_SIZE: '1025m',
       LANDO_NEEDS_EXEC: 'DOEEET' },
    internal_connection: { host: 'elsservice', port: '9200' },
    external_connection: { host: '127.0.0.1', port: 'not forwarded' },
    healthcheck: 'curl -XGET localhost:9200',
    config: {},
    version: '6',
    meUser: 'www-data',
    hasCerts: false,
    hostnames: [ 'elsservice.sharaf.internal' ] } ]

**Trying to connect elastic server**

 lando ssh -c 'curl -XGET localhost:9200'
curl: (7) Failed to connect to localhost port 9200: Connection refused

**Comment by rabauss** [comment]
The value of  `vm.max_map_count` is too low - to increase it permanently, you have to run as root user:
````
echo "vm.max_map_count=262144" >> /etc/sysctl.d/elasticsearchSpecifications.conf && sysctl --system
````

**Comment by pirog** [comment]
Thanks for the assist here @rabauss. For reference here is the documentation around this consideration:
https://docs.lando.dev/config/elasticsearch.html#other-requirements
