### ISSUE TITLE
Landoize Lando docs

### ISSUE THREAD

**Issue by pirog** [lando/lando#288]
@serundeputy @reynoldsalec i updated our Horoscope docs to use lando for local dev, added in some nice markdown standards and got a `travis.yml` rolling. 

we should replicate that awesomeness over here! would love to see lando using lando to test itself.

**Comment by uberhacker** [comment]
This is sounding as scary as requiring Docker to compile Docker. :)

**Comment by pirog** [comment]
@uberhacker lol! 

when i was talking to @serundeputy about doing this i actually BROUGHT UP THAT EXACT EXAMPLE

**Comment by serundeputy** [comment]
This is done! closing. reopen if necessary.

**Comment by pirog** [comment]
@serundeputy sounds good!
