### ISSUE TITLE
Taefik TCP Proxy with TLS/SNI

### ISSUE THREAD

**Issue by iluuu1994** [lando/lando#2889]
**The more steps you complete the more likely we are to address your issue!**

Lando allows configuring `portforward` to a fixed port, but this is not recommended as this could lead to port collisions. Unfortunately, this means that you'll have to constantly reconfigure ports in database tools and other applications that you might run outside of the Docker environment.

**Please explain your request and its importance in the form of a user story.**

As a lando user who works with databases in most applications I want to configure my database in my database management tool once without adjusting the port on every restart of lando.

**Please provide some detail on how lando can help solve this problem**

Lando already solves this problem for HTTP services like Mailhog, allowing to configure additional URLs with `proxy`. Unfortunately, with non-http services this is currently not possible. This probably has to do with the fact that the domain name is transmitted as part of the http layer. [Traefik](https://doc.traefik.io/traefik/routing/routers/#options_1) does seem to allow this when SNI is enabled. Not really being a network guy, I'm not sure if this is viable. Let me know if it's not.

**Describe the solution you'd like**

Optimally, `proxy` would also accept non-http services so that they could be configured like this:

```yaml
proxy:
    database:
        - db_myapp.lndo.site:5432
```

**Comment by pirog** [comment]
@iluuu1994 this is what `portforward` is for. We don't recommend it because it requires users self-manage ports themselves and possibly across many teams which is inherently brittle because humans remembering things.

**Comment by iluuu1994** [comment]
@pirog Yeah, I'm aware this is technically already possible but only through manual port handling. But as you say, managing ports is hard, especially since we're gonna have to find ports that are available across all of our dev machines as we're sharing the same lando config. I'm not sure if my suggestion to use Traefiks TCP proxy is technically feasible (as it will only work with TLS and SNI) but this way we could create a simple naming scheme for our team (db_ + application name is the DB service exposed locally). That would be much easier to manage as we won't have to think about which ports are commonly free and which aren't.

I already created a suggestions a couple of months ago (#2734), maybe that's worth reconsidering? The suggestion basically is: Make lando memorize ports which have been automatically assigned. When starting up next time, try to use the same port and only use a different port if the given port is not available. That doesn't sound any more prone to errors than the current solution.

Thanks for your consideration. Feel free to close this issue if you're not interested in pursuing this.

**Comment by pirog** [comment]
Not sure if traefik can do that. It couldnt last time we checked. If it can/could that would be a good solution to this and a good feature generally. We would definitely put that on the list of shit to do.

As for memorizing... I don't think there is ever going to be a world where Lando is memorizing ports in that way. This is a very non-trivial thing to do reliably, would be at best swimming against the current Docker implementation and at worst reinventing most of it. My intuition tells me more Lando users would be better served if our team spent its time on other things.

The suggestion https://github.com/lando/lando/issues/2734#issuecomment-740045455 is a pretty good one if you are worried about team standardization. Still relies on individual devs to keep track of their own stuff but one is easier to management than many.

Let's keep it open for now, if all of a sudden a large percentage of users are REALLY wanting this we can revisit.
