### ISSUE TITLE
Login to platform CLI not working

### ISSUE THREAD

**Issue by MSBuV** [lando/lando#2895]
**Tell us about your setup**

v3.0.26 on Windows 10, same issue with v3.0.25
site was created with v3.0.25 but rebuilt with v3.0.26

**Tell us about your `.lando.yml`**
```bash
# Change this name to something that makes sense for your project
name: newsite

# Excludes rarely edited folder / files to win performance.
excludes:
  - drush
  - scripts
  - vendor
  - web/core
  - web/modules/contrib
  - web/profiles/contrib
  - web/sites/default/files
  - web/themes/contrib

# Use the recipe appropriate for your application.
recipe: platformsh

# Configure the D8 recipe to match up closer to a vanilla platform.sh stack
config:
  # Use the recipe appropriate for your application.
  id: REPLACE-ME

  # Allows for XDebug locally.
  variables:
    app:
      php:
        xdebug.remote_connect_back: 1

# The following additional build step will install the Platform CLI
# in the application container and auto-run `composer install`
services:
  app:
    overrides:
      environment:
        BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  drush:
    service: app
    cmd: /app/vendor/bin/drush --root=/app/web
  phplint:
    service: app
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: app
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: app
    cmd: /app/vendor/bin/phpunit
  phpstan:
    service: app
    cmd: /app/vendor/bin/phpstan
  behat:
    service: app
    cmd: /app/vendor/bin/behat
  test:
    service: app
    description: Run Tests Locally
    cmd:
      - appserver: composer lint
      - appserver: /app/vendor/bin/phpunit -c web/core --testsuite=unit --exclude-group Composer web/modules/custom
      - appserver: /app/vendor/bin/phpunit -c web/core --testsuite unit --exclude-group Composer web/themes/custom
      - appserver: /app/vendor/bin/phpstan analyse web/modules/custom web/themes/custom
```

**Tell us about the command you were running**

lando platform
lando platform auth:info

**Tell us about the error you got**

```bash
: not foundh-exec.sh: 6: /app/.environment:
/helpers/psh-exec.sh: 12: /app/.environment: Syntax error: end of file unexpected (expecting "then")
```

**Tell us generally about your bug**

I was following the instructions at https://github.com/thinktandem/template-drupal8 to link a local site with platform.sh. Everything worked up to step 3 and logging into platform.sh.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. Cloned repository from https://github.com/thinktandem/template-drupal8
2. Ran "lando start" to start up the drupal app
3. Ran "lando platform"
```

**Comment by pirog** [comment]
@MSBuV what are the contents of `/app/.environment'?

**Comment by pirog** [comment]
@labboy0276 this is coming from our own `template-drupal8` any ideas?

**Comment by pirog** [comment]
FWIW i was not able to replicate using 

```
1. Cloned repository from https://github.com/thinktandem/template-drupal8
2. Ran "lando start" to start up the drupal app
3. Ran "lando platform"
```

On an M1 MacBook Pro

**Comment by MSBuV** [comment]
> 
> 
> @pirog @MSBuV I can not replicate either.
> 
> ```
> 1. Cloned repository from https://github.com/thinktandem/template-drupal8
> 2. Ran "lando rebuild"
> 3. Ran "lando platform" && "lando platform auth:info"
> ```
> 
> On PoPOS 20.04

If I run
```
1. git clone https://github.com/thinktandem/template-drupal8.git test
2. lando start
3. lando platform
```
I get the exact same error every time with a new site.

**Comment by pirog** [comment]
@MSBuV we cannot replicate so not sure what to tell you without knowing more about what makes your setup different.

**Comment by Orace** [comment]
> What can I do to fix that?

Open `/app/. environment` with NotePad++, configure NotePad++ to display all characters. Check if lines end by [CR][LF] or just [LF], on windows it should be [CR][LF]. If it's not the case, you should configure your git to apply [CR][LF] at checkout. See [this](https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf) for more I formatios.

**Comment by MSBuV** [comment]
> 
> 
> > What can I do to fix that?
> 
> Open `/app/.environment` with NotePad++, configure NotePad++ to display all characters. Check if lines end by [CR][LF] or just [LF], on windows it should be [CR][LF]. If it's not the case, you should configure your git to apply [CR][LF] at checkout. See [this](https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf) for more information.

All lines end with [CR][LF].

**Comment by pirog** [comment]
I think the point is that you actually want `[LF]` since on Lando all of these things are running inside a Linux environment.

**Comment by MSBuV** [comment]
> 
> 
> I think the point is that you actually want `[LF]` since on Lando all of these things are running inside a Linux environment.

That point was not apparent from the original post.
Switching [CR][LF] to [LF] seems to work though. Error message is gone and I get:
```bash
Welcome to Platform.sh!

Project ID: REPLACE-ME
Environment ID: master
Application name: app

Local environment commands:

  To view routes, run: platform routes
  To view variables, run: platform decode $PLATFORM_VARIABLES

To view all commands, run: platform list
```
I'll have to check it out later for more testing. Thanks everyone for the help.
