### ISSUE TITLE
Is someone Working on an MERN Receipe

### ISSUE THREAD

**Issue by tkamsker** [lando/lando#2898]
Hi i found Lando and lagoon verry useful but we do MERN so if we are lucky someone has started already MERN . We would help testing .. We do have an extreme docker compose setup which would be neat for this test. On top we also have an Graphql Service which might attract all the Next js and Gatsby people. And if nobody started if someone shows us where to start we could even use marn als basis and do an mern recipe right ? so any hint would help  thx thomas

**Comment by Oleksii909** [comment]
I am trying to follow **Node Recipes or Services** but it is not linked. How can I find the recipes?

**Comment by Oleksii909** [comment]
Ah sorry, I understand **Node Recipes or Services** it is columns with cards.
