### ISSUE TITLE
Clean install on Ubuntu 20.10 fails with `internalModuleStat` error

### ISSUE THREAD

**Issue by nullvariable** [lando/lando#2903]
**Tell us about your setup**
![image](https://user-images.githubusercontent.com/171515/110811713-ea051f00-8254-11eb-96c1-f31e77deacfa.png)

Latest release found here:
```
wget https://files.devwithlando.io/lando-stable.deb
sudo dpkg -i lando-stable.deb
```

**Tell us about the command you were running**

```bash
lando
```

**Tell us about the error you got**

```bash
$ lando
internal/modules/cjs/loader.js:46
const internalModuleStat = function (f) { return require('fs').internalModuleStat(f); };
                                                                                            ^

TypeError: require(...).internalModuleStat is not a function
    at internalModuleStat (internal/modules/cjs/loader.js:46:64)
    at stat (internal/modules/cjs/loader.js:119:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:14)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1145:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:448:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:67:3)
    at internal/bootstrap/pkg.js:7:1
```

**Tell us generally about your bug**

I installed Lando following directions in the docs, rebooted the system, and tried to start a lando project.

```bash
wget https://files.devwithlando.io/lando-stable.deb
sudo dpkg -i lando-stable.deb
# discover docker is not yet installed
curl https://get.docker.com | bash
# remove lando to fix dependency issue
sudo apt --fix-broken install
# actually install docker
curl https://get.docker.com | bash
sudo usermod -aG docker <user>
sudo dpkg -i lando-stable.deb
<reboot>
```

**Tell us more**

Could better documentation have prevented this issue? _unlikely_
Does this bug prevent you from using lando? _yes_

**Comment by nullvariable** [comment]
I did have a $HOME/.lando restored from a backup, I deleted this folder, but the error continues. Happy to provide more info but a bit at a loss on where to start.

**Comment by UnderwoodJM** [comment]
@nullvariable I was also troubleshooting this issue and came across https://github.com/aws-amplify/amplify-cli/issues/6924

Are you running lando commands from inside a terminal in VS Code?

For reference, our issue was in the Mac Version of Lando. If this is also an issue on Ubuntu then it might be an issue with VS Code.
