### ISSUE TITLE
Acquia Integration QA Testing

### ISSUE THREAD

**Issue by grasmash** [lando/lando#2904]
1. When the user selects a local token that has been deleted from Cloud, the resulting error is not clear: ```ERROR ==> Cannot read property 'filter' of undefined```
2. Add more helpful text to the Acquia specific options.
    -   --acquia-app  Acquia Cloud Platform Application UUID 
    -   --acquia-env  Acquia Cloud Platform Environment ID
    -   --acquia-key  Acquia Cloud Platform API Token (key) UUID

**Comment by pirog** [comment]
@grasmash i also got this when i tried things out. Agreed on the help text as well.
