### ISSUE TITLE
Tag v3.0.27 missing.

### ISSUE THREAD

**Issue by rubenvarela** [lando/lando#2922]
Tag v3.0.27 is referenced in a couple places but no tag exists,

>2021
>v3.0.27 - March 17, 2021
- https://docs.lando.dev/help/2021-changelog.html
- https://github.com/lando/lando/blob/ff53f2c23732e395f224aee77cbf84edc5806b60/docs/help/2021-changelog.md

> Also note that you must have Lando version 3.0.27 or higher to try this out.
- https://docs.lando.dev/config/acquia.html
- https://github.com/lando/lando/blob/ff53f2c23732e395f224aee77cbf84edc5806b60/docs/config/acquia.md

**Comment by pirog** [comment]
Hasn't been released yet
