### ISSUE TITLE
Noob Lando Pantheon / Drupal 9 Site Question

### ISSUE THREAD

**Issue by colema18** [lando/lando#2923]
I am trying to do a lando init --source remote --remote-url ssh://codeserver.dev.[user]@codeserver.dev.[user].drush.in:2222/~/repository.git --recipe pantheon

It seems fine until I get:
Detected that ssh://codeserver.dev.[user]@codeserver.dev.[user].drush.in:2222/~/repository.git is a git repo
Whoooops! Looks like you've already got a git repo here!
Either delete this repo or try to lando init in a folder without .git in it
ERROR: 154

How would I go about using lando to work with an existing Pantheon Drupal 9 site? Sorry if this is a silly question - I am a .NET and Sitecore developer so I am in new waters.

**Comment by xaqrox** [comment]
If you're working on a site with an existing git repo, I think you want to use `--source cwd` and omit the `--remote-url` option.

**Comment by alphex** [comment]
I would git clone from pantheon, and then do a `lando init` in the project root.

At least, thats what works for me...

**Comment by reynoldsalec** [comment]
Guessing OP @colema18 had their question answered; closing out but feel free to follow up here or on the Lando Slack https://launchpass.com/devwithlando
