### ISSUE TITLE
Host host unreachable With Docker 3.3.0 

### ISSUE THREAD

**Issue by deshiloh** [lando/lando#2930]
Yesterday docker self updated to the RC 1 Apple M1 3.3.0.

Since, was hard to make Lando works.

Now i can make it work with localhosts address but address with mysite.lndo.info doesn't work anymore :( I got host unreachable error :( 

Any fix with Lando ? Or I have to wait for an another update of docker ?

**Comment by pirog** [comment]
@deshiloh lando does not currently support M1 Macs so this is not surprising

**Comment by deshiloh** [comment]
But lando was working perfectly before the docker update, i was using the preview version of docker

**Comment by pirog** [comment]
The fact that it broke for you so easily on an update is one of the reasons why this is not currently supported.

**Comment by Pablo-Camara** [comment]
Go back to the preview version if you have the dmg file and it will work again, disable auto updates

**Comment by deshiloh** [comment]
Sadly I haven't, I searched for it on docker website but cant't find it. If someone got it, could you please give me a link to it ? :D

**Comment by Pablo-Camara** [comment]
be saved my friend: https://we.tl/t-dRsF9UW5Gz
use that one it works with lando
@deshiloh

**Comment by deshiloh** [comment]
Not Covid, but i kiss you ! haha Thanks a lot ! You saved me !
