### ISSUE TITLE
How do I tell the Platform.sh its ok to overwrite files it created?

### ISSUE THREAD

**Issue by xaqrox** [lando/lando#2947]
When I rebuild my Platform.sh apps on Lando, I get the following prompt:

```
The destination exists: /app/.platform/local/lando. Overwrite? [Y/n]
```

The answer is always "Y". Is there a flag I can set to skip this prompt?

**Comment by pirog** [comment]
@xaqrox can you share your platform config so we can try and replicate?

Note: https://github.com/platformsh-templates/wordpress-composer

**Comment by xaqrox** [comment]
Hmmm I don't seem to be able to reproduce this. Might have cleared up with a recent update. Sorry I didn't include version number in the original issue description. Will reopen if it pops back up and try to include more repro details.

**Comment by pirog** [comment]
@xaqrox good to know but im going to reopen till we can replicate or not ;)

**Comment by pirog** [comment]
@xaqrox i was not able to replicate this using our Drupal 8 test ssite but i was able to replicate using https://github.com/platformsh-templates/wordpress-composer

```bash
git clone https://github.com/platformsh-templates/wordpress-composer
lando start
lando rebuild
```

**Comment by pirog** [comment]
Alright, this should no longer prompt you as of https://github.com/lando/lando/releases/tag/v3.1.0
