### ISSUE TITLE
Acquia Recipe Database Connection

### ISSUE THREAD

**Issue by mikemadison13** [lando/lando#2951]
**Tell us about your setup**

I am currently running an Acquia BLT codebase and the drupal8 recipe. I have destroyed that VM and rebuilt using the experimental acquia recipe. As part of that process, I did update my database details to be 'acquia' across the board (vs. drupal8). What I am seeing is that with the drupal8 recipe, my setup works great. However, with the acquia recipe it cannot load my database setup. 

```
In Database.php line 371:
                                                             
  The specified database connection is not defined: default
```

BLT does have a number of overrides for settings files, so I'm wondering if the acquia recipe is somehow changing the way these are handled? It's highly suspicious to me that the exact same codebase works fine on the drupal8 recipe but not the acquia one.

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

lando version
v3.0.27

Mac OS 10.15.7

**Tell us about your `.lando.yml`**: 

see https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/develop/.lando.yml

See above, TLDR database connectivity works fine on drupal8 but not on acquia (and yes, I did update the database name, user name, and password to be acquia not drupal8). This appears to be flat out not finding the default database array.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

The govcon codebase can be spun up locally and works as is. You can use the same codebase to test the acquia recipe (although you'll have to update the database credentials and lando yml file)

**Comment by rubenvarela** [comment]
I've been testing this out too.

You should have something like, 

```    if (file_exists('/var/www/site-php')) {
        require('/var/www/site-php/example/example-settings.inc');
        }```

on your `settings.php` for Acquia. The Acquia recipe creates a basic file for it with the database info.

**Comment by mikemilano** [comment]
It does seem like the custom lando settings file isn't being included but I confirmed that the BLT include in the repo you linked should pull in the site group based path. `/var/www/site-php/{SITE_GROUP}/{SITE_GROUP}-settings.inc`

This is the Lando settings file that would be included at the path above: https://github.com/lando/lando/blob/master/experimental/lando-acquia/recipes/acquia/acquia-settings.inc

As a sanity check, you could copy the contents of the settings file linked above into the bottom of your settings.php?

At that point, a pull of the database only would be a good test.

**Comment by mikemadison13** [comment]
yeah I'll give that a whirl. it seems odd that the local settings that BLT includes out of the box (which defines the database for lando and works fine with other recipes) wouldn't "just work" though. I guess that's the thing that concerns me here the most. Why is the d8 recipe working in place but acquia isn't? Does that mean the acquia recipe is doing something differently? 

will report back (hopefully later today)

**Comment by mikemadison13** [comment]
I think I figured out what's happening here. Acquia (and BLT in particular) uses https://github.com/acquia/drupal-environment-detector to detect "where" we are in code. Using the acquia recipe, the detector "thinks" we are in a cloud environment and NOT a local. As a result, the local.settings files are not properly being included. 

Here's the output from the environment detector locally while using the acquia recipe:

```

array(7) {
--
  | ["local"]=>
  | bool(false)
  | ["dev"]=>
  | bool(false)
  | ["stage"]=>
  | bool(false)
  | ["prod"]=>
  | bool(false)
  | ["ci"]=>
  | bool(false)
  | ["ode"]=>
  | int(0)
  | ["ah_other"]=>
  | bool(true)
  | }

array(7) {
--
  | ["local"]=>
  | bool(false)
  | ["dev"]=>
  | bool(false)
  | ["stage"]=>
  | bool(false)
  | ["prod"]=>
  | bool(false)
  | ["ci"]=>
  | bool(false)
  | ["ode"]=>
  | int(0)
  | ["ah_other"]=>
  | bool(true)
  | }
```

so i think either the environment detector needs to be updated (FYI @danepowell and @grasmash) or there needs to be some tweaking in the acquia recipe so that it reports as a local and NOT a cloud environment.

**Comment by mikemadison13** [comment]
to confirm what @mikemilano showed above, if i manually paste in those database credentials they work (note that my credentials from the local file _also_ work if i manually include them). the problem here is that the local config isn't being properly applied.

**Comment by grasmash** [comment]
Fixed in https://github.com/acquia/drupal-environment-detector/pull/16
