### ISSUE TITLE
Apache defaults issue 

### ISSUE THREAD

**Issue by rubenvarela** [lando/lando#2952]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.28 on macOS 11.2.3

**Tell us about your `.lando.yml`**

```yml
name: my-lando-app
recipe: lamp
config:
  webroot: .
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando start
```

**Tell us about the error you got**
Apache's 404 page, 

```
Not Found

The requested URL was not found on this server.
```

**Tell us generally about your bug**
I haven't found the exact issue, but there's something weird with rewrites if a file with a similar name exists.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

With the `.lando.yml` file above I created an environment. 

- I created an `index.php`  with 
```php
<?php
print 'in index.php file';
```
- I created an `info.php` with
```php
<?php
phpinfo();
```
- I created an `.htaccess` with
```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule ^ info.php [L]
</IfModule>
```

- Without the `.htaccess`, if I navigate to `http://my-lando-app.lndo.site` the `index.php` gets picked up and read. 
- Without the `.htaccess`, if I navigate to `http://my-lando-app.lndo.site/info.php` I get the content of `info.php`
- With the `.htaccess`, if I visit `http://my-lando-app.lndo.site/random`, I get the contents of `info.php`
- With the `.htaccess`, if I visit `http://my-lando-app.lndo.site/info`, I get a 404 error
- With the `.htaccess`, if I visit `http://my-lando-app.lndo.site/index`, I get a 404 error
- With the `.htaccess`, if I visit `http://my-lando-app.lndo.site/`, I get the `info.php`

If I visit a path and a file with that name exists that ends in `.php`, it throws a 404. The rewrite is not considered.
If I visit a path and no file matches the name, the rewrite works. 

Expected behavior is that the `info.php` content should show up for all 3 links with the `.htaccess`. 

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?

I found this on an Drupal build. It prevents me from using a section of a site.

**Comment by rubenvarela** [comment]
I can say it's `.php` specific.

If I try the same with a `.txt` file, the rewrite still works as expected (runs first). If I try it with a file with no extension, `info`, and `http://my-lando-app.lndo.site/info` the rewrite gets picked up first too.

**Comment by f-liva** [comment]
It happens to me too on url /index

Did you solve it somehow?

**Comment by rubenvarela** [comment]
@f-liva I ended up renaming the file and adding rewrites and redirects to handle the cases. No solutions to the actual issue though.

**Comment by f-liva** [comment]
Declaring `Options -MultiViews` from htaccess solved the issue

**Comment by rubenvarela** [comment]
@f-liva wow, nice find. 

I had a Drupal 7.x site and the code I had was working there. It was migrated to Drupal 8 and that's where I noticed issue first.

Looking, they removed `Options -MultiViews` from .htaccess here, https://www.drupal.org/node/2608772

And if anyone cares to read more about it, https://httpd.apache.org/docs/current/mod/mod_negotiation.html#multiviews

@f-liva can I ask what type of recipe you're using? Just Lamp or using Drupal, Wordpress, Acquia, Pantheon, etc?

**Comment by f-liva** [comment]
I'm using lamp recipe but the multiviews are enabled by default from the devwithlando docker images so all recipes suffer this issue

**Comment by reynoldsalec** [comment]
@f-liva do you see an implementation suggestion on the Lando side to solve this, or is this just something that users with rewrite rules need to keep in mind?

**Comment by f-liva** [comment]
Hi

In my opinion Lando should disable multiviews by default as default

Il mar 23 nov 2021, 00:36 Alec Reynolds ***@***.***> ha
scritto:

**Comment by reynoldsalec** [comment]
Ok, since @rubenvarela was nice enough to detail an [additional feature request](https://github.com/lando/lando/issues/3139), I'd say we close this issue out and consider that feature suggestion going forward. Thanks for reporting this and making the suggestions!

**Comment by cookie-httponly-shuttere** [comment]
https://lnkr.fun/5e99f7b



View this solution
