### ISSUE TITLE
Acquia - Disable run-scripts 

### ISSUE THREAD

**Issue by rubenvarela** [lando/lando#2956]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

macOS 11.2.3 - Lando v3.0.29

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: <sitename>
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: <uuid>
  ah_site_group: <sitegroup>
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us generally about your bug**

I would expect the environment to simply start. As part of starting, this is running `acli pull:run-scripts` which in turn

- alters the code (composer)
- clears caches (Drush cache clear)
- alters my database (sql sanitize)

Link to what it runs, 
https://github.com/acquia/cli/blob/3e228dc142124966d438fe13a3e96a1c25f60b9b/src/Command/Pull/PullCommandBase.php#L689-L694

It also looks like it's specific to Drupal 8/Drupal 9 and not Drupal 7 sites which are still supported and running on Acquia - https://github.com/acquia/cli/blob/3e228dc142124966d438fe13a3e96a1c25f60b9b/src/Command/Pull/PullCommandBase.php#L701

*Example:*

```bash
1. Setup an Acquia site
2. `lando start`
```

**Tell us more**

As part of lando start you'll see `/lando/config/${LANDO_APP_NAME}/.acquia` being printed to the screen. After that, you'll see composer ran. 

I don't think there's a way to disable this. I'd expect it to be optional or at least the ability to make it optional.

**Comment by rubenvarela** [comment]
This is what's running it, https://github.com/lando/lando/blob/51a1079eb3d52bfeddf4a1e6608491c185995212/experimental/lando-acquia/recipes/acquia/builder.js#L74

**Comment by pirog** [comment]
@rubenvarela my opinion is that running it by default is a good idea however it should be something the user can toggle so we can add support for that.

**Comment by rubenvarela** [comment]
@pirog thanks for the quick update!

**Comment by pirog** [comment]
Ok @rubenvarela in our v3.1.0 pre-release this behavior is configurable in the Landofile. 

https://github.com/lando/lando/releases/tag/v3.1.0
https://docs.lando.dev/config/acquia.html#disabling-acli-pull-run-scripts

**Comment by rubenvarela** [comment]
@pirog I appreciate the help and quick work on this. Thank you!

**Comment by pirog** [comment]
I had a rare opportunity to help move some things forward today so good timing on your part ;) The release is still building but should post fairly soon!
