### ISSUE TITLE
`docker-compose` spits out repetitive reminder to use `docker compose up` on Mac & Windows

### ISSUE THREAD

**Issue by xaqrox** [lando/lando#2962]
**Tell us about your setup**

Lando v3.1.0, MacOS Mojave 10.14, Docker Desktop 3.3.0

**Tell us about your `.lando.yml`**

This is happening across all of my apps.

**Tell us about the command you were running**

```
lando start
```

**Tell us about the error you got**

```
Docker Compose is now in the Docker CLI, try `docker compose up`
```

**Tell us generally about your bug**

After updating to v3.1.0 I get this message every time I start any app. I tried platform, pantheon, wordpress, even a lamp app init-d in an empty directory. It's not causing any errors, but it is mildly annoying. However this is only Mac & Windows right now... maybe docker compose needs a config to turn this off. https://github.com/docker/compose/pull/8166

**Comment by flowchartsman** [comment]
Yah, I use `docker-compose` for some shared testing dev targets and any linux users won't be able to use them if I migrate to `docker compose` and I will be annoyed to no end if I don't.

**Comment by pirog** [comment]
As far as we can tell:

1. There is no way to suppress this message
2. `docker compose` is not ready for primetime yet eg lando breaks if you try to use it

I definitely love that `docker-compose` tells you to use `docker compose` but `docker compose` throws a warning that it is still "experimental." ROLLING HARD!

**Comment by xaqrox** [comment]
Ahhh, what happened to the days of taciturn command line utilities...?

**Comment by reynoldsalec** [comment]
Great thread :)

I don't believe this is a concern anymore, but if you find yourself in a bind, you can try disabling Docker Compose V2 in your Docker for Mac/Windows settings. https://docs.docker.com/compose/cli-command/#install-on-mac-and-windows
