### ISSUE TITLE
How is lando resolving hostname, can't find entry in  `/etc/hosts`

### ISSUE THREAD

**Issue by esafwan** [lando/lando#2968]
I have started a Drupal 8 project via Lando recipe. I got the following domain to access it:

1. https://localhost:61755
2. http://localhost:61756
3. http://d8-source.lndo.site/
4. https://d8-source.lndo.site/

Lando has made no entry to my /etc/hosts file. Yet the hostnames work. I am trying to understand how its done. And If we need to change it, where we can change.

**Comment by rabauss** [comment]
see: https://docs.lando.dev/config/proxy.html
