### ISSUE TITLE
Why are all the latest releases marked as prerelease?

### ISSUE THREAD

**Issue by davereid-pfg** [lando/lando#2973]
I'm just curious why they aren't official, is there some major change being tested? I don't feel like I see that reflected in any of the release notes? It would be nice to be able to get Docker Desktop on the latest version to stop the update notifications.

**Comment by pirog** [comment]
https://docs.lando.dev/config/releases.html

**Comment by davereid-pfg** [comment]
Gotcha, I have a hard time reconciling semantic versioning vs the release channels, it seems like they're at odds currently. According to the semantic versioning, the latest stable release to use would be v3.0.29 since that would only have bug fixes from the last stable release (v3.0.26)?

**Comment by pirog** [comment]
Makes sense.

We mostly follow semantic versioning but add the release channel stuff on
top of that for various reasons. We know it’s not perfect and somewhat
confusing but it was the easiest way for us to implement a way for users to
get “less stable” release updates and bleeding edge at the same time.

That said we have plans to overhaul the whole release cycle so it’s
“better” and that’s something you should see in the next few months

**Comment by davereid-pfg** [comment]
@pirog Thanks for that clarification! I'm also curious what is the process for defining once a release has had enough testing? Is it a minimum number of downloads or days without a breaking bug report?

I'll probably update to the edge channel to help test out future releases!

**Comment by pirog** [comment]
@davereid-pfg i'd say it's more an art form than a science ;) but generally we wait a "reasonable" amount of time after the release is cut and no "significant" bug reports come in before we kick the release from edge to stable.
