### ISSUE TITLE
Migrating recipes: from drupal8 to drupal9

### ISSUE THREAD

**Issue by andrewholgate** [lando/lando#2976]
I have recently migrated my project from Drupal 8 to Drupal 9 and now I am eyeing off Lando as the next migration to make: from `recipe: drupal8` to `recipe: drupal9`.

Before I do it, I was wondering if it's as trivial as just changing the recipe name to `recipe: drupal9` and doing a rebuilding of lando, or are there other considerations I should be taking into account before doing it?

For example, will it create a new database for the recipe and I'll need to migrate over to it or will it use the existing database from the current drupal8 recipe? Is there anything else manual I will need to do?

**Comment by rubenvarela** [comment]
I tried this recently. Only change I had to do was regarding Drush.

I did `destroy` and `start` since the database and credentials become `drupal9` instead of `drupal8`.

**Comment by andrewholgate** [comment]
@rubenvarela Ah right, so you had to reimported your database from the `drupal8` recipe into the new `drupal9` recipe database I guess?

Anything else I need to consider?

**Comment by rubenvarela** [comment]
Yeah. I dumped the database before starting the process. Then changed the file, `lando destroy` then `lando start`
Then just import. 

I had to specify `/app/vendor/drush` on some custom commands. 

Not sure if due to environment variables or something else (didn't dig much). Simple enough fix though.

**Comment by andrewholgate** [comment]
@pirog Would what we've discussed above be the recommended instructions for upgrading? If so, perhaps a small addition to the docs would be useful for others?
