### ISSUE TITLE
Docker 3.3.1 not allowing to disable automatic updates

### ISSUE THREAD

**Issue by Didel** [lando/lando#2980]
As of docker 3.3.1 (or earlier?), it appears to be that you aren't able to disable automatic updates any more (unless you are using the paid Docker Teams plan):

<img width="544" alt="Schermafbeelding 2021-04-28 om 13 40 54" src="https://user-images.githubusercontent.com/915243/116398093-af1c7200-a827-11eb-9d63-f35607d738f9.png">

Of course, Lando comes bundled with its own Docker desktop in order to ensure compatibility between Lando and Docker. However, I can only imagine that this change by Docker effectively kills this approach. Once a user has installed version 3.3.1, you are basically forced to always use the latest version and can't 'simply' choose not to update Docker any more.

As a result, I think that Lando should rethink the approach to this. On the bright side, it means that Docker also doesn't need to be bundled with Lando any more, making it a much smaller download. However, it will mean that once Docker releases a new version, the compatibility with Lando should be checked and verified, and fixed ASAP when required. Perhaps this might also require a more flexible releasing schedule (doing smaller releases more often) and introduce (more) new automated tests to verify compatibility.

**Comment by pirog** [comment]
It's in the works

**Comment by rubenvarela** [comment]
This was causing issues (aside from being annoying) and for now we've been adding, 

    127.0.0.1       desktop.docker.com

To our hosts file, `/etc/hosts`

**Comment by nicomollet** [comment]
On a side note, Docker auto updated to 3.3.1 and crashed on start, on Windows (see https://github.com/docker/for-win/issues/10958).
I had to downgrade to 3.2.2 and wait for a fix.
Now Docker 3.3.2 is released and seems to fix it.

**Comment by kopepasah** [comment]
@pirog any specific tickets for "in the works"? Would love to help, where possible.
