### ISSUE TITLE
BREAKUP2021

### ISSUE THREAD

**Issue by pirog** [lando/lando#2989]
https://www.youtube.com/watch?v=WA4iX5D9Z64

**Comment by kopepasah** [comment]
This makes me so curious... 😆

**Comment by uberhacker** [comment]
Could this be a reference to the Bill and Melinda Gates breakup? :-D  I know @pirog thinks Windows is the greatest operating system ever.

**Comment by kopepasah** [comment]
LOLOLOLOLOLOL

**Comment by pirog** [comment]
@uberhacker you know me so well!

**Comment by kopepasah** [comment]
You all are hilarious. Made my day. 👏🏻

**Comment by gmeben** [comment]
This was referenced in the release notes for 3.3.2 and it seems like a facetious and mysterious way of notifying users about an impactful planned change. 

Is this implying that Windows support will be dropped at some point?

**Comment by pirog** [comment]
It's not. If and when there are big changes coming that will impact users in a meaningful way we will communicate them as we have in past. 

This issue exists primarily so we can track some big changes we are making to how the project is structured and organized. Windows support will not be dropped, if anything it will get significantly better.

**Comment by gmeben** [comment]
>It's not. 

The issue is titled "BREAKUP2021", the description is only a link to a Taylor Swift video, and the discussion here until today was apparently focused more on horseplay than providing clarification. 

>This issue exists primarily so we can track some big changes

Then it probably doesn't belong in release notes. 

And if it does, then more context/detail is necessary there to avoid confusing your users.

**Comment by pirog** [comment]
Inclusion in the release notes for lando/lando was a copy/paste error while copying the release notes from lando/cli.
