### ISSUE TITLE
How would I access a lando website from an Android Virtual Device?

### ISSUE THREAD

**Issue by Martmists-GH** [lando/lando#3008]
I've tried using mitmproxy or the AVD Proxy settings, but I've yet to be able to connect to the servers from AVD. 
I also attempted to modify /etc/hosts, but it's in the read-only system partition (which cannot be remounted).

**Comment by vaggelis-net** [comment]
Assuming the lando project runs on the same system,  did you try **10.0.2.2**?

More info [here](https://developer.android.com/studio/run/emulator-networking)

**Comment by martmists-gh** [comment]
The problem is that wordpress returns its own website link, being *.lndo.site, which results in the android device making a request to localhost.

**Comment by vaggelis-net** [comment]
I mostly work with Laravel projects, and Lando provides both *.lndo.site and localhost urls. Isn't that the case for Wordpress too?

**Comment by rubenvarela** [comment]
@vaggelis-net all *.lndo.site urls point to 127.0.0.1

If it's another device, it'll point to itself,

```
 ~  dig anything.lndo.site -t A

; <<>> DiG 9.10.6 <<>> anything.lndo.site -t A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49262
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;anything.lndo.site.            IN      A

;; ANSWER SECTION:
anything.lndo.site.     274     IN      A       127.0.0.1

;; Query time: 2 msec
;; SERVER: 192.168.138.1#53(192.168.138.1)
;; WHEN: Thu May 13 11:00:22 EDT 2021
;; MSG SIZE  rcvd: 63


 ~   dig anythingelse.lndo.site -t A

; <<>> DiG 9.10.6 <<>> anythingelse.lndo.site -t A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61362
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;anythingelse.lndo.site.                IN      A

;; ANSWER SECTION:
anythingelse.lndo.site. 293     IN      A       127.0.0.1

;; Query time: 3 msec
;; SERVER: 192.168.138.1#53(192.168.138.1)
;; WHEN: Thu May 13 11:00:19 EDT 2021
;; MSG SIZE  rcvd: 67

```

@martmists-gh maybe an option, 

You need to modify your `~/.lando/config.yml` and add, `bindAddress: 0.0.0.0`.  There are security implications if you are in a public network or a network with other people, https://docs.lando.dev/config/security.html#exposure

```
cat ~/.lando/config.yml
experimental: true
bindAddress: 0.0.0.0
```

At this point, you can access your lando instance via the IP. 
After that, I run, https://github.com/leproxy/leproxy
This allows me to create an HTTP proxy that I can add to my device. I have a record for `mysite.test` on my hosts file that returns the IP of my host machine. 

    192.168.1.X mysite.test

That gets passed via leproxy. 

Then on my lando file I have, 

```
proxy:
  appserver:
    - mystie.test
```

Configure the http proxy to your android device on your network and it should work
