### ISSUE TITLE
drupal core directory not found?

### ISSUE THREAD

**Issue by aaronELBorg** [lando/lando#3013]
I'm using version v3.1.4 on a MacBook Pro (Big Sur) and brand new to lando but it's almost working.  I say almost because the phpmyadmin bit (see below) is indeed working.

However, going to the main site here:  http://mysite.lndo.site/ 

...results in a redirect to: mysite.lndo.site/core/install.php  which I'm assuming it's looking for the core files and can't find them.  Error message states: Forbidden You don't have permission to access this resource."

And 'lando drush status' results in:

 Drupal version : 8.9.14                            
 Site URI       : http://default                    
 PHP binary     : /usr/local/bin/php                
 PHP config     :                                   
 PHP OS         : Linux                             
 Drush script   : /app/vendor/drush/drush/drush     
 Drush version  : 9.7.2                             
 Drush temp     : /tmp                              
 Drush configs  : /app/vendor/drush/drush/drush.yml 
                           /app/drush/drush.yml              
 Drupal root    : /app/docroot                      
 Site path      : sites/default  

I have a feeling it might something to do with this command in my lando file:
    cmd: drush --root=/app/docroot

FWIW, the site folder in question is located here:
/Users/myname/sites/mysite

And the docroot is:
/Users/myname/sites/mysite/docroot

And the .lando.yml file is located in:
/Users/myname/sites/mysite/.lando.yml

Thank you for any advice.

Here is my lando file:

name: mysite
recipe: drupal8
config:
  php: '7.3'
  via: apache:2.4
  webroot: docroot
  database: mysql:5.7
  xdebug: true

  config:
    # here's our custom php.ini file
    php: .lando.php.ini

proxy:
  phpmyadmin:
    - phpmyadmin.mysite.lndo.site

services:
  phpmyadmin:
    type: phpmyadmin
  appserver:
    overrides:
      environment:
        # support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"

tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/docroot

  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: docker-php-ext-enable xdebug && /etc/init.d/apache2 reload
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload
    user: root

**Comment by fruitshakes** [comment]
sounds to me like it's not connected to the database. have you set the lando database details in `docroot/sites/default/settings.php` (or in settings.local.php if you don't want to push that to prod)?

something along these lines should do it: 

```
$lando_info = json_decode(getenv('LANDO_INFO'), TRUE);
$databases['default']['default'] = [
  'driver' => 'mysql',
  'database' => $lando_info['database']['creds']['database'],
  'username' => $lando_info['database']['creds']['user'],
  'password' => $lando_info['database']['creds']['password'],
  'host' => $lando_info['database']['internal_connection']['host'],
  'port' => $lando_info['database']['internal_connection']['port'],
];
```
