### ISSUE TITLE
Update Composer to LTS version 2.2

### ISSUE THREAD

**Issue by gitressa** [lando/lando#3029]
[Composer 2.0.14](https://github.com/composer/composer/releases/tag/2.0.14) was released May 2021, perhaps we can update to that version? I just can't see where the Composer version is defined ... https://github.com/lando/lando/search?q=composer_version

**Comment by gitressa** [comment]
[Composer 2.1.0](https://github.com/composer/composer/releases/tag/2.1.0) was just released, but maybe it's too soon to update to that version? See also [Update Composer to 2.1.0](https://www.drupal.org/project/drupal/issues/3217142) where it is tested with Drupal.

**Comment by gitressa** [comment]
Composer 2.2 LTS was released 22 December 2021, with many improvements, and for example "... drastically improves memory and CPU usage, in some cases up to 90% reduction". For more, see [Composer 2.2 Release](https://blog.packagist.com/composer-2-2/).

Perhaps Lando should consider updating to the new Composer 2.2.3 release?

**Comment by aschkenasy** [comment]
just making sure you're aware that you can define composer version via
`composer_version: 2-latest` in your lando yml under services as outlined in [https://docs.lando.dev/config/php.html#installing-composer](https://docs.lando.dev/config/php.html#installing-composer)

**Comment by gitressa** [comment]
I wasn't aware of the "2-latest"-option, but that does work perfectly. Thanks!

**Comment by tormi** [comment]
I think it's good idea to update default Composer from `2.0.7` to the [latest LTS](https://blog.packagist.com/composer-2-2/).

**Comment by gitressa** [comment]
I have created the Merge Request lando/php#24 which updates Composer to the latest LTS release `2.2.6`.

**Comment by labboy0276** [comment]
Closing this in favor of the PR
