### ISSUE TITLE
"Hello World" Lando Recipe Yields 404

### ISSUE THREAD

**Issue by GuyPaddock** [lando/lando#3038]
**Tell us about your setup**
v3.1.4 on Windows 10.0.19043 Build 19043

**Tell us about your `.lando.yml`**
Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
```yml
name: hello-lando
recipe: lamp
config:
  webroot: .
```

The `index.html` file contains:
```html
<h1>Lando says hellooo what have we here?</h1>
```

**Tell us about the command you were running**
Paste in a series of commands that caused the bug.

From https://docs.lando.dev/basics/first-app.html#hello-world:
```bash
mkdir hello && cd hello
echo "<h1>Lando says hellooo what have we here?</h1>" > index.html
lando init \
  --source cwd \
  --recipe lamp \
  --webroot . \
  --name hello-lando
lando start
```

**Tell us about the error you got**
Visiting http://hello-lndo.lndo.site/ yields:
```
404 page not found
```

For some reason, Lando is not picking up the `index.html` file. This may be related to https://github.com/lando/lando/issues/2952, though the discussion there seems to be about default handling of PHP files in Apache on Lando and this is just a static HTML hello world test.

Incidentally, if I run the following command:
```
docker exec hellolando_appserver_1 cat index.html
```

I get:
```
<h1>Lando says hellooo what have we here?</h1>
```

**Comment by rubenvarela** [comment]
@GuyPaddock did your last comment on docker/for-win fix this then? Had some information come up on #2952
