### ISSUE TITLE
Drupal webp not working?

### ISSUE THREAD

**Issue by jigarius** [lando/lando#3039]
## Problem

* I installed the `webp` module; `composer require drupal/imageapi_optimize_binaries drupal/webp -W`
* I installed `webp` binaries; `apt update && apt install -y webp`
* I configured the default image optimization pipeline to include `webp`
* The same thing works on my server, but doesn't work with my Lando setup
  * Sadly, I couldn't find much debugging info either, just that `imagewebp()` fails silently.
  * Strangely, without any changes, a `webp` variant of my image was generated only once. I mean, there were no `webp` images, but during multiple refreshes, a `webp` image was generated, only once.
* I wonder if someone else can reproduce this issue?
  * Maybe it's related to memory? `imagewebp()` is running out of memory or something similar?
  * The Drupal app is the only set of Docker containers I have running and Docker is allowed to use 4 GB of RAM.

Any help will be appreciated.

**Comment by ptmkenny** [comment]
I have the Webp module working on Drupal 9 with the base Pantheon recipe.

That said, instead of trying to troubleshoot this, it might be better to wait for Drupal 9.2 (to be released in three days on June 16), which [supports webP out of the box](https://gorannikolovski.com/blog/drupal-92-will-support-webp-images-out-box).

**Comment by rubenvarela** [comment]
anything coming through on `lando logs` or `lando logs --follow`?

> Strangely, without any changes, a webp variant of my image was generated only once. I mean, there were no webp images, but during multiple refreshes, a webp image was generated, only once.

I ask because this reminds me of some possible issues I've seen with running out of memory and that should be shown on logs.

**Comment by reynoldsalec** [comment]
You need any further help on this @jigarius? Re-open if you do, just closing out on the assumption/hope that you were able to get some joy eventually.
