### ISSUE TITLE
Add RAILz recipe

### ISSUE THREAD

**Issue by pirog** [lando/lando#304]
Now that we've got a RUBY service dialed, the pathway to a RAILs recipe is open

@reynoldsalec maybe you can ping mrs @reynoldsalec to see if she knows of any useful documentation we could follow to make sure we cover all the rails basics.

**Comment by serundeputy** [comment]
@dustinleblanc did you have some progress on a rails recipe?

**Comment by dustinleblanc** [comment]
Yep! I got blocked though because for some reason, Puma was refusing connections. I set it up using vanilla docker-compose and Puma was happy to serve connections, so I may be getting blocked by a lack of Lando understanding. I can publish my branch on my fork if its helpful

**Comment by serundeputy** [comment]
yes; I think publishing your branch will not hurt; and best case scenario encourage collaboration!

thanks for your great work so far!

**Comment by dustinleblanc** [comment]
@serundeputy see https://github.com/lando/lando/pull/602. This is definitely not ready for prime time, but I got far enough that you guys may be able to correct my mistakes and we can work on rolling the ball further down the road.

**Comment by hardyoyo** [comment]
Here's a Docker-Compose wrapper written in Ruby which is designed to set up a Rails dev environment, it might have some useful bits to swipe. https://gitlab.com/notch8/stack_car

**Comment by dustinleblanc** [comment]
Marking this as a candidate for a new contrib plugin
