### ISSUE TITLE
Command "lando init --source acquia" get Invalid value

### ISSUE THREAD

**Issue by Adrianm6254** [lando/lando#3042]
Basically any other task or issue should go here. Try to frame it as a user story if it makes sense.
I am running lando version v3.0.26 

This is my output:

$ lando init --source acquia -v
lando init

Initializes code for use with lando

Options:
  --channel          Sets the update channel                                                        [array] [choices: "edge", "none", "stable"]
  --clear            Clears the lando tasks cache                                                                                                    [boolean]
  --experimental     Activates experimental features                                                                                          [boolean]
  --help             Shows lando or delegated command help if applicable                                                           [boolean]
  --verbose, -v      Runs with extra verbosity                                                                                                       [count]
  --full             Dump a lower level lando file                                                                             [boolean] [default: false]
  --github-auth      A GitHub personal access token                                                                                           [string]
  --github-repo      GitHub git url                                                                                                                         [string]
  --lagoon-auth      A Lagoon ssh key                                                                                                                    [string]
  --lagoon-site      A Lagoon project name                                                                                                           [string]
  --name             The name of the app                                                                                                              [string]
  --option, -o       Merge additional KEY=VALUE pairs into your recipes config                                                  [array]
  --pantheon-auth    A Pantheon machine token                                                                                                 [string]
  --pantheon-site    A Pantheon site machine name                                                                                              [string]
  --platformsh-auth  A Platform.sh access token                                                                                                    [string]
  --platformsh-site  A Platformsh project name                                                                                                      [string]
  --recipe, -r       The recipe with which to initialize the app
         [string] [choices: "backdrop", "drupal6", "drupal7", "drupal8", "drupal9", "joomla", "lagoon", "lamp", "laravel", "lemp",
                                                                         "mean", "pantheon", "platformsh", "symfony", "wordpress"]
  --remote-options   Some options to pass into either the git clone or archive extract command              [string] [default: ""]
  --remote-url       The URL of your git repo or archive, only works when you set source to remote                        [string]
  --source, --src    The location of your apps code
                                                               [string] [choices: "cwd", "github", "lagoon", "pantheon", "platformsh", "remote"]
  --webroot          Specify the webroot relative to app root                                                                                  [string]
  --yes, -y          Auto answer yes to prompts                                                                                 [boolean] [default: false]

Invalid values:
  Argument: source, Given: "acquia", Choices: "cwd", "github", "lagoon", "pantheon", "platformsh", "remote"

**Comment by pirog** [comment]
@Adrianm6254 upgrade to teh latest version.
