### ISSUE TITLE
Cannot pull database from Pantheon

### ISSUE THREAD

**Issue by adamdeprince** [lando/lando#3045]
**Tell us about your setup**

lando version 3.1.4 
macos 11.2.3 (20D91)

**Tell us about your `.lando.yml`**

name: pom-olp
recipe: pantheon
config:
  framework: wordpress
  site: pom-olp

**Tell us about the command you were running**

lando pull --database=test --files=none --code=none --verbose

**Tell us about the error you got**

Doesn't download

```
Making sure your site is awake...
 [notice] OK >> test-pom-olp.pantheonsite.io responded
Pulling your database... This miiiiight take a minute
test.b24519f1-11f9-4e70-a6b1-1@appserver.test.b24519f1-11f9-4e70-a6b1-1bfb78801c24.drush.in's password:    0 B 0:00:09    0 B 0:00:29 [   0 B/s] [<=>
```
**Tell us generally about your bug**

I'm trying to pull a database and it stalls.

**Comment by PivotMatt** [comment]
@adamdeprince Hi -- I had the same issue and was able to fix by creating a new Pantheon SSH key for my machine:
https://pantheon.io/docs/ssh-keys

**Comment by dustinleblanc** [comment]
Yep, this looks like an issue with not having an SSH key added on Pantheon. @adamdeprince, if that doc doesn't help, hop on Slack and we can try to troubleshoot.
