### ISSUE TITLE
Quick Laravel start not working

### ISSUE THREAD

**Issue by branivreyes** [lando/lando#3053]
After doing the quick start for Laravel it just shows 404 not found when trying to see the page on whatever link the console gives.
Also, a lot of warnings about Composer 2 and a warning about using an unsupported version of docker compose even when I have a supported one. Containers seems to work fine.

**What is your lando version and operating system?** 
Lando: v3.1.4
OS: tested on two different systems, same result: Manjaro Gnome 21.0.7 and Ubuntu 21.04

.lando.yml is the same as the Laravel quick start guide.

**Tell us about the command you were running**
Commands were the same as the Laravel quick start guide.

**Tell us about the error you got**
Not found 404

**Tell us more**
Does this bug prevent you from using lando? **Yes**

**Comment by LewisLarsen** [comment]
You can specify Composer 2 in the configuration yaml file, however you're correct about the 404.

**Comment by dustinleblanc** [comment]
I just tested a fresh Laravel install and I am not having any problems, posting your .lando.yml may help spot issues. Composer 2 is also now the default, and Laravel shouldn't throw any errors unless you've installed incompatible packages.

**Comment by dustinleblanc** [comment]
This looks like a docs error if you are following the quickstart guide which should be resolved with #3071
