### ISSUE TITLE
lando v3.1.4 + Docker v3.x + Mac Big Sur (11.4)

### ISSUE THREAD

**Issue by jvandenrym** [lando/lando#3057]
Untill now I had to install Docker 2.5.1 to make lando work with Mac Big Sur (11.4) . It seems this is still the case.
Any Docker version 3.x breaks lando still. What is the current status on this?

**Comment by pirog** [comment]
@jvandenrym this is news to us. we have a very large amount of users using lando with big sur and docker 3.x. that said big sur is the oldest macos version currently supported by docker so you likely will need to upgrade at some point.

**Comment by rlorenzo** [comment]
@jvandenrym We had a developer have issues with this as well. He had to uninstall his own version of Docker and uninstall Lando and then reinstall Lando using Lando's Docker package that comes with it. Landos seems to break if you try to use your own Docker install. 

This is noted in the install guide at https://docs.lando.dev/basics/installation.html

> When going through the installer you can choose to not install Docker Desktop, although we recommend you use the version of Docker Desktop that we ship for compatibility and support reasons!
