### ISSUE TITLE
lamp/lemp db-import database option

### ISSUE THREAD

**Issue by drjayvee** [lando/lando#3063]
In the `lamp` recipe, there's a tooling command `db-import`.

While it does provide a `--host|-h` option, it unfortunately doesn't have a `--database|-d` option to specify which database to use for the import.

The [documentation for `db-import`](https://docs.lando.dev/guides/db-import.html#usage) seems to *hint* that this is (or at some point was) possible:

```
# Import a file into an auxiliary second database called 'db2'
# with a db called `dataz`
```

The `sql-import.sh` helper does have some code related to this feature:

```shell
# Get type-specific config
if [[ ${POSTGRES_DB} != '' ]]; then
  DATABASE=${POSTGRES_DB:-database}
  # ...
else
  DATABASE=${MYSQL_DATABASE:-database}
  # ...
fi

# ...

# Build DB specific connection string
if [[ ${POSTGRES_DB} != '' ]]; then
  CMD="psql postgresql://$USER@$HOST:$PORT/$DATABASE"
else
  CMD="mysql -h $HOST -P $PORT -u $USER ${LANDO_EXTRA_DB_IMPORT_ARGS}"
fi
```

I've tried `lando db-import --database name file.sql`, but no cigar. The command always defaults to using the database `lamp`.

**Comment by markdorison** [comment]
The documentation noted in the original issue [still exists](https://docs.lando.dev/guides/db-import.html#usage):

```
# Import a file into an auxiliary second database called 'db2'
# with a db called `dataz`
```

Is it possible to specify a database for import?

**Comment by phil-s** [comment]
> Is it possible to specify a database for import?

Three comments above yours there's an example of doing that.

It would be nice if the default tool provided this option, though.

**Comment by markdorison** [comment]
@phil-s It's still confusing that the official documentation references something that may (or may not?) be supported.

That said, I appreciate you responding! Is your suggestion to copy the existing import script and then modify it in some way with the snippet you shared?

**Comment by phil-s** [comment]
Yes, if the standard script works for you otherwise then a small tweak to that will probably do the trick.  I'm not using that script anyway, but I can see it in `~/.lando/scripts/sql-import.sh` and it's doing this:

```sh
if [[ ${POSTGRES_DB} != '' ]]; then
  DATABASE=${POSTGRES_DB:-database}
  PORT=${LANDO_DB_IMPORT_PORT:-5432}
  USER=${LANDO_DB_IMPORT_USER:-postgres}
else
  DATABASE=${MYSQL_DATABASE:-database}
  PORT=${LANDO_DB_IMPORT_PORT:-3306}
  USER=${LANDO_DB_IMPORT_USER:-root}
fi
```
It's probably simplest just to add the following after that.
```sh
if [ -n "$2" ]; then
  DATABASE=$2
fi
```

**Comment by markdorison** [comment]
@phil-s Thanks I will give this a shot!
