### ISSUE TITLE
Blog entry code example mistake

### ISSUE THREAD

**Issue by JPustkuchen** [lando/lando#3069]
@mikemilano in your blog article
https://blog.lando.dev/2020/12/03/symfony-with-lando/

> Instead of bin/console you will use lando console.
> 
> Let's create a home page by using the maker bundle.

`lando make:controller DefaultController`

must be:
`lando console make:controller DefaultController`

"console" is missing in the example. Might be confusing for beginners.

Thank you :) Great article!

**Comment by mikemilano** [comment]
Thanks for the report @JPustkuchen! I've pushed a fix for this which will be visible as soon as the robots finish deploying.
