### ISSUE TITLE
Docker Desktop on macbook pro causes extreme temperature rise

### ISSUE THREAD

**Issue by zohar** [lando/lando#3073]
Docker-Desktop can cause extreme temperature rise on macbook pro machines. The heat is so high that it burns my fingers.
This is a brand new macbook pro, latest model. 
A reference of this issue can be found on Apple: https://discussions.apple.com/thread/251362074

**I know it's not a lando issue**, but I assume many lando users use macbooks, so I wonder - what do **you** do about this issue? Did you find a way to reduce the heating? Are there any workarounds that remedy this problem?

**Comment by Xilonz** [comment]
This might be the cause of your issue: https://github.com/lando/lando/issues/2635
