### ISSUE TITLE
Lando starts removing old networks because of Docker's network limit

### ISSUE THREAD

**Issue by Vandaahl** [lando/lando#3084]
I am running Lando v3.1.4 on Debian 10 and have a few dozen Lando apps. I run a nightly script that backups all the databases of my Lando apps, so all apps are started and then stopped when the script has finished. In the morning, when I manually start some apps I'm working on, chances are that one of them will complain that "Lando has detected you are at Docker's network limit!" and it starts removing some old networks. Consequently, I will have to rebuild other apps that have their network removed on a daily basis.

I thought I could get around this by increasing the Docker network limit, so I followed [theses suggustions](https://serverfault.com/a/942176) and created /etc/docker/daemon.json with the following contents:

`{
  "bip": "10.200.0.1/24",
  "default-address-pools":[
    {"base":"10.201.0.0/16","size":24},
    {"base":"10.202.0.0/16","size":24}
  ]
}`

This should increase the Docker network limit by the hundreds, if I understand correctly, yet Lando does not seem to be aware of this because it is still complaining about the Docker network limit. Is there anything else I can try to increase my network limit? Or is this a limitation of Lando?

**Comment by jerome-pilotin** [comment]
We are using lots of Lando sites for development purposes with a small team, and we are hitting this issue consistently.
I have followed the same suggestions, but the situation hasn't changed. The bridge network doesn't seem to be respecting this.

Does anyone have an idea to fix this issue?

**Comment by Mgrmjp** [comment]
Anything regarding this?
