### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by blue928** [lando/lando#3086]
I recently got a new Apple Macbook with an M1 chip. I already had Docker 3.5.2.18 installed (latest version as of 7.23.2021) but paid special attention to the "Use our version or YMMV" Warning.

When trying to stay true to the officially supported Docker version packaged with 3.1.4, I get the following error:

```
Incompatible CPU detected

We are sorry, but your hardware is incompatible with Docker Desktop.

This version of Docker Desktop requires an Intel processor.

To learn more about this issue see:

https://docs.docker.com/go/apple-silicon
```

I upgraded back to the Docker version I had installed and quickly started to experience the errors in this issue: #3075

Our company will purchase all M1 chips the next go around and get rid of all Intel. We're a Lando dev group and would like this to work out of the box. Can we please get an officially supported version for M1 so that it works out of the box?

In the meantime, is the solution to follow the advice in the other issue and "uncheck composer v 2.x?" If we go this route, what other "gotchas" might we experience?

Thanks!

**Comment by vincenttush** [comment]
https://www.techboardz.com/gs-bank-usa-credit-card/ Apple Pay and Apple support

**Comment by arnoldski** [comment]
I'm experiencing the same issue as described here: "Fatal Error: Out of memory on new M1 Chip" [https://github.com/docksal/docksal/issues/1501](url).

```
appserver_1  | mmap() failed: [12] Cannot allocate memory
appserver_1  |
appserver_1  | mmap() failed: [12] Cannot allocate memory
appserver_1  | [Fri Aug 06 08:40:36.090230 2021] [php7:error] [pid 5037] [client 172.20.0.2:54184] PHP Fatal error:  Out of memory (allocated 8482816) (tried to allocate 4282056 bytes) in /app/web/includes/common.inc on line 1010
```

I've already increased the memory of Docker and set the `memory_limit = -1` in php.

I'm using a Drupal 7 recipe.
Does anybody has an idea or (temp) solution?

Thanks!

**Comment by pirog** [comment]
@blue928 we plan to support M1 but this is still a few months out. In the meantime we recommend that M1 users replace their current version of Docker Desktop with the Apple Silicon verison: https://docs.docker.com/desktop/mac/apple-silicon/

**Comment by ryanoc1** [comment]
Hi, I can't get the software installed. I have tried installing the silicon version of docker desktop and the lando installer detects it, but later on in the installation process it says that it is incompatible with docker desktop for mac because lando only works for Intel processors.

**Comment by MWals** [comment]
I wanted to kindly ask if there is any update on this topic? We would love to use Lando but currently have to work without it unfortunately. Lando helps us a lot and we appreciate your work, would be great to use it on our new machines.

**Comment by pirog** [comment]
We have been slowly rolling out M1 support but there probably won’t be
UNIVERSAL support until we release Lando 4 early next year.

**Comment by ryanoc1** [comment]
@MWals I have been using it in production, though I don't know if I would call it "production ready". There are a few important things which got it working for me on Monterey:

1. Install docker silicon version for m1. Then install lando. Then you may need to install docker silicon for m1 again (verify docker version).
2. Mac OS System Preferences -> Security -> Privacy -> Full Disk Access -> Unlock and Untick "Docker".
3. Docker Preferences -> Resources -> File Sharing -> Add `/run/host-services/ssh-auth.sock` to the list.
4. Composer v1 is always used even if composer v2 is specified in lando.yml. I can't figure out why. If you're using composer v2 then simply do a `lando composer selfupdate` if you see any error related to this.

**Comment by imyaro** [comment]
Thank you @ryanoc1 , it works for me, but it seems that lando still has some problems with M1 chip.
After implementing all points, I have ~90% of CPU used by Docker app, my laptop became hot in a minute

I guess it happens because lando forces to build images using x86-64 architecture, but my guess could be wrong.

**Comment by ryanoc1** [comment]
@imyaro Interesting. I assume you completely closed docker and restarted it, or at least restarted the host? If so, are you able to determine which container has the high cpu? And perhaps drill down into its processes to see what is going on?

**Comment by apotek** [comment]
Using lando 3.6.0 on an M1 mac with Docker Desktop 4.3.1. 

I am successfully running several lando projects, drupal8, drupal9, pantheon based drupal, java development, wordpress. 

The only issue I ran into was that the old pantheon redis recipe was using a very old version of redis which died on an M1. That can be overridden in .lando.local.yml. Also, a fix for that particular issue is in lando 3.6.2.

So, to me lando is working absolutely fine on M1, and I am not even using 3.6.2.

**Comment by maxmaric** [comment]
It does work, but it is painfully slow.

The reason is usage of mysql and mariadb bitnami containers which are AMD64 and not ARM64!
https://github.com/bitnami/charts/issues/7305

**Comment by seanr** [comment]
We're running into issues more with dated front-end stuff on older sites, but I've also seen odd behavior I just can't pin down, like one M1 user getting an error that seems to indicate it's attempting to install PHP 8 instead of 7.4. Strange stuff all around (though the FE stuff can be resolved with some effort on our side).

**Comment by awm086** [comment]
I'd love to contribute to this. I was able to override the image with mariadb compatible with arm64 not the bitnami one. But I'm not sure if I'm opening myself up for some issue. I'd love to be able to just tell Lando to use the official mariadb image instead of bitnamo. `type: mariadb-official` without having to do my own overrides.      
Or use the oracle MySQL image which supports arm64 architecture. Bitnami isn't making any progress on armification of their images and it's prudent to start looking elsewhere.

**Comment by lefte** [comment]
_(See also issue_ #2688 _for possible workarounds)_

**Comment by CodeBrauer** [comment]
Has anyone successfully run `lando` on macOS 12.6+ (Monterey) with Docker Desktop v4.15.0+?

I'm currently [working with a very heavy workaround myself](https://github.com/lando/lando/issues/2688#issuecomment-1330909083), so I can develop the projects further. Sad to see there is currently no real approach to get M1 going. I tried myself fixing it, but I lack certain knowledge about Landos architecture of for contributing a PR.

I would be happy to give you tips on how to get `lando` working with the current Docker Desktop version under M1/M2.

**Comment by ccharlton** [comment]
Old ticket?

**Comment by reynoldsalec** [comment]
Yeah @ccharlton, most relevant update here is that we'll be redoing all the services using the new Lando 4 service layer when that's finished in the next couple months. That will move us entirely off of Bitnami images and onto images that have ARM-native versions. It'll also make it a hell of a lot easier to use your own images.

For now, highly recommend trying the "Use Rosetta for x86/amd64 emulation on Apple Silicon" in the "Features in Development" section of your Docker Desktop settings if you have critical errors related to ARM support; that's resolved at least one compatibility issue for me.

Going to close this out in favor of #2688 as the main ARM support ticket.
