### ISSUE TITLE
Add a flag to rebuild without rebuilding services

### ISSUE THREAD

**Issue by ledburyb** [lando/lando#3104]
**Please explain your request and its importance in the form of a user story.**
As a lando user writing tooling I want to be able to quickly make and test changes to parts of the config and the environment without waiting for services to rebuild when I know they don't need to. In my current project a full rebuild takes ~2 minutes each time.

**Please provide some detail on how lando can help solve this problem**
Adding a flag such as `--config-only` or `--skip-services` would allow me to update just the lando config.

**Comment by pirog** [comment]
@ledburyb you shouldnt need to rebuild to test tooling changes. at least i never do.

**Comment by ledburyb** [comment]
@pirog Yes, looks like that is the case. The environment variable changes are still time consuming though.

**Comment by pirog** [comment]
@ledburyb you can configure tooling commands to use their own envvars. this also does not require a rebuild.

for the deeper concern here we dont plan on supporting either of these flags, our plan is to provide more granular build caching so lando will only rebuild things that have changed and their dependencies. this should drastically reduce `lando rebuild` times for the use case you are describing.
