### ISSUE TITLE
platform.sh local database not accessible

### ISSUE THREAD

**Issue by mttkng** [lando/lando#3111]
After spinning up a local platform.sh project the database service is unreachable. I’ve tried this on a couple of different projects, both of which prior to today worked fine. And attempt to connect via `lando database` results in `ERROR 2002 (HY000): Can't connect to MySQL server on 'db'`. This from `lando logs -s db`;

```db_1          | userperms 17:20:47.28 INFO  ==> Symlinked users .gitconfig.
db_1          | userperms 17:20:47.28 INFO  ==> Symlinked users known_hosts
db_1          | userperms 17:20:47.29 INFO  ==> This is a debian container
db_1          | userperms 17:20:47.29 INFO  ==> user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
db_1          | userperms 17:20:47.29 DEBUG ==> Lando ENVVARS set at
db_1          | userperms 17:20:47.29 DEBUG ==> 
db_1          | userperms 17:20:47.30 DEBUG ==> ========================================
db_1          | userperms 17:20:47.30 DEBUG ==> LANDO_WEBROOT_USER      : app
db_1          | userperms 17:20:47.30 DEBUG ==> LANDO_WEBROOT_GROUP     : app
db_1          | userperms 17:20:47.30 DEBUG ==> LANDO_WEBROOT_UID       : 1000
db_1          | userperms 17:20:47.30 DEBUG ==> LANDO_WEBROOT_GID       : 1000
db_1          | userperms 17:20:47.30 DEBUG ==> LANDO_HOST_UID          : 502
db_1          | userperms 17:20:47.31 DEBUG ==> LANDO_HOST_GID          : 20
db_1          | userperms 17:20:47.31 DEBUG ==> ========================================
db_1          | userperms 17:20:47.31 DEBUG ==> 
db_1          | userperms 17:20:47.32 INFO  ==> Making sure correct user:group (app:app) exists...
db_1          | userperms 17:20:47.36 INFO  ==> Remapping ownership to handle docker volume sharing...
db_1          | userperms 17:20:47.36 INFO  ==> Resetting app:app from 1000:1000 to 502:20
db_1          | userperms 17:20:47.47 INFO  ==> app:app is now running as uid=502(app) gid=20(dialout) groups=20(dialout),1000(app)!
db_1          | userperms 17:20:47.47 INFO  ==> And here. we. go.
db_1          | userperms 17:20:47.48 INFO  ==> Doing the permission sweep.
db_1          | loadkeys 17:20:47.59 INFO  ==> Scanning /lando/keys for keys...
db_1          | loadkeys 17:20:47.61 INFO  ==> Scanning /var/www/.ssh for keys...
db_1          | loadkeys 17:20:47.62 INFO  ==> Scanning /user/.ssh for keys...
db_1          | loadkeys 17:20:47.63 INFO  ==> Found keys /lando/keys/platformsh.lando.id_rsa /lando/keys/platformsh.lando.id_rsa-cert /user/.ssh/config /user/.ssh/config.bak /user/.ssh/id_rsa
db_1          | loadkeys 17:20:47.64 DEBUG ==> Ensuring permissions and ownership of /lando/keys/platformsh.lando.id_rsa...
db_1          | loadkeys 17:20:47.66 DEBUG ==> Checking whether /lando/keys/platformsh.lando.id_rsa is a private key...
db_1          | loadkeys 17:20:47.67 DEBUG ==> Checking whether /lando/keys/platformsh.lando.id_rsa is formatted correctly...
db_1          | loadkeys 17:20:47.72 DEBUG ==> Ensuring permissions and ownership of /lando/keys/platformsh.lando.id_rsa-cert...
db_1          | loadkeys 17:20:47.75 DEBUG ==> Checking whether /lando/keys/platformsh.lando.id_rsa-cert is a private key...
db_1          | loadkeys 17:20:47.76 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/config...
db_1          | loadkeys 17:20:47.78 DEBUG ==> Checking whether /user/.ssh/config is a private key...
db_1          | loadkeys 17:20:47.79 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/config.bak...
db_1          | loadkeys 17:20:47.81 DEBUG ==> Checking whether /user/.ssh/config.bak is a private key...
db_1          | loadkeys 17:20:47.82 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/id_rsa...
db_1          | loadkeys 17:20:47.85 DEBUG ==> Checking whether /user/.ssh/id_rsa is a private key...
db_1          | loadkeys 17:20:47.86 DEBUG ==> Checking whether /user/.ssh/id_rsa is formatted correctly...
db_1          | loadkeys 17:20:47.88 INFO  ==> Using the following keys: /lando/keys/platformsh.lando.id_rsa /user/.ssh/id_rsa
db_1          | platformsh-prepare 17:20:47.92 INFO  ==> Ensuring needed files are unmounted...
db_1          | /dev/vda1 on /etc/hosts type ext4 (rw,relatime)
db_1          | platformsh-prepare 17:20:48.00 INFO  ==> unmounted /etc/hosts
db_1          | /dev/vda1 on /etc/resolv.conf type ext4 (rw,relatime)
db_1          | platformsh-prepare 17:20:48.01 INFO  ==> unmounted /etc/resolv.conf
db_1          | platformsh-prepare 17:20:48.02 INFO  ==> Ensuring needed directories exist...
db_1          | platformsh-prepare 17:20:48.07 DEBUG ==> Waiting for /run/shared/agent.sock to be ready...
db_1          | platformsh-prepare 17:20:49.08 DEBUG ==> Waiting for /run/shared/agent.sock to be ready...
db_1          | 2021-08-23 17:20:50,660 platformsh.agent DEBUG Running: /etc/platform/boot
db_1          | 2021-08-23 17:20:51,914 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
db_1          | 2021-08-23 17:20:52,111 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
db_1          | 2021-08-23 17:20:53,784 platformsh.agent.service INFO Booting container.
db_1          | runsv mysql-standalone: fatal: supervise/control exists but is not a fifo
db_1          | runsv mysql-cluster: fatal: supervise/control exists but is not a fifo
db_1          | runsv mysql-failure: fatal: supervise/control exists but is not a fifo
db_1          | runsv idmapd: fatal: supervise/control exists but is not a fifo
db_1          | Generating public/private rsa key pair.
db_1          | Your identification has been saved in /run/rsa_hostkey.
db_1          | Your public key has been saved in /run/rsa_hostkey.pub.
db_1          | The key fingerprint is:
db_1          | SHA256:YHbpQzIRcAYzJVC8BS1MoKSMk4Q5glUF6BxJTrDt1Po host
db_1          | The key's randomart image is:
db_1          | +---[RSA 2048]----+
db_1          | |+B*@%OB.         |
db_1          | |%B+.+*o. .       |
db_1          | |O=+..+* +        |
db_1          | | +o..o B         |
db_1          | |  o     S        |
db_1          | |   .     .       |
db_1          | |    E            |
db_1          | |                 |
db_1          | |                 |
db_1          | +----[SHA256]-----+
db_1          | 2021-08-23 17:20:54,800 platformsh.agent DEBUG Finished: /etc/platform/boot
db_1          | lando 17:20:55.02 INFO  ==> Lando handing off to: exec init
db_1          | runsv mysql-failure: fatal: supervise/control exists but is not a fifo
db_1          | runsv mysql-standalone: fatal: supervise/control exists but is not a fifo
db_1          | runsv mysql-cluster: fatal: supervise/control exists but is not a fifo
db_1          | runsv idmapd: fatal: supervise/control exists but is not a fifo
db_1          | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1          | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1          | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1          | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1          | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
```

**Comment by Boosmith** [comment]
I am also getting this problem, starting from a blank project and using the Drupal8 Platform.sh template.

**Comment by ejdunn2001** [comment]
Me too. 
╰─ lando database                                                                                                                                                                ─╯
ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)
`lando pull` gets me
`Verifying your current project...
Verified project id: jtl4tgc2ugdgi
Verifying labaids-35 is an active environment...
Branch labaids-35 is inactive... using the parent environment (master) instead
Verified the master environment is active
Verifying your ssh keys work are deployed to the project...
ERROR 2003 (HY000): Can't connect to MySQL server on 'db' (111 "Connection refused")
Destroying all current tables in database if needed...
Importing data from the database relationship into the main schema...
ERROR 2003 (HY000): Can't connect to MySQL server on 'db' (111 "Connection refused")`

`lando log -s db` gets me
`db_1     | ===============================================================
db_1     |
db_1     |
db_1     | userperms 12:46:48.27 INFO  ==> Symlinked users .gitconfig.
db_1     | userperms 12:46:48.28 INFO  ==> Symlinked users known_hosts
db_1     | userperms 12:46:48.28 INFO  ==> This is a debian container
db_1     | userperms 12:46:48.29 INFO  ==> user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
db_1     | userperms 12:46:48.29 DEBUG ==> Lando ENVVARS set at
db_1     | userperms 12:46:48.30 DEBUG ==>
db_1     | userperms 12:46:48.30 DEBUG ==> ========================================
db_1     | userperms 12:46:48.30 DEBUG ==> LANDO_WEBROOT_USER      : app
db_1     | userperms 12:46:48.30 DEBUG ==> LANDO_WEBROOT_GROUP     : app
db_1     | userperms 12:46:48.30 DEBUG ==> LANDO_WEBROOT_UID       : 1000
db_1     | userperms 12:46:48.31 DEBUG ==> LANDO_WEBROOT_GID       : 1000
db_1     | userperms 12:46:48.31 DEBUG ==> LANDO_HOST_UID          : 501
db_1     | userperms 12:46:48.31 DEBUG ==> LANDO_HOST_GID          : 20
db_1     | userperms 12:46:48.31 DEBUG ==> ========================================
db_1     | userperms 12:46:48.31 DEBUG ==>
db_1     | userperms 12:46:48.31 INFO  ==> Making sure correct user:group (app:app) exists...
db_1     | userperms 12:46:48.49 INFO  ==> Remapping ownership to handle docker volume sharing...
db_1     | userperms 12:46:48.49 INFO  ==> Resetting app:app from 1000:1000 to 501:20
db_1     | userperms 12:46:49.06 INFO  ==> app:app is now running as uid=501(app) gid=20(dialout) groups=20(dialout),1000(app)!
db_1     | userperms 12:46:49.06 INFO  ==> And here. we. go.
db_1     | userperms 12:46:49.06 INFO  ==> Doing the permission sweep.
db_1     | loadkeys 12:46:49.14 INFO  ==> Scanning /lando/keys for keys...
db_1     | loadkeys 12:46:49.15 INFO  ==> Scanning /var/www/.ssh for keys...
db_1     | loadkeys 12:46:49.16 INFO  ==> Scanning /user/.ssh for keys...
db_1     | loadkeys 12:46:49.17 INFO  ==> Found keys /user/.ssh/.DS_Store /user/.ssh/config /user/.ssh/config.bak /user/.ssh/environment-Edmund’s MacBook Pro /user/.ssh/id_rsa /user/.ssh/known_hosts.old
db_1     | loadkeys 12:46:49.17 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/.DS_Store...
db_1     | loadkeys 12:46:49.20 DEBUG ==> Checking whether /user/.ssh/.DS_Store is a private key...
db_1     | loadkeys 12:46:49.20 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/config...
db_1     | loadkeys 12:46:49.25 DEBUG ==> Checking whether /user/.ssh/config is a private key...
db_1     | loadkeys 12:46:49.26 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/config.bak...
db_1     | loadkeys 12:46:49.29 DEBUG ==> Checking whether /user/.ssh/config.bak is a private key...
db_1     | loadkeys 12:46:49.30 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/environment-Edmund’s MacBook Pro...
db_1     | loadkeys 12:46:49.34 DEBUG ==> Checking whether /user/.ssh/environment-Edmund’s MacBook Pro is a private key...
db_1     | loadkeys 12:46:49.35 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/id_rsa...
db_1     | loadkeys 12:46:49.38 DEBUG ==> Checking whether /user/.ssh/id_rsa is a private key...
db_1     | loadkeys 12:46:49.39 DEBUG ==> Checking whether /user/.ssh/id_rsa is formatted correctly...
db_1     | loadkeys 12:46:49.41 DEBUG ==> Ensuring permissions and ownership of /user/.ssh/known_hosts.old...
db_1     | loadkeys 12:46:49.44 DEBUG ==> Checking whether /user/.ssh/known_hosts.old is a private key...
db_1     | loadkeys 12:46:49.45 INFO  ==> Using the following keys: /user/.ssh/id_rsa
db_1     | platformsh-prepare 12:46:49.47 INFO  ==> Ensuring needed files are unmounted...
db_1     | /dev/vda1 on /etc/hosts type ext4 (rw,relatime)
db_1     | platformsh-prepare 12:46:49.48 INFO  ==> unmounted /etc/hosts
db_1     | /dev/vda1 on /etc/resolv.conf type ext4 (rw,relatime)
db_1     | platformsh-prepare 12:46:49.50 INFO  ==> unmounted /etc/resolv.conf
db_1     | platformsh-prepare 12:46:49.50 INFO  ==> Ensuring needed directories exist...
db_1     | platformsh-prepare 12:46:49.88 DEBUG ==> Waiting for /run/shared/agent.sock to be ready...
db_1     | platformsh-prepare 12:46:50.89 DEBUG ==> Waiting for /run/shared/agent.sock to be ready...
db_1     | 2021-08-24 12:46:52,421 platformsh.agent DEBUG Running: /etc/platform/boot
db_1     | 2021-08-24 12:46:53,327 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
db_1     | 2021-08-24 12:46:53,376 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
db_1     | 2021-08-24 12:46:54,117 platformsh.agent.service INFO Booting container.
db_1     | Generating public/private rsa key pair.
db_1     | Your identification has been saved in /run/rsa_hostkey.
db_1     | Your public key has been saved in /run/rsa_hostkey.pub.
db_1     | The key fingerprint is:
db_1     | SHA256:7G2DgRe62abqekGSUWA5Ug2WcOWshr8vOHRjq8GxzZU host
db_1     | The key's randomart image is:
db_1     | +---[RSA 2048]----+
db_1     | |.oBOo            |
db_1     | |.+=o.            |
db_1     | | . +o   .        |
db_1     | | .o.. .+ .       |
db_1     | |..oo Eo S        |
db_1     | |.+=+o  * +       |
db_1     | |.=+oo.o = +      |
db_1     | |o oo.  o . .     |
db_1     | | o+*+..          |
db_1     | +----[SHA256]-----+
db_1     | 2021-08-24 12:46:54,572 platformsh.agent DEBUG Finished: /etc/platform/boot
db_1     | lando 12:46:54.65 INFO  ==> Lando handing off to: exec init
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist
db_1     | runsvdir /etc/service: warning: unabl`

**Comment by jasonevines** [comment]
I am getting a similar problem:

`db_1       | runsv mysql-cluster: fatal: supervise/control exists but is not a fifo
db_1       | runsv mysql-standalone: fatal: supervise/control exists but is not a fifo
db_1       | runsv mysql-failure: fatal: supervise/control exists but is not a fifo
db_1       | runsv idmapd: fatal: supervise/control exists but is not a fifo
db_1       | platformsh-prepare 13:29:35.81 DEBUG ==> Waiting for /run/shared/agent.sock to be ready...
db_1       | runsv mysql-standalone: fatal: supervise/control exists but is not a fifo
db_1       | runsv mysql-failure: fatal: supervise/control exists but is not a fifo
db_1       | runsv mysql-cluster: fatal: supervise/control exists but is not a fifo
db_1       | runsv idmapd: fatal: supervise/control exists but is not a fifo
db_1       | 2021-08-24 13:29:36,985 platformsh.agent DEBUG Running: /etc/platform/start
db_1       | 2021-08-24 13:29:37,397 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
db_1       | 2021-08-24 13:29:37,419 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
db_1       | 2021-08-24 13:29:37,743 platformsh.agent.service INFO Calling legacy boot_start_services (non-state-aware container)
db_1       | 2021-08-24 13:29:37,743 platformsh.agent.service INFO Setting up left-most instance cluster
db_1       | 2021-08-24 13:29:37,818 platformsh.agent.util DEBUG Failed to connect to bus: No such file or directory
db_1       |
db_1       | 2021-08-24 13:29:37,818 platformsh.agent ERROR Error in service config.py:
db_1       | Traceback (most recent call last):
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/__init__.py", line 28, in log_and_load
db_1       |     yield load()
db_1       |   File "/etc/platform/start", line 6, in <module>
db_1       |     service.start()
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 286, in start
db_1       |     self.boot_start_services()
db_1       |   File "/etc/platform/config.py", line 707, in boot_start_services
db_1       |     super(StateAwareService, self).boot_start_services()
db_1       |   File "/etc/platform/config.py", line 167, in boot_start_services
db_1       |     self.service_start("mysql-standalone")
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 222, in service_start
db_1       |     check_call(["systemctl", "start", service])
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/util.py", line 173, in check_call
db_1       |     raise subprocess.CalledProcessError(returncode=proc.returncode, cmd=cmd)
db_1       | CalledProcessError: Command '['systemctl', 'start', 'mysql-standalone']' returned non-zero exit status 1
db_1       | Traceback (most recent call last):
db_1       |   File "/etc/platform/start", line 6, in <module>
db_1       |     service.start()
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 286, in start
db_1       |     self.boot_start_services()
db_1       |   File "/etc/platform/config.py", line 707, in boot_start_services
db_1       |     super(StateAwareService, self).boot_start_services()
db_1       |   File "/etc/platform/config.py", line 167, in boot_start_services
db_1       |     self.service_start("mysql-standalone")
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 222, in service_start
db_1       |     check_call(["systemctl", "start", service])
db_1       |   File "/usr/lib/python2.7/dist-packages/platformsh/agent/util.py", line 173, in check_call
db_1       |     raise subprocess.CalledProcessError(returncode=proc.returncode, cmd=cmd)
db_1       | subprocess.CalledProcessError: Command '['systemctl', 'start', 'mysql-standalone']' returned non-zero exit status 1
db_1       | run-parts: /scripts/001-boot-platformsh exited with return code 1`

**Comment by xaqrox** [comment]
Just here to confirm I'm seeing the same error at the end of `lando log -s db` for two platform projects.

```
runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist

**Comment by pirog** [comment]
@xaqrox the fatals above those warnings might actually be the issue:

```
db_1          | runsv mysql-failure: fatal: supervise/control exists but is not a fifo
db_1          | runsv mysql-standalone: fatal: supervise/control exists but is not a fifo
db_1          | runsv mysql-cluster: fatal: supervise/control exists but is not a fifo
db_1          | runsv idmapd: fatal: supervise/control exists but is not a fifo
```

**Comment by pirog** [comment]
Platform.sh reverted the docker images to an earlier state and that seemed to get me back on the righteous path after a `lando rebuild`. For another project i had to do a `lando destroy && lando rebuild`.
