### ISSUE TITLE
recipe LAMP : php version 8 is not supported

### ISSUE THREAD

**Issue by stloc** [lando/lando#3116]
contrary to what is written https://docs.lando.dev/config/php.html#supported-versions
I have the message 

![image](https://user-images.githubusercontent.com/4832070/130748248-59bd147f-2b7f-486e-a6e5-842fb7a10f55.png)

**Comment by pirog** [comment]
what is written is "8.0" not "8"

**Comment by stloc** [comment]
Yet `php: 7.4` works and `php: 8.0` not.
But you are right for `php: "8.0"`. OK thanks

**Comment by pirog** [comment]
@stloc `php: 7.4` gets parsed by javascript into float `7.4` so you are good there, `php: 8.0` gets parsed by javascript into integer `8` so thats the issue. this is a weird quirk between the YAML spec and javascript. regardless, versions should always be strings anyway so its a good practice to always wrap them in quotes.

**Comment by cabagach** [comment]
On the PHP documentation page https://docs.lando.dev/config/php.html#supported-versions the examples are using services. To make it easier for people, how about showing the simplest way, i.e. something like this?

```
config:
  php: "8.1"
```

**Comment by cabagach** [comment]
I have created [#166](https://github.com/lando/docs/pull/166).

**Comment by pirog** [comment]
@cabagach `config` is a _recipe_ thing so its not going to work for configuring a `php` service, which is what that docs page is all about.

**Comment by cabagach** [comment]
Ah yes, sorry @pirog you're right. It's just because whenever I need to set the PHP version, I end up on that page after doing a search: https://duckduckgo.com/?q=lando+php

Setting PHP version is actually already documented under the individual recipes, see for example https://docs.lando.dev/config/drupal9.html#configuration.

Could PHP version be added as an optional parameter of `lando init`? Like this:

```
lando init --source cwd --php 8.1 --recipe drupal9 --webroot web --name drupal9
```

**Comment by pirog** [comment]
You can use the —option flag to set recipe config on lando init.

**Comment by cabagach** [comment]
Thanks, that's awesome! This worked perfectly:

`lando init --source cwd --option php='8.1' --recipe drupal9 --webroot web --name drupal9`

Resulting `.lando.yml`:

```yaml
name: drupal9
recipe: drupal9
config:
  webroot: web
  php: '8.1'
```

**Comment by cabagach** [comment]
I was experimenting with setting both PHP and MySQL to version 8 and this works fine:
```
lando init --source cwd --option php='8.1' --option database=mysql:8.0 --recipe drupal9 --webroot web --name drupal9
```

Resulting `.lando.yml`:
```
name: drupal9
recipe: drupal9
config:
  webroot: web
  php: '8.1'
  database: 'mysql:8.0'
```
