### ISSUE TITLE
bad CPU type in executable

### ISSUE THREAD

**Issue by developh** [lando/lando#3121]
After I installed v3.3.0 I am start getting this issue `zsh: bad CPU type in executable: lando`  on any command, my mac version is 11.5.2 (macOS big Sur)

**Comment by protitude** [comment]
I'm not sure if you made the same mistake as I did, but there are two MacOS versions now. I accidentally grabbed the arm version and got that same error.

I think it would be helpful to add some sort of test in the installer to detect the wrong CPU type and fail.

**Comment by developh** [comment]
Thanks @protitude same mistake, I used another file and it works fine now.
