### ISSUE TITLE
Running lando from source

### ISSUE THREAD

**Issue by alebon** [lando/lando#3122]
I am using lando on NixOS. For version 3.1.4 I am able to run it from source, as described in the documentation. Unfortunately in the latest version 3.3.0 the bin folder is gone, so I am not sure where to find it or how to build the project so I have an executable file as before?

**Comment by uberhacker** [comment]
See https://github.com/lando/lando/pull/3115.

**Comment by alebon** [comment]
Nice, thanks!

**Comment by tobias-kuendig** [comment]
I'm currently working on packaging the lando/cli beta for NixOS: https://github.com/NixOS/nixpkgs/pull/295413
