### ISSUE TITLE
Lando totally not working on Mac OS 11.5.2

### ISSUE THREAD

**Issue by EternallLight** [lando/lando#3127]
Hello 👋🏻

I've found it impossible to get started with the latest Lando (3.3.0) on the latest Mac OS.

Whichever `lando` command I type, including `lando version`, it exists immediately with no output. 

I tried re-installing it several times, removed my local Docker installation to let Lando install what it needs, but none of it helped. This can be reproduced on both my of Mac machines, which are iMac 2017 and Macbook Pro 16" 2019. Both of them run the latest version of Mac OS Big Sur. 

If I try to run `lando` with sudo, it says `Lando should never ever ever be run as root...`, which is the only output I could get from Lando. 

Would you mind taking a look at this?

**Comment by mieg** [comment]
did you use the right binary? There are now 2 .dmg files, one for macs with the new M1 chip, and one for 'old' x86 macs.

**Comment by EternallLight** [comment]
I used that one has no `arm` in name – https://github.com/lando/lando/releases/download/v3.3.0/lando-x64-v3.3.0.dmg
But, the previous version (that had no arm dmg) doesn't work for me, either.

**Comment by dsuurlant** [comment]
Following this since I am currently working with Big Sur `11.4` and I don't want to upgrade if it breaks Lando! Can anyone else confirm it breaks on `11.5`?

**Comment by spuky** [comment]
@dsuurlant using lando on 11.5 with no problems...

**Comment by mieg** [comment]
Using lando-x64-v3.3.2.dmg on 11.6 without any problems.

**Comment by campaignupgrade** [comment]
I had the same issue and it was also due to pulling the first dmg I saw. 

`arm` and `x64` didn't immediately mean anything to me. `m1` and `intel` would make more sense to a Mac user, but would break from the naming format used on the other OS.

**Comment by brandonferens** [comment]
This is the exact same issue I am facing.
- 2018 MacBook Pro running macOS 11.4
- lando-x64-v3.4.1.dmg

**Comment by dekisha** [comment]
I'm experiencing the same issue with Linux:

- Operating System: LMDE 3 (cindy)
- Kernel: Linux 4.9.0-17-amd64
- Architecture: x86-64

while trying to install lando-x64-stable.deb

Any suggestions on this?

**Comment by campaignupgrade** [comment]
@dekisha I suspect you'll want to open a different ticket for this since it's not a MacOS issue. You'll also want to add detailed of what you tried and the error messages present. 

You can also try the Lando Slack channel for ad-hoc support.

**Comment by reynoldsalec** [comment]
In the absence of a replication pathway I'm going to close this out; if you have this problem...

1. Double-check you have the correct Lando binary for your Mac architecture (lando-x64 for Intel computers, lando-arm64 for M1 chips)
2. Consider going to the [Lando Slack](https://launchpass.com/devwithlando) to see if someone might be able to help you live debug.

Thousands of people are using Lando on Macs each day, so issues of this nature are likely an edge case resulting from specific differences in the configuration of your Mac. Would love to figure out what causes it though, so definitely join Slack so we can try to replicate/get more info!
