### ISSUE TITLE
docker-compose could not be located! | 3.3.1

### ISSUE THREAD

**Issue by Prem-Patel** [lando/lando#3132]

**Comment by RicLeP** [comment]
Same for me. Running Windows 11.

**Comment by AaronFeledy** [comment]
@pirog Yep, just moments ago. Digging into it now.

**Comment by pirog** [comment]
@AaronFeledy k, let me know what you find and perhaps i can do another hotfix

**Comment by AaronFeledy** [comment]
This seems to be an upstream issue with the Docker installer. What's happening is that the Docker Desktop installer removes the old version of Docker, but then fails to complete the installation of the new version without throwing any errors. This is true for the installer packaged with Lando as well as the installer downloaded from Docker's website. This only seems to happen when updating Docker. A fresh install worked fine for me. There are dozens of open tickets in Docker's issue queue about this for Docker Desktop 3.6 and 4.0, so this issue has yet to be fixed on their end.

The workaround for me was to uninstall Docker, then run the Lando installer again.

**Comment by pirog** [comment]
@AaronFeledy AWESOME!

IIRC in the Lando installer you can customize the installation and choose NOT to install Docker. That might be a good workaround for people who already have Docker.

**Comment by doodirock** [comment]
Same issue here.  I installed Docker separately, but the same issue occurs.

**Comment by doodirock** [comment]
Reverted to previous install but now getting errors:

`docker-credential-desktop not installed or not available in PATH`

**Comment by AaronFeledy** [comment]
Try this:
1. Right click your start button and click `run`
2. Type `start services.msc` in the Run dialog to open the Services manager
2. Ensure `Docker Desktop Service` is not running. Stop it if it is.
3. Uninstall Docker
3. Right click your start button and click `run`
4. Type `regedit` to open the registry editor
5. Remove the `Docker Desktop` key from the Windows Registry under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` if it exists.
4. Reboot
5. Run latest Lando installer including the Docker install

**Comment by doodirock** [comment]
> Try this:
> 
> 1. Right click your start button and click `run`
> 2. Type `start services.msc` in the Run dialog to open the Services manager
> 3. Ensure `Docker Desktop Service` is not running. Stop it if it is.
> 4. Uninstall Docker
> 5. Right click your start button and click `run`
> 6. Type `regedit` to open the registry editor
> 7. Remove the `Docker Desktop` key from the Windows Registry under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` if it exists.
> 8. Reboot
> 9. Run latest Lando installer including the Docker install

Worked perfectly.  I'm now running the latest version and fully up to date.  Thank you for all the help and such a great project!
