### ISSUE TITLE
Lando-specific .htaccess-lando file does not override default .htaccess

### ISSUE THREAD

**Issue by thafner** [lando/lando#3135]
It appears that https://github.com/lando/lando/issues/999 got reverted somehow? 

On v3.3.1 MacOS 11.5.2, I added a http -> https .htaccess redirect.  When I copy my .htaccess into .htaccess-lando and remove the undesired section, nothing occurs and the https redirect is still in place.  I do not have any custom httpd.conf files and only use lando defaults for apache settings.

**Comment by reynoldsalec** [comment]
This is still an issue, but moving the convo over to https://github.com/lando/lando/issues/2277. Thanks!
