### ISSUE TITLE
Lando SSH key validation failed | 3.3.1

### ISSUE THREAD

**Issue by orlandoayeras** [lando/lando#3136]
We have a couple of customers having an issue with SSH key validation (including us from the team) after updating to 3.3.1 when running `lando init` or `lando init -source pantheon` command. Here's what we are seeing from the error,

`POST request to users/pantheonuserid/keys failed with code 400: Bad Request. The server responded with the message SSH validation failed: Unknown SSH key type '"ssh-rsa'.`

I am guessing it could be a bad code from that key type, the double-quote before ssh-rsa. Has anyone experienced this too?

I attached an image also. Thanks!
![image](https://user-images.githubusercontent.com/77082837/132923792-54bc421a-5559-4e70-993a-a7c09c8aecce.png)

**Comment by orlandoayeras** [comment]
Just a quick note, this happens on Linux and macOS.

**Comment by pirog** [comment]
@orlandoayeras turns out this came from a small version bump in an upstream dependency. looks like they also just fixed this a few days ago so rolling a hotfix release that includes their hotfix release.

**Comment by pirog** [comment]
https://github.com/lando/lando/releases/tag/v3.3.2

**Comment by orlandoayeras** [comment]
Thanks, @pirog! I Will relay this to our team and customers. Really appreciate the quick action!

**Comment by orlandoayeras** [comment]
I think this is already resolved with the latest release. I'll be closing this now. Thank you a lot, team!
