### ISSUE TITLE
Update warning is no longer shown after switching release channel from "stable" to "none" then back to "stable"

### ISSUE THREAD

**Issue by jaybeaton** [lando/lando#3140]
When running a Lando command, I received the "Update Available" warning; but I'm not able to update right now.  After reading the [Release Channels documentation](https://docs.lando.dev/config/releases.html#release-channels), I was considering writing a script to "sleep" the warning for a period of time by switching the channel to "none" and then back to "stable" after a day or so.

I experimented with manually changing the release channel by trying:

1. Run Lando "version" command with my current channel setting (stable), see "Update Available" message **(as expected)**.
2. Change channel to "none".
3. Run Lando "version" command, see no update message **(as expected)**.
4. Change channel back to "stable".
5. Run Lando "version" command, see no update message. **Not expected!**

Full output is below.

Is this how it is expected to work?  I expected the update message to start displaying again when I switched back to the "stable" channel.

If this is the expected behavior, when will it notify me of a new available release again?  After a period of time?  If so, how long?  When the *next* release comes out?

```
$ lando version

  __  __        __     __        ___            _ __     __   __    ______
 / / / /__  ___/ /__ _/ /____   / _ |_  _____ _(_) /__ _/ /  / /__ / / / /
/ /_/ / _ \/ _  / _ `/ __/ -_) / __ | |/ / _ `/ / / _ `/ _ \/ / -_)_/_/_/ 
\____/ .__/\_,_/\_,_/\__/\__/ /_/ |_|___/\_,_/_/_/\_,_/_.__/_/\__(_|_|_)  
    /_/                                                                   

Updating helps us provide the best support and saves us tons of time

Use the link below to get the latest and greatest
https://github.com/lando/lando/releases/tag/v3.3.2

Lando is FREE and OPEN SOURCE software that relies on contributions from developers like you!
If you like Lando then help us spend more time making, updating and supporting it by contributing at the link below
https://github.com/sponsors/lando

If you would like to customize the behavior of this message then check out:
https://docs.lando.dev/config/releases.html
v3.3.1

$ lando --channel none

You will no longer receive update notifications.
  _      _____   ___  _  _______  _______
 | | /| / / _ | / _ \/ |/ /  _/ |/ / ___/
 | |/ |/ / __ |/ , _/    // //    / (_ / 
 |__/|__/_/ |_/_/|_/_/|_/___/_/|_/\___/  
                                         
If you do not continue to update manually this may limit our ability to support you!

$ lando version
v3.3.1

$ lando --channel stable

Slowing things down to get more
   _____________   ___  __   ____
  / __/_  __/ _ | / _ )/ /  / __/
 _\ \  / / / __ |/ _  / /__/ _/  
/___/ /_/ /_/ |_/____/____/___/  
                                 
Lando will only update you about new stable releases!

$ lando version
v3.3.1
```

**Comment by jaybeaton** [comment]
Well, it's been a little over two hours since I switched to the "none" channel and back to "stable", and now the "Update Available" warning is being shown again.

I ran multiple Lando commands during that time (with some long delays between, including running "lando --channel stable" again), so I'm sure what that means for my questions above about the expected behavior.

**Comment by pirog** [comment]
@jaybeaton best guess is that the update check caches and expires. We are in the process of moving to a new updating mechanism so i do not think this is something we will fix.
