### ISSUE TITLE
Sites not accessible after restart

### ISSUE THREAD

**Issue by dyrer** [lando/lando#3142]
Hello, 
I am running lando on Manjaro
when i create a new app almost everything working. For example a new wordpress installation, but is not working http://domain.lando.site just http://localhost:xxxxxx
after restart of my computer with lando start i get no error but site URL is not accessible, I tried many times i destroy and re-create or rebuild but I have no success
You are my last hope
thank you

**Comment by sclsweb** [comment]
I also have this issue, but on Windows using Ubuntu with WSL2. My workaround is to restart the computer and start up Ubuntu, run "sudo service docker start" and then start up Lando. If anything else accesses the network before Lando (like if I open a browser window or connect to VPN first), all my *.lndo.site URLs come up "Unable to connect." Is there a solution to this?

**Comment by jromef** [comment]
@dyrer @sclsweb after hours of searching, I found the issue for me was that the Windows IP Helper service `Iphlpsvc` was using port 443. To get everything working, I simply:

1. stopped the service in the windows Services app. 
2. did a `lando rebuild` in WSL2 

You can try using `netstat -a -b` from `cmd` to make sure nothing is using the ports Lando depends on. 

Curiously this service only gave me issues on my Windows 10 + WSL2 computer and not on my Windows 11 + WSL2 computer.
