### ISSUE TITLE
Proxy name is ridiculously long

### ISSUE THREAD

**Issue by esteinborn** [lando/lando#3157]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already. **(done)**
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate. **(couldn't find any requests like this, strangely enough)**

**Please explain your request and its importance in the form of a user story.**
As a Lando user who works with Drupal sites but also many multiple Docker containers with no linkage to Lando, I want a clean listing when I see the results of my `docker ps -a` command. Instead I see a monstrously long named proxy which throws off all the other columns in my display table.

**Please provide some detail on how lando can help solve this problem**
I'm requesting that you please rename the Lando proxy container to something much shorter to avoid cluttering up the display list.

**Is your feature request related to a problem? Please describe.**
It always shocks me to see how dang long the proxy container name is. I get the joke, It's funny, I lolled (thats the bit right?), but now its real dev time, and I'd like to get back to work.

**Describe the solution you'd like**
Shorten the Lando proxy container name

**Describe alternatives you've considered**
I could rename it myself, but then I'd probably blow something up, I have enough problems putting together local dev environments, I don't want to start renaming things on my own!

**Additional context**
none

**Comment by pirog** [comment]
proxy container name is configurable in the Lando global config so feel free to change it

**Comment by hardyoyo** [comment]
Oh, cool... This might make a nice addition to the docs (perhaps just an info box to explain the use case of wanting a clean docker ps listing?)

**Comment by hardyoyo** [comment]
docs are here: https://docs.lando.dev/config/proxy.html#configuration

I've just confirmed that adding this to my ~/.lando/config.yaml file:

`proxyName: landoproxy`

yields this output from `docker ps`:

```
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                                                       NAMES
0f165749b38b   traefik:2.2.0                        "/lando-entrypoint.s…"   14 seconds ago   Up 13 seconds   127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:49990->8080/tcp     landoproxy_proxy_1
6a2f604c0487   bitnami/mysql:5.7.29-debian-10-r51   "/lando-entrypoint.s…"   47 hours ago     Up 9 seconds    127.0.0.1:3306->3306/tcp                                                    janeway_db_1
a2914ff18156   python:3.5.9                         "/lando-entrypoint.s…"   47 hours ago     Up 9 seconds    127.0.0.1:8000->8000/tcp, 0.0.0.0:49994->80/tcp, 127.0.0.1:49993->443/tcp   janeway_appserver_1
```
