### ISSUE TITLE
Is the "excludes" feature still available?

### ISSUE THREAD

**Issue by sean1** [lando/lando#3170]
According to the documentation (https://docs.lando.dev/config/performance.html#configuration), we can exclude certain directories from being copied to the containers.  However, I noticed that it is not working for me in the latest version (v3.4.2) and searching the Lando codebase does not show the "excludes" setting anywhere, other than in the documentation.

**Comment by AaronFeledy** [comment]
If you are excluding vendor, it will still be created as part of the mounting process, but any work inside vendor will not be copied back to your host. If you are seeing changes inside that directory showing up on the host, then there's likely something wrong with your excludes implementation. Can you share your .lando.yml?

**Comment by pirog** [comment]
As far as we know `excludes` is still a thing that is in the code and that many people use
