### ISSUE TITLE
How do I use the ads section? 

### ISSUE THREAD

**Issue by AGiveawaysS** [lando/lando#3194]
Hey! I seen the Ads section, I was wondering how I use that, thank you!

**Comment by reynoldsalec** [comment]
@AGiveawaysS if you're talking about the ads you see served on https://docs.lando.dev/, those are served via Carbon Ads: https://www.carbonads.net/

You can either publish ads there or reach out to me on Lando's Slack for details on dedicated sponsorships: https://launchpass.com/devwithlando
