### ISSUE TITLE
Nestjs and Lando

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#3210]
Which best recipe for nestjs ? it s mean recipe ??

If yes official documentation not very clear and a lot of issues found
If not can you share links or demos ?

thank you

**Comment by reynoldsalec** [comment]
@kamalkech there isn't a specific recipe made just for https://nestjs.com/, but yes the MEAN recipe would probably be the best place to start, as would reading through the documentation on the Node service: https://docs.lando.dev/config/node.html#supported-versions

If you have further general questions on Lando usage, I'd recommend asking them on the community Slack: https://launchpass.com/devwithlando
