### ISSUE TITLE
YAMLException: end of the stream or a document separator is expected at line 1, column 1.

### ISSUE THREAD

**Issue by AleMadLei** [lando/lando#3220]
I work with lando on a VMWare virtual machine.

My power went off and the computer shut down. Once I started everything (Windows and the VM), lando wouln't boot.

I just got that error, my `.lando.yml` was ok.

No idea what broke.

**Comment by AleMadLei** [comment]
After a while, it dawned on me to check `/.lando/config.yml`. There were weird characters on this file. 

I emptied it and left the content to be
`bindAddress: "0.0.0.0" and it started to work again.

**Comment by reynoldsalec** [comment]
Awesome, glad to hear @AleMadLei! Closing this out but LMK if you need more help, and feel free to ping #community on the Lando Slack https://launchpass.com/devwithlando
