### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by Eldair** [lando/lando#3225]
When can we expect php 8.1 image to be available?

**Comment by ccharlton** [comment]
Docker _barely_ released the image for 8.1.0, so I'm sure everyone's catching up.

**Comment by reynoldsalec** [comment]
Hoping to have update images up tomorrow (12/1).

**Comment by reynoldsalec** [comment]
Ok, merged in new 8.1 support to lando/lando-cli, when we cut the next release (likely in the next week) you'll be able to use it.

If some of you crazy kids are running Lando from source, you should be able to use the new images as soon as the GH finishes building them and deploys them to Docker Hub (probably ~ 5PM Pacific today).

**Comment by reynoldsalec** [comment]
I'm going to close this out, Lando 3.5.3 should be released tomorrow with this fix included.
