### ISSUE TITLE
Using an unsupported version of DOCKER ENGINE on ubuntu

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#3243]
I updated to Lando v 3.6.0 on Ubuntu 20.04 LTS installed via WSL2.

When running `lando start` with my Pantheon app, I got the following warning:

```
Using an unsupported version of DOCKER ENGINE
   You have version 18.0.0 but Lando wants something in the 18.09.3 - 20.10.99 range.
```

However, I don't know why I'm seeing this, because `docker version` shows:

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

And `which docker`:

`/usr/bin/local`

lando appears to be working fine, so this is a minor issue.

**Comment by reynoldsalec** [comment]
@ptmkenny do either of the conditions from this other ticket apply to your situation? https://github.com/lando/lando/issues/2715

(Installed Docker via a snap or Docker wasn't running prior to starting Lando?)

**Comment by ptmkenny** [comment]
@reynoldsalec Yes, I didn't have docker started.  I'll close this issue in favor of that one then.
