### ISSUE TITLE
php version 8.1 is not supported (but it is documented)

### ISSUE THREAD

**Issue by anibalsanchez** [lando/lando#3247]
Hi,

I'm upgrading my recipes. According to the documentation and dockerhub, PHP 8.1 is available: https://docs.lando.dev/config/php.html#php and https://hub.docker.com/r/devwithlando/php

But, Lando 3.4.2 shows this error: `php version 8.1 is not supported`

**Comment by labboy0276** [comment]
@anibalsanchez please use the [pre-release 3.6.0](https://github.com/lando/lando/releases/tag/v3.6.0) for php 8.1 support.
