### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by benperiton** [lando/lando#3256]
I've just updated my machine, and now I'm getting the following error on running lando start

````
Let's get this party started! Starting app luna...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for docker-compose
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
````

I guess this is because python and some libs updated (I haven't dug in properly yet)
Is docker-compose 2 supported yet? Or should I just try and downgrade everything to get it working?

````
❯ python --version
Python 3.10.1

❯ lando version
v3.6.0

❯ docker-compose --version
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for docker-compose
````

**Comment by benperiton** [comment]
I tried upgrading to latest docker-compose, but then I run into https://github.com/lando/lando/issues/3255

**Comment by ElijahLynn** [comment]
Thanks for this, it just came in handy when I went to use another Python app and got a `importlib.metadata.PackageNotFoundError: No package metadata was found for aws-mfa` and just saw your troubleshooting today, so that was helpful to me, guess I will rollback some updates!

**Comment by benperiton** [comment]
@ElijahLynn Have you noticed the same problem with python 3.10? It seems that 3.10 changes how metadata is loaded slightly, which I guess won't be updated in docker-compose 1.29.2.

I've ended up adding python to ignore-pkgs and putting docker-compose back there as well, but it would be good if there was some timeline or issues that could be helped with for v2

**Comment by ElijahLynn** [comment]
> @ElijahLynn Have you noticed the same problem with python 3.10?

Possibly, I am on Python 3.10.1 but just installed 3.9.9 with `pyenv install 3.9.9; pyenv global 3.9.9` and still same error. Maybe it isn't taking right.

**Comment by ElijahLynn** [comment]
Looks like I need to rebuild all my AUR packages that depend on Python. 

PSA: Python 3.10 is in [core]. Rebuild your AUR packages. (https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/)

This is likely the same for other OSes besides just Arch.

**Comment by benperiton** [comment]
@ElijahLynn Not 100% related to the actual issue, but https://github.com/JustinTimperio/pacback is useful for setting restore points in pacman - and for easily rolling back to a day in the archive.

I wonder what the best course of action is here? Once 3.10.1 hits mainstream, then 1.29.2 will not work.

I had another go at updating and managed to get rid of the 
````
Invalid network mode: invalid container format container:<name|id>
````
error by removing any custom 'compose' services from my .lando.yml file, but then services wouldn't get noted as being started. 

Is there a roadmap for composeV2, and any issues I can help with?

**Comment by labboy0276** [comment]
Just as a FYI Docker Compose 2 is not supported in Lando

**Comment by benperiton** [comment]
Well yes, but it also does t work with python 3.10.1 so..

**Comment by labboy0276** [comment]
Yes, that isn't one of the supported versions yet: https://docs.lando.dev/config/python.html#python

I can address this issue in the next release for you.

**Comment by benperiton** [comment]
@labboy0276 Ah, sorry I hadn't checked supported Python versions 😞

Would be great to have it supported though, probably easier than compose v2!

**Comment by labboy0276** [comment]
@benperiton Support for Python up to 3.11 will be in the next release on Friday.

**Comment by nikolowry** [comment]
> Just as a FYI Docker Compose 2 is not supported in Lando

Is this not a priority? As Arch users, we know we're a little early to using Docker's latest release -- but I don't think it's ever in good form to let hard dependencies get so far behind upstream.

**Comment by pirog** [comment]
It's something we will support but likely wont happen until we move to Lando 4.
