### ISSUE TITLE
Issue with other local projects

### ISSUE THREAD

**Issue by thanosalexandris** [lando/lando#3258]
I noticed that if you have same projects, on same level, each one isolated in its own lando container, there is no way to link `composer.json` repository to an other project on same host level, as each container has its own relative path (`/app/....`). I searched the documentation extensively but i could'd not find an optimal solution.
Do i miss something here?

**Comment by labboy0276** [comment]
@thanosalexandris each project is its own app basically on its on local instance.  There are ways to get files from other projects though dependent on your Operating System.

What is your use case for doing this?

**Comment by thanosalexandris** [comment]
Hi @labboy0276 . I am happy to see and understand my issue. I am on mac os!

**Comment by labboy0276** [comment]
OK @thanosalexandris why would you need to access a composer.json in another project?

**Comment by thanosalexandris** [comment]
No `composer.json` actually. I need to point to a local composer package which is on same phusical path with my project

**Comment by labboy0276** [comment]
Your lando can see the /user folder in the app itself.  You could use that to get to your other project root if need be @thanosalexandris 

If you ssh into your appserver you can poke around and see how to get to it.

**Comment by benperiton** [comment]
I have a project setup like:

````
/user/ben/project/.lando.yml
/user/ben/project/code/<this is the app>
/user/ben/project/packages/<list of packages>
````
which means I can do this in my `/user/ben/project/code/composer.json`
````
"repositories": [
        {
            "type": "path",
            "url": "../packages/*"
        }
],
````

Could you create a symlink in each project to where the packages are located? Or maybe you could add another volume to the .lando.yml for the appserver that points /composer-packages to a location?

**Comment by labboy0276** [comment]
I am going to close this out since there is a way to access other Lando apps as mentioned above.

**Comment by thanosalexandris** [comment]
I'll agree @labboy0276. You can close the issue. It seems to work like this!
Thanks!
