### ISSUE TITLE
Lando totally not working on Linux Mint Debian Edition

### ISSUE THREAD

**Issue by dekisha** [lando/lando#3276]
Basically the same issue as with https://github.com/lando/lando/issues/3127

Whichever lando command I type, including lando version, it exists immediately with no output.

I tried re-installing it several times, removed my local Docker installation to let Lando install what it needs, but none of it helped. Also tried older versions of Lando, but with same output. This can be reproduced on:

- Operating System: LMDE 3 (cindy)
- Kernel: Linux 4.9.0-17-amd64
- Architecture: x86-64

If I try to run lando with **sudo**, it says **Lando should never ever ever be run as root...**, which is the only output I could get from Lando.

**Comment by labboy0276** [comment]
Updated title to reflect flavor of Linux.

**Comment by uberhacker** [comment]
@dekisha: Does docker work outside of Lando?  If not, it's possible you don't have a virtualized kernel.  LMDE is strict about what is allowed in that release.  No Ubuntu stuff.

**Comment by dekisha** [comment]
@uberhacker Yes, Docker works well. All other projects that I have run with Docker and this is the first one that is using Lando. But Lando doesn't want to run whatever I do.

However on my other computer it's working without issues:
- Operating System: LMDE 4 (debbie)
- Kernel: Linux 4.19.0-17-amd64
- Architecture: x86-64

Do you have an idea if this issue is related to LMDE 3 (cindy)? It's really weird that is not giving me any error (the same as with https://github.com/lando/lando/issues/3127)

**Comment by uberhacker** [comment]
Not aware of any specific issues.  Do you have docker-compose installed?  Did you update your packages (`sudo apt update && sudo apt dist-upgrade -y`)?  If everything is updated and all the requirements for Lando are installed and the issue persists, it might make sense to upgrade from cindy to debbie.

**Comment by reynoldsalec** [comment]
@dekisha going to close this out but please re-open if you have further info/questions!
