### ISSUE TITLE
Lando command to perform a sync from container to host

### ISSUE THREAD

**Issue by mikesnoeren** [lando/lando#3314]
I have a lando setup that excludes `vendor` and `node_modules` from syncing because that saves us ~1 second per request.
On landos first start I tell it to run `composer install`, `npm install` and `npm run build`, which makes sure the site is up and running with just one command.

The issue:  `vendor` and `node_modules` are not available on the host, as they are excluded and therefore don't sync. Now, wouldn't it be great if there's some kind of command that syncs selected folders from container to host? This command could make use of the `docker cp` command internally. (or if there's a better way, by all means, use that instead!)

That way my IDE doesn't have to complain about missing dependencies, and if there ever is a mismatch between dependencies I just run the command again, to re-sync from container to host. (i could run the commands locally too, but that defeats the whole containerize everything ideology, doesn't it?)

If there already is some way to achieve what I want (other than using `docker cp`) then I am not aware of it.

**Comment by pinoniq** [comment]
run the composer install command both on the host as in the container

https://docs.lando.dev/config/performance.html#caveats

**Comment by mikesnoeren** [comment]
@pinoniq I am aware of that option, but that doesn't feel like a solid workaround/fix for this issue.
 
The reason I use Lando is so I don't have to think twice about installing software on my machine. When I am required to run `composer install` and `npm install` locally I might aswell just not use Lando at all as it defeats it's whole purpose of containerizing the application.. 
Besides that, I have projects that require on all kinds of different versions of Node & composer which could result in an difference between local `vendor` and `node_modules` and those on the container.. Which is just asking for issues.

A simple (build in) sync command would be way better IMHO.

Untill this is added, I will use `docker cp`, which does exactly what I want but is way more inconvenient then a native command that does the same would be because of the args u have to supply it with..

**Comment by rabauss** [comment]
We create a custom volume `host_vendor` and then we add a event for composer:

```yml
services:
  appserver:
    overrides:
      volumes:
        - /app/vendor
        - ./vendor:/host_vendor

events:
  post-composer:
    - echo "Sync vendor to host..."
    - rsync -rtzL --delete --info=progress2 /app/vendor/ /host_vendor/
```
