### ISSUE TITLE
Official Lando Discord server?

### ISSUE THREAD

**Issue by mikesnoeren** [lando/lando#3319]
I've been using Lando quite a bit lately and found the one missing thing to be an official Discord server where to community can get togethe, help each other out and see announcements from the Lando team.. I did somewhere read about a Slack Channel, but who uses Slack in 2022?!

All successful technologies, software or libraries seem te have their own Discord Server, don't let the Lando community miss out on that!

**Comment by ccharlton** [comment]
Slack is widely used @mikesnoeren and free to download or just use the web browser client.

"All successful technologies" are not all running Discord servers, especially enterprise level software/libraries. But I get the sentiment. One fun example of a widely popular framework who is "behind" in many people's eyes is WordPress who still uses TRAC and SVN.

There's no technical issue here; preferencial.
