### ISSUE TITLE
https://files.lando.dev/cli/lando-linux-x64-stable downloads latest, edge release

### ISSUE THREAD

**Issue by davereid-pfg** [lando/lando#3327]
Right now 3.6.0 is the "stable" release of Lando, but downloading the CLI using `https://files.lando.dev/cli/lando-linux-x64-stable` results in the latest edge 3.6.2 being downloaded. Is this intentional?

**Comment by labboy0276** [comment]
@davereid-pfg we just fixed this which will be in the 3.6.5 pre-release.  We redid our GitHub Actions and packaging / release flow. 

So going forward this is what each "tag" means at the end of each package:

- `-stable` is the latest stable release
- `-edge` is the latest pre-release 
- `-latest` & `-dev` are the latest commit push to the `main` branch in the cli repo
