### ISSUE TITLE
please rebuild devwithlando/php:8.0-fpm-4

### ISSUE THREAD

**Issue by op-euga** [lando/lando#3337]
I think you built the image as the new version php 8.0.16 was released. But the devwithlando/php:8.0-fpm-4 does still contain php 8.0.15 which has a bug when adding socket module, while 8.0.16 should not contain this bug any more.

**Comment by labboy0276** [comment]
I put in this PR: https://github.com/lando/php/pull/27 

It will rebuild all the containers today.  If you are still having an issue, make sure to purge all your local docker images via: https://gist.github.com/labboy0276/4406db072f9ed3bf3641f57c1d902027 @op-euga
