### ISSUE TITLE
I need to access PHP sendmail in Lando site

### ISSUE THREAD

**Issue by digitalit** [lando/lando#3355]
I know everyone talks about MailHog but i dont think i can use that so sent SMTP mail from my published live site?

I woul'd like to have php's built in mail sender to work in Lando so i can just deploy to live server with the same code for sending mail.

Please adwice, and have a nice day.

**Comment by sinnbeck** [comment]
I suggest using the slack chat for support questions as this isn't really an issue with lando. Anyways. You want to use smtp on production, is that correctly understood? What sort of php framework are you using?

**Comment by reynoldsalec** [comment]
You'd need to configure SMTP in your Lando config or, alternatively, use an external SMTP service. The later approach might be the most flexible/reliable if you're already using such a service for your production website.

Here's the link for the Lando Slack: https://launchpass.com/devwithlando

**Comment by digitalit** [comment]
@reynoldsalec thank you for you input :)

Yes i use an external SMTP server that need username and password to send.

I can't find any info other than MailHog Googeling, i need info on how to put stuff in the .lando file to get this to work.

Looking att my phpinfo() on my Lando site i only see this and i guess there are mail stuff missing?

`

mail.add_x_header | Off | Off
-- | -- | --
mail.force_extra_parameters | no value | no value
mail.log | no value | no value

`
and:

`

sendmail_from | no value | no value
-- | -- | --
sendmail_path | /bin/true | /bin/true

`
Maybe the sendmail_path | /bin/true | /bin/true is enought to use regular PHP mail sending code but i guess i will have to add it in the lando file somehow, right?


Tank you again and have a nice day

**Comment by sinnbeck** [comment]
What framework are you using? Wordpress? Laravel? Something else? I use laravel personally and everything works perfectly well without any changes to the .lando.yml 

What is the reason you want to use sendmail? Does your framework require you to use that for using SMTP or?

**Comment by digitalit** [comment]
@sinnbeck thank you for answering,

Just to give you a little background info:

I started using php a long way ago when files were called filename.php3 i produces a few "home made" sites before i discovered PHP framworks.

I tryed Wordpress wich i really don't like ant still try to stay away from unless a customer demands it.

Then i found Joomla and were using it for a pretty long time.

The i found Laravel wich i my oppinion still is the best PHP framework.

After using Laravel for a while i found Lando and i were so happy with it since i don't want to mess up my mac-mini with Brewer or use programs like MAMP, i want my dev env on a separate machine in a vm.

But now and since like 4 year ago i only built sites using Node.js and specifically a node framework called AdonisJS wich is just like Laravel for Node. And since moving over to Node.js Lando didn't work as i wanted mainly due to the whole port stuff thing so i for node sites develop on my separate local machine in a Node vm i use Nginx Proxy Manager with great result.

Made few atempts to use NPM on my dev machine in a PHP vm but since Lando changes ports i guess i must edit NPM every time i start lando for a dev site so i now jus access my php lando sites devserverIP:landoPORT and this i totally fine since all php sites just use one url. 

My node projects has three different apps/sites api.customer.se running AdonisJS and just acts as an API,  admin.customer.se running Quasar (in my oppinion the best node frontend framework) and this url is used for my customer and their staff to "controll the official site, www.customer.se also running Quasar and this is the actual customer webpage. All theese three appps need to comunicate between each other and this is another reason for me not to use Lando.

So the short story is that it's been like 10 years ago i just used a mail send form in a single php page (no framework) and as you can imagine i fallen back alot with my php skills.

I need help to figure out how to use send mail function standard in 8.1 without having to ssh into anything and add stuff.

I get i might need to configure some php stuff in Lando but here i'm lost.

I also if possible (since this is a bit out of Lando topic) get some help with the php code for a plain php site to send SMTP mail using username and password from an external SMTP server.

Thank you again and hva a nice day.

**Comment by sinnbeck** [comment]
Sounds like quite a journey. I use laravel every day myself.

If you want to use laravel, you just add the smtp credentials to the .env file, and laravel will handle the rest :) It is really easy. And if you run into issues with getting it to work, feel free to post on https://laracasts.com/discuss where I personally help out on a daily basis.

If you want to send mail without a framework, is to install a package that can help you do so. Php has an awesome package manager nowadays called composer which laravel also uses. I personally use this package for projects that isn't laravel. https://packagist.org/packages/symfony/mailer

**Comment by digitalit** [comment]
@sinnbeck thank you, sounds great.

The back to my problem with my single send mail without a framework.

Hos to i install this package composer in my lando site's php?

And how do i configure the .lando file to be able to do:

Step 1 just to see that is works in lando

`use Symfony\Component\Mailer\Transport;
use Symfony\Component\Mailer\Mailer;

$transport = Transport::fromDsn('smtp://localhost');
$mailer = new Mailer($transport);

$email = (new Email())
    ->from('hello@example.com')
    ->to('you@example.com')
    //->cc('cc@example.com')
    //->bcc('bcc@example.com')
    //->replyTo('fabien@example.com')
    //->priority(Email::PRIORITY_HIGH)
    ->subject('Time for Symfony Mailer!')
    ->text('Sending emails is fun again!')
    ->html('<p>See Twig integration for better HTML integration!</p>');

$mailer->send($email);`


Ste2 use this with my SMTP server that requires username and passwor using a specific port?

I'm really sorry to bother you but im totally lost here and my customer is calling every 30 minutes asking when it will be up and running :(

**Comment by sinnbeck** [comment]
@digitalit No worries. I love helping people out. In the directory where you have the php file, you install the package
```
lando composer require symfony/mailer
```

Then inside the php file you add something like this.
```
<?php
require_once './vendor/autoload.php';
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;
use Symfony\Component\Mime\Email;


$port = 25; //replace with proper port
$transport = new EsmtpTransport('my-smtp-host.com', $port);
$transport->setUsername('my-username')
    ->setPassword('my-password');
$mailer = new Mailer($transport);

$email = (new Email())
    ->from('hello@example.com')
    ->to('you@example.com')
    //->cc('cc@example.com')
    //->bcc('bcc@example.com')
    //->replyTo('fabien@example.com')
    //->priority(Email::PRIORITY_HIGH)
    ->subject('Time for Symfony Mailer!')
    ->text('Sending emails is fun again!')
    ->html('<p>Sending emails is fun!!</p>');

$mailer->send($email);
```
I personally prefer this transport instead of the default, as it is so much easier to set up correctly :)

Here are the docs: https://symfony.com/doc/current/mailer.html

**Comment by digitalit** [comment]
@sinnbeck please don't get frustrated on me cause im really lost.

The command: lando composer require symfony/mailer i ran in the vscode terminal and i get:

`peter@php:~/development/digitalit/php1.digitalit.se$ lando composer require symfony/mailer
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112`

Did i do wron running this comman in vscode terminal and if so where and how should i run it?

Again please bear with me

**Comment by sinnbeck** [comment]
Don't worry. If possible you can perhaps jump on the slack channel and I can help you "in real-time" ?

The problem seems to be that your php version does not match the symfony version. It expected php 8.1 but I assume you have 8.0 or something :). 

Try this to install an earlier version (5.x instead of 6.x)
```
lando composer require symfony/mailer "^5.0"
```

**Comment by digitalit** [comment]
i have slack on my mac-mini but no microphone.

Can i use slack in my iPhone or on a Discord chanel that i did yesterday with another fantastic support guy like you?

I have phpinfo() on my lando page and it shows:

`PHP Version 8.1.3`

**Comment by digitalit** [comment]
And also, this i a major problem for me so i will like i did with the other gou paypal you for your help

**Comment by digitalit** [comment]
running php -v in my vscode terminal that is connected to my vm gives me:

`peter@php:~/development/digitalit/php1.digitalit.se$ php -v
bash: php: command not found`

So i gues i have to run the command somehow in lando?

**Comment by sinnbeck** [comment]
No need for pay. Just happy to help.

One thing though. Are you trying to use lando on the production server? Be aware that lando is for development. What kind of server is it? Maybe the easiest solution is to just to install php directly on the server?

I am currently on the lando slack chat, in the community tab.

**Comment by digitalit** [comment]
I also work as a firefighter and I got an alarm so I had to leave the office for a while but now I'm back.

No i don't use Lando in production an that server has php 8.1

My dev server is a Debian vm with nothing on it. I just start lando. Maybe i should install php 8.1 in the Debian server?
