### ISSUE TITLE
Proxy *.lndo.site does not work at all! (but it's green)

### ISSUE THREAD

**Issue by abedi-h** [lando/lando#3356]
Hi
Long story short! the proxy system does not work at all but it's green in the console. I get "Gateway Timeout" message.
I checked default profiles for Drupal and LEMP without any extra settings and for troubleshooting I did everything including:
- lando poweroff & rebuild
- the purge script provided in some issues here
- removing all docker / images / containers / lando and reinstalling everything. in this case for the first time it works but after that it does not work again
- I added proxy urls to my hosts file pointing it to local host
- added custom urls to .lando.yml

I run lando on Linux / Manjaro and as I said with just the default profiles.

**Comment by sharique** [comment]
I'm getting "Bad gateway" on latest stable version of lando and docker from official docker repo.
I'm using Fedora 35 and pantheon recipe.

**Comment by abedi-h** [comment]
something I noticed is that when you finished your working, if you do 
`lando poweroff`
instead of
`lando stop`
you get less "Bad Gateway" next time.

**Comment by sharique** [comment]
It didn't helped, butI'm able to access site using `*.lndo.site` after some time.

**Comment by arlina-espinoza** [comment]
Similar story, I've tried the `pantheon` recipe for drupal8 and drupal9, and their `*.lndo.site` domains don't work. I have other sites running using regular drupal8/9 recipes without issues. 
Adding the following override on `.lando.local.yml` makes them work again, so I assume it's related to the varnish service:
 ```
config:
  edge: false
```

My system:
- Fedora 35
- Lando v3.6.5
- Docker version 20.10.14

**Comment by milkovsky** [comment]
For me *.lndo.site works unstable. I can not tell the steps to reproduce. But it very rarely happens, that *.lndo.site URL works for me when I work on my projects.

**Comment by kburakozdemir** [comment]
This may seem to be a temporary solution, but simply add your domain to `C:\Windows\System32\drivers\etc\hosts` file. Do not forget to open the file as an administrator.

![image](https://github.com/lando/lando/assets/1656836/41ce1d55-07fe-4722-8ed9-1eb3031de075)

**Comment by reynoldsalec** [comment]
@kburakozdemir good tip; for those trying to troubleshoot issues with *.lndo.site domains, reading through [the proxy docs](https://docs.lando.dev/core/v3/proxy.html) is highly recommended.
