### ISSUE TITLE
Extra macOS installers without Docker bundled

### ISSUE THREAD

**Issue by rubenvarela** [lando/lando#3368]
Some of us have been using updated versions of docker and having an image without docker would be pretty nice. 

My particular use case,

I have a newer versions of Docker installed. I'm currently traveling and trying to spin a project. Saw that there's an update for lando but my current connection is horrible. Most of the 600MB's is Docker which could be saved.

**Comment by rubenvarela** [comment]
Looks like lando occupies 56.4MB's after installing. The space on the compressed image must be lower.

**Comment by reynoldsalec** [comment]
Interesting idea; this may be made easier by eventual evolutions of Lando as Hyperdrive takes over as a "package manager" for various dev dependencies. Lando is also interested in decoupling from Docker Desktop as a core dependency in the future.

I'm going to close this out just for issue queue cleanliness, but know that your fundamental concern has been heard and, although it can't be easily addressed right now, it will probably be resolved in the long run by the changes planned for Lando 4.x.

Thanks again for the feedback!
