### ISSUE TITLE
Provide lando launch command to open website in browser

### ISSUE THREAD

**Issue by janisint** [lando/lando#3386]
It would be great to have a command named e.g. `lando launch`, which will execute the start process (like lando launch) and then open the web url when finished.
It should also take an uri as argument to one can open e.g. `project.lando.site/test` with `lando launch /test`.

This is more of a nice-to-have feature but can be really useful sometimes.

Inspired by the [similar feature in ddev](https://ddev.readthedocs.io/en/stable/users/cli-usage/#:~:text=or%20other%20container\).-,ddev%20launch,-or%20ddev%20launch).

**Comment by gitressa** [comment]
I agree @janisint, this would be nice. See also:
- #339
- #447
- https://github.com/lando/php/issues/8
- https://github.com/lando/docs/issues/47

This is clunky, but works in Ubuntu:

```
lando start && sleep 5 && xdg-open $(drush uli -l $(lando info --format json | jq '.[0].urls' | jq -r .[3]))
```

Add as alias:

```
alias launch='lando start && sleep 5 && xdg-open $(drush uli -l $(lando info --format json | jq '.[0].urls' | jq -r .[3]))'
```

Use:

```
$ cd recommended-project/
$ launch
Let's get this party started! Starting app drupal9...
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting drupal9_database_1  ... done
Starting drupal9_appserver_1 ... done
Scanning to determine which services are ready... Please stand by...

   ___                      __        __        __     __        ______
  / _ )___  ___  __ _  ___ / /  ___ _/ /_____ _/ /__ _/ /_____ _/ / / /
 / _  / _ \/ _ \/  ' \(_-</ _ \/ _ `/  '_/ _ `/ / _ `/  '_/ _ `/_/_/_/ 
/____/\___/\___/_/_/_/___/_//_/\_,_/_/\_\\_,_/_/\_,_/_/\_\\_,_(_|_|_)  
                                                                       
Your app has started up correctly.
Here are some vitals:

 NAME            drupal9                           
 LOCATION        /home/username/dev/recommended-project 
 SERVICES        appserver, database               
 APPSERVER URLS  https://localhost:49303           
                 http://localhost:49304            
                 http://drupal9.lndo.site/         
                 https://drupal9.lndo.site/
```
... and the web site is opened, logged in as admin.

**Comment by janisint** [comment]
True, but would still be nice to have this as a native feature

**Comment by janisint** [comment]
After working with lando for some time, I don't find this to be a necessary feature anymore.
