### ISSUE TITLE
$HOME/.lando/plugins directory no longer read

### ISSUE THREAD

**Issue by francoisvdv** [lando/lando#3391]
Hi,

I updated Lando from version 3.6.2 to 3.6.4 and it seems the `$HOME/.lando/plugins` directory is no longer read.

If I look at my pluginDirs (through `lando config`) I see that directory is indeed no longer there:

```
 pluginDirs:
   [ '/snapshot/cli',
     { dir: '/snapshot/cli/integrations',
       path: '/snapshot/cli/integrations',
       subdir: '.' },
     { dir: '/snapshot/cli/node_modules/@lando',
       namespace: '@lando',
       path: '/snapshot/cli/node_modules/@lando',
       subdir: '.' },
     { dir: '/Users/francois.vanderven/.lando/plugins/@lando',
       namespace: '@lando',
       path: '/Users/francois.vanderven/.lando/plugins/@lando',
       subdir: '.' },
     '/Users/francois.vanderven/.lando',
     { dir: '/snapshot/cli/integrations',
       path: '/snapshot/cli/integrations',
       subdir: '.' },
     { dir: '/snapshot/cli/node_modules/@lando',
       namespace: '@lando',
       path: '/snapshot/cli/node_modules/@lando',
       subdir: '.' },
     { dir: '/Users/francois.vanderven/.lando/plugins/@lando',
       namespace: '@lando',
       path: '/Users/francois.vanderven/.lando/plugins/@lando',
       subdir: '.' } ],
```

Placing the plugin (https://github.com/francoisvdv/lando-mutagen) in `$HOME/.lando/plugins/@lando` does work, but this does not agree with the documentation (https://docs.lando.dev/config/plugins.html).

**Comment by dsnopek** [comment]
@francoisvdv This problem could be that your plugin directory name has a dash in it (lando-mutagen)? We experienced that problem with a custom plugin of our own. I just filed issue https://github.com/lando/lando/issues/3394 about it

**Comment by francoisvdv** [comment]
Hi @dsnopek 

This indeed seems to be the problem! Without a dash the plugin loads just fine from the ~/.lando/plugins directory.

Thanks, I will close this issue so we can continue in #3394.
