### ISSUE TITLE
Why not allow passphrase protected SSH keys to be added to the containers

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#344]
Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

As a lando user who works with Drupal sites which passphrase protected SSH Keys, I want the option to add these passphrase protected keys from my .ssh folder to the containers to enable the possibility to use drush ssh to move to different environments and execute other drush commands like rsync and sql-sync.

Please provide some detail on how lando can help solve this problem

Right now we filter out passphrase protected ssh keys from the load-keys.sh script
```sh
# Filter out non private keys or keys that are password ENCRYPTED
for SSH_CANDIDATE in "${SSH_CANDIDATES[@]}"; do
  echo "Checking whether $SSH_CANDIDATE is a private key..."
  if grep -L "PRIVATE KEY" $SSH_CANDIDATE &> /dev/null; then
    echo "Checking whether $SSH_CANDIDATE does not have a passphrase..."
    if ! grep -L ENCRYPTED $SSH_CANDIDATE &> /dev/null; then
      if command -v ssh-keygen >/dev/null 2>&1; then
        echo "Checking whether $SSH_CANDIDATE is formatted correctly..."
        if ssh-keygen -l -f $SSH_CANDIDATE &> /dev/null; then
          SSH_KEYS+=($SSH_CANDIDATE)
          SSH_IDENTITIES+=("  IdentityFile $SSH_CANDIDATE")
        fi
      else
        SSH_KEYS+=($SSH_CANDIDATE)
        SSH_IDENTITIES+=("  IdentityFile $SSH_CANDIDATE")
      fi
    fi
  fi
done
```
Why not add those anyway if some configuration setting in the lando yml file tells us to and ask for the passphrase when building the container(s).

**Comment by pirog** [comment]
@jbertoen i think the big reason why we don't so this is because at some point there will be a GUI version of Lando and we don't want to be asking the user their password every time they do something that requires a key.

That said, we could definitely could add a config option so the user can change the default behavior and load in password protected keys.

**Comment by jbertoen** [comment]
That would be awesome. Because we would like to use stuff like rsync and sql-sync with some of our environments using drush. And we need to use passphrase protected ssh keys for this.

**Comment by pirog** [comment]
@jbertoen currently looking at providing a global config setting to switch this on for users who prefer passphrase protected keys. 

When you say "we need to use passphrase protected ssh keys for this" i assume you mean your org has a policy to use passphrase protected keys? i don't think it is a technical requirement for rsync/sql-sync to have passphrase protected keys. Could definitely be mistaken there.

**Comment by jbertoen** [comment]
You are correct. We use it for some of our environments, like using drush ssh with an alias to move to an environment online.

What about running an ssh-agent container that is configurable in this way or something?
https://docs.amazee.io/local_docker_development/drupal_site_containers.html
The guys from amazee have a system that works like this when running haproxy. 
Couldn't this also be the case for running the traefik container with the ssh-agent. Making sure we online have to setup ssh one time?

**Comment by pirog** [comment]
@jbertoen at this point i think something like an `ssh-agent` container might be overkill for us. That said it's definitely a good and valid solution and i inherently trust any design decision that the amazee.io guys come up with.

I'm not completely clear on what you mean re: haproxy and traefix. Seems like potentially a different issue than what this ticket covers? And as far as i know there really shouldn't be any "setup" required to get your ssh-keys setup for use inside of lando containers. If you've got valid non-passphrase protected keys then lando will load them up. Of course once this issue is satisfied you can toggle the non-passphrase protected part of that.

**Comment by AaronFeledy** [comment]
In some of [the scripts I'm working on](https://github.com/AaronFeledy/lando-scripts), I load my password protected SSH key like below, then run multiple ssh, scp, and rsync, having to enter the password only once. Your user's home directory is available in the appserver container under /user/, so you might load your id_rsa like so:
```
SSH_KEY_FILE='/user/.ssh/id_rsa'
eval `ssh-agent` > /dev/null
ssh-add $SSH_KEY_FILE
```

**Comment by jbertoen** [comment]
@pirog Sorry about the confusion with traefik and haproxy. What I gather is that they have a similar setup with docker as lando. Without the whole recipe and plugin system. It's called pygmee, instead of using the traefik container lando uses for proxy multiple environments, it uses haproxy and/with an ssh-agent.
This setup enables that your ssh keys are added ones for all started environments within the proxy setup as I believe.
Lando does this for every project separately.

@AaronFeledy I had something similar done using the extras option in the lando file. Moving ssh keys that are skipped because of the existing passphrases. And when using lando ssh triggering a bash shell in the container would make sure the passphrase was entered.
Down side was that doing a lando drush @somealias ssh would not trigger the request for a passphrase.

**Comment by pirog** [comment]
@jbertoen got it! This all makes way more sense to me now. 

I can definitely see some big advantages to doing things that way but as you infer lando makes a lot of really low-level assumptions that things will be done on a per-project basis so *im guessing* also doing it that way would be a pretty big change. given that i think the user experience FOR MOST PEOPLE in either model is more or less the same im guessing its probably not worth it.

that said, and in contrast, the config option proposed here is pretty easy to implement. so let's get it in and see how it goes. fast iterations to success!

@AaronFeledy those scripts all look awesome. any chance i could convince you to write a tutorial or blog post that details how you guys are using them? ;)

**Comment by AaronFeledy** [comment]
@jbertoen I think you might be able to add something like `'ssh-options' => '-i /user/.ssh/id_rsa',` to your drush alias config to get it to work.

@pirog That is actually the plan. I want to finish up a couple more features I'm working on, then I plan to make a blog post.

**Comment by jbertoen** [comment]
@pirog That seems like a good way to start right now so that is fine by me.
@AaronFeledy Haven't thought about that! Thanks, going to try that out.

**Comment by pirog** [comment]
@AaronFeledy +1 on `ssh-options`, 
also super cool re: blog post! definitely ping us when it's looking good and we can do all the retweets/etc

@jbertoen sounds good!

**Comment by pirog** [comment]
Ok, this is queued up!
https://github.com/lando/lando/commit/8e6e6d482e809a5fe4c348111abda26fb2418520
