### ISSUE TITLE
Upgrade Docker Please

### ISSUE THREAD

**Issue by spencerthayer** [lando/lando#3468]
The current version of Docker Desktop is 4.14 and Lando is producing this warning...

```
Using an unsupported version of DOCKER DESKTOP

You have version 4.13.1 but Lando wants something in the 2.1.0.0 - 3.6.99 range.
If you have purposefully installed an unsupported version and know what you are doing
you can probably ignore this warning. If not we recommend you use a supported version
as this ensures we can provide the best support and stability.

https://docs.docker.com/docker-for-mac/release-notes/
```

**Comment by renebakx** [comment]
From experience it's kinda safe to ignore that warning. Docker development goes way faster than Lando. Been using v.13.1 for a while, not really encountered issues. Running on MacOS 12.6.1 with the new virtualisation turned on.

Haven't tried the new VirtioFS yet.

**Comment by reynoldsalec** [comment]
Reinforcing that's it's safe to ignore (I'm running 4.13); there is an existing issue as well (https://github.com/lando/lando/issues/3370)

**Comment by spencerthayer** [comment]
It does seem odd that the Lando team wouldn't want to support the latest Docker fully.
