### ISSUE TITLE
3.8.0 x64 dmg states hardware mismatch on intel mac

### ISSUE THREAD

**Issue by gilzow** [lando/lando#3487]
Just downloaded the [lando-x64-v.3.8.0.dmg](https://github.com/lando/lando/releases/download/v3.8.0/lando-x64-v3.8.0.dmg) to install on my intel mac (2.6 GHz 6-Core Intel Core i7). After beginning the installer, and clicking on allow to let it run the program to determine if lando can be installed, it warns `Mismatched hardware architecture detected!` and won't let me continue. Tried downloading again just in case it was "wrong" the first time around. And then I tried downloading+installing the `arm64` version just in case the naming of the two .dmg was flipped, but it does the same thing.

Happy to provide more info, logs, etc to help debug. Just let me know what you need.

**Comment by gilzow** [comment]
FWIW, the [lando-x64-v3.6.5.dmg](https://github.com/lando/lando/releases/download/v3.6.5/lando-x64-v3.6.5.dmg) image installs without complaints.

**Comment by suryanto** [comment]
I have the same issue here on my intel mac (2.4 GHz Quad-Core Intel Core i5)

**Comment by luispimentellopes** [comment]
Also have the same issue here. I am running macOS Ventura 13.0.1 on a 2020 Macbook Pro (2.4 GHz Quad-Core Intel Core i5)

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1619998/208659291-bd3454b8-cd67-48f7-afe1-3b559618e791.png">

**Comment by philltran** [comment]
Arm64 dmg ([lando-arm64-v3.8.0.dmg](https://github.com/lando/lando/releases/download/v3.8.0/lando-arm64-v3.8.0.dmg))installs on my M1 Macbook. I think the issue may be related to new release tagging logic added [here](https://github.com/lando/lando/commit/cac87d6cdf327de67f2e3f7f95bb799a71c00ceb).

**Comment by jyodsh** [comment]
The same hardware incompatibility issue was 

reported on my intel mac. Attaching the config details herewith.
<img width="250" alt="Screenshot 2022-12-21 at 5 42 38 PM" src="https://user-images.githubusercontent.com/1733043/208902708-7d3f8d40-b463-46fb-bb34-9a5fcebb83f0.png">

**Comment by xaqrox** [comment]
samesies

![Screen Shot 2022-12-21 at 14 42 20](https://user-images.githubusercontent.com/394919/208989878-58e7085f-a142-44e0-a76a-afecde14579b.png)

**Comment by csaggo** [comment]
same for me mb pro ventura intel i9

**Comment by pirog** [comment]
Could you all try to install again and then share the contents of `/var/log/install.log`? It should have some logging about whats going on.

**Comment by pirog** [comment]
https://github.com/lando/lando/releases/tag/v3.8.1

**Comment by luispimentellopes** [comment]
Thanks @pirog it works fine now 👍🏻
