### ISSUE TITLE
Enhancement request: Option to wipe the database before db_import

### ISSUE THREAD

**Issue by dnotes** [lando/lando#353]
As a lando user who works with Drupal sites in dev/test/live workflow using feature branches and a CI, I want to be sure that my database does not contain extra tables after doing a db_update, because they can break things and waste my time.

I would like an option, or even a setting, to have lando completely wipe the existing database before importing from another database when using `lando db_import` or `lando pull`.

**Comment by uberhacker** [comment]
+1 on this request.

**Comment by ptmkenny** [comment]
+1.  I just got bitten by this and came here to request the same.

**Comment by uberhacker** [comment]
As a workaround in the meantime, you can run `lando drush sql-drop -y` prior to `lando db_import ...`.

**Comment by ptmkenny** [comment]
@uberhacker Thanks, that's helpful.

**Comment by pirog** [comment]
I think this definitely makes sense and is a good idea for `lando pull` on a `pantheon` recipe. 

I'm not sure what the best approach would be for `db-import`. i can definitely see use cases where a user might not want to wipe the db first (eg developer B sends developer A a diff of their db changes and you import it). Options here are:

1. Some sort of wipe and replace flag
2. Having the user set up a custom command that does what they want (https://docs.lndo.io/tutorials/setup-additional-tooling.html#multi-service-tooling-with-events)
3. Documenting that it might be useful to `lando mysql drop table` before importing

**Comment by dnotes** [comment]
Now that I see the options, I think it would be pretty easy to make a
custom command. However, for the long run I think it would make sense to
have flags like `lando pull --wipedb` and `db-import --wipe`.

**Comment by pirog** [comment]
@dnotes i def think its safe to have this be the default behavior on `lando pull`, the `db-import` command is the one that might benefit from some sort of `--wipe` option which i def think we should support.

**Comment by dnotes** [comment]
Yeah, actually that's even better. Maybe a --no-wipe on lando pull, just in
case.

-I'm assuming that lando switch uses lando pull, but if not then that
should wipe the database as well.

**Comment by pirog** [comment]
@dnotes definitely open to that although im struggling to think of a use case where that would be helpful for pantheon apps. Can you think of any?

**Comment by uberhacker** [comment]
I'll give my 2 cents worth here.  I think it makes sense if we wiped the database by default for `lando pull` and `lando db-import`.  This is likely the expectation in 99%+ of the use cases.  I do think a `--no-wipe` flag makes sense, however.  Only require a flag on the 1% of use cases.  I just wish composer would adopt this approach also.  I think the `--with-dependencies` flag is the most ridiculous and pointless flag they have ever introduced.  Sorry for sounding so cynical.

**Comment by pirog** [comment]
@uberhacker yeah i definitely think you could be right here. 

Semantically i think "db import" implies just reading in a SQL file (eg not wiping) but im guessing you are right about expectations. 

The other potential consideration is the result of a failure in expectations. If i am a user who is not expecting a wipe before an import and i lose a bunch of shit i am going to pissed. If i am a user who is expecting a wipe before an import and i end up with a few legacy tables im probably just annoyed.

**Comment by uberhacker** [comment]
Right on both accounts but you shouldn't be pissed if you run a command before learning about the switch options and defaults first. :)

**Comment by dnotes** [comment]
Hah! Cheeky! Well, as for losing stuff on the command "db-import", the only
thing you're going to lose—that you wouldn't lose anyway!—would be tables
that exist locally but not on the remote server. In the rare case that one
has actual value in the local database, I feel like one would do some
research before executing a command that basically implies "I want to
overwrite my local database."

**Comment by pirog** [comment]
I think relying on the user to RTFM first is probably not the best assumption ;) 

That said i think you guys have convinced me for a `no-wipe` option vs a `wipe` option
