### ISSUE TITLE
[Docker Desktop for Mac] ERROR ==> connect ENOENT /var/run/docker.sock

### ISSUE THREAD

**Issue by Bahlaouane-Hamza** [lando/lando#3533]
### Summary

**This issue is for reference and documentation purposes only.** not sure if it's a bug

After installing lando with Docker Desktop for Mac and running 

```bash
$ lando init \
  --source cwd \
  --recipe lamp \
  --webroot . \
  --name hello-lando
```

I get the following error 
```bash
WARN ==> docker is not running!
Starting docker up before we begin... please wait.
ERROR ==> connect ENOENT /var/run/docker.sock
```
### System

- Ventura 13.2.1 (22D68)
- Lando v3.11.0
- Docker Desktop 4.17.0 (99724) **is currently not supported by Lando** 

### My attempts to fix the error...

1. Find location `docker.sock` 

```bash
$ docker --config
Options:
      --config string      Location of client config files (default "/Users/user/.docker")

```

Socket path is `/Users/user/.docker/run/docker.sock` (`$HOME/.docker/run/docker.sock`)

2. Find lando config file using to following command and look for `configSources`

```bash
$ lando config
````

Open one of the config files (i chose the last one `/Users/user/.lando/config.yml`) and add the following

```yaml
engineConfig:
  host: 127.0.0.1
  port: 2376
  socketPath: /Users/user/.docker/run/docker.sock
````

For host and port, make sure to verify they are the same as shown in 
```bash
$ lando config | grep docker

> { host: '127.0.0.1', port: 2376, socketPath: '/Users/user/.docker/run/docker.sock' },
```

3. Restart or rebuild lando if not successful (I did not have to use this)

**Comment by CodeWilliamson** [comment]
I'm having the same issue on my OS (v13.2.1)

**Comment by michaelrobbe** [comment]
As far as I can tell, the OSX upgrade scrubbed the /var/run/ directory, so /var/run/docker.sock was missing.
The hotfix is to just remap the sock file:

`sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock`

**Comment by p-drolima** [comment]
> 

this fixed it for me

**Comment by Zakini** [comment]
I just needed to toggle the "Enable default Docker socket" checkbox in the settings to get this back
<img width="1382" alt="Screenshot 2023-05-16 at 17 52 10" src="https://github.com/lando/lando/assets/11508697/d0487cc6-dde4-46e1-b8b5-c57c3070fe43">

I'm on version 4.18
<img width="872" alt="Screenshot 2023-05-16 at 17 53 40" src="https://github.com/lando/lando/assets/11508697/0c099b94-d222-468a-894d-c601f82e33ee">

**Comment by jonpontet** [comment]
@Zakini looks to be the preferred solution 👍

**Comment by allahnoorturab** [comment]
@Zakini's answer worked for me. 😊

**Comment by ameshkin** [comment]
> sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock

This fixed the issue for me, and I am already using 13.5

**Comment by nickmaine** [comment]
I had this issue today after a reboot that installed a Mac update. I already had the @Zakini solution enabled months ago. My solution was to toggle "Allow privileged port mapping (requires password)", it was enabled but toggling on/off fixed  ERROR ==> connect ENOENT /var/run/docker.sock. 👍

**Comment by ThulaneWork** [comment]
> sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock

this worked for me !!

**Comment by rbabyuk-vs** [comment]
fyi
rancher desktop: `sudo ln -s ~/.rd/docker.sock /var/run/docker.sock`

**Comment by mattneal-stafflink** [comment]
> I had this issue today after a reboot that installed a Mac update. I already had the @Zakini solution enabled months ago. My solution was to toggle "Allow privileged port mapping (requires password)", it was enabled but toggling on/off fixed ERROR ==> connect ENOENT /var/run/docker.sock. 👍

Can confirm that this fixed my issue after upgrading to Mac Sonoma.

**Comment by doruk581** [comment]
Still experiencing this issue. I did all the available solutions on the internet. None of them worked. Docker version 4.24.2. Apple Mac M1 Pro. Macos Sonoma

**Comment by ThulaneWork** [comment]
> Still experiencing this issue. I did all the available solutions on the internet. None of them worked. Docker version 4.24.2. Apple Mac M1 Pro. Macos Sonoma

I would suggest you download the old version of the docker desktop, the latest version does not work well with Lando. here is a version that worked for me 4.20.0

**Comment by doruk581** [comment]
I lost hope and decided to continue with Podman

**Comment by shaniiwild** [comment]
> As far as I can tell, the OSX upgrade scrubbed the /var/run/ directory, so /var/run/docker.sock was missing. The hotfix is to just remap the sock file:
> 
> `sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock`

Thank you !!!!!!

**Comment by attheshow** [comment]
This still appears to be happening after every restart for me.

**Comment by decodist** [comment]
Same here... @michaelrobbe solution works, but needs to be run after each restart.

**Comment by aragrow** [comment]
Thanks to @Zakini because I had the same issue running dockers 4.23.0.  I upgraded to 4.26.0 and the issue remained.  FYI, this happened after I upgraded mac to the latest version.   THIS WORKED

I just needed to toggle the "Enable default Docker socket" checkbox in the settings to get this back.

**Comment by ginabeki** [comment]
a system restart cleared the error for me

**Comment by reynoldsalec** [comment]
Since this is an older issue dealing with a Lando dependency (Docker/Docker Desktop) I'm going to close it out here, but this is a very helpful thread and folks are welcome to continue using it.

For future visitors, if you haven't already seen it, it appears that https://github.com/lando/lando/issues/3533#issuecomment-1550034828 is the top comment here :)

**Comment by attheshow** [comment]
UPDATE: For future visitors, it now appears that [this comment](https://github.com/lando/lando/issues/3533#issuecomment-1464252377) is the top comment here and the solution for most users.
