### ISSUE TITLE
lando.exe error

### ISSUE THREAD

**Issue by wp-coin** [lando/lando#3549]
getting this error when trying to install on windows 11 Version	10.0.22621 Build 22621

```
Access violatin at 768al6c30 in module ucrtbase.dll read of address 03b572cc

```

**Comment by montgomeryyoung** [comment]
I am getting the same error. I also have windows 11 Version 10.0.22621 Build 22621.

I get the error as soon as I try to run lando-x64-v3.17.0.exe

**Comment by Sandy-Garrido** [comment]
This error has been logged a few times here - there is a work around https://github.com/lando/lando/issues/3498#issuecomment-1405549937

**Comment by AaronFeledy** [comment]
Closing as duplicate of #3498
