### ISSUE TITLE
MacOS installer gratuitously overwrites existing Docker.app

### ISSUE THREAD

**Issue by djun-kim-cp** [lando/lando#355]
Version: lando-v3.0.0-beta.17
MacOS dmg installer

Clicking on LandoInstaller.pkg runs an installer which overwrites existing the existing /Applications/Docker.app without warning or choice.

This behaviour is potentially quite damaging.

The installer should check for already installed Docker versions and not install new ones if it is not necessary.  In any case, the user should be warned, and the installation should proceed safely, for example by asking the user to cleanly shut down the old Docker processes before installing newer versions.

**Comment by pirog** [comment]
@djun-kim-cp since we are using most of the bleeding edge docker tech im not sure a choice to install lando without docker is possible. 

That said totally agree that a warning is needed here.

**Comment by djun-kim-cp** [comment]
I'd suggest the installer only offer to overwrite if there is not a minimum acceptable Docker version already installed.

**Comment by pirog** [comment]
It's a good suggestion but i'm guessing the delta between current docker version and minimum required version for lando is going to be (and consistently be) so small that its probably not worth it.

**Comment by djun-kim-cp** [comment]
As a dev, I install and track Docker Edge.  Having 'dev' tools require older/stable releases, or overwrite my choices without warning is surprising and TBH off-putting.

On the other hand, if I consciously chose to use an older version of Docker because of some requirements, I'd again hate to be surprised by the installation changing this behind my back.

**Comment by pirog** [comment]
Agreed, and i think a warning addresses both of those concerns.

**Comment by djun-kim-cp** [comment]
So I would have to chose between Lando and running Docker Edge, for example?

**Comment by pirog** [comment]
AFAIK you can choose to not install Docker as part of the OSX installation by choosing the "Customize" option. 

So you could definitely install Docker edge and install lando (and elect not to install docker). This would put you into "not supported" territory since lando is built on the stable release but i'm guessing it probably works.

**Comment by djun-kim-cp** [comment]
Yes, unchecking Docker in the customize options for the installer seems to work.  So far so good.

**Comment by pirog** [comment]
@djun-kim-cp @ptmkenny should be a good warning for this on subsequent official releases.

**Comment by unknownterritory** [comment]
The same warning should be added to the Windows installer where no "Customize" option is available and only "Git for Windows" was made optional. Thank you.

**Comment by pirog** [comment]
@unknownterritory open a new ticket!
