### ISSUE TITLE
Multiple environment support?

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#357]
Feature/Enhancement Request
===========================
One of my colleagues mentioned that Terra supports multiple environments (don't worry, he still thinks Lando is better).  My understanding of what this means is you can have separate branch environments running simultaneously in the same codebase.   For instance, one site running on a feature branch and the other running on the master branch.  Is it possible that Lando could eventually support something like this?  As an example:
```
$ lando start myproject.branch1
$ lando start myproject.branch2
...
```
where branch1 could be the master branch and branch2 could be my cool new feature branch.  The vanity domains could include the branch as well: `http://myproject.master.lndo.site`.

**Comment by pirog** [comment]
@uberhacker im curious to hear more about what this feature would be used for

**Comment by uberhacker** [comment]
@pirog: I imagine it would similar in concept to multidev environments on Pantheon so you can test feature branches first without affecting the main branch.

**Comment by pirog** [comment]
i think lando already allows this sort of thing. 

You can switch to different code easily enough via git and if you want isolated environments that require separate databases/cache/etc you can spin up another lando app from the same git repo.

Am i missing something here?

**Comment by uberhacker** [comment]
Well, I know you can do it in separate namespaces.  What would be nice is if you could host different branches in the same namespace.

**Comment by pirog** [comment]
@uberhacker possible to do something like this but i'm guessing it would not be a trivial feature given you'd need some sort of generic local multidev-ish management system.

going to icebox this for now so we can revisit once we've banged out a stable release
