### ISSUE TITLE
`lando db-import` no longer has progress on macOS

### ISSUE THREAD

**Issue by millnut** [lando/lando#3572]
When running `lando db-import` on macOS there is no longer progress running on an import, if I remember correctly there used to be one that would show and I believe it stopped working around the macOS Monterey or Ventura release.

I believe this uses `pv` behind the scenes but I haven't had much luck looking at the internals of Lando to see how it detects the presence of `pv`, and whether this is failing and falling back to `cat`

**Comment by nmcltpx** [comment]
I am also experiencing this issue. Having a progres bar would be really useful.
I am on an M1 Mac running Ventura 13.3.1

**Comment by philoSurfer** [comment]
What version of Lando for you both?

**Comment by nmcltpx** [comment]
I am on Lando 3.18.0

**Comment by millnut** [comment]
I'm using Lando 3.18.0

**Comment by CDTdenisP** [comment]
Hello, I've encounter this issue when Docker Disk Memory was near to the limit, you can try to free spaces or give more resources.

![Screenshot 2024-01-09 alle 16 27 23](https://github.com/lando/lando/assets/150345271/52de6efa-4e8b-4d60-b95d-545be3af735a)

Hope this can help.

**Comment by DuaelFr** [comment]
I think this is not a macOS issue
See https://github.com/lando/mysql/issues/54

**Comment by reynoldsalec** [comment]
Closing this out in favor of lando/mysql#54. If your db import stalls, it is useful to make sure that you still have room on Docker Desktop as indicated by https://github.com/lando/lando/issues/3572#issuecomment-1883263693
