### ISSUE TITLE
Why Whhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyy?????

### ISSUE THREAD

**Issue by Stargate-project** [lando/lando#3594]
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in /app/vendor/composer/platform_check.php on line 24

**Comment by Stargate-project** [comment]
I understand that it may be tempting to explore other versions besides PHP 7.4, but based on my experience and expertise, I strongly recommend avoiding it. This will ensure that your website or application is running at optimal performance, which is important for its success.  🤓

**Comment by AaronFeledy** [comment]
It appears as though you may be attempting to run a php 8.1 app in a php 7.4 environment, which would of course be problematic, but not a bug. I would recommend against using one of Lando's legacy 7.4 configurations for your app. Please try one of the [supported recipes](https://docs.lando.dev/core/v3/recipes.html#supported-recipes) that match the needs of your application.
