### ISSUE TITLE
Can't install on Windows 11 (ucrtbase.dll)

### ISSUE THREAD

**Issue by Gokujo** [lando/lando#3599]
I tried versions to 3.17.0 but I get an error

![image](https://github.com/lando/lando/assets/19776684/0af38ef5-3030-4964-81a6-3569a78a3e02)

I am using Windows 11 Pro 22H2 (22621.2134)

**Comment by AaronFeledy** [comment]
This issue is being tracked in #3498. Please check there for workarounds and updates.
