### ISSUE TITLE
Lando 3.18.0 - docker-compose could not be located!

### ISSUE THREAD

**Issue by hades200082** [lando/lando#3606]
> ERROR ==> docker-compose could not be located!

Lando version 3.18.0
Docker Desktop version 4.23.0

Our organisation automatically updates applications as part of its cybersecurity policies. I don't have the option to downgrade.

Is there any way I can resolve this on my machine?

**Comment by bananastalktome** [comment]
I'm in no way affiliated with the lando project, but @pirog mentioned in the slack channel that the pre-release version (https://github.com/lando/lando/releases/tag/v3.19.5) should work with DockerDesktop 4.23.0 (https://devwithlando.slack.com/archives/C2XBSHX8R/p1695224114218619?thread_ts=1695223875.572749&cid=C2XBSHX8R)

**Comment by pirog** [comment]
thanks @bananastalktome! 

we also are planning to roll a release in the next few days that will support both Docker Compose 1 and Docker Compose 2 which should get everybody into a much better, and faster place.

**Comment by szaleq** [comment]
I had the same issue with Lando `3.18.0` and Docker Desktop `4.23.0`. Any `lando` command resulted in error: "docker-compose could not be located!"

I can confirm that updating Lando to pre-release version `3.19.5` solved the problem.

**Comment by hades200082** [comment]
Thanks. Updated to pre release and it worked.

**Comment by florianmuellerCH** [comment]
I will have to add the literal error "Lando could not detect an installation of docker-compose, which is a required dependency!" because I wasn't initially able to find this issue on google :-)

**Comment by web-assistant** [comment]
Having the same issue with Lando `3.20.2` and Docker Desktop `4.23.0` 😢

**Comment by remaxrickerts** [comment]
Having same issue with Lando `3.21.2` and Docker Desktop `4.32.0` on Mac Sonoma 14.6.1

**Comment by AaronFeledy** [comment]
@remaxrickerts Run `lando setup` and Lando should fix that for you.

**Comment by remaxrickerts** [comment]
> @remaxrickerts Run `lando setup` and Lando should fix that for you.

I did and it's just looping: 
```
❯ lando start
Let's get this party started! Starting app mxc-api...

  __  __  _  __           __  ____    __            __
 / / / / / |/ /__ ___ ___/ / / __/__ / /___ _____  / /
/ /_/ / /    / -_) -_) _  / _\ \/ -_) __/ // / _ \/_/ 
\____/ /_/|_/\__/\__/\_,_/ /___/\__/\__/\_,_/ .__(_)  
                                           /_/        

Lando has detected that it does not have all the dependencies it needs to run.
But FEAR NOT because we have a special hidden convenience command called lando setup
which will do the heavy lifting and set you right.

Run lando setup and when it completes try running Lando again.

...

@lando/build-engine (docker-desktop) ✔ Installed     Dialed
 @lando/orchestrator (docker-compose) ⚠ Not Installed Will install docker-compose v2.24.5

Lando would like to run the 1 setup tasks listed above.

...

✔ Installed orchestrator to /Users/rrickerts/.lando/bin/docker-compose-v2.24.5

Setup installed 35 of 35 things successfully!
You are now good to go and can start using Lando!
updating lando
Generating plugin/cli update matrix... done [see table below]
✔ Updated @lando/core to v3.21.2
✔ Updated @lando/symfony to v1.6.0
Updated 2 of 2 packages successfully!
You are now up to date! with the latest and greatest!
adding /usr/local/bin to PATH
Updated /Users/rrickerts/.zshrc to include:

# Lando
export PATH="/Users/rrickerts/.lando/bin${PATH+:$PATH}"; #landopath

Open a new shell or run source /Users/rrickerts/.zshrc to load the changes
success! lando is now installed!

❯ source ~/.zshrc

❯ lando start
Let's get this party started! Starting app mxc-api...

  __  __  _  __           __  ____    __            __
 / / / / / |/ /__ ___ ___/ / / __/__ / /___ _____  / /
/ /_/ / /    / -_) -_) _  / _\ \/ -_) __/ // / _ \/_/
\____/ /_/|_/\__/\__/\_,_/ /___/\__/\__/\_,_/ .__(_)
                                           /_/

Lando has detected that it does not have all the dependencies it needs to run.
But FEAR NOT because we have a special hidden convenience command called lando setup
which will do the heavy lifting and set you right.

Run lando setup and when it completes try running Lando again.

**Comment by AaronFeledy** [comment]
Does `~/.lando/bin/docker-compose-v2.24.5` exist?
What does `which docker-compose-v2.24.5` show?

**Comment by pirog** [comment]
If you don’t open a new terminal or source the file to load the PATH
changes it’s possible it’s not picking up the up to date version of Lando
which may explain why it thinks things are no lt good.

**Comment by remaxrickerts** [comment]
> Does `~/.lando/bin/docker-compose-v2.24.5` exist?
> What does `which docker-compose-v2.24.5` show?

Those files are there and a command like: 
```
❯ docker-compose-v2.24.5 --version
Docker Compose version v2.24.5
```
works fine. The problem is that this was not being aliased as `docker-compose`. I had to do that manually in my `~/.zshrc` file and then lando worked again.
