### ISSUE TITLE
How to configure offline development

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#361]
The issue I have is that I do not fully understand how to configure my global config.yml and host file to get it working offline.

I added .site and .lndo.site to my dnsmasq host file and resolver but it is not working for some reason.

What am I missing?

So the steps that I took are as follows:
- Configured dnsmasq to work with lndo.site
- Rebooted OSX to make sure changes are applied
- Turn off wifi/internet
- started containers of the project

Result, red labeled url's. While using dig to follow the url, I do get my local ip adress.

Using lando stop, turning on wifi, than running lando start will make it work again.

What am I doing wrong...

**Comment by ptmkenny** [comment]
I don't know anything about dnsmasq, but this is how I was able to work offline in OS X.

`sudo vim /etc/hosts
`
Append this line to the bottom:
`127.0.0.1       mysite.lndo.site`

That's all I had to do.

For more info, see "[Working Offline or Using Custom Domains](https://docs.lndo.io/config/proxy.html)."

**Comment by pirog** [comment]
@dustinleblanc any chance you want to write up some docs on how to use `dnsmasq` with lando?

@jbertoen you should not NEED dnsmasq or to configure the global config to run lando offline. The docs posted by @ptmkenny should be sufficient for offline usage. You can also use the localhost addresses provided. Do these things bot satisfy your use case?

**Comment by dustinleblanc** [comment]
@pirog the way I've done it in the past is OSX specific (https://passingcuriosity.com/2013/dnsmasq-dev-osx/). Would OSX specific docs be helpful?

**Comment by pirog** [comment]
@dustinleblanc def! i think we probably want to have a generic not-os-specific "DNSMASQ" doc and it can include just an OSX section for now. if you've got time to add a tutorial that would be great!

**Comment by jbertoen** [comment]
@dustinleblanc If you got this up and running and are ready to share that setup, you would definitely make my day!

**Comment by dustinleblanc** [comment]
writing it up now
