### ISSUE TITLE
Documentation on integrating lando docker setup with IDE like PHPStorm to run stuff like PHPUnit

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#362]
Documentation on how to integrate the lando docker setup as a PHP interpreter with IDE like PHPStorm to run tests for instance.

As a developer using lando and PHPStorm I would like them to be integrated so that I can run PHP Unit Tests and such from the IDE, to deliver better quality code in less time.

**Comment by ptmkenny** [comment]
Yes, +1.

I will eventually try to get this working myself, but if someone already has it working and can just provide quick notes, I would be happy to clean it up into proper documentation.

In the meantime, there are other Docker projects with documentation on debugging/testing with PHPStorm [such as this on using XDebug](http://docs.docksal.io/en/latest/tools/xdebug/#debugging-with-phpstorm), and [this one on setting up the PHP interpreter](http://docs.docksal.io/en/latest/tools/behat/#integration-with-phpstorm).  Of course the steps aren't exactly the same, but for me it's been easier than starting with just the PHPStorm documentation alone, which is good but covers so many use cases it's easy to get confused.

**Comment by jbertoen** [comment]
A tip for the people setting up xdebug without using xdebug=true in the lando config. Because this will slow down the site, because it will xdebug every request.
Use the following in your php.ini

```
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.profiler_enable_trigger = on
xdebug.remote_enable = on
xdebug.remote_host = ${LANDO_HOST_IP}
```

And something like this when setting up your appserver in .lando.yml
```
config:
  xdebug: false
  conf:
    php: php.ini
```

**Comment by ptmkenny** [comment]
@jbertoen Could you explain the last line?

```
  conf:
    php: php.ini
```

This should point to a local php.ini with the xdebug configuration?

**Comment by jbertoen** [comment]
@ptmkenny Exactly! This way you can pass your own php configuration, including xdebug. Using the above I got xdebug working. The only downside is that when I move from a physical location and my IP changes, I need to restart the containers for the project.

**Comment by ptmkenny** [comment]
@jbertoen Ok, thanks.  I added a `php.ini` to my root directory and added the `conf:` line to `.lando.yml` and rebuilt my containers, but `phpinfo()` shows it was not picked up: the path is `/user/local/etc/php` or `/user/local/etc/php/conf.d/....`.

I searched the `phpinfo()` page for `/app/` but the `php.ini` did not turn up.

**Comment by jbertoen** [comment]
@ptmkenny 
This is my lando file as an example, php.ini should be directly placed next to the .lando.yml file.
```
name: project_name
recipe: drupal8
config:
  conf:
    php: php.ini
```

**Comment by jbertoen** [comment]
oops, didn't mean to close it.

**Comment by dutton242** [comment]
This setup worked for me, thank you!

**Comment by aangelinsf** [comment]
@jbertoen Can you explain a little about this comment?

"Because this will slow down the site, because it will xdebug every request."

I've tried your configuration and a bit of testing (admittedly on a bare bones site) doesn't seem to show a speed difference for me. 

I have reviewed 
[this answer](https://stackoverflow.com/questions/17736304/enabling-xdebug-remote-debug-makes-apache-server-very-slow)

and it seems that this is designed to prevent xdebug from attempting to connect to PHPStorm every request _whether or not there is a breakpoint_. In other words, I should save the ~1s connecting to PHPStorm until I hit a breakpoint.

Am I understanding this correctly?

**Comment by dustinleblanc** [comment]
This was merged, closing @aangelinsf and @jbertoen feel free to continue discussing. @aangelinsf just my .02, xdebug is known to slow down PHP when the extension is loaded. The amount you notice may be trivial, but Composer even warns when you have it on for instance. Most of us don't care on dev systems.

**Comment by aangelinsf** [comment]
@dustinleblanc no worries...I was trying to understand the mechanism he was describing. Still curious.
