### ISSUE TITLE
Every lando command is detecting docker-compose

### ISSUE THREAD

**Issue by iKlsR** [lando/lando#3621]
Clean install of lando and docker and every command I type is prefixed with `Could not detect docker-compose v2.21.0! Downloading it.` Not sure if that's a weird path issue on Windows or something else but it really seems to do this every time and adds a couple seconds to the command being ran. Worth noting `docker-compose` by itself runs.

**Comment by pirog** [comment]
@iKlsR see https://github.com/lando/core/issues/67
