### ISSUE TITLE
Update to version 3.20.7 breaks recipies 

### ISSUE THREAD

**Issue by BWilliams1992** [lando/lando#3646]
Updating to the latest version stops lando from working. Ran the install commands from the documentation 
https://docs.lando.dev/getting-started/installation.html

```
wget https://files.lando.dev/installer/lando-x64-stable.deb
sudo dpkg -i lando-x64-stable.deb
```

![image](https://github.com/lando/lando/assets/56208209/1bffc6f1-2dab-4443-bf3a-e2b387efa732)
Appears to be installing an alpha release, unsure if that was intended

**Comment by TheBoyCanFly** [comment]
The explicit version builds are also actually v3.21.0-alpha.7  For example, 
 https://github.com/lando/lando/releases/download/v3.20.7/lando-x64-v3.20.7.deb

I ran lando setup ( I'd never heard of it before and must've found it when I ran into the missing recipe issue)  I'd never ran it before, so it must be new in this alpha.   Anyway, that installed the recipes,  but now I'm stuck with the following whenever I invoke lando from my projects

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Could not find a service builder called _lamp in the builder registry!

**Comment by jds-tag** [comment]
Was able to repro with the `acquia` recipe. We install `lando-x64-stable.deb` during a GitHub action. Pinning to 3.20.6 fixes it.

**Comment by reynoldsalec** [comment]
Sorry guys, looks like a bad CLI version got cached in the build process. Deleted the release and rerolling.

**Comment by reynoldsalec** [comment]
@jds-tag @TheBoyCanFly  @BWilliams1992 new build should be up, LMK if that installer causes any issues: https://github.com/lando/lando/releases/tag/v3.20.8

**Comment by BWilliams1992** [comment]
@reynoldsalec all good now, thanks for sorting so quickly!

**Comment by reynoldsalec** [comment]
👍  NP, I'm going to close this out, but LMK if there are more issues!

**Comment by lalop** [comment]
Same problem exists on 3.21.0-beta7 with node service

**Comment by reynoldsalec** [comment]
@lalop you may need to run `lando setup` to make sure all plugins are installed on Lando versions from 3.21+.
