### ISSUE TITLE
events.lndo.site does not point to localhost.

### ISSUE THREAD

**Issue by oliveyrc** [lando/lando#3649]
According to the documentation, https://docs.lando.dev/core/v3/proxy.html, all *.lndo.site address point to localhost/127.0.0.1.

When setting up a test site, http://events.lndo.site, points to Netlify instead https://viewdns.info/dnsrecord/?domain=events.lndo.site. Not sure if this is right and/or the documentation needs updating to reflect this

**Comment by pirog** [comment]
@oliveyrc this is a bug on our end, 

we set up a redirect for a few "special" subdomains so they point to our sites eg events.devwithlando.io -> events.lando.dev but .lndo.site should be excluded from this so thanks for pointing this out! should work as expected now!

**Comment by oliveyrc** [comment]
Glad to help and see its fixed.
