### ISSUE TITLE
PHPStorm, Xdebug, and Windows- listening but no connection

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#366]
Trying to run Xdebug through PhpStorm using PHP cli on Lando appserver PHP on Windows 10 Pro.

**How I set it up**

Preferences -> Languages & Frameworks -> PHP -> CLI interpreter (click 3 dots to add)
Add interpreter (+ icon)
Server: Add server (Docker, accept defaults for Windows)
**Note: You need to choose "Expose daemon on tcp://localhost:2375 without TLS" from the General settings.  Otherwise, PHPStorm can't connect to Docker.**
Image name: devwithlando/pantheon-appserver:7.0-fpm

When you save this, it should show PHP version: your version + Xdebug: 2.5.5.

After this, save all settings and then click the phone icon (listen for debugging) on the PHPStorm debug toolbar. Then go to your site in Lando and click the Xdebug Helper Chrome extension... but it doesn't connect.

I also tried using Firefox with "Easiest Xdebug" addon, key set to "phpstorm". That didn't work, either.

I tried PHPStorm's Xdebug validation feature and got the error "Remote debugging is not enabled."  However, I'm not sure if this is important, because with a similar configuration on macOS I get the same error but PHPStorm debugging connects on macOS.
![appserver_windows_xdebug](https://user-images.githubusercontent.com/1451472/30922229-7cb45ebe-a3e3-11e7-97f7-6e9060474179.PNG)

**What I already tried**

* Check to see if port 9000 is free (admin powershell: `netstat -ab`).  It wasn't-- first taken by TightVNC server, then Xrite Color Probe software. Disabled both, rebooted, and Phpstorm successfully took control of the port.  However, still no connection when listening.
* Tried different urls (mysite.lndo.site and localhost:32222).
* Opened the Windows Firewall settings and checked for any rules that were blocking port usage by Chrome, Phpstorm, or Docker.  I also tried disabling the firewall completely.
* I tried setting the following variables in the appserver php.ini at '/user/local/etc/php/php.ini':

```
xdebug.remote_enable = 1
xdebug.remote_host = 10.0.75.1
xdebug.remote_port = 9000
xdebug.remote_connect_back = 0
xdebug.idekey = PHPSTORM

```

[This discussion ](https://gist.github.com/chadrien/c90927ec2d160ffea9c4) suggests that remote_connect_back needs to be off, and the remote_host IP address has to be the ip4 address of the DockerNET Ethernet adapter on the Windows host.

I also tried configuring the PHPStorm settings-> Languages -> PHP -> Debug -> DBGp Proxy settings:
IDE key: PHPSTORM
Host: 10.0.75.1
Port: 9000

But that didn't help either.

**Comment by samuelmolinski** [comment]
I don't normally work windows and have been learning the ins and outs of this beast.  I am going to just throw you a bone that might get you going.  I noticed your IP looks a bit odd to me. I use my local IP and not an external one. My current configuration looks like this in my php.ini
```ini

; Custom phpstorm connection
xdebug.remote_enable=1
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.remote_host=192.168.1.2
```

You might also need to add PHPSTORM to your windows variables.
Hope that can get you going

**Comment by ptmkenny** [comment]
@samuelmolinski Thanks for this info.  The IP is odd because that's the Docker NAT IP; I am trying to use the PHP interpreter on the appserver through PHPStorm rather than using my locally installed PHP.

When I get some time I guess I'll try to set it up using a local interpreter, but to me that defeats part of the point of using lando, which is to not have to manage dependencies on the local machine.

**Comment by jbertoen** [comment]
What worked for me is the following snippet in your php.ini

`xdebug.remote_host = ${LANDO_HOST_IP}`
This will dynamically change your ip in the remote host variable when starting your container based on the environment variable.

**Comment by jonathanjfshaw** [comment]
For me, on Windows 10, using `xdebug.remote_host = ${LANDO_HOST_IP} ` causes nginx to fail to start correctly. And even if it that wasn't an issue, LANDO_HOST_IP doesn't have the correct value for me, I need 192.168.x.xxx like @ptmkenny.
