### ISSUE TITLE
"Need to give this composition a project name" (`lando init`)

### ISSUE THREAD

**Issue by ccharlton** [lando/lando#3672]
Got this error when starting a new Lando app (v3.21.0-beta.1). I couldn't find that string in the source code. What causes it? 

> "Need to give this composition a project name"

**Comment by reynoldsalec** [comment]
@ccharlton when do you see that message? Would be good to know source/recipe selections you make if you get that far in the `lando init` process; I'm not able to replicate running `lando init` and choosing the local working directory/LAMP recipe.

**Comment by ccharlton** [comment]
I was able to get through the first few questions of the init wizard, but after pasting the machine token

Recipe: `pantheon`
Lando Command: `lando init`

> $ lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use? pantheon
? Enter a Pantheon machine token [hidden]
? Which site? mysite
ERROR ==> Need to give this composition a project name!

**Comment by ccharlton** [comment]
I'm suspecting it was the write permissions on `/usr/local/bin/lando`. Checking if that's the case now...

**Comment by ccharlton** [comment]
Nope. Spoke too soon. Same error still. It seems to only be happening with one site/app. Unsure what's different with it at this time.

> ❯ lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use? pantheon
? Enter a Pantheon machine token [hidden]
? Which site? mysite
ERROR ==> Need to give this composition a project name!

**Comment by AaronFeledy** [comment]
Found another mention of this error with a workaround: https://github.com/cncf/cncf.io/blob/91473b33cc2c30ce14a9bb73dbca5d7c671a5b18/README.md?plain=1#L33

**Comment by reynoldsalec** [comment]
Thanks @AaronFeledy, @ccharlton did that get you around the issue?

**Comment by trackleft** [comment]
I was able to get around the issue by creating a new lando file with an id and placing it into the directory.

```
name: projectname
recipe: pantheon
config:
  framework: drupal8
  site: projectname
  id: 4250c474-93cc-4817-aa27-4d4c32739898
```

**Comment by reynoldsalec** [comment]
@ccharlton could you see if that one project is missing the `name` attribute in the Landofile? The `Need to give this composition a project name` error is triggered when you're missing that.

**Comment by markfullmer** [comment]
> could you see if that one project is missing the name attribute in the Landofile? The Need to give this composition a project name error is triggered when you're missing that.

The plugin has the `name` attribute, per https://github.com/lando/pantheon/blob/00cea34e4aa456a3d766cd301f6566bdb15d2edf/.lando.yml#L1

**Comment by reynoldsalec** [comment]
@markfullmer could you paste your `.lando.yml`?

The `name` attribute we're looking for is going to be in your `.lando.yml`...the landofile in the root of the plugin source code is for development purposes and not directly related to the operation of the plugin.

**Comment by reynoldsalec** [comment]
@markfullmer are you still encountering this issue? I'm going to close this issue out, but comment back here and I'll re-open it. You can also find help on the Lando Slack: https://www.launchpass.com/devwithlando
