### ISSUE TITLE
v3.21.0-beta.1 should not be marked as stable

### ISSUE THREAD

**Issue by Grldk** [lando/lando#3679]
The latest beta release is marked as the latest release, which causes the lando cli to mark it as an available update. Shouldn't it be marked as a pre-release? I'm on the stable channel, I wouldn't expect beta releases to show up as updates on the stable channel.. 

Thanks for all the hard work on lando btw, really like what you are doing with it!

**Comment by dsuurlant** [comment]
Agreed, especially since per the release notes this version has some big changes. I found it surprising as well to see a beta release show up in the 'stable' channel. Perhaps this is intentional, but then there should be some clarification in what the stable channel contains -- or an additional channel for beta releases perhaps.

**Comment by yorkshire-pudding** [comment]
It would also benefit from better instructions on upgrading from 3.20.8 to this new approach.
I got this message after updating in the usual way and trying to start a lando app (WSL2 > Ubuntu 20.02 LTS):

<details>
<summary>Error message</summary>

```bash
 ✖ Enquirer is a peer dependency that must be installed separately.
ERROR ==> Enquirer is a peer dependency that must be installed separately.

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝


An unrecoverable error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

 ◼ Try running Run lando rebuild
 ◼ Try restarting in debug mode Run lando restart --debug
 ◼ Try checking the logs with Run lando logs

If those fail then consult the troubleshooting materials:

 ◼ https://docs.lando.dev/help/logs.html
 ◼ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

 ◼ Slack - https://launchpass.com/devwithlando
 ◼ GitHub - https://github.com/lando/lando/issues/new/choose


ERROR ==> Enquirer is a peer dependency that must be installed separately.
```

</details>

No mention of `lando setup` as indicated in the blog post.
I've reverted to 3.20.8 for now as cannot spare the time to beta test this process.

**Comment by attheshow** [comment]
If anyone else needs to downgrade to 3.20.8 and has errors after the downgrade, you might need to delete the directory at `~/.lando` and have it be recreated via `lando start`.

**Comment by jnettik** [comment]
I also had big issues on the new beta release. Specifically on sites using the Pantheon recipe, I was getting errors saying:

```
_      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app is starting up but we have already detected some things you should investigate.
These may or may not prevent your app from working.

  ⚠ Proxying to unknown service!
    appserver_nginx is a service that does not exist in your app!!!
    This means we have not been able to set up your proxy route
    We recommend running the below command to see the services for this app
    Run lando info
  
  ℹ Updates available!
    Lando has detected 5 packages that can be updated.
    Updating fixes bugs, security issues and bring new features.
    Run lando update
  

Here are some vitals:

 NAME      touchstone-me                   
 LOCATION  /Users/jnettik/Sites/touchstone 
 SERVICES  appserver, database, index      
 URLS                                      
  ⚠ APPSERVER URLS
    ✖ Client network socket disconnected before secure TLS connection was established
    ✖ socket hang up
  ✔ INDEX URLS
    ✔ http://localhost:63613/ [302]
```

Downgrading this morning.

**Comment by tormi** [comment]
Please use the latest https://github.com/lando/lando/releases/tag/v3.21.0-beta.6.

**Comment by Zakini** [comment]
Have a read of #3666. That covers the same issue and one of the maintainers has explained the reasoning

**Comment by UTCGilligan** [comment]
I'm having good luck by installing beta-7, lando setup/update, and update to latest docker desktop after the automatic setup of docker compose.

**Comment by reynoldsalec** [comment]
As @Zakini you can get a longer explanation of why the beta release was deployed to the stable channel: https://github.com/lando/lando/issues/3666#issuecomment-1953213246

Closing this out but feel free to ping me on the Lando Slack if you have more questions!

**Comment by attheshow** [comment]
@jnettik Did you try updating to the latest beta version yet? Any better luck this time around?

**Comment by jnettik** [comment]
@attheshow I have not had time yet to test out the lastest beta. I might try it out next week depending on a couple deadlines I'm up against.

**Comment by gcalex5** [comment]
Was getting the same/similar for Pantheon recipes on v3.21.0-beta.12 

"service "edge" depends on undefined service appserver_nginx: invalid compose project"

**Comment by reynoldsalec** [comment]
@gcalex5 did you try running `lando update`? Also probably good to make sure if you're running the Pantheon recipe you're not falling into this trap: https://github.com/lando/lando/issues/2634

**Comment by reynoldsalec** [comment]
@gcalex5 in helping some folks on Slack, found out the cause of that error: if you have a `.lando.yml` that overrides the `appserver` service and specifies `type: php`, it will cause that problem.

Example of .lando.yml that will cause the error:

```
name: my-pantheon-project
recipe: pantheon
config:
  framework: wordpress
  site: my-pantheon-project
  id: some id
services:
  appserver:
    type: php # REMOVE THIS LINE
    composer_version: 2.5.8
```

In the above example, if you remove the line `type: php` you should get past the error.

**Comment by miiimooo** [comment]
In my case the `appserver.type: php` entry was in `lando.base.yml`
