### ISSUE TITLE
Cannot launch x64-3.21.0-beta9.exe installer

### ISSUE THREAD

**Issue by nydybbuk** [lando/lando#3688]
I'm running Windows 10 Pro 21H2 (v19044.3693).

Downloaded lando-x64-v3.21.0-beta.9.exe from Github. Attempting to launch installer triggers error: 
![Lando installation error](https://github.com/lando/lando/assets/13974538/50b9eece-6a62-47cc-aeeb-f2fb62287545)

"Access violation at address 75B5FC8E in module 'ucrtbase.dll'. Read of address 039F72FC.

**Comment by AaronFeledy** [comment]
Closing this out in favor of #3498. There are some workarounds there. See the latest comment if you'd like to test an initial version of the new install method.
