### ISSUE TITLE
How do I see the full log of the build for a service?

### ISSUE THREAD

**Issue by phil-s** [lando/lando#3691]
Recent lando versions have taken to restricting the service build output to a small scrolling 'window' within the terminal, such that most of the output disappear shortly after it appears.

I want to review the complete output, either in the terminal, or in a log file.

Using the `-v` (verbose) option does not change the "scrolling window" behaviour, and nor even does `export TERM=dumb` (which seems like a bug).

Short of switching to a *genuine* dumb terminal emulator, how can I do this?  It feels like there must be some kind of switch to revert back to the old output style.

**Comment by pirog** [comment]
@phil-s to be clear this output actually comes from docker and not from lando. that said i believe it is configurable on the docker with something like this:

```sh
export BUILDKIT_PROGRESS=plain
```

FWIW, Lando 4 services, which we are starting to roll out will show the full build output when you use `--debug` or `-vvv`

**Comment by phil-s** [comment]
Ah, that's excellent.  I can confirm that `BUILDKIT_PROGRESS=plain` resolves my problem.  Thank you for that (and for the clarification).  The debug/verbose behaviour for lando 4 services also sounds perfect.
