### ISSUE TITLE
Running `lando update` does not update CLI to beta.12

### ISSUE THREAD

**Issue by possiBri** [lando/lando#3698]
I (was) on the beta.11 version of 3.21, and I was able to update to beta.12 with `lando update` — however, subsequent runs show that the @lando/cli plugin is still on beta.11 which surprised me. I figured maybe it just needed to be re-run, so I re-ran the update, the beta.12 version is shown as downloading/installing, it says update was successful. However, when I run `lando version --component @lando/cli` once the update is complete, it shows that @lando/cli is on beta.11.

![Snag_12250a6e](https://github.com/lando/lando/assets/5619350/238a61f5-06d0-4bba-b6f8-e379c97f0f6e)

![Snag_12257e27](https://github.com/lando/lando/assets/5619350/09971659-7db7-4e12-8c99-a99fe6109f94)

Also, I did try searching in several of the related repos to see if it was already addressed but I couldn't find anything.

**Comment by pirog** [comment]
@possiBri you may have the older version of Lando higher up in your `PATH`, i know this currently happens on Windows. If you run `where lando` or `which lando` what do you get? 

You may also want to open a new terminal windows to make sure any PATH changes are loaded correctly.

**Comment by possiBri** [comment]
Thanks for the quick reply! Running `where lando` returns with: C:\Program Files\Lando\bin\lando.exe — I tried another update and this time made sure to close my terminal and reopen after, no joy.

**Comment by pirog** [comment]
You have an older version of Lando higher up in your `PATH`, remove `C:\Program Files\Lando\bin\lando.exe` and then run `where lando` again and it should point to the newer one.
