### ISSUE TITLE
thank you for lando

### ISSUE THREAD

**Issue by pixelota** [lando/lando#372]
I've been using this to test drupal 8 on my local system and lando has made it incredibly, super easy. Thanks!

**Comment by uberhacker** [comment]
Wow, an issue of gratitude!  A we thought we would only have users who just mention everything wrong about Lando. :)  I echo your sentiments also. :100:

**Comment by pirog** [comment]
@pixelota we've spent a lot of blood, sweat, tears, time and treasure working on Lando (and its predecessor Kalabox) but seeing issues like this make it all worth it!

https://www.youtube.com/watch?v=__VQX2Xn7tI
