### ISSUE TITLE
Build steps failing

### ISSUE THREAD

**Issue by dylan-leopold** [lando/lando#3747]
Everything was working fine yesterday, but today I'm having an issue starting lando. I've tried lando rebuild, lando destroy/lando init, and I've uninstalled and reinstalled Docker (v.4.30), but nothing seems to be working.

name: phr
recipe: pantheon
config:
  framework: wordpress
  site: phr
  id: aac6e037-2acc-45b0-a0ba-02750a5e04e2
  edge: false

/////

Pantheon pre-run scripting
Generating RSA private key, 2048 bit long modulus (2 primes)
.....................................+++++
........................+++++
e is 65537 (0x010001)
Signature ok
subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin, CN = phr
Getting CA Private Key
PHP Warning:  copy(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in Command line code on line 1

Warning: copy(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in Command line code on line 1
PHP Warning:  copy(): Failed to enable crypto in Command line code on line 1

Warning: copy(): Failed to enable crypto in Command line code on line 1
PHP Warning:  copy(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1

Warning: copy(https://getcomposer.org/installer): failed to open stream: operation failed in Command line code on line 1
Could not open input file: /tmp/composer-setup.php
ERROR ==> 
[+] Running 5/5
 ✔ Container phr_appserver_1        Running                                                            0.0s 
 ✔ Container phr_database_1         Started                                                            0.8s 
 ✔ Container phr_index_1            Started                                                            0.8s 
 ✔ Container phr_cache_1            Started                                                            0.7s 
 ✔ Container phr_appserver_nginx_1  Started                                                            0.9s 
[+] Healthchecking 1/1
 ✔ Healthcheck phr_database_1  Passed

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app is starting up but we have already detected some things you should investigate.
These may or may not prevent your app from working.

  ⚠ One of your v3 build steps failed
    This **MAY** prevent your app from working.
    Check for errors above, fix them in your Landofile, and try again by running:
    Run lando rebuild
  

Here are some vitals:

 NAME      phr                                                
 LOCATION  /Users/Dylan.Leopold/Localdev/phr-dylan-2024       
 SERVICES  appserver_nginx, appserver, database, cache, index 
 URLS                                                         
  ✔ APPSERVER NGINX URLS
    ✔ https://localhost:51833 [301]
    ✔ http://localhost:51834 [301]
    ✔ http://phr.lndo.site:8888/ [301]
    ✔ https://phr.lndo.site/ [302]

**Comment by dylan-leopold** [comment]
It actually looks like this could be a related to this issue #3458 since my company forces me to use Zscaler. Is there any update on a workaround for this?

**Comment by reynoldsalec** [comment]
Have you gone through the steps recommended in https://docs.lando.dev/guides/lando-corporate-network-tips.html?

**Comment by dylan-leopold** [comment]
@reynoldsalec Yes, those steps didn't work for me. However I did come across this tutorial and it seemed to fix the issue: https://rngo.ca/posts/202307-lando-corporate-network-zscaler

**Comment by reynoldsalec** [comment]
@dylan-leopold that article looks identical to this step: https://docs.lando.dev/guides/lando-corporate-network-tips.html#adding-certs-to-an-appserver-container

Is that basically the change you made? If that's the case I may try to better highlight it...the rest of the config may be less important/not necessary for most users.

**Comment by dylan-leopold** [comment]
@reynoldsalec Oh yes! Sorry I didn't realize that part is pretty similar. I had mostly been looking at the section above there that required uninstalling Lando and Docker before making any cert changes. It looks like the only difference that wasn't in the above tutorial was adding this line of code to the lando.yml file. It's working without, but is it better to add this as well?

'sed 's|mozilla\/AddTrust_External_Root.crt|#mozilla\/AddTrust_External_Root.crt|g' -i /etc/ca-certificates.conf'

**Comment by reynoldsalec** [comment]
Probably helpful if you have Firefox users, so probably a good bonus but not necessary.

I'll look at refactoring the docs; think this is a case where there's a lot of good stuff here, but that single example is probably what 90% of people need, so it should probably be featured :)

Thanks for the feedback!

**Comment by dylan-leopold** [comment]
@reynoldsalec Great, thanks!

**Comment by reynoldsalec** [comment]
@dylan-leopold see if that's any clearer: https://docs.lando.dev/guides/lando-corporate-network-tips.html

Closing this out for now.
