### ISSUE TITLE
No certificate after update

### ISSUE THREAD

**Issue by sinnbeck** [lando/lando#3749]
I just updated to the latest lando version and had to rebuild one of my sites. When rebuilding I was asked for my sudo password and then threw an error that linuxmint isnt suported.. And now I get a certificate error when visiting the site?

![image](https://github.com/user-attachments/assets/ac71e4fc-18f5-4959-ad8f-e253e4ac66a2)

![image](https://github.com/user-attachments/assets/2c4aaea3-38d5-4d2e-82f0-29ea3db87099)

Is there a way to get the old way of handling certificates back or fix the issue?

**Comment by sinnbeck** [comment]
I have also gone through this, but I still get a certificate error

https://docs.lando.dev/core/v3/security.html#trusting-the-ca

**Comment by edurenye** [comment]
@pirog Since this update I'm getting this warning: `Warning: Ignoring extra certs from '/lando/certs/lndo.site.pem\', load failed: error:02001002:system library:fopen:No such file or directory`

**Comment by reynoldsalec** [comment]
Would be curious if anyone is using the Pantheon recipe?

I think there are some Pantheon-specific cert issues related to the deprecation of Lockr that also might be going on here, would like to disentangle that...
