### ISSUE TITLE
Drupal multisite and drush

### ISSUE THREAD

**Issue by robdecker** [lando/lando#375]
Is Drupal/drush multisite currently supported? If so, is there some trick I need to be using?

I've tried the usual `lando drush -l http://somesite.dev uli` (and other similar commands), but I keep getting this error/response: `We could not find an applicable site for that command.`

The multisites themselves work, I just can't get drush to work.

**Comment by jbertoen** [comment]
@robdecker Do you have a specific webroot specified?

**Comment by cfbauer** [comment]
If anyone else is seeing this in a Google search, I had to cd into the specific site in the docroot/sites/mysitename.com directory to fix this issue.

**Comment by MichaelWhittaker21** [comment]
I was able to solve a simlair problem by doing a `drush --uri=<site-name> cr`
