### ISSUE TITLE
Error: Could not find a service builder called symfony in the builder registry!

### ISSUE THREAD

**Issue by gijsroge** [lando/lando#3769]
Is the builder registry down? Or is this just an issue on my side?

Running on WSL2, Lando v3.23.19 in Ubuntu.

When i run Lando init I also do not get any recipes to choose from, the only option is "none".

```
lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use? (Use arrow keys)
❯ none
```

This is the full error in my project: (symfony is not the issue here I think, non of the recipes work)
```
lando start
WARN ==> symfony is not a supported recipe type.
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: Could not find a service builder called symfony in the builder registry!
    at Factory.get (/snapshot/core/lib/factory.js)
    at /snapshot/core/hooks/app-add-recipes.js
    at AsyncEvents.<anonymous> (/snapshot/core/app.js)
From previous event:
    at AsyncEvents.handle (/snapshot/core/lib/events.js)
    at /snapshot/core/lib/events.js
    at process.processImmediate (node:internal/timers:483:21)
From previous event:
    at AsyncEvents.emit (/snapshot/core/lib/events.js)
    at /snapshot/core/lib/app.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by gijsroge** [comment]
@AaronFeledy thanks that worked! Really digging the new installation method.

However shouldn't the `lando setup` be automated on first use? Or perhaps mentioned when a user gets the message that there is  no supported recipe? Just some thoughts.

**Comment by reynoldsalec** [comment]
@gijsroge I think @pirog actually implemented something like that on the `edge` release of Lando. Going to close this out for now, but feel free to ask more questions if you're still cooking on something!
