### ISSUE TITLE
Confusion On Drupal 8 Install With Database Import

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#378]
**Tell us about your setup**

Lando version: v3.0.0-beta.19
OS: MacOS 10.12.6

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```
name: shrugger
recipe: drupal8
config:
  webroot: .
```

**Tell us about the command you were running**

Following: https://docs.devwithlando.io/tutorials/drupal8.html

```
cd /folder/with/current/drupal8/app
lando init --recipe drupal8
lando db-import db.sql
```

**Tell us generally about your bug**

I...can't...read...just saw `lando info` in the step above the `lando db-import` info. I will leave my journey below to show you how people who skim install docs or can't read go about setting up their DB for a Drupal 8 site.

Adding the `lando info` command with a comment after

```
# Optionally run composer install if needed
lando composer install
```
 
might make things clearer for people like me. Also, the caveat about where the db file should be located would be useful to add.

------------------------

I don't think my issue is a bug, per say, but more of a documentation update. I initially ran the `lando init --recipe drupal8` command on a site that I had running on Pantheon and locally through my own LAMP stack. I didn't see any errors while the VM was booting up, and then I tried the db-import command. 

My first suggestion is to include "Due to restrictions in how Docker handles file sharing your database dump MUST exist somewhere inside of your app directory." into the Drupal 7, Drupal 8, etc. install guides. I had to find that in the links at the bottom of the Drupal 8 tutorial page after flailing my arms about for 5 minutes or so. 

After I placed a SQL file in the root of my app, the `lando db-import` command seemed to work fine, but the Drupal 8 app directory just kept directing me to "install.php". Once I had entered proper DB credentials, Drupal 8 realized a site had already been imported, but I had to find the DB creds manually in order to get past the D8 install wizard.

```
lando start
# Guess database connection is "database" from SERVICES
lando mysql
# Search for db names.
mysql > show databases;
# Search for db users.
select user from mysql.user;
# Guess password is the same as user name. 
``` 

I realize that some of this information is in config files and can be deduced from those files, but for a lot of users, they might not be as adventurous as me.

**Comment by alexfinnarn** [comment]
I can't add a label as mentioned in https://github.com/lando/lando/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by alexfinnarn** [comment]
Just followed https://docs.devwithlando.io/tutorials/drupal7.html after reading `lando info`, and the install process was very smooth.

**Comment by pirog** [comment]
@alexfinnarn this is great feedback. there is def a lot of improvements we can make in the docs

**Comment by alexfinnarn** [comment]
The added code example of "lando info" and db-import caveat is enough for me...https://github.com/lando/lando/pull/419
