### ISSUE TITLE
Does Lando Follow Symlinks?

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#379]
I think this issue might be a feature request...

**Please explain your request and its importance in the form of a user story.**

As a developer using Lando, I would like to initiate projects that can follow symlinks in my app's root folder. 

**Please provide some detail on how lando can help solve this problem**

Where I work, we make heavy use of symlinks to assemble Drupal core and our install profile. Then we put site-specific stuff in "sites/" like most people do. When I used Lando to setup a recipe in a Drupal 7 codebase that had core and profile-level symlinks, I got a permissions error from Apache where I couldn't access any routes, e.g. index.php. 

```
cd /my/app
lando init --recipe drupal7
lando start
# Go to one of the links and see Apache permissions error. 
# Forbidden You don't have permission to access / on this server.
```

When I tried the same thing with a codebase that didn't have symlinks, everything worked fine. I realize following symlinks while mounting the files is probably difficult so I wouldn't put this request too highly on your list, but you should point out any special considerations with symlinks.

**Comment by pirog** [comment]
@alexfinnarn yeah im honestly not sure how these are treated. I'm guessing we probably cant officially support symlinked activity because this isnt really a thing on windows. 

That said if you can get me steps to recreate your environment so i can actually replicate this id be happy to provide some guidance or a doc or something about using symlinks.

**Comment by alexfinnarn** [comment]
As an update, only symlinks outside of my project root don't work. I'm not sure why I expected that to work since they would be outside of `/app` on the app server. So, this might be more of a blog post or doc update, but not really a bug per say. 

Symlinking within the project root where `.lando.yml` is located does work.

I suppose I can check the Lando config files and see if I can specify another mount point to symlink from locally. I'll update the ticket with more info.

**Comment by alexfinnarn** [comment]
`AH00037: Symbolic link not allowed or link target not accessible: /app/web`

Specific error from logs, but makes sense.

**Comment by alexfinnarn** [comment]
Closing since I figured out the stipulations on symlinking.

**Comment by ibuildit** [comment]
I'm running a Drupal 7 site from platform.sh which uses the makefile build process, where webroot is inside the _www folder which is a symlink into a hidden dotfile folder (.platform/...) I get the same permission error. :-( Otherwise this kicks a**.. :)

**Comment by ibuildit** [comment]
looks like it works if i set the webroot to .platform/local/builds/default/public i must have made a typo the first time.

**Comment by ibuildit** [comment]
How ever, during the drupal 7 installation process, it also does not find the files directory so it gives an error on the check page since that directory is also symlinked.
