### ISSUE TITLE
manifest for solr:4.10 not found

### ISSUE THREAD

**Issue by rendered-monkey** [lando/lando#380]
**Lando version:** v3.0.0-beta.19 on OSX 10.12.6
```yml
name: example
recipe: lamp
config:
  php: '5.4'
  webroot: src/drupal
services:
  search:
    type: solr:4.10
    portforward: 8983
```
**Command:**
```
lando start
```

**Result:**
```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Pulling search (solr:4.10)...
ERROR: manifest for solr:4.10 not found
Pulling search (solr:4.10)...
ERROR: manifest for solr:4.10 not found
Pulling search (solr:4.10)...
ERROR: manifest for solr:4.10 not found
Pulling search (solr:4.10)...
ERROR: manifest for solr:4.10 not found
Pulling search (solr:4.10)...
ERROR: manifest for solr:4.10 not found
error:  Error: Error: 1
    at /snapshot/cli/lib/promise.js:56:17
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:42:13)
    at /snapshot/cli/lib/promise.js:50:20
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:49:12
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Doing the same with `solr:3.6` and `solr:5.5` works.

Should be reproducible using the same `.lando.yml`

**Comment by pirog** [comment]
@rendered-monkey this is a great bug report. Will try to replicate. Guessing probably easy to fix!

**Comment by pirog** [comment]
@rendered-monkey able to replicate this. fix will be in next release.
https://github.com/lando/lando/commit/3f6e9a03f659bd26a2a6b02ed3097792d11fc2f9#diff-b918f2fe4df14a1789ac4bc6d8912672

**Comment by ccjjmartin** [comment]
I can verify that I encountered this issue and the latest master branch of lando (including this fix) solved the problem for me.

**Comment by ccjjmartin** [comment]
Looks like the build process was fixed but there might be an upstream issue.  I identified this by finding that Drupal isn't able to make a connection and when I go to the IP address for the Solr instance I get a long error about failing to init:
```
Problem accessing /solr/. Reason:

    {msg=SolrCore 'collection1' is not available due to init failure: Error Instantiating Update Handler ...
```

**Comment by kennethostyn** [comment]
@pirog I'm getting the same error as @ccjjmartin when trying to access the solr web interface.

**Comment by ccjjmartin** [comment]
@pirog 
@serundeputy 

Can this issue be reopened?  It has been marked as fixed but is still throwing a few errors.

**Comment by ccjjmartin** [comment]
I am updating Lando to the lastest version and will test again.  I was running beta19.  Didn't realize we were already on 35/36
