### ISSUE TITLE
Homebrew Cask package

### ISSUE THREAD

**Issue by jordan8037310** [lando/lando#382]
How about providing lando via homebrew? 🤓

e.g. `brew cask install lando`

**Comment by jordan8037310** [comment]
I went ahead and opened a request: https://github.com/caskroom/homebrew-cask/issues/39296

**Comment by pirog** [comment]
@jordan8037310 super open to this, that said, im not completely sure whether lando is homebrew-ifiable because of some of its lower level requirements

**Comment by jordan8037310** [comment]
@pirog - looks like it was taken care of in the referenced request! I assume a new Pull Request just needs to be opened from time to time to update the cask to reference the new DMG.

Cheers

**Comment by pirog** [comment]
@jordan8037310 well ok then! that was easy :) huzzah!
