### ISSUE TITLE
Export a docker compose file based on .lando.yml to some folder

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#385]
Feature/Enhancement Request
===========================
As a developer I want to export my .lando.yml as a docker-compose.yml file to some location to share it with devops people for our online environments.

For our hosting party we want to export the chosen configuration we configured with lando more easily. So that we can send this to our devops guys to get it up and running in our production environments.
Now we have to search for it in some .lando user directory.

Something like 
`
lando docker-compose-export /some/folder/docker-compose.yml
`

**Comment by pirog** [comment]
@jbertoen can definitely see the value in this but given that we highly recommend that you don't use any of our images or docker compose files in production, or even outside of the lando context i dont think we want to encourage that with an explicit export command. 

thats said, looks like you already know where to look for the files we build anyway ;)
