### ISSUE TITLE
Feature request: add machine-identifying info to ssh key string on pantheon

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#388]
Feature/Enhancement Request
===========================

As a lando user who has multiple computers with lando installed, I want to be able to tell which SSH key was registered to pantheon on which machine, so I can remove the correct SSH key when retiring machines.

When lando registers an SSH key to pantheon, the **Account: SSH Keys** page simply shows "lando" for the key.  I have lando on three machines, so I have three instances of "lando" with no way to tell them apart.

It would be great if something like the machine name could be appended to "lando".

**Comment by pirog** [comment]
@ptmkenny this seems pretty trivial to add so why not. that said, what you really want to do is compare the key fingerprints. 

just because the comments for keys match up doesn't mean they are in fact the same key.
