### ISSUE TITLE
Private files not working on Drupal 8/Pantheon

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#396]
Bug Report
==========

lando beta 13, Windows 10 Pro

Drupal 8 site made on pantheon using the drops8/composer repo, not the pantheon recipe

Relevant configuration:

1. Set the download method to "private" here: /admin/config/media/file-system
2. Add an image field to a content type.  Choose to use private files. Unlimited values. Start uploading image files.
3. The first file will seem to work. Subsequent files will give an error:
`The upload directory private://2017-10 for the file field field_testimages could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled.`
Bug: In fact, you can't even save the node-- even if you don't ever try to add any images and the field is not required.  You get a `The file could not be uploaded.` error.

Carrying out the exact same steps on Pantheon dev server does not have any errors-- an unlimited number of images can be added to private files.

**Comment by pirog** [comment]
@ptmkenny what is the path for the private files directory?

**Comment by ptmkenny** [comment]
@pirog Private files path is `sites/default/files/private`

**Comment by spuky** [comment]
@ptmkenny are you on windows 10 ? reminds me of... https://github.com/kalabox/kalabox/issues/1740 which seems still to be present in lando...

**Comment by ptmkenny** [comment]
@pirog Yes I’m on Windows 10. I read the whole thread and it definitely
sounds like the same bug, particularly the very first upload working and
then all subsequent uploads failing.

2017年10月17日(火) 16:34 Thomas Speer <notifications@github.com>:

**Comment by ptmkenny** [comment]
As noted in the kalabox issue, issue [#944582](https://www.drupal.org/node/944582) on drupal.org has a patch that fixes this for Drupal 8 (latest patch) and Drupal 7 (patch #70).  I just tested it and it appears to work OK, will report back if any problems develop later.

This should definitely be mentioned in the docs.

**Comment by ptmkenny** [comment]
See here:

https://github.com/lando/lando/pull/416
