### ISSUE TITLE
Windows installer overwrites existing Docker

### ISSUE THREAD

**Issue by unknownterritory** [lando/lando#398]
lando-v3.0.0-beta.19.exe on Windows 10 Pro.

The current Windows Lando installer overwrites the installed Docker without giving an option. In the installer screen "Select Components", as opposed to "Git for Windows" that can be deselected, "Docker for Windows" appears greyed out and its selection is mandatory.
![print-screen of "select components" screen](https://user-images.githubusercontent.com/152997/31439002-6700c86c-ae3f-11e7-9225-aa6898bf983a.png)

As a developer I might have good reasons to keep my own installed version of Docker and I disagree in principle with any application that treats me as an incompetent user and modifies my setup without giving me a choice.

The installer should check for already installed Docker versions and not install new ones if it is not necessary. The ability to deselect "Docker for Windows" in the "Select Components" screen should be offered no matter what and, if the currently installed version is not suitable, the user should then be warned of potential issues.

This behaviour was [recently corrected in the MacOS installer](https://github.com/lando/lando/issues/355) and just needs to be ported to the Windows installer as well.

**Comment by pirog** [comment]
@unknownterritory thanks for opening this up. Def needs to happen!
