### ISSUE TITLE
Environmental variables not available in Behat?

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#403]
Bug Report
=======

I'm using beta17 on Windows 10 Pro.

I can access the `LANDO_HOST_IP` variable in `web/sites/default/drushrc.php` like this:

```
if (isset($_ENV['PANTHEON_ENVIRONMENT']) && $_ENV['PANTHEON_ENVIRONMENT'] == 'lando') {
  $options['uri'] = ${LANDO_HOST_IP};
}
```

This works great.

However, in `/tests/features/bootstrap/FeatureContext.php`, when I try to do the same thing, I get an error:

>       Notice: Use of undefined constant LANDO_HOST_IP - assumed 'LANDO_HOST_IP' in features/bootstrap/FeatureContext.php line 261

This is the code:

```
    public function iLogInAs($name) {
        if (isset($_ENV['PANTHEON_ENVIRONMENT']) && $_ENV['PANTHEON_ENVIRONMENT'] == 'lando') {
          echo("this is lando");
          $domain = ${LANDO_HOST_IP};
        }
        else {
          $domain = $this->getMinkParameter('base_url');
        }
```

I see the echo "This is lando" so I don't know why the environment variable is not available.

**Comment by pirog** [comment]
@ptmkenny as far as i know `${LANDO_HOST_IP}` is not a valid way to access an environment variable in PHP so i'm not surprised by this although not sure why it works in `web/sites/default/drushrc.php`. 

That said, Lando only injects into the ENV, its up to the user to retrieve them using the correct mechanism for the language or framework they are using. I'd recommend `getenv()` for php.

I'm going to close this for now. run `lando ssh -c "env"`. if you dont see the envvar you are looking for in there then this is a lando bug and feel free to reopen.
