### ISSUE TITLE
Lando clears Pantheon Live site cache without warning

### ISSUE THREAD

**Issue by jdleonard** [lando/lando#406]
Hey y'all!

I just installed v3.0.0-beta.20 (my first Lando install, wooooooo!) and ran `lando init --recipe pantheon` in an existing git repo working directory. I then ran `lando pull` and chose the "dev" environment for code and the "live" environment for db and files.

I was surprised to see the following output by the command:

> @pantheon.mysitename.live
> Clearing remote cache to shrink db size

I did not expect that pulling the database from the live site would result in the live site's cache being cleared. This could be a real problem for large scale websites that rely on high cache hit ratios.

At a minimum I would expect this to be clearly documented. Ideally, this would be a configurable option, hopefully with the less dangerous default of not clearing the remote environment's cache.

**Comment by ccharlton** [comment]
True.

I do believe on Pantheon, the db used for cloning & backups are from a warm slave.

**Comment by pirog** [comment]
@jdleonard @ccharlton this is great feedback and we will change the default behavior to not clear caches when you pull from live. 

That said, i think its worth noting two *ideal* best practices:

1. For the Pantheon site you really should be pulling from `dev` or `test` 
2. It should not be catastrophic to clear the `live` cache

**Comment by kylebehse** [comment]
Does anyone know if we have a lando-pantheon channel in either discord or telegram? ... And I don't mean one or the other, I mean a group where it's only people who use both lando with pantheon. 
Still having issues but don't want to congest this thread.
Cheers!

**Comment by reynoldsalec** [comment]
@kylebehse you can join the [Lando Slack](https://www.launchpass.com/devwithlando), but honestly if you're encountering something related to this issue, it's fine to have the conversation here.

FWIW, I took a quick look at [the pull.sh script](https://github.com/lando/pantheon/blob/main/scripts/pull.sh) for Pantheon and I don't see any cache clearing activity.
