### ISSUE TITLE
Terminus not upgraded in v3.0.0-beta.20

### ISSUE THREAD

**Issue by franciscoDeskmultimedia** [lando/lando#409]
Bug Report
==========

**Tell us about your setup**

Deepin OS last version.

What is your lando version and operating system?

v3.0.0-beta.20 on Deepin OS

**Tell us about the command you were running**

```bash
lando pull
lando start
```

**Tell us about the error you got**

Terminus still in v 1.5.0

lando pull
 [notice] Logging in via machine token.
 [notice] A new Terminus version v1.6.0 is available.
You are currently using version v1.5.0. 
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update

**Comment by pirog** [comment]
@franciscoDeskmultimedia you need to run `lando rebuild` to get updated images

**Comment by franciscoDeskmultimedia** [comment]
@pirog thanks , that did the trick.
