### ISSUE TITLE
EDGE SSL URLS/EDGE URLS not correct for Pantheon

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#414]
Bug Report
==========

Beta21 on Windows 10 Pro

Drupal 8 repo made with pantheon recipe

I really like the new breakdown of URLS by type on `lando start`, it's much easier to figure out what is what.

However, the SSL list is wrong for me (`https://MYSITE.lndo.site` is EDGE SSL but it is listed as EDGE URL):

```
 SERVICES       appserver, nginx, database, cache, edge_ssl, edge, index, mailhog, pma

 NGINX URLS     https://localhost:32786
                http://localhost:32787

 EDGE SSL URLS  https://localhost:32790

 EDGE URLS      http://localhost:32789
                http://MYSITE.lndo.site
                https://MYSITE.lndo.site

 MAILHOG URLS   http://localhost:32785
                http://mail.MYSITE.lndo.site
                https://mail.MYSITE.lndo.site

 PMA URLS       http://localhost:32784
                http://pma.MYSITE.lndo.site
                https://pma.MYSITE.lndo.site
```

**Comment by pirog** [comment]
This breakdown is accurate even if it seems wrong.

The named (eg non localhost) URLs routes through the non-ssl edge since the ssl termination is handled by the proxy and not the service itself in this case.
