### ISSUE TITLE
Backdrop Recipe PHP 5.3 Incompatibility 

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#418]
Bug Report
==========

**Tell us about your setup**

- Lando v3.0.0-beta.19
- Mac OS X 10.12.6
- Backdrop 1.8.0

**Tell us about your `.lando.yml`**

```
name: backdrop
recipe: backdrop
config:
  webroot: .
  php: '5.3'
  backdrush: 'dev'
```

**Tell us about the command you were running**

```
lando start || lando rebuild
```

**Tell us about the error you got**

```
PHP Parse error:  syntax error, unexpected '[' in phar:///tmp/drush.phar/includes/startup.inc on line 63
PHP Stack trace:
PHP   1. {main}() /tmp/drush.phar:0
PHP   2. require() /tmp/drush.phar:10
.....
  [UnexpectedValueException]                                                  
  Could not parse version constraint stable: Invalid version string "stable"  

```

**Tell us generally about your bug**

I think this relates to the short array syntax introduced in PHP 5.4 and the version of "backdrush" on my site. I tried the "dev" version of "backdrush" but still got the same error.  

Maybe have a "backdrush:none" option if Backdrop's version of Drush is finnicky...or turn it off by default.

The "UnexpectedValueException" seems like this could be entirely a backdrush thing as I had a different string than "stable" and still get that error without the "backdrush" key in my .lando.yml file.

**Comment by serundeputy** [comment]
Thanks @alexfinnarn 
yeah; Backdrop Drush requires Drush proper `8.x` and that requires PHP 5.4+.

The idea of `backdropdrush: 'none'`; is valid, but we wouldn't know that the user would be overriding to `php: '5.3'` ahead of time so they would still have to know to use the none option in there `.lando.yml` file.

I can look into a `none` option and maybe update the docs with the gotchya.

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/427

Runs drush in new `appserver_cli` container running php 5.5 when the appserver needs php 5.3.
