### ISSUE TITLE
Kint breaks lando share

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#421]
Note for the documentation-- It appears that when kint is enabled, if a request with Kint is loaded, `lando share` will break (seeing this on Drupal 8/Windows 10/beta20) with an error like this:

```
error:  Error: connection refused: localtunnel.me:40377 (check your firewall settings)
    at Socket.<anonymous> (C:\snapshot\cli\node_modules\localtunnel\lib\TunnelCluster.js:47:32)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

To fix this, all you have to do is stop debugging with kint.  I would be happy to add a note to the docs about this but I wanted to first make sure this is the expected behavior.

**Comment by pirog** [comment]
@ptmkenny i dont think "expected behavior" and "Kint" go together. I am definitely surprised that you are getting a firewall error from `lando share` when you run Kint but again, with Kint, you can never know. 

Can you consistently get this to break? Does Kint use a port or mess around with TCP at all?

**Comment by ptmkenny** [comment]
@pirog After looking into this more, it seems to happen intermittently and randomly on Windows, even when I'm not using kint.  I don't have a way to consistently reproduce this, so I'll close this for now and re-open if I find a guaranteed way to get the error.
