### ISSUE TITLE
Lando push defaults to pushing a database up to DEV (Pantheon recipe)

### ISSUE THREAD

**Issue by marklabrecque** [lando/lando#422]
After making some code changes and running `lando push` to deploy the code to the server, lando prompts the user where to push the database to, and it defaults to dev. The default to maintain best practices would be not to push the database on push to dev, so it would be advisable to change the default of this prompting to <none> instead of the current default of <dev>

Steps for reproduction.
1.  Bring up a lando environment.
2.  Run lando push.

**Comment by pirog** [comment]
@marklabrecque great suggestion and totally agree
