### ISSUE TITLE
Drush not bootstrapped while running commands from the host

### ISSUE THREAD

**Issue by robdecker** [lando/lando#426]
## .lando.yml
```yml
name: drushtest
recipe: drupal8
config:
  webroot: web
  xdebug: true
```

## Directory contents
```
$ ls -la
total 720
drwxr-xr-x@  21 rob  staff     672 Oct 23 09:17 .
drwxr-xr-x@  10 rob  staff     320 Oct 21 20:30 ..
drwxr-xr-x@  16 rob  staff     512 Oct 23 09:28 .git
-rw-r--r--@   1 rob  staff    2012 Oct 18 12:14 .gitignore
-rw-r--r--@   1 rob  staff    2162 Oct  5 13:55 .gitlab-ci.yml
drwxr-xr-x@   9 rob  staff     288 Oct 19 12:35 .idea
-rw-r--r--@   1 rob  staff      70 Oct 23 09:27 .lando.yml
-rw-r--r--@   1 rob  staff    1074 Oct  5 13:55 LICENSE
-rw-r--r--@   1 rob  staff     483 Oct  5 13:55 README.md
-rw-r--r--@   1 rob  staff    3948 Oct 18 12:09 circle.yml
-rw-r--r--@   1 rob  staff    4473 Oct 21 20:32 composer.json
-rw-r--r--@   1 rob  staff  328949 Oct 21 20:32 composer.lock
drwxr-xr-x@ 681 rob  staff   21792 Oct 21 20:32 config
drwxr-xr-x@   3 rob  staff      96 Oct  5 13:55 console
drwxr-xr-x@   4 rob  staff     128 Oct  5 14:25 drush
-rw-r--r--@   1 rob  staff     600 Oct  5 13:55 pantheon.yml
drwxr-xr-x@   4 rob  staff     128 Oct  5 13:55 patches
drwxr-xr-x@   5 rob  staff     160 Oct  5 13:55 scripts
drwxr-xr-x@   5 rob  staff     160 Oct  5 13:55 tests
drwxr-xr-x@  48 rob  staff    1536 Oct 20 14:05 vendor
drwxr-xr-x@  18 rob  staff     576 Oct 20 14:00 web
```

## App startup
```
$ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "drushtest_default" with the default driver
Creating volume "drushtest_appserver" with default driver
Creating volume "drushtest_data" with default driver
Creating volume "drushtest_data_database" with default driver
Creating drushtest_database_1 ...
Creating drushtest_appserver_1 ...
Creating drushtest_database_1
Creating drushtest_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5988k  100 5988k    0     0  3992k      0  0:00:01  0:00:01 --:--:-- 3992k
 PHP configuration      :  /usr/local/etc/php/php.ini
 PHP OS                 :  Linux
 Drush script           :  /tmp/drush.phar
 Drush version          :  8.1.13
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  652k  100  652k    0     0   251k      0  0:00:02  0:00:02 --:--:--  252k

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            drushtest
 LOCATION        /Users/rob/work/c3/c3.com/new/www
 SERVICES        appserver, database

 APPSERVER URLS  https://localhost:32793
                 http://localhost:32794
                 http://drushtest.lndo.site
                 https://drushtest.lndo.site
```

## `$ lando info`
```json
{
  "appserver": {
    "type": "php",
    "version": "7.1",
    "via": "apache",
    "webroot": "web",
    "config": {
      "conf": "/Users/rob/.lando/services/config/drupal8/php.ini"
    },
    "urls": [
      "https://localhost:32793",
      "http://localhost:32794",
      "http://drushtest.lndo.site",
      "https://drushtest.lndo.site"
    ]
  },
  "database": {
    "type": "mysql",
    "version": "latest",
    "creds": {
      "user": "drupal8",
      "password": "drupal8",
      "database": "drupal8"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32790"
    },
    "config": {
      "confd": "/Users/rob/.lando/services/config/drupal8/mysql"
    }
  }
}
```

## Drush
```bash
$ lando drush st
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :  /usr/local/etc/php/php.ini
 PHP OS                 :  Linux
 Drush script           :  /app/vendor/drush/drush/drush.php
 Drush version          :  8.1.15
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :
```
```bash
$ lando drush pml
Command pm-list needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.   
The drush command 'pml' could not be executed.
```

**Comment by serundeputy** [comment]
@robdecker you have a nested webroot; your drupal site is in `web` so you either have to `cd web` and then run `lando drush <command>` or specify the root:

```bash
lando drush --root=web <command>
```

Some users have configured there `.lando.yml` file like this:

```yml
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
```

in order to run drush from the project root rather than having to change to the web root.

**Comment by robdecker** [comment]
I'm totally ok with adding that extra bit to the config file. I had incorrectly assumed that having
```
config:
  webroot: web
```
in the `.lando.yml` would handle the drush routing.

Is there a reason why it doesn't?

**Comment by serundeputy** [comment]
This config:

```yml
config:
  webroot: web
```

tells `nginx` or `apache` where to serve from it doesn't tell drush anything.

**Comment by robdecker** [comment]
I understand that it tells `nginx` or `apache` where to serve from. But is there any reason why the `drush` service can't read that bit of config as well?

If not, the documentation at https://docs.devwithlando.io/recipes/drupal8.html (and the d7 recipe too) needs to include information about configuring `drush` so it works in nested file structures.

**Comment by dsnopek** [comment]
Would you consider changing this behavior with the Pantheon integration? Then it's reading the pantheon.yml and seeing the `web_docroot: true` and can use that to configure Drush. Then `lando drush` will operate basically the same as `terminus drush` too :-)

**Comment by jonathanjfshaw** [comment]
+1 for changing this; my expectation was that Lando would have taken care of configuring things so that "lando drush ... " worked out of the web root.

**Comment by pirog** [comment]
@jonathanjfshaw i assume you mean the actual root since `lando drush` does work out of the webroot?

im curious to here more about why people expect this behavior even when drush itself does not behave this way.

**Comment by jonathanjfshaw** [comment]
I meant "so that I didn't have to do 'cd web' before running 'lando drush ...' if I'm using a composery setup".

In my case it's because conceptually I think of drush as "doing a drush operation thingey on the site/database". It as little conceptual link with what exact folder I'm in. So I'm often falling over the fact that drush doesn't behave this way, and it would be nice if lando would help me out.

I guess that implies I think of Lando as being a magic fairy that takes all the pain out of setting up a Drupal work environment, implementing best practices and helpful OOTB setup. So my idea of a provided lando recipe should give is "what works best for the 80% use case". Something like that is what's in my mind I reckon.

Don't know if it's relevant, but posts like https://www.lakedrops.com/en/blog/post/configure-drush-drupal-8-work-project-root have people adding to their drushrc.php
```
if (file_exists('./web/index.php') && file_exists('./web/core')) {
  $options['r'] = realpath('./web');
}
```

**Comment by dsnopek** [comment]
> im curious to hear more about why people expect this behavior even when drush itself does not behave this way

The expectation that I have is that running `lando drush` should be the same as running `drush @lando` where '@lando' is an alias to the site I'm working on. Maybe I have that expectation because I'm used to using drush aliases and, well, I typed two words, 'drush' and 'lando' and I kinda feel like I've already done enough for the site to be bootstrapped? ;-)

> Im also curious about why you think settings this universally on the lando side is better than the user just configuring this behavior themselves

Since starting to use lando, I'm adding that configuration to every site that has a subdir as the docroot, and it'd be nice to not have to add it. I suppose someone could write a plugin that magically adds that?

**Comment by pirog** [comment]
So we've made some improvements to `drush` handling (see #542) but i don't think we are going to force a `--root=/path/to/webroot` behind the scenes. 

The good news is if you are using the new `drush: composer` setting which is now default for D8 recipes and installs the Drush Launcher then you will get a helpful message (via DL) about not detecting a drupal site

```php
if (!$drupalFinder->locateRoot($ROOT)) {
  echo 'The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:' . PHP_EOL;
  echo '  - Navigate to any where within your Drupal project and try again.' . PHP_EOL;
  echo '  - Add --root=/path/to/drupal so Drush knows where your site is located.' . PHP_EOL;
  exit(1);
}
```

I think that combined with the helpful comments here should be sufficient for the user to realize they are not in the correct directory and steps they can take if they want to set it up differently.

**Comment by robdecker** [comment]
@pirog From the command line, can I pass the path to the webroot? I like to setup bash scripts that I use to run numerous drush commands at will.

**Comment by AaronFeledy** [comment]
@robdecker If your scripts are running from within the appserver container, you can use `$LANDO_WEBROOT` to get the path to the webroot. Also, you may find [Lando Scripts](https://github.com/AaronFeledy/lando-scripts) useful.

**Comment by osopolar** [comment]
I have a drupal 7 installation, where I simply added drush via `composer require drush/drush:^8.1`. I also added the root option via tooling to my .lando.yml (docroot = /app):
```
name: myapp
recipe: drupal7
config:
  drush: composer
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app"
```
But it didn't work, `lando drush` (using drush-launcher) still can't find drush:

>The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
>  - Navigate to any where within your Drupal project and try again.
>  - Add --root=/path/to/drupal so Drush knows where your site is located.

**Comment by uberhacker** [comment]
Release rc.2+ way:
```
tooling:
  drush:
    service: appserver
    # run drush from any directory
    cmd: /path/to/drush --root=/app/docroot
```

**Comment by rotemreiss** [comment]
I'm trying Lando on Ubuntu 18.04 and I'm experiencing the same problems when running Drush from outside the docroot.
I must say that the same config works on Windows (without adding Drush to the tooling section).

When I'm adding Drush to the tooling section as suggested by @uberhacker I'm getting:
`OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec format error": unknown`
When doing `lando ssh` and running `./bin/drush --version` I'm getting those errors:
```
www-data@ba0114af5e4e:/app$ ./bin/drush --version
./bin/drush: line 1: XSym: command not found
./bin/drush: line 2: 0027: command not found
./bin/drush: line 3: ee9a19bed1b343bfd98987119dfecbf5: command not found
./bin/drush: line 4: ../vendor/drush/drush/drush: No such file or directory
```

Any suggestions why?
