### ISSUE TITLE
Mounting services from subfolder

### ISSUE THREAD

**Issue by floretan** [lando/lando#432]
As a user working with applications that often have multiple components in the same git repository, I would like to have the option to mount lando services from specific subfolders. 

For example suppose I have a drupal site and frontend application living at `/drupal` and `/frontend` respectively. I would like to be able to specify that my `appserver` service should only mount the `/drupal` subfolder and run composer commands inside of it, and similarly that my `node` service should only mount the `/frontend` subfolder. 

I currently have an issue with a concrete example where the frontend code is not in the project root. When trying to run `npm` through Lando's tooling feature I am unable to change the directory with the `cd` command directly from the `cmd` attribute, the only workaround that I found was to use an event (similar to https://docs.devwithlando.io/tutorials/setup-additional-tooling.html#multi-service-tooling-with-events even though I only need a single service).

**Comment by pirog** [comment]
@floretan as far as i know you should be able to set the appserver webroot to `/drupal`, if that doesn't work you can use our [advanced service configuration](https://docs.devwithlando.io/config/advanced.html) to get fine grained control over the volume mounting. 

Also pretty sure you can point your node service (which needs to be a separately defined service) at the other directory. 

Definitely have seen a few people do more or less this model for their headless drupal sites.

Re: `lando npm install`, can you not `cd` to the place where `package.json` is and then run `lando npm install`. I know that i often do this sort of thing for projects that have node deps inside of drupal themes. 

Perhaps posting up the lando file you are using would be illuminating
