### ISSUE TITLE
Developing offline not working.

### ISSUE THREAD

**Issue by taherj** [lando/lando#448]
Bug Report
==========

**Setup**

Lando version and operating system

v3.0.0-beta.22 on macOS High Sierra 10.13

**Local `.lando.yml`**

```yml
# Drupal 8 recipe
name: taher

# Start with the default Drupal 8 recipe
recipe: drupal8

# Configure the Drupal8 recipe
config:
  php: '7.1'
  via: nginx
  webroot: web
  drush: stable
  drupal: true
  database: mariadb:10.2
  xdebug: true
```

**What am I trying to do?**

Following the instructions for macOS verbatim from [Documentation](https://docs.devwithlando.io/tutorials/offline-dev.html)

**Error**

1. I have appended the following 👇  to my `/usr/local/etc/dnsmasq.conf`

`address=/local/127.0.0.1`

2. Restarted dnsmasq successfully using 👇 

`sudo brew services restart dnsmasq`

3. I have the following 👇 in my `~/.lando/config.yml` file

```yml
proxyDomain: local
```

 4. When I run the `lando start` as per step 8 from [Documentation](https://docs.devwithlando.io/tutorials/offline-dev.html) I get the following 

<img width="384" alt="error" src="https://user-images.githubusercontent.com/3863292/32216370-dc97c6dc-be4a-11e7-9dbf-fbc2f9305590.png">

Offline development using the domain name is not working locally for me.

**More Debugging Info**

1. The output of `lando info` in my apps directory (ran in a new terminal while the `lando start` command was stuck).

```json
{
  "appserver": {
    "type": "php",
    "version": "7.1",
    "via": "nginx",
    "webroot": "web",
    "config": {
      "server": "/Users/taher/.lando/services/config/drupal8/drupal8.conf",
      "conf": "/Users/taher/.lando/services/config/drupal8/php.ini"
    }
  },
  "nginx": {
    "urls": [
      "https://localhost:32895",
      "http://localhost:32896",
      "http://taher.local",
      "https://taher.local"
    ]
  },
  "database": {
    "type": "mariadb",
    "version": "10.2",
    "creds": {
      "user": "drupal8",
      "password": "drupal8",
      "database": "drupal8"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32859"
    },
    "config": {
      "confd": "/Users/taher/.lando/services/config/drupal8/mysql"
    }
  }
}
```
2. Not able to visit http://taher.local , https://taher.local

In Chrome I get the following

<img width="734" alt="chrome_error" src="https://user-images.githubusercontent.com/3863292/32216513-367beafc-be4b-11e7-9338-a94ec23e982f.png">

**Comment by hussainweb** [comment]
Unless I am mistaken, I think there is something missing in the documentation. The documentation only covers running a DNS server locally (dnsmasq), but does not talk about getting Mac OS X to find the nameserver. Most references I found about adding the TLD to `/etc/resolver/TLD` did not work for me.

After a bit of reading, I found that this address has to be added either via the System Preferences app (search for 'DNS') or the `networksetup -setdnsservers Wi-Fi 127.0.0.1` command.

**Comment by taherj** [comment]
@hussainweb 

Thank you for the analysis!

> After a bit of reading, I found that this address has to be added either via the System Preferences app (search for 'DNS') or the networksetup -setdnsservers Wi-Fi 127.0.0.1 command.

Is ☝️  working for you?

Unfortunately in my case when I add `127.0.0.1` as a DNS, All the internet pages throw up `DNS_PROBE_FINISHED_NXDOMAIN` error along with http://taher.local , https://taher.local

**Comment by hussainweb** [comment]
@taherj Yes, I tried it and it worked. Make sure that `127.0.0.1` is the first IP in the list. Double check with `scutil --dns`.

Also, try running `dig taher.local @127.0.0.1` to see if dnsmasq is working properly.

**Comment by hussainweb** [comment]
Okay, I reread and realised what happened. I should have clarified that add on `127.0.0.1` to output from existing entries from `networksetup -getdnsservers Wi-Fi`. Can you manually set it to your router's IP address for now?

e.g., `networksetup -setdnsservers Wi-Fi 127.0.0.1 192.168.0.1` Replace `192.168.0.1` with your router's address.

**Comment by hussainweb** [comment]
On further reading, I found that there is an issue with `.local` TLD ([not conclusive](https://askubuntu.com/a/81807)). In my case, `dig` was working fine but `ping` wasn't. Like suggested by the answer, I simply tried another TLD `.site`. Both `dig` and `ping` work fine now.

**Comment by hussainweb** [comment]
I see this documentation was added in #361 and the [link over there](https://passingcuriosity.com/2013/dnsmasq-dev-osx/) is the one I referred to as well. However, the documentation missed out on the last section which is to let OS X know to check dnsmasq as well.

**Comment by taherj** [comment]
@hussainweb 

Thank you for all of the above. 

After detailed debugging and following the steps mentioned I found 

1. We need to add the DNS to mac using `networksetup -setdnsservers Wi-Fi 127.0.0.1 192.168.0.1`
2. I was not restarting locally installed `dnsmasq` using `sudo`. Strangely restarting it without sudo does give a false positive. -- This was isolated by using dig.

I will supply a patch for the documentation inline with my learnings shortly.

**Comment by hussainweb** [comment]
I got stuck on the second issue as well. There is no error, but apparently it cannot bind to system ports as a regular user. It is an important gotcha for sure. :)

**Comment by Mchampsee** [comment]
Have you tried visiting http://localhost:32896 ?

**Comment by taherj** [comment]
@Mchampsee Yes http://localhost:32896 works.  
The goal here is to get the TLD to work while we are offline.

**Comment by Mchampsee** [comment]
Can I ask why? I had mentioned to @pirog that Kalabox didn’t work offline way back when so I assume access via localhost was their work-around.

**Comment by dustinleblanc** [comment]
I wrote that doc page, huh, weird. I ran through the whole thing and had no issues, but it may be because I had DNSMasq running previously and tore down / rebuilt, so maybe it had some preset magic going. It may also be possible that High Sierra changed something about the setup. The .local domain issue would definitely cause problems, but I've never, ever had to do the whole `networksetup -setdnsservers Wi-Fi 127.0.0.1 ` business, I'd question if that is necessary. The need to add sudo to the restart of DNSMasq could definitely have been something I missed.

**Comment by taherj** [comment]
@dustinleblanc Would you please inform which macOS version you are using for the documentation?

I understand the issue with the `.local` TLD. I have since changed it to `.dev`,`.site` and checked as well. It does not seem to work on any browser without adding the `127.0.0.1` to the DNS(see issue description for the screenshot of chrome error).

It is very probable this might be a macOS High Sierra specific issue. I would propose we keep the docs updated to include these edge cases as well. 

Thoughts??

**Comment by dustinleblanc** [comment]
I had no clue .dev was a no go, wowsers! I've been using that for quite some time (hence the documentation). All four of tld's they list as safe look absolutely lame, but I guess `.localhost` makes semantic sense...

I'd definitely support updating it so folks don't run into that issue. I like to err on the side of humor as the Lando team have, so pick something comical imo :1st_place_medal:

**Comment by jbertoen** [comment]
Definitely recommend .localhost as well.
What also might help with some dns issues on OSX is doing a
`dscacheutil -flushcache`

**Comment by jbertoen** [comment]
I can't get localhost working without doing the following steps:

    For OS X to resolve requests from *.local to localhost we need to add a resolver:
```

$ sudo mkdir /etc/resolver
$ sudo touch /etc/resolver/local
```

    edit /etc/resolver/local

`nameserver 127.0.0.1`

    re-start the computer to enable the resolver

**Comment by jbertoen** [comment]
@pirog, I updated the documentation to get it working on OS X and also added the recommendation to not use *.dev as a TLD for development.

**Comment by pirog** [comment]
@jbertoen awesome! thanks so much.

**Comment by kamalkech** [comment]
@jbertoen i had the same issue on archlinux (manjaro), there is another configuration for my system ??
