### ISSUE TITLE
Document installation of terminus plugins

### ISSUE THREAD

**Issue by ptmkenny** [lando/lando#454]
Feature/Enhancement Request
===========================

*Example: As a lando user who works with Drupal sites made using the pantheon recipe, I want to be able to run drupal console commands against my pantheon sites, not just my lando environment.

There is a drupal console plugin for Terminus that works like `terminus drush`:
https://github.com/pantheon-systems/terminus-drupal-console-plugin

It would be great if this could be included in the pantheon recipe.

**Comment by pirog** [comment]
@ptmkenny i dont think we want to pick and choose what terminus plugins we ship by default. I do think it would be a great idea to document how to easily add terminus plugins to your lando app though.
