### ISSUE TITLE
lando pull (Pantheon recipe) hangs if Terminus isn't installed

### ISSUE THREAD

**Issue by Shelob9** [lando/lando#463]
I am using Lando v3.0.0-beta.22 with Ubuntu 16.04 LTS. I ran `lando pull` for my Pantheon site. It got to the verifying details steps and then just stopped. No error, and it never stopped running.

I confirmed that Terminus wasn't installed, and then reinstalled and then the Lando Pull worked.

Aside: `lando pull` is an amazing feature, high five.

I suggest that Lando check if Terminus is installed properly and exit with a meaningful error if not.

**Comment by pirog** [comment]
@Shelob9 lando definitely installs (and uses) terminus for every pantheon recipe so im guessing you might have had a different issue

**Comment by Shelob9** [comment]
It's totally my fault that the pull didn't work. I had uninstalled
Terminus.

The bug I see here is that it didn't return an erorr telling me Terminus
isn't installed. I figured that out myself.

**Comment by pirog** [comment]
You actually went into the lando container that has terminus and removed it? 

Lando does not interact with or rely on any host level tools you have. everything lando uses is baked directly into our containers.

**Comment by Shelob9** [comment]
Oh, hmm. No I meant on host machine. I'm super confused now, as
reinstalling host machine Terminus did fix it...

--
JoshPress.net <http://joshpress.net/>
CalderaForms.com
CalderaLearn.com <https://learn.calderalabs.org>
CalderaLabs.org
@Josh412 <http://twitter.com/Josh412>

**Comment by danielrose28** [comment]
If I've ever run into any issues, usually running `lando rebuild` helps. I've had a similar issue but with mysql. During lando pull, when it got to the part for syncing the db, it kept saying unable to read mysql db or something. I just ran `lando rebuild` and it fixed it. Sometimes, if the service gets interrupted via internet outage or computer restart/shutdown, etc., it's helpful to just run `lando rebuild` or maybe even `lando restart`. Not saying that was your issue, but figured I'd throw in my 2 cents to maybe offer some sort of advice. :)

**Comment by pirog** [comment]
@Shelob9 yeah i am definitely able to run `lando pull` without having a installed-on-host-machine copy of `terminus`, which is the expected behavior. 

I'm *guessing* your issue was unrelated and just happenstance "fixed" by installing terminus. I know that `lando pull` can be fickle sometimes given the amount of moving parts and dependencies at play that are our of our control so @danielrose28's suggestions are good ones.

**Comment by Shelob9** [comment]
That makes sense. I'm assuming the two events are realated. They clearly or
not.

Again, thanks for this super awesome tool.
