### ISSUE TITLE
Linux .deb packaging - postrm is removing user configuration from home directory!?

### ISSUE THREAD

**Issue by frederickjh** [lando/lando#470]
Hi!
In examining the .deb of the [newest version of Lando](https://github.com/lando/lando/releases/tag/v3.0.0-beta.22) I found that on [line 13 of postrm](https://github.com/lando/lando/blob/a3be15f5f14c9d93b9e8cd3886447afd38fdffec/installer/linux/scripts/postrm#L13) the user configuration for Lando is being removed from their home directory.

`rm -rf "$HOME/.lando"`

This does not seem like it is correct. Programs should not be deleting a user's configuration for them that is in their home directory.

If a user installs Lando then changes their personal configuration then uninstalls it to install a new version they would lose all their configuration changes. This is not nice for the user.

Please consider removing this from the [postrm script](https://github.com/lando/lando/blob/a3be15f5f14c9d93b9e8cd3886447afd38fdffec/installer/linux/scripts/postrm).

Thanks for your consideration of this!
Frederick

**Comment by pirog** [comment]
@frederickjh, im guessing this is a hold over from our kalabox project which sadly required this for upgrading. 

Feel free to submit a PR that removes the line

**Comment by frederickjh** [comment]
@pirog I created pull request #475 to fix this issue for Linux and also for OSX.

**Comment by pirog** [comment]
Awesome! Merged this in and will roll it out in our next release.
