### ISSUE TITLE
Using "Custom" Version of mysql

### ISSUE THREAD

**Issue by dmott** [lando/lando#471]
I'm having a hard time finding any documentation on how to use "Custom" versions of services. In my case in particular, this is for mysql.

On the service page for mysql (https://docs.devwithlando.io/services/mysql.html) it lists the valid versions, and it shows "custom" as the final item in the list. I was able to get other versions to work using the following syntax in the `.lando.yml` file:

```
services:
  db:
    type: mysql:5.7
```

But when I try instead with `type:mysql:custom`, it (obviously) errors out with `ERROR: manifest for mysql:custom not found`

How, for example, would I go about using mysql 5.1 using the "custom" option? Yes, I know this is an old version of mysql, but there's a legacy setup I'm trying to recreate using Lando

**Comment by pirog** [comment]
@dmott you'll want to use "custom" in combination with https://docs.devwithlando.io/config/advanced.html (which is where you can specify the image/command etc you want to use). 

This is pretty advanced lando usage so while we open things up for you to configure things on this level, once you specify `custom` you are basically on your own.
