### ISSUE TITLE
Feature request: Disable recipe-provided tooling commands

### ISSUE THREAD

**Issue by jeffymahoney** [lando/lando#472]
Is it possible to put something in .lando.yml to prevent certain commands from being available? For example, I'd like to configure a Pantheon project so that developers can pull with Lando but not push.

**Comment by pirog** [comment]
@jeffymahoney i think you can just "override" the `push` functionality in the `.lando.yml` file. 

```yml
app: something
recipe: pantheon
config: whatevs
tooling:
  push: 
    cmd: echo "ACCESS DENIED!!!! MUAHAHAHA"
```

Of course, it would be super easy for the user to just remove this and gain access to the command again. 

Another way to get around this sort of thing is to use GitHub as the canonical upstream and have some build process (eg travis or circle) be the thing that deploys to pantheon. That way you can disable developer access to the Pantheon side of things and use GitHub's branch protection and PR workflow to control how code gets up to Pantheon.

**Comment by jeffymahoney** [comment]
Thanks a lot, Mike. That's exactly the info I needed.

**Comment by jeffymahoney** [comment]
Ah, I see that you reopened this. I closed it without trying first. I just tried to do lando push with this config and the command still asks me the first question, "What did you change? (My awesome Lando-based changes)". I didn't proceed past that.

**Comment by pirog** [comment]
@jeffymahoney yeah i think you might need to just "replace" the options the command defines. Here is where we define it programmatically:
https://github.com/lando/lando/blob/master/plugins/lando-recipes/pantheon/pantheon.js#L313

Reopened the issue because i think we should document that these commands are overridable somewhere.

**Comment by jeffymahoney** [comment]
Thanks. I can't figure out a way to override the push command. No matter what I try, the first question, "What did you change?" always comes up.

**Comment by pirog** [comment]
I think you'd want to blank out all the interactive options. That said, as long as you replace the `cmd` you should be fine, eg it might still prompt you for input but its not going to use it for anything.

**Comment by jeffymahoney** [comment]
That's what I figured. I just couldn't figure out how to blank them out. Perhaps I did something wrong, not sure.

I tried this and some variations of it:

```
tooling:
  push: 
    cmd: echo "ACCESS DENIED!!!! MUAHAHAHA"
    options:
      message: {}
      database: {}
      files: {}
```

**Comment by serundeputy** [comment]
@pirog I'm having trouble overriding the `push` command as well; whereas I can override the `php` command:


Here is a snippet from my `.lando.yml` `tooling` section:

```yml
 35   push:
 36     service: appserver
 37     description: no
 38     cmd: echo "ACCESS DENIED!!!! MUAHAHAHA" && exit;
 39     options:
 40       passthrough: true
 41       push:
 42         message: ''
 43         files: none
 44         database: none
 45         code: none
 46   php:
 47     service: appserver
 48     description: geoff is the best!
 49     cmd: echo "\n\n\t\tno.\n\n"
```

and the output from `lando php`:

```bash
geoff@yep 472 (master) $ lando.dev php
"

		no.

"
geoff@yep 472 (master) $
```

and `lando push`

```bash
geoff@yep 472 (master) $ lando.dev push
? What did you change? (My awesome Lando-based changes)
```

still prompting for the non-overridden `push` command options, but the `description` key is respected:

```bash
geoff@yep 472 (master) $ lando.dev
Usage: /usr/local/bin/lando.dev <command> [args] [options] [-- global options]

Commands:
  php                      geoff is the best! 
  push                     no
```

**Comment by pirog** [comment]
@jeffymahoney @serundeputy ok, tried this out and its *doable* but definitely not easy. I think it might be easier to turn this into a feature request so users can easily disable built-in lando tooling commands since that seems like it's actually pretty trivial.

**Comment by jeffymahoney** [comment]
Thanks Mike :)

**Comment by TMFEspresso** [comment]
@pirog This seems to be not working properly when applied like this:

```
recipe: wordpress
tooling:
  'db-import <file>': disabled
```

Though you can definitely append/override what is there:

```
tooling:
  'db-import <file>':
    description: Downloads a database dump from our host to <file> and imports <file>
    options:
      full-database:
        description: Includes the logging tables in the database backup.
        alias:
        - f
        boolean: false
```

it shows up like this in the terminal:

```
lando db-import --help
lando db-import <file>

Downloads a database dump from our host to <file> and imports <file>

Options:
  --clear              Clears the lando tasks cache                                 [boolean]
  --help               Shows lando or delegated command help if applicable          [boolean]
  --verbose, -v        Runs with extra verbosity                                      [count]
  --full-database, -f  Includes the logging tables in the database backup.
  --host, -h           The database service to use                      [default: "database"]
  --no-wipe            Do not destroy the existing database before an import        [boolean]

Not enough non-option arguments: got 0, need at least 1
```

So this may need to be revisited.

**Comment by pirog** [comment]
My guess would be that this is an edge case failure caused by the
db-import/export commands requiring an argument

**Comment by TMFEspresso** [comment]
It actually has weirder behaviors if you do it with other commands.

.lando.base.yml
```
recipe: wordpress
...
tooling:
...
  php: disabled
  init: disabled
  start: disabled
  share: disabled
```

terminal:
```
$ lando --clear
Lando has cleared the tasks cache!
$ lando
Usage: lando <command> [args] [options]

Commands:
  lando calrissian        Runs calrissian commands
  lando composer          Runs composer commands
  lando config            Displays the lando configuration
  lando db-download       Downloads a database dump from WPEngine
  lando db-export [file]  Exports database from a database service to a file
  lando db-import <file>  Downloads a database dump from WPEngine to <file> and imports
                          <file>
  lando destroy           Destroys your app
  lando info              Prints info about your app
  lando init              Runs init commands
  lando init              Initializes code for use with lando
  lando initial-setup     Gets ran once, directly after cloning down the Lando-localdev
                          project
  lando list              Lists all running lando apps and containers
  lando logs              Displays logs for your app
  lando mysql             Drops into a MySQL shell on a database service
  lando php               Runs php commands
  lando poweroff          Spins down all lando related containers
  lando rebuild           Rebuilds your app from scratch, preserving data
  lando restart           Restarts your app
  lando share             Runs share commands
  lando share             Shares your local site publicly
  lando ssh               Drops into a shell on a service, runs commands
  lando start             Runs start commands
  lando start             Starts your app
  lando stop              Stops your app
  lando version           Displays the lando version
  lando wp                Runs wp commands
```

**Comment by pirog** [comment]
Looks like this is actually a regression, changing to bug.

**Comment by pirog** [comment]
Alright, this should be REFIXED in the next release
