### ISSUE TITLE
Feature Request: Pass custom per user global env variables into containers

### ISSUE THREAD

**Issue by jodyHamilton** [lando/lando#473]
Motivation: I want to pass user-level variables into all the containers. My usecase is that we all connect to our servers with our own username, so I need to use a username variable in all drush alias files for every project.

I was able to add custom env variables into ~/.lando/config.yml as
```
env:
  foo: bar
```
It did merge it into the env section in lando config. But it did not pass it into the containers. Looks like the env passed to the containers is defined in https://github.com/lando/lando/blob/master/plugins/lando-core/lib/env.js

**Comment by serundeputy** [comment]
Hi @jodyHamilton I think you should be able to accomplish this with a `.env` file: https://docs.devwithlando.io/config/env.html#environment-file

**Comment by jodyHamilton** [comment]
Can I put a .env file into ~/.lando ? I thought it was per-app I would have to add the .env file.

**Comment by serundeputy** [comment]
@jodyHamilton Yes; per app `.env` files.  I misunderstood.  You are looking for a global `lando` wide (across all apps) env vars.

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/479

Add a `.global_env` file in `~/.lando/` and add your global per user `env` vars in that file.
If there is a collision of vars in `~/.lando/.global_env` and `.env` the `.env` app local file wins, i.e. the app can override the globals.

**Comment by jodyHamilton** [comment]
Thank you! I don't know if it's easy for me to test the change or if I should just wait for a release.

**Comment by serundeputy** [comment]
if you install from source and pull down the latest `master` && `npm install` you can test.

**Comment by serundeputy** [comment]
@jodyHamilton testing it would be super helpful!

I have a `lando.dev` installation from source that lives side by side my `lando` install.
Then make a symlink to `lando.dev`

```bash
lrwxr-xr-x  1 geoff  admin    40B Jun  9 17:59 /usr/local/bin/lando.dev -> /Users/geoff/code/lando.dev/bin/lando.js
```
