### ISSUE TITLE
Doc Fix: Remove references to drush on Joomla tutorial

### ISSUE THREAD

**Issue by jodyHamilton** [lando/lando#476]
https://github.com/lando/lando/blob/master/docs/tutorials/joomla.md

Looks like the joomla stuff is supporting a joomla cli, but there are some references to 'drush' on this page that should probably get changed to 'joomla'

**Comment by serundeputy** [comment]
@jodyHamilton good catch!
PR: https://github.com/lando/lando/pull/477

**Comment by pirog** [comment]
@jodyHamilton @serundeputy oh no! We definitely cannot be diluting the code purity that is Joomla with such unclean Drupal/Drush-isms.
