### ISSUE TITLE
Running into a curl error

### ISSUE THREAD

**Issue by Mchampsee** [lando/lando#483]
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.
2.  Please tag your issue appropriately. Please review the [tagging criteria](https://docs.devwithlando.io/dev/contributing.html).
3.  Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**
Lando version: v3.0.0-beta.22
Mac OS X: 10.13.1
What is your lando version and operating system?

*Example: v3.0.0-alpha1 on Windows 10 Professional*

**Tell us about your `.lando.yml`**
`
`
Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: lc2
recipe: wordpress
config:
  webroot: .
```

**Tell us about the command you were running**

 `lando init` to setup stock WordPress install. 
Copied over the code into the directory 
`lando start`. Everything looked fine -see below
website shows database connection error
`lando rebuild`

```
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting lc2_database_1 ... 
lc2_appserver_1 is up-to-date
Starting lc2_database_1 ... done
BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            lc2                                  
 LOCATION        /Users/admin/Dropbox/local-sites/lc2 
 SERVICES        appserver, database                  
                                                      
 APPSERVER URLS  https://localhost:32795              
                 http://localhost:32796               
                 http://lc2.lndo.site:8000            
                 https://lc2.lndo.site:444            
 
```

**Tell us about the error you got**

`lando rebuild` yielded what is below

```
Stopping lc2_appserver_1 ... done
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Recreating lc2_database_1 ... 
Starting lc2_appserver_1 ... 
Starting lc2_appserver_1
Recreating lc2_database_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (23) Failed writing body (2180 != 2759)
error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (23) Failed writing body (2180 != 2759)
, code=23

```

**Tell us generally about your bug**

Database doesn't initiate.

**Comment by Mchampsee** [comment]
I shutdown some services, restarted by computer and reset Docker and now databases are coming up for me. I did some googling on others who were getting the same curl error. I have a 5 year old machine and at times spotty internet. My sense is that in bringing up the database container, there is something that runs after another process and in my case it isn't waiting long enough to kick-off because its taking my machine longer than most to do that step.

**Comment by pirog** [comment]
@Mchampsee yeah that is certainly possible. Lando does do more internet-y things than kalabox esp during an initial spin up. I've seen some curlish issues becuse of some proxy weirdness
https://docs.devwithlando.io/issues/proxy.html but im guessing that is different
