### ISSUE TITLE
Cannot pkg on OSX

### ISSUE THREAD

**Issue by fwartner** [lando/lando#484]
I cannot build the pkg using `grunt pkg` on OSX..

Here´s the output:

```bash
mv: rename ../../../lando to ./lando: No such file or directory
+ cd mpkg/docker.pkg
./scripts/build-osx.sh: line 52: cd: mpkg/docker.pkg: No such file or directory
+ sed -i '' -e s/%DCKN_VERSION%/1.0.0/g mpkg/Resources/en.lproj/Localizable.strings mpkg/Resources/en.lproj/welcome.rtfd/TXT.rtf mpkg/Distribution
sed: can't read : No such file or directory
sed: can't read mpkg/Resources/en.lproj/Localizable.strings: No such file or directory
sed: can't read mpkg/Resources/en.lproj/welcome.rtfd/TXT.rtf: No such file or directory
sed: can't read mpkg/Distribution: No such file or directory
```

Can anyone help me out?

**Comment by pirog** [comment]
Hey @fwartner we run this command on OSX/Linux/Winows on every build so it *should* work as is. It's possible you've modified something that causes it to no longer work. 

I'd check out the following things that might help
https://travis-ci.org/lando/lando
https://github.com/lando/lando/blob/master/.travis.yml
https://docs.devwithlando.io/dev/building.html

Beyond that i dont think we intend to offer much support around this beyond what is already documented.
