### ISSUE TITLE
Vanity HTTPS Appserver URL Blocks Loading of Assets - Drupal 7 Recipe

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#486]
Bug Report
==========

**Tell us about your setup**

Lando: v3.0.0-beta.22
Drupal: 7.56
Mac OS: 10.12.6
Chrome: 61.0.3163.100

**Tell us about your `.lando.yml`**

```yaml
name: express
recipe: drupal7
config:
  webroot: .
```
**Commands**

```bash
lando init express --recipe drupal7
lando start
# Install Drupal via admin GUI.
# https://express.lndo.site:444 doesn't load CSS/JS.
```

**Tell us about the error you got**

```
Mixed Content: The page at 'https://express.lndo.site:444/' was loaded over HTTPS, but requested an insecure stylesheet 'http://express.lndo.site:444/modules/system/system.base.css?oz7p5o'. This request has been blocked; the content must be served over HTTPS.
```

**Tell us generally about your bug**

The localhost secure URL seems to work, e.g. "https://localhost:32778", but the vanity URL doesn't load assets, e.g. "https://express.lndo.site:444". I have tried this with the Backdrop recipe as well, nothing more than standard install, and got the same results. 

If I manually set the base URL `$base_url = 'https://' .  $_SERVER['HTTP_HOST'];` then the vanity URL does load the assets. 

**Screenshots**

https://express.lndo.site:444
<img width="820" alt="screen shot 2017-11-10 at 10 30 42 am" src="https://user-images.githubusercontent.com/3640707/32670829-429deb28-c602-11e7-88aa-0bcb172b2b76.png">

https://localhost:32778
<img width="736" alt="screen shot 2017-11-10 at 10 31 20 am" src="https://user-images.githubusercontent.com/3640707/32670854-5420cef6-c602-11e7-860b-bc34a892c8e8.png">

**Comment by pirog** [comment]
@alexfinnarn ok i can definitely replicate this and provide a bit more detail. I think the reason why i (or @dustinleblanc) havent seent his previously is we generally are using the pantheon recipe which sets the following automatically:

```php
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
  $_SERVER['HTTPS']='on';
}
```

Going to move this into the current sprint

**Comment by alexfinnarn** [comment]
cool. I can test the PR, if needed...or the documentation update if it is a manual step.

**Comment by pirog** [comment]
@alexfinnarn looking to see if there is some automatic way to handle this but will let you know!

**Comment by dustinleblanc** [comment]
I guess I assume *everyone* is on the Pantheon recipe :)

**Comment by pirog** [comment]
ok @alexfinnarn this should be dialed for the next release
