### ISSUE TITLE
Can't Init Pantheon Site "Operation not Permitted"

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#488]
Bug Report
==========

I'm running Mac OSX Sierra
I'm using Lando 3.0.0.22 beta

I have no lando config/.yml file

I'm having issues with spinning up a Pantheon site from an existing code base. I was following the instructions from option 3 of the Getting Started guide.
I ran mkdir foldername && cd foldername
I then ran lando init pantheon. I tried running this command with 'sudo' but got the same result.

**Error output**

```landoinitbenjaminc_util_1 is up-to-date
Scanning /user/.ssh for keys...
chown: changing ownership of '/user/.ssh/config': Operation not permitted
error:  message=Scanning /user/.ssh for keys...
chown: changing ownership of '/user/.ssh/config': Operation not permitted
, code=1
```
Because of this issue, I cannot use Lando

**Comment by pirog** [comment]
@digisavvy the obvious guess here would be that you've got something funky going on with `~/.ssh/config` presumably with its permissions or ownership.

**Comment by digisavvy** [comment]
Just adding the fix for this. The error is self-explanatory. Lando requires .ssh/config ownership to not be the `root` user, which it was set to in my case. Running chown on config and changing it to the system user (in MacOSx I just used my username).
