### ISSUE TITLE
Terminus updated to 1.6.1

### ISSUE THREAD

**Issue by bsnodgrass** [lando/lando#490]
Using recipe for Pantheon in README.md
on Lando v3.0.0-beta.22

for terminus commands I get:
```
 [notice] A new Terminus version v1.6.1 is available.
You are currently using version v1.6.0. 
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update
```

https://github.com/lando/lando/search?p=1&q=terminus+version&type=&utf8=%E2%9C%93

Needs update and what is the process for updating Terminus once Lando recipe is installed?

Thanks!

**Comment by serundeputy** [comment]
@bsnodgrass this is merged 5de6a7bea009595650dd19ba7b28ddb67a05900a and will likely be available in the next release.  Once that release is out and you update lando then you can issue `lando rebuild` on your app to get the latest and greatest terminus.

**Comment by bsnodgrass** [comment]
Great thanks!

**Comment by pirog** [comment]
@bsnodgrass ditto @serundeputy that said you can definitely use the normal terminus upgrade method from inside of lando to upgrade in the meantime. guessing it is something like

```
lando ssh -c "cd /tmp && curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update"
```
