### ISSUE TITLE
WordPress: Doesn't work with Bedrock framework

### ISSUE THREAD

**Issue by elliottmangham** [lando/lando#499]
**Description**
I have initialised sites for WordPress and Lando works well, however, it doesn't work when I try to create a site using the popular *[Bedrock](https://github.com/roots/bedrock/issues/new)* framework for WordPress.

Please, can somebody look into the issue, as there seems to be some MySQL issue when using Bedrock. I use Bedrock for all my sites, as do many WordPress developers - so I would love to see Lando support this.

**Setup**
Lando _v3.0.0-beta.22_ on macOS High Sierra.
Computer specs: 16 GB memory and 3.1 GHz Intel Core i7 processor.

**`.lando.yml`**
```yml
name: example-project
recipe: wordpress
config:
  webroot: web
```
This has NOT been modified. This is as it was created during `lando init --recipe wordpress`

**Tell us about the command you were running**

```bash
lando init mysite --recipe wordpress --webroot web
lando start
```
Also tried with the `lamp` recipe...

**The issue**
When I open the URL in the browser, I am presented with the error below - as opposed to the database creation page that WordPress would normally present you with.

*Error:*
```
Warning: mysqli_real_connect(): (HY000/2002): Connection refused in /app/web/wp/wp-includes/wp-db.php on line 1603 Call Stack: 0.0011 358144 1. {main}() /app/web/index.php:0 0.0024 358432 2. require('/app/web/wp/wp-blog-header.php') /app/web/index.php:5 0.0030 358784 3. require_once('/app/web/wp/wp-load.php') /app/web/wp/wp-blog-header.php:13 0.0065 359128 4. require_once('/app/web/wp-config.php') /app/web/wp/wp-load.php:42 0.0324 372688 5. require_once('/app/web/wp/wp-settings.php') /app/web/wp-config.php:9 0.0672 714000 6. require_wp_db() /app/web/wp/wp-settings.php:106 0.0682 726992 7. wpdb->__construct() /app/web/wp/wp-includes/load.php:404 0.0682 727776 8. wpdb->db_connect() /app/web/wp/wp-includes/wp-db.php:658 0.0685 728240 9. mysqli_real_connect() /app/web/wp/wp-includes/wp-db.php:1603
```

*Screenshot:*
![screenshot](https://user-images.githubusercontent.com/12933804/32838459-e6214bfa-ca08-11e7-93f9-26db3fc1641e.png)

**Comment by pirog** [comment]
@elliottmangham this seems more like an application configuration issue than a lando issue.

**Comment by elliottmangham** [comment]
Hi @pirog, I don't think so as I tried this as a fresh installation of WordPress using Bedrock, so no configurations were made.

If I do this on MAMPS, AMPPS, Flywheel, Docker or Vagrant etc. this works perfectly. This leads me to believe it's a Lando related issue, as Bedrock (like stabdard WordPress) should work out of the box.

According to Lando documentation, PHP environment variables are created automatically on init. Where are these stored? I ask, because Bedrock allows you to use an '.env' file to store PHP variables. This may be possibly be conflicting.

It would be great if somebody with both WP and Lando experience could attempt to install Bedrock and see if the same problem arises, and if so, can provide a solution.

Thanks in advance.

**Comment by pirog** [comment]
@elliottmangham yup i think you've hit the nail on the head although my guess is that you probably just want to tweak your ENVVARS on the app side vs us making a change to lando. 

So on the lando side we set ENVVARS for WordPress
https://docs.devwithlando.io/tutorials/wordpress.html#environment-variables

We also allow for envvars to be loaded via `.env` 
https://docs.devwithlando.io/config/env.html#environment-file

Looks like bedrock makes use of the same file
https://github.com/roots/bedrock/blob/master/.env.example

So *my guess* is that your bedrock `.env` is overriding our envvars, specifically the ones that contain the DB connection data, and that is your issue. 

I think the way to get around that is either don't specify any `DB_*` envvars in your `.env` file and let lando handle it, or put the correct values into the `.env` file (you can use `lando info` to find DB credential)

I'm not really sure what we would change on the lando side of things beyond maybe dropping a note in our WordPress docs with this caveats for Bedrock users

**Comment by matthistuff** [comment]
I am running multiple large Bedrock installations using lando for local development. As @pirog stated, the easiest way (and the only I would recommend) is to simply omit any `DB_` variables from the `.env` file. dotenv will load the correct values from the environment variables set by lando. This way you do not have to worry about the credentials, it's all managed for you by lando. It makes working with other developers easier too.

**Comment by elliottmangham** [comment]
Hi @pirog and @matthistuff,

Thanks both for getting back to me.

I have tried as you suggested, however, all three of the below didn't work:

-  Commented out `DB_*` variables from my `.env` file
-  Removed the `.env` file altogether
-  Input correct credentials into `.env` file, from running `lando init` (as below)

```
DB_NAME=wordpress
DB_USER=wordpress
DB_PASSWORD=wordpress
DB_HOST=database
# DB_PREFIX=wp_
```

I have also attempted restarting my Lando app, but I get the same MySQL error as above.

Do you have any other suggestions?

Here is a quick overview of my actions:
```bash
composer create-project roots/bedrock project-name
cd project-name
lando init mysite --recipe wordpress --webroot web
lando start
```

Warmest regards,

**Comment by matthistuff** [comment]
@elliottmangham, I just tried it out on a fresh install with the steps you mentioned.

What I did is:

```shell
composer create-project roots/bedrock project-name
cd project-name
lando init mysite --recipe wordpress --webroot web
```

The composer create-project will have set up a basic `.env` file for you. I opened this file and removed all the `DB_` vars and updated the `WP_HOME` variable. This is vital! If you use no custom proxy you can use the `.lndo.site` domain.

After saving the `.env` file I started lando.

For reference, this is my final .env file:

```
  1 WP_ENV=development
  2 WP_HOME=http://yoursitename.lndo.site
  3 WP_SITEURL=${WP_HOME}/wp
  4 
  5 # Generate your keys here: https://roots.io/salts.html
  6 AUTH_KEY='generateme'
  7 SECURE_AUTH_KEY='generateme'
  8 LOGGED_IN_KEY='generateme'
  9 NONCE_KEY='generateme'
 10 AUTH_SALT='generateme'
 11 SECURE_AUTH_SALT='generateme'
 12 LOGGED_IN_SALT='generateme'
 13 NONCE_SALT='generateme'
```

Please remember, if you are editing the `.env` file for a running lando site, you will have to restart the instance since both Bedrock and Lando read from the same file which is a bit unfortunate.

**Comment by elliottmangham** [comment]
Hi @matthistuff,

Thanks again for your support.

I followed you above guide step-by-step, and weirdly, I still have the same issue.

This leads me to believe it's my local-setup - perhaps other development environments I have had in the passed are conflicting?

Will try on another computer!

**Comment by pirog** [comment]
followed the steps outlined here and it works as expected for me as well. 

going to close this since i am *pretty sure* this is not something actionable on the lando side unless someone here wants to open a PR with some notes to add to the wordpress docs about this

**Comment by elliottmangham** [comment]
Okay, at least I know it's my set-up!

Thanks a lot for the help @pirog and @matthistuff, I appreciate the speedy support.

**Comment by elliottmangham** [comment]
Hi, @pirog and @matthistuff,

I understand the issue is now closed.
But I reset my Docker settings and attempted to install Bedrock again. This time, it didn't have that error I had before, connecting to the database - but rather:

```
Not Found
The requested URL /wp/wp-admin/install.php was not found on this server.
```

<img width="795" alt="screen shot 2017-11-24 at 19 23 09" src="https://user-images.githubusercontent.com/12933804/33222174-1b939efa-d14d-11e7-9b8d-3d2d206b463a.png">

If I go to my site domain `http://test.lndo.site/`, I get a simple `It works!` page, but nothing more.

<img width="780" alt="screen shot 2017-11-24 at 19 25 53" src="https://user-images.githubusercontent.com/12933804/33222200-50f36de6-d14d-11e7-9fa2-3af88ce2195e.png">

I can connect to the database via Sequel Pro, using the external connection details after running `lando info`, so things are ticking - I just can't do anything.

Any help is extremely appreciated, thank you!

**Comment by matthistuff** [comment]
@elliottmangham, can you please paste your `.lando.yml`.

**Comment by elliottmangham** [comment]
@matthistuff, it is as follows:
```yml
name: test
recipe: wordpress
config:
  webroot: web
```

Thanks,

**Comment by labboy0276** [comment]
I am seeing odd things using bedrock as well.

When I try to run lando start on a site with an existing .env, utilizing bedrock it gets confused with the SECURE_AUTH_KEY in the .env file:

```bash
`john@tandem:~/lando/devwithlando$ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
WARNING: The Aq variable is not set. Defaulting to a blank string.
WARNING: The Bq variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "appserver": "P<|ziY*,^Nny98$~3[-vW{GoS4;u(]Q:SU<v_JAK,O+a#odkU.RlhN+%UUrz`U:G"
WARNING: The Aq variable is not set. Defaulting to a blank string.
WARNING: The Bq variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "appserver": "P<|ziY*,^Nny98$~3[-vW{GoS4;u(]Q:SU<v_JAK,O+a#odkU.RlhN+%UUrz`U:G"
WARNING: The Aq variable is not set. Defaulting to a blank string.
WARNING: The Bq variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "appserver": "P<|ziY*,^Nny98$~3[-vW{GoS4;u(]Q:SU<v_JAK,O+a#odkU.RlhN+%UUrz`U:G"
WARNING: The Aq variable is not set. Defaulting to a blank string.
WARNING: The Bq variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "appserver": "P<|ziY*,^Nny98$~3[-vW{GoS4;u(]Q:SU<v_JAK,O+a#odkU.RlhN+%UUrz`U:G"
WARNING: The Aq variable is not set. Defaulting to a blank string.
WARNING: The Bq variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "appserver": "P<|ziY*,^Nny98$~3[-vW{GoS4;u(]Q:SU<v_JAK,O+a#odkU.RlhN+%UUrz`U:G"
error:  Error: Error: 1
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:0:0)
    at /snapshot/cli/lib/promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by labboy0276** [comment]
checkout this forked version of bedrock I made for Lando, et al: https://github.com/thinktandem/bedrock

**Comment by matthistuff** [comment]
@elliottmangham, @labboy0276 I didn't have enough time the last days to look into the issue really deep. A big problem seems to be the general usage of a `.env` file by both projects. `.env` is also used by docker compose by default. I suggest opening an issue for bedrock to rename the `.env` file and see how they respond.

**Comment by labboy0276** [comment]
@matthistuff I doubt they will do anything.  If you look at the fork I made, I negate the .env file and make it so we can use bedrock on a few platforms.

**Comment by Ciul** [comment]
@elliottmangham have you tried installing bedrock in a subfolder from the lando project folder.
e.g. 
```
name: test
recipe: wordpress
config:
  webroot: bedrock/web
```

**Comment by techieshark** [comment]
Solution from @Ciul worked for me.

+ In bedrock/web, set .env based on `lando info`, like:

```
DB_NAME='wordpress'
DB_USER='wordpress'
DB_PASSWORD='wordpress'

DB_HOST='database'

WP_ENV='development'
WP_HOME='http://name-from-lando-yaml.lndo.site'
WP_SITEURL="${WP_HOME}/wp"
# In container, send debug.log to stdout to be collected by Docker host.
# https://serverfault.com/a/738509
# or try https://serverfault.com/a/932888
# (not sure if this is necessary but let's try it)
WP_DEBUG_LOG=/proc/self/fd/2

# Generate your keys here: https://roots.io/salts.html
# ...add yours here
```
