### ISSUE TITLE
Duplicate Links To Services Overview In Docs

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#504]
**Documentation Update**

On https://docs.devwithlando.io/#and-then-dive-deep-into-reference-materials, the link to the reference materials for "Recipes" links to the "Services" page. This might be intentional, but as a user, it confuses me. 

If the docs for that aren't ready for recipes yet (https://github.com/lando/lando/blob/master/docs/dev/recipes.md), I think a standalone Recipes page would make sense even if it just says "@todo make this page."

**Comment by pirog** [comment]
@alexfinnarn i think this is just a copy/paste fail. Good catch.
