### ISSUE TITLE
Remove All Traces Of Lando On Uninstall

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#505]
**Documentation Update**

I have an issue with Lando that might relate to updating, de-upgrading, re-upgrading my install several times. Usually, when this happens with development tools, the answer can be to uninstall and reinstall the tool. 

I'm trying to follow https://docs.devwithlando.io/installation/uninstalling.html to completely remove Lando and reinstall in hopes that will magically fix an issue I have. 

In the #lando Slack channel, I saw someone suggest `rm -rf ~/.lando/services/config` to potentially fix an issue so I went to 11 with `rm -rf ~/.lando`. I know those 4 steps listed in the help article for Mac OS don't remove some files on your local machine.

 I'd like to see complete uninstalling steps so at the end you have no trace of Lando since he is a scoundrel and can't be trusted.

**Comment by alexfinnarn** [comment]
What I did:
- On lando-v3.0.0-beta.24
- Run "uninstall:command"
- Remove "~/.lando/*"
- Reinstall lando-v3.0.0-beta.24

```bash
$ lando
 Error: EISDIR: illegal operation on a directory, open '~/.lando/services/config/scripts/add-cert.sh'
```

I think https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a is my problem, but I followed the most voted on answer with no success.

**Comment by alexfinnarn** [comment]
#497 is a duplicate of my problem, but this issue can be marked solely as a documentation update.

**Comment by pirog** [comment]
@alexfinnarn yeah good call on documenting the steps to COMPLETELY purify a system from lando things.
