### ISSUE TITLE
[UX] Bring lando db-import feedback inline with lando pull feedback.

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#509]
When using a pantheon recipe lando provides nice feedback when complete:

`lando pull`
<img width="632" alt="screen shot 2017-11-16 at 10 05 54 am" src="https://user-images.githubusercontent.com/6763671/32898697-d9af7910-cab6-11e7-8757-de896d7b7826.png">

das nice!

When using:

`lando db-import` you get "echo "Import completed with status code 0" or `1` for fail.

This PR gives feedback of success or fail:
<img width="984" alt="screen shot 2017-11-16 at 10 01 25 am" src="https://user-images.githubusercontent.com/6763671/32898780-1ec19e7a-cab7-11e7-9d26-f356e31c290e.png">

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/510

**Comment by pirog** [comment]
@serundeputy i like colors!
