### ISSUE TITLE
Documentation: Add Comparison To Similar Dev Tools

### ISSUE THREAD

**Issue by alexfinnarn** [lando/lando#512]
Someone recently was talking to me about Docksal for local development, and I mentioned Lando. On a quick inspection of both tools, they looked similar to me; however, I have no idea what the sticking points are in the comparison as I know little about both projects at this point. 

I really like the fact that the Vue.js team wrote https://vuejs.org/v2/guide/comparison.html. Not knowing a lot about reactive JS frameworks at the time I read it, it really helped me to examine Vue from a perspective of contrasts. 

That article can be used to see how they picked three JS frameworks that did similar things and made sure to be fair to the other dev communities. I'm pretty sure they had other framework devs read the section that involved their framework before publishing it. 

Similar tools:
- https://docksal.io/

**Comment by ccharlton** [comment]
Ditto. Docksal has been mentioned to me before as well.

**Comment by pirog** [comment]
@alexfinnarn @ccharlton im personally not going to do this but i would help contribute if someone else wanted to take the lead!
