### ISSUE TITLE
Add support for a Bitbucket init command

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#516]
Add support for a Bitbucket init command
  * Goal is to support `lando init bitbucket`
  * Example mimic UX of GitHub init command https://github.com/lando/lando/blob/30277e1188e9e6299567aa88e67d2758c22a812e/plugins/lando-core/lib/github.js

```bash
# Setup keys, clone a Bitbucket repo and interactively set up a recipe start state
# This requires a Bitbucket Personal Access Token
# See: https://docs.devwithlando.io/cli/init.html#bitbucket
lando init bitbucket
```

**Comment by ccharlton** [comment]
Yep.

**Comment by rjdjohnston** [comment]
+1 Surprised this hasn't moved forward
