### ISSUE TITLE
Add support for a GitLab init command

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#517]
Add support for a GitLab init command
  * Goal is to support `lando init gitlab`
  * Example mimic the GitHub init command https://github.com/lando/lando/blob/30277e1188e9e6299567aa88e67d2758c22a812e/plugins/lando-core/lib/github.js

```bash
# Setup keys, clone a GitLab repo and interactively set up a recipe start state
# This requires a GitLab Personal Access Token
# See: https://docs.devwithlando.io/cli/init.html#gitlab
lando init gitlab
```

**Comment by dschmidtadv** [comment]
That would be amazing, do you have any ideas on ETA?
