### ISSUE TITLE
Add intl and gettext extension for php

### ISSUE THREAD

**Issue by benjaminhirsch** [lando/lando#528]
Hey there,

first of all, great work! I really enjoy using lando, I absolutly love it! 

**Some suggestions regarding php:**
When you're working with translations, the php intl extension and gettext is often required. Currently it's really cumbersome to install this two extensions each time if I start a new project. The thing is, that the installation of intl takes it's time, because of it's dependeny to icu which needs to be compiled.

**Currently I'm doing this each time:**
services:
  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get install libicu-dev  -y"
      - "docker-php-ext-install intl gettext"
      - "docker-php-ext-enable intl gettext"`

It would be much better, when those two extesion would be already installed. :)

**Comment by pirog** [comment]
@benjaminhirsch this seems like a pretty reasonable request to me ;)

**Comment by benjaminhirsch** [comment]
Ah, now I found the docker files in the repository, becuase I already searched  those but wasn't able to find them. :blush:

I will add the missing lines in all neccessary files and send a pull request.
