### ISSUE TITLE
drush: stable doesn't default to latest PHAR

### ISSUE THREAD

**Issue by anavarre** [lando/lando#534]
**Tell us about your setup**

```
$ uname -ar && cat /etc/issue
Linux thinkpad 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 17.10 \n \l
```

**Tell us about your `.lando.yml`**

```yml
name: d8
recipe: drupal8
config:
  drush: stable
```

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

```bash
$ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "d8_default" with the default driver
Creating volume "d8_appserver" with default driver
Creating volume "d8_data" with default driver
Creating volume "d8_data_database" with default driver
Creating d8_appserver_1 ... 
Creating d8_database_1 ... 
Creating d8_database_1
Creating d8_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5988k  100 5988k    0     0  1409k      0  0:00:04  0:00:04 --:--:-- 1409k
 PHP configuration      :                  
 PHP OS                 :  Linux           
 Drush script           :  /tmp/drush.phar 
 Drush version          :  8.1.13          
 Drush temp directory   :  /tmp            
 Drush configuration    :                  
 Drush alias files      :                  


BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            d8                          
 LOCATION        /home/anavarre/Lando/drupal 
 SERVICES        appserver, database         
                                             
 APPSERVER URLS  https://localhost:33098     
                 http://localhost:33099      
                 http://d8.lndo.site         
                 https://d8.lndo.site
```

**Tell us generally about your bug**

I should be getting Drush 8.1.15, not 8.1.13. https://docs.devwithlando.io/recipes/drupal8.html clearly states `drush: stable` should work. I also tried omitting Drush completely in `.lando.yml` but it doesn't make any difference and still pulls 8.1.13.

**Tell us more**

I shouldn't have to add `drush: 8.1.15` in `.lando.yml` to get the latest stable Drush PHAR. Also, only Drush 8.1.15 is compatible with Drupal 8.4.0, so it makes the issue pretty important to fix.

**Comment by pirog** [comment]
@anavarre looks like the issue was relying on "http://files.drush.org/drush.phar" to grab the latest phar of drush 8. Seems like this method is no longer documented or updated in a timely fashion. 

We are going to set stable internally for now, which is annoying and will probably produce some lag on updates but at least its controllable on our end. Hopefully the drush people introduce some reliable "get me the latest phar" download method

**Comment by anavarre** [comment]
@pirog just in case you're not aware yet, Drush 9+ won't offer a PHAR anymore. It's Composer all the way going forward. It's also why I filed #536

**Comment by pirog** [comment]
@anavarre yup, im pretty aware. referring to drush 8 only.
