### ISSUE TITLE
Starting with 8.4.0, there should no longer be a global Drush  

### ISSUE THREAD

**Issue by anavarre** [lando/lando#536]
**Please explain your request and its importance in the form of a user story.**

As a Drupal 8.4.0+ user, I want to follow Drush maintainers' recommendation to NOT install a global Drush and require it in my `composer.json` instead.

Since there's no security support for versions of Drupal prior to 8.4.0 anyway, I think installing a global Drush should just go away.

**Please provide some detail on how lando can help solve this problem**

Stop installing a global Drush by default for the `drupal8` recipe.

**Comment by anavarre** [comment]
As an alternative, the Drush Launcher could perhaps do: https://github.com/drush-ops/drush-launcher

**Comment by pirog** [comment]
@anavarre exactly what i was thinking. See #542 for how we are currently planning on updating the drush handling.
