### ISSUE TITLE
install-wp-tests.sh doesn't work using Lando

### ISSUE THREAD

**Issue by bcbweb** [lando/lando#538]
I'm having trouble using the wp-cli for unit testing a plugin on my local WordPress site. I understand that I can use Lando with wp-cli by using `lando wp command`, however I'm running into issues when trying to use the bin/install-wp-tests.sh script that I get after using `lando wp scaffold plugin-tests my-plugin`. 

I'm trying to execute the command as follows:

`bin/install-wp-tests.sh wordpress_test pantheon 'pantheon' localhost:32769 latest`

Or:

`bin/install-wp-tests.sh wordpress_test pantheon 'pantheon' database latest`

These fail at the `mysqladmin create wordpress_test` command.

Output from `lando info` is as follows:

<pre>
"database": {
    "type": "mariadb",
    "version": "10.0",
    "creds": {
      "user": "pantheon",
      "password": "pantheon",
      "database": "pantheon"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": "32769"
    },
    "config": {
      "confd": "/Users/benjamincharlesbrown/.lando/services/config/pantheon/mysql"
    }
  }
</pre>

I can see Lando has been made compatible with wp-cli, but it appears that they will not consider [making install-wp-tests.sh a wp-cli command](https://github.com/wp-cli/wp-cli/issues/2119). Is there a way use this so that I can unit test my plugins on my local WordPress site using Lando?

**Comment by svict4** [comment]
Hey @bcbweb how did you go about fixing your issue? I'm running into the same sort of problem, more with the `mysqladmin` part of that shell script.
