### ISSUE TITLE
Update all base containers to Debian 9 'jessie'

### ISSUE THREAD

**Issue by anavarre** [lando/lando#539]
As a lando user, I'd like containers to be running off of Debian 9 'jessie' to benefit from newer packages.

Example below with PHP which defaults to PHP 5 for Debian 8 and PHP 7 for Debian 9.

Lando:

```
$ cat /etc/issue
Debian GNU/Linux 8 \n \l
$ apt-cache search ^php7.0$
$ apt-cache search ^php5$
php5 - server-side, HTML-embedded scripting language (metapackage)
```

Debian 9 container:

```
$ cat /etc/issue
Debian GNU/Linux 9 \n \l
$ sudo apt-cache search ^php7.0$
php7.0 - server-side, HTML-embedded scripting language (metapackage)
```

**Comment by pirog** [comment]
@anavarre it looks like a good deal of our base images (which are mostly official docker images) now have a `jessie` variant so while it does make me super nervous to update these images i think its probably worth doing. The only caveat here is we will only do this for services that have a `jessie` variant base image.
