### ISSUE TITLE
Stop supporting EOL'ed PHP versions

### ISSUE THREAD

**Issue by anavarre** [lando/lando#540]
Per http://php.net/supported-versions.php only PHP 5.6+ should be supported. Supporting EOL'ed PHP versions encourages bad habits.

**Comment by pirog** [comment]
@anavarre while lando does try to encourage good habits it is not its primary function. 

Our metrics indicate a substantial amount of lando users are still rolling with unsupported php versions so it's unlikely we will do this until those numbers come down significantly. That said, while we do offer unsupported versions we are likewise not supporting them, eg if someone has an issue with our php 5.3 container our response will be "use a supported php version".
