### ISSUE TITLE
No Sudo No Cry

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#545]
Make Lando un-sudo-able.

**Comment by jbertoen** [comment]
Why?

**Comment by dustinleblanc** [comment]
@jbertoen See @pirog's statements in the slack channel from last week. Lando should never be run as sudo. 

One reason I can think of is that running with sudo could alter the permissions of files written to the host system as well as mess up user mapping inside the container. Docker also typically uses your user directory as the root for its file sharing, and intends you to run docker as your user, not as root.

@pirog this does make me think about the use case of CI servers though, they may be running as root and therefore not able to run here.

**Comment by pirog** [comment]
yeah lando should absolutely not be run with sudo ever. 

i think the CI server case is interesting. i know on travis you can run as a normal user but there may be issues with appveyor/circle? regardless i think we should cross that bridge when we get to it and normal users using lando in the local context should just never do this

**Comment by jbertoen** [comment]
oh man, I thought it was about not using sudo in containers or something haha.
