### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running?

### ISSUE THREAD

**Issue by ccharlton** [lando/lando#550]
This ticket is just to call out the printed warnings when Docker isn't running (yet). Is there a cleaner way to detect if Docker is running? By providing nicer verbiage, and/or a little more context to the user we could reduce the anxiety of the warnings.

> **warn:** Attempting to start engine...
> **warn:** Trying to connect to daemon...
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> **warn:** Trying to connect to daemon...
> Error response from daemon: Bad response from Docker engine
> **warn:** Trying to connect to daemon...
> Error response from daemon: Bad response from Docker engine

**Comment by pirog** [comment]
@ccharlton for various reasons i dont think its trivial to suppress the warning coming directly from `docker` but we might be able to provide context like you say so the user doesn't FTFO.

**Comment by ccharlton** [comment]
Nice! Thank you very much.
