### ISSUE TITLE
Support Request: /bin/sh: 1: php: not found

### ISSUE THREAD

**Issue by startinggravity** [lando/lando#552]
My problem may be out of the scope of Lando support, but here goes. So far, I've been unable to figure out the cause of my problem on my own.

The problem happens while running specific Gulp processes. The Gulp script is part of the [Emulsify Drupal theme starter kit](https://github.com/fourkitchens/emulsify). Normally, I would seek support from the Emulsify team (Four Kitchens), but the error does not appear when I run Emulsify on another development platform. It only happens on a Lando installation.

Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta.29 on MacOS X El Capitan

```name: small-biz
recipe: drupal8
config:
  php: '7.1'
  via: nginx
  webroot: web
  drush: stable
  drupal: true
  xdebug: true
services:
  phpcli:
    type: php:7.1
    via: cli
  node:
    type: node:6.10
    build:
      - "cd $LANDO_MOUNT/web/themes/custom/small_biz && npm start"
    globals:
      gulp-cli: "latest"
tooling:
  composer:
    service: phpcli
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: phpcli
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node

```

**Tell us about the command you were running**

Any attempts to run a Gulp command that uses a command to recompile Pattern Lab fails. The message returned is:

```/bin/sh: 1: php: not found
Error with code 127 after running: php pattern-lab/core/console --generate
```

**Tell us about the error you got**

The error happens when Gulp is attempting to run either line 19 or line 35 of a file found in a custom theme created by using the Emulsify Drupal starter theme. [The file can be viewed here.](https://github.com/fourkitchens/emulsify-gulp/blob/develop/gulp-tasks/gulp-pattern-lab.js)

**Tell us generally about your bug**

The error message `/bin/sh: 1: php: not found` implies that the PHP command is not able to run because PHP-CLI does not exist. I have confirmed that it does.

```lando php -v
PHP 7.1.11 (cli) (built: Nov  4 2017 10:20:15) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

It is not a matter of being a problem with the path. If I edit the tasks at lines 19 and 35 to use `php -v` instead, for example, I still get the same "php: not found" error.

The PHP command in the Gulpfile is wrapped around [a function from here](https://github.com/fourkitchens/emulsify-gulp/blob/develop/gulp-tasks/notifier.js), but I don't see any reason for this causing the problem.

Again, the same Gulp functionality runs successfully when I'm not using a Lando platform.

**Tell us more**

I apologize if I am asking for support that is beyond what is normally or reasonably provided. Any help at all, however, would be appreciated if possible.

**Comment by startinggravity** [comment]
This problem was resolved by running Gulp from my host machine, not through Lando.

**Comment by thamas** [comment]
It still would be good to know what the source is of this problem because currently there is a good workaround but tere is not a solution.

**Comment by startinggravity** [comment]
A few people have asked me about this another issues they have run into using the Emulsify theme, so I wrote up [a page listing the things I have found](https://gist.github.com/startinggravity/5e0847510d292b26b9dcf7ffb660ed53) to help successfully use the theme.

**Comment by brooke-heaton** [comment]
@startinggravity I have an issue up related to lando and PatternLab https://github.com/lando/lando/issues/799 Would you be able to shed any light on why PatternLab may not be working within Lando? The issue may be specific to using the Components Library module.

**Comment by aposudevsky** [comment]
@p51i , @dustinleblanc it works indeed, but how do you access your patternlab served page? Internally in container for me it is http://localhost:8888. 
I've tried setting portforward : true in lando.yml file, but I still don't see it being exposed if I run lando info. 
Any idea how do I access it in the browser?

**Comment by dustinleblanc** [comment]
Either tell patternlab to pick a different port or map the port in proxy config:

```yml
proxy:
  servicerunningplab:
    - pl.appname.lndo.site:8888
```
