### ISSUE TITLE
Why bundle docker on your install?

### ISSUE THREAD

**Issue by hanoii** [lando/lando#558]
I am unsure of this. When I first got to lando and run the installer I found it very odd that you were bundling docker with it and installing it.

Me personally had docker installed so I unchecked it but being a major dependency I would rather point users to install it than doing this yourselves.

I assumes this was to help onboarding but installing docker is very easy nowadays.

This is really just a curious honest question but I think moving away from doing that could have benefits. Also docker might get updated on its own and your latest stable might come with an older binary.

**Comment by pirog** [comment]
We are aware of the potential downside in bundling Docker however this is not going to change. One of the design goals of lando "is one click installable" so this isn't going to change.
