### ISSUE TITLE
Understanding (slow) performance

### ISSUE THREAD

**Issue by jsheffers** [lando/lando#561]
This is really a placeholder issue and I don't think it's related to Lando unless Lando is doing something outside of the current docker defaults, which doesn't look like it.

Over the years, I tried a lot of self-contained development approaches, mostly VM-oriented like vagrant and I always fell back to native because of performance or needing to do some nasty tricks which were hard to keep up with.

Docker on the other hand, felt like it was the way to go and I also thought the same as https://github.com/lando/lando/issues/456#issuecomment-344918724:

> Googling the issue there are a ton of people that get disk performance to be equal of that of the native disk using default docker as long as the filesystems are mounted correctly.

But we are facing a huge difference just to *clear a D8 site cache*, both with drush and from the web. We are not yet sure whether this is coming from the db or the filesystem vs native/Mamp.

Lando/docker was taking around 36s at first. After stopping the containers, restarting docker and starting lando again went down to 18-20s. Native/Mamp takes 6s or less. This is a huge difference for a simple D8 site and I assume the time will start going up again after some usage.  For all drush commands using Lando it's taking 4x what it takes with a Mamp/native setup.  Is this just to be expected because of the nature of Docker/Lando?

**Comment by jbertoen** [comment]
Wow, that is a huge gap in performance. How is your .lando.yml config file looking right now?

I have done some performance testing in lando and docker:
https://github.com/lando/lando/issues/518
Maybe it can help you improve your setup

I also remember that a colleague of mine has seen enormous performance improvements in docker when using docker for mac (edge) on high sierra on OSX.

**Comment by shanejeffers** [comment]
It's a very basic implementation:

`name: drupal-project
recipe: drupal8
config:
  webroot: .
  drush: global:~8
services:
  node-cli:
    type: node:6.10
    globals:
      gulp-cli: "latest"
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli
`
I installed Docker (Edge) with no luck.  Still seems to be just as slow.

**Comment by jsheffers** [comment]
It's a very basic implementation:

```name: drupal-project
recipe: drupal8
config:
  webroot: .
  drush: global:~8
services:
  node-cli:
    type: node:6.10
    globals:
      gulp-cli: "latest"
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli
```
I installed Docker (Edge) with no luck.  Still seems to be just as slow.

**Comment by jbertoen** [comment]
Maybe we should look at this some more
https://github.com/amazeeio/docker-performance-testbench

**Comment by jbertoen** [comment]
It has probably to do something with the current known issues about files in containers. Just so you know, it is an ongoing improvement. Before the native situation would in some cases even give read timeouts.
So my advice is to accept it and deal with it or switch to a linux setup. But it is getting better.

**Comment by jbertoen** [comment]
I experience the same performance on drush cr as you. I think this is something we have to live with for now.

**Comment by jbertoen** [comment]
@jsheffers , have you checked this out?
https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-17110-ce-mac40-2017-11-22-edge
It says something about changing the settings.json to make the APFS integration work on edge.

**Comment by pirog** [comment]
This is (and has been for many years) one of the more difficult parts of a local Docker based container architecture. We've tried multiple workaround solutions on our end to mitigate but each "workaround" presents its own set of problems. 

At this time we think the performance docker delivers is good enough. If you don't agree we totally understand and recommend you use something else that fits your needs. We are going to continue to build out Lando and hope that docker can continue to make improvements in this space.

**Comment by parijke** [comment]
I do not know if this is related but......

The solution mentions in this comment gave me a warpspeed lando setup. Very happy!
https://forums.docker.com/t/mysql-slow-performance-in-docker/37179/10

**Comment by parijke** [comment]
This one did it for me
http://phpforus.com/how-to-make-mysql-run-fast-with-ext4-on-ubuntu/

Worked on two seperate systems

**Comment by MattSchaffO3** [comment]
Thanks @parijke ! However, when I try to edit /etc/fstab, I get "# UNCONFIGURED FSTAB FOR BASE SYSTEM" ... how do I find the UUID of the container to put in fstab?
