### ISSUE TITLE
Make use of smaller Alpine images instead of debian

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#562]
Alpine images are a lot smaller: https://blog.codeship.com/alpine-based-docker-images-make-difference-real-world-apps/

This might seriously decrease the diskspace on development environments.

**Comment by pirog** [comment]
@jbertoen i def get why smaller containers are preferably in some ways. However, we want to provide containers that you can "SSH" into and get a more full featured experience. 

That said, some of our services are alpine services already. It's a blurry line.
