### ISSUE TITLE
Lando within WSL (Windows Linux)

### ISSUE THREAD

**Issue by chris-sparks** [lando/lando#564]
Has anyone managed to get Lando functioning/executing within Windows WSL ?

I've added the install directory to the PATH variable in the same way I handled it for Docker:

```
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
PATH="$PATH:/mnt/c/Program\ Files/Docker/Docker/resources/bin"
PATH="$PATH:/mnt/c/Program\ Files/Lando/bin"

alias lando='lando.exe'
alias docker='docker.exe'
```

and receive the following error when executing 'lando':

```
:~$ lando
net.js:204
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:204:18)
    at createWritableStdioStream (internal/process/stdio.js:173:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:20:14)
    at console.js:170:37
    at NativeModule.compile (bootstrap_node.js:605:7)
    at Function.NativeModule.require (bootstrap_node.js:548:18)
    at installInspectorConsole (bootstrap_node.js:330:41)
    at get (bootstrap_node.js:322:15)
    at readPrelude (bootstrap_node.js:113:11)
    at bootstrap_node.js:117:22
```

Just curious/probing if anyone has encountered the same or otherwise had any success ?

**Comment by pirog** [comment]
@chris-sparks Lando is not supported in WSL so your mileage may vary

**Comment by chris-sparks** [comment]
Thanks for the super speedy reply Mike. Saddened to hear it's not supported in WSL, but in case there's anyone out there having any successes with this, would love to have some feedback/input!

**Comment by aleksijohansson** [comment]
With the Fall Creators update I can run lando.exe in WSL without any additions to PATH, but I do get the same error. I’m very interested to get this working. It’s the last piece of the puzzle.

**Comment by uberhacker** [comment]
@aleksijohansson: Where did you get this Fall Creators update and are you using Windows Home or Pro?  Last time I tried WSL, the kernel was not virtualized and could not be upgraded so it was impossible to install Docker.

**Comment by uberhacker** [comment]
FWIW, [this site](https://github.com/ethanhs/WSL-Programs) gives Docker a big fat zero.  The reason it cannot run is because the kernel is not capable and you cannot upgrade in WSL.

**Comment by aleksijohansson** [comment]
@uberhacker Fall Creators update is just like any update for Windows in terms of where you get it. I have Windows 10 Pro. I'm not saying I run or even installed Docker in WSL. I'm saying I can run the Lando installed to Windows (with Docker installed to Windows too) in WSL by running lando.exe. It should be very similar to running lando.exe in a Windows command prompt, but for some reason it fails with the error described in this issue.

**Comment by uberhacker** [comment]
@aleksijohansson: Maybe I'm way off base but would you ever expect an `.exe` executable to work in a bash shell environment?

**Comment by aleksijohansson** [comment]
@uberhacker Yes, see https://docs.microsoft.com/en-us/windows/wsl/interop#run-windows-tools-from-wsl.

**Comment by aleksijohansson** [comment]
There seems to be a related issue open in WSL where node.exe (Node.js) fails with the same error https://github.com/Microsoft/WSL/issues/2370. It might be even the exact same issue.

**Comment by mrconnerton** [comment]
Can this issue be reopened? I can successfully start/stop lando from powershell, and I can even run lando commands like lando db-import from WSL bash but I can't start/stop from WSL bash. The error I get is

```
Recreating 2221da82fe15_landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for 2221da82fe15_landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
Removing landoproxyhyperion5000gandalfedition_proxy_1
Recreating 2221da82fe15_landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for 2221da82fe15_landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
^C
```

If I bounce around my tooling I can get things working but would love to get this all going from just bash so I can use my Makefiles.

I am running Windows 10 Pro 1803 17134.137, Docker for Windows edge, and ENV variables in bash that use the remote docker. I have ubuntu 18 installed on WSL

**Comment by pirog** [comment]
Lando is not officially supported in WSL so I don’t think reopening this
issue makes sense

**Comment by infernobass7** [comment]
I am currently running Windows 10 Pro version 1809 (not WSL) and I am getting similar issues to @mrconnerton  when running `lando start`. Other `lando {command}` work except when trying to boot the application.

**Comment by mstrelan** [comment]
Can this be revisited for WSL 2? See also what Docker thinks about it: https://engineering.docker.com/2019/06/docker-hearts-wsl-2/

**Comment by aleksijohansson** [comment]
For me everything works now with the latest version of Windows (official, not insider build) and Lando 🙌
