### ISSUE TITLE
feature request: Tomcat/Java recipe

### ISSUE THREAD

**Issue by hardyoyo** [lando/lando#568]
As a Lando user who works with Tomcat (Java)-based sites, I want to be able to use the full Lando toolset, too. There is an official [Tomcat repository on Docker Hub](https://hub.docker.com/_/tomcat/), with 10M+ pulls. If I can figure out how to write a recipe, I'll contribute one myself.

**Comment by hardyoyo** [comment]
https://github.com/lando/lando/pull/595 adds a new Tomcat service, which is a prerequisite for this recipe

**Comment by pirog** [comment]
@hardyoyo i merged in the tomcat service but i was wondering how you see this connecting to a java service and or recipe. I'm going to close this issue out but could you write up a separate one for your vision re: java?

**Comment by hardyoyo** [comment]
Well.. _this_ service basically stands up the appserver, we'll need another container for the command line build tools (the official maven container is fine for that). I'm unfamiliar with the design of how a recipe *should* work, so, I don't know *how* I'll build the recipe exactly. But, the gist of it is, we will have two containers, one for the appserver/Tomcat, and one for the app build, based on the official Maven container, with Ant and Gradle added in. The app build container and the appserver container will share the app src mount.  From that point, it's up to config files. Oh, and we'll need a DB, PostgreSQL works fine.
