### ISSUE TITLE
Mail server

### ISSUE THREAD

**Issue by mmenavas** [lando/lando#569]
As a lando user who works with Drupal site that send out email notifications powered by Rules and Tokens, I want the option to start a mail server (e.g. sendmail) to check what the emails  look like.

**Comment by serundeputy** [comment]
@mmenavas maybe turning on the `mailhog` service in your `.lando.yml` file will meet your needs? https://docs.devwithlando.io/services/mailhog.html

**Comment by mmenavas** [comment]
@serundeputy Thanks for the quick response. I will give that a shot.

**Comment by pirog** [comment]
@mmenavas def try mailhog. I doubt we will offer a straight up mail server service for lando because its better to catch mail than potentially send mail out. That said mialhog is very bound to php right now so we might want to explore a more cross tech way to do this in the future.

**Comment by mmenavas** [comment]
Thank you @pirog! I did try Mailhog, and I was happy with it.

When I created this ticket I was hoping lando had a switch I could flip to enable a mail server, but the truth is I didn't really need one. With Mailhog I was able to preview HTML emails, and that was good enough for me.
