### ISSUE TITLE
ERROR 1050 (42S01) at line 355: Table 'cache_data' already exists

### ISSUE THREAD

**Issue by persianturtle** [lando/lando#571]
Bug Report
==========

**Tell us about your setup**
Default Pantheon / Drupal 8 setup with custom composer packages.

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Running v3.0.0-beta.29 on macOS 10.12.6.

**Tell us about your `.lando.yml`**

```yml
name: ...
recipe: pantheon
config:
  framework: drupal8
  site: ...
  id: ...
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

All config files are default from Pantheon, except I have installed the following composer packages:

```
"mailgun/mailgun-php": "^2.3",
"php-http/curl-client": "^1.7",
"guzzlehttp/psr7": "^1.4"
```

**Tell us about the command you were running**

`lando push`

Paste in a series of commands that caused the bug.

```bash
lando push
```

**Tell us about the error you got**

There was an error writing to the database.  I had failed to clear cache in Drupal 8 on both my local instance as well as Pantheon's.  This was for the **dev** Pantheon site.

```
Making sure your database is awake!
 [notice] OK >> dev-orfadin.pantheonsite.io responded
Pushing DB...
ERROR 1050 (42S01) at line 355: Table 'cache_data' already exists
mysqldump: Got errno 32 on write
Pushing files...
sending incremental file list

sent 165 bytes  received 15 bytes  32.73 bytes/sec
total size is 1,172  speedup is 6.51

Push complete!
```

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

--verbose is not supported for `lando push --verbose`

**Tell us generally about your bug**

I made changes to the database in my locally running Drupal 8 site.  I then ran `lando push` without clearing any caches, and I received the mysql error.  After clearing both caches, the error persists.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. install composer packages

```
"mailgun/mailgun-php": "^2.3",
"php-http/curl-client": "^1.7",
"guzzlehttp/psr7": "^1.4"
```

2. Made changes to files & database

3. Do not clear cache of either locally running instance, or `dev-site.pantheonsite.io`

4. Notice error in `lando push` stdout

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

First of all, kudos on your docs. I was able to get running quickly and was even able to work around this issue by manually dropping the `cache_config` database table via `lando ssh database` (after looking up credentials via `lando info`).

If it's a reasonable solution for this error, please add this workaround somewhere in the docs.

Does this bug prevent you from using lando?

No.  Again, great job.

**Comment by serundeputy** [comment]
@persianturtle to get the `verbose` output use:

```bash
lando push -- -vvv
```

please.

**Comment by persianturtle** [comment]
@serundeputy Thanks, I'll use `verbose` each time and if the error comes back, I'll post the output here. It has happened three times so far with various cache related database tables.

**Comment by persianturtle** [comment]
So far with `v3.0.0-beta.30` I haven't had this issue.  I'll close for now, and if it occurs again, I'll open another issue.
