### ISSUE TITLE
Is a custom NGINX required when not passing through index.php?

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#574]
I've got Symfony up and running using a custom NGINX config. However, is that required? 

All that I *really* need for development is passing through `app_dev.php` instead of `index.php`. I have tried `index: app_dev.php` and `pasthru: app_dev.php`.

If this is not supported, consider this a feature request. It would be nice to set the index file and if I could take this request a step further, it would be nice for that index parameter to allow for regex input such as `^/(app|app_dev|config|install)\.php(/|$)`

**Comment by jbertoen** [comment]
I am not really that familiar. But maybe we could use your setup as a recipe for running symfony then? If what you do is something that is normal in the symfony development.
Or some other setup that would allow more passthroughs of *.php files then what is currently supported.

**Comment by dustinleblanc** [comment]
@tylerssn  I think this kind of setup is atypical and definitely warrants passing in your own nginx.conf file. Is it actually a typical symfony thing? I only dabble in symfony on occasion. We have an open PR/Issue on a Symfony recipe and if this is a thing for Symfony, I think that'd be the best place to implement. The other 99% of PHP apps are going to use index.php afaik if they serve a web front end.

**Comment by peteward** [comment]
`app.php` was the common entry point for Symfony applications up until the latest version 4 where it appears to have reverted back to the standard `index.php`.

Not all applications based on the framework have updated to version 4 though so there will be many cases of `app.php` out there.

**Comment by dustinleblanc** [comment]
Thanks for the additional info @peteward. I think given what we're seeing here, I am going to say this is a Symfony recipe specific thing and we can override the config in that recipe when we wrap up #699 / #307

**Comment by pirog** [comment]
@dustinleblanc this makes sense to me. To play devil's advocate, having some internal mechanism (that we could also expose on our web server services) to set the entrypoint could be advantageous in creating the symfony recipes and any other recipes which use similar non-standard entrypoints

**Comment by dustinleblanc** [comment]
Is the abstraction worth it though? I'd say maybe if we have to reuse it a lot, could it be shared with other services like node? Folks be `node app.js`ing all the time

**Comment by pirog** [comment]
Normally i'd say no but given that we already have good variable and env injection for these things it might be worth it
