### ISSUE TITLE
Add settings.lando.php example to connect a Database in Drupal 8.

### ISSUE THREAD

**Issue by benedikt-buchert** [lando/lando#585]
Feature Request
===============

As a Lando user who works with Drupal 8 sites, I want an example settings.lando.php calling the environment variables to connect to the database. Also It could include the correct host patterns. This file can either be included in the settings.php or called from there. This would make it even more easy to get started with Lando and D8.

It could work similarly to the settings.platfrom.php for platform.sh https://github.com/platformsh/platformsh-example-drupal8/blob/master/web/sites/default/settings.platformsh.php

This is how it could be included in settings.php:
```
if (file_exists($app_root . '/' . $site_path . '/settings.lando.php')) {
  include $app_root . '/' . $site_path . '/settings.lando.php';
}
```

**Comment by benedikt-d** [comment]
Maybe a Drush alias example file calling the local environment variables would also be helpful.

**Comment by pirog** [comment]
@benedikt-d i definitely understand why something like this would be super useful but i think it's highly unlikely that we will add support for something like this. I'll try to summarize the rationale in the below bullet points

1. One of our main design principles is to not ever muck with someone's codebase (with the exception of the `.lando.yml` file) and while we don't adhere to our design principles 100% of the time, there needs to be a super clear benefit gained by betraying them.
2. Once we get into this sort of game it's expected we provide similar config files for other frameworks and since lando is a tool for an ever expanding base of frameworks the maintenance around this is not tenable for the current resource base we have to bring to bear
3. Generally the expectation for something like platform.sh is you need to make your app conform to its standards. We've found that for local dev the expectation is often the opposite. This means that we can't assume to a sufficient level of confidence that the user actually wants whatever config file we might provide. 

All that said, i am totally down to provide some as-barebones-as-possible *examples* that user's can adapt to their needs.

**Comment by pirog** [comment]
@serundeputy this might be a good task to tackle if you are looking for something to do. Let's talk about it a bit beforehand but i see the outline being something like

1. Provide **EXTREMELY BAREBONES** relevant settings/config example files/snippets in the relevant recipe examples eg https://github.com/lando/lando/tree/master/examples/drupal8. They don't have to necessarily work within the context of the example, just seems like the best place to put them.
2. Update our recipe tutorials with a new standard section to talk about the files/snippets from 1. Probably something under the Configuration section (possibly "Application" or the name of the file to be configured). This section should import the files and snippets from the examples directory just like we do for the recipe config 
3. Provide some brief language around what the files do 
4. Note that some recipes (like backdrop, pantheon) are "lando ready" and do not require this sort of thing

So for D8 we'd probably want an `example.settings.php` and `settings.lando.php` in the D8 example directory and import them into a Configuration -> settings.php section in the D8 tutorial. I'm guessing we want `example.settings.php` to conditionally load `settings.lando.php` if we are on `lando` (eg look for the `LANDO` envvar) and for `settings.lando.php` to use the `DB_*` envvars that `lando` sets up for each app.

**Comment by mrconnerton** [comment]
I'm using the file load in settings.php and this in my settings.lando.php

```php
if ($_SERVER['LANDO'] === 'ON') {
  $databases['default']['default'] = [
    'driver' => 'mysql',
    'database' => getenv('DB_NAME'),
    'username' => getenv('DB_USER'),
    'password' => getenv('DB_PASSWORD'),
    'host' => getenv('DB_HOST'),
    'port' => getenv('DB_PORT'),
  ];

  $settings['hash_salt'] = md5(getenv('LANDO_HOST_IP'));
}
```

**Comment by benedikt-d** [comment]
I'm including the file like this: 
```
if ($_SERVER['LANDO'] === 'ON' && file_exists($app_root . '/' . $site_path . '/settings.lando.php')) {
  include $app_root . '/' . $site_path . '/settings.lando.php';
}
```

**Comment by jonathanjfshaw** [comment]
+1 I can understand you don't want to add complex code, but documentation is like gold for the uninitiated.

**Comment by pirog** [comment]
agreed @jonathanjfshaw, this is why we have a SHIT TON of documentation.

**Comment by dustinleblanc** [comment]
@pirog @serundeputy do we still have work to do on this?

**Comment by mikl** [comment]
In my opinion, the docs really could do with a snippet like the one @mrconnerton posted above, or at least some clearer guidance on how to configure Drupal. I’ve wasted a couple of hours looking for this before happening on this thread…

**Comment by quietone1** [comment]
@miki, I agree.

**Comment by tormi** [comment]
You don't need to create yet another settings file for lando, `settings.local.php` will do just as well for https://github.com/lando/lando/issues/585#issuecomment-357836018.

**Comment by pirog** [comment]
@benedikt-d totally agree it would be great to add docs based on the suggestions over here https://github.com/lando/lando/issues/585#issuecomment-355798278

however, doesn't look like anyone is going to jump on this immediately so i am going to icebox this for now.

**Comment by hussainweb** [comment]
Since `DB_NAME` and related variables are deprecated, here is the updated snippet.

```php
if ($_SERVER['LANDO'] === 'ON') {
  $lando_info = json_decode(getenv('LANDO_INFO'), TRUE);
  $databases['default']['default'] = [
    'driver' => 'mysql',
    'database' => $lando_info['database']['creds']['database'],
    'username' => $lando_info['database']['creds']['user'],
    'password' => $lando_info['database']['creds']['password'],
    'host' => $lando_info['database']['internal_connection']['host'],
    'port' => $lando_info['database']['internal_connection']['port'],
  ];
}
```

**Comment by mperetz** [comment]
I tried to add the code above, but I get this exception

Notice: Undefined index: LANDO in /app/sites/default/settings.local.php on line 2 Call Stack: 0.0000 358920 1. {main}() /app/core/install.php:0 0.0022 367360 2. install_drupal() /app/core/install.php:44 0.0022 368720 3. install_begin_request() /app/core/includes/install.core.inc:114 0.0029 471960 4. Drupal\Core\Site\Settings::initialize() /app/core/includes/install.core.inc:323 0.0029 472240 5. require('/app/sites/default/settings.php') /app/core/lib/Drupal/Core/Site/Settings.php:122 0.0029 474728 6. include('/app/sites/default/settings.local.php') /app/sites/default/settings.php:24 Notice: Undefined index: LANDO in include() (line 2 of /app/sites/default/settings.local.php).
include('/app/sites/default/settings.local.php') (Line: 24)
require('/app/sites/default/settings.php') (Line: 122)
Drupal\Core\Site\Settings::initialize('/app', 'sites/default', Object) (Line: 1037)
Drupal\Core\DrupalKernel->initializeSettings(Object) (Line: 269)
Drupal\Core\DrupalKernel::createFromRequest(Object, Object, 'install', ) (Line: 412)
install_begin_request(Object, Array) (Line: 114)
install_drupal(Object) (Line: 44)

**Comment by tormi** [comment]
@mperetz, try without `if` statement:
```
$lando_info = json_decode(getenv('LANDO_INFO'), TRUE);
$databases['default']['default'] = [
  'driver' => 'mysql',
  'database' => $lando_info['database']['creds']['database'],
  'username' => $lando_info['database']['creds']['user'],
  'password' => $lando_info['database']['creds']['password'],
  'host' => $lando_info['database']['internal_connection']['host'],
  'port' => $lando_info['database']['internal_connection']['port'],
];
```

**Comment by mperetz** [comment]
Thank you. 

However, now I get this:
The website encountered an unexpected error. Please try again later.

I will try to debug and see what's going on...

**Comment by mperetz** [comment]
I got the issue resolved, I just did a lando pull command and it worked.

**Comment by willieseabrook** [comment]
I found this ticket whilst looking to get lando to work with platform.sh drupal 8.

The solution by @tormi in https://github.com/lando/lando/issues/585#issuecomment-401641484 inserted into .platform/local/shared/settings.local.php worked.

In addition I needed to also insert $settings['hash_salt'] = 'A VALUE'; as platform sh sets hash_salt using $PLATFORM_PROJECT_ENTROPY which is not available on local or inside lando.

**Comment by tormi** [comment]
New version with some additional settings for `local.settings.php`:

```
if (getenv('LANDO') === 'ON') {
  $lando_info = json_decode(getenv('LANDO_INFO'), TRUE);
  $settings['skip_permissions_hardening'] = TRUE;
  $settings['trusted_host_patterns'] = ['.*'];
  $settings['hash_salt'] = md5(getenv('LANDO_HOST_IP'));
  $databases['default']['default'] = [
    'driver' => 'mysql',
    'database' => $lando_info['database']['creds']['database'],
    'username' => $lando_info['database']['creds']['user'],
    'password' => $lando_info['database']['creds']['password'],
    'host' => $lando_info['database']['internal_connection']['host'],
    'port' => $lando_info['database']['internal_connection']['port'],
  ];
```

**Comment by ChandeepKhosa** [comment]
Just so you know, this also worked for me on a Drupal 7 site. Thanks!
