### ISSUE TITLE
update terminus

### ISSUE THREAD

**Issue by hades200082** [lando/lando#592]
[notice] A new Terminus version v1.6.1 is available.
You are currently using version v1.5.0.
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update

I get the above message every time I pull from Pantheon.  Running the suggested command errors.

**Comment by pirog** [comment]
@hades200082 we ship with the newest terminus 
https://github.com/lando/lando/blob/master/plugins/lando-recipes/pantheon/7.0-fpm/Dockerfile#L11

you probably just need to rebuild your app to get the latest version of the appserver

**Comment by jserrao** [comment]
This popped up again on v3.0.0-beta.35. Terminus v1.6.1 vs v1.7. Not a huge deal but threw a bunch of warnings. Rebuilding the app didn't help, I'm guessing a future beta will catch the versions up.

Thanks for Lando, big improvement over Kalabox. Loving it on this end.
