### ISSUE TITLE
Adding Lando Recipe via Plugin

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#597]
Following the lead of the [lando-recipes](https://github.com/lando/lando/tree/master/plugins/lando-recipes), I have been adding two recipes to the `lando init` command via the `post-bootstrap` event.

The init command is working. However, the generated `.lando.yml` contains `recipe: magento2-lamp` which appears to be parsed *before* the `post-bootstrap` event is fired causing this error to be thrown:

`warn: magento2-lamp is not a supported recipe.`

I would try hooking into an earlier event but (1) `lando-recipes` uses the `post-bootstrap` event and (2) my recipe depends on `lando.recipes.get('lamp')` which would not be registered if I hooked into an earlier event, right?

**Comment by pirog** [comment]
@tylerssn i think i'm going to need to look at whatever code you are using to help out here. Difficult to provide substantive help otherwise!

**Comment by tylerssn** [comment]
It's a fairly strict copy of your Lando recipes set of code. This does not yet have a repo for a home, so here we go...

# index.js

    'use strict';
    
    module.exports = function(lando) {
        // Add recipe config to the global config
        require('./lib/bootstrap')(lando);
    };

# lib/bootstrap.js


    'use strict';
    
    module.exports = function(lando) {
    
        // Modules
        var _ = lando.node._;
        // Recipes
        var recipes = [
            // 'magento2-lamp',
            'magento2-lemp'
        ];
    
        // Add particular recipes to lando
        lando.events.on('post-bootstrap', 5, function(lando) {
            // Load the recipes
            _.forEach(recipes, function(recipe) {
                var recipeModule = './../' + [recipe, recipe].join('/');
                lando.recipes.add(recipe, require(recipeModule)(lando));
            });
    
        });
    
        // Go through our recipes and log them
        lando.events.on('post-bootstrap', 6, function(lando) {
            _.forEach(lando.recipes.get(), function(recipe) {
                if(recipes.indexOf(recipe))
                lando.log.verbose('Recipe %s loaded', recipe);
            });
        });
    
    };

# magento2-lemp/magento2-lemp.js


    'use strict';
    
    module.exports = function(lando) {
    
        // Modules
        // var lamp = lando.recipes.get('lamp');
        var lamp = require('../magento2-lamp/magento2-lamp')(lando);
    
        /*
         * Helper to return proxy config
         */
        var proxy = function(name) {
            return {
                nginx: [
                    [name, lando.config.proxyDomain].join('.')
                ]
            };
        };
    
        /**
         * Build out LEMP
         */
        var build = function(name, config) {
    
            // Start by cheating
            var build = lando.recipes.build(name, 'magento2-lamp', config);
    
            // Replace the proxy
            build.proxy = proxy(name);
    
            // Set via to nginx
            build.services.appserver.via = config.via || 'nginx';
    
            // Return the things
            return build;
    
        };
    
        // Return things
        return {
            build: build,
            resetConfig: lamp.resetConfig,
            getCgr: lamp.getCgr,
            getPhar: lamp.getPhar
        };
    
    };

# magento2-lemp/magento2-lemp.conf

    
    server {
    
        listen 80 default_server;
        listen 443 ssl;
    
        server_name appserver;
    
        set $MAGE_ROOT ${LANDO_WEBROOT}
    
        ssl_certificate           /certs/cert.crt;
        ssl_certificate_key       /certs/cert.key;
        ssl_verify_client         off;
    
        port_in_redirect off;
        client_max_body_size 100M;
    
        root ${LANDO_WEBROOT};
        index index.php index.html index.htm;
    
        location / {
             try_files $uri $uri/ /index.php$is_args$args;
        }
    
        location ~ \.php$ {
            try_files $uri /index.php =404;
            fastcgi_pass fpm:9000;
            fastcgi_index index.php;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    
        location ~ /\.ht {
            deny all;
        }
    
        location /.well-known/acme-challenge/ {
            root /var/www/letsencrypt/;
            log_not_found off;
        }
    }

**Comment by pirog** [comment]
@tylerssn yeah this all looks like it would work to me. Although `var build = lando.recipes.build(name, 'magento2-lamp', config);` looks problematic for other reasons. 

Where are you putting the plugin and are you telling lando to load it in the `config.yml`?

**Comment by tylerssn** [comment]
@pirog - if everything looks good to you, then the issue could reside in [Lando Plugin Anywhere](https://www.npmjs.com/package/lando-plugin-anywhere), a plugin I built to allow plugins to be automatically detected within projects so that the `config.yml` does not have to be managed manually.

I will try to circle back around with more details as soon as I have a free second to commit to this.

**Comment by pirog** [comment]
@tylerssn yeah that sounds really good to me!

i'm going to close this out but feel free to open a new issue when you have that dialed so we can add in some docs for it!
