### ISSUE TITLE
Heavy/automated use causing github API rate limit error on lando update check

### ISSUE THREAD

**Issue by leevh** [lando/lando#598]
I've been using Lando in a CI pipeline for a few months now and just recently I've been getting errors after large parallel runs of CI on several sites that the new update check https://github.com/lando/lando/commit/2bdcdaba83fbc7e360a34a377ac53ef1b6502de4#diff-1af4749a9cdb4c3869ddabe803c584ff is causing an API rate limit exceeded error from Github.  The full error is below.  I realize this isn't a bug and is completely isolated to my unusual use case.  Although I could imagine it happening to a large dev team all behind single IP.  Perhaps a flag to skip update check or a way to use the github-auth token option for this check as well?   Great job on Lando, it's been stellar!

> warn:  {"message":"API rate limit exceeded for 52.123.123.123. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
    (No stack trace)
From previous event:
    at Object.__dirname.setupRoutes.Object.keys.forEach.self.(anonymous function).(anonymous function) [as getReleases] (/snapshot/cli/node_modules/github/lib/index.js:275:40)
    at /snapshot/cli/lib/update.js:0:0
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/lib/update.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3

**Comment by davisshaver** [comment]
I recommend using a custom build step, such as:

```
services:
  appserver:
    build:
      - |
        if [ -n "$GITHUB_TOKEN" ] ; then
          cd $LANDO_MOUNT && composer config --global --auth --unset github-oauth.github.com && composer config --global github-oauth.github.com $GITHUB_TOKEN
        fi
```

This will grab the Github token from `.env` and then you can proceed with composer install.

**Comment by pirog** [comment]
@leevh agree with @davisshaver, i dont think this is a problem rooted in lando. at this level of things its up to the user to handle things like this.

**Comment by carstenwindler** [comment]
@davisshaver @pirog I just encountered this issue, since more and more projects in my company are using lando (great tool by the way, we totally love it!). 

We're all using the same IP, so we hit the limit of 60 requests to github API more regularly sooner or later since it seems lando is doing the update checks upon every run, or am I wrong? The fix from @leevh would be a solution then.

**Comment by grshane** [comment]
I am running into the same issue while running lando.

**Comment by pirog** [comment]
This has been changed in master to only run once a day

**Comment by pirog** [comment]
@geerlingguy i would definitely try out the latest release we have on github. We don't actually manage the updates to the homebrew package.

**Comment by pirog** [comment]
Yeah i was not able to replicate this on the latest version/master on the DrupalCon wifis :(

**Comment by geerlingguy** [comment]
@pirog - Okay, thanks! The official docs mention the homebrew option (admittedly, second to the dmg method): https://docs.devwithlando.io/installation/installing.html, so I hoped it would be maintained as current as possible. I'll switch to the DMG instead. Thanks!

**Comment by pirog** [comment]
@geerlingguy USUALLY they are PRETTY GOOD about updating when we cut a new version but doesn't always work out that way. If you still have a problem you can cheat the update check by dumping a json file into `~/.lando/cache/updates`

```json
{
  "version": "3.0.0-beta.39",
  "url": "https://github.com/lando/lando/releases/tag/v3.0.0-beta.39",
  "expires": 1523470197624
}
```

**Comment by pirog** [comment]
Also ping @dustinleblanc re https://github.com/lando/lando/issues/674
