### ISSUE TITLE
v3.0.0-beta.31 .dmg won't open

### ISSUE THREAD

**Issue by sagannotcarl** [lando/lando#605]
Bug Report
==========

- OSX 10.11.6
- MacBook Pro (Retina, 15-inch, Late 2013)
- v3.0.0-beta.31

I downloaded the dmg and double-clicked it. The dmg would not open and I received the following error: `no mountable filesystems`. See attached screenshot.

<img width="376" alt="screen shot 2018-01-02 at 5 19 10 pm" src="https://user-images.githubusercontent.com/79287/34498276-13c5cb8a-efe8-11e7-8d96-14d632e015b8.png">

**Comment by sagannotcarl** [comment]
v3.0.0-beta.29 successfully opens for me though.

**Comment by anthropos9** [comment]
Same here. Tried everything I could find.

**Comment by pirog** [comment]
we had a bit of wonkiness with our 31 build which should be back to usual on 32 so im going to close this. please reopen if you get the same thing for 32

**Comment by anthropos9** [comment]
32 worked fine. Thanks.
