### ISSUE TITLE
Add presentation materials to the documentation

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#609]
To let the word out that Lando is awesome, but make it easy for people to do this. A kind of "marketing kit" in the documentation section would be nice.
The kit could contain
- logo's and images
- list of companies using lando
- quotes of people who use lando
- good reasons to use lando, or why it should exist
- references to video's and/or slides of other presentations that people created for inspiration

**Comment by pirog** [comment]
I think we are going to expand this to include other marketing materials but here is access to some public slidedeck stuff for now
https://drive.google.com/drive/folders/1ooK_NTMBuwOV0uix8O54umJGwAODL9dC
