### ISSUE TITLE
Drupal 7 apps fail to start after updating to beta 34

### ISSUE THREAD

**Issue by AaronFeledy** [lando/lando#625]
Bug Report
==========

**Tell us about your setup**

lando-v3.0.0-beta.34 on Windows 10 Professional

**Tell us about your `.lando.yml`**

```name: test
recipe: drupal7
config:
  webroot: .
```

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

```
ERROR: for appserver  Cannot create container for service appserver: invalid volume spec "\\usr\\local\\etc\\php\\conf.d\\zzz-lando-my-custom-ini-file-called-php.ini": invalid volume specification: '\usr\local\etc\php\conf.d\zzz-lando-my-custom-ini-file-called-php.ini': invalid mount config for type "volume": invalid mount path: '\usr\local\etc\php\conf.d\zzz-lando-my-custom-ini-file-called-php.ini' mount path must be absolute
```

**Tell us generally about your bug**

Both new and existing drupal7 apps fail to start and display the above error after updating to beta 34. Downgrading to beta 33 allows the apps to start normally.

**Does this bug prevent you from using lando?**

Yes.

**Comment by pirog** [comment]
Can't replicate this on macOS. Will try on Win 10 Pro a little later.

**Comment by dgautsch** [comment]
Having the same issue on lando-v3.0.0-beta.34 on Windows 10 Professional except this is the pantheon recipe. The site is a wordpress site.

**Comment by pirog** [comment]
Good to know. *Pretty sure* this is isolated to Windows. Recommend using beta.33 until this is sorted out.

**Comment by pirog** [comment]
ok i can def replicate this on Win 10 Pro!

**Comment by pirog** [comment]
ok this is obviously a pretty show stopping bug so im going to roll a new release as soon as this passes tests!
