### ISSUE TITLE
Updating Docker for Windows to v46 breaks Lando proxy

### ISSUE THREAD

**Issue by AaronFeledy** [lando/lando#632]
Bug Report
==========

**Tell us about your setup**

lando-v3.0.0-beta.35 on Windows 10 Professional

**Tell us generally about your bug**

Updating Docker for Windows to version 17.12.0-ce-win46 breaks proxy service and prevents apps from starting.

```
ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/C/Users/Aaron/.lando/services/config/scripts/lando-entrypoint.sh\\\" to rootfs \\\"/var/lib/docker/overlay2/167750b90874f3450da3fd97a4ac11fa62f2523227162bd5e8cd6850986ad625/merged\\\" at \\\"/var/lib/docker/overlay2/167750b90874f3450da3fd97a4ac11fa62f2523227162bd5e8cd6850986ad625/merged/lando-entrypoint.sh\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

```
1. Have Docker 17.09.0-ce-win33
2. Successfully create and start a Lando app
3. Say "ok, fine" to Docker's incessant prompts to update to 17.12.0-ce-win46
4. Attempt to start your previously created Lando app or create a new one
5. See failure messages
```

**Tell us more**

Destroying and recreating apps does not fix the issue. 
Removing the landoproxyhyperion5000gandalfedition_proxy_1 container and letting it be recreated during the next `lando start` fixes the issue.

**Comment by burlapdesign** [comment]
Just coming here to second this.

**Comment by joelyoder** [comment]
Third this issue. I'm running the same setup at Aaron. Removing the offending container fixed the issue for me as well.

**Comment by pirog** [comment]
Thanks for the feedback here. I was also able to replicate this when testing the upgrade path on Win. No idea why it happens but i think we can put in something to handle this for Windows users

**Comment by RichardDavies** [comment]
When will a new release be issued with this fix?

**Comment by pirog** [comment]
@RichardDavies given that this fix has both a pretty easy workaround above and is also available in dev builds/source there is not a high priority push to roll a new release just because of this.

We are also in the middle of a pretty extensive change to how the project is structured and run which should lay the foundation for taking the project to the next level. These changes necessitate a more thorough round of tests then we've done in previous releases. As a consequence i dont think there will be a new official release for at least a few more weeks.

**Comment by RichardDavies** [comment]
@pirog I assume the workaround is to "Removing the landoproxyhyperion5000gandalfedition_proxy_1 container and letting it be recreated during the next lando start fixes the issue." Sorry, but I'm new to Lando and not sure how to do that... Could you provide some pointers on how to do that? Thank you.

**Comment by RichardDavies** [comment]
Nevermind, Figured it out:

`docker container rm landoproxyhyperion5000gandalfedition_proxy_1` 

I had to remove several containers before it would successfully start.
