### ISSUE TITLE
Increase Unit Test Coverage

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#638]
Lando isn't as sure of himself as he used to be back in the Cloud city days. He could use a boost in assurances that he's doing the right thing by giving Han to Vader, lets write some test code to re-assure our friend.

**Comment by pirog** [comment]
Lando was unwise to lower his defenses

**Comment by pirog** [comment]
@dustinleblanc so this task implies some refactoring of the codebase to make it more testable. I've gone through the codez and identified a couple of high level things that need to change to make this happen

1. The modules in `lib` definitely are too interdependent. 
2. There are a bunch of modules in `lib` that would be WAY better as plugins (eg `app` and `engine`)
3. The existing plugins need to be put into a common format as dizcuzzed in the slackz

**Comment by dustinleblanc** [comment]
I think we need to set a coverage goal for this. I started on tests over the weekend but we need to decide when done is for this sprint

**Comment by serundeputy** [comment]
Let's get in what we have as a PR
call this done 
then we can iterate on those examples.
