### ISSUE TITLE
Lando apps are not detecting each other's hostnames

### ISSUE THREAD

**Issue by acobster** [lando/lando#640]
**Tell us about your setup**

What is your lando version and operating system?

Lando v-3.0.0-beta.35, Ubuntu 16.04

**Tell us about your `.lando.yml`**

I have two Lando apps, `a` and `b`:

```
# a/.lando.yml
name: a
recipe: lamp
config:
  webroot: .
```

```
# b/.lando.yml
name: b
recipe: lamp
config:
  webroot: .
```

Both are simple `phpinfo()` test apps.

**Tell us about the command you were running**

`lando start a`
`lando start b -- -vvvv`

**Tell us about the error you got**

Per slack discussion today, the `lando-proxy` plugin may not be detecting hosts as intended.

Running the above commands and grepping `stderr` for `xxxxx`, I would expect to see a hostname for `a` when the second command runs. Instead only the hostname for `b` is detected:

```
debug: xxxxx proxy found network hosts 0=b.lndo.site
debug: xxxxx proxy computed external extra_hosts list 0=b.lndo.site:10.0.10.20
debug: xxxxx proxy found preexisting extra_hosts
debug: xxxxx proxy found preexisting extra_hosts
```

Here's my patch for debugging (based off beta.35):

```
diff --git a/plugins/lando-proxy/lib/proxy.js b/plugins/lando-proxy/lib/proxy.js
index 713c233..bee4ec4 100644
--- a/plugins/lando-proxy/lib/proxy.js
+++ b/plugins/lando-proxy/lib/proxy.js
@@ -685,6 +685,8 @@ module.exports = function(lando) {
             return host.indexOf('*') < 0;
           });
 
+          lando.log.debug('xxxxx proxy found network hosts', hosts);
+
           // Send hosts down the pipe
           return hosts;
 
@@ -698,6 +700,8 @@ module.exports = function(lando) {
             return [host, lando.config.env.LANDO_ENGINE_REMOTE_IP].join(':');
           });
 
+          lando.log.debug('xxxxx proxy computed external extra_hosts list', hostList);
+
           // And add them if applicable
           if (!_.isEmpty(hostList)) {
             _.forEach(_.keys(app.services), function(name) {
@@ -708,6 +712,8 @@ module.exports = function(lando) {
                 peeh = _.get(app.services[name], 'extra_hosts', []);
               }
 
+              lando.log.debug('xxxxx proxy found preexisting extra_hosts', peeh);
+
               // Merge the whole shebang
               compose.services[name] = _.merge(compose.services[name], {
                 'extra_hosts': _.flatten(hostList.concat(peeh))
```

The end goal here is simply to have separate Lando apps/repos talk to each other.

**Comment by pirog** [comment]
@acobster thanks for posting this. I'm hoping that this just requires better documentation but we'll find out soon!

**Comment by pirog** [comment]
ok so this definitely works but its very difficult to figure out so i'm going to add some things to make it easier and provide some docs
