### ISSUE TITLE
Latest Docker does not work on recent Windows 10 pro insider previews

### ISSUE THREAD

**Issue by macronomicus** [lando/lando#645]
Bug Report
==========
v3.0.0-beta.36 on Windows 10 Professional
--------------------------------------------------
You can see for yourself in the Docker issues on the latest build (stable and edge), Linux containers no longer work on Windows 10, and there is no fix yet.

I was installing the latest update to Lando to resolve the tmp files directory issue, and instead wiped out my whole lando install lol, no big deal since I have backups of all the important things. 

What happened was the install hung up saying containers were not enabled and it would restart windows to enable them, after restart my containers were wiped out from all sites in lando, and docker will not start with linux containers enabled. Giving the following error.
```
Unable to create File System Image
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass27_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 335
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
Perhaps put a warning for those on Windows 10 not to upgrade Lando or Docker until the issues are resolved.

**Comment by macronomicus** [comment]
Ill just put this here for the record...  The temporary solution is downgrading docker to an older version or not upgrading it.
#https://github.com/docker/for-win/issues/1458

**Comment by macronomicus** [comment]
Actually downgrading docker didnt work for me, I couldn't get a site to start again even with clean installs of the latest lando release and docker, bringing down fresh empty sites from pantheon etc.  I got many of the errors reported already in the issues here.  I suppose ill have to wait for windows to release a hotfix, or maybe downgrade windows, for now im just going to use the inbuilt ubuntu or dev-desktop to do local code work.  I will check back in here at some point soon though since I loved working with Lando, its fantastic!

**Comment by dustinleblanc** [comment]
Hey @macronomicus following up on this as part of backlog grooming. I see this was beta 36, can you confirm if you are stil having an issue with beta 35 and the version of docker that ships with it? Thanks!

**Comment by macronomicus** [comment]
Yeah, sure thing i will test it this weekend, ive been using aquia
dev-desktop and i really miss all the lando bells n whistles!

**Comment by pirog** [comment]
I'm seeing a bunch of people using windows with the latest release so im going to assume this is fixed now. Please reopen if that is not correct and this issue persists in beta.38

**Comment by macronomicus** [comment]
Yes, Ive fully tested and it does appear to be working great now! Yay! :)
