### ISSUE TITLE
Lockr Support

### ISSUE THREAD

**Issue by cellar-door** [lando/lando#651]
Trying to get Lockr running in Lando like we had in Kalabox.

The Lockr module/plugin currently looks for the binding.pem cert to authenticate on behalf of the site. In Kalabox this was accomplished by syncing the binding.pem down from the development environment via SFTP when setting up the appserver. However in Lando, binding.pem is now a self-signed cert so we need to sync to a new pantheon_binding.pem in the /var/www/certs directory.

I've moved the code from the old pantheon.sh to pull.sh under the pantheon recipe as it makes more sense to put it in the pull actions where we're already syncing data from the Pantheon platform. However I'm running into permission issues when trying to write to the /var/www/certs directory.

Just need to figure out how we can get that cert to write and once we do, we'll update our modules/plugins to look for the lando environment and use the pantheon_binding.pem cert instead to authenticate.

Code we're using currently (largely from Kalabox):

`#LOCKR integration
#If we don't have our dev cert already let's get it
	if [ ! -f "/var/www/certs/pantheon_binding.pem" ]; then
	 $(terminus connection:info "$SITE.$ENV" --fields=sftp_command --format=string):certs/binding.pem /var/www/certs/pantheon_binding.pem
	fi

#Lets also check to see if we should refresh our cert
	if openssl x509 -checkend 86400 -noout -in /var/www/certs/pantheon_binding.pem; then
	 echo "Pantheon Dev Cert is good!"
	else
	 $(terminus connection:info "$SITE.$ENV" --fields=sftp_command --format=string):certs/binding.pem /var/www/certs/pantheon_binding.pem
	fi`

**Comment by dustinleblanc** [comment]
@cellar-door I see this has sat for a little bit, probably because @pirog, @serundeputy and I are in a bit of a scramble to get the refactor work finished. 

I think if this issue can be focused down a bit, we might be able to move it into the backlog.

> Just need to figure out how we can get that cert to write and once we do, we'll update our modules/plugins to look for the lando environment and use the pantheon_binding.pem cert instead to authenticate.

That's the big ask right? trying to figure out perms to unblock your contrib work?

**Comment by pirog** [comment]
@cellar-door beta.40 improvements make this trivial! going to make it happen for all the good people of Nashville

**Comment by pirog** [comment]
go away stalebot!

**Comment by pirog** [comment]
@cellar-door DONE!
