### ISSUE TITLE
php 5.3 service via apache cannot inject config

### ISSUE THREAD

**Issue by hanoii** [lando/lando#652]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

Lando-master - macOS High Sierra 10.13.2 (17C205) 

**Tell us about your `.lando.yml`**

```
# LAMP stack example
name: NAME

# Give me http://lamp.lndo.site and https://lamp.lndo.site
proxy:
  appserver:
    - NAME.lndo.site

# Spin up services to run a basic LAMP stack
services:

  # Create a php 5.3 instance served by the latest apache with https turned on
  appserver:

    # PHP version 5.3
    type: php:5.3

    # Serve php by either apache or nginx. You can put in any `service:version`
    # string that is supported by Lando's nginx and apache services.
    via: apache

# Add some nice command routing
tooling:
  php:
    service: appserver
```

I am getting the following error with several apps, but this one is very simple, just static PHP:

```
$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.3-alpine)...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "serberlawfirm_default" with the default driver
Creating volume "serberlawfirm_appserver" with default driver
Creating volume "serberlawfirm_data" with default driver
Pulling appserver (devwithlando/php:5.3-apache)...
Creating serberlawfirm_appserver_1 ... error

ERROR: for serberlawfirm_appserver_1  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/ariel/.lando/services/config/php/php.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged\\\" at \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged/usr/local/etc/php/conf.d\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for appserver  Cannot start service appserver: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/ariel/.lando/services/config/php/php.ini\\\" to rootfs \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged\\\" at \\\"/var/lib/docker/overlay2/ea1a7c06ac7e8d176c01fb6ca74d44b0cb8028cec9a561d272bfba2e84e53512/merged/usr/local/etc/php/conf.d\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
Creating network "serberlawfirm_default" with the default driver
ERROR: Network lando_bridge_network declared as external, but could not be found. Please create the network manually using `docker network create lando_bridge_network` and try again.
error:  Error: Error
    at /Users/ariel/Work/lando/lib/promise.js:56:17
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at rec (/Users/ariel/Work/lando/lib/promise.js:42:13)
    at /Users/ariel/Work/lando/lib/promise.js:50:20
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at /Users/ariel/Work/lando/lib/promise.js:49:12
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I am also on latest docker edge and tried resetting docker to default and pulling everything again.

I am not sure if this is lando, but any ideas?

**Comment by pirog** [comment]
@hanoii using the `master` branch (eg the latest source) is not supported and def in "use at your own risk" territory. So if you are having issues it's advisable to checkout out the latest official release which is `beta.35` as of writing. 

If you still have the same issue after doing that then feel free to reopen this.

**Comment by hanoii** [comment]
Same thing on `v3.0.0-beta.36`

**Comment by pirog** [comment]
@hanoii see above comment: `beta.35` is the actual latest stable release, not `beta.36`

**Comment by hanoii** [comment]
Sorry:

```
$ lando version
v3.0.0-beta.35
```

Same thing.

I still think this is not lando's, but I just wonder if you had an idea about anything like this. I don't expect a ton of support other than maybe see if this has happened to anyone else. It seems to be a docker thing or a docker related to something else. I dunno. But as lando is currently the only docker thing I am using and it's definitely a mounting thing I wondered.

I should mention I am not using your downloaded releases but rather git checkout and npm install, I did branched to the latest stable tag.

I am using the latest docker -edge so that could also be related, but I'd think you'd hit this issue somewhere along the line eventually with more people (if it's really something lando's related).

**Comment by pirog** [comment]
@hanoii yeah best advice i can give is what the error message says `Check if the specified host path exists and is the expected type`. 

My guess for something like that is maybe you are trying to mount a config directory instead of a specific file? The php 5.3 apache service is also REAL old and not super well maintained so its totally possible it's just out of date and this is a legit bug with that.

**Comment by hanoii** [comment]
Yes, It's an old site that's why I wanted to use lando with it.

`/Users/ariel/.lando/services/config/php/php.ini` does exist though.

**Comment by hanoii** [comment]
I tried before (with master) this on a much newer lando recipe (d8/7.1) and it didn't work either, I am trying now again with beta35

**Comment by pirog** [comment]
This looks suspect to me
https://github.com/lando/lando/blob/master/plugins/lando-services/php/php.js#L94

**Comment by pirog** [comment]
Yeah try changing line 95 there to 
`typeConfig.apache.phpConfDir = '/usr/local/lib/conf.d';`

**Comment by pirog** [comment]
If that works i would also totally open up a pull request!

**Comment by hanoii** [comment]
That actually worked!

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/654

works as advertised! Thanks @hanoii RTBC
