### ISSUE TITLE
Upgrade your lando message.

### ISSUE THREAD

**Issue by generalredneck** [lando/lando#657]
Feature Request
===============

As a lando user, I would like to know when a newer version of lando is out so that I can upgrade and have the latest bug fixes.

An expected outcome may be to show a message like terminus does when a command is run specifying that the current version is out of date.

Bonus points if for a self-update command... but not necessary as I know that that may be difficult to cross platform.

**Comment by pirog** [comment]
@generalredneck we already do this! https://github.com/lando/lando/blob/master/lib/update.js#L84

self-update is a little more tricky and probably not something we are going to support

**Comment by generalredneck** [comment]
Awesome. I just upgraded from beta20 a few days ago. Haven't gotten to see it in action yet... but looks like several of our guys were saying this over a 4k so I thought I would suggest it and see. 

Thanks tons.
