### ISSUE TITLE
Offline development configuratin OSX sometimes needs a dns flush when setting it up

### ISSUE THREAD

**Issue by jbertoen** [lando/lando#661]
Not a bug, just a small document change needed to inform users that when setting up dnsmasq en the resolver, also do a dns flush after the restart of OSX.

**Comment by dustinleblanc** [comment]
LGTM
<img src="https://i.imgur.com/yQ5odA5.gif">

**Comment by dustinleblanc** [comment]
Looks like this was implemented, closing, thanks for the PR!
