### ISSUE TITLE
I ❤️ Lando; It has made my life easier!

### ISSUE THREAD

**Issue by amazingrando** [lando/lando#663]
THIS IS A COMPLIMENT, NOT AN ISSUE. (I didn't see any other place to send this compliment.)

As soon as I found Lando creating local dev environments got so much easier. I used to use Vagrant and had no end to complicated issues. 

I appreciate the hard work that everyone is putting into this. Thank you.

Admins can close this issue after reading.

**Comment by rafalfaro18** [comment]
I agree @amazingrando this guys are heroes.

**Comment by dustinleblanc** [comment]
@pirog take a bow!

**Comment by JamesJosephFinn** [comment]
@amazingrando Do you use Lando with Pantheon?

If so, I'm curious how Lando syncs config stored in the database if you make changes locally, and try to sync those changes up to the Pantheon dev environment.

In the past, I've used the Pantheon recommended wp-cfm (config management) plugin, but it is not bulletproof. There's certain settings that get missed by that plugin.

I'm assuming that Lando has not reinvented the wheel, and is using wp-cfm in their stack. Is that true, @dustinleblanc?

Thanks!!

**Comment by amazingrando** [comment]
I don't personally use Lando with Pantheon. The team at Four Kitchens is
slowly rolling out Lando on projects and many of them are on Pantheon.

We believe that we have a WP site using Lando. I'll see what they're using
tomorrow and get back to you.

**Comment by dustinleblanc** [comment]
@JamesJosephFinn nope, Lando's push just straight up pushes your code, database, and files. Don't do that, use WP-CFM instead. If it misses stuff, I'd look into storing your config changes in a plugin and use the upgrade system to fire off upgrades declaratively.

**Comment by JamesJosephFinn** [comment]
@dustinleblanc

>"I'd look into storing your config changes in a plugin and use the upgrade system to fire off upgrades declaratively."

Do you have a tutorial / example implementation that you could point me to. Thanks!
