### ISSUE TITLE
db-import often fails when importing a DB just after the DB container was spun up

### ISSUE THREAD

**Issue by anavarre** [lando/lando#677]
Very often, when I'm trying to import a DB dump just after `lando start`, I'm seeing a failure as a result. Below I'm trying to import the DB 3 times in a row and get a failure always. When I `lando mysql`, it then allows me to import just fine. It's as if there was a need to establish a successful connection to the DB container first before it's actually capable of importing a DB dump successfully.

```
$ lando db-import test.sql.gz
Preparing to import /app/test.sql.gz into drupal8 on database:3306 as drupal8...
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
Destroying all current tables in drupal8... 
NOTE: See the --no-wipe flag to avoid this step!
Gunzipped file detected!
Importing /app/test.sql.gz...
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
  96KiB 0:00:00 [25.3MiB/s] [>                                 ]  5%            

Import failed.
$ lando db-import test.sql.gz 
Preparing to import /app/test.sql.gz into drupal8 on database:3306 as drupal8...
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
Destroying all current tables in drupal8... 
NOTE: See the --no-wipe flag to avoid this step!
Gunzipped file detected!
Importing /app/test.sql.gz...
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
  96KiB 0:00:00 [43.2MiB/s] [>                                 ]  5%            

Import failed.
$ lando db-import test.sql.gz 
Preparing to import /app/test.sql.gz into drupal8 on database:3306 as drupal8...
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
Destroying all current tables in drupal8... 
NOTE: See the --no-wipe flag to avoid this step!
Gunzipped file detected!
Importing /app/test.sql.gz...
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
  96KiB 0:00:00 [42.4MiB/s] [>                                 ]  5%            

Import failed.
$ lando mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.21 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
$ lando db-import test.sql.gz 
Preparing to import /app/test.sql.gz into drupal8 on database:3306 as drupal8...
Destroying all current tables in drupal8... 
NOTE: See the --no-wipe flag to avoid this step!
Gunzipped file detected!
Importing /app/test.sql.gz...
1.74MiB 0:00:14 [ 124KiB/s] [================================>] 100%            

Import complete!
```

So perhaps there's something missing in the deployment process that would make the DB container able to listen on the defined port without having to `lando mysql` first.

I want to insist on this operation not always failing. Sometimes it imports successfully on the first attempt.

**Comment by joelyoder** [comment]
I spend several hours this evening trying to figure out why I could not pull the database from my Pantheon dev site using Lando on a new computer. I've never run into this issue before, but opening the MySQL monitor fixed it for me as well. I'd still be fighting with it if I hadn't found this open bug - thanks a million!

**Comment by serundeputy** [comment]
I will see if I can reproduce this and get it moving.

**Comment by dustinleblanc** [comment]
@serundeputy did you want to look into the implementation of the healthcheck on this?

**Comment by serundeputy** [comment]
@dustinleblanc I can take a look, but this is currently blocked in `master` by #711 which is causing all the sql ops to fail. So, I'm going to start there.

**Comment by pirog** [comment]
OTS here, going to see if we can implement a smarter check to ensure the DB container is actually up and good to go before we start importing things

**Comment by pirog** [comment]
ok i can't replicate this but i have heard enough similar things to be convinced that it's real so im going to try to spoof the behavior and implement the healthcheck

**Comment by pirog** [comment]
so the `healthcheck` option doesnt do what we want but ive found this which seems like a decent alternative
https://docs.docker.com/compose/startup-order/

**Comment by dustinleblanc** [comment]
I think this solution accomplishes what we want.

**Comment by pirog** [comment]
@dustinleblanc yeah the issue i am seeing now is that the checks in that doc are intra-container. so the implementation they have is something like appserver waits for db to be ready before it flags itself as "running" and we want something like db waits for itself to be ready before it flags itself as "running". 

the tight coupling there makes it problematic because of the wide variety of potential combinations someone could have in their landofile, particularly if they arent using a recipe. im seeing if i can find a clever hack though

**Comment by pirog** [comment]
alright! we've got a plan!

after talking to @dustinleblanc on the slack what we are going to do is add some logic on the lando side that inspects containers post-start to ensure any container with a "healthcheck" has reported back healthy before proceeding. this will slow down starts but ensure a start actually means "ready to go".
https://www.youtube.com/watch?v=JgffRW1fKDk

**Comment by wdrupal** [comment]
I have next error when run lando start after this update

```
ERROR: The Compose file '/home/xxx/.lando/compose/layout-hackaton/layout-hackaton-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
```

Docker version 17.12.1-ce, build 7390fc6
docker-compose version 1.19.0, build 9e633ef
