### ISSUE TITLE
Feature Request: Alert compatibility warning when using untested versions of docker

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#678]
It seems that Lando can be touchy when it comes to the version of docker that is running. I've instructed my team to let Lando manage the version of docker that is installed and do not update when prompted by docker.

Though we have our own internal rules when it comes to Lando and Docker, it would be a nice little feature to have Lando issue a warning when starting that an unsupported version of docker is being used or, at the very least, issue an alert stating that it is recommended to let Lando manage docker versions.

**Comment by pirog** [comment]
@tylerssn this will be in 3.0.0-rrc.8
