### ISSUE TITLE
make `lando drush cr` run as fast as `drush cr` in docker

### ISSUE THREAD

**Issue by shaal** [lando/lando#680]
Feature Request
===============

As a lando user who works with Drupal sites I want to be able to run `lando drush cr` as fast as running it with docker.

I am using Ubuntu 17.10, XEON 6 CPUs with SSD.
Lando v3.0.0-beta.35

To compare, I installed a plain d8 using lando, and plain d8 using [docker4drupal](https://wodby.com/stacks/drupal/docs/local/quick-start/)

testing results:
**D8 on Lando**
`time lando drush cr`
```
real 5.35
user 1.13
sys 0.13
```

`lando ssh`
`time drush cr`
```
real    0m4.132s
user    0m3.190s
sys    0m0.241s
```

**D8 on Docker4Drupal**
`time drush cr`
```
real    0m1.856s
user    0m1.257s
sys    0m0.215s
```

**Comment by richvida** [comment]
Relevant discussion: https://github.com/lando/lando/issues/561

**Comment by pirog** [comment]
yeah @shaal, im going to close this in favor of the default answer in #561. 

that said if it can be demonstrated that there is something **IN THE LANDO CODE ITSELF** that is causing a significant slowdown then def please open a new issue.

alternatively, if someone has a superior file sharing idea that is cross-platform, as stable as what docker offers, does not present additional problems and wouldn't require more than 100 hours to implement then all ears for that too.
