### ISSUE TITLE
Automatic standalone php CLI container

### ISSUE THREAD

**Issue by ultimike** [lando/lando#684]
I'm curious if there are plans to include a standalone CLI container similar to what Docksal offers with the `fin run-cli` command.

The reason I'm asking this is that I often teach Windows users Drupal development and having access to this type of "maintenance" container would remove the requirement of having to install Composer on the local OS. With Docksal, I'm able to do a `fin run-cli composer create-project...` _before_ initializing the project's containers - which is kind of a big deal.

Thoughts?

**Comment by pirog** [comment]
@ultimike you can currently add standalone php cli containers at your leisure. 

We actually automatically include standalone cli containers for our `node`, `python`,  `go`, `ruby` and `dotnet` services by default by default. Since `composer` is finally becoming more widely used maybe it's time for us to do the same for `php`.

**Comment by ultimike** [comment]
@pirog That was be most excellent. 

Just out of curiosity, how to the automatically included containers for `node`, `python`, etc... work? Looking at the documentation, it looks like they have to be added to an existing project via the .lando.yml's `tooling` section.

**Comment by dustinleblanc** [comment]
@ultimike It's part of the recipe configuration for those recipes. You wouldn't normally have a global utilities container like you are suggesting, but I think that's a cool concept, especially for Windows devs.

**Comment by pirog** [comment]
Now that we've had time to see how people use lando i dont think this quite fits our model. Using our `init` command (esp in rc2+) or `build` steps is likely what we should recommend people do here instead of having some disconnected php cli container
