### ISSUE TITLE
Sync the docs after #620 and before beta.37

### ISSUE THREAD

**Issue by pirog** [lando/lando#685]
Once the chaos of the refactor begins to die down we definitely want to do a pass on all the docs to make sure they are still in alignment with the facts on the ground. I am happy to do most of this but here are the main areas:

* Updating any relevant install/contrib instructions to reflect new `yarn` usage
* Updating relevants API docs so they are built from the correct places and include plugins and their modules
* Adding in a more robust contrib section so we can start to set up some roles/responsibilities/governance/etc

Other things?

**Comment by dustinleblanc** [comment]
Thankfully I did update docs for for dev processes using yarn, but we might need to look at install from source docs.

**Comment by pirog** [comment]
@dustinleblanc nice! i think this i mostly to accommodate the refactoring i did (eg bullet points 2 and 2)

**Comment by dustinleblanc** [comment]
👍  just wanted to make sure to note what we've done, should we start a little checklist?

- [ ] start checklist
