### ISSUE TITLE
Lando fails to start if the name contains an underscore

### ISSUE THREAD

**Issue by Kwapi** [lando/lando#697]
Version: 3.0.0 beta35

Steps to reproduce:

Set the name in .lando.yml to contain an underscore i.e. 'ysa_wp'

On `lando start`, lando will create the database and app server called 'ysawp_appserver_1' and 'ysawp_database_1' (notice the lack of underscore). Then it will crash with this error:
```
error:  Error: Error: The container ysa_wp_appserver_1 does not exist!
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:0:0)
    at /snapshot/cli/lib/promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

It's looking for a container **with** the underscore but it has already created one **without** the underscore

Switching the name to be 'ysawp' stops the error.

It would be nice to either fix the behaviour or at least prevent users from putting in a name with an underscore.

**Comment by pirog** [comment]
@Kwapi seems reasonable. 

We've got a function that tries to parse user-inputted names into docker-compose names but i guess that function is not as robust as it needs to be.

**Comment by pirog** [comment]
@Kwapi so i dont get an error doing this on `master` but i do get something not quite right.

If you run `lando init` it will translate an app name with a `_` to a `-` and that seems to work. But if you handcraft your landofile with an appname that has a `_` it doesnt quite work

**Comment by pirog** [comment]
@Kwapi closing this as part of #829
