### ISSUE TITLE
Provide some clearer guidelines for BD, Maintainers, Committers and Contributors

### ISSUE THREAD

**Issue by pirog** [lando/lando#701]
We've got governance and generic roles and responsibilities defined in our new docs but we need some clearer and more specific day to day guidelines for these roles. We should add the following sections to our contrib docs

* For Benevolent Dictator
* For Maintainers
* For Committers

Here are some things we should consider adding to each section 

#### For BD

* Just a basic "dont be a dick" reminder with reference to https://producingoss.com/html-chunk/benevolent-dictator.html

#### For maintainers

* Milestone/release creation procedures
* Issue assignment for milestones/releases
* Sprint/release cycle planning based on reasonable story point estimation
* Issue triage and pull request procedure

### For committers

* Policies around submitting and merging pull request

**Comment by serundeputy** [comment]
@pirog is this done?
I know we have new governance docs up on docs.devwithlando.io
