### ISSUE TITLE
Add a --help option for each command

### ISSUE THREAD

**Issue by YPCrumble** [lando/lando#706]
It would be very useful to have a simple way of remembering args for each command. For instance, I couldn't remember the args for `lando pull` today. It would be fantastic if something like:

`lando pull --help`

would return:

# USAGE
## This will pull the environment associated with your currently checked out git branch
lando pull

## Skip a code merge
lando pull --code=none

## Pull only the database from the test environment
lando pull --database=test --files=none

## Pull only the files
lando pull --database=none

## Pull only the latest files without grabbing a files backup
lando pull --database=none --rsync
# OPTIONS
--code, -c      The environment to get the code from or [none]
--database, -d  The environment to get the db from or [none]
--files, -f     The environment to get the files from or [none]
--rsync         Rsync the files, good for subsequent pulls

**Comment by serundeputy** [comment]
Hello @YPCrumble I think the droids you are looking for are: `lando pull -- -h` or `lando pull -- --help`

```bash
geoff@yep$ lando pull -- -h
/usr/local/bin/lando pull

Options:
  --code, -c      The environment to get the code from or [none]
  --database, -d  The environment to get the db from or [none]
  --files, -f     The environment to get the files from or [none]
  --rsync         Rsync the files, good for subsequent pulls
                                                      [boolean] [default: false]
```

Closing out.
