### ISSUE TITLE
While lando ssh <container> fails loudly, lando info happily reports no error, and lando start happily reports no error

### ISSUE THREAD

**Issue by jleaders** [lando/lando#713]
Feature Request: Improved Error Detection 
===============

As a new user to lando, an error-less `lando info` and an error-less `lando start` seems to imply the containers are all functional. However, I noticed I can have this message appear:

```
BOOMSHAKALAKA!!!

Your app has started up correctly.
```

Yet if I run `lando ssh <failing-container-name>` I get an error connecting because the container was down.

I feel that there should be a way for lando to detect failed containers and report them on both `lando start` and `lando info` (at worst [slowest] case, lando could silently `lando ssh` into all of them once and report any failures, but there's probably a faster way than that)

The cause of my failing container was switching a mariaDB to MySQL & changing versions without doing a `lando destroy` / `lando rebuild`, but that was happily silently undetected by lando, even though the containers clearly weren't bootstrapping enough for `lando ssh` to function.

**Comment by dustinleblanc** [comment]
Cool Idea @jleaders! We'll put this suggestion into consideration for future post 3.0 sprints. Thanks!

**Comment by pirog** [comment]
@jleaders closing this because we explicitly scan for unhealthy containers, esp db containers and report this now
