### ISSUE TITLE
`lando info` injected as environment variable in all containers

### ISSUE THREAD

**Issue by vincenzo** [lando/lando#727]
Feature Request
===============

**AS** a Lando user
**I WANT** the same info yielded by `lando info` to be available as an environment variable (e.g. `LANDO_INFO`) in all containers part of my Lando app
**SO THAT** all services can "know" each other peculiar information (e.g. URLs, etc.)

The variable could be encoded with `base64`.

**Comment by pirog** [comment]
@vincenzo definitely +1 this and shouldn't be too tricky to do either

**Comment by dustinleblanc** [comment]
I am curious if base64 encoding is needed here? Is this just to make the format something easy to store in an env var? My concern is that it isn't human readable and requires decoding. I am -1 on that unless we automatically decode it for folks. A gnarly minified JSON string is much easier to grok IMO.

**Comment by pirog** [comment]
@dustinleblanc yeah i think i am with you on that. i know platform.sh base64 encodes these things which im guessing is where @vincenzo got that. I'm not super clear on WHY they do that instead of a straight JSON string. maybe just to avoid escaping hell? obfuscation?

**Comment by dustinleblanc** [comment]
Yeah I was curious if it was for secrecy in case anything got exposed via the API in a way they didn't want. I'd say it almost fits into our earlier YAGNI reference :wink:

**Comment by vincenzo** [comment]
Avoiding "escaping hell" is a good enough reason for me! But yeah, I proposed the encoding because of my being used to P.sh.

**Comment by mikeshiyan** [comment]
Are there any plans to provide `urls` in the var?
