### ISSUE TITLE
Is there a way to stipulate which version of the Docker compose file to use?

### ISSUE THREAD

**Issue by rgoodie** [lando/lando#733]
Issue
--
**Problem:**
Docker v 17.12.1-ce -- which is the default on Ubuntu 16.04 LTS cannot run docker compose files --  under `Version 3.x`. The [Docker Compatibility Matrix](https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix) suggest that version 2.1 be used with this Docker engine version. 

The Question
--
Is there a way to stipulate which version of the Docker compose file to use? Using this version of Docker it expects `2.1` or an omission of the version directive. 

Errata and Versions
--

*CLI / Lando Error Reported*
``` 
$ lando init
? What recipe do you want to use? wordpress
? Where is your webroot relative to the init destination? .
? What do you want to call this app? my-lando-app
```
> error: Error: Version in "/home/user-a346bcde/.lando/util/util-my-lando-app-1.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

*Lando Version*
```
$ lando version
v3.0.0-beta.36
```

*Docker Information*
```
$ docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:40 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:13 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

*Host OS*
```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

**Comment by pirog** [comment]
@rgoodie you might be able to change the docker compose version using https://docs.devwithlando.io/config/config.html. `lando config` will give you a list of all the config that is overridable.

That said i would definitely encourage you to use the versions of docker and docker compose that lando prefers you use otherwise you are likely going to have a bad experience
