### ISSUE TITLE
Drush issues?

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#745]

**Comment by pirog** [comment]
dropping a quick note here. i think this can also happen if you have build steps that error out and prevent teh drush install from happening. it might be nice to provide internal build/extra keys so we can reliably define build steps programmatically without caring what the user provides

**Comment by serundeputy** [comment]
that would explain it for platform.sh users for sure; as we have a failing build step in the docs at p.sh ... we should provide PR to update those docs or fix p.sh cli installation https://github.com/lando/lando/issues/646
