### ISSUE TITLE
Reference properties within the .lando.yml file

### ISSUE THREAD

**Issue by jmdrawneek** [lando/lando#749]
As a developer, I would like to be able to create lando configuration template files with variables that can be set at the top of the file. This would reduce the chance of typos and make repeatable environment setup much quicker.

I would like to propose a similar system to serverless (https://serverless.com/framework/docs/providers/aws/guide/variables/) where you can reference items from anywhere in the configuration file.

**Comment by dustinleblanc** [comment]
I'm generally +1 on this as a concept, what say ye @serundeputy @pirog?

**Comment by fchris82** [comment]
The `env` options will be useful too: 
https://serverless.com/framework/docs/providers/aws/guide/variables#referencing-environment-variables

**Comment by dustinleblanc** [comment]
I _think_ we already do that

**Comment by jmdrawneek** [comment]
@dustinleblanc Currently Lando loads the env vars into the global variables, not the Lando config file. 

I should get a chance this weekend to address those comments on the PR and get code amends sorted.

**Comment by pirog** [comment]
Closing this but check out https://github.com/lando/lando/pull/750#issuecomment-453878919
