### ISSUE TITLE
Push code to pantheon multi-dev

### ISSUE THREAD

**Issue by idpokute** [lando/lando#754]
Feature Request
===============

I bring this ticket due to pantheon multidev. I'm using Wordpress on Pantheon. When I run `lando push` on my multi-dev that was changed by `lando switch`. It pushes code to dev environment not multidev. Does Lando has a functionality to push code to multidev?

Please provide some detail on how lando can help solve this problem

If the target env of `lando push`  is the current dev environment, it would be good. Or `lando push env-name` would be good as well.

**Comment by dustinleblanc** [comment]
Solid request @idpokute, confirmed that `lando push` doesn't check for which branch you are on before executing it's push of code. We'll consider this in a future sprint

**Comment by MadCoder253** [comment]
Just wanted to say that this would be a very handy feature. If there's a work around please let me know. I need to push changes to a multidev branch for a client to review but not to the Dev branch since there could be other changes that take place before the multidev branch is approved.

**Comment by dustinleblanc** [comment]
@MadCoder253 the best work around is just to push code via git `git checkout -b branch-name` and then `git push origin branch-name`. You can then upload the database via `lando db-export` and uploading the tar file to the dashboard.

**Comment by MadCoder253** [comment]
Thank Dustin that worked.
