### ISSUE TITLE
Docker restart causes Lando to grab ports 80 and 443

### ISSUE THREAD

**Issue by ultimike** [lando/lando#761]
I'm not sure if this is a bug or the expected behavior, but... when I restart Docker, it appears that the Lando proxy automatically starts up and grabs a hold of port 443. This is unfortunate if another process wants to use that port - especially if no local Lando sites are up-and-running.

Is there a configuration setting somewhere that I can set to stop this from happening? Ideally, I'd prefer if the proxy was only running when one of my local Lando sites was running.

I'm on Mac OS X with Lando version `v3.0.0-beta.35` and Docker version `17.09.1-ce-mac42 (21090)`.

thanks,  
-mike

**Comment by pirog** [comment]
@ultimike you can turn off the proxy if you want
https://docs.devwithlando.io/config/config.html

this is actually not the expected behavior. proxy should only turn on when its needed so id file this as a bug for now.
