### ISSUE TITLE
Adding Lando Service via Plugin

### ISSUE THREAD

**Issue by lammensj** [lando/lando#765]
Hi,

First, let me thank you for your AWESOME work on this amazing tool! It makes using Docker child's play.

Now back to the problem/question: I was trying to create a custom plugin which loads a custom service in order to use Elasticsearch 6.2 and Kibana. I can see the plugin being loaded in de logs (see line [139](https://gist.github.com/lammensj/91cb486ef2b1b2a287eefc2299bee0c6#file-lando-log-L139), but the event listeners are never handled, and therefor, my service never gets registered. This results in a [warning](https://gist.github.com/lammensj/91cb486ef2b1b2a287eefc2299bee0c6#file-lando-log-L119) saying that my service does not exists upon building.
I'm assuming it's somewhat related to [Adding Lando Recipe via Plugin](https://github.com/lando/lando/issues/597)

Here is a gist with all the code: https://gist.github.com/lammensj/91cb486ef2b1b2a287eefc2299bee0c6

Am I missing something?

**Comment by pirog** [comment]
@lammensj going to close this in favor of #961
