### ISSUE TITLE
document code style for tests (runtime too)

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#766]
Now that contributors are ramping up and we are putting stakes in the ground and drawing lines in the sand on code conventions and readability, we need to document them. This is a moving target as well since we are moving to es6 syntax, but some things we *do* know now:

- [ ] tests are all BDD assertion style via Chai/Mocha

What else?

**Comment by dustinleblanc** [comment]
Some others that I think are good:

Object creation:
@pirog has a style in existing code that I am still kind of learning, and my mind is in flux on this as I try to retool myself from using Classical Inheritence to moving to a functional and composition only future.

Variables:
My preference is to remove as many temporary variables as humanly possible as I think it reduces cognitive load and makes code easier to reason about. However, I feel like this probably is *worse* for code understanding for beginners, so its a strong opinion, weakly held

**Comment by pirog** [comment]
@dustinleblanc i think our current eslint combined with codeclimate is probably sufficient to guide us here. plus this issue is getting hella old so im just going to kill it as part of housekeeping
