### ISSUE TITLE
events example broken

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#767]
![image.png](https://images.zenhubusercontent.com/5a026ca28a75884b90867dab/0126515b-53de-4327-abf8-d8e5cb3b7fa8)
```sh
error: cmd.concat is not a function
```

**Comment by jmdrawneek** [comment]
I'll crack on with this ticket.

**Comment by jmdrawneek** [comment]
@dustinleblanc What os did you come across this? I can't reproduce on OS X 10.13.3.

These are my steps:
> cd examples/events
> lando start | grep "App restarted"
> lando test
runs after test

**Comment by dustinleblanc** [comment]
OSX 10.13.3 but keep in mind, you have to pull the latest master and user your copy of the code, not the production lando (beta.35). You need to be running the example from source. This is for our upcoming release and is for the pre-release code

**Comment by jmdrawneek** [comment]
I get you. I've got lando.dev and lando.stable setup now 👍

Here's the PR for this fix.
https://github.com/lando/lando/pull/769

**Comment by pirog** [comment]
@dustinleblanc @jmdrawneek so i think the underlying issue here is actually that for `cmd: true`, `true` is being parsed (correctly) as a `boolean` which is causing the arrayification logic we actually have in there already to not be triggered.
