### ISSUE TITLE
tests for lib/config.js

### ISSUE THREAD

**Issue by jmdrawneek** [lando/lando#772]
Feature Request
===============
As a Lando user I want to be able to be to use any of the config module methods so that I can manipulate or load configuration so I can build my environment.

Solution:
Build unit tests to ensure reliability across all the config methods.

**Comment by jmdrawneek** [comment]
Here is the PR for this issue: https://github.com/lando/lando/pull/773

**Comment by dustinleblanc** [comment]
Hi @jmdrawneek ! Thanks for diving headfirst into this! It looks like I unintentionally led you by my example to tests that @pirog has already covered in #675.

**Comment by pirog** [comment]
@jmdrawneek dropped some comments in #773, we probably want to codify those comments into our testing doc over at https://github.com/lando/lando/blob/master/docs/dev/testing.md. By that i mean if you could also update the docs as part of this issue that would be awesome :) The immediate things there are 

1. Let's (at least for now) just test exportable functions
2. Let's (also at least for now) use `/**` started comment blocks for exported functions only (else we get a bunch of unwanted stuff in our API docs) and use `/*` everywhere else
3. Let's provide some clarity around where various tests live. eg `tests/unit` and `tests/functional`. It might also be relevant to link to (or edit) https://docs.devwithlando.io/dev/structure.html
