### ISSUE TITLE
Lando Apps Start Super Slow

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#774]
Bug Report
==========

**My Setup**
Lando: v3.0.0-beta.35
MacOSX: High Sierra

Lando App Config
```
name: cloudsponge
recipe: pantheon
config:
  framework: wordpress
  site: cloudsponge
  id: 450cf3bb-6e60-40c9-8773-8019c096c7ff
```

**Command**
```
alexanders-MacBook-Pro-2:slin alex-vasquez$ lando start time
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting cloudsponge_cache_1 ... 
Starting cloudsponge_index_1 ... 
Starting cloudsponge_index_1 ... done
Starting cloudsponge_appserver_1 ... done
Starting cloudsponge_nginx_1 ... done
Starting cloudsponge_edge_1 ... done
Starting cloudsponge_edge_ssl_1 ... done
```

**Error Description**

Lando Apps take several minutes to start, for me. Upwards of five minutes or more.

**Trouble Shooting Steps**
- First, I tried to run `lando stop` and then `lando start`, still didn't work. Same issue. 
- I tried rebuilding the app, no good.
- I stopped lando, removed the app and tried reinstalling again. Same result. [Screenshot](https://digisavvycdn.s3.amazonaws.com/slin__lando_start_time__8021_2018-03-18_02-20-02.png)

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Reproduce:*

Honestly, I don't think you can. If it works for you then you're in great shape and an enviable place. All I do is type `lando start` and wait.

Does this bug prevent you from using lando?
Sure does!

**Comment by dustinleblanc** [comment]
Hi @digisavvy , is this the first time you're spinning up the apps? Lando has to pull images from Dockerhub if you don't already have them which can take a long time. Rebuild will force the same pull to happen again.

A lot of things are going to affect this, from your internet speed, to the disk throughput on the system.

It certainly can be annoyingly long, but once the images are pulled, life is much faster. We could definitely improve the UI for that a bit so you know what's happening and why its taking ages.

**Comment by pirog** [comment]
@digisavvy its not clear to me whether the apps take a super long time to start or whether `lando start` is actually hanging. Can you clarify that?

**Comment by digisavvy** [comment]
@pirog - what seems to be the case is that `lando start` hangs. When I see this '[screenshot](https://digisavvycdn.s3.amazonaws.com/alex-vasquez__lando_start__8024_2018-03-19_10-29-41.png)'  I can actually open the site in my browser. And after 5 or 10 minutes the command will finish and give me my relevant URLs.

**Comment by digisavvy** [comment]
@dustinleblanc it's not the first time I've spun this site up, I've done it a few times now but each time it takes awhile for the `lando start` command to finish.

**Comment by nlenkowski** [comment]
@digisavvy I had a similar issue, with `lando start` hanging even though the site was accessible and everything seemed to be running fine. I eventually narrowed down the cause to running a more recent version of Docker for Mac than the version packaged with the Lando 3.0.0 Beta 35 installer (17.09.1-ce-mac42). 

I completely removed Docker for Mac and Lando and reinstalled both from the Lando installer. I then disabled automatic updates for Docker for Mac and the issue has yet to reappear. A bit of a bummer since this keeps me from running the most recent release of Docker for Mac, but I'm fine with the trade-off until Lando 3.0 lands.

@pirog Just wanted to say that Lando is amazing and has completely modernized the way I do local development! Docker alone is a pain, Lando makes using Docker a pleasure. Thanks a ton for your hard work on it and making it available to the development community.

**Comment by digisavvy** [comment]
@nlenkowski - thanks for the tips, I did uninstall docker/lando and reinstalled lando, skipping prompts to update docker. Unfortunately, the issue persists which is a bit of a bummer.

That said, Lando _is_ awesome. I love using it with Pantheon. I'm excited to keep using it.

**Comment by digisavvy** [comment]
Just an update here but this issue persists with v3.0.0-beta.37.

**Comment by pirog** [comment]
@digisavvy we don't really know what this issue is yet or have steps to replicate it so until we get them its unlikely this will be "fixed" in any future release.

**Comment by digisavvy** [comment]
Thanks @pirog - I guess I'll close this issue then. Are there known issues with other server environments running on the same system that could cause the issue? I run only one server environment at a time so I'm not running Lando and MAMP at the same time, but both are installed. It would be nice to figure it out obviously. So any thoughts or ideas are appreciated.

Thanks.

**Comment by pirog** [comment]
Not that i'm aware of or that ive seen reported. If you have "orphaned" apps, eg you've started an app but then deleted the directory for that app lando will take some time to try and clean up the containers for the deleted app which can take some time.

Another obvious thing that comes to mind is that maybe your computer is just older? I've got a late 2015 MacBook Pro i7 with 16GB of RAM and it takes me about 33 seconds with high verbosity turned on (which probably adds a good 20% overhead).
