### ISSUE TITLE
Update documentation for setting the Drush site URI

### ISSUE THREAD

**Issue by pascal-kubrick** [lando/lando#800]
In Drush 9 the config system was changed to YAML so setting a drushrc.php file won't do anymore if you want to change the site URI used by Drush.

The new way is to create a file called drush.yml like so:

```yaml
options:
  uri: "http://mysite.lndo.site"
```

More info about the new config system can be found here: https://raw.githubusercontent.com/drush-ops/drush/master/examples/example.drush.yml

**Comment by dustinleblanc** [comment]
@pascal-kubrick where do we document this currently? We might want to just link to Drush's docs rather than provide our own and keep them up to date

**Comment by pascal-kubrick** [comment]
@dustinleblanc It's at https://docs.devwithlando.io/tutorials/drupal8.html#drush-url-setup
