### ISSUE TITLE
test lib/cache.js

### ISSUE THREAD

**Issue by pirog** [lando/lando#802]

**Comment by pirog** [comment]
@serundeputy @dustinleblanc i pushed up https://github.com/lando/lando/tree/802-unitTestCache with a good start on the specs. That said here are some relevant notes to move this forward if you guys want to take it from here:

1. We def should consider the note here first to make things simpler: https://github.com/lando/lando/compare/802-unitTestCache#diff-63fdc6a01d0ec0cbf9772723f2356e46R88 this happens in all three of the BIG 3 cache functions so would be less tests and a better overall solution AKA we should do this. This would require finding current cache keys that contain `:`, replacing them with `.` and then adding some logic to throw an error for unsupported characters.
2. `mock-fs` is probably going to be super helpful here
3. Doing object hashing to compare against NodeCache things will help
4. We want to upgrade the core libs to es6 syntax as part of this. The styling/standards here is not clear yet but my recommendation is to write the tests for es5, get them all to pass and then try to move to es6

Let me know what you guys think!

**Comment by dustinleblanc** [comment]
Looking at this today. @pirog The cache conversion, are you talking about an upgrade operation kind of thing?

**Comment by pirog** [comment]
@dustinleblanc i think we just want to remove:

```js
   if (process.platform === 'win32') {
     key = key.replace(/:/g, '.');
   }
```

in all the funcs and then grep the codebase for any cache key that has a `:`. Windows does not like files with `:` in them. 
Example: https://github.com/lando/lando/blob/master/plugins/lando-recipes/recipes/pantheon/init.js#L14
-> `var tokenCacheKey = 'init.auth.pantheon.tokens';`
