### ISSUE TITLE
Let's finally get a POSTgres DB Import/export rolling!

### ISSUE THREAD

**Issue by pirog** [lando/lando#803]
@serundeputy if we could get this rolling as part of the current `db-import/export` scripts that would be hawt.

**Comment by serundeputy** [comment]
@pirog I've got `db-import` up and running for postgres on branch `803/db-im-ex-pgrs`.

There is a problem with `db-export` with mismatch of the version of `pg_dump` on the `database` server vs. the version on the `appserver`.

Here are the detais:

`database` version of `pg_dump`: pg_dump (PostgreSQL) 10.3 (Debian 10.3-1.pgdg90+1)

```bash
geoff@yep drupal-7.57 exit code: [0] $ lando.dev ssh database
www-data@3dbdd94561ed:/app$ pg_dump --version
pg_dump (PostgreSQL) 10.3 (Debian 10.3-1.pgdg90+1)
www-data@3dbdd94561ed:/app$ exit
exit
```

`appserver` version of `pg_dump`: pg_dump (PostgreSQL) 9.4.15
```bash
geoff@yep drupal-7.57 exit code: [0] $ lando.dev ssh
www-data@334ed6c4ac22:/app$ pg_dump --version
pg_dump (PostgreSQL) 9.4.15
www-data@334ed6c4ac22:/app$ exit
exit
```

What happens in the current state of affairs when you execute `lando db-export`:

```bash
geoff@yep drupal-7.57 exit code: [0] $ lando.dev db-export
pg_dump: server version: 10.3 (Debian 10.3-1.pgdg90+1); pg_dump version: 9.4.15
pg_dump: aborting because of server version mismatch
Failed to create file: drupal7.201803241521911414.gz.
```

Here is the `.lando.yml` file I am testing against:

```yml
name: postgres
recipe: drupal7
config:
  webroot: .
  database: postgres:latest
```

I'm not sure how `pg_dump` gets installed on the `appserver` container ... can you help me reconcile this version difference?

thanks.

**Comment by pirog** [comment]
@serundeputy hmmm interesting. I'm honestly not completely sure how to get around this for now. Are the `db-import/export` command running on the `appserver` instead of the `database`? If so i wonder why we (me?) did that vs running it directly on the target service itself (`database` in this case). Maybe because we could potentially have more than one database? 

I also have thought a little bit more about this generally and i think its actually pretty important we consolidate the `mysql` and now `pgsql` scripts into two single `db-import.sh` and `db-export.sh`. The main rationale around this is since a user could have a whole bunch of `pg` or `mysql` dbs in a single app it FEELS like it would be better if they could just `db-import FILE --host=service` and have it "just work". 

If we merged this in currently we'd have a situation where the recipe db would determine whether `db-import` is `mysql` or `postgres` flavored. Meaning if the recipe was `mysql` and then the user added an additional `postgres` db, then `db-import` would never work for any `postgres` dbs. We could get around this by breaking up `db-import` into separate `mysql-import` and `postgres-import` commands  and adding them in based on a scan of what things are used in the lando file. But i feel like the logic around loading the right one migth be messy, and the UX is less than ideal. 

So i think the following two things are worth trying:

1. Consolidating the four db import scripts we have into two generic `sql-import` and `sql-export` scripts. If we can do this well then it should be the simplest and most complete solution for us to implement and also probably better UX. I'm not sure the best way to test whether a file is `pgsql` or `mysql` flavored but im guessing there must be some sort of validation command or something like `try to import schema for postgres -> fails -> assume mysql` that we can do.
2. Running the scripts against the target DB instead of appserver so we can make sure we dont have any server-client mismatches. We can assume `database` as the default but it might be a little tricky to figure out how to get it to use other services. I can help you there once we get to that point.

**Comment by serundeputy** [comment]
@pirog you are right; having it run against the `database` container allowed it run against `postgres:9.4` and `postgres:latest`.

So the low hanging fruit here is to give the `db-import`, `db-export` functionality to the postgres users with parity to what we have with mysql now.

That would in my guestimation handle 80 to 90% of use cases of current users.

To refactor to accommodate the multiple DB/mysql/postgres combinations will take some time and thought.

**Comment by dustinleblanc** [comment]
My understanding of our import/export magic is weak, but is there a reason we are doing shell scripts rather than doing all the db operations inside Node using a database abstraction layer like http://docs.sequelizejs.com/ ?

**Comment by serundeputy** [comment]
afaik; it is just how it has been since the inception; I'm thinking we could detect what database is selected by the user on the `db-import` or `db-export` command and based on that detect the service container from config; then fire off the appropriate sql, mysql, postgres command we need to do the job on the correct DB.

Academically it makes sense and should be extensible, but haven't been back to it since saturday. Hope to return to it soon.

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/969

Consolidates down to 2 files {`sql-import.sh`, `sql-export.sh`} and adds support for postgres imports and exports.
