### ISSUE TITLE
Troubles Getting WordPress-recipe Site Started

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#818]
Bug Report
==========

OS: MacOSx High Sierra (10.13.3)
Lando: v3.0.0-beta.37 (using version of Docker installed by Lando)

Lando.yml
```
recipe: wordpress
config:
  webroot: .
```
**The Problem**
_I acknowledge that I may not fully understand what the WordPress recipe should do and my expectations might be off here._ 

The docs don't really specify what I'm specifically supposed to do with the WordPress-specific Lando recipe or I simply missed it. I'll detail what steps I took below.

After installing a WordPress using Lando I can't seem to get the site to function properly. I'll get a page 404 error when visiting the site directly. 

**Tell us about the command you were running**

- The command I ran is `lando init` and then I chose `WordPress` from the recipe. Of note, running `lando init wordpress` doesn't seem to do anything different because I still have to choose `WordPress` as I'm prompted for recipes.

- I ran `lando start` after 10min the site started up and gave me my app URLs. When I went to them I would get "Page 404 not found". I looked at the app directory and saw only the lando.yml file.

- I then ran `lando wp core install` but it said 'this does not appear to be a WordPress install.' 

- I then ran `lando wp core download` and that worked.

- Then I ran `lando wp config create` with parameters for db user and db name and pwd. I get an error from that command:
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
At this point, I'm not sure how to proceed.

**Tell us more**
Better documentation is needed for the WordPress recipe tutorial as it's not explicit what should be done to install a WordPress and it really should be explicit as to not only what the steps are but what the WP recipe will actually do. The Pantheon recipe works like a dream.

**Does this bug prevent you from using lando?**
Yes, it does.

**Comment by digisavvy** [comment]
Happy to help with WP specific docs.

**Comment by dustinleblanc** [comment]
Hi @digisavvy is there an existing WP codebase in the folder? Is the wp-config.php filled with database connection details?

**Comment by digisavvy** [comment]
@dustinleblanc - no there wasn't. When I noticed that wp-config didn't exist I tried using wp-cli command to create one.

**Comment by pirog** [comment]
@digisavvy the wordpress recipe is intended to be used on an existing wordpress codebase. It's not going to setup a fresh wordpress install for you. That part is up to you.

`lando init wordpress` is not a command, the only `init` methods we offer are `github` and `pantheon`. 

I'd check out these docs on the basics of initializing a site for use with lando
https://docs.devwithlando.io/started.html
https://docs.devwithlando.io/cli/init.html

I'd recommended downloading wordpress first and then running `lando init` inside of the fresh download.

**Comment by digisavvy** [comment]
Thanks for the reply @pirog - Obviously, I have some things I don't understand here and I think it represents an opportunity to improve the documentation there because, to me, it's not clear what is supposed to happen. And I totally get that there are other folks who may not stumble on this like I have. I'm happy to contribute to the documentation and would like to know how.

Thanks again.

**Comment by digisavvy** [comment]
I see how to contribute to the docs now. =)

Thanks for all the great work here. Hope I can help and contribute also.

**Comment by faahim** [comment]
I agree that the doc is not clear. Currently struggling to get a wp site running and I have no idea what to do!

**Comment by digisavvy** [comment]
Yeah, the docs could use some live there. But here's what I recommend.

Type the following commands
1. Lando init and choose WordPress as a recipe.
2. Lando start
3. Lando wp core download
4. Then visit the site url and go through the install steps.

**Comment by d3vit** [comment]
That doesn't appear to work, though?

`lando wp
/bin/sh: 1: wp: not found`

Anyone else getting that issue?
