### ISSUE TITLE
Support: how to alter the webserver read path to some native path?

### ISSUE THREAD

**Issue by hkirsman** [lando/lando#830]
This is more of a support request. I wanted to try out native speeds of Lando by trying to read from native file system. For this I tried multiple things but in vain.

1. I tried unmount /app folder, create another mount and rsync to /app folder. This seems to fail as you need to run docker with privileged option
2. Also tried to change the webroot with webroot but I think it doesn't allow to break out of /app folder

All in all I tried to sync files with normal Lando functionality and then rsync them from the mount to some native folder.

Any ideas?

**Comment by pirog** [comment]
Youd have to install from source and change the source so that this doesnt happen
