### ISSUE TITLE
lando pull is not working

### ISSUE THREAD

**Issue by dealancer** [lando/lando#835]
Bug Report
==========

What is your lando version and operating system?

*Lando v3.0.0-beta.37, MacOS 10.13.3*

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```
name: plum-head
recipe: drupal8
config:
  webroot: .
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

```
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

**Tell us about the command you were running**

```
lando pull
```

**Tell us about the error you got**

```
Unknown argument: pull
```

**Tell us generally about your bug**

I was trying to pull DB and files from Pantheon.

**Comment by pirog** [comment]
@dealancer `lando pull` is only available for the `pantheon` recipe. You are using the `drupal8` recipe.
