### ISSUE TITLE
Can not make Pantheon site work locally

### ISSUE THREAD

**Issue by dealancer** [lando/lando#837]
Bug Report
==========

**Tell us about your setup**

Lando v3.0.0-beta.37, MacOS 10.13.3

**Tell us about your `.lando.yml`**

```
name: plum-head
recipe: pantheon
config:
  framework: drupal8
  site: plum-head
  id: c8da5694-b640-4113-bc9b-30f3f3a857cd
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

```
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
~                   
```

**Tell us about the command you were running**

I was running `init` command, then `pull` command. Everything worked as expected.

**Tell us about the error you got**

However, when I visit `http://localhost:32837/` I am seeing the following message

```

  | Connection failed: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
  | Notice: Undefined variable: dbh in /srv/includes/prepend.php on line 128
  |  
  | Call Stack:
  | 0.0008     372328   1. {main}() /srv/includes/prepend.php:0
  |  
  |  
  | Fatal error: Uncaught Error: Call to a member function exec() on null in /srv/includes/prepend.php on line 128
  |  
  | Error: Call to a member function exec() on null in /srv/includes/prepend.php on line 128
  |  
  | Call Stack:
  | 0.0008     372328   1. {main}() /srv/includes/prepend.php:0


```

**Tell us generally about your bug**

Was not able to get Drupal working.

**Tell us more**

Not sure what else needs to be done to sync site from Pantheon.

**Comment by pirog** [comment]
@dealancer check out https://docs.devwithlando.io/tutorials/pantheon.html#getting-started. It looks like you might be missing the important `lando start` step

```bash
# Grab my site from pantheon
lando init pantheon
# Start my site
lando start
# Pull my database and files
lando pull
```

I just pulled down a vanilla D8 site with the above and its running as expected. We've also got over 2,000 people using Pantheon D8 sites so i **highly suspect** this is not on the lando end but you never know.

@dustinleblanc any thoughts here?

**Comment by dealancer** [comment]
@pirog thanks for your reply.

I think that these steps should be the first thing a user sees on that documentation page. However I was doing in accord with this steps, I still was not able to get it work properly. I noticed that a database container was taking a long time to start and Lando showed a message that it was not healthy.

I tried to reinstall Docker and Lando to the most recent versions and tried to set up D7 Pantheon project and it worked ok. Then I tried to set up D8 Pantheon project and when I was running `lando start` I saw an error message:

```
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Starting plumhead_index_1    ... done
Starting plumhead_cache_1    ... done
Starting plumhead_database_1 ... done
Starting plumhead_appserver_1 ... done
Starting plumhead_nginx_1     ... done
Starting plumhead_edge_1      ... done
Starting plumhead_edge_ssl_1  ... done
error: (HTTP code 500) server error - container 27e47ad7d5ddab6c97de0d4bca81ad86c5deb53784198ef66a27f24fc21afffa is not connected to the network lando_bridge_network Error: (HTTP code 500) server error - container 27e47ad7d5ddab6c97de0d4bca81ad86c5deb53784198ef66a27f24fc21afffa is not connected to the network lando_bridge_network 
    at /snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by alexberendei** [comment]
I get the same lando_bridge_network error message after I've update to v3.0.0-beta.39 from beta.35 ( I've made an lando poweroff before update, but after the update, on "lando list", it returns an empty list and I don't know if they are related with this error)
```
error: (HTTP code 500) server error - container 6ca247b24a8d543b810582ff945f6ebcbe1f6ee2bf8ac0fe202dbbb7d14e2c1b is not connected to the network lando_bridge_network Error: (HTTP code 500) server error - container 6ca247b24a8d543b810582ff945f6ebcbe1f6ee2bf8ac0fe202dbbb7d14e2c1b is not connected to the network lando_bridge_network 
    at /snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by pirog** [comment]
Have you guys run a `docker ps -a` to see what the offending container is? Looks like the container id is `27e47ad7d5ddab6c97de0d4bca81ad86c5deb53784198ef66a27f24fc21afffa` for @dealancer and `6ca247b24a8d543b810582ff945f6ebcbe1f6ee2bf8ac0fe202dbbb7d14e2c1b` for @alexberendei. id be curious to know which container it is since that might help us track things down

**Comment by alexberendei** [comment]
`6ca247b24a8d      solr:5.5       "/lando-entrypoint.s…"   2 weeks ago    Exited (137) 2 weeks ago         demoshop_index_1 `, and it seems that is the only one from demoshop app that appear created 2 weeks ago, the rest of containers are created 33 hours ago, when the update was made. Hope it helps @pirog.

**Comment by pirog** [comment]
You might want to just remove/rebuild that app so that it gets up to date
with our most recent changes.

**Comment by alexberendei** [comment]
Thank you @pirog ! I've deleted that `solr` container and everything is ok now, it seem that `solr` was deleted from `lando.yml` but it managed to remain somehow as an orphan container, even after `lando rebuild`.

**Comment by pirog** [comment]
Oh interesting. Lando "should" try to clean up orphaned containers but i
think there are a few circumstances where they can slip through the cracks.

**Comment by dustinleblanc** [comment]
Closing as this is over six months old and it doesn't look like we have immediate work to do here.
