### ISSUE TITLE
WordPress Recipe Link Issues 404 Error

### ISSUE THREAD

**Issue by digisavvy** [lando/lando#838]
The link to the WordPress recipe is showing a 404 error presently. https://docs.devwithlando.io/recipes/wordpress.md

[Screenshot](https://digisavvycdn.s3.amazonaws.com/Error_404_2018-03-29_23-52-44.png)

**Comment by pirog** [comment]
@digisavvy i dont know where you are getting that link but the correct one is 
https://docs.devwithlando.io/tutorials/wordpress.html

**Comment by OriginalEXE** [comment]
Hello,

That link is referenced on this page:
https://docs.devwithlando.io/tutorials/wordpress.html

at the very top, these words are linked: `configurable recipe`
