### ISSUE TITLE
Provide option to limit container resources

### ISSUE THREAD

**Issue by bruvers** [lando/lando#842]
**Feature Request**

As a Lando user who works with Drupal 8 I want to have an option to limit the resources a container uses to prevent the OS from becoming unresponsive.

On a system running Ubuntu with 8GB RAM the Drupal recipe was using so much resources that the OS "froze" and became completely unresponsive forcing me to do a hard reset. Docker Compose up to version 2 included a `mem_limit` option which limits the amount of RAM a container may use. Lando uses Docker Compose v3 which removed the `mem_limit` option and introduced a `resource` option which only applies to Swarm mode.

There is a [CLI flag to convert Docker Compose v3 files to v2 format where possible](https://github.com/docker/compose/pull/5684). Maybe that might help get that `mem_limit` feature working in Lando?

**Comment by pirog** [comment]
@bruvers wow. i am sorry to hear that! 

that definitely _should_ be sufficient to run a drupal 8 site but your mileage can definitely vary based on the size and scope of the d8 site, the other components of your computer (primarily the processor) and whether you are running any other resource intense things concurrently. 

I usually work on an Ubuntu 17.10 vmware instance with 4GB of ram allocated to it and that usually is sufficient to run at least a vanilla built-from-composer D8 app. 

The bad news here is that its highly unlikely we are going to run lando in swarm mode or support a different docker compose schema. It's even more unlikely we will implement a way to do this in lando space itself (im not even sure HOW we would do that tbh). It would be TOTALLY COOL if we could do all of the above but it would likely be a significant undertaking and generally our line on these sorts of issues are "wait for docker to get better". 

The only *idea* that i have for you is you might be able to tweak your docker engine to boot up with a hard upper bound on resources.
