### ISSUE TITLE
Xargs output using Lando

### ISSUE THREAD

**Issue by generalredneck** [lando/lando#844]
Does anyone have any idea why lando wouldn't produce output when using it in xargs?

I've applied a patch to the hacked module to allow me to do csv format... but we probably do this with any command...

Now I've tried this several ways...  and out of simplicity sake... I'm going to use features because it's the easiest example to set up without having to go thorugh the usecase of patching hacked to give you CSV output and the like...

So lets take this example:

`lando drush fl --format=list --fields=feature --status=enabled | xargs -I {} sh -c 'lando drush fr $1 -y' -- {}`

So what I'm doing there is reverting every enabled feature on the site (I know drush fra will do this... but hear me out)... If I do this using lando, it sits there and process and process (cause I assume it's doing it's thing) but I never get any output... You can even replace `sh -c 'lando drush fr $1 -y' -- {}` with `lando drush status` and you will get jack...

However, If I use straight up drush on a different project... I can do this... and get output... Example

`drush fl --format=list --fields=feature --status=enabled | xargs -I {} sh -c "drush fr $1" -- {}` Works without a hitch... I can even add site aliases in there and all goes well...

I know weird support question, but anyone got ideas? I'm trying to automate reporting from hacked so that future audits will be easier. I will probably end up doing this via PHP... but interested in this.

**Comment by pirog** [comment]
@generalredneck oh this is interesting. My *best guess* here is that the container boundary is the thing that makes this different eg `lando whatever` is running in the container and while its stdout gets piped out to the terminal there is something preventing it from hitting that terminal pipe. One thing you could think about doing (and if it works i'd make it a proper `lando something` tooling command) is trying to wrap the whole thing in `lando ssh SERVICE -c "command"` so something like

```bash
lando ssh appserver -c "drush fl --format=list --fields=feature --status=enabled | xargs -I {} sh -c 'drush fr $1 -y' -- {}"
```

**Comment by pirog** [comment]
@generalredneck if my suggestion works, any ambition to turn this into a "known issue" doc?

**Comment by generalredneck** [comment]
Yeah. I'm out of town today... But I'll try it out when I get back round a computer.

**Comment by generalredneck** [comment]
@pirog so you were close... The challenge here is that running `lando ssh appserver` runs in the home directory which is actually /var/www/html. You have to add the `--root` flag to the command to make it work... so for example ` drush fl --root=/app/web --format=list --fields=feature --status=enabled | xargs -I {} sh -c 'drush fr $1 -y --root=/app/web ' -- {}

**Comment by generalredneck** [comment]
Will reference this issue in the PR for the known issue.
