### ISSUE TITLE
Update to Terminus version v1.8.0

### ISSUE THREAD

**Issue by kclarkson** [lando/lando#848]
I am using lando .39.dmb

A new Terminus version v1.8.0 is available.
You are currently using version v1.7.1. 
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update

Thanks!

**Comment by BrianBenninger** [comment]
I am also experiencing this issue.
v3.0.0-beta.39

**Comment by pirog** [comment]
To be clear, this is not an issue, beta.39 ships with terminus 1.7.1 so this is expected. I'm sure we will update terminus for the next version. In the meantime, if you want to update your terminus then that is something within your own power.

**Comment by pirog** [comment]
@kclarkson the `lando ssh` command is probably what you want and then use whatever commands terminus recommends for the update. 

And the answer to your question is no. It would actually be a really bad idea to create an alias for `lando terminus` or any other `lando` command.

**Comment by benfinklea** [comment]
Just in case someone needs this in the future. To update Terminus:

1. Type: lando ssh and hit enter. Now you have a command prompt in your local environment. (no password required) 
2. THEN, copy/paste the string from Pantheon to update Terminus. (today it was this: curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update) I don't know if that ever changes.

It took a loooong time. I didn't time it, but maybe 10 minutes?

**Comment by kclarkson** [comment]
@benfinklea always nice to see a familiar face ;) Much appreciated man I didn't know how to update it  👍

**Comment by benfinklea** [comment]
Happy to help! Cheers, mate.
