### ISSUE TITLE
Updating lando removes the database

### ISSUE THREAD

**Issue by Kwapi** [lando/lando#859]
I just upgraded from beta 35 to beta 39 and my current projects lost their databases. Is this expected behaviour? If it is, I'd appreciate a mention in the docs or maybe at the installer stage that this would happen.

**Comment by pirog** [comment]
@Kwapi it is not expected behavior. If you upgraded docker and did a factory reset then that will destroy ALL your containers. I'm pretty sure they warn you about this before you do it.
