### ISSUE TITLE
Install Prestissimo by default for all PHP services

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#862]

**Comment by pirog** [comment]
@dustinleblanc MOVED THIS INTO THE CURRENT SPRINT BECAUSE LETS GET IT DONE FOR THE PEOPLEZ

I'm guessing we want to just add this as a `run_internal` step directly on the php service itself?

**Comment by dustinleblanc** [comment]
Yep almost ready to PR it, it sure was a fast change!

**Comment by dustinleblanc** [comment]
Also, in progress was one step ahead of current sprint sir :stuck_out_tongue:

**Comment by tormi** [comment]
Cool! :1st_place_medal:
