### ISSUE TITLE
not running with mysql workbench

### ISSUE THREAD

**Issue by idpokute** [lando/lando#864]
I installed Mysql workbench client, and I reboot my desktop.

When I run `lando start`, it seems it is working. 
but the actual webpage shows 404 error.

I guess it is port conflict issue between Workbench and Lando.

I uninstall workbench, and lando works properly.

**Comment by idpokute** [comment]
@pirog Don't you have any suggestion to solve this issue?

**Comment by pirog** [comment]
Don’t have much control over what workbench does so not really

**Comment by idpokute** [comment]
@pirog 
I can use other sql tools, so it's fine. 
But based on your answer, does it mean Lando doesn't support port changing funcitonality?

**Comment by pirog** [comment]
It supports it extensively and is well documented
