### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by bsnodgrass** [lando/lando#866]
Since updating to v.3.0.0-beta.39 I get this fairly often. It sometimes will correct on refresh. It did not this time however using the Drupal UI /admin/modules/list/confirm
_______________________
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 98583

Varnish cache server
_______________________

Bug Report
==========
Mac OSX 10.12.6

name: shorr
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: shorr
  id: 2a4aba3b-6df8-4887-b8fa-d94e8383f115

**Comment by sryanb** [comment]
Same issue since upgrading yesterday

**Comment by wernerglinka** [comment]
I occurs intermittently when I flush all caches. Back button get's me to the previous page. Flushing again works most of the time.

**Comment by aaron-capellic** [comment]
I'm getting this on beta.40, logged in trying to edit a node, after a few seconds. I don't get the error on Pantheon.

This is all that the logs have running` logs -t -f`

`appserver_1  | 2018-04-26T17:37:37.659231916Z 172.26.0.6 -  26/Apr/2018:17:37:35 +0000 "GET /index.php" 200`

**Comment by aaron-capellic** [comment]
This was happening every time I tried to edit the node. Disabling the pantheon_advanced_page_cache made the problem go away.

**Comment by dustinleblanc** [comment]
@aaron-capellic we were looking at this at Pantheon today. It is probably related to the size of the cache tag headers

**Comment by bsnodgrass** [comment]
I thought I was beyond this one after updating to beta.42, but just got this on a different site.

@dustinleblanc is there any information I should provide re: the size of cache tag headers?

**Comment by jasonbell** [comment]
I started hitting this today on beta39 and comments indicate I won’t have better luck after upgrading. Currently can not access any `/admin` paths.

Is there any sufficient workaround? Can I provide mode log details?

**Comment by bsnodgrass** [comment]
Since upgrading to beta.43 I have only run into this one time, and a refresh corrected it. Other issues have prevented me from a great deal of experience on this version however.

A clear description of how to make it fail or what other things to look at would help confirm if it is still a problem in beta.43

**Comment by p51i** [comment]
I've been having a similar issue and can confirm that disabling pantheon_advanced_page_cache on lando does make the issue go away.

**Comment by Etroid** [comment]
Experiencing the same issue when saving content translation configuration from the UI (/admin/config/regional/content-language). It works when I limit the changes, but larger config updates result in the aforementioned error. The logs are not showing anything out of the ordinary.

**Comment by dustinleblanc** [comment]
This still sounds related to the exact same problem that happens on pantheon with large cache headers. @tinefin researched this a lot at Pantheon, perhaps she has some ideas, not sure.

For Pantheon specific recipes, we're likely to leave the values for max header sizes etc the same as Pantheon, which means Lando is doing it's job to surface issues before they are deployed. What might be a good improvement is better error handling to more explicitly state what has happened. I am not sure if that is possible or not, but would be a nice to have.

For services that aren't vendor specific, the answer is probably to expose the issue in documentation and suggest alterations one can make and document them.

**Comment by square360-douglas** [comment]
In my case I was experiencing timeouts. I was consistently getting this error bang on 60 seconds when loading a heavy admin page. At least as a temporary measure I was able to extend the first_byte_timeout in varnish. 

Get access to the varnish administration:
``` 
lando varnishadm
```
Then set the first timeout. (It appears to be limited to 200)
```
param.set first_byte_timeout 300
```

**Comment by andileco** [comment]
This happens for me on pages that require a lot of memory and sometimes after enabling a module from the UI. Never a problem on Pantheon itself. Would love to figure out how to prevent this from happening. I'm on v3.0.0-beta.47 and this is my only complaint with this version.

**Comment by dustinleblanc** [comment]
@andileco I have discovered that I most often run into this issue when `http.response.debug cacheability_headers` is turned on in my services.yml. It took us a while to find that on our project, but once we disabled it, the error stopped happening to us. This makes sense too, as its one of the few differences you'll have locally vs Pantheon (the services file might be different)

**Comment by andileco** [comment]
Hey Dustin, I always have: http.response.debug_cacheability_headers: false on my sites.
