### ISSUE TITLE
Consider how we can apply mutual TLS between ALL containers (a la Pantheon)

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#867]
**Tell us generally about your bug**

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using lando?

Feature Request
===============

Please explain your request and its importance in the form of a user story.

*Example: As a lando user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how lando can help solve this problem

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by pirog** [comment]
going to close this in favor of an increased-in-scope #446
