### ISSUE TITLE
lando vs docker compose?

### ISSUE THREAD

**Issue by laurencefass** [lando/lando#879]
Feature/Support Request
===============

I've read the documentation and I assume that Lando runs recipes and services as docker containers. What benefits does Lando offer over using docker compose on its own?

thansk

**Comment by laurencefass** [comment]
hi why have you closed without responding? thanks.

**Comment by laurencefass** [comment]
I think this is a documentation issue.  thanks.

**Comment by milkovsky** [comment]
I am also interested. If you google "lando vs docker-compose" this question appears first. I would like to hear comparison from the lando developers as well.

**Comment by laurencefass** [comment]
hi please can you point to the TONS of documentation that answers this? an issue with insufficient documentation remains but you have (too quickly) closed it down as a non-issue... thanks.

**Comment by joshmiller83** [comment]
https://docs.devwithlando.io/config/advanced.html

> Our recipes and services layers are two levels of abstraction on top of the Docker compose v3 file format. Lando will translate the configuration you specify for each recipe and/or service into relevant Docker Compose files and execute them at runtime. This gives you a lot of power to hypertune your services at the Docker Compose level.

In other words, Lando abstracts and simplifies docker compose, but it's still there, below the surface.

**Comment by dustinleblanc** [comment]
Thanks @joshmiller83, that is essentially what Lando is doing. We wrap docker-compose in some additional convenience features. @laurencefass ^ Is a good summary of the value add. We're basically building compose files for you while also:

1. Providing a proxy so you can run multiple apps and not have to manually configure their ports to avoid collusions
2. Provide a way for you to define cli tasks like `lando test` than can map to complex commands inside your containers
3. Let you setup an entire app stack with very few lines of configuration (compared to dc or kube)
4. Let you hack and override most of the above like a boss.

**Comment by laurencefass** [comment]
great stuff thank you.
