### ISSUE TITLE
Pantheon Lando Start/ Pull error - libargon2 no such file or directory

### ISSUE THREAD

**Issue by push10-chris** [lando/lando#884]
lando-v3.0.0-beta.40 version on Macbook Pro macOS High Sierra 10.13.14

`.lando.yml`

```yml
name: push2018
recipe: pantheon
config:
  framework: wordpress
  site: push2018
  id: xxxx
```

(note - I removed the ID from the code above)

```pantheonyml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

Issue:
lando init pantheon - sets up correctly
lando start - throws php error
```
php: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory
error: Looks like one of your build steps failed...
```

If I then try to do Lando Pull I get the same error...

```
Verifying that you are logged in and authenticated by getting info about push2018...
php: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory
```

Verbose Mode:

```bash
lando pull --database=dev --code=dev --files=dev -- -vvvv
debug: Engine is up.
debug: Cached true with key engineup for {"persist":false,"ttl":5}
debug: Engine is up.
debug: Cached true with key engineup for {"persist":false,"ttl":5}
debug: Retrieved from memcache with key engineup
debug: Engine is up.
debug: Cached true with key engineup for {"persist":false,"ttl":5}
debug: Engine is up.
debug: Cached true with key engineup for {"persist":false,"ttl":5}
debug: Retrieved from memcache with key engineup
verbose: Emitting event pre-pull
debug: Event pre-pull has 0 listeners
debug: Retrieved from memcache with key engineup
verbose: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
Verifying that you are logged in and authenticated by getting info about push2018...
php: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory
debug: Logging metrics data {"devMode":false,"nodeVersion":"v8.9.0","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"17.5.0","arch":"x64"},"product":"lando","version":"3.0.0-beta.40","message":"Verifying that you are logged in and authenticated by getting info about push2018...\r\nphp: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory\r\n","action":"error"}
```

I have tried re-installing Docker, Lando. I removed all other applications that could be conflicting, I have tried removing and restarting my Pantheon build and I still get this error.

It only occurs on Lando Start and Lando Pull/ Push. I can do Lando Init fine.

1. Created WP build on Pantheon
2. Created directory locally, entered directory and ran `lando init pantheon`
3. Chose my credentials and the new site
4. It ran correctly so I ran `lando start`
5. Received first error `error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory`
6. Ran `lando pull` and received same error

Any help on this would be greatly appreciated

**Comment by push10-chris** [comment]
PHP info if that helps...
```
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by dustinleblanc** [comment]
This sounds really familiar, but what when exactly I've seen it before I can't remember. @push10-chris does this happen if you start any other type of app? A Vanilla Drupal 7/8 Pantheon site? Wordpress without the Pantheon recipe? Just fishing for variables to tweak hear to see how prevelant the bug is for you.

I see serveral similar reports to random packages on the interwebs, nothing that gives me concrete ideas though. @push10-chris it'd be interesting to see if this happens with beta 39 as well.

Thanks for the report!

**Comment by push10-chris** [comment]
I deployed a Drupal site and it works as normal, would you suggest reverting to beta 39 to try to get WordPress builds working?

**Comment by pirog** [comment]
I'm running WordPress sites on beta.40 so im not sure that is the issue

**Comment by push10-chris** [comment]
yea, I can't seem to get it working with WordPress

I keep running into this error
```
php: error while loading shared libraries: libargon2.so.0: cannot open shared object file: No such file or directory
```

I tried re-installing Lando and Docker completely but still am getting the same error

**Comment by dustinleblanc** [comment]
@push10-chris can you replicate this with a 100% Vanilla brand new Pantheon Wordpress site? I am wondering if the issue has to do with plugins in use on the specific site

**Comment by push10-chris** [comment]
Yep, same problems. The only plugins are the default ones in WP

**Comment by dustinleblanc** [comment]
Hey @push10-chris I just started my wife's WP Pantheon site and I am not seeing any issues:
```
☁  bethanys-art-shop [master] lando start
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Recreating bethanysartshop_index_1    ... done
Recreating bethanysartshop_cache_1    ... done
Recreating bethanysartshop_database_1  ... done
Recreating bethanysartshop_appserver_1 ... done
Recreating bethanysartshop_nginx_1     ... done
Recreating bethanysartshop_edge_1      ... done
Recreating bethanysartshop_edge_ssl_1  ... done
Waiting until edge_ssl service is ready...
Waiting until edge service is ready...
Waiting until nginx service is ready...
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until index service is ready...
Waiting until cache service is ready...
Waiting until edge_ssl service is ready...
Waiting until database service is ready...
Waiting until edge_ssl service is ready...
Waiting until database service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME           bethanysartshop                                          
 LOCATION       /home/dustinleblanc/Sites/bethanys-art-shop              
 SERVICES       appserver, nginx, database, cache, edge_ssl, edge, index 
 NGINX URLS     https://localhost:32771                                  
                http://localhost:32772                                   
 EDGE URLS      http://localhost:32773                                   
                http://bethanysartshop.lndo.site                         
                https://bethanysartshop.lndo.site                        
 EDGE_SSL URLS  https://localhost:32774                                  

```

At this point, this is not reproducable by any members of the Lando dev team. Something must be unusual about your setup, but I can't decide what it is.

I just noticed you show php version as 7.1, which doesn't match your pantheon.yml or the default upstream file on Pantheon: https://github.com/pantheon-systems/WordPress/blob/master/pantheon.upstream.yml#L6

Are you running on a custom upstream?

**Comment by rayskin** [comment]
I had this issue today. Lando rebuild solved my issue. Not sure why.

**Comment by push10-chris** [comment]
The most recent update actually fixed the issue for me

**Comment by scroniser** [comment]
FYI, I also ran into this error, but `lando rebuild` fixed it for me as well.

**Comment by manolobevia** [comment]
It didn't work for me `lando rebuild`. Any other solutions?

**Comment by dustinleblanc** [comment]
Hey @manolobevia! It's been a while, hope you are doing well. I don't think anyone else has come up with any, we closed this as the maintainer team can't reliably reproduce. What verson of Lando are you running? It's possible a destroy and start could help, but bear in mind, that drops your database

**Comment by mehigh** [comment]
Thank you for commenting with the solution @rayskin  . Rebuild solved my issue as well.

**Comment by darko-hrgovic** [comment]
Had this issue today when I changed PHP 7.2 to 5.6 in my .lando.yml and only did a lando restart.

As others have mentioned, lando rebuild does the trick.

Guessing that .so dependency was a php version issue.
