### ISSUE TITLE
Allow specifying a patch version of a docker image in service type

### ISSUE THREAD

**Issue by aleksijohansson** [lando/lando#890]
Specifying the docker image version in the service type in `.lando.yml` allows for python for example to only point versions like `3.6` and not patch versions like `3.6.5`. This makes docker pull the `python:3.6-jessie` tag of the python image. That tag is not a static tag which results different developers having different version of python. I propose the possibility to specify the patch version of the image in the service type in `.lando.yml` to ensure consistent development environments. The worst part of this is that the issue is not easy to detect because there is no clear indication of the differences in environments. Another option would be to at least provide the option to easily pull latest version of the dynamic `python:3.6-jessie` tag, but I would prefer the option to define patch versions instead. Pulling the latest version of an image could be an additional flag to the rebuild command or a completely separate command. It is possible to manually pull the new version of the docker image with docker, but that leaves the existing image (which is probably in use) without a tag and cleaning up images without tags is maybe exactly the kind of complexity we don't want to have with the otherwise so easy to use tool Lando so implementing a way to pull newer versions of images might be not such a good idea which gets us back to the preferred possibility to specify the patch version in the service type.

Here is an example of the proposed syntax:

```bash
name: python
services:
  appserver:
    type: python:3.6.5
```

**Comment by aleksijohansson** [comment]
@dustinleblanc Thanks for reply. Using a service override is actually a viable option for me. The only downside for someone could be the added complexity in the `.lando.yml` and the initial confusion when first switching to Lando from using plaing docker for example.

You're completely right, I meant patch release. I'll update the description of the issue accordingly.

**Comment by pirog** [comment]
ok @aleksijohansson @dustinleblanc this should be fixed and ive documented it (which links to a working example) over here
https://docs.devwithlando.io/services/php.html#using-a-dockerfile

**Comment by pirog** [comment]
whoops, posted this on the wrong issue!

**Comment by pirog** [comment]
@aleksijohansson ok ive added docs on how to do this on every service page as is applicable. here is an example for nginx
https://docs.devwithlando.io/services/nginx.html

**Comment by aleksijohansson** [comment]
@pirog Nginx example looks good! I don’t know if you meant to add the same nginx example to all service pages since now for example on the python page you also have the nginx example? I does the job of explaining how to use patch versions yes, but might be confusing.

**Comment by pirog** [comment]
yeah i understand that but maintaining a separate example for each service
is difficult. Feel free to submit a PR that provides more contextually
relevant examples if you want!

On Thu, May 17, 2018 at 12:48 AM, Aleksi Johansson <notifications@github.com
