### ISSUE TITLE
lando init non-interactive breaks if you have a space in 'name'

### ISSUE THREAD

**Issue by geerlingguy** [lando/lando#891]
Bug Report
==========

Lando v3.0.0-beta40 on macOS High Sierra

When I run the command:

```
lando init --recipe drupal8 --webroot "." --name "Drupal Lando" --yes
```

It creates a `.lando.yml` file with the following contents:

```yaml
name: Drupal Lando
recipe: drupal8
config:
  webroot: .
```

When I run `lando start`, I get the following:

```
$ lando start -vvvv
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating drupallando_appserver_1 ... done
Creating drupallando_database_1  ... done
error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME      drupal lando
 LOCATION  /Users/jgeerling/Dropbox/Development/GitHub/drupal-the-fastest/methods/drupal-lando
 SERVICES  appserver, database
```

If I use the interactive `lando init`, and fill in the name "Drupal Lando", I notice the generated YAML file has `name: drupal-lando`.

So it looks like if we pass in a name that's not machine-name formatted non-interactively... it should be reformatted to a machine name before writing out to the Lando YAML file.

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/892
