### ISSUE TITLE
lando start from Pantheon dev site errors with "error: (HTTP code 500) server error - container is not connected to the network lando_bridge_network"

### ISSUE THREAD

**Issue by JimGagnon** [lando/lando#894]
Running lando start dies with the error:
  error: (HTTP code 500) server error - container 8d72d10e3aaace2936398c2ff32b6f03e7a89368484af3290b7d17e74305ab9c is not connected to the network lando_bridge_network

Very easy to recreate on my machine by entering "lando init; lando start"

Here's the output from docker inspect 8d72d10e3aaace2936398c2ff32b6f03e7a89368484af3290b7d17e74305ab9c :
[badcontainer.txt](https://github.com/lando/lando/files/1905218/badcontainer.txt)

Bug Report
==========

Mac OS X 10.12.6, Lando v3.0.0-beta.40

.lando.yml:

name: foresightst
recipe: pantheon
config:
  framework: drupal8
  site: foresightst
  id: 69177550-246e-4221-9f9e-478c9c68f29d

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

Fresh install today of Lando and its Docker. Bringing in a dev only site from Pantheon. Ran "lando init pantheon" first, and had to create a "/certs" directory to allow it to complete without error. Upon running "lando start" it seems to proceed normally until I hit:

Creating foresightst_edge_ssl_1    ... done
error: (HTTP code 500) server error - container 59436cc451a53c9f6af275850daf936771ba00e064046c10914512f995e85b12 is not connected to the network lando_bridge_network

Paste in a series of commands that caused the bug.

lando init pantheon
lando start

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

Running in verbose mode reveals very little more:

[Redwood:ForesightST/foresightst.com/fslando] jimg% lando start -vvvv
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
foresightst_index_1 is up-to-date
foresightst_cache_1 is up-to-date
foresightst_database_1 is up-to-date
foresightst_appserver_1 is up-to-date
Starting foresightst_nginx_1 ... done
Starting foresightst_edge_1  ... done
Starting foresightst_edge_ssl_1 ... done
error: (HTTP code 500) server error - container 59436cc451a53c9f6af275850daf936771ba00e064046c10914512f995e85b12 is not connected to the network lando_bridge_network

Attempting to diagnose the problem, I tried to bring up an empty instance by executing:
  lando init
  lando start

and got the same error.

**Tell us generally about your bug**

Attempt to migrate a Pantheon test site resulted in error: (HTTP code 500) server error - container is not connected to the network lando_bridge_network

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

fresh install
lando init pantheon
sudo mkdir /certs
sudo chmod g+x /certs
lando init pantheon
lando start

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Verbose mode could have told me more. Also, some idea of what Lando is looking for in ssl and certs.

Does this bug prevent you from using lando? Yes

**Comment by dustinleblanc** [comment]
The 'certs' error makes this sound like it's related to our SSL upgrade @pirog

**Comment by JimGagnon** [comment]
Any way to get around it or downgrade? If downgrade, which old version is the most stable?

**Comment by kcaulkins** [comment]
This is happening to me as well after a fresh install of Lando and Docker. Not using Pantheon.

**Comment by alexberendei** [comment]
That happened to me while an container was not cleaned by lando after the update. That is the link to my issue: https://github.com/lando/lando/issues/837 maybe it helps. 
Do an `docker ps` to see what 59436cc451a53c9f6af275850daf936771ba00e064046c10914512f995e85b12 container holds, in my case was an `solr` and after deleted him, lando started normal.

**Comment by tormi** [comment]
Same error here, after hitting Crtl-C in the middle of the unsuccessful lando start process. 

Lando b40, Ubuntu 16.04.

**Comment by tormi** [comment]
Duplicate: https://github.com/lando/lando/issues/893

**Comment by alexberendei** [comment]
Is strange that the error appear on an fresh install, but sound very much with an issue i had here: https://github.com/lando/lando/issues/837 
If you do an `docker ps -a`, what container 59436cc451a53c9f6af275850daf936771ba00e064046c10914512f995e85b12 contain ? 
In my case was an orphaned `solr` container, and after I deleted him, all went to normal.

**Comment by tormi** [comment]
> In my case was an orphaned solr container

Might be my case as well, will check. I experimented with elasticsearch while problem occurred.

**Comment by dustinleblanc** [comment]
@JimGagnon beta 39 is the current 'stable' release, by chance do you have an orphaned SOLR container like the others?

**Comment by JimGagnon** [comment]
Just downgraded to beta 39, but kept the up-to-date version of Docker. No orphaned SOLR container, but now I get a stack crawl:

[Redwood:ForesightST/foresightst.com/fslando] jimg% lando init
? What recipe do you want to use? drupal8
? Where is your webroot relative to the init destination? .
? What do you want to call this app? foresightst

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run
`lando start` to get rolling.

Check the LOCATION printed below if you are unsure where to go.

Here are some vitals:

 NAME      foresightst
 LOCATION  /Users/jimg/Work/ForesightST/foresightst.com/fslando
 RECIPE    drupal8
 DOCS      https://docs.devwithlando.io/tutorials/drupal8.html
[Redwood:ForesightST/foresightst.com/fslando] jimg% lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
foresightst_database_1 is up-to-date
Starting foresightst_appserver_1 ... done
error: (HTTP code 500) server error - container 7f61e1f88394b73768fc8b6823549ddd735fdf0aebac4a02c16f6b830f0feb28 is not connected to the network lando_bridge_network Error: (HTTP code 500) server error - container 7f61e1f88394b73768fc8b6823549ddd735fdf0aebac4a02c16f6b830f0feb28 is not connected to the network lando_bridge_network
    at /snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[Redwood:ForesightST/foresightst.com/fslando] jimg% docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                        PORTS                                                                    NAMES
8d9cfe6637f8        devwithlando/php:7.1-apache          "/lando-entrypoint.sâ¦"   27 minutes ago      Exited (127) 18 minutes ago                                                                            foresightst_appserver_1
868f3f5725fe        mysql:latest                         "/lando-entrypoint.sâ¦"   27 minutes ago      Up 27 minutes (healthy)       0.0.0.0:32768->3306/tcp                                                  foresightst_database_1
8e9070924174        traefik:1.3-alpine                   "/lando-entrypoint.sâ¦"   27 minutes ago      Up 27 minutes                 0.0.0.0:8000->80/tcp, 0.0.0.0:444->443/tcp, 0.0.0.0:58086->8080/tcp      landoproxyhyperion5000gandalfedition_proxy_1
f46a87ac7a7a        nginx:latest                         "/lando-entrypoint.sâ¦"   3 days ago          Exited (1) 3 days ago                                                                                  foresightst_edge_ssl_1
7f61e1f88394        nginx:1.8                            "/lando-entrypoint.sâ¦"   3 days ago          Exited (1) 3 days ago                                                                                  foresightst_nginx_1
17c68ef06b32        redis:2.8                            "/lando-entrypoint.sâ¦"   3 days ago          Exited (255) 31 minutes ago   0.0.0.0:32810->6379/tcp                                                  foresightst_cache_1
11dfb4ac0ee9        devwithlando/pantheon-index:3.6-3    "/lando-entrypoint.sâ¦"   3 days ago          Exited (255) 31 minutes ago   0.0.0.0:32809->449/tcp                                                   foresightst_index_1
9a0a49c1eb4c        devwithlando/util:stable             "tail -f /dev/null"      4 days ago          Created                                                                                                landocasetupkenobi38ahsoka_ca_1
5080c19f550b        kalabox/proxy:stable                 "/init"                  5 days ago          Up 31 minutes                 127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:8160->8160/tcp   kalabox_proxy_1
6937a7e73a46        drush/drush:8-php5                   "usermap"                5 days ago          Exited (1) 4 days ago                                                                                  foresightst_drush_1
7f8233b98ade        kalabox/terminus:0.13.4              "usermap"                5 days ago          Exited (1) 4 days ago                                                                                  foresightst_terminus_1
f800ed96b15e        kalabox/cli:stable                   "usermap true"           5 days ago          Exited (1) 4 days ago                                                                                  foresightst_cli_1
df57b0c2b273        redis:2.8                            "true"                   5 days ago          Exited (0) 4 days ago                                                                                  foresightst_redis-cli_1
783ca2bcb2cf        kalabox/pantheon-solr:hyperion5000   "/bin/bash /start.sh"    5 days ago          Exited (137) 4 days ago                                                                                foresightst_solr_1
fcc29fe7511a        mariadb:10.0                         "docker-entrypoint.sâ¦"   5 days ago          Exited (0) 4 days ago                                                                                  foresightst_db_1
19d930544e19        nginx:1.8.1                          "/src/config/scriptsâ¦"   5 days ago          Exited (137) 4 days ago                                                                                foresightst_web_1
03d4b4ca213a        redis:2.8                            "docker-entrypoint.sâ¦"   5 days ago          Exited (0) 4 days ago                                                                                  foresightst_redis_1
d1451cdb2e88        busybox                              "sh"                     5 days ago          Exited (0) 4 days ago                                                                                  foresightst_data_1

**Comment by tormi** [comment]
@JimGagnon , delete the broken container with command `docker rm 7f61e1f88394b73768fc8b6823549ddd735fdf0aebac4a02c16f6b830f0feb28` and try `lando start` or `lando rebuild` again.

**Comment by JimGagnon** [comment]
Tried that. Lando rebuild will simply give the same error after container deletion. Lando start offers a different but no less useful output:
[Redwood:ForesightST/foresightst.com/fslando] jimg% docker rm 11dfb4ac0ee93e9904212931eccd9fad8fbc769a5e3e479a3b2f09e02351c615
11dfb4ac0ee93e9904212931eccd9fad8fbc769a5e3e479a3b2f09e02351c615
[Redwood:ForesightST/foresightst.com/fslando] jimg% lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
foresightst_database_1 is up-to-date
foresightst_appserver_1 is up-to-date
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
...ad infinitum...
^C

**Comment by tormi** [comment]
Then there might be something wrong with your .lando.yml. Could you add it here?

**Comment by JimGagnon** [comment]
My .lando.yml:
name: foresightst
recipe: drupal8
config:
  webroot: .

**Comment by dustinleblanc** [comment]
I was running into al sorts of issues like this when I tried running Lando on an unsupported Docker version on Ubuntu specifically. Was everyone here affected by this on Ubuntu and if so, what version of docker were you on?

**Comment by tormi** [comment]
Docker 18.03.0-ce, Ubuntu 16.04.4.

**Comment by persianturtle** [comment]
I'm running into this issue using `Docker for Mac Version 18.03.0-ce-mac60 (23751)` running `macOS 10.12.6`.

```
lando start
Pulling proxy (traefik:1.3-alpine)...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Pulling cache (redis:2.8)...
Pulling nginx (nginx:1.8)...
Pulling edge (eeacms/varnish:4.1-3.0)...
Pulling edge_ssl (nginx:latest)...
Creating kineret_database_1 ... done
Creating kineret_cache_1     ... done
Creating kineret_index_1    ... done
Creating kineret_appserver_1 ... done
Creating kineret_nginx_1     ... done
Creating kineret_edge_1      ... done
Creating kineret_edge_ssl_1  ... done
error: (HTTP code 500) server error - container 60629d2813bb910b5596b875267109346ffc6f9042f848dae54cacca948d0542 is not connected to the network lando_bridge_network Error: (HTTP code 500) server error - container 60629d2813bb910b5596b875267109346ffc6f9042f848dae54cacca948d0542 is not connected to the network lando_bridge_network 
    at /snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/snapshot/lando/build/cli/node_modules/docker-modem/lib/modem.js:229:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
➜  kineret-ll git:(master) ✗ docker rm 60629d2813bb910b5596b875267109346ffc6f9042f848dae54cacca948d0542
60629d2813bb910b5596b875267109346ffc6f9042f848dae54cacca948d0542
➜  kineret-ll git:(master) ✗ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
kineret_cache_1 is up-to-date
kineret_index_1 is up-to-date
kineret_appserver_1 is up-to-date
kineret_nginx_1 is up-to-date
kineret_edge_1 is up-to-date
kineret_edge_ssl_1 is up-to-date
Creating kineret_database_1 ... done
Waiting until database service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge service is ready...
Waiting until nginx service is ready...
Waiting until appserver service is ready...
Waiting until index service is ready...
Waiting until cache service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
^C
```

**Comment by dustinleblanc** [comment]
@persianturtle beta 39? WOw, I just had a user fix this by downgrading to beta 39... I am so confused...

**Comment by cfrench1967** [comment]
I was having the same problem

“error: (HTTP code 500) server error - container fb0e6f484e01114bdc593885dc7f2f2473debffe40c114338121e14c0cf1dccc is not connected to the network lando_bridge_network ”

And by downgrading to v3.0.0-beta39 it fixed the problem!

**Comment by kcaulkins** [comment]
Just want to confirm here that removing the offending container worked for me. Using beta 40.

**Comment by persianturtle** [comment]
@dustinleblanc After resetting Docker to factory settings, everything worked for me.

**Comment by JimGagnon** [comment]
Yes, resetting Docker to factory settings clears the error. Thanks all.

**Comment by sk33lz** [comment]
I did some digging into this, as it was completely confusing me. It turns out that the mysql:latest docker tag was just switched to 8.x yesterday, so that appears to definitely be the cause for the mysql container issue for me. See https://github.com/docker-library/mysql/commit/ff627942605ce08a32fa527993337df0e9856760

**Comment by tormi** [comment]
Yeah, this seems like duplicate of https://github.com/lando/lando/issues/908 (or vice versa).

**Comment by ccjjmartin** [comment]
I was getting this error a lot and a simple `lando rebuild -y` fixes it every time for me (I am running beta39 don't know if this is required).  I am pretty sure it has something to do with networks being lost during a docker version upgrade.  I was also able to fix this on non lando containers with the `docker network connect` command: https://docs.docker.com/engine/reference/commandline/network_connect/

**Comment by rg-srini** [comment]
Im stuck with v3.0.0-beta.47 on Ubuntu 18. Not able to initiate a basic laravel app with elasticsearch due to this issue.

After manually attaching the container to the network, the error has gone. Now I face different issue #817 
docker network connect myapp_default myapp_search_1

**Comment by ccjjmartin** [comment]
This *!&#($& (#&$(@*#* bug.  Hit it again but rebuild wasn't fixing it.  Found that my docker disk space was full and that increasing the amount of disk space fix it.  I think that is why it gives symptoms of different issues (depends on when the disk gets full).  For those using Docker for Mac you can go into your settings and increase the disk space (see screenshot below).

<img width="500" alt="screen shot 2018-07-27 at 4 49 49 pm" src="https://user-images.githubusercontent.com/12279982/43347934-22acbee8-91bd-11e8-8a72-162f378117e6.png">

I wondered why the lando image just started failing in the middle of working on it.

**Comment by jordangidoin** [comment]
I have the same error in linux install.
I resole by change the vm.max_map_count value une ce linux /etc/sysctl.conf file
explain here : https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

**Comment by GhostInTheMachines** [comment]
Rebuild stops the “error: (HTTP code 500) server error - but lando rebuild -vvvv still seems to fail with the following error on lando beta v47
```
± |master U:2 ?:3 ✗| → lando rebuild -vvvv
? Are you sure you want to rebuild? Yes
Killing express_appserver_cli_1 ... done
Removing express_appserver_1     ... done
Removing express_appserver_cli_1 ... done
Pulling appserver_cli (node:6.10)...
Pulling appserver (node:6.10)...
appserver_cli uses an image, skipping
appserver uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating express_appserver_1     ... done
Creating express_appserver_cli_1 ... done
Waiting until appserver service is ready...
Waiting until appserver_cli service is ready...
### error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```
looking back through the steps, I can not really see where the build steps fail

**Comment by dustinleblanc** [comment]
@GhostInTheMachines that error is a general indication that some build step definied in your `.lando.yml` has failed. I'd suggest commenting out any custom stuff until it starts working and then add stuff back in and investigate each step.

**Comment by jessCmi** [comment]
I have started getting this error with a new Pantheon wordpress setup. Nothing I have tried has worked so far

Things I tried:
- Increasing the disk space in Docker
- Uninstalled and reinstalled Lando and Docker
    - Deleted the Lando config.

The container that is showing as not connected to the `lando_bridge_network` is always the database container, so I'm not sure what could be causing this. Any help is appreciated. Using the latest version of Lando, which I just reinstalled today.

**Comment by doostinharrell** [comment]
My issue was the same as ccjjmartin's and updating Docker disk space resolved the issue.  I had been restarting my Mac to get containers back online however this just worked for a day or so.  Glad to know the source of the issue.  Better error handling would be helpful.

https://github.com/lando/lando/issues/894#issuecomment-408547554

**Comment by ezenko** [comment]
https://github.com/lando/lando/issues/894#issuecomment-409216307
For me on Debian 9 the solution about changing vm.max_map_count worked!
Thanks @jordangidoin

**Comment by gwixted** [comment]
Increasing the memory as recommended by ccjjmartin worked for me.

**Comment by paulcham** [comment]
Resetting Docker fixed this for me.

**Comment by flyke** [comment]
Simply restarting Docker and then `lando rebuild` did the trick for me when I got this error just now

**Comment by fcdeveloper** [comment]
Hi I am trying to create a unit test simple as:
`$response = $this->get('/login');
$response->assertSuccessful();
$response->assertViewIs('auth.login');`

but always fail with this message: 
`1) Tests\Feature\Auth\LoginTest::test_user_can_view_a_login_form
Response status code [500] is not a successful status code.
Failed asserting that false is true.`

Any idea ASAP could help.
Thank You!

**Comment by vadiminsk** [comment]
after `lando start` run 
`composer install `
or (if needed) `lando db-import `

**Comment by silverham** [comment]
I would like to mention that you will also get this error if your docker start file has exited but a subprocess is still running.
example
```bash
sleep infinity &
exit
```

**Comment by f-liva** [comment]
This error often hides a startup script crashing inside the container — once a run-parts (or any pre-Apache/PHP hook) exits non-zero, Lando never attaches the container to `lando_bridge_network` and you get the 500 you see.

In my case on Lando 3.x the culprit was `~/.lando/certs/lndo.site.srl` — the OpenSSL serial file used to sign per-service certs (`laravel.ima.crt`, `appserver.xxx.crt`, …). The file had been truncated to 41 bytes of NUL characters (possibly a bad shutdown / filesystem issue on WSL2 in my case, but anything that corrupts the serial will do it). `openssl x509 -CA ... -CAserial` blows up with:

```
Unable to load number from /lando/certs/lndo.site.srl
error:06800096:asn1 encoding routines:a2i_ASN1_INTEGER:short line
run-parts: /scripts/000-add-cert exited with return code 1
```

The container dies before networking is wired up, `lando start`/`lando rebuild` fails with `(HTTP code 500) server error - container <id> is not connected to the network lando_bridge_network`, and `docker logs <appserver>` shows the serial parsing error above.

### Fix without reinstalling Lando

```bash
# Stop Lando
lando poweroff

# Delete the corrupted serial file — OpenSSL will recreate it on next start
# thanks to `-CAcreateserial` in the cert generation script
rm ~/.lando/certs/lndo.site.srl

# (On WSL2 also make sure ssh-agent is running if you bind-mount keys)
eval $(ssh-agent); ssh-add

lando start
```

No need to `docker system prune`, wipe `~/.lando/`, or reinstall. After the file is gone, the `000-add-cert` script regenerates a valid serial and all services come up and join `lando_bridge_network` normally.

### How to confirm it's this specific cause

Before the fix, run:

```bash
# Find which container failed and look at its logs
docker ps -a --filter "status=exited" --format '{{.ID}} {{.Names}}' | head
docker logs <id> 2>&1 | grep -E "000-add-cert|CAserial|a2i_ASN1_INTEGER"

# Inspect the serial file — if it's not a plain hex number it's corrupt
od -c ~/.lando/certs/lndo.site.srl
```

If you see the ASN1 error above, the fix is the single `rm` on the `.srl`.

If `docker logs` shows a *different* error right before `run-parts ... exited with return code 1`, chances are it's still a failing pre-startup hook — the `lando_bridge_network` message is a symptom, the real log is always the one above it.
