### ISSUE TITLE
Pantheon + Drupal 7: Can't Get Solr to Work

### ISSUE THREAD

**Issue by chrisroane** [lando/lando#899]
Lando: v3.0.0-beta.39
Docker: Version 18.03.0-ce-mac60 (23751)

I can't seem to get solr to work locally on a Pantheon Drupal 7 site. I think it is because it isn't reading the right solr schema file.

When I go to: admin/config/search/pantheon . I see that is is loading the "example" schema, which is different from what is shows on the live site:
https://www.dropbox.com/s/y2i02l22v0zgvgm/Screenshot%202018-04-16%2009.05.54.png?dl=0

This is what the server view tab looks like:
https://www.dropbox.com/s/ie7yezwpoxp4h25/Screenshot%202018-04-16%2009.06.18.png?dl=0

I've tried re-submitting the 3.x schema file via the admin, but that doesn't work. In the logs, when I try to index content locally, this is the errors I see:
https://www.dropbox.com/s/b02di3xfs1c7qz2/Screenshot%202018-04-16%2009.08.14.png?dl=0
https://www.dropbox.com/s/u1jygttp9lbcug4/Screenshot%202018-04-16%2009.08.30.png?dl=0

Any tips in how I can get this working locally? Thanks.

**Comment by chrisroane** [comment]
FYI, I try running `lando rebuild` and it still doesn't work.

**Comment by jproctor** [comment]
> You are using an incompatible schema.xml configuration file. Please follow the instructions in the INSTALL.txt file for setting up Solr. 

I'm also seeing this with beta.42, Drupal 8, pantheon recipe.

[This issue at d.o](https://www.drupal.org/project/search_api_solr/issues/2927807) includes a patch that removes two lines from search_api_solr/solr-conf/4.x/schema.xml (and also other files), which has been merged into 8.x-1.x-dev but not released yet. 

Applying that patch made the error go away. I'm not sure I ever had it working locally so I can't say for certain that fixed it, but at least it's not complaining.

**Comment by ccjjmartin** [comment]
@chrisroane Looks like you are using a custom schema.xml file (sites/all/features) this is probably ok but it might not be for the right solr version.  I would recommend doing a `lando info` to see what solr version is running on lando and then looking at the schema file or tracking down where it originated to see what version it was built for.

You may have already seen this page but here it is for further info: https://docs.devwithlando.io/services/solr.html

**Comment by chrisroane** [comment]
@ccjjmartin Thanks for the tips. I'll look into it. Maybe it is using some custom schema file that was built for drupalvm or something.

**Comment by jproctor** [comment]
Also potentially relevant: #656 .

In D8, anyway, the schema gets sent to the Solr container by the Search API Pantheon module when the Solr server is defined. And apparently it is not stored in that container in a way that can be reliably reconstituted. 

The proposed remedy there, `lando rebuild`, consistently does _not_ fix the problem for me. But I did find a workaround: when I want to do local Solr development, I can delete my index and server through the Drupal UI, clear cache, then recreate them. It's tedious, but it might work, and could be scripted (especially if the Search API config can be featurized in D7).

**Comment by chrisroane** [comment]
I was able to play with this more and I got it working. Below is what I had to do:

1. I needed to repost the schema file. I selected `sites/all/modules/contrib/search_api_solr/solr-conf/3.x/schema.xml` from `/admin/config/search/pantheon/schema` and hit submit. At `/admin/config/search/search_api/server/medstat_pantheon_solr` it should look something like this: https://www.dropbox.com/s/jy301m3yaamvns6/Screenshot%202018-05-03%2014.26.29.png?dl=0 . What is a little odd is that the solr core name says `index`, even though lando says the core is `index1`. But that doesn't seem to cause an issue.
2. You have to re-index each index from `/admin/config/search/search_api`. Even if it says drupal has everything indexed, the lando server probably doesn't have that data and you will have to clear the data and re-index everything.

I thought the solr settings we were using on the live site where solr is working wouldn't work in lando, but it looks like it does. The host and port doesn't match what lando info returns, but it works. Maybe the docker containers are setup for the pantheon settings to work?

For anyone else having this problem, follow the steps above and it "should" work.

> Note: I'm not 100% sure this will work until the local site 100% finishes re-indexing the site. I'll post here when it is done and after I confirm it is working. But from what I can tell, things look very promising.

**Comment by chrisroane** [comment]
FYI, I confirmed search works once data was been re-index. So the above steps worked. Closing this.
