### ISSUE TITLE
Fix generation of images styles on nginx for Drupal 7 & 8 when language code in URL.

### ISSUE THREAD

**Issue by AlEltono** [lando/lando#914]
Fix generation of images styles on nginx for Drupal 7 & 8 when language code in URL.
===============

Hello,
the image styles are not properly generated on Drupal 7 (probably 8 too) when using nginx and translations, when the language code is in the URL.

**Please provide some detail on how lando can help solve this problem :**

I changed the regex in the nginx location rule for drupal7 recipe

```diff
diff --git a/examples/drupal7/config/nginx/drupal.conf b/examples/drupal7/config/nginx/drupal.conf
index 623a9c2..1ae8776 100644
--- a/examples/drupal7/config/nginx/drupal.conf
+++ b/examples/drupal7/config/nginx/drupal.conf
@@ -98,7 +98,7 @@ server {
 
   # Fighting with Styles? This little gem is amazing.
   # location ~ ^/sites/.*/files/imagecache/ { # For Drupal <= 6
-  location ~ ^/sites/.*/files/styles/ { # For Drupal >= 7
+  location ~ ^(/[a-z\-]+)?/sites/.*/files/styles/ { # For Drupal >= 7
       try_files $uri @rewrite;
   }
```

Images are now well generated :)

Kind regards and many thanks for the crazy work  !

**Comment by dustinleblanc** [comment]
@AlEltono sweet! Thanks for that @pirog would you like to see this as a PR to make it official? I can't imagine its a problem to do so, but this is also the kind of thing I don't want to pretend to be an expert at

**Comment by pirog** [comment]
@AlEltono very nice catch here! Seems innocent enough to add in!
