### ISSUE TITLE
Pantheon init fails with error: Cannot set property ‘id’ 

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#922]
It looks like the platform sites API changed, so our API client needs to follow. PR to come

**Comment by sturtus** [comment]
I came here to report the same issue. Thank you for being attentive to the issue.

**Comment by bsnodgrass** [comment]
Me too, tried to init on a new clone from Pantheon

**Comment by windycitymoon** [comment]
treid from v3.0.0-beta.40 on Mac. Same issue.
