### ISSUE TITLE
Beta42 fails to list sites for Pantheon account with "lando init pantheon"

### ISSUE THREAD

**Issue by bmcclure** [lando/lando#934]
I had one existing machine token authorized, which continues to work. However, after upgrading Lando I tried to add another known-working machine token for a different Pantheon account, and it won't show the sites I have access to on that account. It only shows a site named "undefined" for me, and none of the 4 sites actually on my dashboard.

This is with Lando 3 beta 42 on elementaryOS Loki.

I have tried fully uninstalling Lando, deleting my `~/.lando` folder, and starting over and I run into the same issue.

Might there be something I'm missing, or is this a bug?

**Comment by pirog** [comment]
@bmcclure already fixed in dev and will be in beta.43
