### ISSUE TITLE
Bug Report: Verbose arguments don't seem to work correctly

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#938]
Lando from source dfb7b0a0bdd84fa65ccf4cb986642a778ff1ef1a beta 43
Linux (ubuntu 17.10)
node 8.11.1

Command:
```bash
lando -vvvv info
```
Expected: 
List of sites with verbose output

Actual:
Help text with no verbose output.

**Comment by dustinleblanc** [comment]
@neclimdul you need to run `lando command -- -vvv` to get global args to work. See https://docs.devwithlando.io/cli/usage.html
