### ISSUE TITLE
error: Cloning into '.'... from pantheon

### ISSUE THREAD

**Issue by irixzafra** [lando/lando#943]
Steps i´m following are:

1.- Lando init pantheon
2.- Choose my "email" Pantheon account
3.- Select "my_site"

Then get this error:

landoinitesaem_util_1 is up-to-date
Scanning /user/.ssh for keys...
Scanning /lando/keys for keys...
Checking whether /user/.ssh/known_hosts2 is a private key...
Checking whether /lando/keys/pantheon.lando.id_rsa is a private key...
Checking whether /lando/keys/pantheon.lando.id_rsa is formatted correctly...
Ensuring permissions for /lando/keys/pantheon.lando.id_rsa...
Using the following keys: /lando/keys/pantheon.lando.id_rsa
landoinitesaem_util_1 is up-to-date
Cloning into '.'...
ssh: Could not resolve hostname codeserver.dev.6.drush.in: Name or service not known
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: Cloning into '.'...
ssh: Could not resolve hostname codeserver.dev.6.drush.in: Name or service not known
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by AcriCAA** [comment]
I think this is related to my issue: 
https://github.com/lando/lando/issues/942

**Comment by artiswilliams** [comment]
I'm experiencing this issue also.

**Comment by artiswilliams** [comment]
I ran the 'git clone' command from my pantheon dashbaord first...then ran lando init pantheon to avoid this error.

**Comment by smutek** [comment]
Check the id parameter in your `.lando.yml` file.

I just upgraded to 3.0.0-beta.43, I followed the recommendation to remove Lando and reinstall from scratch.  When reinitializing my environment with `lando init --recipe=pantheon` I noticed Lando changed the site id parameter in my `.lando.yml` file to 0.
