### ISSUE TITLE
Lando doesn't work when you are logged into Dockers

### ISSUE THREAD

**Issue by heshanlk** [lando/lando#944]
Lando start doesn't work when you are logged into the Dockers, throwing following and when I logged out from Dockers it works perfectly fine.

```
$ lando start
Creating network "landocasetupkenobi38ahsokaddeb0c729e09867718b28c885a23cf91b8d47a2a_default" with the default driver
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
Creating network "landocasetupkenobi38ahsokaddeb0c729e09867718b28c885a23cf91b8d47a2a_default" with the default driver
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
^CCreating network "landocasetupkenobi38ahsokaddeb0c729e09867718b28c885a23cf91b8d47a2a_default" with the default driver
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password

```

**Comment by dustinleblanc** [comment]
@heshanlk Can you elaborate? What is being logged into the dockers?

**Comment by dustinleblanc** [comment]
I'm currently logged in to docker hub, I am able to pull containers. There must be another factor causing the issue

**Comment by Etroid** [comment]
Experienced the same issue when setting up Lando on a coworker's computers. It was resolved when we signed out of Docker for mac before running `lando start`

**Comment by dustinleblanc** [comment]
Are you all logging into the main docker hub? Quay instead? Any kind of corporate accounts that might be locking down your docker access?

Out of curiosity, for any experiencing this, are you able to do a vanilla `docker pull nginx` or anything like that?

**Comment by jstramel** [comment]
I had this same issue until I logged out of Docker after which `lando start` proceeded properly.

**Comment by Etroid** [comment]
@dustinleblanc Main docker hub, and my account is not linked to a corporate account so no restrictions apply.

I tried `docker pull nginx` and was able to do so successfully

**Comment by dustinleblanc** [comment]
I've reopened the issue, but I still can't reproduce

**Comment by vijaycs85** [comment]
I face the same problem described above: `lamdo start` throws below error until logout from docker on mac
```
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
```

**Comment by doostinharrell** [comment]
I can also confirm that this is an issue on my mac as well.

**Comment by aproxit** [comment]
I too can confirm this is an issue on Windows 10 running beta.47 of Lando and Docker Version 18.03.1-ce-win65 (17513)

**Comment by alejomc** [comment]
subscribed!, same to me have had to sign off. 

confirmed.

- v3.0.0-beta.47
- Docker: 18.03.1-ce-mac65 (24312)
- macOS High Sierra: 10.13.3

**Comment by paul-mckibben** [comment]
Confirmed it happens to me too. Same specs as alejomc. Fresh install of Lando (brand new MacBook Pro).

**Comment by shaundrong** [comment]
confirmed had to sign off to download images
- Lando: v3.0.0-rc.1
- Docker: Version 18.06.1-ce-win73 (19507)
- Windows 10: Version 1803(OS Build 17134.345)

**Comment by dustinleblanc** [comment]
@pirog I am beginning to think this has something to do with org access to the Lando org. Since it doesn't happen to me, perhaps this is because I am a member of the lando org on dockerhub an the way we call the images? Perhaps we can do something else to how we specify the image names or configure docker hub to alleviate this for people. It's a weird issue

**Comment by pirog** [comment]
interesting @dustinleblanc, maybe i'll spin up a bogus account and see if i can replicate

**Comment by d3vit** [comment]
I was also able to replicate. **The fix is simply to log out of Docker.**

**Docker**: 2.0.0.0-win78
**Engine**: 18.09.0

**Lando**: v3.0.0-rc.1

Looks like it has trouble, when logged in, trying to generate the CA cert. Once I logged out it guided me through the prompt (I have a new install) and Docker asked my to provide access to my C: drive, network access, etc.

I haven't tested yet but this may be due to needing permissions on a fresh install for docker to access your storage and network.

**Comment by ubershmekel** [comment]
Same. `docker logout` fixes the following error I got:

```
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
Pulling ca (devwithlando/util:stable)...
ERROR: Get https://registry-1.docker.io/v2/devwithlando/util/manifests/stable: unauthorized: incorrect username or password
error: Failed after 5 retries with backoff 500 and error Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at dc (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at compose (/snapshot/lando/build/cli/plugins/lando-engine/engine.js:0:0)
    at exports.start.datum (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/plugins/lando-engine/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
```

**Comment by rabauss** [comment]
I also had some problems if I was logged in.
Then I realized that error only appeared, if I used my mailadress for login.
If I login with username everything is fine.

But I think it's a docker issue - because I also had problems with native docker-compose while logged in with email!

**Comment by pirog** [comment]
i definitely believe there is something funky happening here and im not totally convinced its just a Docker problem. 

That said i cannot replicate.
