### ISSUE TITLE
Dashes removed from site name

### ISSUE THREAD

**Issue by ataylorme** [lando/lando#946]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

Lando version `v3.0.0-beta.44` on High Sierra `10.13.4`

**Tell us about your `.lando.yml`**

```yml
name: wp-clean
recipe: wordpress
config:
  webroot: .
  php: 7.1
  via: nginx
  database: mariadb
  xdebug: true
```

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

Visiting the site URL redirects me to a `404` with no helpful information.  

Turns out newer versions (not sure when it started) of Lando strip dashes from the site name, which is used to determine the URL. I had my site URL in WordPress set to the previous version, what is set in `lando.yml`, that included a dash. This caused a redirect to the version with the dash, resulting in the `404`.

To resolve I had to run a wp-cli search and replace on the database to correct the URLs to the version without a dash.

I just wanted to document this in case it happens to anyone else.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Maybe. A changelog would be great. Not being aware that the change happened made it easy to miss.

Does this bug prevent you from using Lando?

No way, Lando rocks.

**Comment by dustinleblanc** [comment]
Thanks for the report @ataylorme! You are definitely right. We do have a changelog [here](https://docs.devwithlando.io/changelog/2018.html#v300-beta40---april-8-2018) that also reflects what goes in the release notes on Github, but it can be easy to miss. Glad to see you using Lando! Let us know if you see any other Pantheon and/or WP improvements we can make! We'd love to have you as a regular member of our slack org.

**Comment by ataylorme** [comment]
Thanks for the changelog, I did miss it before. I guess my complaint was that [forcing Kebab case](https://github.com/lando/lando/blob/master/plugins/lando-init/tasks/init.js#L70) broke existing Lando instances with a dash in the name. I understand it was done to fix non-URL-friendly names after reading the other issues but a dash is valid so I wasn't expecting it to be stripped.

I'll look at joining Slack but have actually been trying to cut Slack channels as I have about a dozen.

**Comment by dustinleblanc** [comment]
Understood. This definitely was a breaking change for existing lando sites. Once we hit 3.0, we shouldn't have any more of those.

**Comment by osopolar** [comment]
Will dashes come back for use in APPSERVER URLS?
_(related issue: #896)_

**Comment by osopolar** [comment]
No problem, the solution to get the dashes back is to explicitly define a proxy:
```yml
proxy:
  appserver:
    - my-app.lndo.site
```

**Comment by dustinleblanc** [comment]
@osopolar cool hack!
