### ISSUE TITLE
Update Pantheon API node client to use current endpoints

### ISSUE THREAD

**Issue by pirog** [lando/lando#953]
Per @craychee we've definitely got to update our Pantheon API node client to hit the "non-legacy" endpoints ASAP so she can kill the legacy endpoint via :fire:

Currently we are using `/users/ID/sites` and we need to switch to `/users/ID/memberships/sites`.

I'm *guessing* this will resolve the current data structure diff between `/users/ID/sites` and `/users/ID/memberships/organizations`. It's also likely the reason we had some pain because `/users/ID/sites` has been deprecated for... wait for it... years. :/

**Comment by pirog** [comment]
@craychee even after we switch this over it's probable a good idea to keep the legacy endpoint around until we reach some TBD threshold percentage of Lando users.

**Comment by craychee** [comment]
Thank you @pirog. I will take my cue from you.

**Comment by pirog** [comment]
@craychee pinged you some more deetz in the electromail but wanted to at least get this issue spin up first!

**Comment by pirog** [comment]
ok @craychee i've updated the legacy user's site endpoint to `/users/ID/memberships/sites`. I've also set up a monthly recurring event to check in on our usage metrics. Based on previous version update behavior im guessing we are looking at a potential deprecation timeline of 4-6 months.
