### ISSUE TITLE
/bin/sh: 1: [command]: not found

### ISSUE THREAD

**Issue by cooperate** [lando/lando#963]
Bug Report
==========

**Tell us about your setup**

Lando v3.0.0-beta.44
Windows 10 Professional Version 10.0.16299 Build 16299

After spinning up any project with lando I get this error when attempting to use the relative command:

`/bin/sh: 1: [command]: not found`

Even if said command is properly stipulated in the yaml file.  Is there something particular to the Window's version that needs to be changed?

**Comment by sleepingmonk** [comment]
`lando ssh`
Then attempting to run the bash script inside the container yields the same result.

**Comment by dustinleblanc** [comment]
Hi @cooperate can you share your `.lando.yml` file and what command you are attempting to run?

This can happen if your build steps fail, causing the rest of lando's scripts to not properly run.

**Comment by cooperate** [comment]
Relevant error building lando projects on Windows 10
Version	10.0.17134 Build 17134
.......+++
e is 65537 (0x10001)
/certs/lando.pem not found... generating one
CA generated at /certs/lando.pem
ERROR: No such service: /bin/sh
ERROR: No such service: /bin/sh
ERROR: No such service: /bin/sh
ERROR: No such service: /bin/sh
ERROR: No such service: /bin/sh
warn: Something is wrong with the proxy! {}
warn: Trying to take corrective action...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done

This is after clearing user data for lando/docker in windows, resetting docker to factory settings and rebuilding lando project.

**Comment by dustinleblanc** [comment]
Hey @cooperate that looks like #878 in this case
