### ISSUE TITLE
Xdebug not connecting, unable to override default values 

### ISSUE THREAD

**Issue by square360-douglas** [lando/lando#964]
Bug Report
==========
Unable to get xdebug working with PhpStorm on OSX. `remote_enable` is "Off" and attempts to override have no effect

Using a Pantheon recipe for Drupal 8 site.
Lando version: v3.0.0-beta.44 on OSX
```yml
name: ypfs_live
recipe: pantheon
config:
  framework: drupal8
  site: ypfs
  id: xxxxxxxxxxxxxxxxxxxx
  xdebug: true
```
```yml
# pantheon.yml
api_version: 1
php_version: 7.1
````

Site is running fine, but cannot detect xdebug in phpstorm. Phpstorm's debug validator reports that `xdebug.remote_enable` is disabled. This is confirmed in the phpinfo:
```bash
mcmac:ypfs_live dougie$ lando php -i | grep xdebug.remote
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => Off
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => host.docker.internal => localhost
xdebug.remote_log => no value => no value
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
```

## Attempt 2
I try to override the settings adding my own custom xdebug settings
```yml
name: ypfs_live
recipe: pantheon
config:
  framework: drupal8
  site: ypfs
  id: xxxxxxxxxxxxxxxxxxxxx
  xdebug: true
  conf:
    php: xdebug.ini
```
`xdebug.ini` file placed in project directory (beside `lando.yml`)
```php
;...
; Xdebug
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_port = 9000
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.profiler_enable_trigger = 0
xdebug.remote_host = ${LANDO_HOST_IP}
```

Run `lando rebuild`, but the custom settings don't seem to have any effect.

Finally, set xdebug to false in `lando.yml` and rebuild again, but my xdebug config file still has no effect on the detected php settings either through phpstorm or running `lando php -i`

If it's of any use, phpstorm reports the following php.ini files as being parsed (No php.ini was found).
```
Additional .ini files parsed: /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-imap.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-oauth.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-redis.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-soap.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
 /usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
 /usr/local/etc/php/conf.d/xxx-lando-default.ini,
 /usr/local/etc/php/conf.d/zzz-lando-my-custom-ini-file-called-php.ini
```

I'd be grateful for any suggestions.

**Comment by square360-douglas** [comment]
I realise my setup may differ from others, so here are lando urls and the phpstorm server setup.
 
```bash
 NAME           ypfslive
 LOCATION       /Users/dougie/Sites/Lando/ypfs_live
 SERVICES       appserver, nginx, database, cache, edge_ssl, edge, index
 NGINX URLS     https://localhost:32800
                http://localhost:32802
 EDGE URLS      http://localhost:32801
                http://ypfslive.lndo.site:8000
                https://ypfslive.lndo.site
 EDGE_SSL URLS  https://localhost:32799
```

![image](https://user-images.githubusercontent.com/6596055/40122375-0897771a-58fa-11e8-99f4-6751025b333b.png)

![screen shot 2018-05-16 at 11 11 24](https://user-images.githubusercontent.com/6596055/40122393-172c9bac-58fa-11e8-89fc-0c924a2db5c4.png)

![screen shot 2018-05-16 at 11 12 00](https://user-images.githubusercontent.com/6596055/40122399-1a143992-58fa-11e8-86e9-6898b32af03f.png)

**Comment by square360-douglas** [comment]
Just realised in the above I am mixing configurations from different recipes (facepalm). Closing

**Comment by f1rf1n** [comment]
@square360-douglas I think I need my face palmed too. How did you mange to get this to work?

**Comment by square360-douglas** [comment]
@f1rf1n I put my values into a custom php config file just as in the very last code example. Watch out using different tutorials or you could end up like me copying excerpts from unrelated examples. It may be quicker starting from scratch.
