### ISSUE TITLE
apache is not working ... not yet ready with code 502.

### ISSUE THREAD

**Issue by anibalsanchez** [lando/lando#968]
Bug Report
==========

**Tell us about your setup**

Lando v3.0.0-beta.44
Docker Version: 17.11.0-ce
Ubuntu 17.10

**Tell us about your `.lando.yml`**

	name: apiplatform

	proxy:
	  html:
		- apiplatform.lndo.site

	services:
	  html:
		type: apache
		webroot: admin

**Tell us about the command you were running**

	lando start

**Tell us about the error you got**

There is something wrong with the apache service. It just doesn't start. If I change apache x nginx, it runs perfectly fine.

	lando start -- -vvvv
	....
	info: Checking to see if http://localhost:32772 is ready.
	verbose: http://localhost:32772 is not accessible
	debug: http://localhost:32772 not accessible with error Error: read ECONNRESET
	info: Checking to see if http://apiplatform.lndo.site is ready.
	info: Checking to see if https://apiplatform.lndo.site is ready.
	debug: http://apiplatform.lndo.site not yet ready with code 502.
	verbose: http://apiplatform.lndo.site is not accessible
	debug: http://apiplatform.lndo.site not accessible with error [object Object]
	debug: https://apiplatform.lndo.site not yet ready with code 502.
	verbose: https://apiplatform.lndo.site is not accessible
	debug: https://apiplatform.lndo.site not accessible with error [object Object]
	debug: URL scan results url=http://localhost:32772, status=false, color=red, url=http://apiplatform.lndo.site, status=false, color=red, url=https://apiplatform.lndo.site, status=false, color=red

**Tell us generally about your bug**

I've reduced the recipe to the minimum and apache service still doesn't work now. At some point, it was working, but now it always fails. Restarting docker doesn't help. No idea what is generating the issue.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

No

Does this bug prevent you from using lando?

No, I'm going to use nginx

**Comment by pirog** [comment]
@anibalsanchez FWIW i just ran our apache example without issue so you might want to see if you can get that rolling as a sanity check.

**Comment by anibalsanchez** [comment]
Yes, the apache example works Ok. However, after several changes, it breaks...

I have two setups with the same recipe, one setup **apache3** works fine and the other one **apache2** does not. Both of them have similar tmp files (~/.lando/compose/apache2-1.yml and ~/.lando/compose/apache3-1.yml). The only difference is the digit 2/3.

The output of apache2 is:

  ...
  info: Checking to see if https://apache2.lndo.site is ready.
  debug: http://apache2.lndo.site not yet ready with code 502.
  verbose: http://apache2.lndo.site is not accessible
  debug: http://apache2.lndo.site not accessible with error [object Object]
  debug: https://apache2.lndo.site not yet ready with code 502.
  verbose: https://apache2.lndo.site is not accessible
  debug: https://apache2.lndo.site not accessible with error [object Object]
  debug: URL scan results url=http://localhost:32822, status=false, color=red, url=http://apache2.lndo.site, status=false, color=red, url=https://apache2.lndo.site, status=false, color=red

Since the recipes are similar... I guess it is a docker issue...

**Comment by anibalsanchez** [comment]
@pirog It seems that the issue is related to memory issues on Docker.

I'm closing the issue and reopening it with more info if I'm able to pinpoint the exact problem.
