### ISSUE TITLE
Feature request: Match Pantheon infrastructure

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#970]
Feel free to tell me I'm way off base with this request.  Can we switch to a Fedora base image for Pantheon since that is the OS they are using?  Also, can we match the php extensions they are enabling/disabling to get a more native local environment experience?  See https://github.com/lando/lando/pull/910#issuecomment-389896941.

**Comment by dustinleblanc** [comment]
Not that this is a bad thing, but we're not likely to make any changes to the images Pantheon recipe unless completely necessary. Not closing, but iceboxing for now

**Comment by pirog** [comment]
@dustinleblanc whoops, i preemptively backlogged this before seeing you had carbonited. Moved back

Doing an audit of the php extensions is a good idea eg seeing what pantheon has for each php version and making sure we have more or less the same as is relevant. 

A Fedora based image will probably never happen but i agree we should be as close as possible on the extensions front. Hard task since they change stuff and we dont have a ton of visibility on those changes eg this is always a reactive exercise on our part. I'd also like to get our build process all figured out for the long term before we add more stuff to the images.

**Comment by uberhacker** [comment]
What is wrong with Fedora?  I would think the operating system is the least of the worries unless you are more familiar with Debian-based than Redhat-based?

**Comment by pirog** [comment]
Nothing is "wrong" with it. I just don't want to introduce another OS that lando maintainers need to know especially if there are no clear benefits in doing so. Almost all our stuff is standardized on debian for a reason: maintainability.

**Comment by uberhacker** [comment]
Well I understand Debian is easier to maintain but I would think in this one instance, Pantheon could be the exception.  The operating system is the most fundamental foundation when trying to match the infrastructure.

**Comment by uberhacker** [comment]
I understand completely that you want to standardize but we both know Pantheon will always be the bastard child that needs special attention.  The php config is only one aspect.  There are so many variables that go into configuring an entire operating system to run a full stack and the subtle differences between the base systems can be significant when you look at everything as a whole.

**Comment by pirog** [comment]
yeah they "can" be significant but in this instance they aren't. 

in 5 years of running "pantheon-esque" docker images on debian i haven't seen a single issue reported that was due to fedora being used on pantheon and debian being used on kalabox/lando.

**Comment by uberhacker** [comment]
Maybe this issue is the first? ;)

**Comment by pirog** [comment]
Doesn't look like it to me

**Comment by uberhacker** [comment]
See https://github.com/lando/lando/pull/910#issuecomment-389896941.  The php configuration is "significant".

**Comment by pirog** [comment]
There is nothing there that is going to matter in any real way between debian and fedora.

**Comment by uberhacker** [comment]
With a static build maybe but when you start using shared libraries the subtle differences can be significant.  I have run into some very strange things and weird behavior with the "same" configurations on different operating systems.

**Comment by uberhacker** [comment]
Copied from #910.

Based on what phpinfo() reported, I didn't see the extra extensions and since they didn't appear in the configure line or in the loaded extensions, I couldn't see if they were actually loaded.  Here is a vimdiff comparison of the php 7.0 loaded modules (Lando - left vs Pantheon - right):
```
    3 apcu           │    3 apcu          
                     │    4 apm           
    5 bcmath         │    6 bcmath        
    6 bz2            │    7 bz2           
    7 calendar       │    8 calendar      
    8 Core           │    9 Core          
    9 ctype          │   10 ctype         
   13 exif           │   14 exif          
   14 fileinfo       │   15 fileinfo      
   15 filter         │   16 filter        
   16 ftp            │   17 ftp           
   17 gd             │   18 gd            
   18 gettext        │   19 gettext       
                     │   20 gmp           
   19 hash           │   21 hash          
   20 iconv          │   22 iconv         
   21 imagick        │   23 imagick       
   22 imap           │   24 imap          
   23 intl           │
   24 json           │   25 json          
   25 ldap           │   26 ldap          
   26 libxml         │   27 libxml        
   27 mbstring       │   28 mbstring      
   28 mcrypt         │   29 mcrypt        
   29 mysqli         │   30 mysqli        
   30 mysqlnd        │   31 mysqlnd       
   31 OAuth          │   32 OAuth         
                     │   33 odbc          
   32 openssl        │   34 openssl       
   33 pcre           │   35 pcre          
   34 PDO            │   36 PDO           
   35 pdo_mysql      │   37 pdo_mysql     
   36 pdo_pgsql      │   38 pdo_pgsql     
   37 pdo_sqlite     │   39 pdo_sqlite    
                     │   40 pgsql         
   38 Phar           │   41 Phar          
   39 posix          │
   40 readline       │
   41 redis          │   42 redis         
   42 Reflection     │   43 Reflection    
   43 session        │   44 session       
                     │   45 shmop         
   44 SimpleXML      │   46 SimpleXML     
   45 soap           │   47 soap          
                     │   48 sockets       
   46 SPL            │   49 SPL           
   47 sqlite3        │   50 sqlite3       
   48 standard       │   51 standard      
                     │   52 tidy          
   49 tokenizer      │   53 tokenizer     
   50 xdebug         │
                     │   54 wddx          
   51 xml            │   55 xml           
   52 xmlreader      │   56 xmlreader     
   53 xmlwriter      │   57 xmlwriter     
                     │   58 xsl           
   54 Zend           │   59 Zend          
   55 zip            │   60 zip           
   56 zlib           │   61 zlib          
```
As you can see, more work is still needed to match the environments.

**Comment by Quevin** [comment]
not having "52 tidy" is a blocker for me right now. Looking into overriding that in .lando.yml, as mentioned in https://github.com/lando/lando/issues/740.

**Comment by pirog** [comment]
Go away stale bot!
