### ISSUE TITLE
lando start hangs with no information.

### ISSUE THREAD

**Issue by generalredneck** [lando/lando#979]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?
v3.0.0-beta.45
Ubuntu 18.04 LTS
Docker version 18.03.1-ce, build 9ee9f40

This happens on any lando instance... even brand new lando init generated pantheon recepies

**Tell us about the command you were running**

`lando start` sits there an just hangs. no additional information using `lando start -vvvv`. running `lando rebuild` gives me the following output and then hangs the same way

```? Are you sure you want to rebuild? Yes
Pulling database (mariadb:10.0)...
Pulling cache (redis:2.8)...
Pulling index (devwithlando/pantheon-index:3.6-3)...
Pulling appserver (devwithlando/pantheon-appserver:5.6)...
Pulling nginx (nginx:1.8)...
Pulling edge (eeacms/varnish:4.1-3.0)...
Pulling edge_ssl (nginx:1.13)...
Pulling node (node:8.4)...
database uses an image, skipping
cache uses an image, skipping
index uses an image, skipping
appserver uses an image, skipping
nginx uses an image, skipping
edge uses an image, skipping
edge_ssl uses an image, skipping
node uses an image, skipping
```

Was working last week even after the upgrade. removed ~/.lando. uninstalled docker and lando. ran `docker rm $(docker ps -aq)` and `docker rmi $(docker images -q)` and then tried again and same output. Downgrading versions of lando provide the same thing. 

Looking into what I did this weekend that could possibly make this happen .

**Comment by generalredneck** [comment]
Ok so WHILE I was writing the post for this, I had some insight. I had installed `unifi` for some access points over the weekend. This program nails down a couple of ports 8080 and 8443... AS soon as as I did an `apt remove unifi` the hanging lando start instance kicked into action...

Any way we can do some error detection around this area to ensure that `lando start` isn't failing?

**Comment by pirog** [comment]
@generalredneck this sounds eerily familiar to an issue @paul94010 was having that i've never been able to replicate but this definitely helps. did you do anything special to `unifi` or just the base install?

totally +1 on adding error detection just haven't known what to detect until now ;)

**Comment by pirog** [comment]
@paul94010 yeah now that im connecting the dots with your experience and what @generalredneck is reporting my *best guess* is that we just have no handling around situations where there are NO available ports for the proxy to use. I'm not exactly sure what we can do about that but at the very least we should throw a warning and not hang the whole process!

**Comment by pirog** [comment]
Hmmm first attempt to replicate this failed :( Looks like Lando WILL throw an error if there are no ports available. Going to try to install `unifi` and see if i can replicate that way

**Comment by pirog** [comment]
@generalredneck installed `unifi` but still wasn't able to replicate. Definitely feel like we are narrowing things down on the cause here but not quite there yet :(

**Comment by generalredneck** [comment]
That's the thing though. For me it happened on every lando file... even on
a  rand new lando init using the pantheon recipe.

**Comment by pirog** [comment]
@generalredneck right! which is why i thought it was more a problem with the proxy than a specific app. that said, i would have expected it to replicate with your `unifi` config and it didnt which is why im still not exactly sure what the issue is

**Comment by paul94010** [comment]
I can confirm that I experience the problem for any lando site that I create with a specific user.   If I change users, I can use lando with no problems.   I have run netstats and still don’t see the process that is causing the problem.  I’ll try to compare the details of processes for both users.

On 23 May 2018, at 7:32 PM, Allan Chappell <notifications@github.com> wrote:

That's the thing though. For me it happened on every lando file... even on
a rand new lando init using the pantheon recipe.

**Comment by pirog** [comment]
@paul94010 that would be super awesome. while i dont think this issue is impacting a large amount of people its definitely something i've personally wanted to try and figure out for QUITE some time.

**Comment by kclarkson** [comment]
@pirog I just updated my OS to Sierra 10.13.5 and now Lando will not complete loading the appserver on lando start. 

I have tried deleting both lando and Docker, lando destroy and rebuild but nothing seems to work. I noticed people saying the ports are busy which causes lando to hang. 

Can you teach me how to tell what is causing lando to hang?

**Comment by paul94010** [comment]
@kclarkson I had the problem when I upgraded to MacOS 10.13.4.   The install process added a "shaddow user"...what the Apple support person called it...to my computer.   Although I was eventually able to delete this duplicate user, I was never able to run lando start again after the upgrade.   I still don't know why, though I have visually examined all the netstat data.   
I did find a work around:   I added a new user with admin role.   Lando has been working fine for me since.   (One exception is that lando pull command is no longer a recognized command in my the latest version of lando.)
I am continuing to work on a root cause of the problem but no answers yet.   I'll post any updates.   I hope you will do the same.

**Comment by kclarkson** [comment]
@paul94010 sorry to report, but my issues were potentially from a firewall that my University had on the internet. As soon as I got to my home the I was able to use spin up lando without any issues. Now that my appservers are set up I will be able to report tomorrow if I can at least develop while on campus.

**Comment by kevinquillen** [comment]
Lando was working for me for the last week, now that I stopped it to work on another project, I came back a few hours later and now the command hangs with no other output.

**Comment by kevinquillen** [comment]
Probably a coincidence, but quitting out of Chrome, Outlook and Slack made Lando come alive again.
