### ISSUE TITLE
Review CircleCI Config

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#983]
I believe we're getting false positives out of CircleCI after running through some of the work for #647 . I think we need to rework the config based on what @serundeputy and @labboy0276 worked out using the Circle Classic setup. 

I have concerns about this working long term because I believe they have plans to sunset that setup, but we also need to make sure circle runs correctly

**Comment by ataylorme** [comment]
> I have concerns about this working long term because I believe they have plans to sunset that setup, but we also need to make sure circle runs correctly

The CircleCI 1.0 sunset is August 31st. See their [announement blog](https://circleci.com/blog/sunsetting-1-0/) for details.

**Comment by dustinleblanc** [comment]
@ataylorme I think that means that the machine executor should still work, right?

**Comment by ataylorme** [comment]
I'm not sure. I would ask in their forums.

**Comment by felicianotech** [comment]
The `machine` executor is a CircleCI 2.0 concept so it will still work after August.

If you all would like any assistance with the 2.0 transition please let me know.

**Comment by dustinleblanc** [comment]
@felicianotech Thanks! We've been using 2.0 for a bit now, unfortunately, I think the remote docker setup fails to run properly with Lando because of volume mounting. Our test suite is giving us near instant passes, and I think it's because the attempts to start up containers are just exiting without a failing code. That is what we seemed to discover working on #647 

I'd love to actually just stick with the docker executor if we can and figure out the volume mounting issue. Short of that, the only thing I am still stuck on (with converting to machine) is that I can't seem to get NVM to cooperate and let me install Node 8.9 using the machine executor.

Any tips on solving either sets of problems would be sweet!
