### ISSUE TITLE
Pantheon + Custom PHP ini file

### ISSUE THREAD

**Issue by chrisroane** [lando/lando#986]
I can't seem to get a custom php ini file to load to overwrite some default settings. I tried several things, but can't get anything to work. I'm using the latest lando version.

**In my lando.yml file:**

```
name: [name]
recipe: pantheon
config:
  framework: drupal
  site: [site]
  id: [id]
  env: dev
  webroot: build
  xdebug: true
  conf: 
    php: lando/php.ini
```

**lando/php.ini file:**

```
[PHP]

;;;;;;;;;;;;;;;
; PHP Globals ;
;;;;;;;;;;;;;;;

short_open_tag = Off
output_buffering = 4096
allow_call_time_pass_reference = Off
variables_order = "GPCS"
request_order = "GP"
register_long_arrays = Off
register_argc_argv = Off
magic_quotes_gpc = Off
enable_dl = Off
allow_url_fopen = On
realpath_cache_size = "800K"
realpath_cache_ttl = "86400"
;include_path = ".:/usr/share/pear:/usr/share/php"

[Date]
date.timezone = "America/New_York"

;;;;;;;;;;;;;;;;;;;;;;
;; PACKAGE SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;

; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.remote_enable = 1
xdebug.remote_autostart = 1

;;;;;;;;;;;;;;;;;;;;;;;
;; PANTHEON SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;;

; Globals
expose_php = on
max_execution_time = 300
max_input_time = 900
max_input_vars = 10000
memory_limit = 1024M
upload_max_filesize = 256M
post_max_size = 256M
error_reporting = E_ALL & ~E_DEPRECATED
ignore_repeated_errors = on
html_errors = on
display_errors = on
display_startup_errors = on
log_errors = on

; Using this to insert essential Pantheon functionality.
;auto_prepend_file = prepend.php

[Opcache]

opcache.revalidate_freq=0
opcache.validate_timestamps=0
opcache.max_accelerated_files=20000
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
```

I tried `lando restart` and `lando rebuild` and it doesn't appear the settings are being applied. Any tips on how I can get this to work?

I'm mainly concerned about getting the memory_limit value to increase to see if that is what is causing our 500 server error.

**Comment by pirog** [comment]
@chrisroane we dont support a custom php.ini for pantheon recipes because we want to lock down and use the same config they do. 

that said you might be able to work around this by overriding the appserver and specifying a custom php.ini file there.'

FWIW i think its highly unlikely the memory_limit is causing a 500

**Comment by pirog** [comment]
@chrisroane FWIW my _intuition_ here is that this is caused by having a massive database and nginx not wanting to wait around for a response

**Comment by chrisroane** [comment]
@pirog I thought that too but I cancelled out those options. I tested using a very small db on the same project (the db we use for tests) and it still occurred. But I think I figured out the problem. I'm going to post on this PR about what I found:
https://github.com/lando/lando/issues/921

**Comment by pirog** [comment]
@chrisroane many thanks. i know we've got an issue queued up to reverse the way we do xdebug eg have it COMPLETELY OFF by default which should at least provide a way to get some easy relief around this issue until we can 100% isolate the issue
