### ISSUE TITLE
Field::collection : thumbnails generation

### ISSUE THREAD

**Issue by jordangidoin** [lando/lando#987]
Hello,

A problem arises with the generation of thumbnails.
When we use the "Field::collection" it is necessary that the thumbnail "_themosis_media" is generated.
Because of this, the thumbnail that will be displayed will be too big (tested with pdf)

Since version 4.7.0 of wordpress it is necessary to implement the filter "fallback_intermediate_image_sizes"

<img width="1233" alt="image.php" src="https://user-images.githubusercontent.com/5417643/40445950-e3a9c3d4-5ecd-11e8-8ee4-6eeeff09f61f.png">

Here is what I added for this to work properly:

```php
function filter_fallback_intermediate_image_sizes( $fallback_sizes, $metadata ) {
    $fallback_sizes[] = '_themosis_media';
    return $fallback_sizes;
};

add_filter( 'fallback_intermediate_image_sizes', 'filter_fallback_intermediate_image_sizes', 10, 2 );
```

What do you think ?

**Comment by pirog** [comment]
@jordangidoin i think that i am unclear about what you expect lando to do about it

**Comment by jordangidoin** [comment]
@pirog  Oupsss I am sorry !

**Comment by dustinleblanc** [comment]
@jordangidoin no worries! Guessing you maybe just posted on the wrong repository? Is this meant for the wp trac or perhaps a theme's issue queue? Going to go ahead and close as this doesn't seem related to Lando, thanks!
