### ISSUE TITLE
Docker "out of space" produces obscure errors

### ISSUE THREAD

**Issue by danielrose28** [lando/lando#989]
### My Lando version and OS:

`v3.0.0-beta.45 on macOS High Sierra 10.13.4`

### My `.lando.yml` file:

```
name: <site>
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: <site>
  id: d6bcf353-3222-4669-99be-c98e2939f199
  xdebug: true
```

My `pantheon.yml` just in case:

```
api_version: 1
php_version: 7.0
```

### My issue and steps used to address it:

I was starting up an older site that I hadn't worked on in a while. I ran `lando start` and the build process would stop after a couple minutes and return this error:

```
error: (HTTP code 500) server error - container beeee7d021b235877f4b6052550df4077ede169a77df2fb1df601f6600ebb4ba is not connected to the network lando_bridge_network
```

I then ran `docker ps -a` to identify this container. In this case it was a `Mariadb:10.0` database container. So then I ran `lando logs -s database` and here is a snippet of the last handful of lines of the log (this was the only thing in the log that I needed to tell me what was wrong):

```
database_1   | Running command docker-entrypoint.sh mysqld
database_1   | Initializing database
database_1   | mkdir: cannot create directory '/var/lib/mysql//mysql': No space left on device
database_1   | Fatal error Can't create database directory '/var/lib/mysql//mysql'
database_1   |
database_1   | The latest information about mysql_install_db is available at
database_1   | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
```

*update*: looking back, I did also run `lando logs` and did see "no space left on device" many times there as well, if that helps as well.

So, since it was telling me there was "no space left on the device", the next best step was to check the docker images to see if there were any old images that could be removed to free up space. For this I ran `docker images` to view the images. If there were older/large images that I could remove I removed with `docker rmi <image id>`. This then freed up some space in order for the device to finish the database build step and start up the app.

**Comment by dustinleblanc** [comment]
Hey @danielrose28!

Thanks for the update there. Based on your findings, it sounds like this was a failure to start the container because the disk ran out of space so I don't think we have a Lando bug to fix. Closing for now, we can reopen if I am off on that.

**Comment by danielrose28** [comment]
@dustinleblanc no worries. @pirog suggested I create an issue to have something to refer to for this type of error. Just wanted to share my findings here. Hope it can help. :)

**Comment by dustinleblanc** [comment]
@seanr I tnink we're at the mercy of what docker and compose themselves throw back. If they have a specific error code/message that we can react to, we can probably improve this, if not, I'd say no, and to pile on them to surface it instead 😆 not sure what the answer on that is

**Comment by pirog** [comment]
@dustinleblanc always appreciate the quick trigger finger to close things out but i think what might be nice here is 

1. Have lando provide some sort of warning when storage is getting low and then ...
2. Link to some sort of doc with consequences/symptoms and steps the user can take to clear out the storage a bit better

The various messages reported by docker/compose when storage is low are very obscure so its not immediately obvious to the user that they have an "out of storage problem"

**Comment by Meghana64** [comment]
![screenshot 21](https://user-images.githubusercontent.com/40695578/42618999-5a44e9e2-85d4-11e8-9ea5-bb02235a41b5.png)
Getting the above output while running the application,
Can u help me out to resolve this plz...

**Comment by serundeputy** [comment]
the way i get around this is:

  1 # Remove unused docker images.
  2 #   For mac remove the '-r' for xargs
  3 #   https://lebkowski.name/docker-volumes/
  4 ```bash
  5 docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
  6 ```

this removes unused images from your machine freeing up some Docker VM space.  as always read the docs before copying a random command from the internet. :)

**Comment by reynoldsalec** [comment]
Note that Docker now has prune commands to get rid of unused images and containers. Highly helpful for this type of scenario: https://docs.docker.com/engine/reference/commandline/container_prune/
