### ISSUE TITLE
Custom domains not fully supported for Pantheon WordPress instances

### ISSUE THREAD

**Issue by richjenks** [lando/lando#991]
v3.0.0-beta.45 on OSX 10.13.4

Followed the steps at https://docs.devwithlando.io/tutorials/offline-dev.html and my site is running locally from a Pantheon WordPress instance.

The problem is that an image whose URL is stored in the database isn't being correctly changed to match the Offline Development URL, i.e. it should be http://wp.local/wp-content/path/to/img.png but it's http://wp.lndo.site/wp-content/path/to/img.png so the image isn't loading in the site. In other words, it's being correctly changed from the remote URL to the local URL but not being changed from the local URL to the _offline_ URL.

There are probably other instances where URLs aren't being correctly changed to their Offline Development URLs but this is the first one I've seen.

The workaround is to add an entry to `/etc/hosts` but given that the recommendation is to use `dnsmasq` (and it might not make sense to run lando as root so it can edit hosts) it makes sense for custom domains to be fully supported.

**Comment by dustinleblanc** [comment]
@richjenks the best workaround is probably the same one used in this case on Pantheon, WP-CLI search-replace:

```yml
events:
  post-db-pull:
    appserver:
      - wp search-replace ://wp.lndo.site ://wp.local
```

I am mostly guessing at the events stuff there as I never use it, but give that concept a try.

Long term, yeah, we want to recognize the local URL based on whatever the proxy domain is set to.

**Comment by richjenks** [comment]
Alternatively, setting up https://docs.devwithlando.io/tutorials/offline-dev.html with the domain `lndo.site` means you don't need to change Lando's config because the default URLs work offline anyway.

**Comment by dustinleblanc** [comment]
@richjenks thats a cool work around!
