### ISSUE TITLE
Allow configuration of name of .env file

### ISSUE THREAD

**Issue by colynb** [lando/lando#994]
As a Lando user, I would like to be able to customize the name of the .env file Lando uses to set environment variables. For instance, instead of automatically looking for `.env`, I can tell Lando to look for `.landoenv` though the lando.yml file.

The reason I'm asking for this is that Lando creates the environment variables when the server boots up rather than at runtime. For example, Laravel uses phpdotenv to load .env files but it does this at runtime which is beneficial for local development. However, the problem is that if Lando loads those env vars at the server level, phpdotenv ignores changes made to your .env. Server level vars take precedence over runtime vars.

The solution to this problem is to just allow the developer to configure Lando to use a different name than .env.

A PR has been created for this https://github.com/lando/lando/pull/974

**Comment by dustinleblanc** [comment]
@colynb thanks! The reasoning here does make this sound more useful, and I can confirm the annoyance of having to restart every time I change an env var with Laravel.

@pirog @serundeputy what say ye? I vote 👍  on allowing this

**Comment by colynb** [comment]
Thanks. I want to think more clearly about the problem. Something isn't sitting right with me. Is it better to rename the file or is it better to just turn off that feature? So far, in my use case, I renamed it so that it doesn't conflict with my laravel .env but is that really what I want? Or would it be better to configure lando to ignore it altogether instead? Would there ever be a reason to have two sets of environment variables, ones for laravel and ones for just lando?

**Comment by pirog** [comment]
I agree we need to make changes here that said i wanted to add a bit more context:

the *purpose* of our `.env` file feature was to allow a `NOT-IN-VERSION-CONTROL` mechanism so users could customize things a bit either on particular machines or environments. 

It's also worth pointing out that `docker-compose` ALSO has an `env` file mechanism that you can touch via Lando's service `overrides`  
https://docs.docker.com/compose/compose-file/#env_file

**Comment by colynb** [comment]
There's an additional problem this issue causes that is a bit of a show stopper for me. That is, because lando is injecting the env vars at the server level, I cannot override them in my phpunit.xml file for doing tests.

**Comment by colynb** [comment]
Instead of having a feature to allow us to rename it, it might be simpler and more desirable to just be able to turn loading env vars off.

**Comment by pirog** [comment]
@colynb yeah i think some combination of all of the above needs to happen. hopefully will get a chance to look at all of that soon and merge something in.

**Comment by dustinleblanc** [comment]
@colynb can you not use phpunit's force feature? https://github.com/sebastianbergmann/phpunit/pull/2723

**Comment by colynb** [comment]
@dustinleblanc I didn't know about the force feature. I tried it and it resolved that particular issue. Thanks for the tip! Here's my phpunit.xml env settings

```
<php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="MAIL_DRIVER" value="array"/>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="sqlite" force="true" />
        <env name="DB_DATABASE" value=":memory:" force="true" />
    </php>
```

**Comment by colynb** [comment]
@kvij I like it even if you just went with the `environment: false` option. That would help a lot.

**Comment by pirog** [comment]
This is addressed as part of https://github.com/lando/lando/pull/974#issuecomment-453836939
