### ISSUE TITLE
Have generated HTTPS certificates match proxyDomain

### ISSUE THREAD

**Issue by dsnopek** [lando/lando#998]
Feature Request
===============

Internally, we've standardized on an alternate proxy domain (ie. not `*.lndo.site`) configured in the `~/.lando/config.yml` like:

```yml
proxyDomain: wizdev.site
```

This works mostly great, except the certificates generated by Lando are for a hard-coded set of domains (including the default `*.lndo.site`).

This isn't a huge deal, because we just add an exception for each one the first time we use it.

But it'd be so cool, if the certificate generation could look at the configured proxy domain, and add that to the list of domains in the certificate.

**Comment by pirog** [comment]
@dsnopek there isn't a day that goes by where i don't regret making `proxyDomain` a configurable thing ;)

**Comment by dustinleblanc** [comment]
@pirog I think it's one of those features that reealllly doesn't matter, yet makes us all feel so good for it's existence (except you 😆 )

**Comment by pirog** [comment]
lol @dustinleblanc, turns out @dsnopek was quite prescient with this feature request because i think we are going to need this soonish for OTHER UNNAMED PROJECTS

**Comment by dsnopek** [comment]
Closed because it's fixed or closed because it's "won't fix"?

**Comment by dsnopek** [comment]
Awesome!! Thanks :-)

**Comment by davideprevosto** [comment]
@dsnopek were you able to certificate a custom domain? Not me.

**Comment by dsnopek** [comment]
Sorry, I haven't tried it yet, I've been battling other issues with v3.0.0-rc.1 so I haven't been able to fully switch to it yet.

**Comment by davideprevosto** [comment]
What kind of issue are you fighting?

**Comment by dsnopek** [comment]
Mainly, #1197. I had some other weirdness, but reverted back to v3.0.0-beta.47 before digging too deep into the other stuff. One thing at a time! :-)

**Comment by davideprevosto** [comment]
Drupal? Can't help. Sorry.
