### ISSUE TITLE
Have a .htaccess-lando that overrides .htaccess

### ISSUE THREAD

**Issue by dsnopek** [lando/lando#999]
Feature Request
===============

We have some customer sites that have `.htaccess` files that are super complex and won't necessarily work in development. Once solution, is trying to modify them so they'll work both live and in Lando, which is possible in same cases (ie. mod_rewrite stuff can look at the current domain and only run if on the production domain) but not all. It's also overall simpler and less likely to break the live site if the development stuff gets its own file.

It would be cool to be able to provide a `.htaccess-lando` file that, when present, overrides the `.htaccess` so we can copy in some variation of the original file which will work in development (so, we're not necessarily throwing away all the production stuff, just removing anything truly problematic).

Apache provides a easy mechanism to do this, basically, this line needs to be added to the configuration:

```
AccessFileName .htaccess-lando .htaccess
```

We're currently adding this via a Lando pre-run script which has:

```bash
# Some Apache customizations.
if [ -e /etc/apache2/apache2.conf ]; then
    if ! grep -e 'AccessFileName .htaccess-lando .htaccess' /etc/apache2/apache2.conf >/dev/null; then
        echo 'AccessFileName .htaccess-lando .htaccess' >> /etc/apache2/apache2.conf
    fi
fi
```

But since this seems like it'd be useful to others, I decided to create this issue to discuss adding this to Lando upstream.

Please let me know what you think!

**Comment by dustinleblanc** [comment]
@dsnopek I've been Nginxing for a while now so I am not super familiar with .htaccess wizardry. Does this kind of thing gracefully behave if one of the files is not present?

**Comment by dsnopek** [comment]
Yep, it just looks for the filenames in order, so first it'll look for a `.htaccess-lando` and use that if it finds it, but if not, it'll look for `.htaccess`, so this change wouldn't change behavior for existing users (unless for some strange reason they had a file laying around called `.htaccess-lando` :-))

**Comment by dustinleblanc** [comment]
I would hope if they had such file that they were intending to use it! lol

**Comment by pirog** [comment]
@dsnopek late to the game on this one but i think this is a great idea. That said, i'm sort of an apache n00b, can you point us to the relevant config we would need to add to make this happen?

**Comment by dsnopek** [comment]
@pirog Just add this line:

```
AccessFileName .htaccess-lando .htaccess
```

To the end of `/etc/apache2/apache2.conf` in all the containers with Apache and... done! :-)

**Comment by dsnopek** [comment]
Awesome, thanks! That's a little more custom junk we can remove from our usage of Lando :-)
